### ISSUE TITLE
Events OnWeaponFired/OnWeaponAmmoChanged

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-issues#1]
An Event when a Weapon is fired, with weapon hash.

**Comment by gamelaster** [comment]
What is the purpose of OnWeaponAmmoChanged?

**Comment by 7Hazard** [comment]
Inside of an OnWeaponFired callback you can check the ammo that is left rather than have an event for it

**Comment by 7Hazard** [comment]
As well as OnWeaponFired, we could maybe have an event that is called before a weapon is fired (OnWeaponFire)

**Comment by DasChaosAT** [comment]
With this title is ment, that one of them would be cool. But a pre and post Event is even cooler.

**Comment by Hardy535** [comment]
A parameter where the bullet hit (Vector3) would also be very nice.

**Comment by gamelaster** [comment]
Isn't this already implemented? I mean `weaponDamage` event on server

**Comment by FabianTerhorst** [comment]
This is about the ammo change and weapon fire not weapon damage related.

**Comment by C0kkie** [comment]
Added in next dev

**Comment by YannBcf** [comment]
Further infos about the api here https://github.com/altmp/cpp-sdk/commit/fa2ae80c0f2ac1aa8da966f547f39f0207b0cd8d
