### ISSUE TITLE
.getAttached bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1000]
**Client/server version**
#4.0-dev17

**Current behavior**
vehicle.getAttached() always return null. On branch release the script works perfectly.

**Expected behavior**
If i have trailer then return good value.

**Steps to reproduce**
alt.log(player.vehicle.getAttached());

**Context (environment)**
-

**Possible solution**
-

**Comment by C0kkie** [comment]
Fixed in upcoming devversion
