### ISSUE TITLE
drawLine native bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1001]
**Client/server version**
#4.0-dev17

**Current behavior**
drawLine native is not working. No error message, it simply doesn't work. On branch release the script works perfectly.

**Expected behavior**
As it works on release branch, it'd be better if it worked on the dev branch. :D

**Steps to reproduce**
game.drawLine(coords.x, coords.y, coords.z, endPos.x, endPos.y, endPos.z, 255, 255, 255, 255);

**Context (environment)**

**Possible solution**

**Comment by FabianTerhorst** [comment]
Duplicate #982
