### ISSUE TITLE
Vehicle RPM should return 0 when engine is off

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1002]
**Client/server version**

`rc/4.0-rc3`

**Current behavior**
alt.Player.local.vehicle.rpm return a value > 0 after the engine has been turned on then off

**Expected behavior**
When the engine is off, it should always return 0

**Steps to reproduce**
- Spawn a vehicle
- alt.log(alt.Player.local.vehicle.rpm) => 0
- Ignite the engine
- alt.log(alt.Player.local.vehicle.rpm) => 0.200
- Shut off the engine
- alt.log(alt.Player.local.vehicle.rpm) => 0.200
- Exit stream range and go back
- alt.log(alt.Player.local.vehicle.rpm) => 0

**Possible solution**
Actually I'm using getIsVehicleEngineRunning to check and return 0 if engine is off

**Comment by gotgameru** [comment]
Same on 5.3 release

**Comment by martonp96** [comment]
This is normal GTA behavior, it is being read directly from the internal vehicle entity.
