### ISSUE TITLE
drawScaleformMovie3dSolid & drawScaleformMovie3d native bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1003]
**Client/server version**
#4.0-rc4

**Current behavior**
drawScaleformMovie3dSolid & drawScaleformMovie3d native is not working. No error message, it simply doesn't work. On branch release the script works perfectly.

**Expected behavior**
As it works on release branch, it'd be better if it worked on the dev branch. :D

**Steps to reproduce**
game.drawScaleformMovie3dSolid(this.scaleform, position.x, position.y, position.z, rotation.x, rotation.y, rotation.z, 2, 2, 1, scale.x, scale.y, scale.z, 2)

**Context (environment)**
-

**Possible solution**
-

**Comment by C0kkie** [comment]
I guess its related to https://github.com/altmp/altv-issues/issues/982

**Comment by Lekenthu** [comment]
Yeah, probably a similar error.
