### ISSUE TITLE
vehicle.setWheelOnFire crash

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1004]
**Client/server version**
#4.0-rc4 and #4.0-dev17

**Current behavior**
I talked with Vektor today, and probably the server side setWheelOnFire is causing crash. It works with the current release version. There are several crashdumps:
https://www.solidfiles.com/v/3dnGNRxnV4jWz
https://www.solidfiles.com/v/MW3r6yeaavrmQ

**Expected behavior**
It should be fixed asap, because i use it in several places on my server.

**Steps to reproduce**
Use setWheelOnFire frequently, and it will crash sometime.

**Comment by FabianTerhorst** [comment]
Use the RC Version. There is a Crash fix inside.

**Comment by Lekenthu** [comment]
> Use the RC Version. There is a Crash fix inside.

I use latest RC version, but it's not working. :/

**Comment by zacbarnaby** [comment]
> > Use the RC Version. There is a Crash fix inside.
> 
> I use latest RC version, but it's not working. :/

I couldn't replicate it, spent 20 minutes setting the vehicles tires on fire, fixing, repeating, tried with multiple cars at once, couldn't get it to crash at all.

**Comment by Lekenthu** [comment]
> > > Use the RC Version. There is a Crash fix inside.
> > 
> > 
> > I use latest RC version, but it's not working. :/
> 
> I couldn't replicate it, spent 20 minutes setting the vehicles tires on fire, fixing, repeating, tried with multiple cars at once, couldn't get it to crash at all.

There maybe a bug in the other wheel functions as well, and this has really been fixed since then.

**Comment by Lekenthu** [comment]
Fresh crashdump: https://anonfiles.com/Vcg7G660u7/altv_4.0-rc4_Social_Club_0x15c5029_15-07-2021_20-45-52_zip

**Comment by FabianTerhorst** [comment]
you have to send it in discord, i cant use that link.

**Comment by Lekenthu** [comment]
> you have to send it in discord, i cant use that link.

Done.

**Comment by C0kkie** [comment]
I think its fixed now, isnt it? @Lekenthu

**Comment by Lekenthu** [comment]
> I think its fixed now, isnt it? @Lekenthu

Yes.
