### ISSUE TITLE
stuttering after recent altv update

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1006]
**Client/server version**

newest release build after rc->release merge

**Current behavior**
people on different servers are reporting very annoying stuttering. see for example here: https://streamable.com/g3bxbv

edit: we dont have any logs spamming the console, just some default logs, but not a lot

**Expected behavior**

no stutter

**Steps to reproduce**

play on a server

**Context (environment)**

it probably has something to do with increasing player or vehicle counts, because while testing we didnt encounter this kind of issue

**Possible solution**

I dont have any.

**Comment by Letsion** [comment]
Version: release 4.0

**Comment by LeonMrBonnie** [comment]
Please provide any information you have about the issue here.
