### ISSUE TITLE
Overlays (e.g. webview and console) flickering

### ISSUE THREAD

**Issue by Xikun201** [altmp/altv-issues#1007]
**Client/server version**
newest release (4.0.0) and current rc (4.0-rc6)

**Current behavior**
Overlays are flickering including console and webview while showing marker with native method "drawMarker".
Has worked before update.

**Expected behavior**
No flickering to be seen

**Steps to reproduce**
example resource (js) in attachement
[resources.zip](https://github.com/altmp/altv-issues/files/6833557/resources.zip)

**Possible solution**
Sadly no idea

**Comment by LeonMrBonnie** [comment]
Use the `drawRect` native with 0 width and height and see if it fixes it

**Comment by Xikun201** [comment]
`drawRect` works fine.
`drawMarker` buggy.

**Comment by Stuyk** [comment]
@Xikun201 You are meant to combine the two.

**Comment by Xikun201** [comment]
Ok sorry I need to write more to explain myself :) Using both also fixes the issue.
But before `drawMarker` was working fine also without the `drawRect` fix.

**Comment by LeonMrBonnie** [comment]
> 
> 
> Ok sorry I need to write more to explain myself :) Using both also fixes the issue.
> But before `drawMarker` was working fine also without the `drawRect` fix.

It was temporarily fixed in rc / dev but that fix was removed for now, because it brought other bigger problems.

**Comment by Xikun201** [comment]
Thanks alot. Sorry for my confusion!!
