### ISSUE TITLE
Client crashes after deleting a destroyed vehicle which plays audio

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1008]
Client/server version:
release

Current behavior:
when playing audio on a vehicle and then deleting it after it got destroyed, the client will crash

Expected behavior:
when destroying the vehicle, the audio should get destroyed too and the client shouldn't crash

Steps to reproduce:
1. Spawn a vehicle with a audio output
2. shoot the vehicle until it explodes
3. delete the vehicle

Possible solution:
No solution at the moment

**Comment by yoranjj** [comment]
https://user-images.githubusercontent.com/17703007/126066274-11be11e7-ca73-428a-8b59-2bc902dfebb9.mp4

Doesn't seem to crash for me on latest release, could you provide more info?

**Comment by Phill030** [comment]
Maybe try to destroy the vehicle in (c#) Serverside because thats what I am doing.

**Comment by C0kkie** [comment]
The crash isnt always and also other users had a crash with that

**Comment by C0kkie** [comment]
Should be fixed in v15
