### ISSUE TITLE
altV UI lagging

### ISSUE THREAD

**Issue by KaVVaski** [altmp/altv-issues#1010]
**Client/server version**
`Build newest (i don't know where I can check it), branch release`

**Current behavior**
UI lagging so much. When the game runs smoothly at over 60FPS, the UI continues to lag, you can almost do nothing. If I press any button I have to press 2x alt + tab and then the UI "refreshes".

**Expected behavior**
UI shouldn't lag

**Steps to reproduce**
https://streamable.com/uy1vv7

**Context (environment)**
can be seen in the video above

**Possible solution**
FiveM introduced a function named "NUI in-process GPU" which has the description "Fix 'UI lag' at high GPU usage, but may cause reliability issues with GPU crashes"

**Comment by ThomasMarangoni** [comment]
Have you tried this fix: https://wiki.altv.mp/wiki/Tutorial:Troubleshoot_Client#Webview_lagging

**Comment by KaVVaski** [comment]
> Have you tried this fix: https://wiki.altv.mp/wiki/Tutorial:Troubleshoot_Client#Webview_lagging

works, thanks
