### ISSUE TITLE
Async raycast stopped working properly

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1011]
**Client/server version**
`Release 4.1` (also is in 4.0-rc5)

**Current behavior**
Asynchronous raycast (startShapeTestLosProbe) doesnt detect anything for most of the time (like if you are raycasting an object on the same pos it returns that raycast was hit only sometimes)

**Expected behavior**
Asynchronous raycast should work the same as the sync raycast (startExpensiveSynchronousShapeTestLosProbe)

**Steps to reproduce**
client script that shows object model on raycast from final rendered cam: 
https://gist.github.com/zziger/c7e6a9bb96db320b56d3b19ab345300c (replace async raycast to sync raycast at line 58, and everything starts to work properly)

**Comment by zziger** [comment]
Complete full ready-to-test resource:
[reproduce.zip](https://github.com/altmp/altv-issues/files/6840246/reproduce.zip)

**Comment by LameuleFR** [comment]
I can confirm it's also buggy on my side

**Comment by FabianTerhorst** [comment]
Seems to work. Feel free to comment when it isnt.

**Comment by Rodhin** [comment]
> Seems to work. Feel free to comment when it isnt.

It works if you have less than or equal to 60 fps. If you have more it won't work properly (sometimes it works, sometimes it isn't) and the more FPS you have the more like it won't work. I've checked it on a 240Hz monitor, limiting the game to 240, 144, 120, 60 and the less FPS I had the more reliable the native was and on 60 it was working every single time. I think it will be an engine bug not an alt:V related one :\

**Comment by zziger** [comment]
> > Seems to work. Feel free to comment when it isnt.
> 
> It works if you have less than or equal to 60 fps. If you have more it won't work properly (sometimes it works, sometimes it isn't) and the more FPS you have the more like it won't work. I've checked it on a 240Hz monitor, limiting the game to 240, 144, 120, 60 and the less FPS I had the more reliable the native was. On 60 it was working every single time. I think it will be an engine bug not an alt:V related one :\

I am *really* sure that this bug started to happen after some alt:V update (not GTA update), because we were using those async raycasts a lot, and noone had any issue with them until the update

**Comment by LameuleFR** [comment]
> > > Seems to work. Feel free to comment when it isnt.
> > 
> > 
> > It works if you have less than or equal to 60 fps. If you have more it won't work properly (sometimes it works, sometimes it isn't) and the more FPS you have the more like it won't work. I've checked it on a 240Hz monitor, limiting the game to 240, 144, 120, 60 and the less FPS I had the more reliable the native was. On 60 it was working every single time. I think it will be an engine bug not an alt:V related one :\
> 
> I am _really_ sure that this bug started to happen after some alt:V update (not GTA update), because we were using those async raycasts a lot, and noone had any issue with them before the update

I can confirm the same behavior on my side, i was using async raycast everywhere before the altV update
