### ISSUE TITLE
Vehicle Dirtlevel in C# as float not byte like javascript

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1012]
**Suggestion**
On javascript the dirtLevel of the vehicle is in float (https://natives.altv.mp/#/0x79D3B596FE44EE8B), on c# it is in byte.
And add the description that dirtlevel ist between 0.0 an 15.0

**Use cases**
Same object type on both languages

**Describe the solution you'd like**
```
        public float DirtLevel
        {
            get
            {
                unsafe
                {
                    CheckIfEntityExists();
                    return Server.Library.Vehicle_GetDirtLevel(NativePointer);
                }
            }
            set
            {
                unsafe
                {
                    CheckIfEntityExists();
                    Server.Library.Vehicle_SetDirtLevel(NativePointer, value);
                }
            }
        }
```

**Describe alternatives you've considered**
Nothing

**Additional context**
Nothing

**Comment by FabianTerhorst** [comment]
Dirt level is internally a byte thats why its in c# a byte. We don't use natives thats why it has different values then used in natives.
