### ISSUE TITLE
Server connection menu is broken on 2372

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1014]
**Client/server version**

`5.0-dev4`

**Current behavior**
After starting a game connection menu gui doesnt show up (cam under the world and the alt:V watermark), and the console doesnt work (F8 does nothing, but if you open a console via CEF debugger - it works)

**Expected behavior**
Everything should work properly

**Steps to reproduce**
Use EGS and start alt:V client
![image](https://user-images.githubusercontent.com/27638710/126451665-afc07100-19e9-4952-9bd3-bf9809be6ba9.png)

**Comment by cuBeUrg** [comment]
Can confirm. I have the same issue.

**Comment by gotgameru** [comment]
same

**Comment by Tekks** [comment]
+1

**Comment by Revyn112** [comment]
can confirm on social club version too,

**Comment by C0kkie** [comment]
Fixed in latest dev
