### ISSUE TITLE
beginScaleformMovieMethodMinimap broken

### ISSUE THREAD

**Issue by Fyers** [altmp/altv-issues#1016]
**Client/server version**
`5.0-dev4`

**Current behavior**
Crashes the game

**Expected behavior**
Should not crash the client and allow scaleformMovieMethods to be called

**Steps to reproduce**
Call `alt.beginScaleformMovieMethodMinimap("SETUP_HEALTH_ARMOUR")`
<img width="301" alt="GTA5_fPJhAQm0EF" src="https://user-images.githubusercontent.com/26491227/126476644-ae13ee8d-8847-42b8-8dac-ab8f7d7530d7.png">

**Comment by C0kkie** [comment]
Fixed in an upcoming dev build
