### ISSUE TITLE
Linux Build vehicle healthdata getter makes problems

### ISSUE THREAD

**Issue by LeCyreaxYT** [altmp/altv-issues#1017]
**Client/server version**
`Build #5.0, branch dev`

**Current behavior**
When you have a Linux Server on AltV are HealthData from Vehicles broke that is the output https://gyazo.com/b6648d0a80505318e877ead025d60c8a

**Expected behavior**
But normally it should look like this. https://gyazo.com/2f46b45f461ef39ac5ffe46ab3024f95 this is on the Linux Build on the windows build is all normal.

**Steps to reproduce**
1. Build a Linux Server
2. Join & Create a Server and try to get HealthData

**Comment by C0kkie** [comment]
Not sure if we will fix this, cuz this method is deprecated for a long time now. I will mark it was "to investigate", but i can't guarantee it that we will fix that

**Comment by LeCyreaxYT** [comment]
I Need this Feature With HealthData With that can i save a destroyed Wheel. And Other things.

**Comment by FabianTerhorst** [comment]
shuold be fixed next version.
