### ISSUE TITLE
Native Call createMissionTrain failed

### ISSUE THREAD

**Issue by DanielSchuech** [altmp/altv-issues#1018]
**Client/server version**

`Build #5.0-dev6, branch development`

**Current behavior**

Gamecrash with the following error:

```
[16:36:12][Error] Native call failed: createMissionTrain
[16:36:12][Error]   Exception offset: 0xFB9D67
[16:36:12][Error]   Exception code: C0000005
[16:36:12][Error]   Error code: 0
```

**Expected behavior**
`createMissionTrain` native can be executed

**Steps to reproduce**
call `createMissionTrain(24, 424.142, -1998.4, 15.227, true`)`

(worked with release version before GTA Update)

**Context (environment)**
Creating a Metro Train.

**Possible solution**
`-`

**Comment by FabianTerhorst** [comment]
do you tried to use different configs then 24? Maybe they changed train stuff when they added the new train mission.

**Comment by DanielSchuech** [comment]
- variations 0 to 23 are working as expected
- variations 24 (metrotrain) is moved to 25
- maybe variation 24 is the new train?
- not important for the GTA Patch released but should we keep the issue open for tracking the new train mission?

**Comment by C0kkie** [comment]
It's a gta thing, just wait until gta fixed it.
