### ISSUE TITLE
Player.Model failed (Game Crash)

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1019]
**Client/server version**
Build #5.0-dev6, branch development

**Current behavior**
Gamecrash when set "player.Model" serverside to "mp_f_freemode_01" or "mp_m_freemode_01" on C# Serverside
`mp_f_freemode_01 (0x9C9EFFD8  / 2627665880 / -1667301416)`
`mp_m_freemode_01 (0x705E61F2 / 1885233650 / 1885233650)`
All other Peds working fine!

**Steps to reproduce**
`
player.Model = 1885233650;
`

**Crash-Dump**
[altv_5.0-dev6_Steam_0x7b044c_21-07-2021_20-15-10.zip](https://github.com/altmp/altv-issues/files/6858023/altv_5.0-dev6_Steam_0x7b044c_21-07-2021_20-15-10.zip)

**Comment by YannBCF** [comment]
It is a GTA crash so it can be literally caused by anything

**Comment by gt4ever1988** [comment]
The error occurs with all users, exactly in the line in which the model is set - tested via breakpoints. If I don't put a model or an NPC everything works.

**Comment by LeonMrBonnie** [comment]
Does the crash also happen if the model is set via JS?
QA tested this and there was no crash using JS.

**Comment by DurtyFree** [comment]
Talked to @gt4ever1988 - issue was caused by some DLC ressource
