### ISSUE TITLE
alt.getGxtEntry returns empty string

### ISSUE THREAD

**Issue by Rodhin** [altmp/altv-issues#1020]
**Client/server version**

`Build #5.0-dev6, branch dev`

**Current behavior**

alt.getGxtEntry returns empty string for every value I've tested.

**Expected behavior**

It should return the correct textLabel for the gxtEntry as native.getLabelText does.

**Steps to reproduce**

Try with these gxtEntries:
eyebrows for barbershop:
```
CC_EYEBRW_1
CC_EYEBRW_2
etc...
```

livery mods for vehicle "elegy":
```
ELEGY1_LIV1
ELEGY1_LIV2
...
ELEGY1_LIV9
```

**Context (environment)**

I was testing the development build, native.getLabelText works properly with the gxtEntries I've provided. The eyebrows gxtEntries are working on latest release branch but I can't test the livery mod entries on release (but they should work I suppose).

**Possible solution**

**Comment by YannBCF** [comment]
note, if you add a gxtText like that
```js
alt.addGxtText('CC_EYEBRW_1', 'test');
console.log(alt.getGxtText('CC_EYEBRW_1'));
```
it works, so the issue is bound to the native gta gxt's

**Comment by LeonMrBonnie** [comment]
This was always like that and is intended behaviour.
