### ISSUE TITLE
Rpg and vehicle-weapons does console err

### ISSUE THREAD

**Issue by delaverdev** [altmp/altv-issues#1021]
**Client/server version**

`Build currently last, branch release`

**Current behavior**

When player use rpg or other 'boom' weapons (vehicles too - buzzard, lazer..) in the moment the rocket takes off server console gives err: 
[Error] StartProjectileEvent  read failed: 336 325

**Expected behavior**

just ignore.

**Steps to reproduce**

just try to shoot from rpg and other 'boom' weapons

**Context (environment)**

it should not be)

**Possible solution**

???

**Comment by C0kkie** [comment]
Fixed in upcoming build

**Comment by Revyn112** [comment]
This error seems to be back on server6.0-dev1

https://img.revyn112.dev/data/RoyalTS_7RjOBp1abq.png

**Comment by FabianTerhorst** [comment]
It only got fixed in Release.
