### ISSUE TITLE
Cars-Drift-Like_crazy

### ISSUE THREAD

**Issue by lizypizy13** [altmp/altv-issues#1022]
**Client/server version**
alt:V build #5.0, branch release
`Build #xxxx, branch x`

**Current behavior**
Right now, most of the cars, at least what we've tested on a RolePlay server "OneRP", it seems like they inherited the new GTA Online feature "Low Grip Tires" and a as a bonus, major performance boost
example: Windsor Drop, fully upgraded, it spins like hell, it's pretty difficult to even get it to go straight normally.
Also tested the Surge, it seems to go pretty normal. My friend has a Toros but since it's not 100% RWD it drives ... okay-ish.
Edit no1: Some people report motorbikes to drift aswell. 

**Expected behavior**

For the vehicles on the server to go drive as usual, of course the rear wheels will still spin, cause it's still GTA, but i could drive it in an immersive way (since it's a roleplay server i'm playing on :) 

**Steps to reproduce**
Just hop into any car and start driving. , i saw the issue was reported on the discord support channel by someone else aswell, but i wouldn't say it's a global AltV Issue. 

**Context (environment)**

Our server restarted after this AltV compatibility update, and players started to report heavy drifting for no reason. 

**Possible solution**

If it is really an AltV issue for the new GTA 5 DLC, i would probably check the wheel enhancement IDs for default.

**Comment by Lekenthu** [comment]
Solved. In the base64 where the veh datas stored, it not worked at all the new update.

**Comment by C0kkie** [comment]
what exactly do you mean @Lekenthu

**Comment by Lekenthu** [comment]
> what exactly do you mean @Lekenthu

setGamestateDataBase64, setHealthDataBase64, setScriptDataBase64, setDamageStatusBase64, setAppearanceDataBase64

**Comment by C0kkie** [comment]
@lizypizy13  is it fixed for you too?
