### ISSUE TITLE
Players enter vehicles Theft-Style

### ISSUE THREAD

**Issue by Tsumiki-Chan** [altmp/altv-issues#1023]
**Client/server version**
`Build #2372, branch release`

**Current behavior**
When entering a vehicle using F, you do so in the good old Grand Theft Auto Style (Pulling players out of vehicle, punching them off motorcycle)

**Expected behavior**
You should enter the nearest, unoccupied seat and not steal the vehicle.

**Steps to reproduce**
- Spawn a vehicle
- Make a player enter the vehicle
- Try to enter the same vehicle using F

**Context (environment)**
Well, the players should not steal eachothers cars.

**Possible solution**
N/A, probably due to tuners update

**Comment by chaosfreak93** [comment]
Same problem here

[https://streamable.com/wjowge](https://streamable.com/wjowge)

**Comment by FabianTerhorst** [comment]
Is this a bug or isnt this now the correct enter style that you also have in singleplayer.

**Comment by Tsumiki-Chan** [comment]
It wasn't like this before, so I guess it's a bug

**Comment by markvela** [comment]
another Proof https://streamable.com/r3xjyh

**Comment by JulianMa** [comment]
Can confirm. Our Users are reporting the same bug:
**Before Update:**
* Press F shorty -> Player sits down on next free seat
* Hold F -> Driver gets kicked out

**After Update**
* Press F shortly -> Driver gets kicked out
* Hold F -> (Not Sure)

**Comment by elBandoler** [comment]
Having the same problem.

When you try to enter, no matter how long the press is, unless someone is entering between your press and you being in the car, you'll be kicking the driver out (if there is any) and take control of the vehicle. Even if you're near the passenger seat, even if you aim at the back seats.
Tested with an Adder and a Sherrif SUV.

**Comment by tastydev** [comment]
We already know the whats causing it it will take some time to resolve cause it´s a game engine change which needs to be reversed.

**Comment by C0kkie** [comment]
Fixed in release/5.2
