### ISSUE TITLE
Hat desync while in vehicle

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1024]
**Client/server version**

`5.1 release`

**Current behavior**
When a player sits into a vehicle, for his client hat disappears from his head, but doesn't for other people

**Expected behavior**
Either hat should not disappear for a client, or it should disappear for all clients (that makes sense, cuz some hats probably can go through the vehicle)

**Steps to reproduce**
1. Wear a hat
2. Sit inside a vehicle with another player watching

**Comment by FabianTerhorst** [comment]
Fixed in next dev version.
