### ISSUE TITLE
Markings on the map or GPS only client-side

### ISSUE THREAD

**Issue by markvela** [altmp/altv-issues#1025]
**Client/server version**

5.1 release

**Current behavior**

If a player who is sitting in your car marks a place on the map, this place is only marked client side for the player. As a driver or passenger, you cannot see the marker on the map.

**Expected behavior**

Before the update, everyone could still see the marker if another person sitting in the car marked a location.

**Steps to reproduce**

Enter a vehicle with 2 people and mark each other's locations.

**Comment by AlteredCarbonate** [comment]
Can confirm - 5.1 release

**Comment by C0kkie** [comment]
Fixed in release/5.2
