### ISSUE TITLE
Implementing vehicle.speed serverside

### ISSUE THREAD

**Issue by AlteredCarbonate** [altmp/altv-issues#1029]
**Suggestion**

Implement, just like clientside, serverside vehicle.speed.

**Use cases**

Calculations based on speed

**Describe the solution you'd like**

Implement, just like clientside, serverside vehicle.speed.

**Describe alternatives you've considered**

Sending events around, that contain a callback

**Additional context**

I might be the only one, requesting it.
But for me, it essential

**Comment by Rodhin** [comment]
This would be a good feature, currently I have to measure the vehicle's position in an interval and calculate it's avg. speed from the distance travelled in that time.

**Comment by AlteredCarbonate** [comment]
Usually that can be done clientside, to take off load of the server.
But in that case, I would need to send events around.

**Comment by YannBCF** [comment]
Be aware that it's often better to offload a calculation to every client than asking the server to do it for every client.

Also, you can make a heart beat system where the client send various data about him to the server periodically, containing it's average speed, this heart beat system can be useful to detect clientside code modification

**Comment by FabianTerhorst** [comment]
We can provide vehicle Velocity Serverside. But speed isnt needed for sync i think. So it wont be available
