### ISSUE TITLE
Overwriting certain ymaps impossible

### ISSUE THREAD

**Issue by rethon82** [altmp/altv-issues#103]
## Expected Behavior
Ymaps should be replacable via alt-v resource.

## Current Behavior
Not all ymaps are replaceable.

## Possible Solution
Some old dlcs provide ymaps with the same names as in the base-game. These ymaps cannot be overwritten.

## Steps to Reproduce

Extract this file "bh1_occl_05.ymap" with openiv and try to replace via resource.

## Context (Environment)

I realize this issue might be relevant for everyone opening interiors, as some occlusions are defined in these files. Without the removal of these files the world outside of some buildungs it glitching.

[bh1_occl_02.zip](https://github.com/altmp/altv/files/3213791/bh1_occl_02.zip)

**Comment by indilo53** [comment]
FiveM solves it by allowing folder^file_name.ext as filename in stream folder for those who pay
so the file is mounted as folder/file_name.ext

Other solution would be to have special entries in config files to remap files manually.

**Comment by indilo53** [comment]
I do not know if there will be use cases for this but eventually remapping files to null can lead to them removed from the streamer

**Comment by C0kkie** [comment]
I dont think its a problem anymore since i overwrote this too on our server in the hast. If it still happens just reopen the issue
