### ISSUE TITLE
.focus() problem

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1030]
**Client/server version**
alt:V build #5.1, branch release

**Current behavior**
Since the new release version (4.0), 2 webviews cannot be in focus at the same time. this causes quite a few problems, eg. if you open chat and the phone at the same time.

**Expected behavior**
It's nice that only the effect of focus is given to the webview, but there can be more then one at a time

**Steps to reproduce**
let view1 = new alt.WebView("http://resource/test1/index.html");
view1.focus();
let view2 = new alt.WebView("http://resource/test2/index.html");
view2.focus(); // RIP view1 focus

**Context (environment)**

**Possible solution**

**Comment by FabianTerhorst** [comment]
Active focus on multiple webviews wasnt posslbe. The correct behavior now is that the Last webview that received Focus is focused now.

**Comment by Lekenthu** [comment]
This is wrong. Because of the current solution many of my systems don't work. The players are complaining that they can't write into the chat when the phone is open. The logical thing is that the input should be enabled on which has the focus.

**Comment by duydang2311** [comment]
Idk if you can focus multiple webviews in the future but for now, maybe using only one single webview for all your pages, then focusing will be under your control (this way seems to require a lot of effort to update all your current systems).
