### ISSUE TITLE
Native IsPlayerFreeAimingAtEntity always return false

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1032]
**Client/server version**
Build #5.1, branch release Windows

**Current behavior**
The Native **isPlayerFreeAimingAtEntity** return allways false - with alt:V 4.1 the native works.

**Steps to reproduce**
I test it with following code - return allways false:
`let ped = native.createPed(1, ped.Model, ped.Position.x, ped.Position.y, ped.Position.z, ped.Rotation, false, false);`
`let isAiming1 = native.isPlayerFreeAimingAtEntity(player.script, ped);`
`let isAiming2 = native.isPlayerFreeAimingAtEntity(player, ped);`

**Comment by LeonMrBonnie** [comment]
Use `native.isPlayerFreeAiming(0)`
