### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by gruperpro93** [altmp/altv-issues#1035]
**Suggestion**: add new parameter - alt.config

**Use cases** alt.config will display the server settings, for example, the maximum number of participants

**Comment by DurtyFree** [comment]
@gruperpro93 Please edit your suggestion to fit our template: https://github.com/altmp/altv-issues/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by LeonMrBonnie** [comment]
Duplicate of #197
