### ISSUE TITLE
vehmods.bin | Tuner DLC | Missing entries for modType 47

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1037]
**Client/server version**

`Build #6.0dev-3, branch dev`

**Current behavior**
If you want to set any modValue on modType 47 via API you didn't get the mod. Nothing happens.

**Expected behavior**
You should get the requested mod.

**Steps to reproduce**

1. Spawn a new vehicle of tuner dlc; e.g. `dominator7`
2. Set modKit for vehicle.
3. Set modValue 1 on modType 47 via API: `vehicle.setMod(47, 1)`
4. Nothing happens - Should change the crossbar above the engine.
5. Using the native way work like it should be: `natives.setVehicleMod(alt.Player.local.vehicle.scriptID, 47, 1, false);`
6. Crossbar above the engine is now changed on local.

**Context (environment)**
For tuning all parts of a vehicle.

**Possible solution**
I've looked into the vehmods.bin and saw that the entries for modType 47 are missing.
So to fix this, the values for modType 47 should add to the followering vehicles:

CALICO
DOMINATOR7
EUROS
FUTO2
GROWLER
PREVION
REMUS
RT3000
TAILGATER2
VECTRE
WARRENER2
YOSEMIT3
ZR350

**Comment by Arochka** [comment]
Can you show a screen of the modification ?

**Comment by DurtyFree** [comment]
Hi, pls use this updated / fixed version of vehmods.bin

https://discord.com/channels/371265202378899476/583109900024938527/869695872278085652
