### ISSUE TITLE
WebView freezes after unmounting react component

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1039]
**Client/server version**

`5.3 release`

**Current behavior**
When we unmount specific components in react (SPA in WebView), the whole WebView just starts to freeze/crash and you can't interact anymore. The specific component had no changes since january and it started to occur after 4.1 release. 

**Expected behavior**

Shouldnt freeze

**Steps to reproduce**

We can't. Other components work perfectly. Our workaround: instead of unmounting we just hide the problematic interfaces. In early alt:V days we had a similar issue too we think, back then we thought it occured when unmounting a component with a running CSS transition, but we can't confirm this.

**Context (environment)**

We are controlling our UI with a React SPA approach. When we load windows, they get mounted into DOM by react, and we unload them by just unmounting them.

**Possible solution**

It definitely has to do something with (probably undocumented) changes to CEF/client logic from 4.0/4.1. We need some kind of error message or exception to see why this is happening, unfortunately there is none.

**Comment by FabianTerhorst** [comment]
Are you sure its because of a freeze or because you need to focus a new webview and the old webview gets unfocused after?

**Comment by eiksch** [comment]
Because our voice communication runs over WebView too, we see that the whole WebView crashes/freezes because players are dropping from voice too. Other keybinds are not working too and other windows are not opening aswell, so we can say that the whole WebView crashes. We see the old visuals, thats why we initially thought it just "freezes".

**Comment by martonp96** [comment]
@eiksch is it still happening on latest release?
