### ISSUE TITLE
Discord overlay incompatible with alt:v

### ISSUE THREAD

**Issue by Road-Train** [altmp/altv-issues#1040]
**Client/server version**

`Build #unsure, branch release (it's version 5.3 if that helps...)`

**Current behavior**
Discord overlay doesn't show a mouse whilst the client is loading. Once the client finishes loading, it appears.

**Expected behavior**

My mouse should be visible

**Steps to reproduce**

Open discord overlay whilst alt:v is open, but hasn't finished loading yet.

**Context (environment)**

I was just trying to chat with people in the overlay...

**Possible solution**

If at all possible maybe make the mouse visible whilst the client is loading?

**Comment by deluvas1911** [comment]
Same behaviour if starting GTA5 without alt:V. Loading screen is blocking the mouse input, so this isn't an alt:V issue
