### ISSUE TITLE
Abort button doesn't work when downloading is 0bytes/0bytes

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#1041]
**Client/server version**

`All`

**Current behavior**

Abort button doesn't seem to work in some cases when downloading is 0bytes/0bytes, which is just before download starts or it's stuck for whatever reason, it should be forced.

https://media.discordapp.net/attachments/744981304222679191/870043676586426398/unknown.png

**Comment by C0kkie** [comment]
Duplicate of #645

**Comment by Heryshaf** [comment]
Okay this is a duplicate of: https://github.com/altmp/altv-issues/issues/645
hopefully it can get fixed in a the next light year
