### ISSUE TITLE
alt.Player.local.vehicle.speed returns 0

### ISSUE THREAD

**Issue by Ska11er-DLL** [altmp/altv-issues#1044]
**Client/server version**

`Build #5.3, branch release`

**Current behavior**
alt.Player.local.vehicle.speed returns 0

**Expected behavior**
alt.Player.local.vehicle.speed returns current speed

**Steps to reproduce**
alt.setInterval(() => {
if (alt.Player.local.vehicle && alt.Player.local.seat == 1){
console.log(alt.Player.local.vehicle.speed);
}
});

**Context (environment)**
speed display

**Comment by ThomasMarangoni** [comment]
for all vehicles or specific ones? This should only return speed for vehicles with wheels.

**Comment by Ska11er-DLL** [comment]
> for all vehicles or specific ones? This should only return speed for vehicles with wheels.

a motorcycle like with wheels

**Comment by YannBCF** [comment]
Hello, the vehicle.speed property represents the value on the vehicle dashboard speed gauge, when a vehicle doesn't have a dashboard it returns 0.

To calculate the speed of a vehicle i recommend doing this
```js
import * as alt from 'alt-client';
setInterval(() => {
    const veh = alt.Player.local.vehicle;
    if (veh) {
        const speedVector = veh.speedVector.length;
        console.log(Math.round(((speedVector * 3.6) * 100) / 100));
    }
}, 500); 
```
