### ISSUE TITLE
Make Los Santos map hideable/removable

### ISSUE THREAD

**Issue by MrSalimoc** [altmp/altv-issues#1047]
**Suggestion**
A way to remove Los Santos map completely, get rid of collisions, chunk of map appearing, etc.. (Cayo Perico passively removes it but collisions still remains and some chunk of map still appearing.

**Use cases**
We can use this feature to create our own maps or import already existings maps.

**Describe the solution you'd like**
Make a way (like through `natives` and Cayo Perico Island or requestIpl/removeIpl) to remove LS map and collisions.

**Describe alternatives you've considered**
Actually there's no alternative (except changing client, which i really don't want to do)

**Additional context**
![image](https://user-images.githubusercontent.com/8081840/127749312-8a633bfb-98b9-4db2-8548-c81b02429eee.png)
_A screen showing that we can't make the map fully disappear (collisions and chunk of map still remaining blinking/appearing/disappearing if we're far or near of them)_

**Comment by C0kkie** [comment]
You can do it via modding in v15 now
