### ISSUE TITLE
CopyToClipboard

### ISSUE THREAD

**Issue by zManuu** [altmp/altv-issues#1048]
### Suggestion
Copying text to the client's clipboard

### Use cases
It could make the life of developers much easier as you could use the feature to copy positions, rotitions, hashes, etc. to the clipboard and the developers don't have to copy them by hand.

### Solution
**[ClientSide]** _alt.copyToClipboard(string)_ => void

**Comment by LeonMrBonnie** [comment]
Pretty sure you can already do this by using CEF

**Comment by Stuyk** [comment]
> Pretty sure you can already do this by using CEF

Yes you can.

**Comment by ZackaryH8** [comment]
> Pretty sure you can already do this by using CEF

Possible but should still be added, possibly with a permission flag?

**Comment by zziger** [comment]
Why was that closed, it would be a really nice-to-have feature

**Comment by zziger** [comment]
Sending big amounts of data to webview via event just to copy isn't quite fast, if you e.g. want to copy an image

**Comment by LeonMrBonnie** [comment]
> 
> 
> Why was that closed, it would be a really nice-to-have feature

The issue creator closed it himself. I reopened it.
