### ISSUE TITLE
Client download process can't detect redirection loops (SSL?)

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#1049]
**Client/server version**

`alt:V build #5.3`

**Current behavior**

The client download process can't detect redirection loops when using cdn, for instance if there is a mismatch with SSL forced redirection between htaccess + cloudflare and will be stuck on downloading 0 byte / 0 byte for ever, without the abort button ever getting to work

**Expected behavior**

The client should detect redirection loops probably and abort

**Steps to reproduce**

Force SSL on cloudflare then use

```<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
</IfModule>
```

**Possible solution**

Quit anyway if connection is not possible/download can't start after 20 seconds?

**Comment by C0kkie** [comment]
@Heryshaf  could you try on newest dev?

**Comment by FabianTerhorst** [comment]
Feel free to reopen when the issue still exists. the http client follows redirects since last week.
