### ISSUE TITLE
alt.Vehicle.customPrimaryColor & alt.Vehicle.customSecondaryColor & alt.Vehicle.engineOn 

### ISSUE THREAD

**Issue by SladeGit** [altmp/altv-issues#1050]
**Client/server version**
Build #6.0-dev5, branch dev

**Current behavior**
Error: Failed to convert value to boolean
&
Error: Failed to convert value to RGBA

**Expected behavior**
A car should spawn with the color and engine on

**Steps to reproduce**
Snippet:
const teamData = {
    aztecas: {
        name: 'assholes',
        colors: {
            rgb: { r: 0, g: 255, b: 255 },
            hex: '#00FFFF'
        },
        shape: {
            nameType: 'vehicleSpawner'
        },
        coordinates: {
            vehicleSpawn: { x: 144.7516, y: -1287.6263, z: 29.3304 },
            vehicleSpawnRot: { x: -0.0156, y: 0.0000, z: -2.5781 },
        }

    },

function handleFunctionsSpawnFromSpawner(player, vehicleToSpawn) {
    let currentColShape = player.getMeta('currentColshape');
    if (currentColShape !== null) {
        if (currentColShape.nameType === 'vehicleSpawner' && currentColShape.team === player.getMeta('team')) {
            let currentTeam = teamData[currentColShape.team];
            spawnVehicle(
                vehicleToSpawn,
                currentTeam.coordinates.vehicleSpawn,
                currentTeam.coordinates.vehicleSpawnRot,
                currentColShape.team.toUpperCase(),
                currentTeam.colors.rgb,
                false,
                player
            );
        }
    }
}

function spawnVehicle(name, pos, rot, text, color, player) {
    let newVehicle = undefined;
        newVehicle = new alt.Vehicle(name, pos.x, pos.y, pos.z, rot.x, rot.y, rot.z);
    if (newVehicle !== undefined) {
        newVehicle.customPrimaryColor = { r: colors.r, g: colors.g, b: colors.b };
        newVehicle.customSecondaryColor = { r: color.r, g: color.g, b: color.b };
        newVehicle.engineOn = 1;
    }
    
}
    
**Possible solution**
Everything was fine before the last update

**Comment by deluvas1911** [comment]
Don't see any issue here, just wrong code.
As the error states, engineOn is a boolean, so it requires true/false and not 1.
The colors want an alt.RGBA, but you pass an object without alpha

**Comment by LeonMrBonnie** [comment]
There is no bug here, it is intended behaviour.
