### ISSUE TITLE
CEF: Add option to set CEF zoom level 

### ISSUE THREAD

**Issue by Merec** [altmp/altv-issues#1052]
**Suggestion**
Add the option to use the native CEF browser zoom level for HTML contents

**Use cases**
Operating systems like Windows set a default zoom level for the whole desktop to, for example,150% when using 4k resolutions. The CEF implementaion ignores this value in game, due to the fact that the game is presented in the native pixel resolution, it would be helpful to be able to set zoom level in CEF manually.

**Describe the solution you'd like**
Implement an interface to the native zoomLevel property in CEF
https://cefsharp.github.io/api/63.0.0/html/P_CefSharp_Wpf_ChromiumWebBrowser_ZoomLevel.htm

**Comment by FabianTerhorst** [comment]
Fixed in next release.
