### ISSUE TITLE
CEF: Force specific locale to be used

### ISSUE THREAD

**Issue by Merec** [altmp/altv-issues#1053]
**Suggestion**
Add the option to force use a specific locale in CEF

**Use cases**
When using native HTML5 number or date inputs (`<input type="date|number">`), the current implementation of CEF will render them in EN-US formats only.
Some people from other countries do have problems with these formats and set wrong dates or decimal numbers.

**Describe the solution you'd like**
Add an option to force CEF locale property
https://cefsharp.github.io/api/63.0.0/html/P_CefSharp_CefSettings_Locale.htm

**Additional context**
Using native HTML5 inputs will reduce the overhead on workarounds for parsing numbers and dates in frontend development.

**Comment by FabianTerhorst** [comment]
I just checked. The CefSettings can't be dynamically changed at runtime. And they can't be applied per browser.
The only possibility i see is to use the system locale.

**Comment by FabianTerhorst** [comment]
Next version will be using the system locale.
