### ISSUE TITLE
Node lib requires newer Glibc version and breaks current Dev on Debian <= 10

### ISSUE THREAD

**Issue by pixlcrashr** [altmp/altv-issues#1054]
**Client/server version**

`Build dev/6.0-dev6`

**Current behavior**

Newer Glibc version 2.29 was used to compile the Node lib against, which breaks running Debian 10 system running on `dev` branch.

**Expected behavior**

The Node lib should not be compiled aginst Glibc 2.29 without any announcement.

**Steps to reproduce**

E.g. simply create an altv-server without any resources and the JS module from dev branch on a Debian 10 machine.

**Context (environment)**

Debian 10

**Possible solution**

Compile against an older Glibc version (I guess 2.28 is fine, though). Backwards compatibility should be given up to Debian 9, I suggest.

**Comment by LeonMrBonnie** [comment]
@vadzz-dev 
https://github.com/altmp/alt-node/pull/1 Please merge this PR and run the workflow to create a new release so it is properly built by CI, I will then include the built binaries in the next dev build.

**Comment by LeonMrBonnie** [comment]
Fixed in next dev
