### ISSUE TITLE
Client external console causes false perfomance warnings

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1055]
**Client/server version**
`dev/6.0-dev6`

**Current behavior**
False warnings are displayed in the console
`[Warning] Event handler at <...> was too long 8ms`

**Expected behavior**
These warnings should not be present (since they are not present if you use the f8 console)

**Steps to reproduce**
Using this code, try to unfocus and focus the game window several times
```js
import alt from "alt-client"

alt.on("test-event", (data) => {
  alt.log("test-event data:", data)
})

alt.setInterval(() => alt.emit("test-event", "test data string"), 50)
```

**Comment by LeonMrBonnie** [comment]
Needs better reproduction steps, the external console is unrelated to the speed of the JS code running.
Only possible explanation I can think of is that external console drains your PC resources so it causes lags in general, but this seems to be unlikely

**Comment by xxshady** [comment]
Have you completed the repro steps and there were no warnings in the external console?

**Comment by xxshady** [comment]
Or are you unable to complete them because I have not clearly stated them?

**Comment by LeonMrBonnie** [comment]
I can reproduce, but it happens regardless of external console, when tabbing back into the game.

**Comment by xxshady** [comment]
why regardless of console? when I disable external console there are no warnings
https://user-images.githubusercontent.com/54737754/128377786-840b382d-1c24-447a-8bf5-370a2d8dfaeb.mp4
so the problem on my side?

**Comment by FabianTerhorst** [comment]
The game runs slower when its in background because of the windows scheduler. This has nothing to do with the external console.
