### ISSUE TITLE
tuners dlc clothes sync

### ISSUE THREAD

**Issue by Hutstaender** [altmp/altv-issues#1057]
**Client/server version**

`Build #1181, branch release`

**Current behavior**
All dlc clothes set by setClothes from drawable 362+ are not sync. For other people it looks like you wore random clothes or nothing.

**Expected behavior**
Every new tuner cloth should be synced correctly.

**Steps to reproduce**
just set any drawable from 362+ with setClothes and let someone guess what you are wearing.

**Possible solution**
update clothes binary

**Comment by tastydev** [comment]
confirmed

**Comment by Kingwolfi** [comment]
It looks like that every drawable ID > 127 is out of sync or some internal "overflow"? If i set the drawable ID 127 everything is fine and synced but if i try to set the id=128 i see the corresponding cloth on my own char but everyone else gets the cloth with the id=0 (tested with tops on a woman). The client setter are workign fine with id > 127 including the tuning clothes.

**Comment by FabianTerhorst** [comment]
New clothes are in next release.

**Comment by Kingwolfi** [comment]
yes
