### ISSUE TITLE
getProps for some ids returns wrong drawable id

### ISSUE THREAD

**Issue by RysonTV** [altmp/altv-issues#1058]
**Client/server version**

`Build 5.3, branch: release`

**Current behavior**
serverside function player.getProp for some ids (e.g.: component ID 1 / glasses with number 3,4,5,7...) always returns drawable 0 and texture 0

**Expected behavior**
The function should return correct drawable and texture id after setting it with player.setProp

**Steps to reproduce**
https://pastebin.com/EdD0SeUb

**Context (environment)**
I use this function to build items based on bought clothes in clothesshop.
Currently items can not be created correctly because of wrong returns of getProp function

**Possible solution**
-

**Comment by C0kkie** [comment]
Confirmed on #6.0-dev7

**Comment by FabianTerhorst** [comment]
Fixed in next update.
