### ISSUE TITLE
Add possibility to stream replacement of vehicles.meta vanilla vehicles

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1059]
**Client/server version**

`Build #6.0-dev6, branch dev`

**Current behavior**
It is not possible to replace an existing vehicles.meta of an original vanilla vehicle at the moment.

**Expected behavior**
The vehicles.meta should be replaced by the streamed vehicles.meta

**Steps to reproduce**
1. Add a replacement of an existing vehicle to resources (e.g. https://www.gta5-mods.com/vehicles/police-maverick-replace)
2. Start server and test the vehicle (you should sit as a back passenger like in the swift).

**Context (environment)**
Want to replace default vehicles with modded vehicles (and meta's) which got extended mapping, skins etc. without adding them separetly as addon.

**This behaviour is known for months now, but there was no issue for it.**
Want to bring this issue into dev backlog.

**Possible solution**
Alternative way: Dont replace them and add them as addon.

**Comment by deluvas1911** [comment]
Can confirm that the replacement of vanilla vehicles isn't possible

**Comment by OstriySous** [comment]
Any news about it?

**Comment by C0kkie** [comment]
Works in dev/15.0-dev68
