### ISSUE TITLE
crash client on call gta's native

### ISSUE THREAD

**Issue by bozoweed** [altmp/altv-issues#1065]
**Client/server version**
`Build 5.4, branch release`

**Current behavior**
when i call game.createMissionTrain client crash

**Expected behavior**
that should spawn train

**Steps to reproduce**
var debug = game.createMissionTrain(24,9999,9999,9999 , true);
let carriage = game.getTrainCarriage(debug,1)
game.deleteMissionTrain(carriage)
game.deleteMissionTrain(debug)

**Context (environment)**
all client crash on connection pleas fix it ...

**Possible solution**
no idea

crash log
[20:48:30][Error] Native call failed: createMissionTrain
[20:48:30][Error]   Exception offset: 0xFB918B
[20:48:30][Error]   Exception code: C0000005
[20:48:30][Error]   Error code: 0

**Comment by FabianTerhorst** [comment]
gta added a new train. Variation 24 moved to 25. Use index 25 now.

**Comment by bozoweed** [comment]
okey gona try, wait for

**Comment by bozoweed** [comment]
working fine thanks you alote :)
