### ISSUE TITLE
vehmodels are outdated or broken

### ISSUE THREAD

**Issue by Dixel-exe** [altmp/altv-issues#1066]
**Client/server version**
`Build #2372.2, branch release`

**Current behavior**
The new Tuner DLC vehmodels no longer work since the latest update

**Expected behavior**
Happen that I can spawn the vehicles

**Steps to reproduce**
1. Spawn vehicle of Los Santos Tuners update like: `comet6`
2. Console Output: `[Error] Failed to create vehicle: 2568944644 is not a proper model hash`

**Comment by ThomasMarangoni** [comment]
You can use the vehicle models bin from dev branch, they are still considered unstable, that's why they aren't in release yet.

**Comment by Dixel-exe** [comment]
Okay, then I will use these. Thanks for the quick help
