### ISSUE TITLE
HttpClient request works incorrectly without http://

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1067]
**Client/server version**

Release 5.4

**Current behavior**
Returns status code 0

**Expected behavior**
Return correct status code and send request

**Steps to reproduce**
```
let http = new alt.HttpClient();
alt.log(await http.post("127.0.0.1:8080",anydata));
```

**Context (environment)**
I'm trying to make screenshot and send it through http request

**Possible solution**
Automatically append "http://" at start of address or throw exception

**Comment by FabianTerhorst** [comment]
url verification is out of scope in my opinion.

**Comment by pixlcrashr** [comment]
> url verification is out of scope in my opinion.

Well, I mean at least you could throw an exception as it is an unhandled error and no HTTP status error.

**Comment by FabianTerhorst** [comment]
Urls on next release now must start with https or http otherwise error is printed out.
