### ISSUE TITLE
Server MoveSpeed Getter always 0

### ISSUE THREAD

**Issue by insus100** [altmp/altv-issues#1068]
**Client/server version**
`Server 5.4, branch release`

**Current behavior**
Serverside MoveSpeed getter (C#) always 0

**Expected behavior**
Should show correct MoveSpeed

**Steps to reproduce**
Log MoveSpeed somewhere and move your ped in the server.

**Context (environment)**
Trying to use it to update player synced data in an interval that depends on movespeed.

**Possible solution**
Sync the client movespeed, maybe idk
<img width="959" alt="movespeed" src="https://user-images.githubusercontent.com/37269595/130094931-401eeae5-b92a-4825-96ae-1e565c6c6e1c.png">

**Comment by FabianTerhorst** [comment]
Fixed in next release version.
