### ISSUE TITLE
When players use Chinese or other language input method that will make client crash

### ISSUE THREAD

**Issue by WpyOu** [altmp/altv-issues#1069]
**Client/server version**

Server 5.4, branch release
**Current behavior**

When you use Chinese or other language typewriting (Microsoft input method)，you type one word and client will crash
**Expected behavior**

It won't make client crash and ignore what users input
**Steps to reproduce**

Video there:
[https://player.bilibili.com/player.html?aid=889881297&bvid=BV15P4y1s7UG&cid=392978521&page=1](url)
**Context (environment)**

It won't make client crash and ignore what users input
**Possible solution**

**Comment by ZackaryH8** [comment]
Same as #837
