### ISSUE TITLE
CEF random crashes | GPU process isn't usable

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1070]
**Client/server version**

`Build #6.0-7, branch dev`

**Current behavior**
Sometimes it happens that the CEF crashes randomly.

**Expected behavior**
CEF shouldn't crash.

**Steps to reproduce**
Not really found a reproducable way for this for now.

**Context (environment)**
Added cef.log for further investigation.

**Possible solution**

[cef.log](https://github.com/altmp/altv-issues/files/7023231/cef.log)

**Comment by vadzz-dev** [comment]
Can you upload some crashdumps pls?
