### ISSUE TITLE
the new DLC vehicle bins do not work on release; on C# it works neither on release nor on DEV

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#1071]
**Client/server version**
`6.0-dev7 (dev)` and `release 5.4` 

**Current behavior**
the  new vehicles does not work when spawning them under release (JS) and with C# it does not work under all branches.

**Steps to reproduce**
spawn the Vehicle `comet6`

**Comment by FabianTerhorst** [comment]
Duplicate of #1015

**Comment by Letsion** [comment]
the last binaries were posted on 27th July and is still like that. This issue request that i opened descripes bit more branches with witch languages it is not working. I don't think it is allmost a duplicate

**Comment by deluvas1911** [comment]
@Letsion Please update the original post that you're using the vehicles.bin from #snippets, else it's confusing

**Comment by FabianTerhorst** [comment]
There is No difference between the languages. For Code questions ask on discord.

**Comment by Letsion** [comment]
For me is not working with C# in the Dev version when i spawn the new vehicles  with the binaries of the snippets where the new dlc vehicles are inside. With Javascript it is working i do not know why but it is working on the dev version and on release then again not.
