### ISSUE TITLE
DISABLE_AUTO_WEAPON_SWAP in first person (autoshoot & sound if empty)

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#1072]
**Client/server version**
`Build #5.4, branch release`

**Current behavior**
If you aim and empty the weapon, the char try to shoot autom.
If you release then right mouse click, a sound appears.
[https://www.youtube.com/watch?v=l8l0_3BHexo](url)

**Expected behavior**
No Autoshooting
No Sound after rightclick release

**Steps to reproduce**
1. alt.setConfigFlag("DISABLE_AUTO_WEAPON_SWAP", true);
2. First Person
3. Rightclick
4. shoot empty gun(now he sould try to shoot auto.)
5. wait a few seconds
6. stop right click(now a sound should appear)

**Context (environment)**

**Possible solution**

**Comment by LeonMrBonnie** [comment]
Please follow the issue template.

**Comment by FabianTerhorst** [comment]
fixed in next update.
