### ISSUE TITLE
Initial teleport inside custom interior partly loads the interior

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1074]
**Client/server version**

`Build #6.0-dev8, branch release`

**Current behavior**
When teleport into a custom interior (e.g. Casino Interior Uncle Just) the interior gets partly loaded (missing stairs, railings etc.). After teleport out of the streaming / lod range and back into the interior everythings loads like it should. It could be that the interior loading gets interrupted or didn't work properly when teleport to fast into interior.

**Expected behavior**
Everything should load on first teleport.

**Steps to reproduce**
1. Set Position into Uncle Just Casino Interior 
2. Log Off (save Position to Database)
3. Start Client new and relog
3. 1. On Client Connect Spawn Player on 0 0 72, set Dimension to Int32.MaxValue, Change Model to Rat
3.2. After Login, ClientSide Screen FadeOut, ChangeModel To Freemod Ped, Set Dimension 0 and then Set Database Position, ClientSide Screen FadeIn
4. Walk through Interior and see missing parts
5. Set Position to 0 0 72 and afterwards back to Casino Interior Position, Missing Parts are loaded

Video: https://img.revyn112.dev/data/hK2WSIyvsr.webm

**Context (environment)**

**Possible solution**
Alternative way: first spawn the player and teleport player to 0 0 72, wait for a moment and then teleport the player into the interior.

**Comment by C0kkie** [comment]
I dont think its a problem anymore
