### ISSUE TITLE
VoiceChannel players getter

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1075]
**Suggestion**
I would like to get current players on a voiceChannel

**Use cases**
Planned to create/remove channel on request and would like to check if the channel has no more players to remove it then

**Describe the solution you'd like**
I would like a getter like voiceChannel.GetPlayers()

**Comment by FabianTerhorst** [comment]
when you only need it for length it would be better for performance to e.g. add a isEmpty method.

**Comment by Arochka** [comment]
For my usecase isEmpty or Length would be perfect, but maybe in the future there will be a usecase to get players too ?

**Comment by LeonMrBonnie** [comment]
Added in next dev
