### ISSUE TITLE
Side Mouse buttons are not eligible for voice keybinding

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1076]
**Client/server version**
release #5.4

**Current behavior**
Side Mouse buttons are not eligible for voice keybinding

**Expected behavior**
We should be able to bind side mouse buttons and other specials keys

**Steps to reproduce**
Try to bind side mouse buttons on voice settings client tab

**Comment by EtzBetz** [comment]
Idk what the officials say, but there definitely already is a way to bind those buttons manually if the server provides a shortcut for muting. You can then just bind mouse4 and 5 to that shortcut.

**Comment by C0kkie** [comment]
Will be fixed in dev/14.0-dev13
