### ISSUE TITLE
Streaming weapons.meta for existing weapons is buggy, streaming weaponsanimations.meta for existing weapons doesn't work at all

### ISSUE THREAD

**Issue by insus100** [altmp/altv-issues#1079]
**Client/server version**
`Build 5.4, branch release`

**Current behavior**
When you stream weapons.meta for existing weapons (not addon weapons), settings apply randomly to the defined weapons after each server restart (some weapons will be affected by the weapons.meta config, some don't).

weaponanimations.meta streaming doesn't work at all for existing gta v weapons. It streams fine to addon weapons.

**Expected behavior**
All weapon configs you modified in weapons.meta should be applied, not only some.

Weaponanimations should properly change in gta v existing weapons when a weaponanimations.meta file is streamed for them.

**Steps to reproduce**
Example resource: [weaponsanimations.zip](https://cdn.discordapp.com/attachments/511996079324135424/882227074759270460/weaponsanimations.zip)

**Context (environment)**
I was trying to modify the behaviour of default gta weapons without having to make addons.

**Possible solution**
Using addons, but weapon addons don't have weapon icons in the weapon wheel

**Comment by xxshady** [comment]
@insus100 for modifications of vanilla weapons, use `WEAPONINFO_FILE_PATCH` instead of `WEAPONINFO_FILE`

**Comment by xxshady** [comment]
i guess `WEAPONINFO_FILE` is intended for adding new weapons

**Comment by insus100** [comment]
I've been messing with this again and it's correct, using WEAPONINFO_FILE_PATCH works fine with default weapons.
Weapon animation modding also works fine if done properly. The trick is to get original gta v weaponanimations from update.rpf, place it in your resource and modify all entries for the desired weapon in there.
It will work fine if done as mentioned above so I'll close this.
