### ISSUE TITLE
Allow streaming of hud.gfx and hud.ytd

### ISSUE THREAD

**Issue by insus100** [altmp/altv-issues#1080]
**Suggestion**
Addon weapons are missing an icon in the weapon wheel. Allowing streaming of hud.gfx and hud.ytd so we can add icons to them or use existing ones.

**Use cases**
To add weapon icons for addon weapons.

**Describe the solution you'd like**
Resources should recognize these files and stream them, replacing them in clients.

**Describe alternatives you've considered**
None at the moment, only leaving addon weapons w/o icons

**Additional context**
Example [flamethrower](https://github.com/rjmxtechnology/flamethrower_WildBrick142/tree/master/stream/hud) resource with custom weapon icons for another MP mod.

**Comment by C0kkie** [comment]
Fixed in dev/15.0-dev11
