### ISSUE TITLE
getHeadshotBase64 causing crash

### ISSUE THREAD

**Issue by seelrd** [altmp/altv-issues#1081]
**Client/server version**

`Build #5.4, branch release`

**Current behavior**
`getHeadshotBase64` function causes crash sometimes.
[altv_5.4_EGS_0x179585a51_31-08-2021_21-11-06.zip](https://github.com/altmp/altv-issues/files/7086471/altv_5.4_EGS_0x179585a51_31-08-2021_21-11-06.zip) (reproduced manually)
[altv_5.4_EGS_0xffff80088c600000_31-08-2021_21-32-30.zip](https://github.com/altmp/altv-issues/files/7086472/altv_5.4_EGS_0xffff80088c600000_31-08-2021_21-32-30.zip) (reproduced manually)
[altv_5.4_EGS_0x1a56ff997_30-08-2021_23-32-30.zip](https://github.com/altmp/altv-issues/files/7086484/altv_5.4_EGS_0x1a56ff997_30-08-2021_23-32-30.zip) (most likely caused by this function)
[altv_5.4_Social-Club_0x7fcc01f0028_31-08-2021_22-12-21.zip](https://github.com/altmp/altv-issues/files/7086605/altv_5.4_Social-Club_0x7fcc01f0028_31-08-2021_22-12-21.zip) (caused by this function used once)

**Expected behavior**
The function should not cause crash.

**Steps to reproduce**
```
let id = game.registerPedheadshotTransparent(alt.Player.local.scriptID);
if(game.isPedheadshotValid(id))
{
    alt.getHeadshotBase64(id);
    alt.getHeadshotBase64(id);
}
```

**Context (environment)**
Of course we do not use the function this way as in my example, and that way the function does not cause crash all the time, but the example code is good for causing crash every time. (The example code even causes crash if you wait one second before calling the function again.)

Sometimes it is enough to use `getHeadshotBase64` once to cause crash.

**Possible solution**
I do not know whether the crash reason is the same when using the function too often and when using it only once.

**Comment by C0kkie** [comment]
Fixed in upcoming dev
