### ISSUE TITLE
alt.PedBlip clientside method creates the blip but doesn't attach it to the player

### ISSUE THREAD

**Issue by YannBCF** [altmp/altv-issues#1082]
**Client/server version**
dev/6.0-dev11 (internal build with bindings activated)

**Current behavior**
The blip gets created but doesn't get attached to the player, it doesn't move at all

**Expected behavior**
It should get attached to the player

**Steps to reproduce**
```js
new alt.PedBlip(alt.Player.local);
```

**Comment by FabianTerhorst** [comment]
The PedBlip is working but it needs a index from players counted up by the players in range. E.g. 
```new alt.PedBlip(1);``` creates a blip for the first player in range.
