### ISSUE TITLE
Allow streaming texture dicts from update.rpf/x64/textures

### ISSUE THREAD

**Issue by insus100** [altmp/altv-issues#1083]
**Suggestion**
Similar [issue](https://github.com/altmp/altv-issues/issues/1005)
All these are probably loaded on game start and can't be streamed currently, but would be cool if they can be in the future.
fxdecal.ytd contains blood pools and bullet holes textures.
Some of these ytds are also in x64a.rpf/textures

**Use cases**
Changing textures in those texture dictionaries.

**Describe the solution you'd like**
Create a resource with the texture files and load them ingame for clients.

**Describe alternatives you've considered**
None at the moment

**Additional context**
Example [resource](https://insu.s-ul.eu/3jOnfM7c)

**Comment by C0kkie** [comment]
Works in v15
