### ISSUE TITLE
Slow Clientside-Time (Controllable via Server?)

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1085]
**Suggestion**
Add a Option in _server.cfg_ to set the max Time for Client-Warnings for slow Functions or a option to disable it:
`[21:00:03][Warning] Event handler at skylinev-client:modules/server_keypress.js:96 was too long 6ms`

**Use cases**
Sometimes it is not possible to accelerate the script further, which sometimes causes a message to appear in the client log which confuses the player and also causes the log to fill up. With worse computers this warning leads to even worse performance because this warning has to be written into the text file.

**Describe the solution you'd like**
**server.cfg** 
Add a Option for timeMS to show a Warning `clientWarningMs: 50ms`
Or a Option to disable/enable it `clientWarning: false`

**Comment by LeonMrBonnie** [comment]
Discussed many times before, it is something that will not be added.
