### ISSUE TITLE
Returning false in PlayerDamage event does not work with headshots.

### ISSUE THREAD

**Issue by insus100** [altmp/altv-issues#1086]
**Client/server version**
`Build #5.4, branch release`

**Current behavior**
Check this [video](https://streamable.com/9795km)
As you can see, player takes no damage, but when he is shot in the head they ragdoll (only for the client that shot them in the head)

**Expected behavior**
User should stay up when shot in the head if I return false in PlayerDamage event

**Steps to reproduce**
Make your PlayerEvent event return false and shoot players in the head.

**Context (environment)**
Prevent player  damage.

**Possible solution**
Get player aiming entity, disablePlayerFiring (but you can still land a bullet if you prefire)
Also there's the native setPedSuffersCriticalHits but it does not always work (unreliable), in the video I was using it and you can see it's useless

**Comment by LeonMrBonnie** [comment]
That is intended behaviour, because returning false there just prevents the damage from being synced to other clients.
You can disable headshots by following this [tutorial in the wiki](https://wiki.altv.mp/wiki/Tutorial:Stream_Weapons#Edit_weapons_damages).

**Comment by insus100** [comment]
But if I edit this, then player won't die if they're headshotted, right? They'll have to take multiple headshots to die

**Comment by insus100** [comment]
> That is intended behaviour, because returning false there just prevents the damage from being synced to other clients.
> You can disable headshots by following this [tutorial in the wiki](https://wiki.altv.mp/wiki/Tutorial:Stream_Weapons#Edit_weapons_damages).

I just tested it and player no longer drops dead, but when you want to kill him, it takes more than one shot to the head so headshot is no longer fatal

**Comment by ThomasMarangoni** [comment]
You can create a own damage system with weapon damage event, there you get the bone that got hit:
https://docs.altv.mp/js/api/alt-server.IServerEvent.html#_altmp_altv_types_alt_server_IServerEvent_weaponDamage

**Comment by insus100** [comment]
> You can create a own damage system with weapon damage event, there you get the bone that got hit:
> https://docs.altv.mp/js/api/alt-server.IServerEvent.html#_altmp_altv_types_alt_server_IServerEvent_weaponDamage

okay thanks a lot, will do this.
We've been testing and looks like players still drop dead for the shooter but happens rarely:
[Video1](https://streamable.com/7cjs3c)
[Video2](https://streamable.com/cfei0u)

But I guess we can live with this
