### ISSUE TITLE
ServerCrash on Vehicle/Player damage, while player gets forced from a vehicle / motorcycle

### ISSUE THREAD

**Issue by Myrinia** [altmp/altv-issues#1087]
**Client/server version**
Testet with RC:    Client 6.0-rc5     ,   Server: 6.0-rc5
Testet with DEV:  Client: 6.0-dev12,  Server: 6.0-dev12

Also testet with Nuget Altv.net+Altv.net.Async  6.0.2-rc57 which still let the Server crash.

**Current behavior**
Server crashes if player is on a motorcycle and crashes into a wall and gets forced from the vehicle.

**Expected behavior**
Server should not crash.

**Steps to reproduce**
1.)
```c++ using AltV.Net;
using AltV.Net.Async;
using AltV.Net.Elements.Entities;
using System;
using System.Threading.Tasks;

namespace AltV_AsyncTestResource
{
    public class Main : AsyncResource
    {
        public override void OnStart()
        {
            AltAsync.OnPlayerConnect += OnPlayerConnectTest;
        }

        public override void OnStop()
        {
            return;
        }


        // Test
        private async Task OnPlayerConnectTest(IPlayer player, string reason)
        {
            // Simple spawn the player and wait for each function to finish
            await player.SpawnAsync(new AltV.Net.Data.Position(0, 0, 72)); // Spawn the Player
            await player.SetModelAsync(Alt.Hash("mp_m_freeMode_01"));

            IVehicle vader = await AltAsync.CreateVehicle(AltV.Net.Enums.VehicleModel.Vader, new AltV.Net.Data.Position(10, 10, 73), new AltV.Net.Data.Rotation());
            if (vader.Exists)
            {
                vader.SetEngineOnAsync(true);
            }
        }
    }
}
```
2.) Connect, get on the Vadder and accelerate to high speeds
3.) Crash into something

**Possible solution**
As this is not happening in release version, but only in rc/dev. It most likely is because of recent changes to  
```sh
AltAsync.OnVehicleDamage
AltAsync.OnPlayerDamage
```
To allow for faster reproduction of the Issue, i uploaded RC/dev/release/ with the resource + the VisualStudio Project

Download: https://easyupload.io/ndv23r

**Comment by deluvas1911** [comment]
It’s fixed in the next rc/dev release
