### ISSUE TITLE
Vehicle AttachTo not full synced

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1089]
**Client/server version**
`6.0-rc5 (rc)`

**Current behavior**
As soon as the NetworkOwner is changed, the vehicle is "detached" for the previous and all others and falls down while driving.

**Expected behavior**
The vehicle remains attached to the flatbed

**Steps to reproduce**
[attachToBug.zip](https://github.com/altmp/altv-issues/files/7111760/attachToBug.zip)
At least 2 players needed.

1. player 1 executes the command "/attach" via chat (T-key). This attaches the vehicle to the flatbed
2. player 1 gets into the flatbed -> sync for all ok
3. player 1 gets out of the flatbed -> sync with all ok
4. player 2 gets into the flatbed -> sync only for player 2 ok. No more for the others

As soon as player 2 drives with the flatbed, the vehicle rotates for player 1 as the flatbed drives and is teleported behind.

If now player 1 executes the command "/tp" and is teleported back after 3 seconds, the sync is ok again. (Leaving and re-entering the streamingrange).

**Context (environment)**
Want to attach a vehicle to a flatbed to transport them

**Possible solution**
-

**Comment by deluvas1911** [comment]
bug confirmed

**Comment by Kingwolfi** [comment]
confirmed

**Comment by JulianMa** [comment]
Before the Serverside attachment system, we did the vehicle attaching via natives. We had the exact same issue, when attaching the Vehicle without collisions. After detaching, there was no way of restoring the collisions for other players beside the netOwner. The vehicle then was also falling through the floor for other players.

Is this also happening, when attaching with enabled Collisions?

This might even be a deeper sync issue with vehicle collisions.

**Comment by JulianMa** [comment]
confirmed

**Comment by Doxoh** [comment]
not fixed with current 9.0-rc2 (rc) version

**Comment by C0kkie** [comment]
@Doxoh  test newest dev
