### ISSUE TITLE
Connection queue for full servers

### ISSUE THREAD

**Issue by 7Hazard** [altmp/altv-issues#109]
Wait on a join queue if the server is full

Like this
https://i.imgur.com/eucrkDa.jpg

**Comment by mrgharabaghi** [comment]
An essential feature for servers with hardware limitations.
Please prioritize this issue.

**Comment by mrgharabaghi** [comment]
This feature can be implemented by server developers with `Early Auth`.

**Comment by DurtyFree** [comment]
The possibility to add your own connection queue has been added with Update 9.0, see the docs for more information. https://docs.altv.mp/articles/connection_queue.html

**Comment by FabianTerhorst** [comment]
We still need to implement logic to not reserve slots on connect.

**Comment by FabianTerhorst** [comment]
added in dev/15.0-dev52
