### ISSUE TITLE
Masterlist endless reconnect

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1091]
**Client/server version**

`release`

**Current behavior**
Sometimes the server disconnect from masterlist and never reconnect until restart(and we have to wait something like 60 or 120sec between shutdown and startup)

**Expected behavior**
Reconnect should work without entire server restart

**Context (environment)**
It's pretty anoying in production to restart entire server just to fix that

**Possible solution**
My guess is there is some kind of "antiflood" maybe cloudflare ? So adding a greater retry interval(60 sec or 120sec) when retries count > 10 can maybe fix the issue ?

**Comment by FabianTerhorst** [comment]
Can someone e.g. check with wireshark if the server still send requests to the masterlist server or if that stopped as well.

**Comment by FabianTerhorst** [comment]
announceRetryErrorDelay and announceRetryErrorAttempts will be available on next release.
