### ISSUE TITLE
New Tuners DLC natives

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1092]
**Suggestion**
Adding new DLC natives

**Use cases**
A lot of my players want to use drift mode during their races and _SET_DRIFT_TYRES_ENABLED native can achieve that

**Describe the solution you'd like**
Just implement new natives, especially _SET_DRIFT_TYRES_ENABLED 
They are listed here: 
- https://github.com/alloc8or/gta5-nativedb-data/commit/8aafa68992cbb463e2f56a9619022728a55dd81a
- https://github.com/alloc8or/gta5-nativedb-data/commit/719ffdc8860937a26ee429aa5a548e962e02137b
- https://github.com/alloc8or/gta5-nativedb-data/commit/a5399c86b55022c445879c7b2db9d35fbbfd2c70

**Comment by FabianTerhorst** [comment]
We will make drift mode available as a server setter.

**Comment by FabianTerhorst** [comment]
Drift mode setter is available in next release.

**Comment by FabianTerhorst** [comment]
For new natives we don't have a eta.

**Comment by C0kkie** [comment]
Wont be available in 7.0, maybe on 8.0

**Comment by C0kkie** [comment]
Added in rc/7.0-rc3
