### ISSUE TITLE
Clothes override data on Linux

### ISSUE THREAD

**Issue by nils-kt** [altmp/altv-issues#1093]
**Client/server version**

`Build #6.0-rc5, branch RC`

**Current behavior**
Console spam with:
clothes override data 00000000000000000000111111111010
clothes gta data 00000000000000000000111111111110

**Expected behavior**
Set player clothes/HeadBlendData .

**Steps to reproduce**
I dont know. The problem is only on Linux (tested Debian 10).
On Windows it works fine.

**Context (environment)**
I cant set player properties like HeadBlendData etc.

**Possible solution**

**Comment by FabianTerhorst** [comment]
you setted hair on clientside. You have to do it serverside since hair is a cloth.
