### ISSUE TITLE
playPedAmbientSpeech, playPedAmbientSpeechWithVoiceNative broken

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1094]
**Client/server version**
Release, Current build

**Current behavior**
Doesn't play any ambient speech sound.

**Expected behavior**
Should play dialogue speeches.

**Steps to reproduce**
natives.playPedAmbientSpeechWithVoiceNative( alt.Player.local.scriptID, "GENERIC_INSULT_HIGH", "s_m_y_sheriff_01_white_full_01", "SPEECH_PARAMS_FORCE_SHOUTED", 0 );

**Comment by deluvas1911** [comment]
That native also doesn't works on FiveM with the players ped.

Try this:
```js
const ped = game.createPed(26, alt.hash("s_m_y_cop_01"), alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z, 0, false, false);
game.playPedAmbientSpeechWithVoiceNative(ped, "GENERIC_INSULT_HIGH", "s_m_y_sheriff_01_white_full_01", "SPEECH_PARAMS_FORCE", 0);
```
It's working fine with peds created by the native, tho I can't tell you why and what's the (internal) difference there

**Comment by GVMP** [comment]
Hold on. Did you try to spawn the ped and afterwards try the call the native on the localPlayer again in the same server session?
Maybe some audio bank is missing and as you spawn the cop ped, the audio bank gets loaded from GTA.

**Comment by FabianTerhorst** [comment]
Native is fixed, sync will be added as well.

**Comment by C0kkie** [comment]
playAmbientSpeech will be added in next dev branch update

**Comment by C0kkie** [comment]
Reopend for the serverside setter on 8.0

**Comment by C0kkie** [comment]
Fixed in next dev native & serverside setter

**Comment by mrgharabaghi** [comment]
Why this happening?

https://user-images.githubusercontent.com/40915667/176680456-39256b3e-5796-4ce9-9001-8deac4bbc178.mp4

```js
alt.onClient('startSpeech', (player) => {
    player.playAmbientSpeech(
        'AIMED_AT_BY_PLAYER', // speechName: string
        'SPEECH_PARAMS_FORCE_SHOUTED', // speechParam: string
        alt.hash('MAUDE') // speechDictHash: number
    );
});
```
```
Failed to play ambient speech  AIMED_AT_BY_PLAYER
```
```json
{
  "Name": "MAUDE",
  "Speeches": [
    {
      "Name": "AIMED_AT_BY_PLAYER",
      "Index": 1
    },
    {
      "Name": "AIMED_AT_BY_PLAYER",
      "Index": 2
    },
    {
      "Name": "AIMED_AT_BY_PLAYER",
      "Index": 3
    }
  ]
}
```

**Comment by mrgharabaghi** [comment]
https://github.com/DurtyFree/gta-v-data-dumps/blob/master/speeches.json

**Comment by deluvas1911** [comment]
It happens when you try to play a speech while the character is still speaking

**Comment by mrgharabaghi** [comment]
> It happens when you try to play a speech while the character is still speaking

As you see the speech is over and I press a button to play new one, but `Failed to play ambient speech  AIMED_AT_BY_PLAYER`.
