### ISSUE TITLE
CEF Display bug with 5+ webviews

### ISSUE THREAD

**Issue by n0minal** [altmp/altv-issues#1096]
**Client/server version**
`release`

**Current behavior**
When you create 5 or more webviews in AltV they seem to don't display on the players screen sometimes, but if the player presses ALT + ENTER when they disappear, then they do show up as expected. 

I have recorded an video on the issue, I **strongly recommend** you to turn off the volume on the video because there was an weird noise on the background.

PS: When the game window "flickers" in the video, is the time when I pressed ALT + ENTER and the UI shown up.

Reproduction video:
https://youtu.be/hmScE1hUwH8

Active CEF webviews:
https://i.imgur.com/BSxy2oJ.png

**Expected behavior**
The UI should appear without having to do ALT + ENTER for them to show up, no matter how many CEF webviews are active.

**Steps to reproduce**
1. Create 5 or more basic CEF webviews containing only an HTML with a h1 tag and a button to go to a next webview.
2. Set up all the webviews at the client-side but only show the first one in the beginning.
3. Once the player clicks the button on the webview, make it hide the current webview and show the next one.
4. Repeat the previous steps for all webviews.
5. At some point, one of the webviews won't display on your screen until you hit ALT + ENTER.
6. Sometimes the bug doesn't happen and you have to reconnect throught F8 menu or close and open the game again until the bug happens

**Context (environment)**
My gamemode uses a single webview instance for each page of our user interface (example: authentication, chat, character selection, character creation, etc).

We came from other multiplayer platforms in which we have been developing this gamemode for three years, our UI's always worked without issues in other platform's CEF browsers but we got this bug once we migrated to altv webviews.

**Possible solution**
An workaround as said before is just accomplished by hitting ALT + ENTER, but I can't teach all my players to do it everytime the bug happens because it occurs very frequently and newbiess will give up on it instead of working around it.

**Comment by pixlcrashr** [comment]
> Shouldn't be fixed. Pretty much should just move down to `1` or `2` WebViews max.

Wouldn't this break existing resources with 3+ WebViews?

**Comment by zziger** [comment]
> Shouldn't be fixed. Pretty much should just move down to `1` or `2` WebViews max.

Having multiple webviews is quite helpful even with SPA. For example, first webview can be just normal GUI, second webview can be an overlay webview, third can be used to offload some computation.

**Comment by pixlcrashr** [comment]
> > Shouldn't be fixed. Pretty much should just move down to `1` or `2` WebViews max.
> 
> Having multiple webviews is quite helpful even with SPA. For example, first webview can be just normal GUI, second webview can be an overlay webview, third can be used to offload some computation.

@zziger But note that when using SPAs, there is a notable delay when executing actions. My experience is that preloading all GUIs into multiple WebViews is faster than having one single SPA for GUI-things.

**Comment by n0minal** [comment]
> Shouldn't be fixed. Pretty much should just move down to `1` or `2` WebViews max.

What? What if a server uses multiple resources that uses CEF? I don't see a reason for it not being fixed to be honest

**Comment by FabianTerhorst** [comment]
Test if the bug also happens on dev or rc branch?

**Comment by n0minal** [comment]
> dev or rc branch?

I'll do it tonight and post here if it happens on these branches aswell.

**Comment by n0minal** [comment]
> Test if the bug also happens on dev or rc branch?

Tested right now, happens in both `dev` and `rc` branches aswell.

**Comment by deluvas1911** [comment]
Can confirm the issue with current 6.0-rc6

**Comment by Lekenthu** [comment]
I can confirm. 6.0-rc7

**Comment by Lekenthu** [comment]
If I create more than 2 webview the CEF freezes. (1 alt:V cef, 1 own) Before that it worked with 2 CEFs. 
Here is a video:
https://www.youtube.com/watch?v=g0eO4avEmrU

Inspect: (2 active cef)
https://i.imgur.com/gX9FlWX.png

**Comment by Xantron** [comment]
We have the same problem. Before 4 - 5 webviews, at the moment make it problems with 2 cefs. 
We can not rewrite all systems for this webview problem....

**Comment by Derodin** [comment]
I have the same problem, I use 2 webviews, one for the HUD and one for other things (GUI) and when I open the console and close everything again I can't open anything. can only have 1 webview active?

**Comment by DurtyFree** [comment]
We are working on this issue to be fixed for the upcoming release, keep an eye on our discord update log channels - thanks everyone for reporting issues:)

**Comment by Xantron** [comment]
@deluvas1911 
Webview Problems not only with flickering. Problems with opening f8 console, menus, etc. if you have more then 2 Webviews

**Comment by deluvas1911** [comment]
> @deluvas1911
> Webview Problems not only with flickering. Problems with opening f8 console, menus, etc. if you have more then 2 Webviews. On release version no problems with more then 5+ webviews. On rc & dev some problems.

We have several issues related to CEF in our scope. As DurtyFree mentioned, the issues are worked on to be fixed for the oncoming release

**Comment by DurtyFree** [comment]
Reproduction code for this issue:
```javascript
const wv = [];

for(let i = 1; i < 28; i++)
{
    wv[i] = new alt.WebView(`http://resource/client/index1.html`);
    wv[i].on('load', () => {
        wv[i].emit('repro#1096', i);
    });
}

let ix = 1;
alt.setInterval(() => {
    wv[ix].isVisible = false;
    ix++;
    if(ix > 27) ix = 0;
    wv[ix].isVisible = true;
}, 1000);

// Index.html
<div><p1>Code to reproduce #1096</p1></div>

<script>
    alt.on('repro#1096', idx => {
        document.querySelector('div').style.paddingTop = idx * 15 + 'px';
    });
</script>
```

**Comment by C0kkie** [comment]
@n0minal @Xantron @Derodin @Lekenthu  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

**Comment by Lekenthu** [comment]
> @n0minal @Xantron @Derodin @Lekenthu Should be fixed in rc/6.0-rc12, please report back if its fixed for you

Don't working. :/ CEF is freezes.

**Comment by houhuaming** [comment]
since the problem still exists, please fix it.

**Comment by n0minal** [comment]
> @n0minal @Xantron @Derodin @Lekenthu  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

I'll test the display issue again soon, thank you. 

I have no idea why people seems to be reporting every single CEF problem they found in their gamemode on this issue, I think you guys should open an issue for every single bug you guys do find?

Idk anything about CEF freezing or lagging btw on my gamemode.

**Comment by n0minal** [comment]
> > @n0minal @Xantron @Derodin @Lekenthu Should be fixed in rc/6.0-rc12, please report back if its fixed for you
> 
> Don't working. :/ CEF freezes.

Wouldn't it be better to open an issue for that problem with proper reproduction steps tho?

I think developers won't be able to fix it unless you create a proper issue for that very specific problem friend, I'm not experiencing freezes on my gamemode's CEF BTW.

**Comment by C0kkie** [comment]
@Lekenthu @n0minal  Thats a other issue and there is already one open #1120

**Comment by Xantron** [comment]
> @n0minal @Xantron @Derodin @Lekenthu Should be fixed in rc/6.0-rc12, please report back if its fixed for you

hey, its not fixed :( We test it with rc/6.0-rc14

**Comment by ThomasMarangoni** [comment]
Can you provide minimal reproduction code?

**Comment by Derodin** [comment]
Try: rc/6.0-rc14

All CEF Freeze, this is Random, can't reproduction this problem. If on first connect freeze all or is Random if open a Webview and all Freeze.
3 Webview (HUD, Chat and GUIs)

**Comment by Xantron** [comment]
> Try: rc/6.0-rc14
> 
> All CEF Freeze, this is Random, can't reproduction this problem. If on first connect freeze all or is Random if open a Webview and all Freeze.
> 3 Webview (HUD, Chat and GUIs)

@ThomasMarangoni we have exactly the same problem.... 
we can provide a test server with rc version to see...

**Comment by ThomasMarangoni** [comment]
We need code to reproduce and not a server to test @Xantron

**Comment by n0minal** [comment]
Tested the display issue in rc branch and it's now freezing the whole game UI indeed, even F8 console.

**Comment by chaosfreak93** [comment]
> Tested the display issue in rc branch and it's now freezing the whole game UI indeed, even F8 console.

Can confirm

**Comment by UnskilledFreak** [comment]
I have the exact same issue with 6.0-rc14.
Connecting to the server works fine and the character selection webview gets rendered but after selecting a character, all CEF's will freeze. The game itself and the client side js code works as expected, but all CEF's are either stuck or completely gone. Looking at the task manager the processes for each CEF exists but ideling at 0% CPU usage. The freezing also crashes debugging on port 9222 as well as F8 console and internal altV menu (like getting timeout or other messages).

I was digging down what was causing this and found a way to reproduce at least one of two instances, where all CEF's just freezes:
After my character selection, the webview gets destroyed, but I "forgot" to unregister all events from the webview by using the `.off()` method.

So create a webview, register at least one event with `.on()` method, wait for a bit and then use the `.destroy()` method without calling the `.off()` method before. That way a could always reproduce the freezes.

The second instance is, when the `.focus()` method is not called after the webview creation, but I am not totally sure if that is true. 
For me it looks like there has to be an order to follow:

- instantiate a new webview with `new alt.webview(<url>)`
- call `.focus()`
- register as many events as you want with `.on()`
- unregister ALL events with `.off()`
- call `.unfocus()`
- call `.destroy()`

with that it seems to be working now without any freeze, can someone confirm this please?

Reproduction of the freeze
```js
const wv = new alt.WebView('http://resource/client/index.html');

wv.on('repro_freeze#1096', () => {
    console.log('response');
});

// trigger freeze after 60 seconds
alt.setTimeout(() => {
    wv.destroy();
}, 60000);

// index.html
<div><p1>Code to reproduce #1096 freezes</p1></div>

<script>
window.addEventListener("load", function(event) {
    alt.emit('repro_freeze#1096');
});
</script>
```

**Comment by xxshady** [comment]
@UnskilledFreak cant reproduce it with code that you provided

**Comment by UnskilledFreak** [comment]
@xxshady I can confirm that this does not happen for some ppl.
We tested with 10 players where 7 had no issues at all but the others experienced the freeze.
After restarting altV client like 15 times I had also luck to experience no freeze but after another try it freezed again. So I cant say for sure whats causing this. We never had issues with CEF before 6.0 :S
But still, following the order I mentioned above it works no so thats a workaround at least.

**Comment by Xantron** [comment]
problem persists in dev/7.0-dev3

**Comment by n0minal** [comment]
I can confirm issue was solved in latest `rc` branch, both problems that happened with multiple webviews not showing up or freezing seems to be fixed in rc6.
