### ISSUE TITLE
Add JS BaseObject create and remove events

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1098]
**Suggestion**
Add a single way to delete all server-side alt:V's objects created by gamemode resources.

**Use cases**
Now the only normal way to clear all objects is a complete restart of the server.
When developing a project with a large number of resources (mostly mods), it is tedious to wait until they are all loaded (or not loaded and crash the client) on the server (restart server) and client (reconnect).
With adding baseObject events gamemodes developers will be able to simply delete all the objects they created and simply restart their main resource.

**Describe the solution you'd like**
Add BaseObject events.

**Comment by LeonMrBonnie** [comment]
https://github.com/altmp/v8-helpers/commit/6867952edcaf5935796003c1c6ba1b80b98ec1d0
Implemented

**Comment by xxshady** [comment]
thanks for very fast response

**Comment by xxshady** [comment]
why it was removed? https://github.com/altmp/v8-helpers/commit/3670653662f3ac42d87e93cd40fd260e487c693d

**Comment by LeonMrBonnie** [comment]
> 
> 
> why it was removed? [altmp/v8-helpers@3670653](https://github.com/altmp/v8-helpers/commit/3670653662f3ac42d87e93cd40fd260e487c693d)

The events caused major bugs which can't be fixed without spending a lot of work on it.
Because users can write a wrapper for these themselves, it is not a priority feature.
