### ISSUE TITLE
Add client event playerEnteredVehicle / playerLeftVehicle

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#11]

**Comment by KifKick** [comment]
And playerChangedVehicleSeat

**Comment by Lhoerion** [comment]
Discussion moved to #408

**Comment by FabianTerhorst** [comment]
This is unrelated to #408 because this issue is about Client having None enter Exit Event.

**Comment by Lhoerion** [comment]
How it's unrelated to #408 when it's about server-side & client-side?

**Comment by FabianTerhorst** [comment]
Because clientside doesn't has the normal enter exit events.

**Comment by FabianTerhorst** [comment]
So its a bigger priority then adding some start stop events on top of it.

**Comment by C0kkie** [comment]
Is there any progress on it? I mean events like weaponchanged got added, it would be so usefull instead of manually checking in interval or tick or something like this if player entered the vehicle.

**Comment by martonp96** [comment]
available in dev
