### ISSUE TITLE
Add thread-safe DeleteStreamSyncedMetaDataAsync

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#1100]
**Suggestion**
We have ``SetStreamSyncedMetaData `` and the thread-safe equivalent ``SetStreamSyncedMetaDataAsync``.

However, we only have ``DeleteStreamSyncedMetaData`` on server-side C# as of right now, which isn't thread safe. There is no ``DeleteStreamSyncedMetaDataAsync``.

**Use cases**
So we don't have to ``AltAsync.Do/RunOnMainThread`` or ``lock`` the entity while deleting.

**Describe the solution you'd like**
DeleteStreamSyncedMetaDataAsync

**Describe alternatives you've considered**
Running on main thread.

**Additional context**

**Comment by C0kkie** [comment]
You should open a issue in the module: https://github.com/FabianTerhorst/coreclr-module
