### ISSUE TITLE
Lagging animations in cef

### ISSUE THREAD

**Issue by faizmain** [altmp/altv-issues#1101]
**Client/server version**
`dev/6.0-dev14`

**Steps to reproduce**
im just use animations in the browser and they play for a long time
https://disk.yandex.ru/d/gV4-1pKenvPEcQ

**Comment by LeonMrBonnie** [comment]
This is expected behaviour since we updated CEF, unfortunately there can't be anything done about that currently.

**Comment by DurtyFree** [comment]
Sadly this is a technical limitation we have since updating to CEF v92 - we are not able to improve the performance until CEF provides us the possibility to do so.

Sry :(
