### ISSUE TITLE
Checkpoint.color on clientide sets wrong color

### ISSUE THREAD

**Issue by its4l3x** [altmp/altv-issues#1102]
**Client/server version**
`5.3/release`

**Current behavior**
(JS) When you have created a checkpoint and want to change the color with the .color property and with the RGBA Class the property r and b are mixed up. So, when i want to set my Checkpoint Red, i have to adjust the property Blue to set it red. 

The constructor in the alt.Checkpoint is working fine, only the .color property isnt working correctly.

**Expected behavior**
Property r sets the red and propery b the blue color for the checkpoint

**Steps to reproduce**
This example creates a Green Checkpoint, and after 4secs. the color should be setted to red, but the color is now blue.
Same behavior in the other direction

```
let player = alt.Player.local;

let cp = new alt.Checkpoint(4, new alt.Vector3(player.pos), new alt.Vector3(player.pos), 3, 3, new alt.RGBA(0, 255, 0, 255));


setTimeout(() => {
    cp.color = new alt.RGBA(255, 0, 0, 255);
}, 4000);
```

**Context (environment)**

**Possible solution**
switch the properties r & b

**Comment by martonp96** [comment]
FIxed in dev.
