### ISSUE TITLE
Unknown event error message - natives

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1103]
<!-- 🚨 STOP 🚨 STOP 🚨 STOP 🚨

**Client/server version**
alt:V build #6.0-rc7, branch rc

**Current behavior**
When using playSound and other natives I keep getting an unkown event error message on client side
Example:
[04:08:45][Error] Unknown event 51 PLAY_SOUND_EVENT
[04:37:29][Error] Unknown event 83 UPDATE_FXN_EVENT
Unknown event 71 VOICE_DRIVEN_MOUTH_MOVEMENT_FINISHED_EVENT

**Expected behavior**
Clear error message.

**Steps to reproduce**
game.playSound(-1, "CLICK_BACK", "WEB_NAVIGATION_SOUNDS_PHONE", true, 0, true);

**Context (environment)**
-

**Possible solution**
-

**Comment by C0kkie** [comment]
Follow the template and open it again
