### ISSUE TITLE
Unknown event error message - natives

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1104]
**Client/server version**
alt:V build #6.0-rc7, branch rc

**Current behavior**
When using playSound and other natives I keep getting an unkown event error message on client side
Example:
[04:08:45][Error] Unknown event 51 PLAY_SOUND_EVENT
[04:37:29][Error] Unknown event 83 UPDATE_FXN_EVENT
Unknown event 71 VOICE_DRIVEN_MOUTH_MOVEMENT_FINISHED_EVENT

**Expected behavior**
Clear error message.

**Steps to reproduce**
game.playSound(-1, "CLICK_BACK", "WEB_NAVIGATION_SOUNDS_PHONE", true, 0, true);

**Comment by Doxoh** [comment]
confirmed that. We got 
UPDATE_FXN_EVENT
NETWORK_GARAGE_OCCUPIED_STATUS_EVENT

**Comment by Konders** [comment]
Confirmed at 6.0 rc
Gotta Unknown event 83 UPDATE_FXN_EVENT 
When i have deattached trailer from tractor, and left tractor driver seat
Cant reproduce it again

**Comment by martonp96** [comment]
The unknown event messages were disabled
