### ISSUE TITLE
setExtraTimecycleStrength() doesn't use its parameter

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#1106]
**Client/server version**
`rc/6.0-rc7`

**Current behavior**
The extra timecycle modifier strength applied is always 1.0

**Expected behavior**
The extra timecycle modifier strength applied should be the value passed as parameter

**Steps to reproduce**
Simply call: 
`setExtraTimecycleModifier('spectator3');
setExtraTimecycleStrength(0.2);`

and after: 
`setExtraTimecycleModifier('spectator3');
setExtraTimecycleStrength(1.0);`

You will have the same result

**Comment by deluvas1911** [comment]
can't reproduce this. please provide an full snippet

**Comment by LeShred** [comment]
I have 2 events:
One event for TimecycleModifier:
```
    alt.onServer('VisualEffects:SetTimecycle', (name: string, strength: number) => {
        game.setTimecycleModifier(name);
        game.setTimecycleModifierStrength(strength);
    });
```

Another for ExtraTimecycleModifier:
```
    alt.onServer('VisualEffects:SetExtraTimecycle', (name: string, strength: number) => {
        game.setExtraTimecycleModifier(name);
        game.setExtraTimecycleModifierStrength(strength);
    });
```

Here are the results:
Without timecycle modifier
![normal](https://user-images.githubusercontent.com/7643284/133006220-4c054323-096e-4808-9dd5-915b7b044fca.jpg)

With TimecyleModifier 0.5
![timecycle-1](https://user-images.githubusercontent.com/7643284/133006233-3d39940b-2076-4797-83b0-da6edae11755.jpg)

With TimecycleModifier 1.0
![timecycle-2](https://user-images.githubusercontent.com/7643284/133006245-0ddfe08b-5f06-4a5a-997b-9ddf093ba126.jpg)

Without TimecycleModifier but with ExtraTimecycleModifier 0.5
![extratimecycle](https://user-images.githubusercontent.com/7643284/133006258-763f6805-4dbe-427e-9de2-5dcd0a8e0030.jpg)

Last effect applied to screen should be like TimecycleModifier 0.5 but currently it is like 1.0

**Comment by Lawliz** [comment]
You should probably reset it with: https://natives.altv.mp/#/0x2BF72AD5B41AA739

**Comment by LeShred** [comment]
I finally took time to test and the resetExtraTimecycleModifierStrength native didn't helped.

Apparently there is the same problem with FiveM so it looks more like a GTA bug or the way it is working : https://forum.cfx.re/t/more-than-one-timecycle-modifier-at-a-time/160499/5

![image](https://user-images.githubusercontent.com/7643284/170890773-64e6b6ae-3b6e-4a2a-af07-39ce993bc809.png)

I then close the issue.
