### ISSUE TITLE
Blip pool increase

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1107]
**Suggestion**
It would be good, if the blip pool wasnt just 99, because in many cases this is not enough.

**Use cases**
I have lots of blips, and if I want more, I cant display them.

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by LeonMrBonnie** [comment]
Duplicate of https://github.com/altmp/altv-issues/issues/546
