### ISSUE TITLE
Holding vehicle enter key makes player kick driver

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1108]
**Client/server version**

`release 5.4`

**Current behavior**
If you will stand near the right front door and will hold F while the driver is in the vehicle, ped will sit into the vehicle and kick the driver out

**Expected behavior**
Driver shouldn't be kicked out of the vehicle

**Steps to reproduce**
1. Spawn a vehicle
2. First player should sit to the driver place
3. Second player should stand near the right front door and hold F key

https://youtu.be/h3GTb-DNwqU

**Comment by C0kkie** [comment]
that is normal gta behavoir

**Comment by zziger** [comment]
Oh, is there a way to prevent it?

**Comment by xxshady** [comment]
override game f control with custom scripted one

**Comment by xxshady** [comment]
and maybe there is task for it in `taskChange`

**Comment by martonp96** [comment]
This is normal gta behavior, i think people already found the way to prevent this.
