### ISSUE TITLE
<select> does not fold up after used

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv-issues#1109]
**Client/server version**
`Build 6.0-rc7, branch rc`

**Current behavior**
When creating an <select> element with <option(s)> and using it ingame. The options wont fold up after choosing on of them.

**Expected behavior**
Should work as html works

**Steps to reproduce**

<select id='gender' v-model='gender'>
    <option value='disabled' :value='null'>Wähle dein Geschlecht</option>
    <option value='male'>Männlich</option>
    <option value='female'>Weiblich</option>
</select>

**Context (environment)**
The options will only disappear as soon as the whole webview disappears.

![S1jVtQe4Q92vZx93nekpbg](https://user-images.githubusercontent.com/5124966/133134958-aafe8c8b-7e40-44d3-b33f-6c1ba0ea040e.png)

**Comment by DurtyFree** [comment]
Can you pls attach some copy paste reproduction code for us? :D

**Comment by C0kkie** [comment]
@GangstaSunny  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

**Comment by Kingwolfi** [comment]
fixed for me in rc/6.0-rc13

**Comment by C0kkie** [comment]
Thank you @Kingwolfi
