### ISSUE TITLE
" @ " (at) can't be used in input fields anymore

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv-issues#1110]
**Client/server version**
`Build 6.0-rc7 branch rc`

**Current behavior**
While trying to write down the " @ " -symbol it just won't work. But you can copy the symbol (from somewhere else, e.g. notepad.exe) and insert it with CRTL + V.

**Expected behavior**
Beeing able to use the symbol as usualy.

**Steps to reproduce**
Just create an input field and try to write it down.

**Comment by Xantron** [comment]
same problem here. All with "ALT key" (@,€,etc.)

**Comment by C0kkie** [comment]
Try on newest rc @GangstaSunny @Xantron

**Comment by Xantron** [comment]
@C0kkie @GangstaSunny its fixxed.
https://abload.de/img/unbenanntekkvt.png

**Comment by C0kkie** [comment]
Fine

**Comment by Kingwolfi** [comment]
I have tested this on rc10 and now i can type the @ with AltGr+Q but not with Strg+Alt+Q

**Comment by ThomasMarangoni** [comment]
Is Ctrl + Alt + Q working for you in browser? Because for me it's also not working here on github.

**Comment by vadzz-dev** [comment]
For me ctrl-alt was working in browser but not in cef example or alt:V. But it shouldn't be hard to fix

**Comment by Kingwolfi** [comment]
can confirm the result from vadzz

**Comment by C0kkie** [comment]
@Kingwolfi  Should be fixed in rc/6.0-rc12, please report back if its fixed for you

**Comment by Kingwolfi** [comment]
is fixed in rc/6.0-rc13 !!!THANKS!!!

**Comment by C0kkie** [comment]
Thanks for confirmation
