### ISSUE TITLE
Vehicle repair engine bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1111]
**Client/server version**
alt:V build #6.0-rc7, branch rc

**Current behavior**
If I use vehicle.repair on a vehicle then a vehicles engine turns off even when before that it was running. The engine was started with vehicle.engineOn

**Expected behavior**
It would be great, if after repair the engine did not stop

**Steps to reproduce**
vehicle.engineOn = true;
vehicle.repair();

**Comment by vadzz-dev** [comment]
Can confirm that behavior

**Comment by Lekenthu** [comment]
#6.0-rc10 fixed. Ty. :D
