### ISSUE TITLE
Webview visible property has no effect

### ISSUE THREAD

**Issue by YannBCF** [altmp/altv-issues#1112]
**Client/server version**
rc/6.0-rc9

**Current behavior**
Webview visible property has no effect

**Expected behavior**
The visible property should hide the webview when set to true, show it when set to false

**Steps to reproduce**
```js
import * as alt from 'alt-client';
const view = new alt.WebView(url);
view.visible = true;

setInterval(() => {
    console.log(view.visible);
    view.visible = !view.visible;
}, 2000);
```

**Comment by xxshady** [comment]
there is only isVisible property

**Comment by LeonMrBonnie** [comment]
The property is named `isVisible` as shady already pointed out.
