### ISSUE TITLE
Waypoint sync bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1114]
**Client/server version**
#6.0-rc12, branch rc

**Current behavior**
When the driver selects a waypoint, the passengers cant see the waypoint.

**Expected behavior**
In the past it was in sync. It would be great to have that in sync.

**Steps to reproduce**
Select waypoint (driver).

**Comment by deluvas1911** [comment]
Issue confirmed

**Comment by deluvas1911** [comment]
Fixed with next update
