### ISSUE TITLE
Add vehicle.passengers property [Server-side]

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1116]
**Suggestion**
It would be nice to have a .passenger property on vehicles, that returns with the passenger entity.

**Use cases**
It would be good for many uses. For example I miss it in my damage system.

**Describe the solution you'd like**
vehicle.passengers -> return all passenger entity

**Comment by chaosfreak93** [comment]
That would be a great feature

**Comment by ZackaryH8** [comment]
There's already been a request for this but it was closed (#733). However I still think this should be added.

Manual Method
```js
alt.on('playerEnteredVehicle', handleEnteredVehicle);
alt.on('playerLeftVehicle', handleLeftVehicle);

// Add player as a passenger
function handleEnteredVehicle(player, vehicle, seat) {
    if (!vehicle.passengers) {
        vehicle.passengers = [];
    }
    vehicle.passengers.push({ seat, player });
}

// Remove player as a passenger
function handleLeftVehicle(player, vehicle, seat) {
    if (vehicle.passengers) {
        vehicle.passengers = vehicle.passengers.filter((passenger) => passenger.id !== player.id);
    }
}

// Get passenger by ID
alt.Vehicle.prototype.getPassengerByID = function (id) {
    return this.passengers.find((player) => player.id === id);
};
```

**Comment by FabianTerhorst** [comment]
The think is that the Code you posted is much more efficient for e.g. js instead of Code that could be added in SDK.

**Comment by xxshady** [comment]
@ZackaryH8 you should also handle `playerChanged
VehicleSeat`

**Comment by ZackaryH8** [comment]
> @ZackaryH8 you should also handle `playerChangedVehicleSeat`

It's more just an example but obviously that is something you'd have to handle by yourself

**Comment by C0kkie** [comment]
added in v15
