### ISSUE TITLE
CEF-Update: toFixed not working anymore

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1117]
**Client/server version**
`6.0-rc12 (rc)`

**Current behavior**
[14:47:15][Error] [WEB, View 000001838004CD00] https://xyz.de/build/7.87d49035.js:26:TypeError: Cannot read property 'toFixed' of undefined

On Normal Webbrowser (Firefox/Chrome/Edge) and current 5.4 release version its worked.

**Expected behavior**
Method "toFixed" works.

**Steps to reproduce**
Vue.JS -> 

```
textnumb: number = 1.234;

let newTextNumb = textnumb.toFixed(2);
```

**Context (environment)**
Nothing

**Possible solution**
Nothing

**Comment by LeonMrBonnie** [comment]
This is an issue in your code, not an issue with CEF.

**Comment by yoranjj** [comment]
I'm using Vue too and it works perfectly fine on the latest dev build.
