### ISSUE TITLE
Closing early auth via script doesn't work properly

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1121]
**Client/server version**

`release 5.4`

**Current behavior**
Calling window.close() from early auth makes "Joining server" window appear with Abort button broken.

**Expected behavior**
Calling window.close() should behave like ESC button, so "Early auth failed" menu should appear instead of "Joining server"

**Steps to reproduce**
Call window.close() from early auth

**Context (environment)**
I want to provide user a way to cancel the early auth (pressing ESC to leave is not that obvious actually)

**Comment by vadzz-dev** [comment]
@zziger there's `alt.emit('closeMe')` for that, tho it might be missing in docs, please test if it works for you

**Comment by zziger** [comment]
yea, that works perfectly, thanks :D
