### ISSUE TITLE
Player Death event not called

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1122]
**Client/server version**

`6.0-rc14 (rc)`

**Current behavior**
If the health-state is set to 0, the player died but the PlayerDeath event is not called

**Expected behavior**
PlayerDeathEvent called

**Steps to reproduce**
[deathbug.zip](https://github.com/altmp/altv-issues/files/7187111/deathbug.zip)

**Context (environment)**
See zip file

**Possible solution**
Nothing

**Comment by Lekenthu** [comment]
Confirmed.

**Comment by FabianTerhorst** [comment]
We decided to not call the events when the data is set manually. When you set it to 0 you know you set it and so you dont need the event. The event would contains invalid data anyway.

**Comment by Doxoh** [comment]
Then please write it in the changelog :)

**Comment by FabianTerhorst** [comment]
We wrote in changelog that the damage events arent called when heath is modified.

**Comment by Doxoh** [comment]
Ihr habt geschrieben, dass es bei Spielerschaden und nicht Spielertod nicht ausgelöst wird. Das sind 2 verschiedene Ereignisse. Bitte erweitert den Changelog um das Spielertod event

**Comment by tastydev** [comment]
If u set it to 1 - 99 the event is calling btw

**Comment by ThomasMarangoni** [comment]
@Doxoh only english in github issues

**Comment by Doxoh** [comment]
You wrote that it does not trigger for player damage and not player death. These are 2 different events. Please expand the changelog with the player death event

Sorry @ThomasMarangoni :)

**Comment by vadzz-dev** [comment]
We're going to get it back for consistency

**Comment by FabianTerhorst** [comment]
We will casll it manually when you set the health to <99 with 0 killer, 0 deathReason and 0 damage

**Comment by Doxoh** [comment]
Yes, that's good! Thanks :) If it is on rc I will test it directly

**Comment by FabianTerhorst** [comment]
fixed in next rc version

**Comment by Doxoh** [comment]
Worked with rc6. Thanks!
