### ISSUE TITLE
Server-side female clothing API crashes the server

### ISSUE THREAD

**Issue by n0minal** [altmp/altv-issues#1123]
**Client/server version**
`release`

**Current behavior**
Setting clothes on female characters crashes the server.

**Expected behavior**
The server shouldn't crash when clothing are set on female characters.

**Steps to reproduce**
I have recorded a video as always to help the developers to understand the crash, but basically whenever you set clothes on female characters the server crashes and generates a mini-dump, I'll provide an example code, the video and the crash dump file below:

1. Reproduction video

https://youtu.be/_RslCQX7eN0

2. Example code

**File: `outfit.js`**

```js
export default const outfit = {
  "index" : 2,
  "gender" : "female",
  "components" : [ 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : 0,
        "texture" : 0
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : 3,
        "texture" : 0
    }, 
    {
        "drawable" : 0,
        "texture" : 0
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : 10,
        "texture" : 2
    }, 
    {
        "drawable" : 1,
        "texture" : 1
    }, 
    {
        "drawable" : 3,
        "texture" : 0
    }, 
    {
        "drawable" : 0,
        "texture" : 0
    }, 
    {
        "drawable" : 0,
        "texture" : 0
    }, 
    {
        "drawable" : 3,
        "texture" : 1
    }
  ],
  "props" : [ 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }, 
    {
        "drawable" : -1,
        "texture" : -1
    }
  ]
}
```

 **File: `index.js`**
```js
import outfit from './outfit'

setPlayerOutfit(player: Player) {
    outfit.components.forEach((component, index) => {
        player.setClothes(index, component.drawable, component.texture);
    });

    outfit.props.forEach((prop, index) => {
        player.setProp(index, prop.drawable, prop.texture);
    });
}
```

3. Crash dump:

https://mega.nz/file/HR4mkZLS#6q1A6gWp93iUdU5Ia7XgPT2I1Jv5RMwDFGumqwWtQq8

**Context (environment)**
It crashes my entire server if someone picks a female character.

**Possible solution**
There's no workaround for this issue unfortunately.

**Comment by C0kkie** [comment]
You should not set -1 as drawable

**Comment by FabianTerhorst** [comment]
I think -1 is fixed in js on Dev.

**Comment by n0minal** [comment]
> You should not set -1 as drawable

It's a common thing in GTA:O outfits, the outfits were dumped from scriptmetadata.meta, and it works for male characters.

I'll try it in `dev` branch.

**Comment by FabianTerhorst** [comment]
-1 wont Work Serverside. Its Not a real clothes id. No mather how the native works.

**Comment by tastydev** [comment]
-1 is blocked in js module anyways on next release merge because of that

**Comment by n0minal** [comment]
Yeah just tested in dev branch and it doesn't set any piece of clothing if some of them has -1

**Comment by n0minal** [comment]
@FabianTerhorst for some reason setting any piece of clothing in `dev` branch doesn't work on server-side for female characters, even while not passing -1.

Please reopen the issue.
