### ISSUE TITLE
Add server event: OnResourceStart

### ISSUE THREAD

**Issue by cuBeUrg** [altmp/altv-issues#1124]
**Suggestion**
Add a server event called: 'OnResourceStart'.

**Use cases**
Create blips, coleshapes, call functions, events when a C# resource starts.

**Describe the solution you'd like**
N/A.

**Describe alternatives you've considered**
None.

**Additional context**
N/A.

**Comment by YannBCF** [comment]
It does already exists https://docs.altv.mp/js/api/alt-server.IServerEvent.html#_altmp_altv_types_alt_server_IServerEvent_resourceStart
