### ISSUE TITLE
A way to disable social club menu (on HOME button)

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1125]
**Suggestion**
Currently HOME button always opens the social club menu, control natives/alt.toggleGameControls don't block it.
It would be very helpful to have a way to disable it.

**Use cases**
Home button is oftenly used while writing a text/code to go to the start of the line.

**Describe the solution you'd like**
Maybe adding some separated method or at least making alt.toggleGameControls block it.

**Describe alternatives you've considered**
Sadly you can't block that menu rn :c

**Comment by xxshady** [comment]
I agree it will really help for us home button guys

**Comment by C0kkie** [comment]
Added in next dev
