### ISSUE TITLE
Multiple Server Crashes and after hours no Idea why

### ISSUE THREAD

**Issue by DevelopmentUnionV** [altmp/altv-issues#1126]
[Uploading altv_5.4_Steam_0x12d0bd3_21-09-2021_22-11-13.zip…](
[Uploading altv_5.4_Steam_0x12d0bc1_21-09-2021_22-28-05.zip…]()
[Uploading altv_5.4_Steam_0x12d0bc1_21-09-2021_23-05-29.zip…]()
)

**Comment by DurtyFree** [comment]
Please create an issue by following our template (Which should have been visible when you create an issue)

**Comment by DevelopmentUnionV** [comment]
**Current behavior**


**Expected behavior**


**Steps to reproduce**


**Context (environment)**


**Possible solution**

**Comment by DevelopmentUnionV** [comment]
?

**Comment by FabianTerhorst** [comment]
Ask your question in discord.
