### ISSUE TITLE
Custom clothes not working on RC 15 version

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1129]
**Client/server version**
`Build #6.0-rc15 (rc)`

**Current behavior**
Custom clothes do not appear when applying them (does not matter if its done via native or serverside

**Expected behavior**
Custom clothes should appear

**Steps to reproduce**
Try to load https://www.lcpdfr.com/downloads/gta5mods/character/8151-emergency-uniforms-pack-law-order/ as custom clothes. Not working. Working in release tough

**Context (environment)**
Debian 10 server is the operating system 

**Possible solution**
needs fix

**Comment by FabianTerhorst** [comment]
Upload the altv resource.

**Comment by cmdflow** [comment]
https://mega.nz/file/nZIhDQba#trvID3xZHTSLTKzRllhM4JrkYM0SBJawMpXXQP8AUfA

**Comment by cmdflow** [comment]
BTW: Its armor collection (ID 9) round about drawable 56 which should be lspdfr uniform vest but does show different

**Comment by FabianTerhorst** [comment]
When its not working with natives as well its a bug in your clothes resource.

**Comment by cmdflow** [comment]
I have 2 clothes ressource. Both working finde just as they are in release branch. Now both do not work in rc. I could not imagine what should be wrong with the ressource as they are made like described in wiki. And they do work in release

**Comment by cmdflow** [comment]
Here is the second ressource: https://mega.nz/file/nEJ3ka7a#UAP7v8IlFLLgSJKX66CmKRbb6rlAj6vf43Z5J4dCZMA

**Comment by cmdflow** [comment]
Here is how i set the clothes (both ways don't work in RC in meaning of that i can set every standard clothes but not the custom ones added via ressource):
`native.setPedComponentVariation(player.scriptID, parseInt(d[0]), parseInt(d[1]), parseInt(d[2]), 2);`
`player.setClothes(parseInt(clothes[0]), parseInt(clothes[1]),parseInt(clothes[2]));`

**Comment by C0kkie** [comment]
Does it work with natives?

**Comment by cmdflow** [comment]
native.setPedComponentVariation does neither work

**Comment by C0kkie** [comment]
Then it must be a problem with your dlc, we have no issues

**Comment by cmdflow** [comment]
Okay so what can i try then? I mean it is 2 DLCs packs that functioned perfectly on release branch and still do function properly on release branch

**Comment by cmdflow** [comment]
Did you try both ressources i sent you? They work on your testserver with rc branch?

**Comment by cmdflow** [comment]
Component 9 with id 56 is a police vest with the first dlc i sent you. But just in release branch. 
In RC branch this is: https://i.imgur.com/IxJ9KwN.png
It has to be something with rc branch

**Comment by C0kkie** [comment]
You have to use the setDlcClothes serverside if you want your own dlc to work

**Comment by cmdflow** [comment]
That's what i asked in discord an durty said i dont have to use it. I mean how can you decide between dlc and non dlc clothes. That's kinda confusing to develop a ingame shop system which can decide between dlc and non dlc clothes. What's the matter or best practice? I mean before in this ticket natives also should work. I am confused :(

**Comment by cmdflow** [comment]
Also what is my dlc number then? When ressource name is "factionwest":

public setDlcClothes(dlc: number, component: number, drawable: number, texture: number, palette?: number): void

**Comment by C0kkie** [comment]
Lets discuss that in discord.

**Comment by cmdflow** [comment]
requesting models with stuyks charchreator was the issue. 

native.requestModel(fModel);
native.requestModel(mModel);
