### ISSUE TITLE
Mute loading music

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1132]
**Suggestion**
Ability to mute alt:V launcher's loading music with `F1` or any other keys.

**Describe the solution you'd like**
Save the mute state in `altv.cfg` client file with `loadingMusic: boolean` key.

**Comment by mrgharabaghi** [comment]
Muted

![muted](https://user-images.githubusercontent.com/40915667/222912698-1dfbcef3-2e6f-4084-b244-1da1c35f78f2.jpg)

Unmuted

![unmuted](https://user-images.githubusercontent.com/40915667/222912721-c3b4fa60-d2af-4725-8fbf-9821719f36a9.jpg)

**Comment by C0kkie** [comment]
It will be disabled by default with a future rework

**Comment by C0kkie** [comment]
Should be done in next dev build
