### ISSUE TITLE
Ped Config Flag 48 CPED_CONFIG_FLAG_BlockWeaponSwitching deactivates vehicle weapons

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1133]
**Client/server version**

` 6.0-rc16`

**Current behavior**
With `native.setPedConfigFlag(pedId.scriptID, 48, true);` all vehicle weapons will be blocked like issue #1009 . In this issue the problem with the vehicle weapons is fixed but not for this ped config.

**Expected behavior**
Vehicle Weapons can be used like firetruk

**Steps to reproduce**
``native.setPedConfigFlag(pedId.scriptID, 48, true);`

**Context (environment)**
Nothing

**Possible solution**
Simple said, like as in #1009, but I don't know :D

**Comment by C0kkie** [comment]
Thats a native, dont think we can change that behavoir

**Comment by FabianTerhorst** [comment]
The fix was unrelated to ped flags.
We probably can in the future create a own way to prevent weapon switching but its for sure not a bug.
