### ISSUE TITLE
Improve server.cfg error message (Invalid token)

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1134]
**Suggestion**
Add a more understable error message for `Reason: invalid token`.

**Use cases**
It happens often that users think the error `Reason: invalid token` is related to the token key, instead of a missing value / wrong format. Adding a more clearly error message would solve that.

**Describe the solution you'd like**
Instead of invalid token maybe print `Invalid value` or `Invalid format` and the key which the error belongs to

**Describe alternatives you've considered**
 /

**Additional context**
 /

**Comment by LeonMrBonnie** [comment]
The error message for this is now `Unexpected character` which should avoid the confusion with the masterlist token
