### ISSUE TITLE
Using setDlcClothes is spamming console when using natives before

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1135]
**Client/server version**
`Build #6-16, branch rc`

**Current behavior**
Setting Clothes clientside with native and afterwards setting clothes with setDlcClothes is spamming console with:
`clothes override data 00000000000000000000001000000000
clothes gta data 00000000000000000000111111111011
clothes override data 00000000000000000000001000000000
`

**Expected behavior**
no console spam

**Steps to reproduce**
set clothes with native then set serverside

**Context (environment)**
Operation system debian 10 64bit

**Possible solution**

**Comment by C0kkie** [comment]
Thats normal behavoir if you use debug mode. You should also not set it clientside and then serverside. Only use serverside
