### ISSUE TITLE
Players don't die at Vehicle Explosion

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#1136]
**Client/server version**
`Build #6.0-rc16, branch rc`

**Current behavior**
The Player can't die from a vehicle Explosion (video: https://streamable.com/h5uc89 )

**Expected behavior**
The player should die

**Steps to reproduce**
Spawn a Vehicle & let them Explode + stand nearby the Vehicle

My Code for Destory Command:
`
                vehicle.EngineHealth = -100;
                vehicle.PetrolTankHealth = -100;
`

**Context (environment)**
**/**

**Possible solution**
**/**

**Comment by FabianTerhorst** [comment]
Do you override Explosion Event?

**Comment by BuddiesTV** [comment]
Nope, when i shoot at the Vehicle the Player will die. When i use the Setters EngineHealth & PetrolTankHealth & set them to -100 the Player will not die

**Comment by FabianTerhorst** [comment]
We cant reproduce it. Please provide a working resource.

**Comment by BuddiesTV** [comment]
YANN already reproduced it, https://discord.com/channels/371265202378899476/371271006360436757/892440250431963177

**Comment by martonp96** [comment]
done in 9.0-dev1
