### ISSUE TITLE
Remove Debug Log

### ISSUE THREAD

**Issue by its4l3x** [altmp/altv-issues#1138]
**Client/server version**
altv-6.0-release / server (windows server)

**Current behavior**
Currently the server console is getting spammed from a debug log

https://i.imgur.com/7eCBW1y.png

**Expected behavior**
no debug log, we guess

**Steps to reproduce**
we think the debug log come, when you equip dlc clothes / normal clothes on a player

**Possible solution**
remove debug log

**Comment by LeonMrBonnie** [comment]
This isn't a "debug log", its an error. Don't use the serverside clothes API and the clientside native at the same time, otherwise that will cause that error.
Working as intended

**Comment by its4l3x** [comment]
We don't use the Natives anymore... @LeonMrBonnie

**Comment by tastydev** [comment]
if they are not using the native (as they mentioned before) it could be a real sync missmatch in ped appearence

**Comment by cmdflow** [comment]
is what it is: Spamming server logs is causing issues. Should be fixed
