### ISSUE TITLE
Segmentation Fault 6.0 stable linux

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1139]
`Build #6.0, branch release`

**Current behavior**
[23:13:44] alt:V Server 6.0 (release)
[23:13:44] Starting alt:V Server on 0.0.0.0:7788
Segmentation fault

**Expected behavior**
Server should start

**Steps to reproduce**
Load standard server files for linux with sample resources from website and start on linux

**Context (environment)**
Debian 10 64 bit

**Possible solution**
n/a

**Comment by deluvas1911** [comment]
https://github.com/FabianTerhorst/coreclr-module/releases/tag/6.0.2
Update C# modul to 6.0.2

**Comment by LeonMrBonnie** [comment]
Update your modules and server.

**Comment by cmdflow** [comment]
They should be delivered with download, shouldn't they?
