### ISSUE TITLE
Scrolling in iframes not working properly

### ISSUE THREAD

**Issue by lokuPadoku** [altmp/altv-issues#1140]
**Client/server version**
`Build 6.0, branch release`

**Current behavior**
Scrolling in iFrames not working properly if having multiple scrollable areas on webpage

**Expected behavior**
Should work like in 5.4

**Steps to reproduce**
1. Create a Webview
2. Insert an iFrame with a Webpage with multiple scrollables areas
2. Fire up alt:V and open the Webview

**Context (environment)**
We have a webview which displayes a website. It contains an navigation on the left, and Content on the right. If both have enough height and scrollbars, its not possible to scroll.

**Possible solution**
I don't know.

**Comment by Xantron** [comment]
Same problem with login on a webpage with iFrame ?

**Comment by lokuPadoku** [comment]
> Same problem with login on a webpage with iFrame ?

What do you mean with login? My login works expect the blinking cursor but that is an other issue.

**Comment by Xantron** [comment]
> > Same problem with login on a webpage with iFrame ?
> 
> What do you mean with login? My login works expect the blinking cursor but that is an other issue.

Do you have a Login in your webview / iFrame?

liveinvader, or Mail Login for your Users ?

**Comment by lokuPadoku** [comment]
> > > Same problem with login on a webpage with iFrame ?
> > 
> > 
> > What do you mean with login? My login works expect the blinking cursor but that is an other issue.
> 
> Do you have a Login in your webview / iFrame?
> 
> liveinvader, or Mail Login for your Users ?

Yes.

**Comment by Xantron** [comment]
> > > > Same problem with login on a webpage with iFrame ?
> > > 
> > > 
> > > What do you mean with login? My login works expect the blinking cursor but that is an other issue.
> > 
> > 
> > Do you have a Login in your webview / iFrame?
> > liveinvader, or Mail Login for your Users ?
> 
> Yes.

Okay, and this logins work ?

**Comment by lokuPadoku** [comment]
Yes

**Comment by SandDanGlokta** [comment]
Same Problem here.

**Comment by tobydarkh** [comment]
Problem still present

**Comment by C0kkie** [comment]
@SandDanGlokta @lokuPadoku Can you test on newest dev?

**Comment by C0kkie** [comment]
Should be fixed, if someone has the problem, we can reopen it
