### ISSUE TITLE
AttachEntity not accepting all of the bones

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1143]
**Client/server version**

`Build #6.0.2, branch release`

**Current behavior**

AttachToEntity not accepting higher values cause of short type of bone. 
https://wiki.altv.mp/wiki/GTA:Ped_Bones

**Expected behavior**

Should be ushort i guess

**Steps to reproduce**

https://i.imgur.com/5a09fqA.png

**Context (environment)**

      

**Possible solution**

Should be ushort i guess

**Comment by C0kkie** [comment]
Looks more like a c# modul issue, better open a issue here https://github.com/FabianTerhorst/coreclr-module

**Comment by TuK4z** [comment]
Oh ok ty

**Comment by FabianTerhorst** [comment]
In the sdk its a int16. Im not sure if bones are unsigned.

**Comment by zziger** [comment]
Well short max value is 32767, but on wiki there are bones as high as 65245, so I guess it should be ushort then

**Comment by FabianTerhorst** [comment]
Are the values on the wiki the bone indexes or the values you give into the ped bone index native?

**Comment by TuK4z** [comment]
In wiki i gues its bones indexes, because in csharp code u place that index straight.

**Comment by FabianTerhorst** [comment]
Someone need to verify that.

**Comment by deluvas1911** [comment]
@FabianTerhorst 
The values on the wiki are are the bone ids which you pass to the getPedBoneIndex native

**Comment by FabianTerhorst** [comment]
Then you need to use serverside the values the native would return.
