### ISSUE TITLE
CEF creating new Session on every page load.

### ISSUE THREAD

**Issue by SandDanGlokta** [altmp/altv-issues#1144]
**Client/server version**
6.1

**Current behavior**
CEF creates a new session on every page load. So it is impossible to use for example php as server backend creating sessions(). Login, saving / editing / deleting via api request (using jquery (js) http request) does not work either ofcource.

**Expected behavior**
Not creating a new session on every page load, which did work fine before the 6.x update.

**Steps to reproduce**
Call a php page that creates a session. Click on a refresh java script link to reload the page and echo the session id. It will change. Or: Load a php page, show session id, and load an iframe and display session id in there. It will be different.

**Context (environment)**
A lot of systems like email, "twitter" etc using sessions at backend do not work.

**Comment by Xantron** [comment]
I can confirm this issue. Since Version 6.0 massiv Problems.

**Comment by StoneOnELP** [comment]
hello, we have the same Problem in 6.0 and 6.1. @C0kkie when you can check ?

**Comment by C0kkie** [comment]
What can i check? @StoneOnELP

**Comment by StoneOnELP** [comment]
this issue, this problem, we have some iframes in use and can not use our systems. you can reproduct logins about iframes with cookies and sessions, its not work
 @C0kkie

**Comment by C0kkie** [comment]
I am not a dev

**Comment by StoneOnELP** [comment]
Ahhh Ok sorry @C0kkie

**Comment by Rumbo444** [comment]
I have the same Problem !

**Comment by AmKoma** [comment]
Sameee

**Comment by C0kkie** [comment]
Its fixed for now in release/6.4
