### ISSUE TITLE
player.vehicle.speed returns 0 when sitting on some motorcycles

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1151]
**Client/server version**
`Build #6.4, branch release`

**Current behavior**
Sitting on some motorcycles does return 0 for client side player.vehicle.speed

**Expected behavior**
Should return speed

**Steps to reproduce**
Spawn bikes like sanchez, hexer or avarus and try to get player.vehicle.speed

**Context (environment)**
n/a

**Possible solution**
Needs fix?

**Comment by YannBCF** [comment]
See https://github.com/altmp/altv-issues/issues/1044#issuecomment-890106052

Invalid issue
