### ISSUE TITLE
Ped and vehicle models in JSON format instead

### ISSUE THREAD

**Issue by martonp96** [altmp/altv-issues#116]
Store always the latest list of models/etc. on cdn, so i can download and use it anytime from server side.

-trusted source
-can be used outside server too
-json

Example links:
`https://cdn.altv.mp/server/{branch}/{platform}/data/vehmodels.json`
`https://cdn.altv.mp/server/{branch}/{platform}/data/pedmodels.json`

**Comment by FabianTerhorst** [comment]
@vadzz-dev would that increase the cost of the cdn?

**Comment by 7Hazard** [comment]
@FabianTerhorst no

**Comment by martonp96** [comment]
Solved by durty dumps

**Comment by DurtyFree** [comment]
Just for documentation purpose, this dump: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/vehicles.json
