### ISSUE TITLE
Door Glass Shot Sync

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1163]
**Client/server version**
Build #6.1, branch release (outdated)

**Current behavior**
=> My View https://gyazo.com/c5ecbbd50a16a6d5edc7b2a1cc66cd2e
=> Other Player View https://gyazo.com/da5d5e3d159f8446b1823a6b90cad1d1

**Expected behavior**
No information

**Steps to reproduce**
No information

**Context (environment)**
No information

**Possible solution**
No information

**Comment by deluvas1911** [comment]
@BuddiesTV Please provide information to correct this issue according to the template.

**Comment by FabianTerhorst** [comment]
i think this is a duplicate of the missing projectile issue.
