### ISSUE TITLE
Blood Sync

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1165]
**Client/server version**
Build #6.1, branch release (outdated)

**Current behavior**
=> My View https://gyazo.com/f9a331e0d12264f9afd9d8745ae020db
=> Other Player View https://gyazo.com/30aa6b15d5f6abe918c0dbfb468959fe

> When i have blood, and go into the first person, the blood is disapearing on my View, but other Players still can see the blood

**Expected behavior**
Sync blood correctly

**Steps to reproduce**
No information

**Context (environment)**
No information

**Possible solution**
No information

**Comment by deluvas1911** [comment]
@BuddiesTV Please provide information to correct this issue according to the template.

**Comment by C0kkie** [comment]
@BuddiesTV  is this still a thing?

**Comment by BuddiesTV** [comment]
> @BuddiesTV is this still a thing?

No, it seems to be fixed
