### ISSUE TITLE
Buggy Movement

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1167]
**Client/server version**
Build #6.1, branch release (outdated)

**Current behavior**
=> My View https://streamable.com/04fe3p
=> Other Player View Just normal walking

**Expected behavior**
No information

**Steps to reproduce**
No information

**Context (environment)**
No information

**Possible solution**
No information

**Comment by BuddiesTV** [comment]
Sometimes, when a player is going into the first person & then walk the player has buggy movement

**Comment by yoranjj** [comment]
Just tested on latest dev, seems to work perfectly fine. Perhaps you/your partner reconnected a few times? Sync issues are known to happen when using the reconnect feature.
