### ISSUE TITLE
When i'm flying with a hunter & shoot other Players only see the explosion not the "bullet shooting"

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1169]
**Client/server version**
Build #6.1, branch release (outdated)

**Current behavior**
No information

**Expected behavior**
No information

**Steps to reproduce**
No information

**Context (environment)**
No information

**Possible solution**
No information

**Comment by deluvas1911** [comment]
@BuddiesTV Please provide information to correct this issue according to the template.

**Comment by BuddiesTV** [comment]
When i shoot a rocket with the Hunter the explosion is Synced, but not the Rocket

**Comment by deluvas1911** [comment]
As the rocket is a projectile it's related to #660
