### ISSUE TITLE
addExplosion does not do damage

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#1172]
### Description of the problem

addExplosion native doesn't do damage to the player, even when "noDamage" parameter is set to false. I've tried both true/false on this parameter, either way it does no damage. The player does get launched into the air a bit sometimes, but no HP damage(aside from the fall damage once the ped hits the ground).

### Reproduction steps

```ts
alt.onServer( "TriggerExplosion", ( x, y, z, explosionType, damageScale, isAudible, isInvisible, cameraShake ) => {
    natives.addExplosion( x, y, z, explosionType, damageScale, true, isInvisible, cameraShake, false );
} );
```

Eg call the explosion on player position.

### Expected behaviour

Should damage/kill the player.

### Additional context

As a workaround, "addOwnedExplosion" can be used, but this sometimes incorrectly triggers a kill for another player, eg:

- Player 1 damages player 2
- Player 3 sets an explosive at XYZ.
- Player 2 goes to XYZ and dies from the explosion
- Player 1 gets the kill on player 2, even though the last time player 1 saw player 2 could've been like 10 minutes ago.

### Operating system

Windows 10

### Version

Latest release

**Comment by C0kkie** [comment]
There is already a issue open https://github.com/altmp/altv-issues/issues/1136
