### ISSUE TITLE
OnPlayerLeaveVehicle event is never fired when a player disconnects

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1177]
### Description of the problem

When a player leaves the server while inside a vehicle, the OnPlayerLeaveVehicle event is never called.

### Reproduction steps

Spawn a vehicle, enter it, press F8 and type reconnect, or ALT + F4 etc.

### Expected behaviour

It should call the OnPlayerLeaveVehicle event

### Additional context

I want to keep track of vehicle occupants via these events, I have to make a workaround via disconnect event or smtn now. Also leaves me wondering what other things a player could do that would bypass the OnPlayerLeaveVehicle event.

### Operating system

Windows 10

### Version

Latest release

**Comment by C0kkie** [comment]
Will be fixed in dev/9.0-dev2
