### ISSUE TITLE
Rename _0x2AED6301F67007D5 to disableCamCollisionForEntity and fix it

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1179]
### Description of the problem

Native should disable the gameplay camera collision with the entity, so it won't accidentally zoom in when you stay inside a player or vehicle, while the collision is disabled.

### Reproduction steps

Disable collision between two entities and get into the entity. The cam should jump into a very close zoom position.
https://i.gyazo.com/388a6657c2a1dbd3309d75dfc7d805a0.mp4

### Expected behaviour

The collision should be ignored in this frame.

### Operating system

Windows

### Version

Release/Current

**Comment by FabianTerhorst** [comment]
We will do native data sync from the last researched natives at some point. But not individually.
