### ISSUE TITLE
playerDeath event parameters bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1180]
### Description of the problem

playerDeath event killer and weaponHash parameters do not return the correct value.

### Reproduction steps

Use my example script, kill someone and you can see the problem.

alt.on("playerDeath", function(player, killer, weaponHash) {
    alt.log("weaponHash: " + weaponHash)
    alt.log("killer: " + killer)
});

### Expected behaviour

It would be good, if the event returned the correct parameters.

### Operating system

Windows 11

### Version

alt:V build #6.4, branch release

**Comment by C0kkie** [comment]
We couldn't repro it and there is no answer from your side, so i will close it
