### ISSUE TITLE
Too many modding vehicles in the same area unloading the world

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1185]
### Description of the problem

When too many different modding vehicles are in the same area the world will beginn to unload.

### Reproduction steps

For reproduction i used the package of Trooper Corentin with 15 vehicles (https://www.youtube.com/watch?v=aihUFIYocR0).
No any other mod is used.

1. Spawning 7 different vehicles from the package and then the world beginn to unload. 
2. Reproduction on Video: https://img.revyn112.dev/data/MHkJ6FLF2i.mp4

### Expected behaviour

The world shouldn't unload.

### Additional context

Its not a problem of NVE because i can reproduce this with vanilla game too.
Also to say, there are no other modded vehicles loaded in the resource, just the package.
I've got this issue some time ago and reported back in discord, but with a bigger number of different vehicles spawned in the same are (around 60-80).

I think its because of to big size of the texture dictionary and alt:V is hitting a limit. Each vehicle of the package has a ytd around 10 megabyte. this would be an explanation while i encounter the same issue with around 60 vehicles, because they don't have so big ytd included.

### Operating system

Windows 11

### Version

release/6.4

**Comment by C0kkie** [comment]
As @PavlovTM  that happens if you use unoptimized vehicles, so thats not a problem on our end
