### ISSUE TITLE
Street lights bug

### ISSUE THREAD

**Issue by x90nik** [altmp/altv-issues#1186]
### Description of the problem

After an accident with a street light, it separates from the ground again every time you approach it.

### Reproduction steps

https://user-images.githubusercontent.com/40915667/138601591-95d6b2d1-9f46-4c4b-ac4d-da5b4bb68147.mp4

### Expected behaviour

It shouldn't separate from the ground after moving away from the street light and approaching it again.

### Operating system

Windows 10

### Version

release/6.4

**Comment by zziger** [comment]
Should be fixed in `dev/15.0-dev356`
