### ISSUE TITLE
Mouse wheel does not work within iframe on external website

### ISSUE THREAD

**Issue by pixlcrashr** [altmp/altv-issues#1193]
### Description of the problem

When including an external webpage that has not the same origin as the base site, the mouse wheel does not work for scrolling (= mouse wheel scroll does not work).

### Reproduction steps

Seems obvious:

1. Create CEF page.
2. Include an iframe to e.g. `https://github.com/`
3. Go to a sub-page within the iframe that can be scrolled
4. Try to scroll -> does not work

### Expected behaviour

Scrolling should also work within an iframe.

### Additional context

Related issue (maybe same root cause): #1119 

### Operating system

CEF

### Version

release/6.4

**Comment by Revyn112** [comment]
Still a problem in release/8.8 https://img.revyn112.dev/data/LG95BRmJpx.mp4

**Comment by C0kkie** [comment]
Fixed in dev/14.0-dev54
