### ISSUE TITLE
Options for Discord rich presence

### ISSUE THREAD

**Issue by opysium** [altmp/altv-issues#1195]
### Description of the problem

We don't have options for alt:V's Discord rich presence.

### Desired solution for the problem

We should have these options in in-game altV settings menu and altv.cfg.

1. Toggle Discord rich presence.
2. If Discord rich presence is enabled, show/hide name in rich presence.
3. If Discord rich presence is enabled, show/hide time played in rich presence.
4. If Discord rich presence is enabled,  show/hide server name in rich presence.

**Comment by C0kkie** [comment]
Please use the search in the future: https://github.com/altmp/altv-issues/issues/398
You can add suggestions there

**Comment by zziger** [comment]
@C0kkie that issue you've mentioned is about controlling rich presence from the server, while this was about controlling it from the client settings
