### ISSUE TITLE
Scenarios triggering PlayerWeaponChange Event

### ISSUE THREAD

**Issue by TheGodlyLuzer** [altmp/altv-issues#1196]
### Description of the problem

When a player is entering a scenario where the ped holds a prop in his hands the Event gets triggered.

### Reproduction steps

Let the ped play a scenario, the event gets triggered instantly.

Client Code to play a scenario:

native.taskStartScenarioInPlace(alt.Player.local.scriptID, name, 0, true);
alt.setTimeout(() => {
      native.clearPedTasks(alt.Player.local.scriptID);
}, 15000);

### Expected behaviour

Only weaponchanges should get triggered

### Operating system

Windows 10

### Version

release 6.4

**Comment by C0kkie** [comment]
We decided in the past already to not fix that, because you get invisible weapon for it with a lot of different ids, same is for animals
