### ISSUE TITLE
Add push to mute option for voice

### ISSUE THREAD

**Issue by Lawliz** [altmp/altv-issues#1200]
### Description of the problem

It's not really a problem but more a comfort for some players.
Personally I prefer a push to mute instead of push to talk.

### Desired solution for the problem

Add another option in voice to use push to mute.

### Alternatives you considered

I made my own system but it force players use voice detection in alt:V settings and use my system to set it to voice detection, push to talk or push to mute.

**Comment by FabianTerhorst** [comment]
you can mute players via channel mute player api.

**Comment by Lawliz** [comment]
I know it can be handle like this but I personally think it'll be a great option to add.
