### ISSUE TITLE
When cloning ped in pause menu all UI's  disappear 

### ISSUE THREAD

**Issue by Ignelio6666** [altmp/altv-issues#1202]
### Description of the problem

Cloning ped for pause menu all UI disappear even the client console and radar. But when you alt+tab and go to your second screen all UI's appears. (Webview isOverlay = false doesnt help). Also in activateFrontendMenu, FE_MENU_VERSION_EMPTY_NO_BACKGROUND and FE_MENU_VERSION_EMPTY is the same and dont clear background.

### Reproduction steps

-

### Expected behaviour

UIs should work

### Additional context

// code from snippets

let ped;
let isShowing = false;

async function showChar(){
    if(ped) hideChar();
    
    game.setFrontendActive(true);
    game.activateFrontendMenu(alt.hash("FE_MENU_VERSION_EMPTY_NO_BACKGROUND"), false, -1);
    await waitFor(game.isFrontendReadyForControl);
    
    
    ped = game.clonePed(alt.Player.local.scriptID, 0.0, false, false);
    await waitFor(game.doesEntityExist, ped);

    game.givePedToPauseMenu(ped, 2);
    game.finalizeHeadBlend(ped);
    game.setPauseMenuPedLighting(true);
    game.setPauseMenuPedSleepState(false);
    game.setMouseCursorVisibleInMenus(false);

    alt.setTimeout(() => {
        game.setPauseMenuPedSleepState(true);
    }, 1000);
}

function hideChar(){
    game.clearPedInPauseMenu();
    game.setFrontendActive(false);
}

### Operating system

WINDOWS 10

### Version

6.4 (release)

**Comment by C0kkie** [comment]
@Ignelio6666 @xxshady  test in newest rc

**Comment by Ignelio6666** [comment]
> 

Holy this is so old issue :D I'm no longer coding in altv, so sorry can't test it  :(

**Comment by C0kkie** [comment]
Fixed in v14
