### ISSUE TITLE
vehicle visible setter

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#1203]
### Description of the problem

vehicle visible setter is not working properly

when I set visible  to false, the value changed but vehicle still visible

I also tried with native methods, setEntityAlpha and setEntityVisible they both not working

PS: node sever has the same problem

### Reproduction steps

I tried with JS and C# they both not working

var vehicle = Alt.CreateVehicle(Alt.Hash("Elegy2"), player.Position, Position.Zero)
vehicle.Visible = false;

### Expected behaviour

Vehicle should be invisible when it sets to false

### Operating system

Windows 11

### Version

6.4 (release)

**Comment by juztim** [comment]
test on dev branch please @hookmethods
