### ISSUE TITLE
isKeyDown and isKeyToggled are swapped

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1204]
### Description of the problem

Right now isKeyDown changes it's state on each key press and isKeyToggled returns true only when the key is pressed. So basically they are swapped somehow

### Reproduction steps

```js
setInterval(() => alt.log(`pressed: ${alt.isKeyDown(73)}, toggled: ${alt.isKeyToggled(73)}`), 1000)
```

### Expected behaviour

pressed should be true only when the key is pressed actually
toggle should change it's state on each key press

### Operating system

both windows and linux servers

### Version

7.0-dev16 and 6.4 release

**Comment by FabianTerhorst** [comment]
Fixed in next release.
