### ISSUE TITLE
Clientside netOwner getter always null

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1205]
### Description of the problem

Clientside getter `entity.netOwner` (player & vehicle) always returns null

### Reproduction steps

`alt.log(vehicle.netOwner)` of nearest vehicle or `alt.log(alt.Player.local.netOwner)`

### Expected behaviour

The net owner getter must return the player or null

### Operating system

Windows 10

### Version

7.0-dev17

**Comment by FabianTerhorst** [comment]
Thats because its not implemented clientside.

**Comment by FabianTerhorst** [comment]
The only change i see is to return the local player when the local player is the net owner. But nothing else.

**Comment by YannBCF** [comment]
Confirmed on QA server

**Comment by Rodhin** [comment]
It would be handy if we could check if the local player is the netOwner of the vehicle for some cases, like freezing it's position or using natives on gameEntityCreate event that aren't accessible trough the server side setters.

**Comment by martonp96** [comment]
done in 9.0-dev1
