### ISSUE TITLE
Add server side method to set a vehicle or player frozen

### ISSUE THREAD

**Issue by Rodhin** [altmp/altv-issues#1206]
### Description of the problem

There could be a server side setter/getter or method to set a vehicle or player frozen.

### Desired solution for the problem

Add a server side setter/getter or methods to freeze a vehicle or player, like vehicle.frozen = true or vehicle.freeze()

### Additional context

Heron already mentioned player.freeze() in this issue and I think it could be useful for vehicles too:
https://github.com/altmp/altv-issues/issues/19#issuecomment-473006378

### Version

6.4

**Comment by Rodhin** [comment]
Also this issue by DurtyFree is loosely connected to this:
https://github.com/altmp/altv-issues/issues/354

**Comment by C0kkie** [comment]
There is a event suggestion for it https://github.com/altmp/altv-issues/issues/704
