### ISSUE TITLE
Toggle Mic On/Off Button

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1207]
### Description of the problem

Players have the ability to use push to talk and voice activation. Every communication solution also has push to mute. Simple button to toggle microfon state

### Desired solution for the problem

add a button for user in client so he can toggle his mic on and off without having to mute them serverside

### Alternatives you considered

none

### Additional context

wrote to heron, he told me to open an issue for that. thanks

**Comment by FabianTerhorst** [comment]
v15 has a voice permission for extra voice apis to support this.
