### ISSUE TITLE
Serverside object API

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv-issues#121]
**Is your feature request related to a problem? Please describe.**
Currently you can't create objects serverside. You'd have to create an object on every client. Syncing objects that way is tedious. Placing object on serverside has many usecases as seen in other multiplayer mods (especially, but not limited to, GTA mp mods).

**Describe the solution you'd like**
`alt.createObject(uint model, Position pos, Rotation rot, int dimension = 0);` //returns AltV.Object or similar
`alt.deleteObject(AltV.Object object);`
`alt.deleteWorldObject(Position position, uint modelHash, double radius = 1.0);`

**Describe alternatives you've considered**
You can do it all on client side and spend hours syncing everything yourself. <3

**Comment by 7Hazard** [comment]
I think if the objects state were to contantly be updated, it would be nice to have them synced through the server.

**Comment by datWeazel** [comment]
AltV.Object could have methods like `moveTo(Position pos)` or `attachTo`. Those things aren't currently possible to implement without much work if you want to have every player seeing the object move.

**Comment by FabianTerhorst** [comment]
Dynamic objects are working in v15 on serverside.
