### ISSUE TITLE
--justpack is causing Segmentation fault on 7.0-rc2

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1211]
### Description of the problem

Packing files with:

` ./altv-server --host some.host.com --port 7788 --justpack`

ends in 

`22663 Segmentation fault      ./altv-server --some.host.com --port 7788 --justpack`

on debian 10

### Reproduction steps

pack files on debian

### Expected behaviour

should not throw an error

### Operating system

Debian 10 Linux version 4.19.0-18-amd64 

### Version

7.0-rc2

**Comment by C0kkie** [comment]
Can you try on windows? I can't confirm it there @cmdflow

**Comment by cmdflow** [comment]
Can't confirm on windows (no server running) but on 2 servers running same debian version

**Comment by cmdflow** [comment]
Okay downloaded testversion windows and packed with same ressources. no issue here

**Comment by cmdflow** [comment]
Btw the error is thrown at the end of process. It seems like its packing but then causing a segfault. Not sure if any packages are coruppted but server starts with them and players can connect. So maybe "just cosmetic"

**Comment by C0kkie** [comment]
Hm i can't repro it on my wsl maschine

**Comment by cmdflow** [comment]
No Idea. Redownloaded altv-server binary and tried again but it still throws segfault at the end on two machines (useraccount is non root of course)

**Comment by FabianTerhorst** [comment]
Can you try to run the Server with gdb?

**Comment by cmdflow** [comment]
BTW: Server itself is not crashing when running. Just with pack command it throws segfault on end of packing process

**Comment by cmdflow** [comment]
Friendly reminder: If you want me to start with gdb: Please give me advise how to do so

**Comment by ThomasMarangoni** [comment]
Just use `gdb altv-server`

**Comment by cmdflow** [comment]
That's why i am asking. Running just gdb altv-server gives me:

```
flow@dev:~/fightclub$ gdb altv-server
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from altv-server...(no debugging symbols found)...done.
(gdb)
(gdb)

```

**Comment by ThomasMarangoni** [comment]
@cmdflow please contact me on discord, name: DasChaos#3782

**Comment by cmdflow** [comment]
I sent a friend request. You have to accept it

**Comment by ThomasMarangoni** [comment]
The CDN files are getting generated correctly. Segmentation fault happens after finishing. If this issue needs to be reopened make a comment.

**Comment by Tsumiki-Chan** [comment]
Linux Server 7.0 Release, same error.
```

gameserver_1  | terminate called without an active exception
gameserver_1  | start.sh: line 14:    13 Aborted                 (core dumped) LD_LIBRARY_PATH=${BASEDIR} ./altv-server --host ${SERVER_HOST} --port 7788 --justpack

```

**Comment by slynx-01** [comment]
error on altv-server --justpack

`
  System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 22.99 GB / 50.15 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Managers:
    Apt: 1.8.2.3 - /usr/bin/apt
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 5.0.3 - /bin/bash
    Perl: 5.28.1 - /usr/bin/perl
`

`[11:56:48] alt:V Server 7.1 (release)
[11:56:48] Starting Gameserver on 0.0.0.0:8000
[11:56:48] Packing resource gamemode
[11:56:48] Packed resource gamemode
[11:56:48] Packing resource trainer
[11:56:48] Packed resource trainer
[11:56:48] Packing resource _dlc_greenscreen
[11:56:48] Packed resource _dlc_greenscreen
/usr/app/build_cdn.sh: line 15:   194 Segmentation fault      "${SERVER_PATH}"/altv-server --justpack
[11:56:48] alt:V Server 7.1 (release)
[11:56:48] Starting Gameserver on 0.0.0.0:8000
[11:56:48] Packing resource gamemode
[11:56:48] Packed resource gamemode
[11:56:48] Packing resource trainer
[11:56:48] Packed resource trainer
[11:56:48] Packing resource _dlc_greenscreen
[11:56:48] Packed resource _dlc_greenscreen
[11:56:49] Client resources packed successfully.
[11:56:49] Server shutdown
`

**Comment by slynx-01** [comment]
error on altv-server --justpack

```
  System:
    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 22.99 GB / 50.15 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Managers:
    Apt: 1.8.2.3 - /usr/bin/apt
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 8.3.0 - /usr/bin/gcc
    Git: 2.20.1 - /usr/bin/git
  Languages:
    Bash: 5.0.3 - /bin/bash
    Perl: 5.28.1 - /usr/bin/perl
```

```
[11:56:48] alt:V Server 7.1 (release)
[11:56:48] Starting Gameserver on 0.0.0.0:8000
[11:56:48] Packing resource gamemode
[11:56:48] Packed resource gamemode
[11:56:48] Packing resource trainer
[11:56:48] Packed resource trainer
[11:56:48] Packing resource _dlc_greenscreen
[11:56:48] Packed resource _dlc_greenscreen
/usr/app/build_cdn.sh: line 15:   194 Segmentation fault      "${SERVER_PATH}"/altv-server --justpack
[11:56:48] alt:V Server 7.1 (release)
[11:56:48] Starting Gameserver on 0.0.0.0:8000
[11:56:48] Packing resource gamemode
[11:56:48] Packed resource gamemode
[11:56:48] Packing resource trainer
[11:56:48] Packed resource trainer
[11:56:48] Packing resource _dlc_greenscreen
[11:56:48] Packed resource _dlc_greenscreen
[11:56:49] Client resources packed successfully.
[11:56:49] Server shutdown
```

**Comment by pixlcrashr** [comment]
So, why will this issue not get fixed if there is an actual error to it?

Can be reproduced using the Docker image `eisengrind/altv-server`.

**Comment by ThomasMarangoni** [comment]
The error happens on server exit, everything is finished at this point. So the error is only cosmetic and that's why it doesn't have any priority to fix.

**Comment by FabianTerhorst** [comment]
> So, why will this issue not get fixed if there is an actual error to it?
> 
> Can be reproduced using the Docker image `eisengrind/altv-server`.
> 
> Note that sometimes the server also hangs up when packing files.
> 
> I'll test test the seg fault asap using gdb.

Feel free to paste the gdb output in this issue.
