### ISSUE TITLE
Blip removal is broken on the resource unload

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1215]
### Description of the problem

On the current dev when the resource unloads - it doesn't remove blips

### Reproduction steps

1. Create a blip
2. Reconnect or unload a resource

### Expected behaviour

Created blip should be deleted

### Additional context

That kinda breaks reconnect, cuz after a few reconnects to a server, that creates some blips on load - it will eventually hit the blip limit

### Operating system

windows client xd

### Version

7.0-dev18

**Comment by xxshady** [comment]
I hope this problem has not been lost, as well as the related this one: #1247

**Comment by LeonMrBonnie** [comment]
Fixed in next update
