### ISSUE TITLE
beforePlayerConnect is broken on 7-rc5

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1223]
### Description of the problem

`alt.on('beforePlayerConnect', (player, passwordHash, cdnUrl) => {
player.kick();
});
`
Returns:
`Error beforePlayerConnect > TypeError: player.kick is not a function` and crashes the server 

### Reproduction steps

code is in description of problem

### Expected behaviour

should kick the player and not crash the server

### Additional context

none

### Operating system

Debian

### Version

10

**Comment by C0kkie** [comment]
@cmdflow  there was changes in this event. Check the updated typings

**Comment by cmdflow** [comment]
So there is no player object anymore?
