### ISSUE TITLE
C# Server crash on connect

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#1225]
### Description of the problem

Server crashes when a player connects. No logs, nothing. Just the server ending.

### Reproduction steps

Download latest nugets(prerelease), download altV dev version from website(server). then run server and then connect to it.

Make sure server is using C# module.

I use debug API, not sure if this matters.

### Expected behaviour

Server to not crash

### Operating system

Windows 10

### Version

latest dev

**Comment by LeonMrBonnie** [comment]
Please open an issue in the C# module repo, as this is related to the module, not alt:V itself.
https://github.com/FabianTerhorst/coreclr-module
