### ISSUE TITLE
SetDateTime no longer working

### ISSUE THREAD

**Issue by DisturbedNoob** [altmp/altv-issues#1227]
### Description of the problem

![altv-server 01 12 2021 00_13_18](https://user-images.githubusercontent.com/67128126/144143335-e368afe6-8ef8-4db8-bfad-63d68f032667.png)

> foreach (IPlayer player in Alt.GetAllPlayers())
> {
>    if (!player.Online) { continue; }
>    player.SetDateTime(DateTime.Now.Day, DateTime.Now.Month, DateTime.Now.Year,DateTime.Now.Hour,DateTime.Now.Minute, DateTime.Now.Second);
> }

### Reproduction steps

Set Time after Client is connected serverside (C#)

### Expected behaviour

SetDate sets Time for Client/Player

### Operating system

Win 10 Pro 

### Version

release/7.1

**Comment by C0kkie** [comment]
Month starts at 0, so you need to use 11 instead of 12

**Comment by DisturbedNoob** [comment]
Before 7.1 it was working fine

**Comment by EtzBetz** [comment]
> Before 7.1 it was working fine

Because until 30 minutes ago, the month was `11`, now it's `12`, which isn't valid. Input value ranges from 0-11.

**Comment by C0kkie** [comment]
That change was already introcuded in 6.0. So change your code and it will work
