### ISSUE TITLE
Cloth and appearance missmatch log as parameter in config

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1228]
### Description of the problem

currently, the missmatch logs are only logged in server debug mode. To see if there are any missmatches in live operation, this is not really possible with the current way. Therefore it would be cool if it is not set to the debug mode, but a config parameter from the server.cfg.

### Desired solution for the problem

Add a new property to server.cfg

### Version

7.1 release

**Comment by FabianTerhorst** [comment]
Fixed in next release.
