### ISSUE TITLE
Password validation when password isn't set in the server.cfg

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1229]
### Description of the problem

Right now if you don't set any password in the server.cfg and will enter something in the password field - connection fails with "Wrong password" message

### Reproduction steps

1. Don't set password in the cfg
2. Provide password in connection window

### Expected behaviour

Any password should be allowed, so the server can validate it manually using beforePlayerConnect event

### Operating system

Any

### Version

release/7.1

**Comment by C0kkie** [comment]
Fixed in 9.0-dev1
