### ISSUE TITLE
native.getShapeTestResult[1] returns number instead of boolean

### ISSUE THREAD

**Issue by Fyers** [altmp/altv-issues#1232]
### Description of the problem

`getShapeTestResult` returns in [1] per documentation type boolean. https://natives.altv.mp/#/0x3D87450E15D98694

It will actually return an number with 0 and 1 instead of true and false which in JS/TS will be fine, but sending this value over an event to the server and parsing in C# now is different compared to <7.0 and would be a breaking change.

`bool.TryParse` on server now will now fail since an number (instead of "true" or "false") is passed.

### Reproduction steps

```
let pos = alt.Player.local.pos;
let ray = native.startShapeTestCapsule(pos.x, pos.y, pos.z - .75, pos.x, pos.y, pos.z - .5, 1, 1, 0, 7);
let result = native.getShapeTestResult(ray, undefined, undefined, undefined, undefined);

console.log("ActualType: " + typeof (result[1]), result[1]);
console.log("ExpectedType: " + typeof (true), true);
```

This will print
```
[17:39:03] ActualType: number 1
[17:39:03] ExpectedType: boolean true
```

### Expected behaviour

Result should be of type boolean or native-db updated

### Operating system

Windows 10

### Version

release/7.1

**Comment by LeonMrBonnie** [comment]
The NativeDB is an external project and not managed by the alt:V team, please open an issue about it there.

**Comment by Fyers** [comment]
> The NativeDB is an external project and not managed by the alt:V team, please open an issue about it there.

Isn't this an breaking native change, if the native has returned boolean before and now is returning number instead.
It was not marked as breaking change and idk if other return types of boolean now actually are numbers since the update.

**Comment by LeonMrBonnie** [comment]
@DurtyFree 
Maybe it was some issue in the native data generation.

**Comment by Rodhin** [comment]
I can confirm this too, I had to change my result checks to check for 1 instead of boolean true. Before 7.x it was returning a boolean, after 7.x it's returning a number with 0 or 1.

**Comment by ThomasMarangoni** [comment]
Natives are written in c/c++, there is no bool by default in these languages. But normally 1 is interpreted as true and 0 as false.

C# on the other hand has bool as default type. But the Method Convert.ToBoolean(i); can also accept numbers. So you should use this method instead of yours.

**Comment by DurtyFree** [comment]
This change could be very much related to the nativedb json types having changed (Maybe due to some changes done in the generator, not sure yet)

**Comment by C0kkie** [comment]
Thats fixed since few months
