### ISSUE TITLE
AltV Voice LipSync not working

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1233]
### Description of the problem

Lipsync is not working in 7.1-release branche

### Reproduction steps

Talk to another person with altv voice. Lips on yourself are moving, lips on other player are not moving

### Expected behaviour

Lipsync should be synced and was before

### Operating system

Debian 10 Linux version 4.19.0-18-amd64 

### Version

10

**Comment by tastydev** [comment]
will be fixed with #112  i guess

**Comment by FabianTerhorst** [comment]
has nothing to do with 112

**Comment by tastydev** [comment]
nvm then

**Comment by cmdflow** [comment]
just as information: not fixed in 7.2

**Comment by C0kkie** [comment]
Just check the changelogs or this issue if we changed something, you dont need to update it for every release @cmdflow

**Comment by LeonMrBonnie** [comment]
Fixed and will be part of Update 9
