### ISSUE TITLE
Listeners 'vehicleAttach' and 'vehicleDetach' aren't working properly

### ISSUE THREAD

**Issue by Hutstaender** [altmp/altv-issues#1235]
### Description of the problem

Both listeners arent working properly, when first called at new spawned vehicles. 
They work correctly after you leave streaming range or change dimension like shown in this short example video:
(the code snippet for the logs is shown below and the inserted console.logs are shown in the video right above the minimap)
https://www.dropbox.com/s/ok7reqkwb567h8s/6IsMp3IeBO.mp4?dl=0

### Reproduction steps

1. Add the listeners with this snippet:

```
                alt.on(
			'vehicleAttach',
			(vehicle: alt.Vehicle, attachedVehicle: alt.Vehicle) => {
				console.log('Listener vehicleAttach fired');
			}
		);
		alt.on(
			'vehicleDetach',
			(vehicle: alt.Vehicle, detachedVehicle: alt.Vehicle) => {
				console.log('Listener vehicleDetach fired');
			}
		);
```

2. use any tow vehicle "phantom" and spawn a fresh towed vehicle like the "trailers"
3. enter the phantom and try to attach and detach the trailers -> both listeners 'vehicleAttach' and 'vehicleDetach' arent reacting.
4. after leaving the streaming range OR after you change dimension, the trailers will get teleported to its first location like it wasnt even attached.
5. attach and detach again -> both listeners are working correctly.

### Expected behaviour

fire both listeners right after creating a vehicle

### Additional context

No Response

### Operating system

Windows

### Version

release/7.1

**Comment by yoranjj** [comment]
I can't seem to reproduce the "the trailers will get teleported to its first location" bug?

https://www.dropbox.com/s/vluvtor2b1yhfp5/i9jsCBneVk.mp4?dl=0

**Comment by Hutstaender** [comment]
@yoranjj yea, the teleport may be because we lock the clutch on spawn of the trailers. I just tested it and found out, that the clutch somehow isn't working properly. Currently i don't know if this is an issue in our scripts or an vehicle api issue.

**Comment by Hutstaender** [comment]
Just tested everything out, and somehow theres a netowner problem when spawning vehicles. Right after spawn the netowner is null. Both in this issue mentioned issues are solved by applying a netowner change right after spawn:

vehicle.setNetOwner(player, true); <- Mitigation has to be "true" otherwise the problem will sometimes appear again.

**Comment by FabianTerhorst** [comment]
There is a reason why its null while spawning. I don't recommend changing that.

**Comment by Hutstaender** [comment]
And what would be a better solution? Somehow all vehicles wont act synced when i wont do that.

this also applies to spawned vehicles -> spawn -> destroy or move without entering -> leave streaming range and reenter -> vehicle is still at spawned position with full health

**Comment by tastydev** [comment]
> Just tested everything out, and somehow theres a netowner problem when spawning vehicles. Right after spawn the netowner is null. Both in this issue mentioned bugs are solved by applying a netowner change right after spawn:
> 
> vehicle.setNetOwner(player, true); <- Migration has to be "true" otherwise the problem will sometimes appear again.

Can you explain it further? Cause when no player is in the streamingrange while spawning the vehicle it is normal that the netOwner is `null` until a player enters the streamingrange cause then the migration system will automatically swap the ownership to the nearest player respecting the migrationDistance. I did some tests on my local testserver and the ownership system seems to work right. Serverside spawn -> nearest player gets ownership, Serversidespawn -> no player in migrationDistance -> netOwner `null`. Those tests behaved correctly. It might be possible that you are encountering a bug introduced by your script by using manual migration.

**Comment by Hutstaender** [comment]
I just did some further testing, and this are the results:

Spawning a vehicle right beside me will result in a netowner of null after 5 seconds

https://i.imgur.com/MHu0nYI.png

even if i change the dimension and go back the netowner stays null 

https://i.imgur.com/1MK3ha1.png

**Comment by yoranjj** [comment]
> I just did some further testing, and this are the results:
> 
> Spawning a vehicle right beside me will result in a netowner of null after 5 seconds
> 
> https://i.imgur.com/MHu0nYI.png
> 
> even if i change the dimension and go back the netowner stays null
> 
> https://i.imgur.com/1MK3ha1.png

This doesn't seem to be the case for me, I spawned a vehicle started a 1 second loop, and logged the netowner. It was never null after 5 seconds.

**Comment by Hutstaender** [comment]
Hmm Something in our script seems to fuck up our whole netOwner migration, passively. This behaviour is also present in a patch state of our Code from January running with AltV version 7. (in previous AltV version everything worked fine) I need to dive deeper and hopefully find the trigger for this fuckery.

**Comment by tastydev** [comment]
> 

Can confirm it, they have nothing netOwner/migration related stuff in their gamemode but something seems to break the migration. Vehicles getting only migrated when entering vehicles as a driver in their gamemode. Something is breaking the migration system since alt:V Version 7.X.  BTT: `vehicleAttach` event is not firing on first hooking is confirmed for me on a clean freeroam gamemode

**Comment by FabianTerhorst** [comment]
Small note: Its mandatory to call spawn on a player that can freely move in the world.

**Comment by FabianTerhorst** [comment]
When he isn't spawned the system will also think that he isn't spawned.

**Comment by Hutstaender** [comment]
@FabianTerhorst Uff, we did not use player.spawn() in some of our login cases. Instead some cases used player.pos to teleport.  Changing all teleports right after login to a player.spawn() in every case fixed both, the migration issue and the 'vehicleAttach' and 'vehicleDetach' issue. Thanks for your help!
