### ISSUE TITLE
alt.hashServerPassword returning wrong Password hash

### ISSUE THREAD

**Issue by Chapodev** [altmp/altv-issues#1237]
### Description of the problem

If we try to prevent a Player from connecting with a wrong password by using the "alt.hashServerPassword()" function,
the return of the function always contains the 'n' character at the end.

If we compare the values like in the alt:V Docs, currently the User would always get kicked when connecting to the Server.

### Reproduction steps

Server is JS based.

```
alt.on('beforePlayerConnect', (connectionInfo) => {
	console.log('process.env.SERVERPASSWORD -> ', process.env.SERVERPASSWORD);
	console.log('connectionInfo.passwordHash -> ', connectionInfo.passwordHash);
	console.log('alt.hashServerPassword(process.env.SERVERPASSWORD) -> ', alt.hashServerPassword(process.env.SERVERPASSWORD));
	console.log('alt.hashServerPassword(process.env.SERVERPASSWORD) -> ', alt.hashServerPassword('1337'));
	console.log('alt.hashServerPassword(process.env.SERVERPASSWORD) -> ', alt.hashServerPassword('abcd'));
	console.log('alt.hashServerPassword(process.env.SERVERPASSWORD) -> ', alt.hashServerPassword('kekw1337"()§§§$'));
	
	if (process.env.SERVERPASSWORD) {
		if (connectionInfo.passwordHash !== alt.hashServerPassword(process.env.SERVERPASSWORD)) {
			return false;
		}
	}
	return true;
});
```

### Expected behaviour

Value of "connectionInfo.passwordHash" by using password '1337' should be the same value as return of "alt.hashServerPassword('1337')" without character 'n' at the end

### Additional context

Console output
```
process.env.SERVERPASSWORD ->  1337
connectionInfo.passwordHash ->  10592054399825886747
alt.hashServerPassword(process.env.SERVERPASSWORD) ->  10592054399825886747n
alt.hashServerPassword(process.env.SERVERPASSWORD) ->  10592054399825886747n
alt.hashServerPassword(process.env.SERVERPASSWORD) ->  15997673941747208908n
alt.hashServerPassword(process.env.SERVERPASSWORD) ->  2585348683601667219n

```

### Operating system

Ubuntu 20.04.3 LTS (Focal Fossa)

### Version

release-7.2

**Comment by zziger** [comment]
Just for the info - `n` at the end of number means, that the value is BigInt. But well the values still should be of one type (both as BigInts or both as strings), so it's a js module bug

**Comment by LeonMrBonnie** [comment]
The `n` at the end just indicates that it is a bigint. So it works as expected.
We just accidentally set the passwordHash in the connection info as a string instead of a bigint, but this was now fixed in https://github.com/altmp/altv-js-module/commit/6b23b045139652515fff3737060554ce2e4253be
