### ISSUE TITLE
Unexpected behaviour of Alt.Server.Version in linux

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1238]
### Description of the problem

In windows Alt.Server.Version; working perfect, but in linux Ubuntu iš shows some kind of symbols.
![image](https://user-images.githubusercontent.com/40861802/144692347-9c350233-2419-414d-aabc-69172c545378.png)

### Reproduction steps

Alt.Log($"Alt:V versija: {Alt.Server.Version}");

### Expected behaviour

Should be string or numbers.

Windows: 
![image](https://user-images.githubusercontent.com/40861802/144692484-35873cb6-e3ba-45e9-b3d3-39dee90b77c9.png)

### Operating system

Ubuntu 20.04

### Version

7.2

**Comment by TheFruchtiHD** [comment]
Can confirm on 7.2 on Debian 10. Looks like Alt.Server.Branch has the same problem.

**Comment by FabianTerhorst** [comment]
Fixed in next version.
