### ISSUE TITLE
Slippery/tripping/falling in snow not synced

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1239]
### Description of the problem

When using xmas weather (ID 13) there are some areas on the map where players can lose their footing in the snow and trip/slip or fall. When this happens for the local player, the animation etc works fine. But other players just see you floating around abit while stuck in a half-falling animation or something.

### Reproduction steps

- Enable snow weather (ID 13)
- Find some areas where a player can trip/fall over from snow
- Get a 2nd player to watch it

### Expected behaviour

Animation stuff should sync properly.

### Additional context

This is probably very minor, but wanted to report it nonetheless.

### Operating system

Ubuntu 20.04

### Version

release 7.2

**Comment by C0kkie** [comment]
Does this still happen? Also send us some positions where it happens in which areas

**Comment by CoffeeGen** [comment]
Errr, it's been a long time since I reported this bug. I have no idea if this still happens lol.

If I remember correctly, it happened on those areas in the northern part of the city where there's like these grass patches in the middle of the road between each lane, sometimes they have these palm trees on them too. Pretty sure it happened in that area. 

Might also happen in other areas, although I can't confirm that. Also can't confirm if the bug still exists

**Comment by C0kkie** [comment]
Then i will close it for now, if it still happens someone can open it
