### ISSUE TITLE
"setHornEnabled" (native) doesn't work 

### ISSUE THREAD

**Issue by PluginYML** [altmp/altv-issues#1240]
### Description of the problem

Hello, I am currently trying to press the horn on a vehicle using any hotkey. I looked at the native methods and tried a few. Unfortunately none of them worked, and I think the `setHornEnabled` method should do what it says. Unfortunately, I cannot play the horn with this method? Is that supposed to be the case or is the method intended for something else?

Important: I also want to play the horn when the player is in the vehicle.

### Reproduction steps

- / -

### Expected behaviour

That the horn works until I turn false.

### Operating system

Linux

### Version

release/7.2

**Comment by deluvas1911** [comment]
This is not an issue with the native but a wrong usage of the native.
The native basically does what it says: if you setHornEnabled to false nothing happens when you press E until you set it to true again
The native you're looking for is startVehicleHorn
