### ISSUE TITLE
External voice server does not reconnect

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1241]
### Description of the problem

External voiceserver does not reconnect on _SERVER SIDE_
Once the connection is lost, its over until your restart your gameserver.

### Reproduction steps

Have 2 hosts. A gameserver and a voiceserver. Stop voiceserver and start it again. Client reconnects but gameserver does not. So voice is dead...

### Expected behaviour

Should reconnect on connection loss

### Operating system

Debian 10 Linux version 4.19.0-18-amd64 

### Version

10

**Comment by R3DIANCE** [comment]
https://github.com/altmp/altv-issues/issues/566

**Comment by cmdflow** [comment]
I dont think so because i do not have to restart the voice server. I have to restart the GAME server to reconnect again

**Comment by FabianTerhorst** [comment]
Duplicate of #566

**Comment by FabianTerhorst** [comment]
We will add reconnect on connection lost from one of the servers to another soon.
