### ISSUE TITLE
Serverside blip attached to entity is not deleted with entity

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1247]
### Description of the problem

Attached to entity blip is not deleted after the entity is deleted. 

When reconnecting after deleting an entity, an error is displayed in the client console:
![image](https://user-images.githubusercontent.com/54737754/145383248-df0a2512-d5b0-4a22-ac24-33e09543d6c5.png)

### Reproduction steps

```js
const veh = new alt.Vehicle('sultan2', 0, 5, 72, 0, 0, 0);
new alt.PointBlip(veh);
alt.setTimeout(() => veh.destroy(), 1500);
```

### Expected behaviour

Attached blip should be deleted together with the deleted entity

### Operating system

Windows 10

### Version

8.0-dev2

**Comment by C0kkie** [comment]
I think its related to the blip api itself, because blips also dont get deleted on reconnect

**Comment by LeonMrBonnie** [comment]
This was probably fixed with #1215

**Comment by xxshady** [comment]
Still can confirm on dev/10.0-dev3

**Comment by martonp96** [comment]
if you create blips manually you have to delete blips manually
