### ISSUE TITLE
Colshapes crash the server randomly

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1249]
### Description of the problem

Colshapes can randomly crash the server on enter (in my case with vehicle).

Not sure what happens. I talked to Heron/Zigger about this on discord about a week ago. Zigger told me there had been some tests to find it but no results etc. So might aswell put it here.

### Reproduction steps

- Create a colshape
- listen for enter event and delete colshape in enter event
- go thru colshape with vehicle

In my case, when a player enters colshape, it deletes the colshape and spawns a new one elsewhere.

### Expected behaviour

Server to not crash

### Additional context

I use C# module

### Operating system

Ubuntu 20.04

### Version

latest release 7.4

**Comment by C0kkie** [comment]
Do you use async for it?

**Comment by CoffeeGen** [comment]
> Do you use async for it? Also afaik its a issue in the c# module not in alt:V in general

Async yeah, I create the colshapes in main thread(RunOnMainThread) then async them via async context everywhere else.

**Comment by FabianTerhorst** [comment]
Fixed in next Update. Feel free to comment when its Not.
