### ISSUE TITLE
Event not getting triggerd

### ISSUE THREAD

**Issue by paviln** [altmp/altv-issues#1252]
### Description of the problem

When a player in a vehicle drives into a colshape, the event entityEnterColshape is not triggered. The event is only triggered when a player or vehicle enters it alone, but not at the same time.

### Reproduction steps

1. Create a new Colshape.
2. Subscribe on the entityEnterColshape.

### Expected behaviour

- Player in vehicle enters colshapem trigger entityEnterColshape with callback entity being a vehicle.

In the special case were playersOnly is true.
- Still trigger when player drives vehicle into colshapem, but callback entity being a player.

### Additional context

Check example where it happens https://github.com/paviln/alt-example

### Operating system

Windows 10

### Version

7.3 (release)

**Comment by tastydev** [comment]
invalid everything is working.

```Javascript
const shape1 = new alt.ColshapeSphere(525.5736, -332.1758, 43.0125, 5);
shape1.playersOnly = true;
shape1.name = "PlayersOnlySphere";
const shape2 = new alt.ColshapeSphere(580.3253, -361.3978, 43.0125, 5);
shape2.name = "PlayerAndVehicleSphere";

alt.on('entityEnterColshape', (colshape, entity) => {
  console.log('entityEnterColshape', colshape.name, entity.type);
});

alt.on('entityLeaveColshape', (colshape, entity) => {
  console.log('entityLeaveColshape', colshape.name, entity.type);
});
```

`shape1` fires only for the player even when driving through with a vehicle

`shape2` fires for both when driving through with a vehicle

so everything is working as intended

btw if u want to execute different scripts for different entity types for `shape2` your listener could look like this for example:

````
alt.on('entityEnterColshape', (colshape, entity) => {
  if(entity instanceof alt.Player){
        //player related colshape enter code
  }
  if(entity instanceof alt.Vehicle){
        //vehicle related colshape enter code
  }
});
```

**Comment by C0kkie** [comment]
We also use it on our server and the problem is definitive on your end

**Comment by paviln** [comment]
> 

I tested it on my end, and your code does indeed work, the only difference is that you are using ColshapeSphere, and I was using  ColshapeCylinder. The ColshapeCylinder seems not to work how I thought it would, as the pos is not in the center of it. I guess ColshapeSphere pos is in the center? And that if the pos is a point on the ground, only half of it is visible?
