### ISSUE TITLE
Rotated colshapes

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1253]
### Description of the problem

Current rectangle and cuboid colshapes are aligned perpendicularly to the axis, but it's often needed to rotate them

### Desired solution for the problem

.rot property of colshape, or a new type of colshapes that either takes a rotation, or takes more than two points

### Alternatives you considered

:c

### Version

release/7.3

**Comment by gt4ever1988** [comment]
I would also find this feature very good.

**Comment by zziger** [comment]
I think it's kinda useless now, because of #1313 implemented
