### ISSUE TITLE
[UX] Reconnect Button in Debug Mode on Disconnect

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1259]
### Description of the problem

When you disconnect from a development server with debug on you are not prompted about what you can do after you disconnect. 

### Desired solution for the problem

I suggest instead of having users type `reconnect` every single time that they are given a `reconnect` button and the additional button from this request: https://github.com/altmp/altv-issues/issues/1258

**Comment by C0kkie** [comment]
Added in release/8.5
