### ISSUE TITLE
Allow player.Emit to return something

### ISSUE THREAD

**Issue by datWeazel** [altmp/altv-issues#126]
**Describe the solution you'd like**
Would be nice to have player.Emit return something.

You could use this to get game information from a specific client. e.g. the ground z coord to a given x and y coord. Or the "street-length" between two positions. 

One example usage could be: 
```csharp
//Server
var distance = player.Emit("getGPSdistance", position1, position2);
```

```javascript
//Client
alt.on("getGPSdistance", (pos1, pos2) => { 
return game.calculateTravelDistanceBetweenPoints(pos1.x, pos1.y, pos1.z, pos2.x, pos2.y, pos2.z); 
});
```

Other usecases include:

- getting Zone/Region and Street Names at a given position
- getting detailed information about player state (https://github.com/altmp/altv/issues/85)
- getting player information like screen size or screen safezone size

**Comment by martonp96** [comment]
You can already do this by emitting an event as a reply.
