### ISSUE TITLE
[UX] Install alt:V in %appdata% by Default

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1260]
### Description of the problem

Users are often installing alt:V in the wrong location. I believe the wording of the installation instructions and where it is installed is the problem.

### Desired solution for the problem

Ideally we just install it in %appdata% and then most users won't be confused about where to install alt:V itself. Since it'll be the most recommended place for installation and isn't in an obscure place like `c:/altv`.

**Comment by datWeazel** [comment]
Using %appdata% as the install location for alt:V means that alt:V will use the C: drive. I know it's 2021 (nearly 2022) but there are still people with small SSDs as their C: drive. Some people (like me) also just simply don't like programms installing themselves to obscure locations and rather use manually selected installation paths (e.G. most of my games are on D:\Games while software is on D:\Software and so on) 

At the very least, give an option to specify another install location on first start.

**Comment by FabianTerhorst** [comment]
It will be optional when its implemented.

**Comment by Stuyk** [comment]
@datWeazel It's better to put it in the right place first and let the advanced users figure out where they want to put it. Steam doesn't recommend optional drives right away unless you look for it.

**Comment by FabianTerhorst** [comment]
The new launcher version allows installing to appdata folder.
