### ISSUE TITLE
[UX] More Descriptive Error Messages

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1261]
### Description of the problem

Instead of saying something like `altv-client.dll` can't be loaded. It would wise to supply some information about common solutions or a link to the Trouble Shooting Documentation to help resolve it.

![](https://i.imgur.com/m6g9DWP.png)

### Desired solution for the problem

* Description of what to do as a common remedy in the error itself.
* A link to the Trouble Shooting Article
* Always check if the client is being ran as Admin

**Comment by zziger** [comment]
Maybe it's worth to do it not in the message box, but in some fancy error box, e.g. like fivem does it. That way it will be able to add some action buttons (button to restart altv as administrator?), or even a link to a troubleshooting page.

**Comment by FabianTerhorst** [comment]
> Maybe it's worth to do it not in the message box, but in some fancy error box, e.g. like fivem does it. That way it will be able to add some action buttons (button to restart altv as administrator?), or even a link to a troubleshooting page.

Maybe with reworked launcher ui.

**Comment by C0kkie** [comment]
Will be improved in launcher rework
