### ISSUE TITLE
Galaxy nightclub interior/IPL broken since 7.0 update

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1263]
### Description of the problem

the galaxy nightclub interior worked fine before 7.0, but after the update the interior won't load anymore, the collision is there and some objects but the walls etc aren't loading.

I talked with YANN about this, he (and other devs?) confirmed this bug and could possibly be related to a pool change?

### Reproduction steps

Load the galaxy nightclub IPL via snippet below
```
natives.requestScriptAudioBank( "DLC_BATTLE/BTL_CLUB_OPEN_TRANSITION_CROWD", false, -1 );
            natives.setAmbientZoneState( "IZ_ba_dlc_int_01_ba_Int_01_main_area", false, false );

            natives.startAudioScene( "DLC_Ba_NightClub_Scene" );
            natives.playSoundFrontend( -1, "club_crowd_transition", "dlc_btl_club_open_transition_crowd_sounds", true );

alt.requestIpl( "ba_int_placement_ba_interior_0_dlc_int_01_ba_milo_" );
```

### Expected behaviour

Should load fine

### Operating system

Windows and linux

### Version

latest release 7.*

**Comment by FabianTerhorst** [comment]
Afaik already fixed.

**Comment by CoffeeGen** [comment]
Is not fixed. Tested just now on latest release.
