### ISSUE TITLE
Implement logrotation in the server

### ISSUE THREAD

**Issue by Rodhin** [altmp/altv-issues#1264]
### Description of the problem

It would be nice if the server could rotate the logfiles.

### Desired solution for the problem

There should be a logs folder where the server should keep the timestamp rotated log files. There could be a config value to how much files the server should keep before deleting the older ones.

### Alternatives you considered

In linux, it is possible to use cat, tee and pipe the output to timestamp named logfiles, it's even possible to rotate them via the system's logrotation but it would be nice if the server could do this platform-independently.

**Comment by Rodhin** [comment]
Just found this issue, it's nearly the same request: #369

**Comment by C0kkie** [comment]
Yep and there is explained how to do it
