### ISSUE TITLE
Tuning @ Dominator8

### ISSUE THREAD

**Issue by CitroneTwitch** [altmp/altv-issues#1265]
### Description of the problem

The Dominator8 (Dominator GTT) have many Tuning Options. The tuning parts of the Dominator 8 (Dominator GTT) are completely AltV-side mess. That means that all tuning scripts currently only have to be completely rewritten for the Dominator8 so that it can be tuned.

### Reproduction steps

*

### Expected behaviour

*

### Additional context

*

### Operating system

All

### Version

Since GTA Summer Update Implement Dominator8

**Comment by FabianTerhorst** [comment]
Didnt follow issue template.
