### ISSUE TITLE
OnPlayerWeaponChange is called on connect

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1267]
### Description of the problem

The OnPlayerWeaponChange event is always called as soon as a player connects to the server.

No idea if this is intentional or not, just seemed a little off.

### Reproduction steps

Add a log to the event and join the server

### Expected behaviour

Not to call the event

### Additional context
I'm running C# module, async resource

### Operating system

Windows 10

### Version

Latest release 7

**Comment by zziger** [comment]
Cannot reproduce on 9.0-dev5 using JS, can you please try reproducing it on an empty server, or confirming that the issue happens only on C# module?

**Comment by zziger** [comment]
We couldn't reproduce that bug on both JS and C#
