### ISSUE TITLE
Server crashes when player connects and the entity id limit is reached

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1268]
### Description of the problem

alt:V entities (players & vehicles) limit is 8192. If you take all id slots except the last one (for e.g. spawn 8191 vehicles) and one player connects to the server, then he will take the last slot. Everything will be fine until that player decides to disconnect (release his id slot) and go back to the server (return his id slot), then the server will crash after the "entity id" error

![image](https://user-images.githubusercontent.com/54737754/146679456-b391915f-9982-40f3-a8a9-b77ad44eb196.png)

### Reproduction steps

1. 
```js
for (let i = 0; i < 8191; i++) {
  new alt.Vehicle("sultan2", 10_000, 0, 0, 0, 0, 0)
}
```
2. Connect one player
3. Reconnect player
4. Server crash after entity id error

### Expected behaviour

The player must return his id back when reconnecting to the server

### Operating system

Windows

### Version

8.0-dev4

**Comment by FabianTerhorst** [comment]
Fixed next update

**Comment by xxshady** [comment]
> Fixed next update

@FabianTerhorst is it normal that when player reconnects at first time server dont gives that player last free id, but in second time everything fine?
