### ISSUE TITLE
Vehicle machine gun aim bug

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1269]
### Description of the problem

  https://user-images.githubusercontent.com/27638710/146690055-83ae6ebd-50d9-47b0-9ed1-c504761a8ffb.mp4

### Reproduction steps

1. Spawn valkyrie, barrage, halftrack, caracara, insurgent, insurgent3 or any other vehicle that has a machine gun
2. Sit in the machine gun seat
3. Try to shoot

### Expected behaviour

Aiming shouldn't be buggy

### Operating system

Windows

### Version

release/7.4

**Comment by yoranjj** [comment]
Seems to work fine on release 8.4, maybe an issue on your end?

**Comment by zziger** [comment]
Seems to be our local issue

**Comment by zziger** [comment]
For anyone that will have the same problem and found this issue:
For us that issue was related to the fact that isPedShooting is true while player shoots using the vehicle weapons too, but player.currentWeapon is 0, which lead to an error in our logic 😄
