### ISSUE TITLE
getVehicleEngineHealth broken after update

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1271]
### Description of the problem

Sometimes getVehicleEngineHealth returns 1148846080

### Reproduction steps

```
alt.on("enteredVehicle", (vehicle, seat) => {
	alt.log("getVehicleEngineHealth", game.getVehicleEngineHealth(alt.Player.local.vehicle.scriptID));
});

```
Chance of reproduce 25%
1.Spawn police2
2.Get output "getVehicleEngineHealth 1148846080"
If output is 1000, try different vehicles

### Expected behaviour

getVehicleEngineHealth returns value not bigger than 1000

### Additional context

I dont know how to reproduce it, but to be clear i've spawned custom emergency car and get  this crazy health value, after that i sit in "oracle" and got the same value
after server restart oracle health is ok, but police 2 now is b roken

### Operating system

Windows 11

### Version

release 8.2

**Comment by FabianTerhorst** [comment]
Fixed next update.
