### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by burakhanoztas** [altmp/altv-issues#1274]
### Description of the problem

On the server-side, there is no problem when the "host" value in the "config.cfg" file is changed to IPv6.
> server.cfg
> ```cfg
> host: "[::1]"
> or
> host: "[::]"
> or
> host: "0.0.0.0"
> ```
On the client-side, it can only connect with IPv4.
> Client console:
> ```
> [13:20:48][Error] HTTP Request failed, curl code: 3
> [13:20:48][Error] Connection failed: Error connecting to HTTP server
> ```

### Desired solution for the problem

IPv6 support should come!

### Version

release/8.3

**Comment by pixlcrashr** [comment]
Very important!

**Comment by FabianTerhorst** [comment]
please provide the value you entered into the input.

**Comment by FabianTerhorst** [comment]
I tested
```
http://[::1]:7788/
```
and it worked

**Comment by burakhanoztas** [comment]
> I tested
> 
> ```
> http://[::1]:7788/
> ```
> 
> and it worked

I tested it, it doesn't work.
> ```
> [Error] Connection failed: Server not responding
> ```
Can you write down your transactions one by one?

**Comment by pixlcrashr** [comment]
> > I tested
> > ```
> > http://[::1]:7788/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and it worked
> 
> I tested it, it doesn't work.
> 
> > ```
> > [Error] Connection failed: Server not responding
> > ```
> 
> Can you write down your transactions one by one?

I mean, I know it is a basic question but does any of your network interfaces have an IPv6 address assigned?

**Comment by FabianTerhorst** [comment]
I used a localhost running ipv6 to ipv4 proxy

**Comment by FabianTerhorst** [comment]
cdn is in general independent of the altv server and the client http client seems to support ipv6.

**Comment by burakhanoztas** [comment]
I have an IPv4 and IPv6 address.
I'm not having problems with IPv6.
The server is running on windows.
I am not using CDN and I am working on local.
I have no problems with IPv6 on the FiveM platform and with all general applications.
Can you prove that it works with IPv6? @FabianTerhorst

**Comment by FabianTerhorst** [comment]
I can only test emulated ipv6 since i dont have ipv6 support.

**Comment by burakhanoztas** [comment]
alt:V developer team needs to review this situation.

**Comment by C0kkie** [comment]
Should be fixed in dev/14.0-dev13

**Comment by zziger** [comment]
Fixed in dev/15.0-dev585

Specifying `[::]` as a host, and connecting via `[::1]:7788` works now

**Comment by burakhanoztas** [comment]
I tried, but it's not working.
```
[18:10:51] Game version: 2944 on Social Club
[18:10:51] [WEB] Initialized Web API
[18:10:51] CreateEnumeratorFromKey
[18:10:51] MoveNext 0 false
[18:10:51] [object Proxy]
[18:10:51] [object Proxy]
[18:11:08] Connect [::1] 7788    
[18:11:08] Finished downloading all resources
[18:11:08] Download finished
[18:11:12] All natives DLC packs preloaded
[18:11:21][Error] HTTP Request failed, curl code: 7
[18:11:33] Loaded font face 'rmlui-debugger-font' [regular] from 'memory'.
[18:11:33] Loaded font face 'rmlui-debugger-font' [italic] from 'memory'.
[18:11:33] Loaded font face 'rmlui-fallback-font' [regular] from 'memory'.
[18:11:33] Loaded font face 'rmlui-fallback-font' [italic] from 'memory'.
[18:11:34] alt:V Multiplayer started
[18:11:34] Started in 52488 ms
[18:11:34] Connecting to: [::]:0
[18:11:44][Error] Connection failed: Server not responding
```

**Comment by zziger** [comment]
Hi @burakhanoztas! I have reworked a lot of IP related stuff, and since `dev/15.0-dev593` IPv6 addresses should be fully supported now.

Set your host in server config to `::` (without brackets)
Connect via `::1`, `[::1]`, or `[::1]:7788` (brackets are optional, but required when you want to specify port)

**Comment by zziger** [comment]
With `dev/15.0-dev594` specifying `[::]` as host is now accepted too.
Host `::` supports both IPv4 and IPv6 connections, and is now made default (if not specified in config) for out-of-the-box IPv6 support

**Comment by burakhanoztas** [comment]
👋🏻 Hi @zziger,

🙌🏻 First of all, I want to thank you for everything. Currently, I'm not experiencing any issues with IPv6 testing. However, when trying to connect to the server, I encounter the `HTTP Request failed, curl code: 7` error. I don't think this problem is related to IPv6. It seems to be present on the IPv4 side as well. Perhaps you could take a look.

💪🏻 Thank you.

**Comment by zziger** [comment]
> 👋🏻 Hi @zziger,
> 
> 🙌🏻 First of all, I want to thank you for everything. Currently, I'm not experiencing any issues with IPv6 testing. However, when trying to connect to the server, I encounter the `HTTP Request failed, curl code: 7` error. I don't think this problem is related to IPv6. It seems to be present on the IPv4 side as well. Perhaps you could take a look.
> 
> 💪🏻 Thank you.

Yep, that's a known issue that's yet to be fixed. Not related to new IP resolution. 
We'll check it soon
