### ISSUE TITLE
Disable the Ambient SOunds from Gta etc

### ISSUE THREAD

**Issue by Alessandro18K** [altmp/altv-issues#1275]
### Description of the problem

 it seems to be broken since the 8.4 Update
 Code was: 

       game.startAudioScene("FBI_HEIST_H5_MUTE_AMBIENCE_SCENE"); // Used to stop police sound in town
	game.cancelCurrentPoliceReport(); // Used to stop default police radio around/In police vehicle
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_GENERAL", 1, 0); // Turn off prison sound
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_WARNING", 1, 0); // Turn off prison sound
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_ALARM", 1, 0); // Turn off prison sound
	game.setAmbientZoneState(0, 0, 0); // Set ambiant sound to 0,0,0
	game.clearAmbientZoneState("AZ_DISTANT_SASQUATCH", 0, 0);
	game.setAudioFlag("LoadMPData", true);
	game.setAudioFlag("DisableFlightMusic", true);

### Reproduction steps

Insert the Code in an handler or everyTick

### Expected behaviour

The Code should disable the Standard Sounds from Gta , Prison Sounds, Police Sirens etc. bute doesnt work anymore since the Update

### Operating system

Windows Server 2016

### Version

8.4 (Release)

**Comment by YannBCF** [comment]
Can you double check ? We just tested and every methods you posted are working for us

**Comment by Alessandro18K** [comment]
I can test it tomorrow again :D

**Comment by leoms1408** [comment]
Works for me. (8.4 (Release))
```
alt.everyTick(() => {
	game.startAudioScene("FBI_HEIST_H5_MUTE_AMBIENCE_SCENE"); // Used to stop police sound in town
	game.cancelCurrentPoliceReport(); // Used to stop default police radio around/In police vehicle
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_GENERAL", 1, 0); // Turn off prison sound
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_WARNING", 1, 0); // Turn off prison sound
	game.clearAmbientZoneState("AZ_COUNTRYSIDE_PRISON_01_ANNOUNCER_ALARM", 1, 0); // Turn off prison sound
	game.setAmbientZoneState(0, 0, 0); // Set ambiant sound to 0,0,0
	game.clearAmbientZoneState("AZ_DISTANT_SASQUATCH", 0, 0);
	game.setAudioFlag("LoadMPData", true);
	game.setAudioFlag("DisableFlightMusic", true);
})
```

**Comment by C0kkie** [comment]
normally you dont do this in everytick
