### ISSUE TITLE
8.4 | Custom Interiors unloads world props / textures

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1277]
### Description of the problem

Some Interiors leeds to unloading some street textures / prop textures (collisions are there),
Using https://rfc-mapping.tebex.io/package/4652693 for alt:V unloads the street at `-728,7560424804688 -1180,193359375 10,8125`.

### Reproduction steps

1. Load the Interior mentioned from above.
2. Port to the coordinate `-728,7560424804688 -1180,193359375 10,8125`

### Expected behaviour

The world props shouldn't unload.

### Additional context

This was not a problem before the release of version 8.X.
A user who uses the same interior on r*ge didn't have the same problems.
So this has to do something with alt:V internal.

https://img.revyn112.dev/data/ZzArqtPiT2.mp4

### Operating system

Windows 11

### Version

release/8.4

**Comment by Revyn112** [comment]
> A dev of a mlo worte that the way ymaps work has changed since the update. he is fixing the mlo so i GUESS its nothing related directly to altv, but to mlo developers

The same mlo works on other plattforms. So i see this issue on the site of alt:V and there it should be fixed.
Many mlo developers didn't support alt:V in the past. You're able to buy the files from them and can then convert them for alt:V (not really hard) but there clearly stated that there don't give you support. When we now have such gamebreaking changer behaviour, do you think they will help for something that they dont support even in the past?
I dont think so, because for fiveM (greatest plattform) it will work. So thats why i think the fix should be come from alt:V.

**Comment by cmdflow** [comment]
I am not related to AltV ;) Just telling you what the mlo dev said as we have same issues with one specific mlo. And the dev of the mlo told me that he has to fix it. All other mlso are working fine on our server. So....

**Comment by gt4ever1988** [comment]
This is an MLO problem that we had ourselves. The GTA update changed certain YMAPs which are overwritten by an MLO, which creates invisible streets. The respective MLO developer must use the original GTA-YMAP and adapt it again. This is not an old: V problem.

**Comment by FabianTerhorst** [comment]
Im closing this for now since it seems to be a mlo and not altv issue.
