### ISSUE TITLE
Vehicle door lock problem

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1278]
### Description of the problem

Since the new release if a vehicle is closed it can't be opened. I tried server side .lockState and client side native (setVehicleDoorsLocked) functions as well.

### Reproduction steps

1. Close the cehicle. Like vehicle.lockState = 2
2. Use the vehicle.lockState = 1 an try to get in

### Expected behaviour

It would be important to fix as no player can ge in to their vehicle right now.

### Operating system

Windows 11

### Version

alt:V build #8.4, branch release

**Comment by yoranjj** [comment]
https://www.dropbox.com/s/t86e7se58ex4ili/4TnlmgPAY4.mp4?dl=0

Works fine on 8.4

**Comment by Lekenthu** [comment]
It doesn't work for me in some cars: https://i.imgur.com/WyYCLe4.png

**Comment by FabianTerhorst** [comment]
Then make the issue more specific. For which Cars its Not working.

**Comment by yoranjj** [comment]
I've tried 20 different models and all of them work fine, list the ones that aren't working for you please!

**Comment by Lekenthu** [comment]
Okay, I realized the problem. I used setGamestateDataBase64, setHealthDataBase64, etc with old datas.
