### ISSUE TITLE
all vehicle not spawned

### ISSUE THREAD

**Issue by eodclan** [altmp/altv-issues#1279]
### Description of the problem

No vehicle spawns when the server is started and via a command. 

### Reproduction steps

Spawn Code

> IVehicle veh = Alt.CreateVehicle(model, new Position(player.Position.X + 2f, player.Position.Y, player.Position.Z), player.Rotation);
                if (veh != null)
                {
                    veh.EngineOn = true;
                    veh.LockState = VehicleLockState.Unlocked;
                    veh.SetNumberplateTextAsync("FL");
                    veh.PrimaryColor = 1;
                    veh.SecondaryColor = 1;
                    veh.DashboardColor = 1;
                    veh.WindowTint = 3;
                    veh.WheelColor = 55;
                    veh.PearlColor = 3;
                }

is not working now.

### Expected behaviour

It would be important to fix this as no vehicle is currently spawning. 

### Operating system

Windows 11 Pro 21H2

### Version

alt:V build #8.4, branch release

**Comment by leoms1408** [comment]
Hi are you getting any errors? For me works exactly the code that you provided

**Comment by C0kkie** [comment]
Be sure vehicle & player are in the same dimension
Be sure your server, vehicle bin & modules are up2date
For everyone else its working
