### ISSUE TITLE
blurry Background in Settings windows after alt:V Update

### ISSUE THREAD

**Issue by markvela** [altmp/altv-issues#1281]
### Description of the problem

After the new update from alt:V you now have a blurry background in the window with the map and the settings.

https://i.imgur.com/nRn14oH.png

### Reproduction steps

Open the ESC window 

### Expected behaviour

The background should not be blurry but clear as before.

### Operating system

Windows 10 

### Version

release/8.4

**Comment by FabianTerhorst** [comment]
Don't see a reason to fix it.
