### ISSUE TITLE
[UX] Exit Game Inside GTA:V Internal Menu

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1282]
### Description of the problem

If you are not a very wise computer user you cannot leave alt:V without doing one of the following:

* Hit `alt + F4` to exit.
* Open Task Manager, Kill GTAV

### Desired solution for the problem

Create an option in the internal GTAV menu that lets you leave the game.

That or create an `alt on` event that prompts the user to quit the game so that server owners can script their own exit menus.

**Comment by martonp96** [comment]
done
