### ISSUE TITLE
attachTo API buggy

### ISSUE THREAD

**Issue by tobias-schanze** [altmp/altv-issues#1283]
### Description of the problem

Since 8.x the attachTo API ist buggy. It is reproducible on JS serverside ans JS clientside with a native. The ped on which will a Ped attached ported the attached ped on the ground. For the attached ped/player it looks good as well as for all other players.

### Reproduction steps

Use the JS Serverside attachTo API oder the attachEntityToEntity native.

JS Serverside:
player.attachTo(otherPlayerInstance, 0,0, alt.Vector3.zero, alt.Vector3.zero, false, true); 

Native:
native.attachEntityToEntity(localPlayer.scriptID, target.scriptID, 0, 0, 0, 1, 0, 0, 0, true, true, true, true, 1, true);

### Expected behaviour

The ped that is attached must not be ported but should be attached correctly.

### Operating system

Windows

### Version

release/8.6

**Comment by RobDeFlop** [comment]
Confirmed

**Comment by FabianTerhorst** [comment]
fixed in next release.
