### ISSUE TITLE
WebView Instances not Destroyed

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1285]
### Description of the problem

Currently WebView instances are not being destroyed on disconnect. They sometimes do destroy but often times you end up with additional altv-webengine executables.

![](https://i.imgur.com/nIGgk17.png)

### Reproduction steps

```ts
const view = new alt.WebView('https://google.com/');

alt.on('disconnect', () => {
    view.destroy();
});
```

### Expected behaviour

They get destroyed either by default through connection loss, or we can invoke the destroy through the disconnect event.

### Operating system

Windows 10

### Version

*

**Comment by C0kkie** [comment]
Can you try on latest rc? pretty sure we fixed something there @Stuyk

**Comment by dominion56** [comment]
same thing on 9.4 Release

**Comment by FileCode** [comment]
and 9.5 on dev rel and rc

**Comment by LeonMrBonnie** [comment]
I am unable to reproduce this issue with the provided reproduction steps

**Comment by LeonMrBonnie** [comment]
Wasn't able to reproduce and no response from the issue author so I will close this issue.

**Comment by C0kkie** [comment]
Should be fixed in newest dev
