### ISSUE TITLE
Player stays connected until game closes when getting timedout after early auth

### ISSUE THREAD

**Issue by TheDutchDev** [altmp/altv-issues#1291]
### Description of the problem

When a player connects to a server that uses early auth, they can get timed out for whatever reason. The problem is that (in some cases) the player actually does join the server (as in is connected) while the player himself is still on the "timed out" or main menu screen of altV.

As a result, in the case of my server where they can't login to their account when it's already logged in and ingame, they can't join anymore.

The only reason for them to fix it is to close the altV game (when they're at the altV main menu or timed out message etc). Only then will altV recognize the player disconnecting and leave the server.

The other fix right now is to simply kick the player.

### Reproduction steps

- Make server use early auth
- Connect to the server, login with early auth and download resources etc
- Make the player time out somehow
- Player still joins server, but the player is stuck at main menu/timedout message

### Expected behaviour

altV should completely disconnect the player when they get timed out.

### Additional context

This might also happen without early auth, but players are generally not logged in then until they're actually ingame (and gotten past the authentication screen ingame), so nobody has ever noticed it until now.

### Operating system

Windows 10 (client), Ubuntu 20 (server)

### Version

Release 8.6

**Comment by CoffeeGen** [comment]
This also seems to happen when a player fails to download all packages properly for whatever reason. The client still connects to the server or something (connection is opened?) but for the user it gives an error and stays in the main menu/error overlay screen.

**Comment by FabianTerhorst** [comment]
We maybe fixed this in next release but we are not sure if its the same bug we fixed or not.
