### ISSUE TITLE
Helicopter starting sound when entering as passenger

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1292]
### Description of the problem

No clue if it also happens on other vehicles such airplanes, but for helicopters:

When you enter a helicopter as passenger (was tested on buzzard2) while there's no-one piloting it, it will make the starting sound (but obviously rotors wont start rotating).

### Reproduction steps

- Spawn a helicopter (eg buzzard2)
- Enter as passenger and listen to the sound

### Expected behaviour

No sound

### Operating system

Windows 10 (client), Ubuntu 20 (server)

### Version

Release 8.6

**Comment by xxshady** [comment]
Can't confirm on 9.0-dev2

**Comment by xxshady** [comment]
@CoffeeGen

**Comment by CoffeeGen** [comment]
Maybe its already fixed in 9.0?
I tested it on release 8.6

**Comment by xxshady** [comment]
Then we can close this issue xd

**Comment by CoffeeGen** [comment]
If you're 100% its fixed on 9.0 then yep :)

**Comment by xxshady** [comment]
I'm 100% sure, you can test it :)

**Comment by FabianTerhorst** [comment]
There was no change related to that and i also dont think we want to fix gta bugs.

**Comment by xxshady** [comment]
@CoffeeGen I hope you haven't forgotten about this issue? xd

**Comment by CoffeeGen** [comment]
Uhm I might have haha

I think this has been resolved no? Can close

If not fixed in 9.0 release I'll make a new issue/reopen this

**Comment by xxshady** [comment]
> Can't confirm on 9.0-dev2

@CoffeeGen as i already wrote, tested on 9.0 dev
