### ISSUE TITLE
Attachto is not synced

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1293]
### Description of the problem

Attaching a burrito to a flatbed is not synced and the car is dropping arround or even stands on same place while beeing attached.
See: https://www.youtube.com/watch?v=sfPZ5VTYTR0

### Reproduction steps

Spawn a flatbed, spawn a burrito. Attach Burrito to flatbed with following command:

`burrito.attachTo(flatbed, 0, -1, new alt.Vector3(0, -8.5, 4.5), new alt.Vector3(0, 0, 0), true, false);`

Drive around with a passenger and look at the vehicle. Change seats, the vehicle detaches immedately. But also not chaning seats will cause desyncs on attached burrito

### Expected behaviour

Should be fixed already

### Additional context

none

### Operating system

Debian 10

### Version

Release 8.6

**Comment by FabianTerhorst** [comment]
Try to Set both Bones to 0

**Comment by cmdflow** [comment]
Ok. Tomorrow then

**Comment by cmdflow** [comment]
Still the same attaching to 0:
https://www.youtube.com/watch?v=zks8TsiNw1o
`vehicle.attachTo(flatbed, 0, 0, new alt.Vector3(0, -8.5, 4.7), new alt.Vector3(0, 0, 0), true, false);`

**Comment by FabianTerhorst** [comment]
What Happens when you use the native. Instead of the serverside method.

**Comment by cmdflow** [comment]
Basically the same. Tried with following code:
`native.attachEntityToEntity(veh.scriptID, flatbed.scriptID, 0, 0, -8.5, 4.7, 0, 0, 0, true, false, false, false, 1, true);`
Vehicle stays as it should, switching drivers 2 or three times then causes the passenger to see the vehicle "hopping" after the truck. So basically clientside is the same error

**Comment by FabianTerhorst** [comment]
Will be fixed next update.

**Comment by cmdflow** [comment]
Still not fixed.
Reproduction steps:
Player A spawns a flatbed and a car
Player A attaches car on flatbed
Player B enters faltbed as driver, player A enters flatbed as passanger
Player B has correct sync, passenger looses attached vehicle.

Same issue as before. tested on 9.0-rc6

**Comment by C0kkie** [comment]
Try serverside setter

**Comment by cmdflow** [comment]
Tested also serverside. Depends on netowner. When the netwoner changes, the car is not attached for the attacher but for the netowner. Wired behaviour
