### ISSUE TITLE
Teleporting with attached Vehicles

### ISSUE THREAD

**Issue by Hutstaender** [altmp/altv-issues#1295]
### Description of the problem

If u teleport a vehicle that has another vehicle attached to it, you will lose the attached vehicle occasionally (around 1 times in 10 teleports)

Sometimes you will lose it before teleportation, sometimes afterwards. 
(the attachment will be reapplied if u get out)

### Reproduction steps

1. Spawn two vehicles. e.g. neon and scorcher and get their id's
2. Attach the scorcher to the neon with this server side code example
```
let neon = alt.Vehicle.getByID(2);
let scorcher = alt.Vehicle.getByID(8);
scorcher.attachTo(
                neon,
                0,
                0,
                new alt.Vector3(0, -9, 3.8),
                new alt.Vector3(0.12, 0, 0),
                true,
                false
            );
```
3. Get in the neon
4. Teleport between 2 locations around 10 times (in this snippet just switch the if from true to false)
``` 
let pos = {x: 2256.414, y: 1146.7, z: 69.1}
if (true) {
    pos = {x: -440.414, y: 6035.7, z: 30.9}
}
player.vehicle.pos = new alt.Vector3(pos.x, pos.y, pos.z);
```

### Expected behaviour

Teleport without loosing the attached vehicle occasionally.

### Operating system

Windows

### Version

release/8.6

**Comment by FabianTerhorst** [comment]
fixed in next release.
