### ISSUE TITLE
Add WebView features

### ISSUE THREAD

**Issue by KifKick** [altmp/altv-issues#13]
Events:
- [ ]  webViewCreated
- [ ]  webViewDomReady

Functions:
- [x]  destroy
- [ ]  reload
- [x]  hide(?)
- [x]  show(?)

Properties:
- [x]  url

**Comment by KifKick** [comment]
`alt.on('webViewCreated', (webView) => {
})`

`alt.on('webViewDomReady', (webView) => {
})`

**Comment by btx78000** [comment]
Keep a list of all opened WebView up to date like an array of WebViews objects accesible from : alt.webviews

**Comment by KifKick** [comment]
Better is to use in my opinion alt.webView.all

**Comment by LeonMrBonnie** [comment]
`webViewCreated` event is not needed, you create webviews yourself so you always know when one is created. If you need such an event emit it yourself.
`webViewDomReady` this has been implemented as the `load` event.
To reload the page you can use JS in the CEF.
