### ISSUE TITLE
Add Ped class

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv-issues#130]
**Is your feature request related to a problem? Please describe.**
Since PEDs (e.g gas station) are being created client side only, they need to be synced by our self. The dramatic is that we would need to sync every move, sound etc. Even if this is synced player A can punch his PED but for player B he is just hitting the air.

**Describe the solution you'd like**
Make it possible to create server side PEDs.

**Describe alternatives you've considered**
Fully synced PEDs (but will more difficult I guess)

**Comment by emcifuntik** [comment]
Syncing of static objects is take extra network trafic. Clientside script that create ped with invincibility is much better solution. Peds controller will be added to server only when we will make NPCs controllable serverside

**Comment by timedotcc** [comment]
`Peds controller will be added to server only when we will make NPCs controllable serverside`
Is this already planned or not yet? I also think the function is important for many game modes.

**Comment by floyd75** [comment]
I think server side PED's are better for many gamemodes. When players are driving around and the Ped is not spawning fast enough or the player is too far away from the Peds spawnpoint... the player will not see a Ped. Bad for Jobs, Missions or what ever when the player is new to the server. My oppinion.

**Comment by FabianTerhorst** [comment]
Possible server and clientside in v15.
