### ISSUE TITLE
Some Vehicles are locked at model specific top speed

### ISSUE THREAD

**Issue by lokuPadoku** [altmp/altv-issues#1300]
### Description of the problem

With the Cocntract update, R* introduced some internal changes that lock specific vehicles at specific top speeds.
I tried using Handling API to increase topspeed. Also setVehicleCheatPowerIncrease wont change topspeed.

### Desired solution for the problem

Remove lock

### Alternatives you considered

Examples (with cheatpower 6 or initialDriveMaxFlatVel = 250):
comet6 => ~205 km/h
euros => ~195 km/h
sultan3 => ~195 km/h

### Version

release/8.7

**Comment by Revyn112** [comment]
I can confirm, but you can bypass this behaviour when you set the maxspeed via native and it will work.

**Comment by lokuPadoku** [comment]
Which native do you mean? Can u supply an example?

**Comment by Revyn112** [comment]
https://natives.altv.mp/#/0xBAA045B4E42F3C06

**Comment by Revyn112** [comment]
That's what we re using without problems.

**Comment by lokuPadoku** [comment]
Oh wow, how did I missed that. Thanks, I will give it a try.

**Comment by lokuPadoku** [comment]
Seems not to work for me.

```javascript
onServer('command:setmaxspeed', (speed: number) => {
	native.setVehicleMaxSpeed(Player.local.vehicle.scriptID, speed);
});
```

I called it sitting in the vehicle by Command in F8 console. I checked and it gets called, but still limited speed to 205.

**Comment by Revyn112** [comment]
Sorry i had the wrong native in mind.
I've looked in our code and we use this native:
https://natives.altv.mp/#/0x93A3996368C94158

**Comment by lokuPadoku** [comment]
Oh thats why, and I can confirm it works like a charm, thanks for the help!
