### ISSUE TITLE
alt.RadiusBlip issue on server-side

### ISSUE THREAD

**Issue by GIT-XEN** [altmp/altv-issues#1302]
### Description of the problem

If i try to set a RadiusBlip on server-side it is not visible on map (same code works client-side)

### Reproduction steps

1: set a RadiusBlip on server-side
2: set sprite (example: 9)
3: set color (example: 62)
4: set alpha (example: 100)
5: check your map and you will see there is nothing

### Expected behaviour

RadiusBlip should be visible on the map

### Operating system

Windows 10

### Version

release/8.6

**Comment by savvin-dev** [comment]
9.8-rel, 10.0-dev7 actually, it still doesn't work
```js
const radiusBlip = new alt.RadiusBlip(0.0, 0.0, 72.0, 300.0);
radiusBlip.color = 37;

console.log(radiusBlip.valid); // true
```

**Comment by savvin-dev** [comment]
9.8-rel, 10.0-dev7 actually, it still doesn't work
```js
const radiusBlip = new alt.RadiusBlip(0.0, 0.0, 72.0, 300.0);
radiusBlip.color = 37;

console.log(radiusBlip.valid); // true
```

**Comment by xxshady** [comment]
Confirmed on 13.0-dev12

**Comment by xtance** [comment]
Confirmed on release 13.13

**Comment by C0kkie** [comment]
@xxshady @xtance @savvin-dev @GIT-XEN  Can you guys test in newest dev?

**Comment by xxshady** [comment]
Still not visible on 15.0-dev353
```js
const radiusBlip = new alt.RadiusBlip(0.0, 5.0, 72.0, 300.0, true);
radiusBlip.color = 37;

console.log(radiusBlip.valid); // true
```

**Comment by TuK4z** [comment]
Isn't it fixed yet? Maybe it was because of size setter?

https://github.com/altmp/altv-issues/issues/1719

**Comment by xxshady** [comment]
Seems like yes, can't reproduce anymore (15.0-rc2)
