### ISSUE TITLE
Streaming carmodcols

### ISSUE THREAD

**Issue by lLukDreams** [altmp/altv-issues#1303]
### Description of the problem

With the upcoming new GTA 5 version, there will be new colors (in this case chameleon called colors). They are pretty cool and already leaked, but you can't stream them in any way since there was never an update on the color options, so you could copy it. I need an option to stream carmodcols file to add new colors to the system.

### Desired solution for the problem

A way to add new objects to the carmodcols.ymt in the database, otherwise u can't stream new colors or select them better saying. With weapons there is a file type called at the end _PATCH (in this case would be: CARMODCOLS_FILE_PATCH) which one replaces already existing meta files.  This would be a nice approach to the problem.

**Comment by C0kkie** [comment]
@lLukDreams  do you have a example file which should work in sp for example?

**Comment by lLukDreams** [comment]
https://www.gta5-mods.com/misc/chameleon-paint-add-on

this worked for a long time ago

**Comment by C0kkie** [comment]
Should work in v15 with this resource provided by PIXEL https://discord.com/channels/371265202378899476/1129008891791937647/1129008891791937647
