### ISSUE TITLE
Audio API got broken in one of the last few updates

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1304]
### Description of the problem

alt.Audio no longer works with .mp3 files. We had a feature that worked a couple weeks ago(15th of december), but no longer works now.

Can be seen in this video from #showcase: https://discord.com/channels/371265202378899476/384874419446743041/920804145806581880

### Reproduction steps

```ts
let myAudio = new alt.Audio( '@resource/sounds/' + fileName, 1, alt.AudioCategory.HUD, true );
    myAudio.looped = false;
    myAudio.addOutput( alt.Player.local );
    myAudio.play();
```

asset resource .cfg file
```
type: asset-pack

client-files: [
  "sounds/*",
]
```

is a separate resource, with .mp3 files inside the sounds subfolder.

### Expected behaviour

The sound to work.

### Additional context

Got this in client log
```
[22:33:11][Error] No buffer when trying to add output!
[22:33:11][Error] Errored audio cannot be played!
[22:33:16][Error] Invalid asset pack
```

### Operating system

Windows 10

### Version

Release 8.8

**Comment by FabianTerhorst** [comment]
Most likely got broken by the gta update.

**Comment by Revyn112** [comment]
can confirm it is broken with other file formats too.

**Comment by YannBcf** [comment]
Audio api works in the update 10.0
