### ISSUE TITLE
Serverside Blip heading Setter does not work

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#1306]
### Description of the problem

Serverside Blip heading setter does not work.

### Reproduction steps

Serverside Code:
```
let blips:alt.Blip[] = []

alt.everyTick(() => {
    alt.Player.all.forEach(player => {
        if(blips[player.id] == undefined) {
            blips[player.id] = new alt.PointBlip(player.pos.x, player.pos.y, player.pos.z)
            blips[player.id].sprite = 225;
            blips[player.id].heading = 161.32464223311902
        }
    });
});
```

This code looks ingame like this: https://cdn.discordapp.com/attachments/835927155586236457/927237214151266415/unknown.png

but if i remove "blips[player.id].heading = 161.32464223311902" & set the heading clientside 
```
alt.everyTick(() => {
    alt.Blip.all.forEach((blip) => {
        blip.heading = 161.32464223311902
    });
});
```
it will work & look like this https://cdn.discordapp.com/attachments/835927155586236457/927236736587792424/unknown.png

### Expected behaviour

Set the Blip heading.

### Additional context

N/A

### Operating system

Windows 11

### Version

release 8.8

**Comment by LeonMrBonnie** [comment]
Fixed in next update
