### ISSUE TITLE
alt Worker load event is broken

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1309]
### Description of the problem

the "load" event is called before the worker is actually loaded/ready. When you try to emit something to the worker inside the load event, it won't send it.

When waiting for a few seconds with eg a timeout, it works fine.

### Reproduction steps

Create a worker, emit in load event.

### Expected behaviour

The worker to be ready when it sends load event.

### Operating system

Windows

### Version

release 8.8

**Comment by LeonMrBonnie** [comment]
Please reopen this issue in the [JS module repo](https://github.com/altmp/altv-js-module), because this issue is not related to the core of alt:V
