### ISSUE TITLE
taskSynchronizedScene not synced for other Players

### ISSUE THREAD

**Issue by its4l3x** [altmp/altv-issues#1311]
### Description of the problem

taskSynchronizedScene Native isnt synced. 

See the follow Videos of the two Sites

https://www.youtube.com/watch?v=IkhLyxkTxZ0
https://www.youtube.com/watch?v=iLEitqkVAi0

### Reproduction steps

Execute Following-Script Block. Or use simply native taskSynchronizedScene.
```

this.scene2 = game.createSynchronizedScene(
			goToVector.x,
			goToVector.y,
			goToVector.z,
			rot.x,
			rot.y,
			rot.z,
			2
		);

		game.taskSynchronizedScene(
			this.localPlayer.scriptID,
			this.scene2,
			'anim_casino_b@amb@casino@games@shared@player@',
			'idle_cardgames',
			2.0,
			-2.0,
			13,
			16,
			1148846080,
			0
		);

          game.setSynchronizedScenePhase(this.scene2, 0.0);
```

### Expected behaviour

Native should be synced and other players sees for example the animation

### Operating system

Windows 10

### Version

release/8.6

**Comment by GVMP** [comment]
That's a major feature which is missing! Need that asap

**Comment by ZackaryH8** [comment]
I don't like the idea of natives being synced, if something should be synced it should be handled inside the alt API.

**Comment by LightSrc** [comment]
This is what will make scripting much easier if gets synced, no more will need for a workaround. Hopefully in version 13.

**Comment by C0kkie** [comment]
Fixed in dev/15.0-dev407

**Comment by xenicle** [comment]
[MedalTVGrandTheftAutoV20230803022922.webm](https://github.com/altmp/altv-issues/assets/26338409/dbe4b9a1-473c-471f-a885-567624164838)
I've tryed on 15.0 DEV447 with this code : 
```
const coord = native.getOffsetFromEntityInWorldCoords(cabins[i].Entity, 0, 0, 0)
    let uLocal_376 = native.createSynchronizedScene(coord.x, coord.y, coord.z, 0, 0, 0, 2)
    native.taskSynchronizedScene(player, uLocal_376, "anim@mp_ferris_wheel", "enter_player_one", 8, -8, 131072, 0, 1148846080, 0)
    native.setSynchronizedScenePhase(uLocal_376, 0.0)
```

And as you see in the video the animation seem to not be synchronized unless I made it wrongly...

**Comment by xenicle** [comment]
> [MedalTVGrandTheftAutoV20230803022922.webm](https://github.com/altmp/altv-issues/assets/26338409/dbe4b9a1-473c-471f-a885-567624164838) I've tryed on 15.0 DEV447 with this code :
> 
> ```
> const coord = native.getOffsetFromEntityInWorldCoords(cabins[i].Entity, 0, 0, 0)
>     let uLocal_376 = native.createSynchronizedScene(coord.x, coord.y, coord.z, 0, 0, 0, 2)
>     native.taskSynchronizedScene(player, uLocal_376, "anim@mp_ferris_wheel", "enter_player_one", 8, -8, 131072, 0, 1148846080, 0)
>     native.setSynchronizedScenePhase(uLocal_376, 0.0)
> ```
> 
> And as you see in the video the animation seem to not be synced unless I made it wrongly...

I've tried with multiple animations flags like "2, 16" or "514, 16" without better results

**Comment by C0kkie** [comment]
As you can see in the typings, you need to return true in all the events

https://github.com/altmp/altv-types/blob/master/server/index.d.ts#L331

**Comment by xenicle** [comment]
> As you can see in the typings, you need to return true in all the events
> 
> https://github.com/altmp/altv-types/blob/master/server/index.d.ts#L331

Thanks @C0kkie but I'm making certainly something wrong ! I've tried with (on 15-RC2 or DEV457):

Server side:

```
alt.on('requestSyncedScene', (player, sceneId) => {
    alt.log('requestSyncedScene', player.name, sceneId)
    return true
})

alt.on('startSyncedScene', (player, sceneId, startPos, startRot, animDictHash, entityAnimPairs, ) => {
    alt.log('startSyncedScene', player.name, sceneId)
    return true
})

alt.on('stopSyncedScene', (player, sceneId) => {
    return true
})

alt.on('updateSyncedScene', (player, startRate, sceneId) => {
    return true
})
```

And the code above client side. 
And It's not working : I doesn't even get the log when the scene start or is request...

**Comment by xenicle** [comment]
> > As you can see in the typings, you need to return true in all the events
> > https://github.com/altmp/altv-types/blob/master/server/index.d.ts#L331
> 
> Thanks @C0kkie but I'm making certainly something wrong ! I've tried with (on 15-RC2 or DEV457):
> 
> Server side:
> 
> ```
> alt.on('requestSyncedScene', (player, sceneId) => {
>     alt.log('requestSyncedScene', player.name, sceneId)
>     return true
> })
> 
> alt.on('startSyncedScene', (player, sceneId, startPos, startRot, animDictHash, entityAnimPairs, ) => {
>     alt.log('startSyncedScene', player.name, sceneId)
>     return true
> })
> 
> alt.on('stopSyncedScene', (player, sceneId) => {
>     return true
> })
> 
> alt.on('updateSyncedScene', (player, startRate, sceneId) => {
>     return true
> })
> ```
> 
> And the code above client side. And It's not working : I doesn't even get the log when the scene start or is request...

I've tried another approach with networkCreateSynchronisedScene native on 15.0-DEV463 and it's working.

**Comment by xenicle** [comment]
With to player I get

> > > As you can see in the typings, you need to return true in all the events
> > > https://github.com/altmp/altv-types/blob/master/server/index.d.ts#L331
> > 
> > 
> > Thanks @C0kkie but I'm making certainly something wrong ! I've tried with (on 15-RC2 or DEV457):
> > Server side:
> > ```
> > alt.on('requestSyncedScene', (player, sceneId) => {
> >     alt.log('requestSyncedScene', player.name, sceneId)
> >     return true
> > })
> > 
> > alt.on('startSyncedScene', (player, sceneId, startPos, startRot, animDictHash, entityAnimPairs, ) => {
> >     alt.log('startSyncedScene', player.name, sceneId)
> >     return true
> > })
> > 
> > alt.on('stopSyncedScene', (player, sceneId) => {
> >     return true
> > })
> > 
> > alt.on('updateSyncedScene', (player, startRate, sceneId) => {
> >     return true
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the code above client side. And It's not working : I doesn't even get the log when the scene start or is request...
> 
> I've tried another approach with networkCreateSynchronisedScene native on 15.0-DEV463 and it's working with one player.

With to player I've got this results :

[MedalTVGrandTheftAutoV20230807224525.webm](https://github.com/altmp/altv-issues/assets/26338409/74526e2f-0470-45d0-a782-15d4fccbd543)

**Comment by xenicle** [comment]
> With to player I get
> 
> > > > As you can see in the typings, you need to return true in all the events
> > > > https://github.com/altmp/altv-types/blob/master/server/index.d.ts#L331
> > > 
> > > 
> > > Thanks @C0kkie but I'm making certainly something wrong ! I've tried with (on 15-RC2 or DEV457):
> > > Server side:
> > > ```
> > > alt.on('requestSyncedScene', (player, sceneId) => {
> > >     alt.log('requestSyncedScene', player.name, sceneId)
> > >     return true
> > > })
> > > 
> > > alt.on('startSyncedScene', (player, sceneId, startPos, startRot, animDictHash, entityAnimPairs, ) => {
> > >     alt.log('startSyncedScene', player.name, sceneId)
> > >     return true
> > > })
> > > 
> > > alt.on('stopSyncedScene', (player, sceneId) => {
> > >     return true
> > > })
> > > 
> > > alt.on('updateSyncedScene', (player, startRate, sceneId) => {
> > >     return true
> > > })
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And the code above client side. And It's not working : I doesn't even get the log when the scene start or is request...
> > 
> > 
> > I've tried another approach with networkCreateSynchronisedScene native on 15.0-DEV463 and it's working with one player.
> 
> With to player I've got this results :
> 
>  MedalTVGrandTheftAutoV20230807224525.webm

Does it's because I have disabled netowner on the objects that I get this ?
