### ISSUE TITLE
Client module reload

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#1312]
### Description of the problem

Make it possible to reload client modules without restarting the whole client

### Desired solution for the problem

`reloadmodule module-name` console command
(only available in debug mode + dev)

**Comment by zziger** [comment]
IMO this shouldn't require dev branch, as it is quite helpful in development, and most of servers develop on release (cuz dev oftenly breaks a lot of stuff)

**Comment by FabianTerhorst** [comment]
It needs to have dev branch requirement.

**Comment by FabianTerhorst** [comment]
because custom modules only work in dev.

**Comment by zziger** [comment]
Ah i misread, i thought that was about reloading resource, sorry XD

**Comment by LeonMrBonnie** [comment]
Available in next version.
