### ISSUE TITLE
Polygon Based ColShapes

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1313]
### Description of the problem

Currently we have every type of ColShape but one of the most useful ones is one that can have multiple developer specified positions to create an area based ColShape. It would be useful for mapping clothing stores, regions, areas, etc.

### Desired solution for the problem

There's an MIT licensed repository which I've used as a mock way to create ColShapes:
https://github.com/reymond-group/smilesDrawer/blob/cff2e2b4a378ba5099af6eb764b3684ca807680a/src/Vector2.js#L354

I've implemented this in JavaScript and it works really well, however I'd like to have the performance of C++ for this type of thing.

### Alternatives you considered

Implementing it myself and implemented it myself. It works but it's likely not going to be as performant.

I've done some rough implementation inside of Athena here:
https://github.com/Stuyk/altv-athena/blob/master/src/core/shared/classes/polygon.ts

**Comment by FabianTerhorst** [comment]
added in next release
