### ISSUE TITLE
C# | Server crash with AccessViolationException because of HasStreamSyncedMetaData

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1316]
### Description of the problem

The Server is crashing after some time (24-48 hours) with the error:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at AltV.Net.Elements.Entities.Vehicle.HasStreamSyncedMetaData(System.String)
   at GTALife.Server.Core.Services.VehicleStatusService+<>c__DisplayClass7_1.<UpdateVehicleStatusAsync>b__1()
   at AltV.Net.Async.ActionTickScheduler+ActionContainer5.Run()
   at AltV.Net.Async.ActionTickScheduler.Tick()
```

### Reproduction steps

The code will be called every minute for saving some information to database.

```
var engineState = false;

await AltAsync.Do(() =>
{
    if (gameVehicle.HasStreamSyncedMetaData("ENGINE_STATE"))
        gameVehicle.GetStreamSyncedMetaData("ENGINE_STATE", out engineState);
});
```

### Expected behaviour

The server shouldn't crash.

### Operating system

Windows 10 Server

### Version

release/8.8

**Comment by FabianTerhorst** [comment]
Pleas test on dev branch again we did many refactorings and maybe its fixed already.

**Comment by Revyn112** [comment]
> Pleas test on dev branch again we did many refactorings and maybe its fixed already.

@FabianTerhorst I think its confirmed, because of issue #1319

**Comment by FabianTerhorst** [comment]
Its a different reason.
