### ISSUE TITLE
Clientside NetOwner Change Event

### ISSUE THREAD

**Issue by LennartF22** [altmp/altv-issues#1317]
### Description of the problem

When a player enters certain vehicle as driver, I sometimes have to turn the engine on with natives on the client that just entered the vehicle because of the plane/heli engine issue. The problem is that sometimes the engine does not turn on.
I think that this is caused by the fact that the client sometimes does not know it is network owner of the vehicle yet when the "enteredVehicle" event is called.

### Desired solution for the problem

Now that network owner information is available to the client, it would be nice to also have a corresponding event.

### Alternatives you considered

I was able to solve my issue by delaying the engine start by a couple of milliseconds, but this is not a particularly pretty solution. The next best solution would probably be to manually send an event from the server to the client when the client becomes network owner of a vehicle, but this would be unnecessary overhead and maybe also slightly less reliable.

**Comment by C0kkie** [comment]
Added if local player gets netowner or loses, currently in tested by qa
