### ISSUE TITLE
Health, Armor, MaxHealth and MaxArmor not synced properly for remote players

### ISSUE THREAD

**Issue by LennartF22** [altmp/altv-issues#1318]
### Description of the problem

The clientside "maxArmor" field of remote players seems to always be 200. The "health" and "maxHealth" fields are sometimes also not synced properly when a remote player is spawned after being dead (a ragdoll). For the local player, all values are always correct.

### Reproduction steps

The MaxArmor issue should be easy to reproduce. The other sync issues seem to be sort of random, and I have not found a proper way to reproduce them yet.

### Additional context

I need these values to display a health/armor bar above player heads.

### Operating system

Windows 10

### Version

8.4

**Comment by juztim** [comment]
please test on latest dev as there have been a lot of changes. It might be fixed already

**Comment by LennartF22** [comment]
@juztim On the latest dev I cannot even get my server started because it crashes when SetStreamSyncedMetaData is used (C# server module btw.)

**Comment by juztim** [comment]
wait for next build then

**Comment by LennartF22** [comment]
@juztim I was able to test it on dev now and things do not seem to have improved, didn't to extensive testing though.

**Comment by LennartF22** [comment]
It's a giant mess at the moment to be honest. I created a very simple test resouce and there were many issues. First of all, the Health, MaxHealth, Armor and MaxArmor of a local player (i.e. the player my client is controlling) are always consistent with the server values for this player, but for remote players (i.e players that are streamed to my client) the problems begin:

1. Sometimes when a remote player is dead and then spawned, his health is exactly the same as yours until his health changes.
2. MaxArmor seems completely broken for remote players (MaxArmor-Setter has no direct effect except for the local player).
3. MaxHealth-Setter sometimes also sets MaxArmor for the corresponding remote player (when a remote player connects, his MaxArmor is streamed to other players as 200, which is the initial MaxHealth value, while it is streamed to himself as 100, which is the correct value)
4. Sometimes MaxHealth for remote players is just 0
6. Sometimes when setting Health, the health of the remote player is set to the correct value for a frame or so, but then jumps back to the old value (race condition?)

I could upload a video which shows some of the issues, but it's probably easier if you just look at it yourself.

**Comment by LennartF22** [comment]
I'm pretty sure that some of the aforementioned problems exists for at least 8 months or so, as I already notices some of them back then, but it seems like it's getting worse.

Related issues:
#1097 #799
