### ISSUE TITLE
Easy RPC System

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1322]
### Description of the problem

A lot of people have been wanting to make RPC calls to the client to get `native`  specific information that may not be available on server-side. I think it would be a good idea to create a type of interface that will allow for an event to be `awaited` until a return from the event comes back. However, that event could also expire if no information is returned in `x` amount of time.

**Why?**
RPC is something that is a difficult subject to grasp for most people who start programming with alt:V and having the ability to essentially label an event on server-side that calls some other event `client-side` and then returns that data back to the event would be an incredible feature for alt:V to have.

### Desired solution for the problem

Making the process as simple as it can possible be I think it could work in a way similar to the following:

**Server Side**
```ts
const screenSize = await alt.emitRpc(someClient, "getScreenSize", arg1, arg2, arg3);
```

**Client Side**
```ts
alt.onRpc("getScreenSize", (arg1, arg2, arg3) => {
    const someResult = native.someNative...
    return someResult;
});
```

### Alternatives you considered

Writing my own implementations that are incredibly tricky through `on` and `off` events and unique event names and various other ways. Just wish there was an easier way to make them.

**Comment by ZackaryH8** [comment]
This would undoubtably be a great feature to add but from what I have been told, it would increase network traffic

**Comment by LightSrc** [comment]
Must have feature for multiplayer mod in 2022. It would also be nice to be able RPC in CEF.

**Comment by xxshady** [comment]
was added in [v15](https://docs.altv.mp/articles/changelogs/15_0.html#added-2)
