### ISSUE TITLE
"This PC" crashes the game directory selection dialog

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1323]
### Description of the problem

.

### Reproduction steps

1. Enter invalid `gtapath` in `altv.cfg`
2. Launch altv
3. Click on "This PC" in select directory dialog

![image](https://user-images.githubusercontent.com/54737754/149231459-b9d00f4e-53f7-44a6-b120-c6ffdb38f3bf.png)

### Expected behaviour

No crash

### Operating system

Windows 10

### Version

dev/9.0-dev8

**Comment by ZackaryH8** [comment]
This `::{20d04fe0-3aea-1069-a2d8-08002b30309d}` will open This PC in explorer. It just need blocking I guess.

**Comment by C0kkie** [comment]
Fixed in a upcoming version
