### ISSUE TITLE
Alt Voice | Muffle Effect not working in custom modded interiors

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1324]
### Description of the problem

When using the alt voice in standard interiors / mlo the sound is muffled when players are in different rooms and have no clear sight to another, but when the players are in a custom mlo, this effect is not present.

### Reproduction steps

Use voice implemented in alt:V and go into a custom interiors (tested in mrpd by gabz, rhpd by shmann and so many other custim interiors).

### Expected behaviour

The voice effect should hit also in a custom interiors.

### Additional context

As an alternative idea: Give the possibility to add on client side a player specific method to toggle the "muffle" effect for other players. This would give the possibility to make an own system for muffling with other factors (like vehicle inside / outside) too.

### Operating system

Windows 11

### Version

release/8.8

**Comment by YannBCF** [comment]
Can you check in your mlo if the hash that this native https://natives.altv.mp/#/0x47C2A06D4F5F424B return is changing when you walk from a room to another ?

If you have no effect it is most likely that your mlo has only 1 room defined or is lacking of room definitions

**Comment by martonp96** [comment]
No reply from the issue opener

**Comment by Revyn112** [comment]
> No reply from the issue opener

@martonp96 Since when are issues closed here after one week?
Anyways: Yes the RoomKeys are different.
So this should be re-open @C0kkie.

**Comment by Revyn112** [comment]
Proof: https://img.revyn112.dev/data/NVIDIA_Share_Y3djI2o5sr.mp4

Used code:
```
alt.setInterval(() => {
    alt.log(natives.getRoomKeyFromEntity(alt.Player.local.scriptID));
}, 1000);
```

**Comment by martonp96** [comment]
@Revyn112 i can close any issue whenever i feel like so

**Comment by DurtyFree** [comment]
Muffle effect for custom interiors can be fixed by providing / adding proper audio occlusions for the interior. 
You can generate it using this tool for example: https://github.com/pedr0fontoura/gtav-audio-occlusion
