### ISSUE TITLE
Player StreamSyncedMetaData not synced when set in Player Constructor

### ISSUE THREAD

**Issue by LennartF22** [altmp/altv-issues#1326]
### Description of the problem

When calling `SetStreamSyncedMetaData` in the constructor of a custom player class in C#, the data is not synced to the client, although `GetStreamSyncedMetaData` returns the correct value. Calling `SetStreamSyncedMetaData` later, for example in the `PlayerConnect` event, works as expected.

I have not tested whether the issue is the same for vehicles.

### Reproduction steps

```cs
public class MyPlayer : Player
{
    public MyPlayer(IServer server, IntPtr nativePointer, ushort id) : base(server, nativePointer, id)
    {
        SetStreamSyncedMetaData("x", true);
    }
}
```

### Expected behaviour

`SetStreamSyncedMetaData` should also work when called in the player constructor.

### Operating system

Windows 10

### Version

9.0-dev8

**Comment by FabianTerhorst** [comment]
does the same bug happens for vehicles?

**Comment by LennartF22** [comment]
> does the same bug happens for vehicles?

Just tested it and for Vehicles it works correctly.

**Comment by LennartF22** [comment]
The weird thing is that when another player leaves and then reenters my streaming range, the meta data that was set in the constructor is still not getting synced to me, even though `GetStreamSyncedMetaData` returns the correct value on the server side.

**Comment by FabianTerhorst** [comment]
btw are you sure you use player.Spawn?

**Comment by LennartF22** [comment]
Yes, but I set the meta data before `Player.Spawn`. I can try to spawn the player in the constructor before setting the meta data.

I also just noticed that on release/8.9, the stream synced meta data that is set in the player constructor does not cause a `streamSyncedMetaChange` for the own/local player (maybe that is just due to the fact that the client code has not registered the event until the meta data in the constructor has already been set, because `getStreamSyncedMetaData` definitly returns the correct value with release/8.9).

**Comment by LennartF22** [comment]
Not working either:
```cs
public MyPlayer(IServer server, IntPtr nativePointer, ushort id) : base(server, nativePointer, id)
{
    Model = Alt.Hash("mp_m_freemode_01");
    Spawn(new Position(0, 0, 72), 0);
    SetStreamSyncedMetaData("x", true);
}
```

**Comment by LennartF22** [comment]
@FabianTerhorst I made a mistake while doing some of the tests, see the two edits above (basically I was using 'synced meta data' where I thought I was using 'stream synced meta data').

Nevertheless I'm sure now that both 'synced meta data' and 'stream synced meta data' don't work correctly when set in the player constructor, but they have slightly different symptoms:
- 'synced meta data': the data of some player x is only synced to players which connect after player x.
- 'stream synced meta data': the data of some player x is *not* synced to player y if player x directly spawns in the streaming range of player y (when player x spawns far away from player y and then moves closer to player y, so that he starts getting streamed to player y, the meta data is set correctly).

**Comment by FabianTerhorst** [comment]
Should be fixed by last dev build.
