### ISSUE TITLE
Add Serverside Tattoo methods

### ISSUE THREAD

**Issue by tastydev** [altmp/altv-issues#1327]
### Description of the problem

As i can see tattoo's still need to be applied through natives. It would be great to bring this feature to the serverside api to "complete" the serverside appearence api.

### Desired solution for the problem

Serverside functions for ```game.clearPedDecorations(this.localPlayer.scriptID);
			game.addPedDecorationFromHashes(
				this.localPlayer.scriptID,
				alt.hash(collection),
				alt.hash(overlay));```

### Alternatives you considered

Using the natives.

### Additional context

Maybe it could be done when the invisibility of tattos gets fixed.

**Comment by YannBCF** [comment]
Duplicate of https://github.com/altmp/altv-issues/issues/19
