### ISSUE TITLE
alt.setCursorPos works even when game is not in focus

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1329]
### Description of the problem

.

### Reproduction steps

1. 
```js
alt.everyTick(() => alt.setCursorPos({x: 0, y: 0}))
```
2. unfocus game window
3. enjoy xd

### Expected behaviour

This method should not work when the game window is not in focus I guess

### Additional context

Perhaps there are some other methods that should not work while the game window is out of focus

### Operating system

Windows 10

### Version

dev/9.0-dev8

**Comment by LeonMrBonnie** [comment]
Fixed in next version

**Comment by xxshady** [comment]
![wwsww](https://user-images.githubusercontent.com/54737754/149589111-90573d77-4746-47b9-80e9-6ff82b81a67b.png) thanks xd
