### ISSUE TITLE
IPL Facility

### ISSUE THREAD

**Issue by PrisonIndustry** [altmp/altv-issues#1330]
### Description of the problem

When i go to coords from Facility, the textures are buggy. I testet it with the Facility IAA and in Facility IAA it work.

### Reproduction steps

TP to Coord from Facility. 

### Expected behaviour

Fix that 

### Operating system

Windwos AltV Client and Server 

### Version

8.9 (release)

**Comment by ThomasMarangoni** [comment]
Please add reproduction code and a screenshot.

**Comment by PrisonIndustry** [comment]
`chat.registerCmd('Bunker', player => {
      player.pos = new alt.Vector3(345.0041, 4842.001, -59.9997)
})`

IIA Facility Working: 
https://prnt.sc/26dy4z6

Facility not Working: 
https://prnt.sc/26dy5vr

**Comment by ThomasMarangoni** [comment]
This is default GTA behavior and not a bug, you need to load the correct entity sets.

Please inform you about EntitySets. Example Code.
`
let eSet= "set_int_02_shell";
let interior = native.getInteriorFromEntity(alt.Player.local.scriptID);
native.activateInteriorEntitySet(interior , eSet);
native.setInteriorEntitySetColor(interior, eSet, 1);
native.refreshInterior(interior);
`
