### ISSUE TITLE
Vehicle goes invincible after shuff

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#1331]
### Description of the problem

When player a is on the driver seat and get out of the vehicle, player b will shuff over to the driver seat and now the Vehicle is invincible.
Here's a short Video: https://www.youtube.com/watch?v=wzy2EcGohjU

### Reproduction steps

Two players needed.
Player A, Player B
Spawn Vehicle => Player A gets in the driver seat => Player B in the passenger seat => Player A get out of the vehicle => Player B will shuff over => Vehicle invincible

### Expected behaviour

The vehicle shouldn't be invincible

### Additional context

N/A

### Operating system

Client Windows 11 & Windows 10 | Server Linux Debian 10.0

### Version

dev/9.0-dev9

**Comment by FabianTerhorst** [comment]
ty for report, is fixed next dev build
