### ISSUE TITLE
Completely Weapon De-Sync

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#1332]
### Description of the problem

Weapons are fully out of Sync
Little Video: https://www.youtube.com/watch?v=nXVeFwkN6RI&feature=youtu.be
In this video i'm => shooting at the Tire of the vehicle, but for the other player I'm shooting at the ground => i'm throwing grenades & launching RPG's but there are not Synced anymore & i cannot damage the other Player

### Reproduction steps

Just have two players & try to shoot eachother. Explosions, grenades, even the Position where the Player is aiming & shooting is out of sync

### Expected behaviour

It should be synced

### Additional context

N/A

### Operating system

Client Windows 11 & Windows 10 | Server Linux Debian 10.0

### Version

dev/9.0-dev9

**Comment by FabianTerhorst** [comment]
i recommend to not test with broken dev build right now.

**Comment by BuddiesTV** [comment]
Okay
