### ISSUE TITLE
'streamSyncedMetaChange' fires when Entity with Meta Data gets streamed in but not when it gets streamed out

### ISSUE THREAD

**Issue by LennartF22** [altmp/altv-issues#1333]
### Description of the problem

I don't know whether it is intended to be this way, but `streamSyncedMetaChange` is fired when an entity gets streamed in (i.e. when `gameEntityCreate` is also fired), but not when an entity gets streamed out (i.e. when `gameEntityDestroy` is fired).

### Reproduction steps

Create an entity, add meta data, move away from the entity until it has left the streaming range and the `streamSyncedMetaChange` event won't fire.

### Expected behaviour

When deleting stream synced meta data on the server side, `streamSyncedMetaChange` is fired on the client side with value `undefined`. To be consistent it would make sense for me to also fire the event when the entity gets streamed out.

### Additional context

Sometimes you have to do some cleanup work when stream synced meta data is deleted by the server, for example if the meta data is used to create and attach visual/cosmetic objects to entities. This cleanup work is - at least in my case - practically always the same cleanup work you'd have to do when the entity gets streamed out. Right now you have to react to `gameEntityDestroy` to do the meta data related cleanup work, but you don't have to react to `gameEntityCreate` manually, as `streamSyncedMetaChange` has already fired by then.

### Operating system

Windows 10

### Version

release/8.8

**Comment by FabianTerhorst** [comment]
this is the intended behavior and wont be changed.

**Comment by LennartF22** [comment]
I already guessed it was intended, but it's good to have it confirmed. Do you know whether it's safe to check the validity of the script id in the `streamSyncedMetaChange` event to distinguish a real meta data change from an entity which is in the process of getting streamed in, or could is happen that the script id becomes valid before `streamSyncedMetaChange` is fired? @FabianTerhorst

**Comment by FabianTerhorst** [comment]
When you need to cleanup something it won't automatically loose its script id.

**Comment by LennartF22** [comment]
I think you misunderstood my question. Basically I want to know where the following order always holds when an entity with stream synced meta data is streamed in:
- `streamSyncedMetaChange` fires (script id still 0)
- `gameEntityCreate` fires (script id now set to something valid)
Or could it happen that `streamSyncedMetaChange` is fired after `gameEntityCreate`, even when the stream synced meta data has already been set (on the server side) way before the entity was streamed in for some player?
