### ISSUE TITLE
Broken event entityEnterColshape

### ISSUE THREAD

**Issue by Whitee303** [altmp/altv-issues#1334]
### Description of the problem

Problem looks like this:

If a player in a vehicle enters a checkpoint, the event will stop working. 

https://discord.com/channels/371265202378899476/547079158300147725/933047662415085688 <= My Message on discord alt:v

### Reproduction steps

```
import * as alt from 'alt-server'
let marker = new alt.Checkpoint(11, -760.7999877929688, -43.635162353515625, 37.839599609375, 1, 1, 122, 155, 122, 155)
marker.playersOnly = false;
alt.on('entityEnterColshape', (Colshape: alt.Colshape, entity: alt.Entity) => {
    alt.log("Works ;)")
    alt.log(entity.type)
});
```

### Expected behaviour

The alt.log should show up if I'm even in the vehicle.

### Additional context

![obraz](https://user-images.githubusercontent.com/84782812/149991056-99cc5ff3-e634-43c6-9049-81b43d59bfc0.png)

^ Working if i doesn't sitting in vehicle

![obraz](https://user-images.githubusercontent.com/84782812/149991279-275a701a-58e0-48c7-ab27-0895ea876217.png)

^ Doesn't working if i'm sitting in vehicle

### Operating system

Windows 10

### Version

Release/8.9 || Dev/9.0

**Comment by Konders** [comment]
`marker.playersOnly = false;`

`Expected behaviour
The alt.log should show up if I'm even in the vehicle.`

coolstorybob

you can remove your line with playersOnly, and add to start of handler `if(!entity instanceof alt.Player) return;`

**Comment by Whitee303** [comment]
> even

Still the same problem. Event doesn't working if i'm sitting in vehicle

**Comment by C0kkie** [comment]
Cant repro anymore. If it doesnt work for you, try to make the pos z value lower
