### ISSUE TITLE
Segmentation Fault with "setStreamSyncedMeta"

### ISSUE THREAD

**Issue by fauconjona** [altmp/altv-issues#1337]
### Description of the problem

When I use "setStreamSyncedMeta" on a vehicle just created, there's a segmentation fault, then the server crash

### Reproduction steps

```js
import * as alt from 'alt-server'; 

let entity = new alt.Vehicle("omnis", 76.2725296020508, -565.015380859375, 17.232177734375, 0, 0, 0);

entity.setStreamSyncedMeta("anything", true);
```

### Expected behaviour

No segmentation fault and no crash

### Operating system

Manjaro 21.2.1

### Version

rc/9.0-rc1

**Comment by FabianTerhorst** [comment]
Fixed.
