### ISSUE TITLE
attachEntityToEntity Desync

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#1341]
### Description of the problem

If I attach an object via attachEntityToEntity to a player and move them, then i have the following problem:
Player that is attached to the object -> sync is perfect
3rd Players: player teleports to the position

Player that is attached to the prop:
https://user-images.githubusercontent.com/72868017/150354238-8a7db4c2-ba97-4e4a-b0dc-a0663c5a36bb.mov

other player: 
https://puu.sh/IDO85/917bf8d433.mp4

### Reproduction steps

Attach player to object game.attachEntityToEntity(entity.scriptID, wheelchair, 0, -0.03, 0, 0.43, 0.0, 0.0, 185.0, true, false, false, false, 0, true)
Attach object to player game.attachEntityToEntity(wheelchair, entity.scriptID, game.getPedBoneIndex(entity.scriptID,  28422), -0.00, -0.3, -0.73, 170.0, 180.0, 180.0, false, false, false, false, 2, true)
move object

### Expected behaviour

The player shouldnt teleport

### Operating system

Windows 11

### Version

8.0 and RC 9.0

**Comment by tastydev** [comment]
Objects are not synced by alt:V so how should it be synced perfectly. For your usecase u have to attach the player to the other player with offsets somehow to achieve sync.
