### ISSUE TITLE
Whitelist or integrate AMD FSR

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#1342]
### Description of the problem

Many players use low-to-mid settings to play on servers where theoretically can be a large number of players in one place. Also, some servers may use mods that lower FPS of a player. 

### Desired solution for the problem

There is open source implementation of AMD FSR specially for GTAV. It works on GTX 10/16 series (don't know about 9 and 20+). My proposal is whitelist it or integrate into altv like you did with `rmlui`. It can give a player 15+ FPS without major reduce in graphics.

https://www.amd.com/en/technologies/radeon-software-fidelityfx-super-resolution
https://github.com/NarutoUA/gta5_fsr

### Additional context

Higher fps = better sync overall = 🚀

**Comment by nrzull** [comment]
> I'd argue this is not something that is useful for alt:V and would even go as far to say its not their responsibility to implement.

Maybe it's not useful for alt:V, but it's useful for end-users of alt:V.

**Comment by martonp96** [comment]
should be fixed in next rc build
