### ISSUE TITLE
Manual transmission for vehicles

### ISSUE THREAD

**Issue by Erumeldor** [altmp/altv-issues#1344]
### Description of the problem

I would love to see the option to add manual transmission for some cars. This would enhance any server that supports tuning/racing.
For races, it would request the user's skill, not the car he uses.

### Desired solution for the problem

I don't have any solution for the core development.

On the end-user side, it would be nice to have for example a tuning option for the cars. So on server side it could be implemented to switch the transmissions between an automatic one and a manual one.

It could be implemented on serverside that for example there will be an automated downshift when reaching slow speeds. Like a semi-automated transmission known in modern cars.

But like I said, that's only the ideas of a player - I have no idea on how to implement that on the core side bc I'm not involved in any development.

### Alternatives you considered

Alternatively, if the dynamic option can not be done it would also be okay to have a fixed configuration per car.

For example:
Cars from the "Tuner DLC" like Karin Calico GTF, Jester RR, etc. could be configurated to be manual only.

### Additional context

It is also a workaround for the change that appeared to the new Tuner cars during the "Contract" DLC.
See here: https://www.youtube.com/watch?v=wmosB27NzqI

**Comment by zziger** [comment]
If i understand correctly what you want to do - it would be possible to implement already via client-side gear setter, but for now it's broken, see #996

**Comment by Erumeldor** [comment]
I honestly don't know if that would fix it. I just asked that in discord and got the response that there have to be changes done on the core. Some of the answers:
"It's not possible without a feature in core for sure.
But afaik the sp mod isn't that great because it uses static offsets.
So we would need to reverse it ourselves, and we have too many other important features."

**Comment by martonp96** [comment]
I don't know what do you mean, a script like this should perfectly work on altv: https://forum.cfx.re/t/fivem-manual-transmission-server-side-resource-with-custom-gears-and-different-gearmods/2754006
