### ISSUE TITLE
[RmlUi] Updating too many RmlElements in everyTick causing game crash

### ISSUE THREAD

**Issue by KubasGC** [altmp/altv-issues#1345]
### Description of the problem

I'm trying to test new feature RmlUi. When I'm trying to update ~140 elements in everyTick event - game crashes with crashdump generation.

### Reproduction steps

1. Download zip file from **Additional context** header.
2. Set resource with code.ts from zip resource I uploaded here.
3. Join to the server.
4. Run, forest, run, tapping space all the time.
5. When you will be 150+ elements spawned, game will crash.

### Expected behaviour

So it doesn't crash

### Additional context

[altv_9.0-rc2_Social Club_0x57f8fc63b_21-01-2022_18-01-17.zip](https://github.com/altmp/altv-issues/files/7915442/altv_9.0-rc2_Social.Club_0x57f8fc63b_21-01-2022_18-01-17.zip)

### Operating system

Windows

### Version

rc/9.0-RC2

**Comment by martonp96** [comment]
should be fixed in the next rc build
