### ISSUE TITLE
Add Vector2, Vector3 and RGBA support for WebViews

### ISSUE THREAD

**Issue by LennartF22** [altmp/altv-issues#1346]
### Description of the problem

Currently when sending a Vector2, Vector3 or RGBA from the clientside js code to a WebView, the WebView just receives `undefined`.

### Desired solution for the problem

It would be useful if MValueVector2, MValueVector3 and MValueRGBA were properly converted to js for the WebView. Just converting them to a simple js object would already be an improvement, but it would be even better if there was an actual class/type for them to also properly support sending vectors and RGBA values back to the client js module.

### Alternatives you considered

For some events, I only need to forward the event parameters (which sometimes are nested objects with vectors or RGBA values) to a WebView. Currently I have to do the following to not loose the vectors and RGBA values:

```js
function replaceStructsInPlace(object) {
	if (object instanceof alt.Vector2) {
		return {
			x: object.x,
			y: object.y
		}
	} else if (object instanceof alt.Vector3) {
		return {
			x: object.x,
			y: object.y,
			z: object.z
		}
	} else if (object instanceof alt.RGBA) {
		return {
			r: object.r,
			g: object.g,
			b: object.b,
			a: object.a
		}
	} else if (object instanceof Object) {
		for (const key in object) {
			object[key] = replaceStuffInPlace(object[key]);
		}
	}
	return object;
}

alt.onServer('test', data => {
	view.emit('test', replaceStructsInPlace(data));
});
```

This is not particularly pretty though, and it does not handle the other direction (WebView to client module) either.

### Version

9.0-rc2

**Comment by LeonMrBonnie** [comment]
This would need code duplication because WebView JS is independent from Client JS, so it would be harder to maintain.
I would only add a object with XYZ properties, which wouldn't be the same as client JS but probably enough for this use case.

**Comment by LeonMrBonnie** [comment]
Vector3 already worked before, but I added support for Vector2 and RGBA now too
