### ISSUE TITLE
clientWidth & clientHeight are always 0 on RmlDocument

### ISSUE THREAD

**Issue by fauconjona** [altmp/altv-issues#1348]
### Description of the problem

I tried to get width and height of a rmlDocument but I always get 0, with clientWidth/Height and offsetWidth/Height. I though it was because there's nothing in the document, but even with a div I get 0.

### Reproduction steps

test.rml:

```html
<rml>
    <head>
        <title>RML Test</title>
    </head>
    <body>
        <div style="background-color: red; position: fixed; left: 0; top: 0; width: 500px; height: 300px;"></div>
    </body>
</rml>
```

client.js:
```js
import * as alt from 'alt-client';

let document = new alt.RmlDocument('/test.rml');

document.show();

//To be sure that the document is loaded
alt.setTimeout(() => {
    alt.log(`Displaying document info`)
    alt.log(`visible: ${document.isVisible}`)
    alt.log(`width: ${document.clientWidth}`)
    alt.log(`height: ${document.clientHeight}`)
    alt.log(`offset width: ${document.offsetWidth}`)
    alt.log(`offset height: ${document.offsetHeight}`)
}, 1000);
```

### Expected behaviour

To get the screen size

### Operating system

Manjaro 21.2.1

### Version

9.0-rc2

**Comment by LeonMrBonnie** [comment]
This is either intended behaviour or a bug in rmlui, but it is not related to alt:V
