### ISSUE TITLE
rmlUi have problems to display tga and png images

### ISSUE THREAD

**Issue by xenicle** [altmp/altv-issues#1350]
### Description of the problem

When I use tga image in a `decorator` rcss declaration I get `Could not create texture from file data: -2003292320` error code
With a png nothing is displayed.

### Reproduction steps

- Download gamemode4.zip (in Additional context) and extract in your altv server resource directory
- Add gamemode4 to your resources in server.cfg
- You can change `decorator: image( icon.tga );` to `decorator: image( icon.png );` in `/gamemode4/client/rml/icon.rss` to see result with png 

### Expected behaviour

rmLui display tga and png image from rcss `decorator` declaration.

### Additional context

[gamemode4.zip](https://drive.google.com/file/d/181NNtM6Hf8MW-ldTFMdPKUmtRZgJ0pC_/view?usp=sharing)

### Operating system

Windows 10

### Version

9.0 RC2

**Comment by PavlovTM** [comment]
Please fix the download, it's broken

**Comment by martonp96** [comment]
We use WICTextureLoader and it does not support TGA.
https://github.com/microsoft/DirectXTK/wiki/WICTextureLoader#remarks
