### ISSUE TITLE
New methods don't work

### ISSUE THREAD

**Issue by Basarus** [altmp/altv-issues#1351]
### Description of the problem

The setHeadOverlay, setHeadOverlayColor, setHairColor, setHairHighlightColor methods do not
work, possibly others

### Reproduction steps

I just made a command and pass the values to these methods (on a clean server)

### Expected behaviour

Must work

### Operating system

Windows 10

### Version

8.4 (release)

**Comment by FabianTerhorst** [comment]
You have to call setHeadBlendData before using the other methods.
