### ISSUE TITLE
Player model desync

### ISSUE THREAD

**Issue by Konders** [altmp/altv-issues#1352]
### Description of the problem

Sometimes when player enter the stream, for other player his model is "cs_amandatownley", but for local player its our mp_m_freemode_01 which we set on player auth

### Reproduction steps

Reproduced 3/15 times

1.Two players see each others
2.One of them leave the stream(or die) and come back
3.Other players see the wrong model, but for this client everything is ok

### Expected behaviour

Model syncs correctly

### Additional context

![image_2022-01-24_16-49-00](https://user-images.githubusercontent.com/29742102/150806616-e644ec7e-2916-4afc-a262-6e4bcdd406bd.png)
![image_2022-01-24_16-49-13](https://user-images.githubusercontent.com/29742102/150806642-019e9959-4229-4668-afa7-6034227240f3.png)

### Operating system

Windows 11

### Version

RC2 9.0

**Comment by Konders** [comment]
On release 8.0 I've never seen that problem

**Comment by FabianTerhorst** [comment]
Please provide full reproduction code to reproduce it on a empty server.

**Comment by Konders** [comment]
player.setClothes(2, 1, 0, 4));
Problem can be reproduced when we give pallete id in clothes(with hair component) parameters, in large scale of player visual customization(on auth complete)

**Comment by FabianTerhorst** [comment]
Please provide a full sample resource.

**Comment by Konders** [comment]
We have removed pallete id from setClothes params and use setHairColor, after that problem are not reproducible

**Comment by FabianTerhorst** [comment]
Both wouldn't be a reason for not getting the model streamed.

**Comment by Konders** [comment]
> Both wouldn't be a reason for not getting the model streamed.

You were right, something else is causing the desync problem

We have been sorting through the code line by line for several days in order to understand where the problem is. After that, we could create an empty server with the repro code
But so far without success

**Comment by FabianTerhorst** [comment]
Feel free to comment when you have reproduction Code.

**Comment by cmdflow** [comment]
Same for us. Current 13.37 version. Debian 11. Happens randomly. Nothing special done. Using serverside Character setter. No clothes setter whatever. Sometimes the player is cs_amandatownley for no reason (could be because debug mode reconnecting?) no idea, no further data
