### ISSUE TITLE
Modded cloth bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1353]
### Description of the problem

When I wear modded clothes I can see my torso  but for the other players it's invisible. In some cases the modded clothes do appear but not the torso. Sometimes not even the clothes are visible
Server log: https://i.imgur.com/iHehaKK.png
Images:
- https://cdn.discordapp.com/attachments/759057136914530358/935699049422680134/unknown.png
- https://i.imgur.com/PfLTBXS.jpeg

Edit: As far as I can see the problem is not only with the modded clothes. In the picture you can see that my beard and hair is totally different than that can be seen by others

### Reproduction steps

1. Add some addon clothes to the server. 
2. Set the clothes and the torso using the following native: setPedComponentVariation

### Expected behaviour

Should be working as in the current release version.

### Operating system

Windows 11

### Version

alt:V build #9.0 RC3, branch release

**Comment by FabianTerhorst** [comment]
Please provide reproduction Code.

**Comment by Lekenthu** [comment]
> Please provide reproduction Code.

As far as I can see the problem is not only with the modded clothes. In the picture you can see that my beard and hair is totally different than that can be seen by others.

game.setPedComponentVariation(localPlayer.scriptID, 2, parseInt(cloth), 0, 2);
game.setPedHairColor(localPlayer.scriptID, parseInt(hairColor), parseInt(hair2Color));

**Comment by FabianTerhorst** [comment]
You Mix serverside and Clientside setters

**Comment by Lekenthu** [comment]
> You Mix serverside and Clientside setters

I used natives only.

**Comment by FabianTerhorst** [comment]
Serverside appearance setters are considered in that logic.
