### ISSUE TITLE
RmlUI Drag events not triggered

### ISSUE THREAD

**Issue by xenicle** [altmp/altv-issues#1354]
### Description of the problem

RmlUI Drag events (`dragover`,  `dragout` and `dragdrop`) isn't triggered on RmlUI elements with elements set to rcss  `drag: clone;`

### Reproduction steps

- Download gamemode4 resource in "Additional context"
- Extract this resource to your server 9.0RC resource directory
- Add gamemode4 to your server.cfg resource section
- when connected drag, drop or over the Icon to the content or other Icon : there's no log in console

### Expected behaviour

RmlUI Drag events is triggered on RmlUI elements

### Additional context

[gamemode4](https://drive.google.com/file/d/1dcBTb0Tga_pA_tA5CXOEjTQSXYB8J5o9/view?usp=sharing)

### Operating system

Windows 11

### Version

9.0 RC3

**Comment by martonp96** [comment]
drag: clone will not trigger those events. If you need them you need drag: drag-drop.
See https://mikke89.github.io/RmlUiDoc/pages/tutorials/dragging.html
