### ISSUE TITLE
Reticle is not hiding

### ISSUE THREAD

**Issue by aembee** [altmp/altv-issues#1355]
### Description of the problem

The crosshair is not hidden via Natives. I update the native native.hideHudComponentThisFrame(14);. However, this does not work, I've already asked around, it's probably not going to work for a long time.

### Reproduction steps

native.hideHudComponentThisFrame(14); every tick

### Expected behaviour

Reticle is hiding.

### Operating system

Windows 11

### Version

8.7 release

**Comment by C0kkie** [comment]
It is working in current release and also rc
