### ISSUE TITLE
Synced meta doesn't get synced sometimes

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1356]
### Description of the problem

Sometimes player don't get some player's synced meta on join.
Example: 
Player 1 joins, we set synced meta on him.
Player 2 joins, and sometimes randomly he doesn't receive player 1's synced metas (reading them gives undefined). Other players (if were, or joined and got that meta) can read the meta normally.

Interval between those joins doesn't matter (player 2 can join a lot later, and still get this bug)

If we set some meta on player 1 after player 2 joined, he will get it synced (only the meta that we set, other metas that were set before join won't be synced)

### Reproduction steps

Happens randomly 😭 
It seems, that the bug isn't related to player count, or time between player joins

### Expected behaviour

Synced meta should be synced reliably

### Operating system

Linux

### Version

release/8.9

**Comment by FabianTerhorst** [comment]
Test on dev branch again.

**Comment by zziger** [comment]
> Test on dev branch again.

Will the rc be okay?

**Comment by CoffeeGen** [comment]
I can 100% confirm this (on release). Have often seen this happen with player names being undefined.

**Comment by FabianTerhorst** [comment]
We need to have it confirmed in RC otherwise we cant fix it.

**Comment by CoffeeGen** [comment]
> We need to have it confirmed in RC otherwise we cant fix it.

It's hard to reproduce since it's pretty random. Not sure if we can even reproduce it on RC before the update.

From what I've seen it only tends to happen to specific people. For example: it never happens to me, but another player used to get it all the time (it stopped happening at some point for whatever reason).

Maybe it happens due to packet loss? I've seen packet loss mess with other things too. Not entirely sure how one could solve this though..

**Comment by LennartF22** [comment]
On 9.0-rc5 already set synced meta data is not sent to new players that connect to the server.

**Comment by MyHwu9508** [comment]
I'm using nametags for example with synced and steam synced meta with player data works fine for everything. Just in the first few seconds the player joins the server, his synced data is undefined, even if it's set.

The reason I assume. When the streaming in hook is called the meta are sometimes not loaded yet and will return undefined. Solved this by setting a timeout to a few milliseconds.

**Comment by FabianTerhorst** [comment]
yes its synced async thats where there is a event so you don't need to add a timeout.

**Comment by zziger** [comment]
> I'm using nametags for example with synced and steam synced meta with player data works fine for everything. Just in the first few seconds the player joins the server, his synced data is undefined, even if it's set.
> 
> The reason I assume. When the streaming in hook is called the meta are sometimes not loaded yet and will return undefined. Solved this by setting a timeout to a few milliseconds.

I read the meta all the time, and read it manually when tested and reproduced that bug, so it surely isn't the case here.

Basically I hope this issue is resolved after the update, I think we can wait for some time, and if noone will face this issue again it would mean it was fixed.

**Comment by FabianTerhorst** [comment]
Feel free to comment back when its still reproducable.

**Comment by zziger** [comment]
> Feel free to comment back when its still reproducable.

Reproduced today on current release

**Comment by FabianTerhorst** [comment]
Feel free to comment back when its still reproducable on update 10.
