### ISSUE TITLE
getControlNormal working not properly in vehicle

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1357]
### Description of the problem

When player is in vehicle, position X always 0,
Y working properly

var x = native.getControlNormal(28, 239);

### Reproduction steps

var x = native.getControlNormal(28, 239);
    console.log("X: " + x);
	var y = native.getControlNormal(28, 240);
    console.log("Y: " + y);
    
**Try it in vehicle**

### Expected behaviour

Should get x when in vehicle too

### Operating system

Ubuntu 20.04 and Windows 10

### Version

8.9

**Comment by PavlovTM** [comment]
What does it return ?
Does it return 0 or an error ?

Perhaps you need to call it in a loop, to ensure the game detects he's in a car in the right moment

**Comment by TuK4z** [comment]
It returns 0, i don't think that should be in a loop. Because when u are in person it perfectly gives X and Y position of the screen.
When in car it always gives X = 0 and Y = right number. It's to get screen coordinates, but X not working in a vehicle.

I would be gratefull if someone try it out, to check if they are getting same result, but i tested it several times, always X not working in vehicle.
var x = native.getControlNormal(28, 239);

**Comment by YannBCF** [comment]
@TuK4z Can you try again on dev/10.0-dev2 ? Because I cannot reproduce it, here is the code I use.

```ts
setInterval(() => {
    const x = native.getControlNormal(28, 239);
    const y = native.getControlNormal(28, 240);

    console.log(`x: ${x}, y: ${y}`);
}, 1000);
```
Note that you can also use the method ``alt.getCursorPos()`` and normalize it with the screen size

**Comment by YannBCF** [comment]
You can now use https://github.com/altmp/altv-js-module/commit/5a777837dd77ce6c56248f19f39af0b3617bb84a in dev ```alt.getCursorPos(true)``` and it will return a normalized version of it.

**Comment by TuK4z** [comment]
Hmm i tried several times in 9.6 and it works like charm... Thank you, i guess it was my mistake, o just some fix in update 9-9.6

**Comment by TuK4z** [comment]
I also tried alt.getCursorPos(true) it works perfect, Ty both ways working in 9.6

**Comment by YannBCF** [comment]
Side note but getCursorPos with the normalized boolean is not even yet in dev branch, so you only tested it with absolue value there if you didn't divided it by the screen resolution.
