### ISSUE TITLE
Lag on alt.Audio play() with custom url

### ISSUE THREAD

**Issue by its4l3x** [altmp/altv-issues#1358]
### Description of the problem

When you play a sound via the alt.Audio API with a custom url (.mp3) the game get a micro lag on the start "stream"

### Reproduction steps

Execute following code for reproducment:

```
let audio = new alt.Audio("https://dl.statev.de/sounds/race_start_4.mp3", 0.5, 'radio', false);

audio.addOutput(alt.Player.local.scriptID)

audio.play();
```

### Expected behaviour

no micro lag on the start stream of the audio

### Operating system

Windows 10 / Windows Server 2019 & 2022

### Version

rc/9.0-rc3

**Comment by LeonMrBonnie** [comment]
That is normal and not something we can do anything against, you should create all the Audio instances you need in the top level of your clientside script, and play them when you need them.
