### ISSUE TITLE
vehicle default extras maybe not fully initialised

### ISSUE THREAD

**Issue by DanielSchuech** [altmp/altv-issues#1359]
### Description of the problem

The default states of the vehicle extras seems to be not fully initialised. It even changed after going out of the streaming range and going back to the vehicles or just restarting the game.

Tested with `trailersmall` and a modded vehicle.

I will add images to the respective reproduction steps to better describe the issue.
I know it is hardly to test with custom modded vehicles but maybe it still helps to find the issue.

I disabled my vehicle `vehicle.setExtra(...)` calls to just watch the default initialising by AltV.

After repairing the vehicle the sync seems to work perfectly. Then there are no issues with restarting or joining the streaming range again for that vehicle.

This issue is new with the 9.0 rc's and worked on 8.0

I could set the extras using `setExtra` after spawning to manually initialise them but I dont think that this has to be done. Or am I wrong?

Best regards
Daniel

### Reproduction steps

spawn vehicle:
- trailersmall
![image](https://user-images.githubusercontent.com/9282669/151834424-d6827705-e2c9-4c93-b884-04691f4d5172.png)
- modded vehicle (lightbars are missing)
![image](https://user-images.githubusercontent.com/9282669/151834547-42788652-e0af-41a0-9561-7baa745bf7f4.png)

after restarting the game:
- trailersmall
![image](https://user-images.githubusercontent.com/9282669/151834638-9b3d68eb-dd0a-4df8-8013-8db3bef3da33.png)
- modded vehicle
![image](https://user-images.githubusercontent.com/9282669/151834740-4c4086c3-4d47-4c6b-855a-7969f5119573.png)

after `vehicle.repair()`:
- trailersmall
![image](https://user-images.githubusercontent.com/9282669/151834829-3b28fe66-d65e-49fb-852a-47fe26553e9c.png)
- modded vehicle
![image](https://user-images.githubusercontent.com/9282669/151834888-11d6fe35-2025-4be9-9880-8f7de35f91bb.png)

### Expected behaviour

Vehicle extras are initialised with the defaults of the vehicle.

### Additional context

I am using the `vehmodels.bin` and `vehmods.bin` from AltV DIscord Snippets Channel 20.12.21
The data folder from `rc` Branch seems not to include the vehicles from the last GTA Update.

I tested the new `getVehicleModelInfoByHash` to have a look into the extras with `hasDefaultExtra` and it returned the same state that was visible (e.g. false for the lightbar even when it should be true by default)

### Operating system

Ubuntu 18.04

### Version

9.0-rc6

**Comment by FabianTerhorst** [comment]
Does the trailersmall bug also happens with the official vehicle bin from altv download page?

**Comment by DurtyFree** [comment]
[altv-server-data-bins.zip](https://github.com/altmp/altv-issues/files/7972733/altv-server-data-bins.zip)
@DanielSchuech Can you please replace your server data binary files with those and test again?

**Comment by FabianTerhorst** [comment]
You tried the cdn bins from release branch?

**Comment by DanielSchuech** [comment]
I tested the release bins now and it is not working, too.

**Comment by TeubyDE** [comment]
confirmed with trailersmall

**Comment by C0kkie** [comment]
Should be fixed in release

**Comment by dexslab** [comment]
Most vehicle extras can be set default via vehicles meta make sure you have the extras you want set there as they should populate based on that. GTA V will randomize extras considered optional on every vehicle spawn.
