### ISSUE TITLE
Unimplemented  WeaponModel C#

### ISSUE THREAD

**Issue by GuilhermeTrevizani** [altmp/altv-issues#1361]
### Description of the problem

The weapons below were not implemented in the enumeration: AltV.Net.Enums.WeaponModel:

weapon_navyrevolver (0x917F6C8C)
weapon_ceramicpistol (0x2B5EF5EC)
weapon_raycarbine (0x476BF155)

### Reproduction steps

Check WeaponModel enum C#.

### Expected behaviour

Implement the weapons in the enum.

### Operating system

Windows 11

### Version

8.0.0

**Comment by LeonMrBonnie** [comment]
Open this issue in the C# module repository, or even better just make a PR and add the missing values.
