### ISSUE TITLE
player.Kick reason is not shown

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-issues#1364]
### Description of the problem

When kicking a player with a reason, you get kicked but it shows "Timed out" rather than the actual kick message.

## JS-Module
```typescript
import alt from "alt-server";

alt.on("playerConnect", (player: alt.Player) => {
  player.kick("Test Reason");
});
```

## CSharp Module
```csharp
foreach (var player in Alt.GetAllPlayers())
{
	player.Kick("Test Reason");
}
```

### Expected behaviour

Display the proper kick message - in this case "Test Reason"

### Operating system

Windows 10

### Version

rc/9.0-rc6

**Comment by C0kkie** [comment]
I tried your snipped and  my client just crashed.
If i use the kick method later, i get the correct kick message.

Which server/client version do you use?

**Comment by xLuxy** [comment]
Well, for some strange reasons i was using an older version of the server package. It does work as intended.
