### ISSUE TITLE
Server not responding error happens alot

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1366]
### Description of the problem

After I implemented early auth back in mid-december-ish, a lot of connectivity issues started to appear. Could never figure out why.

Then, after 9.0 update a few days ago, those issues only got worse. A lot of players are reporting a "Server not responding" error. Even players that were able to connect just fine before are now getting that error.

Don't have much info. My server uses cloudflare CDN for early auth and resources. Hosted at Avoro with DDoS protection.

### Reproduction steps

I have none

### Expected behaviour

Players to connect properly

### Operating system

Windows 10 for users(I assume), Ubuntu 20.04 for server

### Version

Latest release 9.x

**Comment by MyHwu9508** [comment]
I had such an issue with my users, because the IP address of the main server (not CDN) was blacklisted on some German Fritz!Box devices. When creating the CDN packages and generating the connect.json I changed the IP flag to the actual server domain instead of IP address. This solved the issue for my players.

**Comment by CoffeeGen** [comment]
> I had such an issue with my users, because the IP address of the main server (not CDN) was blacklisted on some German Fritz!Box devices. When creating the CDN packages and generating the connect.json I changed the IP flag to the actual server domain instead of IP address. This solved the issue for my players.

ahh so if I'm correct you got a domain name linked to that IP address correct? and in connect.json, instead of your IP it has smtn like "mywebsite.com"

**Comment by MyHwu9508** [comment]
> > I had such an issue with my users, because the IP address of the main server (not CDN) was blacklisted on some German Fritz!Box devices. When creating the CDN packages and generating the connect.json I changed the IP flag to the actual server domain instead of IP address. This solved the issue for my players.
> 
> ahh so if I'm correct you got a domain name linked to that IP address correct? and in connect.json, instead of your IP it has smtn like "mywebsite.com"

Yep. Using a subdomain for CDN and the game server. Somehow this is working fine for everyone since I made that change.

And when moving from IP to domain name the alt:V cache folder name for the server will change and the users may loose their localstorage file.

**Comment by CoffeeGen** [comment]
Ahh I see. Thanks, I'll try this first thing tomorrow :)

**Comment by YannBCF** [comment]
@CoffeeGen any news ?

**Comment by CoffeeGen** [comment]
> @CoffeeGen any news ?

Apologies, haven't been able to test this yet as I've been pretty ill from covid since shortly after I posted the last reply. I'll update once I have tested it

**Comment by CoffeeGen** [comment]
A little late, but I pushed the change just now. Will let yall know if it solves the issues.

We've also been getting the "resource download failed" error quite a lot. So am hoping this will fix both of them.

**Comment by YannBCF** [comment]
@CoffeeGen Any update on this ?
