### ISSUE TITLE
Some animation doesn't work

### ISSUE THREAD

**Issue by LameuleFR** [altmp/altv-issues#1367]
### Description of the problem

Some functional animation on other MP mods doesn't work on altV with the same args.

### Reproduction steps

Request the animDict with async/promise method then launch it:

const dictAnim = "anim@mp_player_intmenu@key_fob@";
game.taskPlayAnim(alt.Player.local.scriptID, dictAnim, "fob_click_fp", 8.0, 8.0, -1, 48, 1, false, false, false)

This anim with theses args is working on FiveM/RageMP

### Expected behaviour

Play the animation

### Operating system

Windows

### Version

9.4

**Comment by C0kkie** [comment]
We use the same animation and it works

**Comment by C0kkie** [comment]
`native.taskPlayAnim(alt.Player.local.scriptID, "anim@mp_player_intmenu@key_fob@", "fob_click", 8.0, -4.0, 1000, 49, 0.0, false, false, false);
`

**Comment by ThomasMarangoni** [comment]
animations need to be requested before playing them.

**Comment by LameuleFR** [comment]
> animations need to be requested before playing them.

"Reproduction steps
Request the animDict with async/promise method then launch it:"

Also @C0kkie it's not the same args as used on other MP mod, that was the initial report.
Many animation require different args in the native than FiveM/RageMP to be played.
