### ISSUE TITLE
Ability to show message to a client in a queue

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1368]
### Description of the problem

As for now current implementation of connection queue looks more like a stuck infinite resource load than a queue. It would be nice to have ability to show a client some message, e.g. information about where he is exactly in the queue, and some other additional info

### Desired solution for the problem

There are currently accept and decline methods on a connection info object, maybe adding a third one like `setMessage`

### Alternatives you considered

Using my own connection queue based on early auth

**Comment by FabianTerhorst** [comment]
Will be implemented in the new client ui.

**Comment by xxshady** [comment]
Added in 15.0
