### ISSUE TITLE
playerDeath: killer is undefined

### ISSUE THREAD

**Issue by xtance** [altmp/altv-issues#1371]
### Description of the problem

In playerDeath event, killer and weapon are is not sometimes, even when player is killed by another player.

### Reproduction steps

```
alt.on('playerDeath', (player, killer, weapon) => {
    console.log(killer instanceof alt.Player);
});
```
Sometimes true and sometimes false

### Expected behaviour

I expect killer to be a player object, in case if player was killed by him

### Additional context

Iit is happening with "normal" weapons aswell and not only explosives

I know that it's ok for killer to be undefined, if player killed himself, but thats not the case

It feels like completely random, we tried with same weapons and same players and have no clue why it is like that in some cases

Also, when killer isn't there, weapon won't be there aswell

### Operating system

Windows 10 and also Debian 10

### Version

release/9.5

**Comment by CoffeeGen** [comment]
Can confirm this. We're also having issues. Appears to be completely random? Although it does happen quite often.

15 minutes of QA testing will most likely make it occur atleast once.

**Comment by YannBCF** [comment]
@CoffeeGen Can you try again with last dev build ? We were not able to repro it on qa server

**Comment by FabianTerhorst** [comment]
Feel free to comment back when you still have the issue.
