### ISSUE TITLE
alt.onClient repeats itself.

### ISSUE THREAD

**Issue by Tricky-Ricky** [altmp/altv-issues#1374]
### Description of the problem

Once I add a Command Handler, the alt.onClient event iterates over itself twice.

If I remove the Command Handler script - The chat works as expected. I have been through the code for the last 4 days before coming here, and cannot see why or what is causing the alt.onClient to loop itself.

Debugging in Visual studio code, just shows the alt.onClient looping, the command handler is fired once at start up, otherwise isn't touched when a player is typing in chat. The chat will output the message twice, triggered by the onClient repeating itself.

I have added console.logs for 3 steps, Vue -> altV client -> altV Server. It's on the serverside event (chat.js: line 15) that repeats after emitting back too the client. Due to debugging restrictions, I am unable to debug the altV Client side within the resources folder to dig deeper as to why this is happening. 

I have created a minimal script replication here to showcase this, which can be found here:
https://github.com/Tricky-Ricky/Issues-test

### Reproduction steps

Download files
Run NPM Install
Start the server
Press "J" to type in the input box and enter to send.

### Expected behaviour

Chat should output once

### Additional context

I have tried debugging within VSC, However it only loads the resources/server files and doesn't include the resources/client, so I am unable to find out why this is doing this.

### Operating system

Windows 10

### Version

Latest release

**Comment by LeonMrBonnie** [comment]
This is the wrong place to search for help with your coding problems, please ask on the discord instead.
