### ISSUE TITLE
Implementation of branch validation in altv.cfg

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1378]
### Description of the problem

If you will write the wrong branch name, client will try to fetch updates from branch name, that you entered, even if it is wrong

![image](https://user-images.githubusercontent.com/54737754/154818336-5ebd8d9a-633f-46d2-8f85-8b5c6ae3052b.png)

### Reproduction steps

Enter wrong branch into altv.cfg

### Expected behaviour

Branch validation

### Operating system

Windows 11

### Version

10.0-dev2

**Comment by xxshady** [comment]
ah, and it should be an improvement, not a bug, i think

**Comment by LeonMrBonnie** [comment]
Added in next update
