### ISSUE TITLE
Client console connect command

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1380]
### Description of the problem

Now we have a command for reconnect, so why not add a command for connect as well?
With the introduction of the external console, this became even more relevant, because now we can avoid using the game window at all to develop certain things or test something for which we don't need the game window itself

### Desired solution for the problem

Add client `connect [ip:port or url] [password?]` console command

**Comment by xLuxy** [comment]
Can you provide some use cases? You usually develop locally with debug enabled and this means, that you can basically reconnect to the local server once your resource started.

See: https://docs.altv.mp/articles/auto_reconnect.html#

**Comment by xxshady** [comment]
This command is needed for the connection to the server, not reconnect.

The purpose of this feature is to allow us to abstract from the game and ui and concentrate on developing or allow us to test something faster.

Client launch option `-connecturl` also cannot replace this command because the server may be shut down at the time of the first connection

**Comment by YannBCF** [comment]
The auto_reconnect feature also allows you to connect to the server on client startup.

**Comment by xxshady** [comment]
this is still different from the feature I'm requesting here

**Comment by C0kkie** [comment]
Will be added in dev/10.0-dev19
