### ISSUE TITLE
TaskPlayAnim isn't synced when you set lockPos args to true

### ISSUE THREAD

**Issue by yannbcf** [altmp/altv-issues#1381]
### Description of the problem

The native https://natives.altv.mp/#/0xEA47FE3719165B94 is not synced when setting the 3 last parameters to true, it would be nice to have it synced synced otherwise you can move while doing an animation

### Reproduction steps

```ts
const localPlayer = alt.Player.local;
native.requestAnimDict("dead");

native.taskPlayAnim(localPlayer, "dead", "dead_a", 8.0, 1.0, -1, 33, 0, true, true, true);
```

### Expected behaviour

The ragdoll animation should be synced

### Operating system

Windows 10

### Version

dev10.0-dev2

**Comment by YannBcf** [comment]
We probably don't care about it anyway since we can freeze the player either via the native https://natives.altv.mp/#/0x428CA6DBD1094446 or via the player serverside frozen setter

**Comment by YannBcf** [comment]
Maybe we will care in the future, so I re-open it so we know the issue exists

**Comment by martonp96** [comment]
those aren't lockpos args
