### ISSUE TITLE
Add a normalized getCursorPos method

### ISSUE THREAD

**Issue by YannBCF** [altmp/altv-issues#1382]
### Description of the problem

It would be nice to be able to have a normalized cursor position on the screen

### Desired solution for the problem

I was thinking of just passing a boolean to the current getCursorPos method to return a normalized version or not

```js
alt.getCursorPos(true);
```

**Comment by xxshady** [comment]
as an alternative you can use native for getting screen resolution and divide current cursor pos by it

**Comment by LeonMrBonnie** [comment]
Done
