### ISSUE TITLE
Add screenResolutionChange event

### ISSUE THREAD

**Issue by YannBcf** [altmp/altv-issues#1384]
### Description of the problem

Since rmlui got introduced, and methods such as setMinimapComponentPosition got implemented, it would be nice to be able to make it more dynamic by updating UI elements when the screen resolution changes

### Desired solution for the problem

```ts
alt.on("screenResolutionChange", (oldResolution: alt.Vector2, newResolution: alt.Vector2) => {});
```

**Comment by LeonMrBonnie** [comment]
Done
