### ISSUE TITLE
Bucket System

### ISSUE THREAD

**Issue by risvensh** [altmp/altv-issues#1395]
### Description of the problem

My house system used multiple interiors, Bucket system in FiveM use one interior for all players with hiding players 

### Desired solution for the problem

https://forum.cfx.re/t/routing-buckets-split-game-state/1831709 

https://forum.cfx.re/t/release-vrp-free-house-system/4253748

### Version

10

**Comment by FabianTerhorst** [comment]
Dimension Property is what you are looking for.
