### ISSUE TITLE
Invalid Documentation Links

### ISSUE THREAD

**Issue by iCry1337** [altmp/altv-issues#1396]
### Description of the problem

In the documentation the SDK is linked to an unsopported version : https://docs.altv.mp/cs/articles/setup.html -> 5.0 also the example *.csproj has wrong version -> https://docs.altv.mp/cs/articles/create-resource.html

### Reproduction steps

https://docs.altv.mp/cs/articles/setup.html
https://docs.altv.mp/cs/articles/create-resource.html

### Expected behaviour

Updated Links and Examples (Maybe users can update it like in Doxygen Wiki?)

### Operating system

Windows

### Version

9.0

**Comment by LeonMrBonnie** [comment]
This issue does not belong here. Either open an issue in the C# module repo, or make a PR there to fix them yourself. You can find the articles here: https://github.com/FabianTerhorst/coreclr-module/tree/dev/docs/articles
