### ISSUE TITLE
streamSyncedMetaChange is always called on entity stream in

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1398]
### Description of the problem

At first you may think this is a useful bug(or feature xd), but it really isn't, because `"streamSyncedMetaChange"` is called before the entity is spawned (`"gameEntityCreate"`), which can cause confusion among users

### Reproduction steps

1. create a vehicle
2. subscribe to `"streamSyncedMetaChange"` and `"gameEntityCreate"` events clientside
3. set some stream synced meta on the vehicle
4. restream the vehicle (`vehicle.streamed`)
5. `"streamSyncedMetaChange"` is always called on stream in and before `"gameEntityCreate"`

### Expected behaviour

The `"streamSyncedMetaChange"` should be called after `"gameEntityCreate"` or this bug/feature should be fixed

### Operating system

Windows 11

### Version

dev/10.0-dev3

**Comment by deluvas1911** [comment]
Confirmed on dev/10.0-dev21

**Comment by C0kkie** [comment]
@xxshady  test on newest dev

**Comment by FabianTerhorst** [comment]
Fixed in 16.0

**Comment by matvejs16** [comment]
> Fixed in 16.0

Not fixed

**Comment by xxshady** [comment]
fixed
