### ISSUE TITLE
Add setHudComponentPosition function

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1399]
### Description of the problem

**Suggestion**
```js
/**
 * @param {string} name
 * @param {string} alignX
 * @param {string} alignY
 * @param {number} posX
 * @param {number} posY
 * @param {number} sizeX
 * @param {number} sizeY
 * @returns {void}
 */
setHudComponentPosition(name, alignX, alignY, posX, posY, sizeX, sizeY)

// "L" Left - "B" Bottom
alt.setHudComponentPosition('HUD_STREET_NAME', 'L', 'B', -10.0, -10.0, 0.0, 0.0);
```

In order to optimize the client-side code, instead of using natives to hide HUD components, we can use this function to hide or change the position of the components.

### Desired solution for the problem

Just like #804

### Additional context

HUD components data (from `common:/data/ui/frontend.xml`) for a specified component.

The worst approach to hide `Street Name`:
```js

setInterval(() => {
    native.hideHudComponentThisFrame(9); // HUD_STREET_NAME
}, 0);
```

Best approach:
```js
alt.setHudComponentPosition('HUD_STREET_NAME', 'L', 'B', -10.0, -10.0, 0.0, 0.0);
```

**Comment by FabianTerhorst** [comment]
I only see https://natives.altv.mp/#/0xAABB1F56E2A17CED . Are you sure its possible to have such setter?

**Comment by mrgharabaghi** [comment]
I'm not sure, but I guess it's possible like #804.
This function has more advantages than https://natives.altv.mp/#/0xAABB1F56E2A17CED.

**Comment by FabianTerhorst** [comment]
That has nothing to do with the other Setter. And the other Setter doesnt help for this.

**Comment by FabianTerhorst** [comment]
Feel free to comment back when you know that the functionality is actually possible.
