### ISSUE TITLE
Add event playerSpawn (both of sides)

### ISSUE THREAD

**Issue by KifKick** [altmp/altv-issues#14]
`alt.on('playerSpawn', (player) => {
})`

**Comment by AlteredCarbonate** [comment]
Any progress or similar?

**Comment by LeonMrBonnie** [comment]
Serverside this is not needed because alt:V never does this automatically for you, you have full control of spawning the player meaning you also always know when the player is spawned.
If you need this event just emit it yourself, same for client.
