### ISSUE TITLE
Implement player.velocity serverside

### ISSUE THREAD

**Issue by LameuleFR** [altmp/altv-issues#1401]
### Description of the problem

Suggestion
Implement serverside player.velocity getter like vehicle.velocity

### Desired solution for the problem

Implement serverside player.velocity getter like vehicle.velocity

### Alternatives you considered

Sending events around, that contain a callback

### Additional context

I develop a skill system.

**Comment by FabianTerhorst** [comment]
I don't think that a player has a velocity.

**Comment by FabianTerhorst** [comment]
But i can add 
float strafeSpeed;
float forwardSpeed;

**Comment by LameuleFR** [comment]
Both value should be enough to realize what i need ! 

Thank's

**Comment by FabianTerhorst** [comment]
Added in next build.
