### ISSUE TITLE
SetHeadOverlay not working correctly for all indexes

### ISSUE THREAD

**Issue by ChuckGod6** [altmp/altv-issues#1402]
### Description of the problem

The appeareance setter methods introduced in the last altv versions doesn't seem to work correctly for all overlays and indexes.
I have noticed this problem with setHeadOverlay as I've tried to set ageing of a character. It doesn't seem to do anything except for index 13 which is the only one working correctly.

If I'm using the suitable native method it works as it should.

### Reproduction steps

```js
player.model = 'mp_m_freemode_01';
player.setHeadBlendData(0, 0, 0, 0, 0, 0, 0, 0, 0);
player.setHeadBlendData(
      0,
      21,
      0,
      0,
      21,
      0,
      0.5,
      0.5,
      0
);

player.setHeadOverlay(3, 14, 1.0);
```

### Expected behaviour

The server side methods should set the appeareance data as it does when using the native methods.

### Operating system

Windows 10 / Debian 10

### Version

release/9.6

**Comment by deluvas1911** [comment]
Working on dev/10.0-dev21
