### ISSUE TITLE
handing null several times to IVehicle.SetDamageAsync yields MemoryAccess Violation

### ISSUE THREAD

**Issue by bietiekay** [altmp/altv-issues#1403]
### Description of the problem

Calling SetDamageAsync several times on a/multiple vehicle objects while handing over a null object crashes AltV.

![image](https://user-images.githubusercontent.com/219032/157684219-bc68f320-3e80-4e19-b2b9-ce5bf218b018.png)

### Reproduction steps

call vehicle.SetDamageAsync(null) 10x 

See crash.

### Expected behaviour

not crashing - actually not even taking any strange strings/null values at all 

### Operating system

Windows and Linux

### Version

9.6

**Comment by FabianTerhorst** [comment]
Will add a exception when the method is called with null. Since hte method is not null safe.

**Comment by FabianTerhorst** [comment]
Also c# module related.

**Comment by bietiekay** [comment]
by any chance: Is there any possibility to get more debug information into altV for development purposes? I've got several other "null reference exceptions" that clearly get thrown out of AltV on the console - but I cannot catch them.
