### ISSUE TITLE
Add sync for taskGoToCoordAnyMeans

### ISSUE THREAD

**Issue by TheGodlyLuzer** [altmp/altv-issues#1404]
### Description of the problem

The native 'taskGoToCoordAnyMeans' is not synced. 
Would be great to add sync to it since it's the only native known to me, that makes the ped walk to a specific coordinate.

### Desired solution for the problem

Add sync for ped movement when using 'taskGoToCoordAnyMeans'.

### Version

release 9.6

**Comment by xxshady** [comment]
last time tested, it was synced for me

**Comment by YannBcf** [comment]
Peds are clientside entities, meaning they are not synced at all. This kind of stuff will come later with a ped API.
I assume you're using this native on peds since player position is synced

**Comment by TheGodlyLuzer** [comment]
Ahh okay, thanks that explains it
