### ISSUE TITLE
setDisableVehicleWindowCollisions only works if Player is in Vehicle

### ISSUE THREAD

**Issue by lokuPadoku** [altmp/altv-issues#1405]
### Description of the problem

Like the title, the native setDisableVehicleWindowCollisions only works if the Player is in the Vehicle. If this native is called on an Entity like Enus Deity by clienside event "gameEntityCreate" while no Player is inside the car, the Windows are still bulletproof.

### Reproduction steps

This won't work if no player inside vehicle.

`on('gameEntityCreate', (entity: Entity) => {
  if (entity instanceof Vehicle) {
    setDisableVehicleWindowCollisions(entity.scriptID, true);
  ]
}`

### Expected behaviour

It should work if no player is in vehicle

### Operating system

Windows 11

### Version

release/9.6

**Comment by FabianTerhorst** [comment]
Natives that influence a vehicle only works when the player that calls them is netowner. Otherwise best way would be to have a setter serverside.
