### ISSUE TITLE
Ability to add effects to Voice class

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1406]
### Description of the problem

When players speaks together in 3D space and at the same time a person speaks in the radio, it's unrealistic and a little bit difficult to recognize which voices from radio or 3D space.

### Desired solution for the problem

As `Vektor` said in Discord:
`The plans are changed for the filters, luajit will be implemented and you will be able to create your filters privately in lua`
https://discord.com/channels/371265202378899476/371271006360436757/945706667960582254

### Additional context

This issue is related to #984.

**Comment by DurtyFree** [comment]
Until we implemented support to provide these filters via client side scripts, you are free to contribute your desired radio effect to our repository: https://github.com/altmp/voice-filters

Everything is already there, you just have to do a pull request, which will also contribute back to the platform and community.

Other option is to wait until we add official support to provide those effects via client side scripts - which is not planned to be worked on right now, so theres no ETA.

Thanks for understanding and pls don't open a new issue every 5 months, thx

**Comment by mrgharabaghi** [comment]
> Until we implemented support to provide these filters via client side scripts, you are free to contribute your desired radio effect to our repository: https://github.com/altmp/voice-filters
>
> Everything is already there, you just have to do a pull request, which will also contribute back to the platform and community.

I've done this before in https://github.com/altmp/voice-filters/commit/4b1467664253a74b5493a3825f23d881e7d31ce6

The reason of this issue is `Vektor` which said:
`The plans are changed for the filters, luajit will be implemented and you will be able to create your filters privately in lua` in discord as you can see.
https://discord.com/channels/371265202378899476/371271006360436757/945706667960582254

The new plan == new issue.

**Comment by mrgharabaghi** [comment]
implemented in `v15`

**Comment by C0kkie** [comment]
We will close it, if the api is fully implemented, cuz rn its not.

**Comment by FabianTerhorst** [comment]
v15 allows applying clientside created filters to voice.
