### ISSUE TITLE
Client-side: setPedComponentVariation

### ISSUE THREAD

**Issue by SilverGoLt** [altmp/altv-issues#1408]
### Description of the problem

Currently seems like there's an issue when setting player's hair client-side (Making a Character Editor) currently the max value for hair you get is 77 but you can only set it up to 22 higher than that the hair doesn't show up (Doesn't load Hair).

### Reproduction steps

`
game.setPedComponentVariation(player, 2, 24, 1, 0); // Setting Hair higher then 22 will not load
`

### Expected behaviour

Should be able to set Player hair up to max range from `game.getNumberOfPedDrawableVariations(player, 2)`

### Operating system

Windows 10

### Version

Release

**Comment by YannBcf** [comment]
Wrong usage => ``game.setPedComponentVariation(player, 2, 24, 0, 0);`` not every drawable have more than 1 texture
