### ISSUE TITLE
Create start menu shortcut as system wide or user specific

### ISSUE THREAD

**Issue by MusaSSH** [altmp/altv-issues#1410]
### Description of the problem

Before starting to explain my feature request I'll define names for directories.

System wide, C:\ProgramData\Microsoft\Windows\Start Menu\Programs
User specific, %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

As of alt:V 9.0, the installation file creates a alt:V Multiplayer shortcut in system wide directory, there is two problem with that.

1. In order to create a shortcut in a system wide directory, you have to start altv.exe as administrator. Which I'm completely against, if I just want to install an application to my user directory, I shouldn't be have to run an application as administrator.
2. The system wide shortcuts can be available from any Windows user profile, if there are multiple users of same PC, there can be multiple Windows user profile for each one. This also violates my privacy because other Windows user profiles will be able to see this shortcut but they will not be able to open it, Windows doesn't let a user to access files in other user directories.

### Desired solution for the problem

alt:V installer asking us to select a installation directory, if we're installating alt:V to a directory anywhere inside %USERPROFILE%, create start menu shortcut in user specific start menu directory, if we are installing alt:V outside of %USERPROFILE% create shortcut in system wide start menu directory.

### Alternatives you considered

There is another alternative. Create shortcut in user specific directory if alt:V installer is not running as administrator, if it's running as administrator it can create shortcut in system wide without listening to where alt:V is installed. This alternative still can be a problem if a user installs alt:V to their user profile but randomly runs installer as administrator so in my opinion the desired solution for the problem is the best way.

**Comment by zziger** [comment]
In the reworked launcher both desktop and start menu shortcuts are created in user directories
