### ISSUE TITLE
Saving resource.cfg in UTF-8 with BOM silently breaks config parse

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1411]
### Description of the problem

Provided reproduction resource looks like loaded successfully, but actually it isn't (should log "Working!"). If you save it's resource.cfg in UTF-8 without BOM, then it works properly

### Reproduction steps

[reproduction.zip](https://github.com/altmp/altv-issues/files/8324200/reproduction.zip)
1. Start server with this resource, it seems to be loaded succesfully, but it doesn't log message
2. Save resource.cfg in UTF-8 without BOM
3. Start server, resource loaded succesfully, but now it actually works (logs "Working!")

### Expected behaviour

Maybe some warning or error about invalid encoding, or support of BOM

### Operating system

Ubuntu 20.04, Windows 10

### Version

release 9.6

**Comment by FabianTerhorst** [comment]
With bom causes the resource.cfg to get parsed invalid. Sometimes it skips keys so the behavior that happens might vary depending on key order.

**Comment by FabianTerhorst** [comment]
Anyone can fix this issue the repo for the parser is open source.
https://github.com/altmp/alt-node

**Comment by ZackaryH8** [comment]
When files are saved with BOM `EF BB BF` is prepended to the file, this just need to be checked for and either ignored or throw an error

**Comment by LeonMrBonnie** [comment]
Fixed in next update
