### ISSUE TITLE
Several files are required to be in cef folder in order for cef to render on linux

### ISSUE THREAD

**Issue by oranmehavi** [altmp/altv-issues#1412]
### Description of the problem

CEF is not rendering inside the alt:v client on linux.

### Reproduction steps

In order to get CEF to render in the alt:v client on linux, some files from `libs` folder need to be copied to `cef` folder:
`libcef.dll, icudtl.dat, snapshot_blob.bin, chrome_elf.dll, v8_context_snapshot.bin`

When the files in the list are not present inside the `cef` folder then [this](https://i.gyazo.com/thumb/1200/493c99558d9424a48282560b8e0160da-png.jpg) happens as described in this [Troubleshooting section](https://docs.altv.mp/articles/troubleshooting/client.html#webview-not-working)

### Expected behaviour

The expected behavior is that the installer will also download/copy the files to the `cef` folder.

### Additional context

Other things to note is that I have not used vanilla version of Wine but instead used [Wine-GE](https://github.com/GloriousEggroll/wine-ge-custom/releases) (the latest release is preferred of course) and used [Lutris](https://lutris.net/) to download Steam (Windows version) and then download GTA:V through that.

In order to use Wine-GE with Lutris, it needs to be extracted to `~/.local/share/lutris/runners/wine/`.

### Operating system

Linux (all distributions)

### Version

latest

**Comment by C0kkie** [comment]
Is that still a thing? Even on newest dev? @oranmehavi

**Comment by oranmehavi** [comment]
Yes

**Comment by zziger** [comment]
Fixed in `dev/15.0-dev871`
