### ISSUE TITLE
Add the ability to get a server blip on the client side

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1413]
### Description of the problem

Currently, if we create a blip on the server, we cannot determine on the client side which one we created because we have all blips mixed in `alt.Blip.all` without any ids

### Desired solution for the problem

- Add extra blips getter created from the server side, e.g. `alt.Blip.allRemote` or `alt.Blip.allServer`
- Add mvalue for server blip, so we can send it to client from server directly
- Maybe add IDs for blips (like we have for entities)

### Alternatives you considered

Track all clientside created blips ourselves and by exclusion get server blips from `alt.Blip.all` (how to get the exact one if we created more than one on server idk xd)

### Additional context

Use case: creating blips for each player and hiding local player's blip on the client side

### Version

dev/10.0-dev7

**Comment by LeonMrBonnie** [comment]
You can use `blip.isRemote` now to check whether a blip is created from serverside or not.

**Comment by xxshady** [comment]
@LeonMrBonnie what about my use case? what if i have several server blips and i want to get a specific one of them?

**Comment by LeonMrBonnie** [comment]
I don't know if adding blips to the id system would be a good idea, and without we can't send them over the network. I let this decision open for the other developers to decide
