### ISSUE TITLE
Load missing IPLs by default

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#1415]
### Description of the problem

If you create a new alt:V server you need to search in the discord or somewhere else all the missing ipls, that there are no holes in the map

### Desired solution for the problem

Add a function to load all missing ipls or load it by default

**Comment by LeonMrBonnie** [comment]
Unsure if we should actually do that, would also mean we have to maintain a list of IPLs to be loaded in core

**Comment by C0kkie** [comment]
Vektor suggested a function the past thats why that issue, i just forgot to create it :D
Also that list will probably never change

**Comment by ZackaryH8** [comment]
> Vektor suggested a function the past

I think that's the best way to do it, `alt.loadDefaultIPLs()` or something like that

**Comment by C0kkie** [comment]
We will load it by default not via method

**Comment by C0kkie** [comment]
Will be added in dev/10.0-dev19

**Comment by gt4ever1988** [comment]
IPLs then only loaded in the standard if, for example, alt.loadDefaultIPLs() is called and not in general, right?

**Comment by C0kkie** [comment]
Its loaded in general, there is no method

**Comment by gt4ever1988** [comment]
Thanks for your info! Which IPLs are then automatically loaded so that we don't load them additionally?

**Comment by C0kkie** [comment]
ex_dt1_02_office_02b
FIBlobbyfake
v_tunnel_hole
trevorstrailertidy
farm
farmint
farm_lod
farm_props
des_farmhouse
facelobby
CS1_02_cf_onmission1
CS1_02_cf_onmission2
CS1_02_cf_onmission3
CS1_02_cf_onmission4
bkr_bi_hw1_13_int
shr_int
sp1_10_real_interior
sp1_10_real_interior_lod
id2_14_during_door
id2_14_during1
refit_unload
post_hiest_unload
Carwash_with_spinners
ferris_finale_Anim
ch1_02_closed
dt1_05_hc_remove
dt1_05_hc_remove_lod
FINBANK
hei_yacht_heist
hei_yacht_heist_enginrm
hei_yacht_heist_enginrm_lod
hei_yacht_heist_Lounge
hei_yacht_heist_lounge_lod
hei_yacht_heist_lod
hei_yacht_heist_slod
hei_yacht_heist_Bridge
hei_yacht_heist_bridge_lod
hei_yacht_heist_Bar
hei_yacht_heist_bar_lod
hei_yacht_heist_Bedrm
hei_yacht_heist_bedrm_lod
hei_yacht_heist_DistantLights
hei_yacht_heist_LODLights
hei_carrier
hei_carrier_DistantLights
hei_Carrier_int1
hei_Carrier_int2
hei_Carrier_int3
hei_Carrier_int4
hei_Carrier_int5
hei_Carrier_int6
hei_carrier_LODLights
bkr_bi_id1_23_door
lr_cs6_08_grave_closed
hei_sm_16_interior_v_bahama_milo_
RC12B_Default
canyonriver01
canyonriver01_lod
cs3_05_water_grp1
cs3_05_water_grp1_lod
trv1_trail_start
CanyonRvrShallow

**Comment by Phill030** [comment]
Does it also load the EntitySet for eg. the window at PDM?

**Comment by C0kkie** [comment]
it doesnt load entitysets for now
