### ISSUE TITLE
[bug/server-side] alt.RadiusBlip still doesn't work

### ISSUE THREAD

**Issue by savvin-dev** [altmp/altv-issues#1416]
9.8-rel, 10.0-dev7 actually, it still doesn't work
```js
const radiusBlip = new alt.RadiusBlip(0.0, 0.0, 72.0, 300.0);
radiusBlip.color = 37;

console.log(radiusBlip.valid); // true
```

_Originally posted by @savvin-dev in https://github.com/altmp/altv-issues/issues/1302#issuecomment-1078779483_

**Comment by YannBcf** [comment]
Yes, the issue you mentionned is still open so it's still not working
