### ISSUE TITLE
Alt:V Custom player discord status

### ISSUE THREAD

**Issue by Kaos1420** [altmp/altv-issues#1417]
### Description of the problem

My feature is not related to a problem but it would be a feature for Ruby+. It would be quite nice to customize the information displayed in Playing a Game section while you are actively playing Alt:V.

### Desired solution for the problem

Have a section that we can input a URL (or asset url) for an image that would replace the Alt:V image. 

Add the ability to have 2 togglable buttons below it, the top one would say Join and when players click it, it starts up alt:v and starts connecting to the server and the second one would be what the server developers wish to have it as (possibly a link to their forums?).

If possible, swap the alt:V Multiplayer text and the server name so instead of this:

**alt:V Multiplayer**
Your awesome alt:V server
Playing (XX of XXX)
XX:XX:XX elapsed

it would say:

**Your awesome alt:V server**
alt:V Multiplayer
Playing (XX of XXX)
XX:XX:XX elapsed

I say if possible because i know discord goes off of the client name.

**Comment by xxshady** [comment]
@Kaos1420 there is already an issue for this feature, use search for existing issues before create a new one

**Comment by YannBcf** [comment]
Duplicate of #398
