### ISSUE TITLE
Using setRearWheels on alt:V server side somehow desynces with getVehicleMod on client side (Motorcycles)

### ISSUE THREAD

**Issue by lackos888** [altmp/altv-issues#1419]
### Description of the problem

When you set a wheel with setRearWheels it will be synced to all players, but when using native getVehicleMod(veh, 24) it returns -1.

### Reproduction steps

1. Create a bike (for e.g zombieb)
2. Use /srun player.vehicle.setRearWheels(1)
3. /crun game.getVehicleMod(alt.Player.local.vehicle.scriptID, 24) => returns -1
4. Use /crun game.setVehicleMod(alt.Player.local.vehicle.scriptID, 24, 0, false);
5. /crun game.getVehicleMod(alt.Player.local.vehicle.scriptID, 24) => returns 0

### Expected behaviour

Native should be in sync.

### Operating system

Windows 10

### Version

release/9.3

**Comment by FabianTerhorst** [comment]
Rear wheel are internally in GTA not inside a modkit and are not a mod.

**Comment by lackos888** [comment]
@FabianTerhorst i looked at the GTA Online tuning decompiled script, it literally uses the same native

**Comment by lackos888** [comment]
but maybe only for preview then

**Comment by FabianTerhorst** [comment]
We dont use natives. So thats not comparable

**Comment by FabianTerhorst** [comment]
When we dont have Clientside Mod getters yet then we can add them.

**Comment by lackos888** [comment]
A getter would be good then
