### ISSUE TITLE
alt.PointBlip with .dimension visible in other dimensions

### ISSUE THREAD

**Issue by savvin-dev** [altmp/altv-issues#1421]
### Description of the problem

Player see Point Blips from 100..104 dimensions in 0 dimension

### Reproduction steps

```js
import * as alt from 'alt-server';

alt.on('resourceStart', (errored) => {
    if (errored)
        return;

    for (let i = 0; i < 5; i++) {
        const blip = new alt.PointBlip((50.0 * i), (50.0 * i), 72.0);
        blip.dimension = (100 + i);
        blip.color = (1 + i);
        blip.name = 'Blip #' + i;
    }
});

alt.on('playerConnect', (player) => {
    player.spawn(0.0, 0.0, 72.0, 0);
    player.model = 'MP_M_Freemode_01';
    player.dimension = alt.defaultDimension;
});
```

### Expected behaviour

Player shouldn't see PointBlip from another dimensions

### Additional context

![image](https://user-images.githubusercontent.com/34009919/160909779-5f8c8960-e503-46dd-8c81-be56f7c84825.png)

### Operating system

Windows 11 21H2, Debian 10.12

### Version

dev/10.0-dev7

**Comment by FabianTerhorst** [comment]
Blips dont have dimensions

**Comment by zziger** [comment]
> Blips dont have dimensions

Why does it implement worldobject then?

**Comment by zziger** [comment]
It would make sense if it would implement baseobject and had it's own position, or if the fact that it doesn't have dimension would be marked somehow idk 🤔

**Comment by FabianTerhorst** [comment]
Maybe we should check that then. So its ether a worldobject because it has a Position or Dimension is somehow not implemented.
