### ISSUE TITLE
Server crash while operating in js on player kicked from c#

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1422]
### Description of the problem

If you kick a player on c# side and then try to emit an event to that player on js side - it will crash the server.

### Reproduction steps

```js
alt.on('playerConnect', player => setTimeout(() => alt.emitClient(player, 'someEvent', 5), 1000));
```

```csharp
public class TestResource : Resource
{
    public override void OnStart()
    {
        Alt.OnPlayerConnect += OnPlayerConnect;
    }
    
    private void OnPlayerConnect(IPlayer player, string reason)
    {
        player.Kick("Why");
    }
    public override void OnStop()
    {
    }
}
```

will result in a server crash

### Expected behaviour

Exception that player was destroyed already (e.g. baseobject is invalid)

### Operating system

Windows

### Version

release 9.4

**Comment by deluvas1911** [comment]
JS throws a error that player or null is expected - issue seems to be fixed
tested on 14.0-rc3
