### ISSUE TITLE
Direct connect menu easy to close

### ISSUE THREAD

**Issue by litolax** [altmp/altv-issues#1423]
### Description of the problem

Direct connect menu is very sensetivity for selecting.

### Reproduction steps

• Open direct connect menu
• Write some text
• Select text and without releasing the mouse button move selection outside the menu.
• Release the mouse

### Expected behaviour

Direct connect menu shouldn't close after selection.

### Operating system

Windows

### Version

Release 9.6

**Comment by FabianTerhorst** [comment]
UI won't be changed until rework is done.
