### ISSUE TITLE
Simple Frontend Audio API

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1425]
### Description of the problem

Currently there is only two ways to play audio.

- Using the alt:V Voice API
- Using CEF and creating an audio handler with the `Audio` Web API

Each of these have their own benefits but are not fit to play a simple piece of Audio with very simple controls.

**CEF Issues**
You can actually run out of Audio instances.

_See here error below:_
```
http://127.0.0.1:3000/:0:Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27
```

**alt:V Voice API**

Currently it's not heavily in use, and it uses the server to play audio to multiple clients.

### Desired solution for the problem

A single API for playing client-side audio that is directly integrated into alt:V's client.

I believe a simple but also primitive API with the following restrictions could be put into place and be a very successful feature to add.

- No files greater than 256kb 
    - This is more than reasonable for short form audio
    - [See this image for example audio sizes](https://i.imgur.com/FUe6jqn.png)
- Limit the size of Audio files that can be played
- Only support `.ogg` format

```ts
const instance = alt.FrontendAudio.create('/assets/xyz.ogg'); // Create the instance

instance.play(); // Plays the instance once from zero.

instance.on('finish', () => {
    instance.destroy(); // Destroy the instance if it finishes
});
```

### Alternatives you considered

See above.

**Comment by YannBcf** [comment]
Did you consider the Audio API with the 2D arg set to true ? https://docs.altv.mp/js/api/alt-client.Audio.html#_altmp_altv_types_alt_client_Audio_constructor

Currently this API is broken but it might get fixed in the future, so I think you're asking for something already existing
