### ISSUE TITLE
RML element innerRML always returns empty string

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1427]
### Description of the problem

See repro steps

### Reproduction steps

```js
const document = new alt.RmlDocument("bug.rml");
const elem = document.createElement("div");
elem.innerRML = "bug";
alt.log("inner rml:", `[${elem.innerRML}]`) // empty string
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

dev/10.0-dev8

**Comment by LeonMrBonnie** [comment]
You need to wait for the next tick so the content in the element is updated accordingly. This is expected behaviour.

**Comment by xxshady** [comment]
@LeonMrBonnie can reproduce in next tick too

**Comment by LeonMrBonnie** [comment]
Then this is 99% a Rmlui bug
