### ISSUE TITLE
External console remains on the screen after disabling

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1431]
### Description of the problem

If the external console is enabled in `altv.cfg` before starting client, if you disable it with a `external_console 0` client command or in the main menu settings, console window will not close, but will turn into a "dumb" window which you can close and nothing happens

### Reproduction steps

See description 

### Expected behaviour

/

### Operating system

Windows 11

### Version

dev/10.0-dev12

**Comment by YannBcf** [comment]
@xxshady Cannot repro on dev/10.0-dev11

**Comment by xxshady** [comment]
I'll close this then, since my launch of the game kinda is different from a normal launch, so i guess that's the reason

**Comment by xxshady** [comment]
Turning on terminal legacy mode fixed problem

![use-legacy-mode](https://user-images.githubusercontent.com/54737754/162535448-64b8c81b-b0a1-4266-9921-93b0078c5f4e.jpg)
