### ISSUE TITLE
alt.isOnScreen

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1436]
### Description of the problem

Working with the `alt.worldToScreen` function has been really great but there's a small issue that this new reversed native doesn't fully address.

There's no way to tell if a position is currently on screen based on which way the camera is pointing. The current work around is to use `native.getScreenCoordFromWorldCoord` which returns a boolean determining if a position is on screen or not.

It pretty much makes `alt.worldToScreen` useless in the case of positional based drawing on screen because that boolean is necessary to properly draw stuff on screen.

### Desired solution for the problem

There's two solutions that come to mind.

**Solution 1:**

`alt.isOnScreen(x:  number, y: number, z: number);`

Which returns a result if the camera is currently pointing towards that position and is on screen.

**Solution 2:**

`alt.worldToScreen` will return `-1` values for x and y if the position is off screen.

I believe solution 1 will get more use and has more use cases.

### Alternatives you considered

Using a cool down for `native.getScreenCoordFromWorldCoord` and getting the onScreen boolean every `1s~` or so.

### Additional context

![](https://thumbs.gfycat.com/IndolentMealyAztecant-size_restricted.gif)

The image above demonstrates that the same ids are being drawn regardless of their actual position. Maybe it could be considered a bug.

**Comment by YannBcf** [comment]
You can alternatively use what Vektor posted.

```js
const isOnScreen = native.isSphereVisible(pos.x, pos.y, pos.z, 0.0099999998);
```

**Comment by C0kkie** [comment]
Added in next dev
