### ISSUE TITLE
JS module reserved commands are sent to users

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1440]
### Description of the problem

Console commands, such as `heap`, `timers` are reserved by js module, and `consoleCommand` event is sent to users anyway, even if command is already reserved in the module

![image](https://user-images.githubusercontent.com/54737754/163884610-ee72b1d4-ecda-4e25-943b-a53d99230023.png)

### Reproduction steps

/

### Expected behaviour

 reserved JS module commands should block the `consoleCommand` event, just like alt:V core console commands

### Operating system

Windows 11

### Version

10.0-dev12

### Scope

shared

**Comment by LeonMrBonnie** [comment]
Core issue

**Comment by LeonMrBonnie** [comment]
Fixed in next version
