### ISSUE TITLE
Voice: allow activityInputEnabled to be changed

### ISSUE THREAD

**Issue by R3DIANCE** [altmp/altv-issues#1441]
### Description of the problem

As now, **activityInputEnabled** is read only and can be set only trough the settings, but once you connect to a server you can't really change it.

There's some player can/want to stream music trough the microphone input but they have to hold the voice activation key for that.

### Desired solution for the problem

Allow to change it client side realtime.

### Version

release/9.9

**Comment by FabianTerhorst** [comment]
f1 settings menu wll be available ingame.
