### ISSUE TITLE
Undefined <IConnectionInfo>.discordUserID

### ISSUE THREAD

**Issue by vicelo23** [altmp/altv-issues#1446]
### Description of the problem

discordUserID property of IConnectionInfo is undefined in beforePlayerConnect

### Reproduction steps

```ts
import * as alt from "alt-server";

alt.on(
  "beforePlayerConnect",
  (connectionInfo: alt.IConnectionInfo): boolean | string | void => {
    if (!connectionInfo.discordUserID) return "Discord User ID is undefined.";
  }
);
```

### Operating system

Windows 11

### Version

release/9.9

**Comment by Phill030** [comment]
That happens if you start discord as admin, alt:V not as admin or discord started after alt:V

**Comment by vicelo23** [comment]
@Phill030 I didn't start Discord as admin.

**Comment by YannBcf** [comment]
Confirmed on 10.0-dev14

**Comment by deluvas1911** [comment]
Additional info: this seems to only be a issue with IConnectionInfo. If getting the discord id clientside by alt.Discord the correct id is returned

**Comment by LeonMrBonnie** [comment]
Uh. This might be because I forgot to add that property in JS module
And with might be I mean, it is because of that
