### ISSUE TITLE
playerStartedAnimation event / currentAnimation getter

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1447]
### Description of the problem

Currently it is not possible to query which animation a player is playing by using natives or other methods. Since some animations can be enhanced with objects or visual fx it would be great to have an way to get information about the used dictionary and animation name.

With the taskChange event the start of an animation can be recognized, but there is no information that allows you to find out which animation it is.

Since animations are already synced by alt:V I assume that alt:V is in knowledge of this information and could pass it on to the client (hopefully).

### Desired solution for the problem

Implement an event that signals the start of an animation as well as the dictionary and the name as parameters

### Alternatives you considered

If an event isn't suitable for this case, some sort of getter (e.g. alt.Player.currentAnimationName & alt.Player.currentAnimationDictionary) would be also fine

### Version

#10.0-dev14

**Comment by YannBcf** [comment]
I think an event is way better than a getter, both could be good but in any case the server developpers can extend / make a factory setting this getter via the event

**Comment by YannBcf** [comment]
Available in the upcoming update 11 dev build
