### ISSUE TITLE
'streamSyncedMetaChange' not called on player disconnect to invalidate data

### ISSUE THREAD

**Issue by hydrum** [altmp/altv-issues#1448]
### Description of the problem

When a player disconnected and has some streamSyncedMeta set to its entity, no `streamSyncedMetaChange` event is triggered with an updated value of `undefined`.

We spawn and attach objects to peds via the `streamSyncedMetaChange` event and its functionality. However, when a player has disconnected the related `streamSyncedMetaChange` does not trigger and we cannot clean up the objects. As a result the spawned objects fall to the ground or stay in the air.

### Reproduction steps

1. set some streamSyncedMetaData `await player.SetStreamSyncedMetaDataAsync("test", "value")` on the server
2. Have an event implemented on the client such as `alt.on('streamSyncedMetaChange', (entity, key, value, oldValue) => alt.log('metadata change:', entity.scriptID, key, value, oldValue));`
3. Connect to the server  (observation: `metadata change: 770 test value undefined`)
4. Let a second client connect to the server (observation: `metadata change: 0 test value undefined`)
5. Disconnect with the second client (observation: `-` no message)

### Expected behaviour

The event `streamSyncedMetaData` is called with the new value of `undefined` (similar behaviour as to how `await player.DeleteStreamSyncedMetaDataAsync("test")` works on the server)

### Operating system

Windows 10

### Version

release/9.6

**Comment by LeonMrBonnie** [comment]
Not a bug, but rather a feature request. Questionable if this is behaviour we want though.

**Comment by C0kkie** [comment]
why not just handle your cleanup in gameentitydestroyed event

**Comment by FabianTerhorst** [comment]
As already written. Its intended behavior.
