### ISSUE TITLE
GetResourceExports function segfaults

### ISSUE THREAD

**Issue by Marvisak** [altmp/altv-issues#1449]
### Description of the problem

When using `alt.getResourceExports()` function, the server segfaults, this happens with any module.

### Reproduction steps

Create resource and with any module call function GetResourceExports()
Here is a example with JS module
```js
const alt = require("alt-server")

alt.getResourceExports("js-test")
```

### Expected behaviour

The server should not segfault and the function should work as intended

### Additional context

After debugging a little bit I found out that this is probably caused by the MValue returned by the module sdk function being invalid, as it segfaults right after calling it's GetType method.

### Operating system

Arch Linux

### Version

dev/10.0-dev14

**Comment by LeonMrBonnie** [comment]
This issue was present on both sides, but is fixed in the next version.
