### ISSUE TITLE
Create a folder when installing altv

### ISSUE THREAD

**Issue by Stefanelll** [altmp/altv-issues#1450]
### Description of the problem

It's kinda annoying for someone to install the client app and throw all the files in the directory they selected.

### Desired solution for the problem

The batter way is to let people select the directory and then create a directory inside called "altv" or something where all the data it's gonna be installed.

### Alternatives you considered

Leave the app as it is.

### Version

latest, 26.04.2022

**Comment by Stefanelll** [comment]
yes, it is, but i meant that after you select the directory, inside him to create a folder "altv" where all resources to be installed.

_Like this:_

**C:\Desktop\Games (the path i sellect to install the altv | Games is a folder)**

_and the app to be installed like this:_

**C:\Desktop\Games\altv (altv it's a directory created by the application)**

**Comment by FabianTerhorst** [comment]
The next version of the launcher can install to appdata directory now.
