### ISSUE TITLE
[9.10] Client Crash when using Mod Clothing

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1451]
### Description of the problem

Several players reported that the client crash when using mod clothing on the female freemode ped.

### Reproduction steps

We have a one Mod Clothing Pack combined for female and male clothing (total of 3 ymt).
As soon as one of our female mod clothing is selected the client is crashing.

### Expected behaviour

Client shouldn't crash.

### Additional context

Before the update of 9.10 everything work like it should.

### Operating system

Windows 11

### Version

release/9.10

**Comment by FabianTerhorst** [comment]
Test with 9.12 again.

**Comment by Revyn112** [comment]
@FabianTerhorst bug is still persistent, log and dump is here: https://workupload.com/start/JANQDeRatYB

**Comment by FabianTerhorst** [comment]
Send the resources to a Dev in pm.

**Comment by lelorinel** [comment]
same problem with 9.12
It usually crashes when switching from normal clothes to modded ones.
like tops 151 to 152.

**Comment by C0kkie** [comment]
Maybe try dlc setter clothes
