### ISSUE TITLE
alt:V freeze on OAuth2 token request if in fullscreen mode

### ISSUE THREAD

**Issue by chaosfreak93** [altmp/altv-issues#1455]
### Description of the problem

When Discord OAuth2 token get requested and GTA/alt:V is in full screen mode, alt:V freezes as soon as you switch back to the window. Window mode works without problems.

### Reproduction steps

- Open alt:V in Fullscreen Mode.
- Execute following code snippet somewhere on clientside:
`let test = await alt.Discord.requestOAuth2Token('appId');
alt.log(test);`

### Expected behaviour

alt:V shouldn't freeze

### Operating system

Windows 11

### Version

dev/10.0-dev19

**Comment by C0kkie** [comment]
Fixed in upcoming dev
