### ISSUE TITLE
Unhooking a vehicle from a tow truck doesn't change the netowner

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1457]
### Description of the problem

See repro steps (this shit doesn't happen in all cases for me)

### Reproduction steps

Unhook attached car from a towtruck in car accident https://youtu.be/gVSyJ-clDBE
Remarks:
- "owned" means player is net owner of this vehicle
- Timecode 0:03 shows a half-second change of the cheburek netowner

### Expected behaviour

Normal return of the netowner to the car driver

### Operating system

Windows 11

### Version

dev/10.0-dev20

**Comment by YannBcf** [comment]
Confirmed on release/9.13

Easy reproduction steps:

tow a vehicle then the towtruck driver calls
```ts
alt.setRotationVelocity(alt.Player.local.vehicle.scriptID, 0, 0, 10);
```

This issue seems random tho, it sometimes take up to 5 tries

**Comment by martonp96** [comment]
Issue couldn't be reproduced anymore. Gets closed until proven otherwise.
