### ISSUE TITLE
Environment variable support for configuration

### ISSUE THREAD

**Issue by vicelo23** [altmp/altv-issues#1458]
### Description of the problem

We have to use a shell script to transpile envrionment variables into server.cfg file to use inside Docker container, it can be improved.

### Desired solution for the problem

Adding environment variable support to config reader will make things more simple.

### Additional context

An example shell script to transpile environment variables into server.cfg.
https://github.com/eisengrind/docker-altv-server/blob/master/.docker/scripts/entrypoint.sh

**Comment by FabianTerhorst** [comment]
Im against environment variables. I think config files are easier to understand and maintaining both doesn't really makes sense.
