### ISSUE TITLE
IVehicle.SetMod broken with some vehicles

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#1460]
### Description of the problem

Using the C# method IVehicle.SetMod() and IVehicle.SetModExt() on some vehicles leads to wrong mods applied.
It seems to work well with recent DLC vehicles (club, dominator7, gt1 ...) but it seems to not work well with base game vehicles and old DLC before January 2016 update (premier, bullet, cheetah, tampa ...) but I'm not 100% sure and not tested all vehicles.

For example on the cheetah changing the ECM mod (11) changes the suspension. On the premier changing the transmission change the suspension.

It used to work well on every vehicle but not since some time, perhaps linked to lastest GTA update?

### Reproduction steps

Create a premier and apply a spoiler:

Server:

```
IVehicle vehicle = Alt.CreateVehicle(VehicleModel.Premier, player.Position + new Position(2, 2, 0), Rotation.Zero);
vehicle.ModKit = 1;
vehicle.SetMod(0, 1);
```

Client:
```
game.setVehicleModKit(vehicle, 0);
game.setVehicleMod(vehicle, 0, 0, false);
```

This gives a premier with rear spoiler on the client-side version but no spoiler on server-side code.
Using the same code on a club works.

### Expected behaviour

Same mods should be applied on vehicles using the server API or client natives. (Knowing that there is a +1 difference in mod index server-side compared to client-side).

### Operating system

Windows 10 21H2

### Version

stable/9.13 with vehmods.bin up to date

**Comment by ThomasMarangoni** [comment]
Maybe #1280 is related to that?

**Comment by LeShred** [comment]
It seems to work well with v10.1

**Comment by C0kkie** [comment]
Yes got fixed with the bin update
