### ISSUE TITLE
alt.ConfigFlag.DisableIdleCamera first person view in vehicle will not work

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1461]
### Description of the problem

If `alt.setConfigFlag(alt.ConfigFlag.DisableIdleCamera, true)` is set in js client, then the first person view in the vehicle will not work.

### Reproduction steps

Use `alt.setConfigFlag(alt.ConfigFlag.DisableIdleCamera, true)` 

### Expected behaviour

first person view in the vehicle worked

### Operating system

Linux/Windows

### Version

10.0-rc1 (rc)

**Comment by xxshady** [comment]
I also noticed this behaviour

**Comment by deluvas1911** [comment]
Confirmed on current dev

**Comment by C0kkie** [comment]
Fixed in next dev/rc

**Comment by Doxoh** [comment]
it works in rc, thanks
