### ISSUE TITLE
player.setFaceFeature() problems - Serverside JavaScript

### ISSUE THREAD

**Issue by PrisonIndustry** [altmp/altv-issues#1463]
### Description of the problem

So here's the thing, in the documentation it says that I can change the neck with the index id 19 which stands for the neck. If I now want to change something, I get this error: https://prnt.sc/DSHBNkBEvpeJ and my nose becomes wide or thin. Is this normal or do I have to change something

### Reproduction steps

player.setFaceFeature(19, anyvalue) -- Serverside 

### Expected behaviour

That I can make the neck wider or thinner 

### Operating system

Windows Server 216 / JavaScript

### Version

alt:V Server 9.8 (release)

**Comment by C0kkie** [comment]
Its the same like the native https://github.com/altmp/altv-issues/issues/593 so its a duplicate
