### ISSUE TITLE
setHairColor - js Serverside

### ISSUE THREAD

**Issue by PrisonIndustry** [altmp/altv-issues#1464]
### Description of the problem

when i want to change the hair color nothing changes, the same is with the 2 hair color. everything was done serverside with player.setHairColor()

### Reproduction steps

player.setHairColor(4) not working it is on all hair colors

### Expected behaviour

pls fix that for using this serverside 

### Operating system

Windows Server 216 / JavaScript

### Version

alt:V Server 9.8 (release)

**Comment by C0kkie** [comment]
Did you set headblenddata first? Haircolor setter is working

**Comment by PrisonIndustry** [comment]
yeah this is clientside is this false?

**Comment by C0kkie** [comment]
you have to set it serverside if you use haircolorsetter serverside
