### ISSUE TITLE
globalMetaChange event not fired on alt.setMeta call

### ISSUE THREAD

**Issue by YannBcf** [altmp/altv-issues#1465]
### Reproduction steps

serverside
```ts
alt.on("playerConnect", (player: alt.Player) => {
  alt.setMeta("globalMeta", false);

  setTimeout(() => alt.setMeta("globalMeta", true), 5000);
});
```

clientside
```ts
alt.on("globalMetaChange", (key: string, value: any, oldValue: any) => {
    console.log("globalMetaChange", key, value, oldValue);
});
```

### Operating system

Windows 10

### Version

dev/10.0-dev21

**Comment by xxshady** [comment]
@YannBcf @LeonMrBonnie isnt global meta means alt **local** global meta? we also have alt global **synced** meta (alt.setSyncedMeta, alt.getSyncedMeta)

**Comment by LeonMrBonnie** [comment]
> @YannBcf @LeonMrBonnie isnt global meta means alt **local** global meta? we also have alt global **synced** meta (alt.setSyncedMeta, alt.getSyncedMeta)

`globalMetaChange` is for `alt.setMeta` serverside.

**Comment by xxshady** [comment]
but isnt `alt.setMeta` only shared between resources on one side, e.g. server and not client?

**Comment by xxshady** [comment]
![image](https://user-images.githubusercontent.com/54737754/167315570-a3b06204-33c9-4be2-aec7-d41256e890d3.png)

**Comment by LeonMrBonnie** [comment]
Ah right, I thought about `alt.setSyncedMeta`

**Comment by YannBcf** [comment]
Just tested you're right, my bad
