### ISSUE TITLE
Vehicle .pos bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1467]
### Description of the problem

If I want to change, for example, the value of the z coordinate of my vehicle by +1, the vehicle will not move.

### Reproduction steps

player.vehicle.pos = new alt.Vector3(player.vehicle.pos.x, player.vehicle.pos.y, player.vehicle.pos.z+1);

### Expected behaviour

 If I want to set the z coordinate by 1 value, then modify it and do not leave the vehicle on the ground.

### Operating system

Windows 11

### Version

alt:V build #9.13, branch release

**Comment by deluvas1911** [comment]
Confirmed on dev/10.0-dev21

Additional info: the vehicle goes up as soon as z gets increased by 3.8 or more

**Comment by Lekenthu** [comment]
> Confirmed on dev/10.0-dev21
> 
> Additional info: the vehicle goes up as soon as z gets increased by 3.8 or more

Yes, I noticed that too.

**Comment by FabianTerhorst** [comment]
Works in v15.
