### ISSUE TITLE
Vehicle .engineHealth bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1468]
### Description of the problem

If I repair a vehicle with a .repair() property and then crash physically, and I want to manually set engineHealth to e.g. 500, the entire vehicle will be fixed. Vektor saw my problem in live, no matter how many times, it is reproducible always.

### Reproduction steps

1. Create vehicle.
2. Smash the vehicle.
3. Use .repair() property.
4. Smash the vehicle again.
5. Use player.vehicle.engineHealth = 500

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #9.13, branch release

**Comment by YannBcf** [comment]
#1184 duplicate
