### ISSUE TITLE
cef input element doesn't trigger focus / blur events

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#1469]
### Description of the problem

Listeners that registered with `addEventListener` don't trigger.

### Reproduction steps

- add element `<input type="text" />`
- register focus listener with `document.querySelector("input").addEventListener("focus", () => console.log("focus triggered"))`
- register blur listener with `document.querySelector("input").addEventListener("blur", () => console.log("blur triggered"))`
- try to focus input with cursor in game
- remove focus by clicking outside of input

### Expected behaviour

- output in console `focus triggered`
- output in console `blur triggered`

### Additional context

It trigger focus/blur events when CEF DevTools (`localhost:9222`) is opened and input focused there

### Operating system

Ubuntu 20.04

### Version

release

**Comment by zziger** [comment]
If you select text in an input, is the selection blue or gray? Do you use data: urls at any point?

**Comment by nrzull** [comment]
@zziger selection is gray. Nope, I don't use any `data:` urls

**Comment by Hardy535** [comment]
Might be related to https://github.com/altmp/altv-issues/issues/1119

**Comment by C0kkie** [comment]
@Hardy535 @nrzull  can you test on newest dev build?

**Comment by nrzull** [comment]
@nrzull sorry mate, I'm on linux rn, don't have ability to test it(

**Comment by C0kkie** [comment]
Its fixed in current rc. If you still have problems reopen the issue
