### ISSUE TITLE
Discord OAuth. Failed to get OAuth2 token second time

### ISSUE THREAD

**Issue by JustCup** [altmp/altv-issues#1471]
### Description of the problem

When I re-obtained the token via `requestOAuth2Token()` I get the error
```
[Error] Error: Failed to get OAuth2 token
```
I tried both with reconnect and simply by calling the method a second time.

### Reproduction steps

- Get a token for the first time
- Deauthorise app in discord
- Try to get the token a second time

### Expected behaviour

Same as the first login attempt

### Operating system

Windows 11

### Version

dev/10.0-dev21

**Comment by vicelo23** [comment]
I can confirm this problem, I don't know if it is a problem with Discord itself because it happens if you Deauthorize your application.

**Comment by deluvas1911** [comment]
Confirmed when using reconnect.
If alt:V get's restarted the Discord popup to authorize the app will be shown again

**Comment by deluvas1911** [comment]
Will be fixed with the next update

**Comment by b2soft** [comment]
Not fixed in 11.0-dev24, please reopen @deluvas1911

**Comment by Firjens** [comment]
This issue still occurs with the exact same repro steps.

**Comment by NeekoDev** [comment]
Hi, got the same problem on C# (latest nuget package version), server version 16.0.125 (release) and client 16.0.139
