### ISSUE TITLE
Native taskRappelDownWall - types check error

### ISSUE THREAD

**Issue by R4ndomizeR** [altmp/altv-issues#1476]
### Description of the problem

```js
taskRappelDownWall(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): void;
```

I get an error on p9. There must be a string (clipSet). But type checking returns an error:
```
Native argument at index 9 (string) could not be parsed to type int (taskRappelDownWall)
```

### Reproduction steps

```js
const coords = new alt.Vector3(258.68, -3311.5, 45.72)

native.ropeLoadTextures()

const [ropeID, _] = native.addRope(coords.x, coords.y, coords.z, -90, 90, -90, 78, 7, 78, 78, 1.2, false, false, true, 10, false, 0)

native.setEntityCoordsNoOffset(localPlayer.scriptID, coords.x, coords.y, coords.z - 10, false, false, false)

native.taskRappelDownWall(
  localPlayer.scriptID,
  coords.x,
  coords.y,
  coords.z,
  coords.x,
  coords.y,
  coords.z,
  -130.0,
  ropeID,
  'anim_heist@hs3f@ig1_rappel@male@', // type check error: expected int
  1
)
```

### Expected behaviour

Specified in type-natives:
```js
taskRappelDownWall(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): void;
```
Supposed:
```js
taskRappelDownWall(ped: Player | number, x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, minZ: number, ropeId: number, clipSet: string, p10: number): void;
```

### Operating system

Windows 10

### Version

release/9.1

**Comment by deluvas1911** [comment]
The alt:V natives get created by using all0c8ors nativedbas source.
As the native there has the wrong argument types, it will also affect the generated alt:V natives.

Feel free to create an pr on the [nativedb repository](https://github.com/alloc8or/gta5-nativedb-data) to get that fix included when natives are generated next time

**Comment by R4ndomizeR** [comment]
Thanks. That repository uses C++ types?

**Comment by tastydev** [comment]
> Thanks. That repository uses C++ types?

I have already done it for you.

alt::Core parses `Any` type as int32 so the js client module checks if argument with index 9 is an integer which obviously fails.

As mentioned before you have to wait for the natives db update cause i think we won't disable this "check" inside the native invoker inside the js client module.

**Comment by deluvas1911** [comment]
I'm going to close the issue then as it's related to a nativedb entry and not to alt:V itself
