### ISSUE TITLE
Weapon Data API

### ISSUE THREAD

**Issue by nordpoldieb** [altmp/altv-issues#1477]
### Description of the problem

Add an Clientside-API for the weapon data like it was introduced for the vehicle handling. It would be especially useful for an anticheat to check values like the spread of the weapon etc.

### Desired solution for the problem

While doing some research I found the following repository which contains some interesting offsets for the pointer adresses.

https://github.com/Yimura/GTAV-Classes/blob/master/CWeaponInfo.hpp

**Comment by YannBcf** [comment]
4 clientside getters have been added -> https://github.com/altmp/cpp-sdk/commit/d53a548afd1492e9596356747126d1deeddbde30

Available in the upcoming dev update 11 dev build
