### ISSUE TITLE
Early-Auth not working after second fresh start

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1479]
### Description of the problem

Early Auth login website is not displayed when connecting for the second time

### Reproduction steps

When you connect to the server for the first time, the early auth login website is loaded and you can log in.

After successful login, you join the server. If you quit the game, restart and try to connect, no web view is loaded and you remain on the Joining Server screen.

If you quit the game, clear the cache folder in the cef folder and then connect to the server, it works fine again.

### Expected behaviour

Early Auth login website is displayed

### Operating system

Client v10.0

### Version

v10.0

**Comment by yuAwi** [comment]
Additional Information:
It's related to store some data in local storage
There is no kind of log which would be called on login page load

**Comment by deluvas1911** [comment]
Confirmed that deleting cef cache folder fixes this issue

**Comment by C0kkie** [comment]
Should be fixed in next release
