### ISSUE TITLE
Master server using default interface even if bound to different ip

### ISSUE THREAD

**Issue by Mozorianer** [altmp/altv-issues#1480]
### Description of the problem

If you run the altv-server binary on a server with multiple interfaces and bind it to a secondary interface, the master server still connects using the default server interface resulting in a "Master server connect failed." loop.

### Reproduction steps

Get a linux server with 2 ip addresses and bind the server to the second ip

### Expected behaviour

Use the bound interface/ip for master server connection instead of the default one

### Operating system

Ubuntu 20.04

### Version

release/10.1

**Comment by Mozorianer** [comment]
![Screenshot 2022-05-21 135420](https://user-images.githubusercontent.com/17972071/169650484-5db7ae9b-7689-466d-8525-04b014cc0808.png)

altv-server bound to xxx.xxx.4.55
on tcpdump its still using my primary interface xxx.xxx.4.14

**Comment by LeonMrBonnie** [comment]
Fixed in dev
