### ISSUE TITLE
alt.ConfigFlag.DisableIdleCamera cinema camera in vehicle will not work

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1482]
### Description of the problem

If alt.setConfigFlag(alt.ConfigFlag.DisableIdleCamera, true) is set in js client, then the cinema camera in the vehicle will not work.

### Reproduction steps

Use alt.setConfigFlag(alt.ConfigFlag.DisableIdleCamera, true)

### Expected behaviour

cinema camera in the vehicle worked

### Operating system

Linux/Windows

### Version

10.3

**Comment by xxshady** [comment]
by cinema camera do you mean camera that is turned on by `R` key (by default)?

**Comment by yuAwi** [comment]
> by cinema camera do you mean camera that is turned on by `R` key (by default)?

Yes

**Comment by deluvas1911** [comment]
Confirmed

**Comment by Doxoh** [comment]
Fixed with 11.0-rc9 - thanks! @C0kkie i have created a changelog pull request for this: https://github.com/altmp/altv-docs/pull/132

**Comment by C0kkie** [comment]
? This was fixed with 10.0 already and the thing with the "R" key will be fixed in 11.0 until release

**Comment by C0kkie** [comment]
With v10 it works, pretty sure. Anyway v11 will fix everything

**Comment by Doxoh** [comment]
please feel free to test it with these ressources, and you can see that you are not right
[disabelIdeCameraCinemaBugv11.zip](https://github.com/altmp/altv-issues/files/9062125/disabelIdeCameraCinemaBugv11.zip)
[disabelIdeCameraCinemaBugv10.zip](https://github.com/altmp/altv-issues/files/9062128/disabelIdeCameraCinemaBugv10.zip)

disabelIdeCameraCinemaBugv11.zip -> working
disabelIdeCameraCinemaBugv10.zip -> not working

**Comment by C0kkie** [comment]
i dont know i use it on our productionsystem and qa also tested it, but anyway as i said, the "R" key thing will get fixed until release

**Comment by C0kkie** [comment]
Fixed in rc/11.0-rc13
