### ISSUE TITLE
Permission System - No Dialog when no permission is *required*

### ISSUE THREAD

**Issue by Quantum2707** [altmp/altv-issues#1483]
### Description of the problem

So when a resource has the configuration variable "optional-permissions" set in the resource.cfg but on no other neither the same resource asks for required permissions there will no permission popup appear on join.
So as long as there is less than 1 required permission you can not agree with optional permissions. E.g. to copy the clipboard which maybe only team members need you need to require it since you can't agree with only optional permissions. The popup won't appear.

### Reproduction steps

Create a resource.
define optional-permissions array with different entries.
Join the Server
See no popup appears.
Add a required permission.
Join again.
See a popup appears including required *and* optional permissions,

### Expected behaviour

Even if there is only optional permissions set in the resource.cfg files it should ask for agreement to provide the possibility to use optional functionality.

### Operating system

Windows 10

### Version

10.1.x

**Comment by deluvas1911** [comment]
Confirmed with the given reproduction steps.
As long as there's no required permission the popup won't appear

**Comment by FabianTerhorst** [comment]
Fixed in next version.
