### ISSUE TITLE
Additional setters and getters for Weapon Data API

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1487]
### Description of the problem

```
// Recoil setter and getter
RecoilShakeAmplitude (***)
RecoilAccuracyMax (***)
RecoilAccuracyToAllowHeadShotPlayer (***)
RecoilRecoveryRate

// Reload setter and getter
AnimReloadRate (***)
VehicleReloadTime

// Range setter and getter
LockOnRange (***)

```
***: Very important setter and getter

### Additional context

https://gtamods.com/wiki/Weapons.meta
https://gtaforums.com/topic/681401-weapons-information-by-game-files/
https://forums.gta5-mods.com/topic/36832/tutorial-basic-editing-of-weapons-meta

**Comment by LeonMrBonnie** [comment]
> RecoilShakeAmplitude (***)
Already exists: `alt.Player.local.currentWeaponRecoil`

**Comment by mrgharabaghi** [comment]
> Already exists: alt.Player.local.currentWeaponRecoil

It's better to rename the `currentWeaponRecoil` to `currentWeaponRecoilShakeAmplitude`.

**Comment by C0kkie** [comment]
Added in upcoming dev
