### ISSUE TITLE
Peds and set player into air vehicle crash

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1488]
### Description of the problem

Game crashes if you spawn more than 110 peds and put your player into any air vehicle, like hydra or maverick

### Reproduction steps

1. run the following code:
```js
const { pos, model } = alt.Player.local

for (let i = 0; i < 110; ++i) {
  const coords = {
    x: pos.x + (Math.random() * 5.0),
    y: pos.y + (Math.random() * 5.0),
    z: pos.z,
  }

  const ped = native.createPed(
    0,
    model,
    coords.x,
    coords.y,
    coords.z,
    0,
    false, false,
  )
  native.freezeEntityPosition(ped, true) // without this line my game may crash 

  alt.log("created ped:", i)
  await alt.Utils.wait(0)
}
```
2. spawn air vehicle, like hydra
3. set your player into spawned vehicle with `player.setIntoVehicle` or `native.setPedIntoVehicle`

### Expected behaviour

/

### Operating system

Windows 11

### Version

release/10.5

**Comment by LeonMrBonnie** [comment]
Too many physics calculations cause the game to crash, same thing happens with objects etc. too

**Comment by xxshady** [comment]
ah, no

**Comment by xxshady** [comment]
the cause of this crash is `player.setIntoVehicle`

**Comment by xxshady** [comment]
upd: `native.setPedIntoVehicle` crashes too

**Comment by deluvas1911** [comment]
Can confirm it sometimes crashing on 110, but always between 110 - 120
Maybe dependend on the location where the peds are spawned (e.g. like having more or less physic calculations in that area as leon said?)

**Comment by xxshady** [comment]
@deluvas1911 if this depends on physic calculations why doesn't putting a player in a car cause a crash?

**Comment by FabianTerhorst** [comment]
Shouldn't always type 2 be used for createPed?

**Comment by xxshady** [comment]
> Shouldn't always type 2 be used for createPed?

no, xd https://discord.com/channels/371265202378899476/557307592129511444/978377544296435742

![IMG_20220624_191202.jpg](https://user-images.githubusercontent.com/54737754/175575228-efed0a14-8871-427a-823b-a4eb9bfbac59.jpg)

**Comment by FabianTerhorst** [comment]
Have you tried delaying ped spawns? Like only one ped every second.

**Comment by xxshady** [comment]
Fixed since some gta or alt:V update
