### ISSUE TITLE
RmlUI crush game

### ISSUE THREAD

**Issue by slynx-01** [altmp/altv-issues#1490]
### Description of the problem

1. Using bundlers that pack code into `eval`, then calling `new RmlDocument()` causes a crash without displaying logs or crashdump files
2. Updating `transform` in `css` on `RmlDocument` every tick after sometime causes crash without displaying logs and crashdump files

### Reproduction steps

```ts
document.setProperty('transform', translate(${x}%, ${y}%) scale(${scale}))
```

### Expected behaviour

Correct render or get details of reason crash

### Operating system

Windows 10 21H1 19043.1645

### Version

10.5

**Comment by mehrangta** [comment]
rml transform doesn't work as intended tho

**Comment by martonp96** [comment]
Inlcude full minimal reproduction resource in the issue.
