### ISSUE TITLE
--justpack tries to pack serverside only ressource / skips them, but keeps dependency

### ISSUE THREAD

**Issue by riffy** [altmp/altv-issues#1491]
### Description of the problem

When packing the resources with `--justpack` option, the program will try to pack resources that have no client-main or client-files, without finishing them (log-wise). Additionally, if this resource, that is serverside only, is a dependency for another resource, connecting players will not have the main-resource started, because the dependency is not downloaded (missing) on the cdn.

Therefore it is not contained in the `cdn_upload` directory.

![log](https://user-images.githubusercontent.com/13089522/170026925-69d9aa45-ac2d-444b-a44b-4b489b8cd423.PNG)

### Reproduction steps

1. Create a ressource with a main file
2. Add ressource to `server.cfg`
3. run altv-server with `--justpack`

[server_only_empty_ressource.zip](https://github.com/altmp/altv-issues/files/8762320/server_only_empty_ressource.zip)

### Expected behaviour

`--justpack` will not pack any ressource (or even try), where no `client-files` and `client-main` is provided in the `resource.cfg`.

### Additional context

Maybe this is just a huge edge case, i resolved this issue by simply adding an empty 'index.js' and marking it as client (adding to `resource.cfg`:

```
client-main: index.js,
client-files: []
```

### Operating system

Debian 11, Windows 10

### Version

10.5-release

**Comment by xxshady** [comment]
![изображение](https://user-images.githubusercontent.com/54737754/205501486-4d116c2b-e36e-46ec-95ee-3bd176d1f964.png)

ready-to-test repository: https://github.com/xxshady/altv-serverside-only-resource-bug
just run `yarn start` in the root of repo to test it

**Comment by xxshady** [comment]
Confirmed on 13.0-dev63

**Comment by martonp96** [comment]
Was fixed in 15.0.

**Comment by xxshady** [comment]
Packing of serverside resource is fixed, but if you add server-only resource to deps of clientside resource you will still get the [error](https://github.com/altmp/altv-issues/issues/1491#issuecomment-1336450712) and this is considered expected behavior
