### ISSUE TITLE
Cache the master list locally on the client

### ISSUE THREAD

**Issue by KoronGIT** [altmp/altv-issues#1493]
### Description of the problem

If the master server cannot be reached, you can only connect via direct connect. To do this, the user must know the IP+Port of the server.

### Desired solution for the problem

As soon as the client retrieves the master list, save it locally. As soon as the client cannot retrieve the master list because the master server list cannot be reached, display this cached version with a corresponding notice.

**Comment by Doxoh** [comment]
Additionally it is so that if one has connected so far by master list, and now by direct connect, all resources are downloaded again completely.

It would be good if the cache of the resources for the masterlist and the direct connect is the same.

**Comment by FabianTerhorst** [comment]
This is not something that should happen. I don't think caching makes sense.

**Comment by KoronGIT** [comment]
Can you please read the actual feature request and not the unrelated comment?

**Comment by KoronGIT** [comment]
> This is not something that should happen. I don't think caching makes sense.

Can you please read the actual feature request and not the unrelated comment?
