### ISSUE TITLE
Abort button is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1494]
### Description of the problem

if try to abort downloading resources, nothing happens and the game may freeze later

also this displayed in the client console after click on abort button:

![изображение](https://user-images.githubusercontent.com/54737754/170470425-0761968e-a482-44f1-b8c6-2e056f35ed7d.png)

### Reproduction steps

/

### Expected behaviour

/

### Operating system

Windows 11

### Version

release/10.5

**Comment by xxshady** [comment]
tested this with corrosive.eu server in the masterlist

**Comment by deluvas1911** [comment]
Confirmed (release + dev)

**Comment by C0kkie** [comment]
Should be fixed
