### ISSUE TITLE
[C#] Two different IPlayer instances can be equal

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#1497]
### Description of the problem

When a player connects he gets a IPlayer instance with a particular Id.
When he disconnects and reconnects back later he gets another IPlayer instance with different Id but the two IPlayer instance are equal.
It seems that the Equal() is not based on content of the IPlayer instance but on something else because the behavior isn't 100% consistant.

### Reproduction steps

Create and in Alt.OnPlayerConnect event that add the IPlayer instance to an HashSet<IPlayer> and display an error if the add returned false:
```
    public static class LoginManager
    {
        private static HashSet<IPlayer> _players = new();

        public static void Init()
        {
            Alt.OnPlayerConnect += (IPlayer client, string reason) =>
            {
                Alt.Log($"Client {client.Id} Connected");
                if (!_players.Add(client))
                    Alt.Log("IPlayer already in HashSet");
            };
        }
    }
```

Result:
```
[20:10:19] Client 164 Connected
[20:10:34] Client 165 Connected
[20:10:52] Client 166 Connected
[20:10:52] IPlayer already in HashSet
```
Here it takes me 2 reconnects to have equal IPlayer instances but sometimes it can take morre or less attempts.

### Expected behaviour

Different IPlayer instances with different Id should not be equal.

### Operating system

Windows 10 21H2

### Version

release/10.8

**Comment by LeonMrBonnie** [comment]
This issue is not a problem with the alt:V core, please open an issue in the C# module repo for this
