### ISSUE TITLE
Debug argument for client launch options

### ISSUE THREAD

**Issue by MusaSSH** [altmp/altv-issues#1500]
### Description of the problem

Developers might be playing in production servers and they will need to change debug line in altv.cfg each time they want to switch between modes.

### Desired solution for the problem

A `--debug` command line argument will make switching between modes easier for us. We can either just execute `altv.exe --debug` or we can create another shortcut for running altv.exe with --debug argument.

**Comment by C0kkie** [comment]
Added in launcher rework
