### ISSUE TITLE
Wildcard for resources

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1504]
### Description of the problem

Add Wildcard feature for resources in `server.cfg`.

### Desired solution for the problem

```yaml
resources: [
    folder1/*
    folder2/folder3/*
    folder4/folder5/folder6/*
    script1
    folder7/script2
]
```

**Comment by Phill030** [comment]
Looks like a duplicate of #1485

**Comment by C0kkie** [comment]
Clientfiles and ressource config is different

**Comment by C0kkie** [comment]
Possible in v15
