### ISSUE TITLE
Add rmlControlsEnabled getter

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1506]
### Description of the problem

You can use alt.toggleRmlControls(state) to enable/disable it, but there is no getter for the current state

### Desired solution for the problem

Add an alt.rmkControlsEnabled getter to have same options as alt.showCursor (alt.isCursorVisible) & alt.toggleGameControls (gameControlsEnabled)

### Alternatives you considered

/

### Additional context

/

### Version

dev/11.0-dev15

**Comment by C0kkie** [comment]
Added in next dev
