### ISSUE TITLE
Persistant localStorage or something similar available in EarlyAuth

### ISSUE THREAD

**Issue by Timo972** [altmp/altv-issues#1508]
### Description of the problem

I am looking for a way to implement a remember me functionality inside EarlyAuth, but it's not possible to save any session information using the localStorage, IndexedDB or Cookies. They are cleared on every start / stop.

### Desired solution for the problem

Make localStorage persistant or give WebViews access to alt.LocalStorage

### Alternatives you considered

n/a

### Additional context

n/a

### Version

11.0-dev5

**Comment by FabianTerhorst** [comment]
I checked the possibility of implementing this and it won't be implemented anytime soon.

**Comment by FabianTerhorst** [comment]
Added in next version.
