### ISSUE TITLE
Alt:V Vehicle Customizations?

### ISSUE THREAD

**Issue by QuantumZx20** [altmp/altv-issues#1510]
### Description of the problem

Hello. We are running an Alt:V based server and we see that players are faced with different options when they access the vehicle modding menu. For example, when we want to change the Front Bumper, another part of the vehicle changes, for example the Spoiler. This issue occurred after Alt:V updates and it increased after each update. We thought the issue was based on Alt:V and wanted to report it.

### Reproduction steps

- Firstly create a vehicle, for example Asea.
- Go for Custom Menu.
- Change car parts and check if they're changing correct parts or not.

### Expected behaviour

N/A

### Additional context

N/A

### Operating system

Windows

### Version

Release

**Comment by FabianTerhorst** [comment]
Make Sure to download latest vehicle bin's. They got updated multiple times.

**Comment by QuantumZx20** [comment]
Fixed
