### ISSUE TITLE
Change the position of "alt:V Multiplayer"

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1512]
### Description of the problem

"**alt:V Multiplayer**" and "**Initializing Social Club**" are on the top of each other on the loading screen.

### Desired solution for the problem

The best position is "**Top Right**".

### Additional context

![logo](https://user-images.githubusercontent.com/40915667/173224292-a83cfb1f-81dd-49f6-a2dc-d1c3e5ed7da2.jpg)

**Comment by martonp96** [comment]
The loading screen will be changed in the future, we will not change the current alt:V label for now.
