### ISSUE TITLE
ColShape continues calculations after removal

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#1513]
### Description of the problem

The ColShape continues calculating entities that are inside it after its removed until calculation of all colshapes is complete.

**Comment by mrgharabaghi** [comment]
Colshape continues calculations even if no one in the server.
```js
const points = [
    new alt.Vector2(410.0031, -946.0042),
    new alt.Vector2(397.5432, -945.8661),
    new alt.Vector2(402.5566, -957.7299)
];

for (let i = 0; i < 20000; i++) {
    let col = new alt.ColshapePolygon(25, 35, points);
}
```

**Comment by FabianTerhorst** [comment]
> Colshape continues calculations even if no one in the server.
> 
> ```js
> const points = [
>     new alt.Vector2(410.0031, -946.0042),
>     new alt.Vector2(397.5432, -945.8661),
>     new alt.Vector2(402.5566, -957.7299)
> ];
> 
> for (let i = 0; i < 20000; i++) {
>     let col = new alt.ColshapePolygon(25, 35, points);
> }
> ```

Thats unrelated to the issue. The issue is about that the colshapes thinks a entity exists that is already removed.

**Comment by C0kkie** [comment]
Fixed in dev
