### ISSUE TITLE
--justpack with c# module

### ISSUE THREAD

**Issue by cuBeUrg** [altmp/altv-issues#1514]
### Description of the problem

I have 1 resource in the resources folder. It contains the client-sided script (which is in JS) and the server-sided script which is written in C#. When I open the server without `--justpack` it launches the server just fine in under 10 seconds.

When I use the --justpack option, the server won't start. It just gets stuck at:
`[csharp-module] Checking dependencies... this might take a few minutes...`

I waited like 45 minutes, with an almost empty C# resource, and I had to close it, since nothing was happening.

I got told to disable the C# module, and just pack the client-side files, and of course that works, but however, it is still strange that when using `--justpack` the server doesn't start corectly. 

What I want to do, is make a script on the server-side that will automatically upload the files on the CDN for me, after they are packed, but however, that's kinda impossible at the moment, since the server just doesn't start.

### Reproduction steps

Create a resource with the client-side in JS and server-side in C#, and use `--host 127.0.0.1 --port 7788 --justpack` or just `--justpack` and start the resource.

### Expected behaviour

The server should not get stuck on checking dependencies.

### Operating system

Windows

### Version

10.10 (release)

**Comment by FabianTerhorst** [comment]
Please create the issue in c# bug tracker. Its not altv related.

**Comment by juztim** [comment]
https://docs.altv.mp/articles/configs/server.html

Check the option for csharp-module
