### ISSUE TITLE
Installer improvements

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-issues#1516]
### Description of the problem

Users often don't know where to install alt:V and use wrong directories or ones with problematic permissions.

### Desired solution for the problem

Introduce an automatic installation process:
- Install config files in AppData/Roaming
- Install binaries and cache in AppData/Local

This is the new intended way by Microsoft.

**Comment by FabianTerhorst** [comment]
There will be a config variable "expert" (Default false) that configures If the appdata folder is used or not. 
When the appdata folder is used altv will create a shortcut and place the altv.exe inside the appdata local folder. 
The appdata local and roaming folder will have the same name altv-dev, altv-rc, altv.

**Comment by C0kkie** [comment]
Should be possible in newest dev
