### ISSUE TITLE
Creating webview causes alt:V to crash

### ISSUE THREAD

**Issue by lucasmorais99** [altmp/altv-issues#1519]
### Description of the problem

Since 16/06/2022, I've ran into an issue where: upon connect, an webview is shown for login. The webview does not show up and alt:V crashes. I have narrowed it down to this specific webview causing the crash. It doesn't even appear on screen. Before the date I mentioned above, everything was working correctly.

### Reproduction steps

The following code block is what's causing the crash:

```js
function handleDiscordAuth(url) {
    if (view && view.destroy) {
        view.destroy();
    }

    discordURL = url;
    view = new alt.WebView('http://resource/client/modules/auth/html/index.html');
    view.on('discord:BearerToken', handleBearerToken);
    view.on('discord:Ready', handleReady);
    view.focus();

    showCursor(true);
}
```

It is called upon connect.

### Expected behaviour

The webview should appear and enable the player to login correctly.

### Additional context

Attached are crash logs and the whole code in question, including the HTML file.
[altv_10.10_Steam_0x942c3dff5_17-06-2022_12-25-33.zip](https://github.com/altmp/altv-issues/files/8928877/altv_10.10_Steam_0x942c3dff5_17-06-2022_12-25-33.zip)
[auth.zip](https://github.com/altmp/altv-issues/files/8928881/auth.zip)

### Operating system

Windows 10, Windows Server 2016

### Version

release/10.10

**Comment by LeonMrBonnie** [comment]
We added a fix disallowing destroying base objects multiple times, which should have fixed this issue now.
