### ISSUE TITLE
CEF, get all registered events

### ISSUE THREAD

**Issue by Zynischer** [altmp/altv-issues#1520]
### Description of the problem

On CEF-JS you can not get the registered events. You can only register and remove events. It would be helpful to create a possibility to show all registered events.

(pseudo)
alt.on("bla", {});
alt.events -> {"bla": {}} 
alt.off("bla", {});
alt.events -> {} 

### Desired solution for the problem

maybe a readable alt.events

**Comment by b2soft** [comment]
Why do you think it will be helpful? What problem does it solve?

P. S. alt.off, as we discussed before, is a bad design (and there is no alt.off in csharp client btw)

**Comment by xxshady** [comment]
@b2soft why`alt.off` is a bad design?

**Comment by b2soft** [comment]
@xxshady  Sorry, confused this with webview.off. But still did not get the point of such enhancement.

**Comment by Zynischer** [comment]
@b2soft I need a possibility to see if an event is still listening or not. You can only add and remove listeners but can not see which listeners are still enabled
