### ISSUE TITLE
tireSmokeColor setter not working

### ISSUE THREAD

**Issue by xtance** [altmp/altv-issues#1522]
### Description of the problem

player.vehicle.tireSmokeColor = new alt.RGBA(255, 1, 1, 255);
Doesn't seem to work

### Reproduction steps

Execute this code while player is in vehicle:
`player.vehicle.tireSmokeColor = new alt.RGBA(255, 1, 1, 255);`

### Expected behaviour

It should change the color of tire smoke

### Additional context

I also tried some methods from discord like this:
`player.vehicle.customTires = true`
or this:
`player.vehicle.tireSmokeColor = 1`
But they also didn't worked for me

The car for test was zentorno (not any custom model)

### Operating system

Windows 10

### Version

release/10.1

**Comment by C0kkie** [comment]
You have to set the mod and then you can use tireSmokeColor

vehicle.setMod(20, 1);
vehicle.tireSmokeColor = 1

for example

**Comment by FabianTerhorst** [comment]
Fixed in next version.
