### ISSUE TITLE
Add setVehicleXenonLightsColor setter serverisde

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#1524]
### Description of the problem

Currently there is no way serverside to set setVehicleXenonLightsColor via serverside setter

### Desired solution for the problem

Add setter & getter for setVehicleXenonLightsColor  serverside

**Comment by FabianTerhorst** [comment]
It seems like headlight color is xenon color.

**Comment by C0kkie** [comment]
Its different

**Comment by C0kkie** [comment]
Checked again and its the same, my bad
