### ISSUE TITLE
Add interval for colshapes

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1526]
### Description of the problem

For optimization purposes, I need to check a very big `colshape` every 3 seconds, not every fixed rate.

### Desired solution for the problem

```js
// Interval in ms
alt.ColshapeCircle(x: number, y: number, radius: number, interval: number);
```

### Additional context

Discussion about this in Discord.
https://discord.com/channels/371265202378899476/371271006360436757/946430787069313024

**Comment by FabianTerhorst** [comment]
For what use case you need this?

**Comment by mrgharabaghi** [comment]
For example, I don't want to load all IPLs like this https://github.com/jovanivanovic/altv-os-missing-interiors/blob/master/client/interiors.js
It doesn't make sense for a player in Sandy Shores to load Diamond Casino's IPL.
This is one of my use cases.

**Comment by FabianTerhorst** [comment]
Then i dont know for what you need a extra interval.

**Comment by mrgharabaghi** [comment]
Sandy Shores and Diamond Casino are far apart and for a server with 200 players doesn't make sense to check every 1ms for example.

**Comment by YannBcf** [comment]
First, I think there is a missunderstanding in what "loading an ipl" means, you don't actually need to "stream" it because it just tells the engine that this ipl should be rendered when this portion of the map is.

Second, colshapes calculations run into their own thread in cpp (you can see the thread id when starting your server) and it's a fairly simple maths calculations, aka checking if a point is in a shape. The optimizations you're aiming for aren't there.

**Comment by FabianTerhorst** [comment]
I dont think this Feature makes sense.

**Comment by mrgharabaghi** [comment]
> First, I think there is a missunderstanding in what "loading an ipl" means, you don't actually need to "stream" it because it just tells the engine that this ipl should be rendered when this portion of the map is.

So, why does Rockstar use natives like `requestIpl` and `removeIpl`?
@YannBcf

**Comment by deluvas1911** [comment]
> > First, I think there is a missunderstanding in what "loading an ipl" means, you don't actually need to "stream" it because it just tells the engine that this ipl should be rendered when this portion of the map is.
> 
> So, why does Rockstar use natives like `requestIpl` and `removeIpl`? @YannBcf

To adjust the map on demand. For example the farm house which can be loaded in a destroyed variant and the good variant, but one of those is always loaded. Or the train bridge with a clear way and a derailed train. 

If you take a look at the decompiled scripts you will see that rockstar doesn’t use the natives to unload not required parts of the map, only to adjust the map to the currently required state
