### ISSUE TITLE
RMLUI ASCII 8201 not rendered properly

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#1527]
### Description of the problem

As soon as I try to use the thin space character (ASCII 8201), I get a placeholder instead of the correct character.

However, the font I use supports the character.

The character: https://www.utf8icons.com/character/8201/thin-space

The result (between 6 and 2 in the speedo): 

![image](https://user-images.githubusercontent.com/53119369/175839867-4eccfe63-c658-4460-8c21-aba00d19833d.png)

### Reproduction steps

1. Create a RMLUI Element
2. Try to render the ASCII 8201 char

### Expected behaviour

The char should render properly

### Operating system

Windows 11

### Version

 10.10 (release)

**Comment by zziger** [comment]
Are you sure it exists in the font you use? In normal browser you commonly have some fallback fonts from os, but rmlui uses only the font you specified

**Comment by vanlueckn** [comment]
Ok nevermind the font doest not contain the char. I was fooled by the browser fallback.
