### ISSUE TITLE
webView freezes

### ISSUE THREAD

**Issue by thpma** [altmp/altv-issues#1528]
### Description of the problem

webview freezes after unmounting react component 

### Reproduction steps

can't really tell the behavior
it just happen randomly

### Expected behaviour

don't freeze

### Operating system

windows 10 pro

### Version

alt:V Server 10.5 (release)

**Comment by FabianTerhorst** [comment]
Not enough steps to reproduce.

**Comment by thpma** [comment]
> Not enough steps to reproduce.

yeah, i try few days now
it just happen randomly
cant really tell the steps to reproduce
just let you guys know this it is a bug
in the old version like 2.0 (i think, dont really remember) dont have this bug

**Comment by nrzull** [comment]
@thpma Do you use some kind of rpc between cef/client that use Promises? If yes, then try to use raw `window.alt.on` and `window.alt.emit`

**Comment by thpma** [comment]
@nrzull  nope, only alt.on and alt.emit
