### ISSUE TITLE
playerConnect event not triggered on dev branch

### ISSUE THREAD

**Issue by GregologyDEV** [altmp/altv-issues#1529]
### Description of the problem

On lastest dev version of alt server (11.0-dev34 and 11.0-dev33) `playerConnect` event is not triggered. However `beforePlayerConnect` seems to work perfectly fine. What's quite strange,  `playerConnect` event can be triggered by using in-game code editor ([such as](https://github.com/tameemi/altv-ingame-editor)) and it does all the job it should

### Reproduction steps

```
alt.on("playerConnect", (player) => {
    alt.log("CONNECTED NOW")
    player.spawn(0, 0, 72, 0);
    player.model = "mp_m_freemode_01";
});
```

https://www.youtube.com/watch?v=RbUIhEXm7sI&ab_channel=Gregology

### Expected behaviour

Event should be triggered at player connection

### Operating system

Windows 10 21H2

### Version

11.0-dev34 and 11.0-dev33

**Comment by FabianTerhorst** [comment]
Please provide the Code you used serverside.

**Comment by C0kkie** [comment]
I cant repro it on our qa server, it triggers normally

**Comment by FabianTerhorst** [comment]
Fix in next build.
