### ISSUE TITLE
Failed to parse server response

### ISSUE THREAD

**Issue by katsutosh** [altmp/altv-issues#1535]
### Description of the problem

if we try to connect to our testserver via direct connect and using cdn, we get the error:
`[Error] Failed to parse server response [json.exception.type_error.302] type must be number, but is string`

### Reproduction steps

connect to a server with rc-branch and cdn active

### Expected behaviour

connect successfull without any error

### Operating system

Ubuntu 20.04.4 LTS

### Version

11.0-rc3

**Comment by FabianTerhorst** [comment]
your cdn server didnt returned a json.

**Comment by katsutosh** [comment]
`connect.json` is a valid json
the error complains about the type number/string

i just checked the difference between release connect.json and rc connect.json

after running `altv-server --justpack` the permission-strings were copied instead of  using the permission IDs for the connect.json array

Example from rc connect.json: `"required-permissions":["Screen Capture", "Clipboard Access"]`
Example from release connect.json: `"required-permissions":[1]`

**Comment by FabianTerhorst** [comment]
good catch.

**Comment by FabianTerhorst** [comment]
@katsutosh test again on rc3

**Comment by deluvas1911** [comment]
Still reproducable on rc4 without using cdn

**Comment by FabianTerhorst** [comment]
Should be fixed now with rc5
