### ISSUE TITLE
-connecturl startparameter removes first character of ip/url

### ISSUE THREAD

**Issue by katsutosh** [altmp/altv-issues#1537]
### Description of the problem

if i starting alt:V with the startparam `-connecturl 127.0.0.1` or `-connecturl http://server1.example.com` its remove the first character from the ip / url.
in the mainmenu it tries to connect to: `27.0.0.1` / `ttp://server1.example.com`

### Reproduction steps

just use the startparameter `-connecturl IP`

### Expected behaviour

shouldn't remove the first character from ip/url

### Operating system

Windows 10

### Version

11.0-rc5

**Comment by FabianTerhorst** [comment]
Is it the same in release branch?

**Comment by katsutosh** [comment]
no, on release branch its working

**Comment by C0kkie** [comment]
Fixed in next rc build
