### ISSUE TITLE
Add wheel steering angle

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1540]
### Description of the problem

It would be nice and useful to add vehicle `getVehicleSteeringAngle` and `setVehicleSteeringAngle`.

### Desired solution for the problem

https://docs.fivem.net/natives/?_0x1382FCEA
https://docs.fivem.net/natives/?_0xFFCCC2EA

### Additional context

https://github.com/citizenfx/fivem/blob/8de8e67c58ac0ea765e09f5fc4f393944afbcb91/code/components/extra-natives-five/src/VehicleExtraNatives.cpp

**Comment by FabianTerhorst** [comment]
Will be available automatically after sync refactor. Since its already required for sync and then available as a clientside api as well.

**Comment by mrgharabaghi** [comment]
I want to set the angle of wheels when there is no one in the driver seat.

![angle](https://user-images.githubusercontent.com/40915667/177549364-90a0d65b-9707-4e49-b017-8cc0e96dfaf7.png)

**Comment by FabianTerhorst** [comment]
Its not settable. It will be read only.

**Comment by mrgharabaghi** [comment]
2 years ago I set the angles in FiveM and it worked well.

**Comment by FabianTerhorst** [comment]
With v12 we can add the getter. Maybe we will add the setter in a future version as well. The way fivem did it doesnt matter.

**Comment by C0kkie** [comment]
Added in v15
