### ISSUE TITLE
alt:V - ENB : Game is not starting

### ISSUE THREAD

**Issue by Faldal** [altmp/altv-issues#1541]
### Description of the problem

GTA always crashes to desktop when starting via altV with natural vision + enbseries. When I remove enbseries, it works.

### Reproduction steps

Grab the newest ENB version of the webpage or NVE with ENB included.
Test it with AMD graphics card, game crashes when main menu is loading, swap graphics card to Nvidia and repeat test; the game runs.

### Expected behaviour

Game should start without crashing, when using AMD graphics cards with ENB.

### Additional context

Crashdump (link to full dump at the bottom) shows enb as the failing module:
MODULE_NAME: d3d11_7fffec250000 IMAGE_NAME: d3d11.dll
ERROR_CODE: (NTSTATUS) 0xc0000005 - Die Anweisung in 0x%p verwies auf Arbeitsspeicher bei 0x%p. Der Vorgang %s konnte im Arbeitsspeicher nicht durchgef hrt werden.
Which is german and means "Operation could not be executed in memory".
ExceptionAddress: 00007fffec37a75c (d3d11_7fffec250000!CContext::TID3D11DeviceContext_SetShader_<1,0>+0x000000000000001c)

System:
XFX Speedster MERC 319 Radeon RX 6800 XT
AMD Ryzen 9 5900X
G.Skill DDR4-3600 F4-3600C16D-32GTZNC, Trident Z Neo

I am using AMD Software: Adrenalin 22.5.2.
But I also tried it with older drivers.

Windows Dump from crash with altV:
https://drive.google.com/file/d/1-PvY33P4IbXS8BRrr6NkSyfNVnjRsmFC/view?usp=sharing

### Operating system

Win 10 21H1

### Version

10.10

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-issues/issues/1503

**Comment by Faldal** [comment]
thank you
