### ISSUE TITLE
Launcher crashes after selecting "Install here"

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1542]
### Description of the problem

See repro steps.

### Reproduction steps

Create empty directory, copy altv.exe to it, run it, select "Install here".

### Expected behaviour

.

### Additional context

Drake already knows the cause of the problem.

### Operating system

Windows 11

### Version

11.0-rc9

**Comment by deluvas1911** [comment]
Note: It's already fixed, launcher repo just hasn't been merged yet

**Comment by xxshady** [comment]
Still happens for me.
