### ISSUE TITLE
 New wheel API not fully working

### ISSUE THREAD

**Issue by MyHwu9508** [altmp/altv-issues#1544]
### Description of the problem

The new wheel API may have some issues in the current RC branch.
Using latest RC branch client and server version.
Clientside is plain JS.

**Getters are all working fine.**

**Setters:**
setWheelCamber: working as expected
setWheelHeight: working as expected
setWheelTrackWidth: working as expected
setWheelRimRadius: Changes wheel height; not working as expected
setWheelTyreRadius: Changes wheel height; not working as expected
setWheelTyreWidth: h as no effect at all; not working as expected

### Reproduction steps

Using the problematic setters on any vanilla vehicle will reproduce the issue.
Modded vehicles or modded wheels have the same behavior.

### Expected behaviour

The setters are not doing what they are described with.

### Operating system

Windows 10

### Version

rc/11.0-rc14

**Comment by LeonMrBonnie** [comment]
These actually all work as intended from the game, the last three only have an impact on physics and not an actual visual change.
