### ISSUE TITLE
Vehicle Position-Bug

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1545]
### Description of the problem

Vehicles of different classes (e.g. Pegassi Bati 801) change position as soon as a player enters the streaming range and triggers the "gameEntityCreate" function. As soon as a player stays in the vicinity, the vehicle does not change.

The following image shows how the vehicles move after exiting and re-entering the streaming area about 30 times (vehicles were on the red line):
https://cdn.discordapp.com/attachments/768194023042580520/989557827628576768/bwSXrCD7Q_aImyUR_LUcfQ.png
https://cdn.discordapp.com/attachments/843525154465251358/996144211676123186/unknown.png

### Reproduction steps

Spawn Vehicles of different classes (e.g. Pegassi Bati 801) and exit streaming range and re-enter (fly away).

### Expected behaviour

Don't set wrong position.

### Additional context

To fix this error you can set in Serverside Spawn-Function a "SetStreamSyncedMetaData" to the Position and reset this in "ChangeSeatEvent" when oldSeat was the driver, sorry, the code formatting doesn't let me as it should.

**Workaround to Fix it:**
**(Serverside) Spawn-Function:**
...
AltAsync.Do(() => { vehicle.SetStreamSyncedMetaData("position", vehicle.Position); });
...

**(Serverside) Change-Seat-Event:**
...
public static async Task ChangeSeatEvent(SLPlayer player, SLVehicle vehicle, byte oldSeat, byte newSeat) {
	if (oldSeat == 1 && newSeat == 255) {
		AltAsync.Do(() => { if (vehicle.Exists) { vehicle.SetStreamSyncedMetaData("position", vehicle.Position); } });	
	}
	
	if (oldSeat == 255 && newSeat == 1) {
		AltAsync.Do(() => { if (vehicle.Exists) { vehicle.SetStreamSyncedMetaData("position", null); } });
	}
}
...

**(Clientside) Event**
...
alt.on('gameEntityCreate', (vehicle) => {
	if (vehicle.type != 1) return;
	
	var pos = vehicle.getStreamSyncedMeta("position");
    if (pos && distance(pos, vehicle.pos) > 0.01) {
        native.setEntityCoords(vehicle.scriptID, pos.x, pos.y, pos.z, 1, 0, 0, 1);
    }
});
...

### Operating system

Windows 10/Windows 11

### Version

10.10-release & 11.0.16-rc

**Comment by Phill030** [comment]
I assume that's because the setEntityCoords setter on clientside which shouldn't be used since you can set it on serverside and can cause un-sync between the players

**Comment by FabianTerhorst** [comment]
Test again on latest dev.

**Comment by FabianTerhorst** [comment]
Feel free to open it again when it still happens in v15.
