### ISSUE TITLE
Massive server lag

### ISSUE THREAD

**Issue by gt4ever1988** [altmp/altv-issues#1546]
### Description of the problem

As soon as a few players play on the server for around 20 minutes (4-5 players), the server lags heavily until some players (2-3) lose the connection (see yellow lines in log). For the remaining players, the server then works without any problems until it starts again after about 20 minutes.

https://cdn.discordapp.com/attachments/843525154465251358/996150786860007465/unknown.png

### Reproduction steps

With version 10.10, these errors never appear, even with more than 100 players. We use debug: 'true'

### Expected behaviour

Stable performance

### Operating system

Windows 10/Windows 11

### Version

11.0.16-rc

**Comment by Doxoh** [comment]
can not confirm this for us, with ~8 players over multiple hours

**Comment by gt4ever1988** [comment]
We restart for test with debug: 'false'

**Comment by Doxoh** [comment]
on debug you dont have these problem?

**Comment by gt4ever1988** [comment]
We just started again without the debug mode / we are testing.

**Comment by FabianTerhorst** [comment]
from the log it seems you send more then 300k events in 3 seconds.

**Comment by gt4ever1988** [comment]
Also without debug mode. Same Server-Code with 10.10 and > 100 players has no lags

https://cdn.discordapp.com/attachments/843525154465251358/996160410443059341/unknown.png

**Comment by FabianTerhorst** [comment]
test on next rc build again.

**Comment by gt4ever1988** [comment]
We test it today with 11.0.17-rc, get back to you after the tests thanks

**Comment by FabianTerhorst** [comment]
Do you have any News?

**Comment by gt4ever1988** [comment]
> Do you have any News?
Yes, we tested it again with the new RC version and couldn't find any more lags - everything was fine! The ticket can therefore be closed, thank you!
