### ISSUE TITLE
DISABLE_AUTO_WEAPON_SWAP causes weapons to shoot slower

### ISSUE THREAD

**Issue by yarxv** [altmp/altv-issues#1549]
### Description of the problem

if you set `DISABLE_AUTO_WEAPON_SWAP` weapons start shooting slower

### Reproduction steps

**Test Resource**: [test.zip](https://github.com/altmp/altv-issues/files/9112258/test.zip)

1. Set config flag DISABLE_AUTO_WEAPON_SWAP to true
2. Give player weapon_specialcarbine
3. Weapon automatically shoots slower

### Expected behaviour

The weapon(s) should shoot normal

### Operating system

Windows 11

### Version

11.0-rc22

**Comment by C0kkie** [comment]
Can you test that on release too?

**Comment by YannBcf** [comment]
Cannot reproduce this on dev branch
