### ISSUE TITLE
-noupdate CLI flag is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1552]
### Description of the problem

-noupdate flag doesn't work on rc, but does on release branch.
https://docs.altv.mp/articles/commandlineargs.html#client-launch-options

### Reproduction steps

`altv.exe -noupdate`

### Expected behaviour

`-noupdate` should skip checking for altv client updates.

### Operating system

Windows 11

### Version

11.0-rc23

**Comment by YannBcf** [comment]
It's not broken, the ``-noupdate`` flag is removed for release and rc with the update 11
