### ISSUE TITLE
Launcher crashes because of the network error

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1553]
### Description of the problem

When i start altv.exe with broken network connection it mostly just crashes without any error popup, but sometimes error window pops up and client starts as it should.

launcher.log:
```
[19:31:02] alt:V Launcher - 11.0-rc4
[19:31:02] HTTP client initialized
[19:31:02] Current working directory: C:\test-altv
[19:31:03] GDI+ started
[19:31:03] Splash Error: 0
[19:31:03] DRM found. It's Social Club
[19:31:03] Protocols registered
[19:31:03] Checking for updates
[19:31:03][Error] HTTP Request failed, curl code: 35
```

### Reproduction steps

Block network connection for altv launcher somehow and try to run altv.exe.

### Expected behaviour

Error popup and client starts after it.

![изображение](https://user-images.githubusercontent.com/54737754/179032891-551c52ec-a2d8-4c0f-af83-6e2e270348ed.png)

### Operating system

Windows 11

### Version

11.0-rc23

**Comment by xxshady** [comment]
It is also possible that ah error window will appear and if you click ok there will be a crash without starting the game

**Comment by litolax** [comment]
Confirmed on 13.0-dev12

**Comment by C0kkie** [comment]
Should be fixed in launcher rework
