### ISSUE TITLE
Wrong number of total files to download (altv-client)

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1554]
### Description of the problem

The wrong number of files is displayed during download

![image](https://user-images.githubusercontent.com/17340739/179254390-77bcd5ec-7beb-47fe-b986-a2c80e0aee54.png)

### Reproduction steps

download a new update

### Expected behaviour

Correct number of total files

### Operating system

Windows

### Version

11.0-rc25

**Comment by YannBcf** [comment]
Good catch, a fix has been pushed then i'm closing this once it's tested on our side

**Comment by C0kkie** [comment]
Looks like fixed
