### ISSUE TITLE
Switching versions breaks the text in the launcher

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1555]
### Description of the problem

The text in the launcher is unreadable when changing the branch from RC to dev for example
![TzWYKoV5g7](https://user-images.githubusercontent.com/50775241/179290456-bebd2c1a-7263-4b77-ba05-495da435cec3.png)

### Reproduction steps

1. Download RC
2. open RC
3. close the game and set the branch to dev
4. open the launcher

### Expected behaviour

The text should be in readable characters

### Operating system

Windows 10

### Version

11.1-dev4

**Comment by FabianTerhorst** [comment]
looks like the old launcher ui.

**Comment by litolax** [comment]
Can't reproduce on new ui

**Comment by C0kkie** [comment]
If you have still the problem, reopen the issue
