### ISSUE TITLE
Screen is not saved for the external console

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1556]
### Description of the problem

When starting the game and the console pops up, its on the right position but on the wrong monitor which doesn't get saved in the config file.

### Reproduction steps

1. Open the game and enable external console
2. Drag the console into a different screen and close the game
3. Open the game

### Expected behaviour

The console should be on the right screen instead of the default one.

### Operating system

Windows 10

### Version

11.1-dev4

**Comment by FabianTerhorst** [comment]
yes that feature didnt made it into 11.0. It got written in changelog but wasnt added.

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-issues/issues/1495
