### ISSUE TITLE
[Linux] altv-webengine.exe crashed if you run Alt:V in SteamLinuxRuntime_Soldier

### ISSUE THREAD

**Issue by LinuxGamesTV** [altmp/altv-issues#1561]
### Description of the problem

This affect only AMD Videocard User, on Nvidia you don't must use the SteamLinuxRuntime_Soldier.

To understand why i must use the SteamLinuxRuntime_Soldier see this Video:

https://www.twitch.tv/videos/1495747516

So if you must use the SteamLinuxRuntime_Soldier the altv-webengine.exe crashed after load, if you symlink the "chrome_elf.dll, icudtl.dat, libcef2.dll, snapshot_blob.bin and v8_context_snapshot.bin" from dir "libs" to "cef".

If you use the normal Wine way and with lutris it works with symlinks, but only for Nvidia Users. I had tested all.

But if you copy the "chrome_elf.dll, icudtl.dat, libcef2.dll, snapshot_blob.bin and v8_context_snapshot.bin" from dir "libs" to "cef", all works fine again.
This behavior has only occurred since the SocialClub fix update from 07/14/2022.
In the last Update, too.

### Reproduction steps

Create a new Proton prefix, install the Rockstarlauncher GTA 5 Version in it. After that, Alt:v to C:\AltV.

Now in a terminal/Console:
```

cd /yourProtonPrefix/drive_c/AltV
```

run
```

STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/YourUser/.local/share/Steam" STEAM_COMPAT_DATA_PATH="/Path_To_Your_Proton_Prefix/" STEAM_COMPAT_INSTALL_PATH="/Path_to_your_GTA-v_Installfolder/Grand Theft Auto V" STEAM_COMPAT_MOUNTS="/home/YourUser/.local/share/Steam/steamapps/common/Steamworks Shared:/Path_to_your_Steam_Lib/Steam/steamapps/common/Proton - Experimental:/Path_to_your_Steam_Lib/Steam/steamapps/common/SteamLinuxRuntime_soldier" DXVK_STATE_CACHE_PATH="/Path_to_the_DXVK_state_cache_dir/" DXVK_LOG_PATH="/Path_to_the_Logs_dir/" WINEFSYNC=1 WINEPREFIX="/Path_To_Your_Proton_Prefix/" /home/YourUser/.local/share/Steam/ubuntu12_32/reaper -- /Path_to_your_Steam_Lib/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=runinprefix -- /Path_to_your_Steam_Lib/Steam/steamapps/common/Proton\ -\ Experimental/bin/wine C:\\Alt-V\\altv.exe
```

If you have q4wine on your System, open it and go to the tab "processes" and you can see thats altv-webengine.exe crashed

Logs:
client_14-07-2022_22-27-51.log https://pastebin.com/f35Ucwsr
cef.log: https://pastebin.com/NXbB9WLi
launcher.log: https://pastebin.com/Y81eBCgi
cef_log.txt Proton Steam: https://pastebin.com/P8JaQzL1

### Expected behaviour

Alt:V should works

### Additional context

I wish a copy from the "chrome_elf.dll, icudtl.dat, libcef2.dll, snapshot_blob.bin and v8_context_snapshot.bin" in dir cef, because we don't need symlinks anymore on Linux and every User can run Alt:V out of the Box.

### Operating system

opensuse Tumbleweed on AMD Radeon RX 5700 XT (RadV)

### Version

since release/10.11

**Comment by C0kkie** [comment]
can you try on newest dev branch build? @LinuxGamesTV

**Comment by LinuxGamesTV** [comment]
We can close this. The problem no longer exists
