### ISSUE TITLE
alt.log() repeating errors

### ISSUE THREAD

**Issue by simas727** [altmp/altv-issues#1563]
### Description of the problem

Hello suggestion for alt:v make alt.log if same error not repeat it self every time on interval but update integer 
(101) Error etc.....

### Desired solution for the problem

alt.log() repeating errors in one line not spam

### Alternatives you considered

none yet

### Version

release/11

**Comment by ZackaryH8** [comment]
Yeah I always thought about this and it makes sense to add because otherwise your console gets flooded with errors.

**Comment by C0kkie** [comment]
Its included in update v14
