### ISSUE TITLE
Adaptivity for client console layout

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1564]
### Description of the problem

Client console looks small in high resolution.

2560 x 1440

![Снимок экрана 2022-07-17 193820(1)](https://user-images.githubusercontent.com/54737754/179413864-a20ce3df-73bc-4ccc-97dc-7e8ae0e669c3.png)

1600 x 900

![Снимок экрана 2022-07-17 194355(1)](https://user-images.githubusercontent.com/54737754/179415104-847ebc91-2e5e-4ee3-8c1a-b620ab117aff.png)

### Desired solution for the problem

Add adaptivity for client console css.

### Version

11.0

**Comment by C0kkie** [comment]
fixed in dev/14.0-dev13
