### ISSUE TITLE
Quick quit clientside function API

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1566]
### Description of the problem

There is currently no user-friendly way to quickly quit the game (console quit command doesn't count).

### Desired solution for the problem

Add quit function api to clientside.

### Alternatives you considered

Slow alternative: [native.restartGame](https://natives.altv.mp/#/0xE574A662ACAEFBB1)

### Version

11.0

**Comment by deluvas1911** [comment]
duplicate of #1557

**Comment by xxshady** [comment]
@deluvas1911 its not a duplicate, read **Desired solution for the problem** please

**Comment by FabianTerhorst** [comment]
we won't add a api for closing the game.

**Comment by Lennart-1337** [comment]
use native.restartGame()
