### ISSUE TITLE
Player Disconnect Event not Triggered

### ISSUE THREAD

**Issue by SamDavid93** [altmp/altv-issues#1567]
### Description of the problem

Not everytime the Player Disconnect Event will be triggered after the Player Disconnects...

### Reproduction steps

Quit the game and try to log it!

### Expected behaviour

Should be triggered!

### Operating system

Windows Server

### Version

11 Release

**Comment by deluvas1911** [comment]
please add a control log using the js modules playerDisconnect to check if it may be related to the csharp module

so far we haven't recevied any reports regarding this issue and I'm unable to reproduce it

**Comment by deluvas1911** [comment]
It's not a core issue but a issue of the c# module, therefor an issue should be opened on the [csharp module repository](https://github.com/FabianTerhorst/coreclr-module)

AltAsync.OnPlayerDisconnect doesn't seem to trigger the event registration, while Alt.OnPlayerDisconnect does

FYI @zziger
