### ISSUE TITLE
Add entity.get*metaKeys() to retrieve all current assigned meta data keys for the given scope (* = scope)

### ISSUE THREAD

**Issue by prdatur** [altmp/altv-issues#1571]
### Description of the problem

If we need to resync things on `gameEntityCreate` / `gameEntityDestroy` and have variable keys, it would be very easy to loop through each assigned key and sync the current state.

For example, we want to play multiple sounds on an entity. To have simplified server logic, we use variable key `effect:{A_UNIQUE_RANDOM_ID}` this could also be a uuid4v id from database.

On the client side, we then we check in *metaChanged event the key 
```
if (metaKey.startsWith('effect:')) {
...
}
```

while on *metaChanged events this works perfectly, due to the provided metaKey parameter, it is not possible on gameEntityDestroy / Create, because we do not know which key is already assigned.

### Desired solution for the problem

Some new getters for entities:

```typescript
  /**
   * Returns a list of stored meta keys.
   *
   * @returns The assigned keys.
   */
  export function getMetaKeys(): string[];
```

```typescript
  /**
   * Returns a list of stored streamed synced meta keys.
   *
   * @returns The assigned keys.
   */
  export function getStreamSyncedMetaKeys(): string[];
```

```typescript
  /**
   * Returns a list of stored synced meta keys.
   *
   * @returns The assigned keys.
   */
  export function getSyncedMetaKeys(): string[];
```

**Comment by ZackaryH8** [comment]
Seems like a good idea 👍

**Comment by C0kkie** [comment]
Got added in rc-13
