### ISSUE TITLE
Resize ingame console

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1572]
### Description of the problem

Currently there are only two options for the console size

### Desired solution for the problem

Make the console resizable in every direction instead of having a button for only two different modes

### Alternatives you considered

Predefined buttons for more modes like in Chrome
![chrome_29Z5x4iUzm](https://user-images.githubusercontent.com/50775241/180451010-c03d807b-7735-430d-935a-0007c77b8db1.png)

**Comment by C0kkie** [comment]
Currently possible in dev
