### ISSUE TITLE
Add Antialiasing to RML

### ISSUE THREAD

**Issue by MyHwu9508** [altmp/altv-issues#1573]
### Description of the problem

When using shadows, glow or even round borders it looks no bueno and the possibilities to make good UIs with RML is currently extremely limited to boxes and text.

![image](https://user-images.githubusercontent.com/16681058/180595510-ba672869-faa5-4901-9f52-31f3d2a1143d.png)

### Desired solution for the problem

Add Antialiasing.

**Comment by vanlueckn** [comment]
This would be really helpful

**Comment by martonp96** [comment]
Should be fixed with dev14.0-dev8.
