### ISSUE TITLE
"alt.getLicenseHash" broken after latest update

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv-issues#1575]
### Description of the problem

After the latest GTA update the clientside function **alt.getLicenseHash()** always seems to return the hash which it normally returns when you're not connected to the social club: **e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855**

### Reproduction steps

Call **alt.getLicenseHash()** clientside and take a look at the result

### Expected behaviour

Should return the proper license hash for the social club account

### Operating system

Windows 11 (21H2)

### Version

GTA 5 (Social Club) build 2699, server: 12.2 (release)

**Comment by LeonMrBonnie** [comment]
Fixed in next dev

**Comment by C0kkie** [comment]
will be in release
