### ISSUE TITLE
New natives from changelog are not added

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1576]
### Description of the problem

New natives are not available on latest dev branch

https://discord.com/channels/371265202378899476/585862696281571341/1001569055976726578

### Reproduction steps

Call any new native, e.g. `isJapaneseVersion`.

### Expected behaviour

The new natives must be present in the api as well as the renamed ones.

### Operating system

Windows 11

### Version

13.0-dev3

**Comment by C0kkie** [comment]
Fixed in next dev build
