### ISSUE TITLE
Add scriptIdChange to IClientEvent

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1577]
### Description of the problem

In specific situations, I need to know when the player's `scriptID` is changed.

**Comment by deluvas1911** [comment]
The script id only gets changed when the ped gets recreated, so you can use the spawned event for it

**Comment by mrgharabaghi** [comment]
True, but when I change the player model on the server side, `spawned` does not trigger.
```js
// Server side
chat.registerCmd('trevor', (player, args) => {
    player.model = 'player_two';
});
```

**Comment by mrgharabaghi** [comment]
When you change the `player.model`, `player.local.scriptID` will change on the client side.

**Comment by mrgharabaghi** [comment]
Why did you close the issue?
@FabianTerhorst

**Comment by FabianTerhorst** [comment]
because we added the spawned event for that.

**Comment by mrgharabaghi** [comment]
What about this?
https://github.com/altmp/altv-issues/issues/1577#issuecomment-1197119769

**Comment by FabianTerhorst** [comment]
we can trigger spawned event when model changes

**Comment by mrgharabaghi** [comment]
So, you do this in the future updates?

**Comment by FabianTerhorst** [comment]
yes

**Comment by mrgharabaghi** [comment]
> we can trigger spawned event when model changes

Should I open a new issue for this?
