### ISSUE TITLE
Blip.route not working anymore

### ISSUE THREAD

**Issue by TheGodlyLuzer** [altmp/altv-issues#1580]
### Description of the problem

when creating a clientside blip, routes are not shown anymore

### Reproduction steps

```js
let blip = new alt.PointBlip(0, 0, 0);
blip.sprite = 57;
blip.color = 60;
blip.alpha = 255;
blip.scale = 1;
blip.route = true;
```

### Expected behaviour

A yellow route to the blip should appear

### Operating system

Windows 10

### Version

release 12.7

**Comment by C0kkie** [comment]
Fixed in upcoming release
