### ISSUE TITLE
The Win key is blocked by active webview in the game

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1585]
### Description of the problem

See **Reproduction steps**. In singleplayer Win key always works.

### Reproduction steps

- Press F8 so alt:V webview is now active (focused)
- Press Win key, so windows start menu is opened
- Focus game window again
- Press Win key

### Expected behaviour

The Win key shouldn't be blocked.

### Operating system

Windows 11

### Version

13.0-dev4

**Comment by Phill030** [comment]
Can reproduce the same in Windows 10

**Comment by deluvas1911** [comment]
Confirmed

**Comment by xxshady** [comment]
This issue also blocks Windows key even when game is out of focus on game start, when main menu opens

**Comment by Phill030** [comment]
@xxshady I'll try today

**Comment by Phill030** [comment]
@xxshady Works!

**Comment by Phill030** [comment]
Update: First time Win-Pressing worked, now it doesn't

**Comment by xxshady** [comment]
For me it's still broken

**Comment by Phill030** [comment]
@xxshady it seems to be working right now

**Comment by xxshady** [comment]
it can work sometimes

**Comment by xxshady** [comment]
Still broken for me on latest rc

**Comment by martonp96** [comment]
There is a fix attempt in dev591, if it still comes up then its not altv related issue.
