### ISSUE TITLE
Applying mods not working with the picador

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#1586]
### Description of the problem

When applying mods on the picador nothing happens.
The only mod working is the plate color.

### Reproduction steps

Spawn a picador and apply mods on it like spoiler (id 0) or rear tray mod (id 2), they will not apply.

### Expected behaviour

Mods should work on the vehicle

### Operating system

Linux and Windows

### Version

release/12.8

**Comment by deluvas1911** [comment]
Confirmed

**Comment by deluvas1911** [comment]
@LeShred have you tested the Picador in GTA Online?
because as far as I see there are no carcols.meta entries related to that vehicle, so maybe they haven't implemented it yet?

**Comment by C0kkie** [comment]
Thats a problem on gta side, we cant fix this

**Comment by LeShred** [comment]
Sorry but the picador is modifiable on GTA Online : https://gta.fandom.com/wiki/Picador
Here is a pic of it modified : https://media.discordapp.net/attachments/995749299545722990/1004513336899158126/unknown.png?width=1443&height=732

**Comment by LeShred** [comment]
I just went on GTA Online and managed to modify the picador :
![image](https://user-images.githubusercontent.com/7643284/182725927-63dd180b-6c50-401c-ab86-010f3d2cf7b0.png)

**Comment by DurtyFree** [comment]
Fixed with latest vehmods & vehmodels binaries, available on our CDN; https://altv.mp/#/downloads
