### ISSUE TITLE
quit || disconnect command

### ISSUE THREAD

**Issue by egerdnc** [altmp/altv-issues#1587]
### Description of the problem

So right now we are unable to quit || disconnect off a server and connect to another one.
We can only reconnect to the current server.

### Desired solution for the problem

Add a quit || disconnect command that clears your GTA cache off memory and so lets you go back to the main menu of alt:v then people can connect to any other server that they wish.

The point of that is to not lose time by doing a fresh GTA load every time we want to connect another server.
Please do not tell me something like, "Modern computers can load GTA within 30-60 seconds it is not a waste."

Yes, it is a waste and annoying, I would suggest you go and try developing a server using the Athena framework you will have to restart your server and client hundreds of times during a regular day.

### Alternatives you considered

N/A

### Additional context

N/A

### Version

Any

**Comment by FabianTerhorst** [comment]
For development you have debug mode. For none devs we plan a quick reload.

**Comment by egerdnc** [comment]
How will that "quick reload" work?
