### ISSUE TITLE
Method to draw 2D line on screen

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1588]
### Description of the problem

Currently we can draw 3D lines using natives, but there are cases where you would want to draw  a2D line, e.g. for displaying object/ped skeletons.

### Desired solution for the problem

Some method that would allow to draw a line from point to point

### Alternatives you considered

Currently it's possible to draw 2D lines using rmlui but the performance isn't the best with a lot of lines, and rmlui is being drawn over cef, meaning those skeletons would be rendered on top of CEF GUIs

**Comment by martonp96** [comment]
rmlui is now renderedunder cef
