### ISSUE TITLE
Clientside Object API object disappears after leaving initial streaming range

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1589]
### Description of the problem

After spawning an object and setting the position of the object in an interval to the player position for eg. the object disappears after leaving the Streaming range where the object was spawned

### Reproduction steps

1. Spawn an object with 
```ts
    const obj = new alt.Object(alt.hash('ex_prop_crate_ammo_sc'), alt.Player.local.pos, alt.Player.local.rot, true, false);
    alt.setInterval(() => {
      const { x, y, z } = alt.Player.local.pos;
      obj.pos = new alt.Vector3(x, y, z + 4);
    }, 250);
```
2. Go out of streaming range of the object

### Expected behaviour

The object shouldn't disappear

### Additional context

https://streamable.com/c58tu7

### Operating system

Windows10

### Version

13.0-dev6 (dev)

**Comment by C0kkie** [comment]
Fixed in upcoming dev
