### ISSUE TITLE
Clientside Object API object wrong attached and is frozen

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1590]
### Description of the problem

Old Object native Way:
![image](https://user-images.githubusercontent.com/17340739/183264057-53a7a167-1a60-4fae-9c33-3dc1367776d8.png)

New Object Api Way:
![image](https://user-images.githubusercontent.com/17340739/183264266-17e8bd64-2e64-4209-b861-bd85f1379076.png)

The object is not attached to the bone and pos/rot is wrong

### Reproduction steps

- Download following zip
- Unzip
- run update-server.ps1
- start server
- connect to server
- Type T to open chat
- Type "/createOldObject" to use the old native way 
- reonnect
- Type "/createNewObject" to use the new api way

[objectBug.zip](https://github.com/altmp/altv-issues/files/9275711/objectBug.zip)

### Expected behaviour

New Object Api works like old native way

### Operating system

Windows 11

### Version

13.0-dev6 (dev)

**Comment by LeonMrBonnie** [comment]
The rotations in the alt:V API are in radians, the natives use degrees. 
Are you sure that the bone index is correct?

**Comment by LeonMrBonnie** [comment]
Can you check if using vertex index 0 for the native changes it? Internally we are using vertex index 0 instead of 2, and I am unsure what effect that has

**Comment by LeonMrBonnie** [comment]
Hm, then that is very weird. It uses the same function internally as serverside attach (which works fine), so I don't know what could cause that

**Comment by LeonMrBonnie** [comment]
Fixed, I am stupid
