### ISSUE TITLE
Clientside Object API object disappears & cam is not colliding with it

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1591]
### Description of the problem

When standing under a object, the cam has no collision and the object disappears
(*leon didn't reply me after I asked if I should create an issue*)

### Reproduction steps

1. Spawn an object with the new API 
2. Walk beneath it

### Expected behaviour

The gameplay camera should collide with the object & shouldn't make the object invisible

### Additional context

https://gfycat.com/descriptiveheavyfirecrest

### Operating system

Windows 10

### Version

13.0-dev6 (dev)

**Comment by LeonMrBonnie** [comment]
Reproduction code?

**Comment by Phill030** [comment]
```ts
    const obj = new alt.Object(alt.hash('ex_prop_crate_ammo_sc'), alt.Player.local.pos.add([0,0,2]), alt.Player.local.rot, true, true);
```

**Comment by Phill030** [comment]
Ah wait, I just found out that it only happens after changing the position 
```ts
    const { x,y,z } = alt.Player.local.pos;
    const obj = new alt.Object(alt.hash('ex_prop_crate_ammo_sc'), new alt.Vector3(x,y,z+2), alt.Player.local.rot, true);
    alt.setTimeout(() => {
      const position = alt.Player.local.pos;
      obj.pos = position.add(0,0,2)
    }, 5000);
```

**Comment by LeonMrBonnie** [comment]
Then this is the same issue as #1589, so I will close this.
