### ISSUE TITLE
Subfolder resources with same name are simply skipped

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1592]
### Description of the problem

If you create multiple subfolder resources with same name, only the first one will be loaded and the other ones will be just skipped without any errors in the server console.

### Reproduction steps

Create 2 subfolder resources with same name and specify them in server.cfg:
```yaml
resources: [
  subfolder/test
  subfolder2/test
]
```

### Expected behaviour

I think we should have some hint about something went wrong when loading resources with same name.

### Operating system

Windows 11

### Version

13.0-dev6

**Comment by LeonMrBonnie** [comment]
Done
