### ISSUE TITLE
Ctrl+c crashes server

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1594]
### Description of the problem

![изображение](https://user-images.githubusercontent.com/54737754/183301422-d175b3da-954c-49ef-9eec-2525b869cd92.png)

### Reproduction steps

Start server, ctrl+c

### Expected behaviour

No crash

### Operating system

Windows 11

### Version

13.0-dev7

**Comment by Phill030** [comment]
Isn't that what CTRL + C is made for in consoles?

**Comment by xxshady** [comment]
what do you mean?

**Comment by Phill030** [comment]
Ah nvm misread, I thought you meant that normally CTRL + C shouldn't work at all

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.
