### ISSUE TITLE
Object api spawning multiple objects causes client to crash

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1595]
### Description of the problem

When spawning two objects, the client crashes immediatly

### Reproduction steps

1. Spawn a prop with 
```ts
const obj = new alt.Object(alt.hash('ex_prop_crate_ammo_sc'), alt.Player.local.pos, alt.Player.local.rot, true)
```
3. Spawn another prop

### Expected behaviour

The client shouldn't crash and the object should be spawned

### Operating system

Windows 10

### Version

13.0-dev8 (dev)

**Comment by chaosfreak93** [comment]
No crashdump is getting created

**Comment by Phill030** [comment]
Yes, I can confirm this too

**Comment by LeonMrBonnie** [comment]
Should be fixed in next dev
