### ISSUE TITLE
Suggestions for client-side functions and events

### ISSUE THREAD

**Issue by gamelaster** [altmp/altv-issues#16]
Please, post here a comment about functions, variables and events which you like to have in client side scripting. Also, write here things also which is available in natives, we don't recommend to use natives, so we will implement things which you need. 

Please mark every function as `/ [] nameOfFunction`.

**Comment by LucasRitter** [comment]
Access to bone structures of entities would be a massively great thing to have.

**Comment by Wiwishka** [comment]
player GetAmmoInClip

**Comment by Hardy535** [comment]
These are the natives I use in one of my projects:

>[AI]
> 
> TASK_ENTER_VEHICLE (0xC20E50AA46D09CA8)
> TASK_LEAVE_VEHICLE (0xD3DBCE61A490BE02)
> CLEAR_PED_SECONDARY_TASK (0x176CECF6F920D707)
> 
> 
> [AUDIO]
> 
> PLAY_SOUND_FRONTEND (0x67C540AA08E4A6F5)
> PLAY_SOUND_FROM_ENTITY (0xE65F427EB70AB1ED)
> PLAY_SOUND_FROM_COORD (0x8D8686B622B88120)
> STOP_SOUND (0xA3B0C41BA5CC0BB5)
> FREEZE_RADIO_STATION (0x344F393B027E38C3)
> UNFREEZE_RADIO_STATION (0xFC00454CF60B91DD)
> SET_USER_RADIO_CONTROL_ENABLED (0x19F21E63AE6EAE4E)
> _IS_PLAYER_VEHICLE_RADIO_ENABLED (0x5F43D83FD6738741)
> SET_VEHICLE_RADIO_ENABLED (0x3B988190C0AA6C0B)
> 
> 
> [CAM]
> 
> RENDER_SCRIPT_CAMS (0x07E5B515DB0636FC)
> CREATE_CAM_WITH_PARAMS (0xB51194800B257161)
> DESTROY_CAM (0x865908C81A2C22E9)
> DOES_CAM_EXIST (0xA7A932170592B50E)
> SET_CAM_ACTIVE (0x026FB97D0A425F84)
> IS_CAM_ACTIVE (0xDFB2B516207D3534)
> GET_CAM_COORD (0xBAC038F7459AE5AE)
> GET_CAM_ROT (0x7D304C1C955E3E12)
> IS_SCREEN_FADED_OUT (0xB16FCE9DDC7BA182)
> IS_SCREEN_FADED_IN (0x5A859503B0C08678)
> IS_SCREEN_FADING_OUT (0x797AC7CB535BA28F)
> IS_SCREEN_FADING_IN (0x5C544BC6C57AC575)
> DO_SCREEN_FADE_IN (0xD4E8E24955024033)
> DO_SCREEN_FADE_OUT (0x891B5B39AC6302AF)
> GET_GAMEPLAY_CAM_COORD (0x14D6F5678D8F1B37)
> GET_GAMEPLAY_CAM_ROT (0x837765A25378F0BB)
> GET_GAMEPLAY_CAM_RELATIVE_HEADING (0x743607648ADD4587)
> SET_GAMEPLAY_CAM_RELATIVE_HEADING (0xB4EC2312F4E5B1F1)
> GET_FOLLOW_PED_CAM_VIEW_MODE (0x8D4D46230B2C353A)
> SET_FOLLOW_PED_CAM_VIEW_MODE (0x5A4F9EDF1673F704)
> GET_FOLLOW_VEHICLE_CAM_VIEW_MODE (0xA4FF579AC0E3AAAE)
> SET_FOLLOW_VEHICLE_CAM_VIEW_MODE (0xAC253D7842768F48)
> 
> 
> [CONTROLS]
> 
> IS_CONTROL_ENABLED (0x1CEA6BFDF248E5D9)
> IS_CONTROL_PRESSED (0xF3A21BCD95725A4A)
> IS_CONTROL_RELEASED (0x648EE3E7F38877DD)
> IS_CONTROL_JUST_PRESSED (0x580417101DDB492F)
> IS_CONTROL_JUST_RELEASED (0x50F940259D3841E6)
> GET_CONTROL_VALUE (0xD95E79E8686D2C27)
> GET_CONTROL_NORMAL (0xEC3C9B8D5327B563)
> IS_DISABLED_CONTROL_PRESSED (0xE2587F8CBBD87B1D)
> IS_DISABLED_CONTROL_JUST_PRESSED (0x91AEF906BCA88877)
> IS_DISABLED_CONTROL_JUST_RELEASED (0x305C8DCD79DA8B0F)
> GET_DISABLED_CONTROL_NORMAL (0x11E65974A982637C)
> GET_CONTROL_INSTRUCTIONAL_BUTTON (0x0499D7B09FC9B407)
> DISABLE_CONTROL_ACTION (0xFE99B66D079CF6BC)
> ENABLE_CONTROL_ACTION (0x351220255D64C155)
> DISABLE_ALL_CONTROL_ACTIONS (0x5F4B6931816E599B)
> ENABLE_ALL_CONTROL_ACTIONS (0xA5FFE9B05F199DE7)
> 
> 
> [ENTITY]
> 
> DOES_ENTITY_EXIST (0x7239B21A38F536BA)
> ATTACH_ENTITY_TO_ENTITY (0x6B9BBD38AB0796DF)
> FREEZE_ENTITY_POSITION (0x428CA6DBD1094446)
> 
> 
> [GAMEPLAY]
> 
> SET_TIME_SCALE (0x1D408577D440E81E)
> SET_WEATHER_TYPE_NOW (0x29B487C359E19889)
> _SET_WEATHER_TYPE_OVER_TIME (0xFB5045B7C42B75BF)
> _SET_WEATHER_TYPE_TRANSITION (0x578C752848ECFA0C)
> SHOOT_SINGLE_BULLET_BETWEEN_COORDS (0x867654CBC7606F2C)
> GET_MODEL_DIMENSIONS (0x03E8D3D5F549087A)
> 
> 
> [GRAPHICS]
> 
> DRAW_MARKER (0x28477EC23D892089)
> _SET_UI_LAYER (0x61BB1D9B3A95D802)
> _GET_ACTIVE_SCREEN_RESOLUTION (0x873C9F3104101DD3)
> SET_NIGHTVISION (0x18F621F7A5B1F85D)
> _IS_NIGHTVISION_ACTIVE (0x2202A3F42C8E5F79)
> SET_SEETHROUGH (0x7E08924259E08CE0)
> _IS_SEETHROUGH_ACTIVE (0x44B80ABAB9D80BD3)
> START_PARTICLE_FX_NON_LOOPED_ON_ENTITY (0x0D53A3B8DA0809D2)
> _SET_PTFX_ASSET_NEXT_CALL (0x6C38AF3693A69A91)
> REQUEST_SCALEFORM_MOVIE (0x11FE353CF9733E6F)
> HAS_SCALEFORM_MOVIE_LOADED (0x85F01B8D5B90570E)
> SET_SCALEFORM_MOVIE_AS_NO_LONGER_NEEDED (0x1D132D614DD86811)
> DRAW_SCALEFORM_MOVIE_FULLSCREEN (0x0DF606929C105BE1)
> CALL_SCALEFORM_MOVIE_METHOD (0xFBD96D87AC96D533)
> _CALL_SCALEFORM_MOVIE_FUNCTION_FLOAT_PARAMS (0xD0837058AE2E4BEE)
> _CALL_SCALEFORM_MOVIE_FUNCTION_STRING_PARAMS (0x51BC1ED3CC44E8F7)
> BEGIN_SCALEFORM_MOVIE_METHOD (0xF6E48914C7A8694E)
> END_SCALEFORM_MOVIE_METHOD (0xC6796A8FFA375E53)
> _ADD_SCALEFORM_MOVIE_METHOD_PARAMETER_INT (0xC3D0841A0CC546A6)
> _ADD_SCALEFORM_MOVIE_METHOD_PARAMETER_FLOAT (0xD69736AAE04DB51A)
> _ADD_SCALEFORM_MOVIE_METHOD_PARAMETER_BOOL (0xC58424BA936EB458)
> BEGIN_TEXT_COMMAND_SCALEFORM_STRING (0x80338406F3475E55)
> END_TEXT_COMMAND_SCALEFORM_STRING (0x362E2D3FE93A9959)
> GET_SCREEN_COORD_FROM_WORLD_COORD (0x34E82F05DF2974F5)
> 
> 
> [INTERIOR]
> 
> GET_INTERIOR_AT_COORDS (0xB0F7F8663821D9C3)
> _ENABLE_INTERIOR_PROP (0x55E86AF2712B36A1)
> _DISABLE_INTERIOR_PROP (0x420BD37289EEE162)
> _IS_INTERIOR_PROP_ENABLED (0x35F7DD45E8C0A16D)
> REFRESH_INTERIOR (0x41F37C3427C75AE0)
> 
> 
> [OBJECT]
> 
> SET_STATE_OF_CLOSEST_DOOR_OF_TYPE (0xF82D8F1926A02C3D)
> GET_STATE_OF_CLOSEST_DOOR_OF_TYPE (0xEDC1A5B84AEF33FF)
> 
> 
> [PATHFIND]
> 
> GET_STREET_NAME_AT_COORD (0x2EB41072B4C1E4C0)
> 
> 
> [PED]
> 
> IS_PED_COMPONENT_VARIATION_VALID (0xE825F6B6CEA7671D)
> SET_PED_COMPONENT_VARIATION (0x262B14F48D29DE80)
> SET_PED_CAN_SWITCH_WEAPON (0xED7F7EFE9FABF340)
> GET_PED_BONE_INDEX (0x3F428D08BE5AAE31)
> 
> 
> [STREAMING]
> 
> REQUEST_ANIM_DICT (0xD3BD40951412FEF6)
> REQUEST_IPL (0x41B4893843BBDB74)
> REMOVE_IPL (0xEE6C5AD3ECE0A82D)
> REQUEST_NAMED_PTFX_ASSET (0xB80D8756B4668AB6)
> HAS_NAMED_PTFX_ASSET_LOADED (0x8702416E512EC454)
> 
> 
> [TIME]
> 
> SET_CLOCK_TIME (0x47C3B5848C3E45D8)
> SET_CLOCK_DATE (0xB096419DF0D06CE7)
> 
> 
> [UI]
> 
> _SET_NOTIFICATION_BACKGROUND_COLOR (0x92F0DA1E27DB96DC)
> _SET_NOTIFICATION_FLASH_COLOR (0x17430B918701C342)
> _SET_NOTIFICATION_TEXT_ENTRY (0x202709F4C58A0424)
> _SET_NOTIFICATION_MESSAGE (0x2B7E9A4EAAA93C89)
> _DRAW_NOTIFICATION (0x2ED7843F8F801023)
> ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME (0x6C188BE134E074AA)
> _SET_NOTIFICATION_COLOR_NEXT (0x39BBF623FC803EAC)
> GET_STREET_NAME_FROM_HASH_KEY (0xD0EF8A959B8A4CB9)
> DISPLAY_HUD (0xA6294919E56FF02A)
> DISPLAY_RADAR (0xA0EBB943C300E693)
> IS_HUD_HIDDEN (0xA86478C6958735C5)
> IS_RADAR_HIDDEN (0x157F93B036700462)
> SET_WAYPOINT_OFF (0xA7E4E2D361C2627F)
> IS_WAYPOINT_ACTIVE (0x1DD1F58F493F1DA5)
> SET_NEW_WAYPOINT (0xFE43368D2AA4F2FC)
> HIDE_HUD_COMPONENT_THIS_FRAME (0x6806C51AD12B83B8)
> SHOW_HUD_COMPONENT_THIS_FRAME (0x0B4DF1FA60C0E664)
> 
> 
> [VEHICLE]
> 
> _SET_DISABLE_VEHICLE_SIREN_SOUND (0xD8050E0EB60CF274)
> SET_VEHICLE_SIREN (0xF4924635A19EB37D)
> IS_VEHICLE_SIREN_ON (0x4C9BF537BE2634B2)
> _IS_VEHICLE_SIREN_SOUND_ON (0xB5CC40FBCB586380)
> 
> 
> [WORLDPROBE]
> 
> START_SHAPE_TEST_LOS_PROBE (0x7EE9F5D83DD4F90E)
> START_SHAPE_TEST_CAPSULE (0x28579D1B8F8AAC80)
> _GET_SHAPE_TEST_RESULT_EX (0x65287525D951F6BE)
> 
> 
> [ZONE]
> 
> GET_NAME_OF_ZONE (0xCD90657D4C30E1CA)

**Comment by abstractFlo** [comment]
It would be nice if the vehicle has RPM and Gear properties as well.

**Comment by inpex** [comment]
Raycasts on Obejct, Vehicle and Peds

**Comment by Kipero** [comment]
- Pool of objects, players and vehicles streamedit ( so we could make foreach player in range exec function etc.),
- drawtext function,
- screen2dToWorld3d function,
- World3dToScreen2d function,
- DrawText3D function or variation of drawtext,
- streamin / streamout for players,objects,vehicles event,
- colshapes - player enter / exit colshape event,
-  player enter/exit vehicle event

**Comment by danini1705** [comment]
Stretch Objects and their collision

**Comment by datWeazel** [comment]
`createRaycast(Vector3 start, Vector3 end, int flag, LocalHandle? ignoreEntity);`

- **start**: parameter input should be in Vector3 type.
- **end**: parameter input should be in Vector3 type.
- **flag**: parameter input should be in int type. See Flags section below.
- **ignoreEntity**: parameter input should be in LocalHandle? type.




ID | Name | Description
--------|---------------|------------
-1 | Everything |  
1 | Map |  
2 | Mission_Entities |  
10 | Vehicles | //seems like it hits peds too, waiting for confirmation
12 | Peds1 | //4 and 8 both seem to be peds
16 | Objects |  
32 | Unk1 |  
64 | Unk2 |  
128 | Unk3 |  
256 | Vegetation |  
512 | Unk4

**Comment by abstractFlo** [comment]
Ability to add seatbelt to player

**Comment by FabianTerhorst** [comment]
Run tasks for entities.
Like
```
ped.tasks.cruiseWithVehicle(vehicle, speed, VehicleDrivingFlags.FollowTraffic | VehicleDrivingFlags.YieldToCrossingPedestrians);
```

**Comment by ripkens** [comment]
Get  Position in front, back ,right left of Player or Vehicle

Vector3 = (player|vehicle).getRelativePosition(int (0=front|1=back|2=right|3=left), float Distance, float Z);

**Comment by emcifuntik** [comment]
> Get Position in front, back ,right left of Player or Vehicle
> 
> Vector3 = (player|vehicle).getRelativePosition(int (0=front|1=back|2=right|3=left), float Distance, float Z);

It's pure math. You can make wrapper on it. No need in client core.

**Comment by Revyn112** [comment]
_DOOR_CONTROL (0x9B12F9A24FABEDB0)
Control of a specific door.

**Comment by martonp96** [comment]
This is not needed, please open an issue for each request, so we can keep track of them and/or group them.
