### ISSUE TITLE
Streamer mode broke

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#1603]
### Description of the problem

Streamer mode enabled freezes the game right after game version log

### Reproduction steps

`streamerMode: true` to altv.cfg

### Expected behaviour

At least game shouldnt freeze

### Operating system

Windows 11

### Version

release/12.10

**Comment by litolax** [comment]
Probably hardware dependent, cannot reproduce on 13.0-dev12

**Comment by Marvisak** [comment]
Also couldn't reproduce on 13.0-dev12 and on release/12.10

**Comment by zziger** [comment]
Cannot reproduce this exact issue on `14.0-dev32`, but now #840 is back
