### ISSUE TITLE
Add getPlayerPosition

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1607]
### Description of the problem

I have a for loop in order to get the players position and facing such a big object like `alt.Player.getByID()` isn't optimal.
It's better to add a function like `alt.getPlayerPosition()`.

### Desired solution for the problem

As you know, working with arrays in for loop is more optimal than objects like `Vector3`.
So, it's better to return an array that contains player position. `[ 11.0, 22.0, 33.0 ]`
```ts
alt.getPlayerPosition(id: number): Array | null
```

**Comment by FabianTerhorst** [comment]
This just causes api fragmentation. The benefit is not worth adding it.

**Comment by mrgharabaghi** [comment]
What about this?
```ts
alt.Player.getPlayerPosition(id: number): Array | null
```

**Comment by FabianTerhorst** [comment]
That doesnt change the fact that its a second api for the same think.
