### ISSUE TITLE
Colshape continues calculations even if no one in the server

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1609]
### Description of the problem

Colshape continues calculations even if no one in the server.
After making Colshapes, CPU usage increases in the Task Manager.

### Reproduction steps

1. Create Colshapes.
```js
const points = [
    new alt.Vector2(410.0031, -946.0042),
    new alt.Vector2(397.5432, -945.8661),
    new alt.Vector2(402.5566, -957.7299)
];

for (let i = 0; i < 20000; i++) {
    let col = new alt.ColshapePolygon(25, 35, points);
}
```
2. Run the server.

### Operating system

Windows 10

### Version

release/12.10

**Comment by LeonMrBonnie** [comment]
Heron just told you that its because colshapes are also calculated for vehicles and that the system will be rewritten.

**Comment by mrgharabaghi** [comment]
Which vehicles?
There are no vehicles in the server.
