### ISSUE TITLE
Justpack error segementation fault inside docker

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#1611]
### Description of the problem

I have a directory with an altv server inside. 
Without docker (on debian 11) i am able to pack all resources successfully.

If i try to pack the resources of the same server inside docker (debian 11 based image) i get this error:

` start.sh: line 7:    31 Segmentation fault      (core dumped)`

Some resources got packed, some others and the connect.json are missing.

### Reproduction steps

Create a debian 11 based docker image 
Try to pack resources with justpack inside the docker container

### Expected behaviour

Should pack successfully and without missing resources

### Additional context

Screenshot inside docker: https://img.joshua-gerke.de/l/TPVOzLLaSMGiss7axt9_ZQ

Screenshot outside docker: https://img.joshua-gerke.de/l/ILJBXsKFSveXckul4gl0mA

### Operating system

Debian 11

### Version

12.10 (release)

**Comment by vanlueckn** [comment]
```DOCKERFILE
FROM debian:11

RUN apt update && apt install -y libatomic1 wget curl jq

RUN mkdir -p /usr/src/altv

COPY . /usr/src/altv

RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt update && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs dotnet-sdk-6.0

RUN useradd -d /usr/src/altv altv && \
    chown -R altv:altv /usr/src/altv

USER altv
WORKDIR /usr/src/altv

EXPOSE 7788

RUN wget -O 'update.sh' 'https://raw.githubusercontent.com/Lhoerion/altv-serverupdater/master/update.sh' && \
    chmod +x ./update.sh && \
    ./update.sh && \
    chmod +x /usr/src/altv/start.sh && \
    chmod +x /usr/src/altv/altv-server

ENTRYPOINT ["/bin/bash", "start.sh"]
```

**Comment by C0kkie** [comment]
@vanlueckn  is this still a thing on newest dev?

**Comment by vanlueckn** [comment]
I will test it and provide feedback

**Comment by vanlueckn** [comment]
I tested it using docker run, it seems to work in the latest version
