### ISSUE TITLE
An unknown problem caused the server to crash

### ISSUE THREAD

**Issue by Cyuancai** [altmp/altv-issues#1614]
### Description of the problem

The server console churns out null characters ```\u0000```
Then the server crashed, If there is no crash, " Versions doesn't match [ 2900408713 != 12 ] " will be displayed
![TW}E3)~MX8TWZY9Y6{7ZNBQ](https://user-images.githubusercontent.com/32071418/184808279-071e926e-a03a-4ccd-9183-aaba976ed7c7.png)
![FW MAT`@I~W}GDGMBX%AIH](https://user-images.githubusercontent.com/32071418/184808304-751b90d3-3bfe-4640-b00b-e399d1517ad9.png)

### Reproduction steps

Can't reproduce, random problems, don't know trigger conditions

### Expected behaviour

Don't crash

### Operating system

Ubuntu 20.04.2 LTS

### Version

12.10 (release)

**Comment by C0kkie** [comment]
If its still a problem reopen the issue
