### ISSUE TITLE
Clientside Object API: attachToEntity crashes client

### ISSUE THREAD

**Issue by chaosfreak93** [altmp/altv-issues#1615]
### Description of the problem

If i try to attach one entity to another the client crashes

### Reproduction steps

- Create first Object
- Create Second Object
- Attach Second Object to First Object
- Client crash

### Expected behaviour

The Client should not crash and the entity should get attached

### Additional context

```
this.cableCar = new alt.Object(
            alt.hash('p_cablecar_s'),
            new alt.Vector3(this.pos.x - 0.2, this.pos.y, this.pos.z),
            new alt.Vector3(0, 0, this.heading),
            true,
            false
        );
this.cableCarDoor_l[0] = new alt.Object(
            alt.hash('p_cablecar_s_door_l'),
            new alt.Vector3(this.pos.x - 0.2, this.pos.y, this.pos.z),
            new alt.Vector3(0, 0, this.heading),
            true,
            false
        );
this.cableCarDoor_l[0].attachToEntity(
            this.cableCar,
            0,
            new alt.Vector3(0, 0, 0),
            new alt.Vector3(0, 0, 0),
            false,
            true,
            true
        );
```

### Operating system

Windows 11

### Version

13.0-dev9

**Comment by chaosfreak93** [comment]
[altv_13.0-dev9_Social Club_0x872e76530_15-08-2022_20-41-26.zip](https://github.com/altmp/altv-issues/files/9351007/altv_13.0-dev9_Social.Club_0x872e76530_15-08-2022_20-41-26.zip)

**Comment by C0kkie** [comment]
Fixed in next dev
