### ISSUE TITLE
Special characters in path prevent dlc resources from being streamed to client

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1618]
### Description of the problem

Issue related to [this](https://discord.com/channels/371265202378899476/652672692876607507/1009803643928719460) discord discussion.

Using the alt:V server inside a path with special characters (example from dc: `E:\Server\[AltV]\trgtg\`) prevents dlc resources from being streamed (or at least being loaded) to the client.

Renaming the [AltV] directory to something without special characters fixes this.

### Reproduction steps

Put your alt:V server with dlc resources into some path with special characters.

### Expected behaviour

Either it being working or at least show up some error in the server.log indicating that special characters in the path can lead to issues.

### Additional context

/

### Operating system

Windows 11

### Version

release/12.10

**Comment by yannbcf** [comment]
Fixed in dev13.0-56
