### ISSUE TITLE
alt-server::getServerConfig() does not return variable values properly that start with numeric characters

### ISSUE THREAD

**Issue by Quantum2707** [altmp/altv-issues#1620]
### Description of the problem

When a property in the server.cfg starts with a number it parses the value into a numeric value, e.g. into an integer or float.
Examples below:

**Default variable "host"**
When checking the output of `alt-server::getServerConfig().host` it is clearly visible that the output is really weird, it contains only the first 2 parts of the ip address (e.g. 104.0.5.10 turns into 104.0).
This happens due to the conversion method seeing 104.0 as a floating point number.

**Any custom variable**
So if using a custom variable called "testvar" which got the value "a123" assigned everything is fine but if the value "123a" is assigned, the output will become "123", completely ignoring the characters that are non-numeric

### Reproduction steps

1. Make sure alt-server::getServerConfig().host is printed into console on server start
2. Open up the server.cfg and set the host variable to 1.2.3.4
3. Start the server 
4. See the output is equal to "1.2"

To verify the issue appears only if the value of a variable starts with a numeric character:

1. Assign a new variable in the server.cfg called "test" with value "a123"
2. Start the server, output should be "a123"
3. Set the value of the test property to "123a" and restart the server.
4. The output now should be "123", since the non-numeric character is ignored

### Expected behaviour

The converter should treat strings starting with numeric characters as string instead of parsing it into a number and removing all non-numeric characters.

### Operating system

Debian Bullseye, Debian Bookworm 0w8369 Snapshot, Windows 10

### Version

RELEASE v12.8

**Comment by LeonMrBonnie** [comment]
I just fixed this 2 minutes ago xd
