### ISSUE TITLE
Game crashes cause of webview.size

### ISSUE THREAD

**Issue by litolax** [altmp/altv-issues#1621]
### Description of the problem

When I set webview.size to 4 then my game crashes

### Reproduction steps

let webview = new alt.WebView("https://www.google.com/",  true);

webview.size = 4;

### Expected behaviour

Game shoudn't crash

### Operating system

Windows 11

### Version

13.0-dev12 (dev)

**Comment by Marvisak** [comment]
Confirmed on 13.0-dev12

**Comment by LeonMrBonnie** [comment]
Already fixed
