### ISSUE TITLE
Streaming ytyp with DLC_ITYP_REQUEST doesn't work

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1627]
### Description of the problem

I followed alt:V official docs to stream addon objects.
But I've got an error and nothing spawned.

`stream.cfg`
```
files: [
    'stream/assets/*'
]

meta: {
    'stream/data/def_props.ytyp': 'DLC_ITYP_REQUEST'
}
```

### Reproduction steps

1. Download sample files from `gta5-mods`.
2. Request one of the models with `await alt.Utils.requestModel(alt.hash('block_01'), 3000);`.
3. `(Error: Model 76191688 is invalid)`

### Expected behaviour

Should stream `ytyp` without error.
`(Error: Model 76191688 is invalid)`

### Additional context

alt:V official docs:
https://docs.altv.mp/gta/articles/tutorials/stream_objects.html
https://www.gta5-mods.com/maps/billboard-props-pack-addon

### Operating system

Windows 10

### Version

release/12.10

**Comment by WhishN** [comment]
In comments of that mod people complain that the ytyp is broken so i think its an issue of that mod

**Comment by mrgharabaghi** [comment]
I tested it with a model which I made myself.
`(Error: Model xxxxxxxx is invalid)`

**Comment by C0kkie** [comment]
Send a example of your ytyp

**Comment by C0kkie** [comment]
Solution was to stream ytyp too, so streamcfg must be

files: [
    'stream/*'
]

**Comment by mrgharabaghi** [comment]
Yes, as you said, `ytyp` is not a meta file, and I had to stream `def_props.ytyp` too.
Thank you `C0kkie`.
