### ISSUE TITLE
Optional permissions are broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1628]
### Description of the problem

See repro steps.

### Reproduction steps

1. Add this to `resource.cfg`
```yml
optional-permissions: [
  Clipboard Access
]
```
2. Allow Clipboard Access in ui dialog
3. Try to get permission state
```js
alt.log(alt.getPermissionState(3 /* Permission.ClipboardAccess */))
```
4. getPermissionState returns "Denied" (1)

### Expected behaviour

Optional permissions should work i guess

### Operating system

Windows 11

### Version

13.0-dev12

**Comment by litolax** [comment]
Confirmed on 13.0-dev12

**Comment by C0kkie** [comment]
Fixed in upcomng dev
