### ISSUE TITLE
Reconnect works without debug mode

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1631]
### Description of the problem

/

### Reproduction steps

- Disable debug on both sides
- Connect to the server
- Use reconnect command

### Expected behaviour

Reconnection should only work when debug mode is enabled

### Operating system

Windows 11

### Version

13.0-dev12

**Comment by litolax** [comment]
Confirmed on 13.0-dev12

**Comment by FabianTerhorst** [comment]
Works as intended. Reconnect always worked with dev branch.
