### ISSUE TITLE
"spawned" event is called before player is spawned

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1634]
### Description of the problem

![изображение](https://user-images.githubusercontent.com/54737754/186982534-b5b089a5-2dd5-477a-810d-2de9e714d3ff.png)

### Reproduction steps

server
```js
import * as alt from 'alt-server'

alt.on('playerConnect', (player) => {
  player.model = 'mp_m_freemode_01'
  player.spawn(0, 0, 72)
})
```
client
```js
import * as alt from 'alt-client'

alt.on('spawned', () => {
  alt.log('spawned')
})
```

### Expected behaviour

"spawned" event should not be called for model changes when the player is not spawned yet.

### Operating system

Windows 11

### Version

13.0-dev12

**Comment by YannBcf** [comment]
Fixed in 13.0-dev13
