### ISSUE TITLE
Setting health to the same it was after model change leaves hp at 200 when reacting to client event

### ISSUE THREAD

**Issue by mikkasendke** [altmp/altv-issues#1635]
### Description of the problem

When setting the model and directly afterwards the hp of a player to the same hp as it was before the model change as an reaction to a client event, it will leave the hp at 200. It is also possible that for some amount of time after the model change it sets it to 200 but I don't see how that would make sense.

### Reproduction steps

C# Server:

```cs
using AltV.Net;
using AltV.Net.Elements.Entities;
using AltV.Net.Enums;

namespace Server;

class ServerMain : Resource
{ 
    public override void OnStart()
    {
    }
    public override void OnStop()
    {
    }
}
public class Events : IScript
{
    [ScriptEvent(ScriptEventType.PlayerConnect)]
    public void OnPlayerConnect(IPlayer player, string reason)
    {
        player.Model = (uint)PedModel.FreemodeMale01;
    }
    [ClientEvent("SomeEvent")]
    public void OnSomeEvent(IPlayer player)
    {
        player.Model = (uint)PedModel.FreemodeMale01;
        player.Health = 120;
    }
}
```

js Client:

```js
import * as alt from "alt-client";

alt.on("keydown", (key) => {
    if (key === 72) { // 72 = H
        alt.emitServer("SomeEvent");
    }
});
```

In this example when pressing T the hp will change with each time the key is press either from 120 to 200 or from 200 to 120.

### Expected behaviour

The health setter should work directly after a model change in response to a client event. In the example above this would amount to the model being changed and the hp bar only flickering if anything from the short time it has 200 hp from the model change and then returning to 120 after each time T is pressed.

### Operating system

Windows 10

### Version

release/12.10

**Comment by litolax** [comment]
Confirmed on 13.0-dev12

**Comment by C0kkie** [comment]
Fixed in v15
