### ISSUE TITLE
Add ability to submit nickname on welcome screen by pressing enter

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#1636]
### Description of the problem

It would increase UX because there are only one field

### Desired solution for the problem

Add ability to submit nickname on welcome screen by pressing enter

### Additional context

<img width="640" alt="Screenshot 2022-08-28 091418" src="https://user-images.githubusercontent.com/50291680/187060507-af8f1347-39b3-4e8e-887b-80934443017a.png">

### Version

release

**Comment by C0kkie** [comment]
Should work in dev/14.0-dev13
