### ISSUE TITLE
manually started ressource doesnt start on client

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#1640]
### Description of the problem

If you start or restart a ressource with the command or the code method it loads on the serevr but not on the client. It affect also all clients joining after the execution.

### Reproduction steps

use the command "start <ressource>"

### Expected behaviour

should start the ressource on server and client

### Operating system

Debian 10

### Version

13.0-dev25 (dev)

**Comment by LeonMrBonnie** [comment]
If the resource isn't specified in the resources array in the server.cfg, the client also doesn't receive the files for that resource.
But I think we should just remove starting a resource thats not in server.cfg resources list, as you are not supposed to just start a resource that wasn't previously started

**Comment by MalteCr** [comment]
But it worked a while ago. Why would you remove this feature?

**Comment by LeonMrBonnie** [comment]
If that ever worked it was a bug, and not a feature.

**Comment by MalteCr** [comment]
but it worked well, what is the point of denying it?

**Comment by FabianTerhorst** [comment]
We want to support lazy resources in the future so its on our list to allow starting a resource that wasn't send to a client yet.

**Comment by xxshady** [comment]
@FabianTerhorst so it's rather a enhancement than a bug?

**Comment by FabianTerhorst** [comment]
Duplicate of #39
