### ISSUE TITLE
alt.Blip updating pos doesn't update route

### ISSUE THREAD

**Issue by Xcker8** [altmp/altv-issues#1641]
### Description of the problem

alt.Blip updating pos doesn't update route

### Reproduction steps

this is my code
alt.onServer("Client:Player:CreateMarker", (player) => {
   // let p=targetplayer.pos;
    //let player = targetplayer;
    if (!player.valid) return;

    playerblips_blip[player.scriptID] = new alt.PointBlip(player.pos.x, player.pos.y, player.pos.z);
    playerblips_blip[player.scriptID].scale = 0.9;
    playerblips_blip[player.scriptID].color = 4;
    playerblips_blip[player.scriptID].sprite=280;
    playerblips_blip[player.scriptID].name = "客户";
    playerblips_blip[player.scriptID].routeColor = 1;
    playerblips_blip[player.scriptID].route = true;
    playerblips_blip[player.scriptID].dimension = player.dimension;

    playerblips_allblips.push(playerblips_blip[player.scriptID]);
    playerblips_interval = alt.setInterval(() => {
        

            if (playerblips_blip[player.scriptID] == undefined) {

                playerblips_blip[player.scriptID] = new alt.PointBlip(player.pos.x, player.pos.y, player.pos.z);
                playerblips_blip[player.scriptID].scale = 0.9;
                playerblips_blip[player.scriptID].color = 4;
                playerblips_blip[player.scriptID].sprite=280;
                playerblips_blip[player.scriptID].name = "客户";
                playerblips_blip[player.scriptID].routeColor = 1;
                playerblips_blip[player.scriptID].route = true;
                playerblips_blip[player.scriptID].dimension = player.dimension;
                playerblips_allblips.push(playerblips_blip[player.scriptID]);
            }
            if (!player.valid || player.scriptID == undefined) {
                playerblips_blip[player.scriptID].destroy();
                return;
            }

            playerblips_blip[player.scriptID].pos = new alt.Vector3(player.pos.x, player.pos.y, player.pos.z);
        
    }, 500);
});

### Expected behaviour

alt.Blip updating pos doesn't update route

### Operating system

win 2012

### Version

Re 12.11

**Comment by xxshady** [comment]
I don't think it's a bug, because the same happens with blips created with game natives

![изображение](https://user-images.githubusercontent.com/54737754/188680551-d1889ca3-f7c2-47ee-b1ab-65c7ffd7895f.png)

**Comment by Xcker8** [comment]
> 

So it also has problems

**Comment by FabianTerhorst** [comment]
Its a gta bug that we can workaround in the future. But priority isn't high since it can be avoided.
