### ISSUE TITLE
PushToMute Button (alt:V Voice)

### ISSUE THREAD

**Issue by cRiZZlyy-CR** [altmp/altv-issues#1644]
### Desired solution for the problem

I want add the Function when you have Voice Acitivity on that you can choose a Option to make a Button to Mute himself.

Thanks!

### Alternatives you considered

Nothing. Only this.

### Additional context

You can contact me on Discord if you need more Informations.

.cRiZZly#7777

**Comment by deluvas1911** [comment]
duplicate to #1076 and #1207
