### ISSUE TITLE
Add support for stdout logging on windows

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1646]
### Description of the problem

If e.g. starting the altv-server.exe by a C# process it's not possible to catch the stdout stream from alt:V due the current logging implementation. alt-log uses stdout only on linux.

### Desired solution for the problem

Vektor recommended using spdlog instead alt-log

### Alternatives you considered

If the benefits from the current implementation overwhelm the stdout benefits it would be nice if via the server.cfg a different logging provider (like spdlog) could be enabled

### Version

dev/13.0-dev31

**Comment by FabianTerhorst** [comment]
Afaik WriteConsoleA was chosen because its in terms of speed the fastest solution for windows.

**Comment by FabianTerhorst** [comment]
But yes it would be nice if we could make the logging implementation swappable with the server config.

**Comment by zziger** [comment]
You can also use C#'s Console.SetOut to override default text writer and send logs your own way (e.g. to Alt.Log)

**Comment by FabianTerhorst** [comment]
Already fixed in current build.
