### ISSUE TITLE
vehicle.handling.handlingNameHash does return hash as signed int instead of unsigned int

### ISSUE THREAD

**Issue by TheGodlyLuzer** [altmp/altv-issues#1647]
### Description of the problem

When using `vehicle.handling.handlingNameHash`, an incorrect value is returned.

### Reproduction steps

Try set the handling for the vehicle "Regina".

```
vehicle.handling.handlingNameHash : -14495224

realHandlingName = "REGINA";
alt.hash(realHandlingName): 4280472072
```

### Expected behaviour

vehicle.handling.handlingNameHash returns the correct value so we can rely on clientside handlingName getter

### Operating system

Windows 10

### Version

13.0-dev34

**Comment by ThomasMarangoni** [comment]
Just for your information: it's the correct hash but in the wrong format. As a temporary fix, you can cast the hash from this signed int to an unsigned int.

**Comment by TheGodlyLuzer** [comment]
ohh i see, thanks alot

**Comment by FabianTerhorst** [comment]
Fixed in next build.
