### ISSUE TITLE
Blips' heading indicator showing as a dollar sign

### ISSUE THREAD

**Issue by elBandoler** [altmp/altv-issues#1650]
### Description of the problem

I've been using [Point]Blips on both server (C#) and client (JS) side. Whenever I try to enable the heading indicator using `blip.headingIndicatorVisible`, it adds a dollar sign to the blip instead of the indicator:
![image](https://user-images.githubusercontent.com/10284630/191742769-b585d545-38df-45df-9bf2-cfd25801ea2a.png)

However, when using the native function `showHeadingIndicatorOnBlip` (even on a [Point]Blip), this does not happen, and the indicator is shown correctly.

### Reproduction steps

Create a PointBlip, then set `headingIndicatorVisible` to true, then look in the map.

### Expected behaviour

It should add a heading indicator, like the one here (the black arrow, ignore the grey arrow):
![image](https://user-images.githubusercontent.com/10284630/191743644-16b409b3-5c4d-4e69-bd0f-7460b31fcee5.png)

### Additional context

This has never happened before alt:V latest release (12), and has been repeated by other people.
As I've said, the native does work on those pointblips (`native.showHeadingIndicatorOnBlip(blip.scriptID, true);`).
Here's my #scripting-questions thread regarding this matter: https://discord.com/channels/371265202378899476/1021117059666559086

### Operating system

Windows 10 Pro 21H2

### Version

release/12.11

**Comment by CoffeeGen** [comment]
Can confirm.

Started happening after latest GTA 5 update if I recall correctly. It was the update where blips got fucked overall (blip IDs switched out, blips flashing weirdly, etc. Those issues were fixed pretty quickly but this one remained)

**Comment by C0kkie** [comment]
Will be fixed in dev/13.0-dev39
