### ISSUE TITLE
natives.giveWeaponComponentToWeaponObject doesn't work

### ISSUE THREAD

**Issue by Serske** [altmp/altv-issues#1651]
### Description of the problem

natives.giveWeaponComponentToWeaponObject doesn't give component to weapon object

### Reproduction steps

```
const weaponHash = 0x1d073a89; // weapon_pumpshotgun
natives.requestWeaponAsset(weaponHash, 31, 0); // Omitted custom function

const localPlayer = alt.Player.local;
const handle = natives.createWeaponObject(weaponHash, 1, localPlayer.pos.x, localPlayer.pos.y, localPlayer.pos.z, true, 0, 0, 0, 1);
 
const components = [0x7bc4cddc, 0xa2d79ddb];
for (let i = 0; i < components.length; ++i) {
  natives.giveWeaponComponentToWeaponObject(handle, natives.getWeaponComponentTypeModel(components[i]));
}
```
![image](https://user-images.githubusercontent.com/114166676/191786029-91eed51c-e2ce-4dc7-a1ab-e581d5477d59.png)

### Expected behaviour

Components appear on weapon

### Operating system

Windows 10 21H1

### Version

12.11-release

**Comment by Slowmoney** [comment]
try it
const weaponHash = 0x1d073a89; // weapon_pumpshotgun
natives.requestWeaponAsset(weaponHash, 31, 0); // Omitted custom function

const localPlayer = alt.Player.local;
const handle = natives.createWeaponObject(weaponHash, 1, localPlayer.pos.x, localPlayer.pos.y, localPlayer.pos.z, true, 0, 0, 0, 1);
 
const components = [0x7bc4cddc, 0xa2d79ddb];
for (let i = 0; i < components.length; ++i) {
  natives.giveWeaponComponentToWeaponObject(handle, components[i]);
}

**Comment by LeonMrBonnie** [comment]
Are you sure this bug is caused by alt:V, does it work in other multiplayer mods and/or singleplayer?

**Comment by Serske** [comment]
@LeonMrBonnie my bad, i found issue. I was abliged to

**Comment by Serske** [comment]
@LeonMrBonnie my bad, i found issue. I was obliged to request component model
