### ISSUE TITLE
Add multilanguage support for serverlist servers

### ISSUE THREAD

**Issue by MyHwu9508** [altmp/altv-issues#1654]
### Description of the problem

Bonjour!

Please give us the option to declare a server as multi-language. A lot players are not reading the server tags and just skip to another server, because they don't like the selected language. If you run a server that supports multiple languages, it's kinda frustrating.

### Desired solution for the problem

Add multilanguage option for servers.

Examples for multilanguage icon
https://www.flaticon.com/free-icon/languages_3898082?related_id=3898082&origin=search
https://www.flaticon.com/free-icon/languages_3898150?related_id=3898150&origin=search
https://www.flaticon.com/free-icon/website_8377459?related_id=8377459&origin=search

However any globe icon would work for this I guess.

### Alternatives you considered

Give us the option to set two languages instead of one.
Or change the style of the server tags, like adding colors, so players would be more focused on that.

### Additional context

Thank you <3

**Comment by zziger** [comment]
Will be available in dev/14.0-dev13 by setting language to `all`
