### ISSUE TITLE
playerConnectDenied event does not triggered

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1656]
### Description of the problem

New server event "playerConnectDenied" does not triggered

![image](https://user-images.githubusercontent.com/17340739/192059391-cd87e414-60f7-43c6-b0d6-2c8d6fe28f4d.png)

### Reproduction steps

```
alt.on("playerConnectDenied", (reason, name, ip, hash, debug, branch, version, url, id) => {
    console.log("got event");
});
```

Add these to server side. Expected to get a log.

tried, wrong password, or cdn url

### Expected behaviour

event got called

### Operating system

Windows 11

### Version

alt:V Server 13.0-dev38 (dev)

**Comment by C0kkie** [comment]
Fixed in next dev
