### ISSUE TITLE
alt:V fails to parse config file correctly when there is two # in the same line.

### ISSUE THREAD

**Issue by MusaSSH** [altmp/altv-issues#1658]
### Description of the problem

alt:V server fails to parse config file read the config file when there is a second # in the same line.

### Reproduction steps

https://docs.altv.mp/articles/configs/server.html
Copy this configuration file and you will get errors on these lines below.

```
68 # "https://nodejs.org/api/cli.html#--enable-source-maps"
69 source-maps: true,
70 # "https://nodejs.org/api/cli.html#--heap-prof"
71 heap-profiler: true,
72 # Enable profiler
73 profiler: true,
74 # "https://nodejs.org/api/cli.html#--experimental-fetch"
75 global-fetch: true,
```

### Expected behaviour

It seems to be ignoring text from start of first # to next # or line break, it should ignore texts from start of # to line break instead.

### Additional context

```
[20:51:30][Error] Error while reading server.cfg on line 68 , column 67 . Reason: key expected
[20:51:30][Error] Failed to load server.cfg
```
The error will keep appearing for the rest.

### Operating system

Tested on Windows & Linux

### Version

release/12.11

**Comment by C0kkie** [comment]
Did you check on dev branch? There was a rework of that afaik

**Comment by MusaSSH** [comment]
> Did you check on dev branch? There was a rework of that afaik

I did now, it's fixed.
