### ISSUE TITLE
Discord ID is not retrieved for some users

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#1660]
### Description of the problem

From 24th of September some users are unable to join our server, because client side **alt.Discord.currentUser.id** and server-side **connectionQueueAdd discordUserID** for some users always return null. We contacted these users to make sure they have installed Discord and are authenticated. When issue occurs client receives errors in console:

```
[17:38:03] Discord: Disconnected. Code: 4
[17:38:08] Discord: Inited
[17:38:28] Discord: Disconnected. Code: 4
[17:38:28][Error] Discord: Failed to update game activity
[17:38:28] Discord: Inited
[17:38:58] Discord: Disconnected. Code: 4
[17:38:58][Error] Discord: Failed to update game activity
[17:38:58] Discord: Inited
```

Attempted solutions
- Tried running alt:V or Discord windows apps as administrators (Does not fix the issue).
- Tried reinstalling both alt:V and Discord (Does not fix the issue).
- Tried logging out of Discord and creating a new account (Fixes the issue).
- Tried logging out of Discord and logging into a different account (Sometimes fixes the issue).

### Reproduction steps

Can't reproduce the issue, it seems to only happen to some Discord users

### Expected behaviour

Discord ID should be returned correctly if user has Discord app and is authenticated within it

### Operating system

Debian 11

### Version

12.11 (release)

**Comment by deluvas1911** [comment]
Can you reproduce it on dev branch too? Discord SDK was updated there (13.0-dev41)

**Comment by kyro95** [comment]
> Can you reproduce it on dev branch too? Discord SDK was updated there (13.0-dev41)

`[10:35:18] Discord: Inited
[10:35:18] Discord: Disconnected. Code: 4
[10:35:18][Error] Discord: Failed to update game activity
[10:35:18] Loaded font face 'rmlui-debugger-font' [regular] from 'memory'.
[10:35:18] Loaded font face 'rmlui-debugger-font' [italic] from 'memory'.
[10:35:22] alt:V Multiplayer started
[10:35:22] Started in 59238 ms
[10:35:23] Discord: Inited
[10:35:23] Discord: Disconnected. Code: 4
[10:35:28] Discord: Inited`

**Comment by FabianTerhorst** [comment]
Someone please check if it doesn't happen when you don't use the multi user discord feature.

**Comment by edgarasx** [comment]
Just talked to one of our users that have this problem, they say they don't even have the multi user feature and have not used it, yet they still get the error. This is on the release version.

**Comment by litolax** [comment]
Confirmed on 13.0-dev44

> Someone please check if it doesn't happen when you don't use the multi user discord feature.

![image](https://user-images.githubusercontent.com/60060712/193860389-37d11956-cd5b-48fa-b9b1-be3f1e1306fd.png)

**Comment by FabianTerhorst** [comment]
We need to wait till discord resolved it.

**Comment by deluvas1911** [comment]
Discord pushed a client update today. Should be resolved for all users as soon as they restart discord so they update gets installed
