### ISSUE TITLE
Add auto localization choose on first start

### ISSUE THREAD

**Issue by litolax** [altmp/altv-issues#1661]
### Description of the problem

alt:V always starts on english localization on first start

### Desired solution for the problem

In my opinion it would be great if launcher on first start will select user localization, that used by computer and set it to alt:V automatically if it will be found.

**Comment by PavlovTM** [comment]
Localization is chosen based on GTA V Settings.
Another step sounds redundant for me.

**Comment by C0kkie** [comment]
Added in new installer
