### ISSUE TITLE
Change rendering order for RML and CEF

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#1662]
### Description of the problem

As for now, RML renders after CEF so it overlaps custom-made user interface, but RML often used for in-game things like nametags. With current situation you should somehow understand when CEF UI and RML interface elements has bound intersection and hide latter if it has.

### Desired solution for the problem

Render CEF after RML, not vice versa

### Alternatives you considered

Calculate bound intersections and hide/show cef/rml ui despite the situation

### Version

release

**Comment by C0kkie** [comment]
Should be changed in upcoming dev

**Comment by ZackaryH8** [comment]
We need to be able to specify which one draws on top, sort of how z-index works in css. Maybe you want to render a few different ones?

**Comment by Shaviq** [comment]
That issue has been marked as done - is there a way render CEF after RML?
