### ISSUE TITLE
C# IPlayer.GetWeapons() behaving wierd

### ISSUE THREAD

**Issue by rabeKneo** [altmp/altv-issues#1663]
### Description of the problem

Calling the IPlayer.GetWeapons() Function returns different Values or Raises Exceptions based on which weapons and how many weapons the player has.
Holding the Weapon didnt made a difference in my test.

With none or one Weapon it works fine, the function returns an Array with zero ore one Object in it.

With two Weapons the function returned an Array with the amount of objects equal to the amount of different weapons.
But only the first object had usable values, for the second object all values were 0

With three or more Weapons the Exception System.AccessViolationException is raised
Sometimes it doesn't raise any Exception with three or four Weapons.

With 8 or more Weapons the Exception System.OverflowException is raised
Somtimes it raises this Exception with 4 weapons.

As long as the Weapons i tested with are the same between the test, the behavior is the same.
As soon as i change a weapon or the Amount of different weapons the Behavior could change.
I couldnt test every combination of all Weapons, maybe the Problem is depending on the WeaponCategory (Melee, Pistol, Throwable, ...)

### Reproduction steps

1. give the player different weapons with the GiveWeapon(WeaponModel, ...) function
2. call the GetWeapons() function in any context

to get no Exception with 3 Weapons i used following Weapons:
- CombatShotgun
- AdvancedRifle
- Musket

to get no Exception with 4 Weapons i used following Weapons:
- CombatShotgun
- AdvancedRifle
- Musket
- APPistol

to get the Access Violation Exception i used the following Weapons:
- CombatShotgun
- AdvancedRifle
- Musket
- CombatMG
or
- CombatShotgun
- AdvancedRifle
- Musket
- Hatchet
- CombatMG
- CombatPDW
- APPistol

to get the Overflow Exception i used the following Weapons:
- CombatShotgun
- AdvancedRifle
- Musket
- Hatchet
- CombatMG
- CombatPDW
- APPistol
- AssaultRifle
or
- at least 3 random weapons
- AntiqueCavalryDagger

### Expected behaviour

i expected to get an array of all the weapons the player has

### Additional context

![image](https://user-images.githubusercontent.com/70174901/194151665-0675577f-6c8e-4dca-a3a8-6f4c784f0127.png)

![image](https://user-images.githubusercontent.com/70174901/194155028-b3f0a382-6bc6-4730-bcf7-0f1b167c6781.png)

the error in the following screenshot only came twice, i cant reproduce this
![image](https://user-images.githubusercontent.com/70174901/194149982-b838d054-9fbd-4627-8551-9019a29fc25d.png)

### Operating system

Windows Server 2019 Standard - Version 1809 - OS Build 17763.3287

### Version

release/12.11

**Comment by LeonMrBonnie** [comment]
Check if this also happens with JS module

**Comment by TheGodlyLuzer** [comment]
This still occures in 12.11 c#.
