### ISSUE TITLE
Native clonePed() and setting pedComponent of a cloned ped

### ISSUE THREAD

**Issue by MyHwu9508** [altmp/altv-issues#1665]
### Description of the problem

Bonjour,

when setting the componentID (native.setPedComponentVariation) numero 3 (torso) or 4 (legs) the change will be also always appllied to the player ped. With all other component IDs this is not happening.

This only applies to peds cloned from the player using the native clonePed()

### Reproduction steps

1. Clone the player ped with native.clonePed(alt.Player.local,0, false, true); and store the returned value as ped
2. Change the leg component (ID 4) of the cloned ped.

### Expected behaviour

Changing the components of a cloned ped should not affect the player ped.

### Additional context

https://discord.com/channels/371265202378899476/1028396424439795852

### Operating system

Windows 10 21H1

### Version

12.3 (release)

### Reproduction tested

- [x] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Phill030** [comment]
I think natives won't get changed iirc

**Comment by LeonMrBonnie** [comment]
That checkbox at the bottom is there for a reason, closed until you confirmed this on dev.

**Comment by MyHwu9508** [comment]
Sir Leon,

I can confirm this issue is also present on the latest dev branch.
https://imgur.com/qzj9A3i

**Comment by FabianTerhorst** [comment]
I think this is GTA behavior. So wont be changed.

**Comment by xxshady** [comment]
This bug doesn't happen if you set last parameter of clonePed native to false
