### ISSUE TITLE
Minidump crash call stack after joining a server.

### ISSUE THREAD

**Issue by ADVGierki1** [altmp/altv-issues#1666]
### Description of the problem

I'm trying to join a certain polish roleplay server on altV, but after joining the server my console log shows this and then crashes the game.

[19:26:35] MINIDUMP: Temporary dump saved
[19:26:35] MINIDUMP: MiniDump created
[19:26:36] Crash call stack:
[19:26:36] kernelbase.dll+0x7FFB99E84FD9
vcruntime140.dll+0x7FFB85DB6480
altv-client.dll+0x4BDAB
altv-client.dll+0x47E80
altv-client.dll+0x21B389
altv-client.dll+0x21D859
altv-client.dll+0x21D68F
altv-client.dll+0x2184F4
altv-client.dll+0x1F0DEC
ucrtbase.dll+0x7FFB99A31BB2
kernel32.dll+0x7FFB9B5B7034
ntdll.dll+0x7FFB9C2A26A1
ntdll.dll+0x7FFB9C2A26A1
[altv_12.11_Social Club_0x76f204fd9_10-10-2022_21-12-56.zip](https://github.com/altmp/altv-issues/files/9748557/altv_12.11_Social.Club_0x76f204fd9_10-10-2022_21-12-56.zip)
[altv_12.11_Social Club_0x76f204fd9_10-10-2022_21-23-45.zip](https://github.com/altmp/altv-issues/files/9748559/altv_12.11_Social.Club_0x76f204fd9_10-10-2022_21-23-45.zip)

### Reproduction steps

no idea

### Expected behaviour

I'm just expecting it to work

### Operating system

Windows 10

### Version

12.11

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by zziger** [comment]
Does it crash joining other servers? Did you ask server support?
Also I'm quite sure you couldn't test this problem on the newest dev version 🙃
