### ISSUE TITLE
Increase of WEAPONINFO_FILE limit

### ISSUE THREAD

**Issue by Swwox** [altmp/altv-issues#1668]
### Description of the problem

The game has a limit on how many WEAPONINFO_FILE can be loaded, if this limit is exceeded the game crashes.

### Desired solution for the problem

Increase that limit. Essentially implement this mod https://www.gta5-mods.com/tools/cweaponinfoblob-limit-adjuster into alt:v directly I hope that is possible.

### Alternatives you considered

Using the mod although I then have to manually rename dinput8.dll back.

### Additional context

.

### Version

.

**Comment by Swwox** [comment]
for now I just made a little script that renames it back so I can use it

**Comment by C0kkie** [comment]
Did you try on newest dev

**Comment by Swwox** [comment]
seems to work
