### ISSUE TITLE
alt.setCursor

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1669]
### Description of the problem

Currently if you hover over non-cef based things you cannot change the cursor type. This can be remedied by giving users control over the type of cursor to display.

Normally controlled through css with:
```css
cursor: pointer
```

### Desired solution for the problem

```ts
alt.setCursor('pointer');
alt.setCursor('unset');
alt.setCursor('loading');
alt.setCursor('not-allowed');
```

### Alternatives you considered

Using the GTA:V native cursor; doesn't work since RMLUI, and CEF are rendered above the game itself so it doesn't make sense to do it with natives.

Also forcing the cursor to be of a certain type through CEF itself. Not a good solution for non-cef based things.

ie. If you want to have zero reliance on CEF and go full rmlui.

**Comment by LeonMrBonnie** [comment]
As changing the cursor works in rmlui now, I don't see any good usecase for this anymore.

**Comment by Stuyk** [comment]
The changes that were done fix the missing `css` properties for `cursor` inside of `rmlui`.
You can simply do `cursor: pointer` in rmlui css to make the cursor a pointer.

If you use natives, use the GTA:V native cursor for hovering / pointer.
If you use rmlui, set it in css.
If you use cef, set it in css.
