### ISSUE TITLE
alt:V Launcher Stagnation at 'Starting'

### ISSUE THREAD

**Issue by Ptr147** [altmp/altv-issues#1670]
### Description of the problem

maybe when network environment can't connect cdn.altv.mp
the alt:V Launcher will stagnation at 'Starting'

### Reproduction steps

Launch alt:V
stagnation at 'Starting'

### Expected behaviour

stagnation at 'Starting'
need wait huge time

### Additional context

pls let noupdate work

### Operating system

Windows11

### Version

release/12.11

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Can you provide more precise steps to reproduce? I don't understand how to reproduce it

**Comment by Fannerdev** [comment]
> Can you provide more precise steps to reproduce? I don't understand how to reproduce it

i think only reproduce at limited cloudflare network area (such as China).
in this network environment altv will keep to try update all along.
if dont have network altv will close.

**Comment by ZackaryH8** [comment]
> Can you provide more precise steps to reproduce? I don't understand how to reproduce it

It can sometimes happen when the RSG Launcher has a popup. alt:V will sit doing nothing until you clear the popup

**Comment by C0kkie** [comment]
Duplicate of 1553
