### ISSUE TITLE
Vehicle-Dashboard Functions

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#1672]
### Description of the problem

It would be nice if we could have access to the lamps of the vehicle dashboard to control, for example, the battery light. 
It would be a nice addition to the "new" vehicle API.

### Desired solution for the problem

There is already an [Open Source Library that makes that possible](https://github.com/E66666666/GTAVDashHook) and there is a [FiveM Pull Request that contains the functions to get but not set the state of the lamps](https://github.com/citizenfx/fivem/pull/1664/commits/eb5ef999c630eac03ac39de2cc16d08ef6fa6de2#diff-9913ec910520109854f7aeda73d0f5102284a61eff9dcb808f39e72760e667d6).

**Comment by LeonMrBonnie** [comment]
added in next dev
