### ISSUE TITLE
Implement vehicle speed getter on server-side

### ISSUE THREAD

**Issue by Whitee303** [altmp/altv-issues#1674]
### Description of the problem

Implement vehicle speed getter on server-side

### Desired solution for the problem

`let speed = vehicle.speed;
alt.log(speed)`

**Comment by LeonMrBonnie** [comment]
[https://docs.altv.mp/js/api/alt-server.Vehicle.html#_altmp_altv_types_alt_server_Vehicle_velocity](https://docs.altv.mp/js/api/alt-server.Vehicle.html#_altmp_altv_types_alt_server_Vehicle_velocity)
