### ISSUE TITLE
WebView event receives null instead of undefined

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1675]
### Description of the problem

If you send a `undefined` value in the event argument to or from webview, it will be sent as null instead of undefined

### Reproduction steps

client.js
```js
import alt from 'alt-client'
const v = new alt.WebView('http://resource/bug.html')
v.emit('test', undefined)
```

bug.html
```html
<script>
  alt.on('test', (value) => console.log('test', value))
</script>
```

![изображение](https://user-images.githubusercontent.com/54737754/197343524-68e4e5fd-f9c0-4470-bf4b-30e7ea618e2d.png)

### Expected behaviour

`undefined` should be sent as `undefined`.

### Operating system

Windows 11

### Version

13.0-dev47

### Scope

client

### Reproduction tested

- [x] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
in cef its the same in the enum.
https://magpcss.org/ceforum/apidocs3/projects/(default)/cef_value_type_t.html
there is just null there not undefined.
