### ISSUE TITLE
Alt:V Server is connecting to External Voice server even with --justpack argument

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#1677]
### Description of the problem

It look like that server is able to establish a connection to external voice server even with --justpack argument.

In my case before server launch my script is packing resources, the issue is the real server launch was unable to connect to external, if done just after. I guess the first connection made by justpack had not enough time to dispose correctly and reject the legit one.

### Reproduction steps

Setup server.cfg with voice and external voice server and launch altv server with justpack argument

### Expected behaviour

justpack should ignore voice settings

### Operating system

Ubuntu 22

### Version

release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
Fixed
