### ISSUE TITLE
Position setter is broken, adds extra height.

### ISSUE THREAD

**Issue by CoffeeGen** [altmp/altv-issues#1678]
### Description of the problem

Whenever I set a player's position via Position property, an extra ~1.0 is added to the height for no reason.

Code I'm using:
```
        // newPos can be any position really..
        Console.WriteLine( $"client pos before: { client.Position }, newPos before: { newPos }" );
        client.Position = newPos;
        Console.WriteLine( $"client pos after: { client.Position }, newPos after: { newPos }" );
```

Logs:
```
// Setting the position for the first time. I'm doing "client.Position = newPos;". I'm also freezing the player before setting position to be able to log this properly as it takes some time for altV to update the position.
client pos before: Position(x: -267,33627, y: -959,6044, z: 31,21753), newPos before: Position(x: -267,13, y: -959,73, z: 31,2231)
client pos after: Position(x: -267,33627, y: -959,6044, z: 31,21753), newPos after: Position(x: -267,13, y: -959,73, z: 31,2231) // no change yet, prolly needs to still update in altV or so

// Setting pos the second time. You can already see that the player's Z position has suddenly moved up by ~1 unit.
client pos before: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos before: Position(x: -267,13, y: -959,73, z: 31,2231)
client pos after: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos after: Position(x: -267,13, y: -959,73, z: 31,2231)

// third time, no change
client pos before: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos before: Position(x: -267,13, y: -959,73, z: 31,2231)
client pos after: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos after: Position(x: -267,13, y: -959,73, z: 31,2231)

// fourth, no change.
client pos before: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos before: Position(x: -267,13, y: -959,73, z: 31,2231)
client pos after: Position(x: -267,13846, y: -959,73627, z: 32,21167), newPos after: Position(x: -267,13, y: -959,73, z: 31,2231)
```

Also appears to be happening for JS clientside (according to KampfHamster on discord) with ``setEntityCoords``. https://discord.com/channels/371265202378899476/1036248625107439717/1036248625107439717

### Reproduction steps

- Spawn a player
- Set their position via position setter.
- Watch player being placed slightly above ground
- Do some additional logging if necessary to see the position coords.
- Optionally freeze the player before setting position so they don't drop down to the ground after setting position.

### Expected behaviour

The position to be set properly

### Additional context

I didn't test on latest dev version as I barely use that for development. My guess is this is caused by one of the latest GTA updates and thus would be present in both branches as nobody has reported it yet..

### Operating system

Windows 10

### Version

Release 12.20

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by DanielSchuech** [comment]
Hi guys,

i ve to correct my statement. The clientside native `setEntityCoords` works as expected and does not have any issues.

The issue with the ~1 z offset for serverside player `pos` setter still exists.

Best regards,
Daniel

**Comment by LeonMrBonnie** [comment]
Was fixed in last release already
