### ISSUE TITLE
Server CDN is broken on dev

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1682]
### Description of the problem

It is only broken in the dev branch, in release it works as expected.
http:// or https:// it doesn't matter.

```
[23:47:54] Disconnect reason INVALID_CDN_URL
[23:47:54][Error] Connection failed: Refused by server
```

### Reproduction steps

https://github.com/xxshady/altv-serverside-only-resource-bug
just run `yarn start` (it includes altv-server.exe start & local http server as cdn)

### Expected behaviour

/

### Operating system

Windows 11

### Version

13.0-dev52

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed on the latest dev (13.0-dev60)

**Comment by FabianTerhorst** [comment]
We can't reproduce it anymore.
