### ISSUE TITLE
Add "playerDimensionChange" event serverside

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1684]
### Description of the problem

To simplify some stuff for modular resources development serverside, just add an event which triggers when you set player.dimension.

`alt.on("playerDimensionChange",  (player, dimension) => {
    if(player.isUsingSomeStuffInAnotherDimension) {
        cancelThatStuffFor(player);
    }
});`

It becomes handy when you create modular resources and the player use some temporary functions which are only accessable in this dimension ( aka own interior ).

### Desired solution for the problem

Just add it. It's probably not a big deal.

### Alternatives you considered

Rebind the current .dimension setter or hook to a custom property

As example:
`Object.defineProperty(alt.Player.prototype, 'setDimension', function( dim : number ) {
    this.dimension = dim;
    alt.emit( "cPlayerDimensionChange", this, dim );
});`

**Comment by FabianTerhorst** [comment]
Since we have optional events now its not a overhead anymore and makes sense to add.

**Comment by LeonMrBonnie** [comment]
Added in next dev
