### ISSUE TITLE
[object].attachToEntity() crashing client without logs on 13.0 DEV55.

### ISSUE THREAD

**Issue by xenicle** [altmp/altv-issues#1685]
### Description of the problem

When [object].attachToEntity() is call client crash and close without log output or crashdump.

### Reproduction steps

With this code to reproduce the crash:

```
async function test () {
  const colliderHash = 3705876410
  const modelHash = 442185650

  const player = alt.Player.local

  const collider = new alt.Object(colliderHash, new alt.Vector3(player.pos.x, player.pos.y, player.pos.z), alt.Vector3.zero, false, true)
  await collider.waitForSpawn()

  const modelCase = new alt.Object(modelHash, alt.Vector3.zero, alt.Vector3.zero, true, false)
  await modelCase.waitForSpawn()

  modelCase.attachToEntity(collider, 0, new alt.Vector3(0.0, 0.01, 0.0), new alt.Vector3(0.0 * (Math.PI / 180), 90.0 * (Math.PI / 180), 180.0 * (Math.PI / 180)), false, false, true)
}
```

### Expected behaviour

It doesn't crash and attach entities.

### Operating system

Windows 11

### Version

13.0 DEV55

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
fixed in next dev
