### ISSUE TITLE
addRope is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#1686]
### Description of the problem

I'm adding the rope by addRope native, I'm getting the error "addRope is not a function or its return value is not iterable", and I can't use attachEntityToEntity on it.

### Reproduction steps

addRope by native and try to attachEntityToEntity with it

### Expected behaviour

It should attach rope to entity

### Additional context

It worked before the update.

### Operating system

Windows 10

### Version

release/12.22

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Post the full code you use.

**Comment by Avepy** [comment]
Nevermind, realised about something, not the client stuff.
