### ISSUE TITLE
Setting password during runtime doesn't works

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#1687]
### Description of the problem

alt.setPassword("12345678") isn't working and connections to the server are still possible without requiring a password.
Tested on C# + JS (release) & JS (dev)

### Reproduction steps

1) Start server without password
2) Set password after some delay
3) Connect to server without needing to enter a password

### Expected behaviour

Password being set

### Operating system

Windows 11

### Version

dev/13.0-dev55

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in next build
