### ISSUE TITLE
alt.Vehicle.setDoorState method will not really open or close doors

### ISSUE THREAD

**Issue by JohnDeved** [altmp/altv-issues#169]
Vehicle::setDoorState will not really open or close Doors. Only seems to work sometimes, and the doors will usually only open an inch.
(tested server side)

## Expected Behavior

should open or close doors on the target vehicle

## Current Behavior

door opens only sometimes depending on which vehicle is beeing used.
and only opens for about an inch, and not all the way.

tested vehicles: 
Dominator (about 1 out of 20 times)
Police2 (1 out of 2 times)

## Steps to Reproduce

1. use setDoorSate on any Vehicle

## Context (Environment)

<!--- Providing context helps us come up with a solution that is most useful in the real world --
I am trying to write a script where you can open a vehicle's trunk.

**Comment by lsvMoretti** [comment]
Report is still active. Been testing this evening and posting messages on Discord.

This is value 15.

https://i.imgur.com/Gb3EhSL.jpg

This is value 7.

https://i.imgur.com/gdj5zI9.jpg

I have also noticed you need to walk into the door to get it to open and doesn't work when I have been sat in the vehicle.

**Comment by FabianTerhorst** [comment]
Another way to reproduce https://github.com/altmp/altv/issues/482#issue-582454812

**Comment by Kudze** [comment]
Bump. Still not fixed.

**Comment by Revyn112** [comment]
The state will also only be visually updated, if the syncer is moving.

**Comment by martonp96** [comment]
This is now tracked in issue #737.
