### ISSUE TITLE
altv-server --config is broken on dev

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1690]
### Description of the problem

see repro

### Reproduction steps

Following file structure:
```
root/
├─ altv-server.exe/
├─ server.cfg
├─ custom.cfg
```
`altv.server.exe --config custom.cfg` server starts with server.cfg

Note: toml config format doesn't have such issue.

### Expected behaviour

/

### Operating system

Windows 11

### Version

13.0-dev57

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Use toml config and it works

**Comment by xxshady** [comment]
Found a workaround if anyone needs to use godly altcfg 😎
```
root/
├─ altv-server.exe
├─ server.toml // empty file
├─ custom.cfg
```
`altv-server.exe --config custom.cfg` works now!
