### ISSUE TITLE
Server | C# | AsyncVehicle | SetBumperDamageLevel sets bullet holes

### ISSUE THREAD

**Issue by xxMrC** [altmp/altv-issues#1693]
### Description of the problem

When i want to set bumper damage levels on a vehicle, it instead sets bullet holes on some part of the car.
Note: its about the async implementation -> AltV.Net.Async.Elements.Entities.AsyncVehicle SetBumperDamageLevel()

### Reproduction steps

Try to set the vehicles front bumper to damaged via command.
Heres a quick command to use with the chat resource and chat api.

```csharp
[Command("rmBumper")]
public async void CMD_removeBumper(Player player)
{
    player.Vehicle.SetBumperDamageLevel(0, 1);
}
```

### Expected behaviour

I expected that the damage level of the bumper gets set, instead of bullet holes.

### Additional context

```csharp
namespace AltV.Net.Async.Elements.Entities
{
    public class AsyncVehicle : AsyncEntity, IVehicle, ISharedVehicle, ISharedEntity, ISharedWorldObject, ISharedBaseObject, IRefCountable, INative, IEntity, IWorldObject, IBaseObject, IAsyncConvertible<IVehicle>
    {
        ...

        public void SetBumperDamageLevel(byte bumperId, byte damageLevel)
        {
            lock (Vehicle)
            {
                if (AsyncContext.CheckIfExistsNullable(Vehicle))
                {
                    Vehicle.SetPartBulletHoles(bumperId, damageLevel);
                }
            }
        }
        ...
    }
}
```

### Operating system

Windows 10

### Version

Release 12.22

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in next nuget build.
