### ISSUE TITLE
Blip sync is broken on dev

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1694]
### Description of the problem

/

### Reproduction steps

```js
const blip = new alt.PointBlip(0, 0, 0)
// if player connects after creation, blip is not created in game

// also doesnt work in game
blip.destroy()
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

13.0-dev57

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Test it in next build.
