### ISSUE TITLE
VoiceChannel creation calls baseObjectCreate event two times

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1695]
### Description of the problem

/

### Reproduction steps

```js
import alt from 'alt-server'

alt.on("baseObjectCreate", (baseobj) => {
  alt.log("baseObjectCreate", baseobj)
})
new alt.VoiceChannel(false, 0)
```

### Expected behaviour

One event call, as vehicle creation for example.

### Operating system

Windows 11

### Version

13.0-rc1

### Scope

server

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
fixed next build.
