### ISSUE TITLE
Pistols, Rifles, Shotguns Damage Bug

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#1696]
### Description of the problem

Pistols, Rifles, Shotguns do only 3 dmg (body) and 5dmg (head).
Meele or explosion weapons do the normal dmg.
If u use the meele function of a pistol, the dmg is 500.

### Reproduction steps

Take a weapon (pistol)
Aim at a player
Shoot!

### Expected behaviour

More than 2 dmg on body or 5 dmg on head.

### Additional context

/

### Operating system

Debian 10

### Version

13.0-rc2

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Test on release branch as well.

**Comment by xxshady** [comment]
Confirmed on 13.0-rc6

**Comment by FabianTerhorst** [comment]
fixed in rc9
