### ISSUE TITLE
Front/back window unbreakable / bullets fly through

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#1697]
### Description of the problem

You cant destroy the front window. If you shoot at the front window, the bullets fly through.
If you aim through the front window to the side window, the side window get the dmg.

For specific vehicles like the adder you have the problem with the front window.
For example dominator have the same problem with the back window.

If you respawn the vehicle, sometimes it work again.

### Reproduction steps

Take a weapon
Spawn a vehicle
Shoot on the front window.

### Expected behaviour

breaking window

### Operating system

debian 10

### Version

13.0-rc2

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can't reproduce on 13-0 rc3. Maybe I understand your thought not fully corrected but I can destroy all windows and bullets doesn't fly through. Same for `dominator`.

**Comment by deluvas1911** [comment]
13.0-rc5 not reproducable with adder (front) & dominator  (back)

**Comment by C0kkie** [comment]
QA cant repro it anymore, try on newest rc and if it still happens, feel free to reopen the issue
