### ISSUE TITLE
Sync of first person walk anim is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1699]
### Description of the problem

/

### Reproduction steps

Two players, enter first person mode, try to go backwards.

### Expected behaviour

Animation should not look like a moonwalk.

### Additional context

Reproduced it with deluvas five days ago on qa server 

### Operating system

Windows 11

### Version

13.0-dev something 

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Whitee303** [comment]
I guess it's GTA Bug not alt:V. You can join to GTA Online and note same result as in altv

**Comment by xxshady** [comment]
This is no longer reproducible on release 13.22
