### ISSUE TITLE
alt.WebView.destroy method don't close altv-webengine associated process

### ISSUE THREAD

**Issue by Matspyder51** [altmp/altv-issues#170]
When you destroy a Webview, the associated process still running, even after a disconnect, we need to totally close the game

## Expected Behavior

altv-webengine associated process should be closed/kill when the associated webview is destroyed

## Current Behavior

Removed from the game, but still running in background and can lead to an overload of processor : [11 altv-webengine process running](http://prntscr.com/o6ke9b)

## Context (Environment)

I was trying to create a manager to temporarily fix #157 and auto removed them on disconnect

## Steps to Reproduce

You can run this snippet, write test in console, then write destroy, the prop and image will be removed from the game, but you can still hear the music in background, and process in 

If you comment the props foreach loop in destroy command, you can see the image freezing on it when you destroy the webview, but it still showed
```js
let Webviews = [];

function DestroyAllWebViews() {
    Webviews.forEach((webview) => {
        webview.unfocus();
        webview.destroy();
    });
    Webviews = [];
}

function CreateWebView(url, isOverlayVal = false, targetTexture) {
    let webview = new alt.WebView(url, isOverlayVal, targetTexture);
    Webviews.push(webview);
    return webview;
}

alt.on('disconnect', () => {
    DestroyAllWebViews();
    Props.forEach((prop) => {
        natives.deleteObject(prop);
    });
});

let Props = [];

alt.on('consoleCommand', (cmd, ...args) => {
    if (cmd == "test") {
        let pos = alt.getLocalPlayer().pos;
        let hash = natives.getHashKey("gr_prop_gr_trailer_tv");
        Props.push(natives.createObject(hash, pos.x, pos.y, pos.z, false, false, false));
        let inter = alt.setInterval(() => {
            if (alt.isTextureExistInArchetype(hash, "script_rt_gr_trailertv_01")) {
                CreateWebView('https://www.youtube.com/embed/WNeLUngb-Xg?fs=1&autoplay=1&start=48', hash, "script_rt_gr_trailertv_01");
                alt.clearInterval(inter);
                return;
            }
        }, 50);
    }
    else if (cmd == "destroy") {
        DestroyAllWebViews();
        Props.forEach((prop) => {
            natives.deleteObject(prop);
        });
    }
});
```

**Comment by 7Hazard** [comment]
This issue is related to why they don't get destroyed on disconnect

**Comment by Matspyder51** [comment]
Not really, not destroying them on disconnect is more like a forget, we can removed them ourself with the "disconnect" event, but calling destroy method not killing process is lot more problematic, imagine if you create a webview to show something to the client for like 30 seconds, then you destroy it, do it 10 times that can lead to an overload for the client

**Comment by FabianTerhorst** [comment]
Destroy happen already on disconnect automatically. But process isn't killed on destroy.

**Comment by Matspyder51** [comment]
Last time I checked, video still progress on prop after I reconnect

**Comment by 7Hazard** [comment]
The webviews are based on reference counting, but somewhere it's not dereferenced and therefore it still lives

**Comment by emcifuntik** [comment]
Fixed
