### ISSUE TITLE
Server Crashing with a valid carcols.meta

### ISSUE THREAD

**Issue by XCOYoshi** [altmp/altv-issues#1700]
### Description of the problem

the server crashes when starting it with my carcols.meta set in my stream.cfg ore stream.toml

the server throws this error 

```xml
Thread 1 "altv-server" received signal SIGSEGV, Segmentation fault.
0x0000561190291795 in tinyxml2::XMLNode::FirstChildElement(char const*) const
    ()
```

the bug was discussed yesterday with @LeonMrBonnie in the discords german channel

### Reproduction steps

load the carcols.meta with it being set in the stream file of the resource

### Expected behaviour

the server should load the resource and not crash

### Additional context

here is the [.meta](https://pastebin.com/8kipqhF6) file 
it passes XMl validation
it works in single player

### Operating system

Ubuntu 22.04

### Version

dev/13.0-dev60

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by XCOYoshi** [comment]
added additional information

**Comment by FabianTerhorst** [comment]
can you upload a resource folder to reproduce? it only needs to contain the required files and cfg for the crash.

**Comment by XCOYoshi** [comment]
unfortunately, I cannot upload more files than the meta file because the vehicle is a purchased vehicle however, the bug is reproducible with the carcols.meta alone

however, I can upload the resource cfg and the stream cfg

resource.cfg:
`type: dlc,
main: stream.cfg,

client-files: [
  stream/*
]
`

stream.cfg
`files: [
  stream/*
]

meta: {
  	stream/carcols.meta: CARCOLS_FILE
}
gxt: {
}
`

**Comment by XCOYoshi** [comment]
the folder: https://github.com/XCOYoshi/Issu-relatet-stuf

**Comment by FabianTerhorst** [comment]
fixed in next build.

**Comment by XCOYoshi** [comment]
thx
