### ISSUE TITLE
stdconsole only leads to seg fault

### ISSUE THREAD

**Issue by yuAwi** [altmp/altv-issues#1701]
### Description of the problem

Enabling stdconsole without console enabled leads to Segmentation fault. I only tried with justpack.
When enabling both there will be duplicate logs.

```
gameserver-gameserver-1  | start.sh: line 16:    13 Segmentation fault      (core dumped) LD_LIBRARY_PATH=${BASEDIR} ./altv-server --host ${SERVER_HOST} --port 7788 --justpack
gameserver-gameserver-1  | start.sh: line 18:    15 Segmentation fault      (core dumped) LD_LIBRARY_PATH=${BASEDIR} ./altv-server
```

### Reproduction steps

Add `logStreams = [ "console", "file", "stdconsole" ]` to server.toml - starts as usual
Remove ` "console", ` - seg fault
Start the server

### Expected behaviour

Server shouldn't crash when only using stdconsole

### Operating system

Debian 11

### Version

13.0-rc4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
fixed in next build.
