### ISSUE TITLE
A dead body stands up when shot in the head

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1703]
### Description of the problem

![GTA5_icMvBmg82Q-min](https://user-images.githubusercontent.com/54737754/204539794-39d23c87-414f-4f3a-ab4f-73c8c55a2502.gif)

### Reproduction steps

2 players, kill player, do not respawn him, take one shot to the head.

### Expected behaviour

Dead body should not stand up on shot. Doesn't happen on release branch.

### Operating system

Windows 11

### Version

rc/13.0-rc4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed on the latest rc (13.0-rc4)

**Comment by C0kkie** [comment]
Fixed  in rc/13.0-rc6
