### ISSUE TITLE
alt:V doesn't close after invalid start

### ISSUE THREAD

**Issue by litolax** [altmp/altv-issues#1706]
### Description of the problem

If you close R* after start of alt:V, it will stay forever

### Reproduction steps

1) Start alt:V
2) Wait for R* open
3) Close R* window
4) See alt:V
![image](https://user-images.githubusercontent.com/60060712/205140614-ab717738-9b8f-4aae-a537-78b2ed1c4590.png)

### Expected behaviour

alt:V should close

### Operating system

Windows 10

### Version

rc/13.0-rc5

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
confirmed on 13.0-rc6

**Comment by C0kkie** [comment]
Added in launcher rework by a timeout
