### ISSUE TITLE
Client crash without error if enter a addon vehicle

### ISSUE THREAD

**Issue by ZieddenCoding** [altmp/altv-issues#1707]
### Description of the problem

If i Spawn an addon vehicel and i will enter then crash are close the game without error.

### Reproduction steps

- Download Custom Vehicle Addon
- Create Streaming file
- Spawn Vehicle
- Enter The Vehicel
- Client Crash

### Expected behaviour

I can enter the Vehicel an drive

### Additional context

Last Log Lines from Client
````
[19:13:02] Delegates set
[19:13:02] Client Mode was loaded!
[19:13:02] Startup finished
[19:13:02] Loaded resource gamemode-client
[19:13:02] Loading resource mh47g
[19:13:02] Loaded resource mh47g
````

### Operating system

Windows 10

### Version

alt:V build #12.22, branch release  (GTA 5 (Social Club) build 2699)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Hi, you need to provide the vehicle resource.

**Comment by litolax** [comment]
I think your addon vehicle is invalid. It can cause crashes and I think not related to alt:V

**Comment by C0kkie** [comment]
You mostly try to load a vehicle with custom vehicle layout file, which isnt supportet at the moment

**Comment by ZieddenCoding** [comment]
> You mostly try to load a vehicle with custom vehicle layout file, which isnt supportet at the moment

what is the difference a normal vehicle layout and a custom vehicle layout?

**Comment by C0kkie** [comment]
Custom layouts are mostly used to define custom positions and more seats for modded vehicles

**Comment by C0kkie** [comment]
And this is a know bug #567 
If its not the case reopen the issue and upload the ressource
