### ISSUE TITLE
Switching back and forth between Rc, release and dev results in having a .cfg and .toml file

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1708]
### Description of the problem

Switching branches between Dev and rc (or release) results in creating a .cfg/.toml file which resets the configuration of the client (name, etc.)

### Reproduction steps

1. Download dev and open it
2. switch branche to rc/release
3. start the client
You'll see a .cfg file which is resetted

### Expected behaviour

The client should use the toml file OR copy the keys & values from toml to cfg (and back if switched)

### Operating system

Windows 10

### Version

dev, rc, release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
this behavior is accepted by us because release wont get .toml support until the update is released.
