### ISSUE TITLE
Connect command doesn't work on rc branch

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1710]
### Description of the problem

/

### Reproduction steps

Enter `connect localhost` to client console on dev branch, then try on rc.

### Expected behaviour

Connect command should work on rc branch.

### Operating system

Windows 11

### Version

13.0-rc11

### Reproduction tested

- [ ] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
You have debug true?

**Comment by xxshady** [comment]
yes
![изображение](https://user-images.githubusercontent.com/54737754/205712714-1ea7639c-f9d3-4794-9faf-5d9fda860339.png)

**Comment by FabianTerhorst** [comment]
fixed in next build.
