### ISSUE TITLE
Add entityEnterColshape in client-side

### ISSUE THREAD

**Issue by Whitee303** [altmp/altv-issues#1713]
### Description of the problem

We have an 'entityEnterColshapeEvent' in serveride and it's a good solution because we don't need to use everyTick to check if the player is in the colshape. Adding this event on the client side would be a good change it seems to me

### Desired solution for the problem

Just like on the server side

### Version

13.0-dev62 (dev)

**Comment by LeonMrBonnie** [comment]
There is no colshape system clientside and there won't be one.
