### ISSUE TITLE
Client-side log problem

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1714]
### Description of the problem

Since the new release version, our alt:V client does not create more log files like before.

### Reproduction steps

Restart the client twice.

### Expected behaviour

Should be working as in the previous release version.

### Operating system

Windows 11

### Version

alt:V build #13.2, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
fixed in next dev
