### ISSUE TITLE
Size property doesn't work for radius blip

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1719]
### Description of the problem

c# BlipType.Radius cannot set scale. Some time ago same issue was with Area blip.

### Reproduction steps

IBlip areaBlip = Alt.CreateBlip(BlipType.Radius, new Position (-1562.7f, -920.2f, 13f));
areaBlip.ScaleXY = new Vector2(20f, 20f);
areaBlip.Color = 1;

### Expected behaviour

ScaleXY to set size, just like Area blip

### Operating system

Windows 10

### Version

13.09 release and 13.0rc12

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
i think we already had similar issue

**Comment by TuK4z** [comment]
Yeah, it was with AreaBlip. Now the same issue with Radius blip.

**Comment by xxshady** [comment]
Confirmed on release 13.14

**Comment by litolax** [comment]
Confirmed on the latest 15.0-dev56

**Comment by TuK4z** [comment]
After Blip rework **Area** blips Size setter is not working also.

**Comment by TuK4z** [comment]
Looks like Area blips ant Radius blip both working in latest Dev
![image](https://github.com/altmp/altv-issues/assets/40861802/eb279df3-e68f-4afa-aff5-b605cfe4a205)
