### ISSUE TITLE
alt.Vehicle.customPrimaryColor and alt.Vehicle.customSecondaryColor getter wrong return value

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv-issues#172]
customPrimaryColor and customSecondaryColor getter property return XYZ. It's bug. Good return value is RGB. Please fix.

Example:
alt.log(JSON.stringify(vehicle.customPrimaryColor))

Setter is good.

**Comment by Lekenthun** [comment]
neonColor also buggy.

**Comment by LeonMrBonnie** [comment]
Fixed.
