### ISSUE TITLE
The vehicle flickers when the netowner changes

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1725]
### Description of the problem

It's reproducable without debug enabled

https://user-images.githubusercontent.com/54737754/206899971-2fe4fe17-50ca-4f64-8370-da4126b01d77.mp4

### Reproduction steps

https://youtu.be/eEEW8AQLJ_4

### Expected behaviour

/

### Operating system

Windows 11

### Version

release 13.14

### Reproduction tested

- [x] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed on the latest release (Release 13.23)

**Comment by C0kkie** [comment]
Should be fixed in dev/15.0-dev37
