### ISSUE TITLE
Object API attach bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1728]
### Description of the problem

If we create the same attached object in the new object api, then delete it, then create it again in the same second, then everyone who was around us in the streaming distance will freeze out and constantly crashes.

### Reproduction steps

Example:
let boneName = 24818;

let object1 = new alt.Object(alt.hash("W_AR_ASSAULTRIFLE"), entity.pos, new alt.Vector3(0, 0, 0), true, false);
if(object1) {
	object1.attachToEntity(entity, (typeof(boneName) === 'string') ? game.getEntityBoneIndexByName(entity.scriptID, boneName) : game.getPedBoneIndex(entity.scriptID, boneName), new alt.Vector3(0, 0, 0), new alt.Vector3(0, 0, 0), false, false, true);

	object1.detach(true);
	object1.destroy();
}

let object2 = new alt.Object(alt.hash("W_AR_ASSAULTRIFLE"), entity.pos, new alt.Vector3(0, 0, 0), true, false);
if(object2) {
	object2.attachToEntity(entity, (typeof(boneName) === 'string') ? game.getEntityBoneIndexByName(entity.scriptID, boneName) : game.getPedBoneIndex(entity.scriptID, boneName), new alt.Vector3(0, 0, 0), new alt.Vector3(0, 0, 0), false, false, true);

	object2.detach(true);
	object2.destroy();
}

### Expected behaviour

It would be nice if it didn't cause a crash, if it already works properly with the natives.

### Operating system

Windows 11

### Version

alt:V build #13.18, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can not reproduce on the latest release (13.20)

**Comment by xxshady** [comment]
> then everyone who was around us in the streaming distance will freeze out and constantly crashes.

@Lekenthu do you mean remote players who are in streaming range?

**Comment by xxshady** [comment]
And can you please format code like this
![изображение](https://user-images.githubusercontent.com/54737754/214974850-0fd0b23e-7f22-4981-ae92-d87d9dbc90a4.png)
