### ISSUE TITLE
Add vehicle headlight colour getter

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv-issues#173]
Please add getVehicleHeadlightColor (https://runtime.fivem.net/doc/natives/#_0x3DFF319A831E0CDB) native in client-side.

**Comment by FabianTerhorst** [comment]
Headlight color is already available on serverside, no need for clientside.

**Comment by Lekenthun** [comment]
I know but I need headlight color on client-side.

**Comment by FabianTerhorst** [comment]
Have you checked if its a property in alt.Vehicle on clientside?

**Comment by Lekenthun** [comment]
Yes and I not found headlightColor property.

**Comment by FabianTerhorst** [comment]
Ok then it would make more sense to add that instead of the native.

**Comment by Lekenthun** [comment]
It is also good for me.

**Comment by LeonMrBonnie** [comment]
This was added recently.
