### ISSUE TITLE
entityLeaveColshape - colshape parameter is null when triggered by colshape deletion

### ISSUE THREAD

**Issue by Quantum2707** [altmp/altv-issues#1730]
### Description of the problem

Hey all,

I did not touch my script for 2 months and before updating my server to release 13.23/13.29, when deleting a colshape the `entityLeaveColshape` event was fired where it showed which colshape was left (**colshape not null**).
Now after a colshape got deleted, the entityLeaveColshape event got fired with the colshape parameter being **null**.
Since for my script this is a breaking change I wanted to make sure if this is just an issue which will be fixed or if this is by design.

Cheers

### Reproduction steps

Script Preparation:
- listen to entityEnterColshape and entityLeaveColshape
- Delete colshape on entityEnterColshape
- Log colshape parameter of event entityLeaveColshape when fired

Ingame:
1. Create a Colshape
2. Go into a Colshape
3. Delete the Colshape
4. See the console output

### Expected behaviour

The colshape should not be null as it was before (if not changed by design)

### Additional context

Dev Build seems broken rn - Could not test on latest dev

### Operating system

Windows 10

### Version

release 13.23/13.29

### Reproduction tested

- [ ] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can not reproduce on the latest release (13,35)

**Comment by ISFASI** [comment]
Still happening on 13.37

**Comment by FabianTerhorst** [comment]
Fixed in latest dev and release.
