### ISSUE TITLE
Wrong content of error message

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1732]
### Description of the problem

When trying to start the server with a missing or corrupt server.toml, the error message is `[Error] Failed to load server.cfg` instead of `[Error] Failed to load server.toml`

### Reproduction steps

1. Delete `server.toml`
2. Start the server and look for the console output

### Expected behaviour

The error message should be
`[Error] Failed to load server.toml`
instead of
`[Error] Failed to load server.cfg`

### Additional context

(I cannot confirm on dev, since it is unplayable rn)

### Operating system

Windows 10

### Version

Release 13.35

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can not confirm on the latest release (13.35), maybe I don't understand wdym. 
![image](https://user-images.githubusercontent.com/60060712/208264126-c831d4d2-14e4-4e51-a84c-ef26c4eac5bd.png)
(I deleted me server.toml)

**Comment by Phill030** [comment]
there should be a red error when the file is not found

**Comment by Phill030** [comment]
![NVIDIA_Share_VJUK93MNA1](https://user-images.githubusercontent.com/50775241/208267726-a6a07e9f-fa27-4bdf-bb12-c8d108968a99.png)

**Comment by litolax** [comment]
![image](https://user-images.githubusercontent.com/60060712/208290863-64aa847c-2260-4b5d-aca4-29057d1a116b.png)
Can not confirm anyway

**Comment by Phill030** [comment]
Ah ok so I found why. If you have a server.cfg and not a server.toml it says "failed to load server.cfg" instead of toml for me

**Comment by litolax** [comment]
alt:V it this case try to load server.cfg because you can now use it without convert, and I think error message describe error correctly.

**Comment by LeonMrBonnie** [comment]
Working as intended
