### ISSUE TITLE
Custom vehicle model bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1733]
### Description of the problem

Since the last GTA update, some parts of some modded cars are not loading. Here is an example in the picture. There was a problem with these cars a long time ago, for which Vektor made a workaround. In my opinion, there may be a problem with this, because of it cannot load.

Pic: https://i.imgur.com/PBpdfCo.jpeg

### Reproduction steps

Step 1: Let's overwrite trailersmall files. (https://anonfiles.com/Z8fdtfN8yf/example_rar)
Step 2: Spawn trailersmall trailer.

### Expected behaviour

Should be working as in the previous gta version.

### Operating system

Windows 11

### Version

alt:V build #13.37

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
i can wrong but this "issue" is related to that the mod vehicle data that he use as core are modify?
in simply words the mod vehicle reference to Data that called in old GTA StuffA and in new GTA StuffA is gone?

in core it sounds first for me like every thing you have with map replacements 
if you use GTAV2392 mappart123 to Modify the city park area and GTA Update 2393 Removes/rename a model thats used in the map then its gone in your modified map by reference to nothing in the new version

**Comment by Lekenthu** [comment]
It works on another model. Something has changed on this basic model.
