### ISSUE TITLE
playerLeftVehicle is called with null vehicle on destroy

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1734]
### Description of the problem

Server-side playerLeftVehicle event is called with null vehicle parameter after vehicle destroy call

### Reproduction steps

```js
alt.on("playerLeftVehicle", (player, vehicle, seat) => {
  alt.log("playerLeftVehicle", player, vehicle, seat)
})
const player = alt.Player.all[0]
const vehicle = new alt.Vehicle("sultan", player.pos, player.rot)
player.setIntoVehicle(vehicle, 1)

alt.setTimeout(() => {
  vehicle.destroy()
}, 1500)
```

### Expected behaviour

playerLeftVehicle should be always called with valid vehicle instance

### Additional context

Can be related to #1730

### Operating system

Windows 11

### Version

release 13.35

### Reproduction tested

- [x] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed on the latest release (13.37)

**Comment by ZackaryH8** [comment]
It's also present on `14.0-dev1 (dev)`

**Comment by FabianTerhorst** [comment]
Fixed in latest dev and release.
