### ISSUE TITLE
Clientside native / method to deduct stamina

### ISSUE THREAD

**Issue by riffy** [altmp/altv-issues#1735]
### Description of the problem

A detailed description and some discussion can be found here:
[Discord Scripting Question](https://discord.com/channels/371265202378899476/1054377387279781978)

In Summary:
To make more use of the stamina a player has, server developers may found it beneficial to manipulate the current stamina a player has (for this purpose can be clientside only).

### Desired solution for the problem

Must Have: Providing a native

Nice to have: Implementing a player property "stamina", which invokes the correct natives on the clientside, e.g.:
- Reading stamina `const currentStamina = alt.Player.local.stamina` invokes `natives.getPlayerSprintStaminaRemaining(alt.Player.local.scriptID)`
- Setting stamina `alt.Player.local.stamina -= 10` invokes the new native (from Option 1)

### Alternatives you considered

Manipulating the `maxStamina` with `alt.setStat` and resetting. Wouldn't work.

**Comment by LeonMrBonnie** [comment]
Added in next dev
