### ISSUE TITLE
Force Snow pass

### ISSUE THREAD

**Issue by 5pHiNxX** [altmp/altv-issues#1736]
### Description of the problem

alt:V has no possiblity to allow permanent snow in other weather types than xmas.

### Desired solution for the problem

Create a alt function that forces a snow pass render like this custom FiveM Native: [https://docs.fivem.net/natives/?_0xE6E16170](https://docs.fivem.net/natives/?_0xE6E16170)

This would allow servers to have snow laying on the ground and also have other weather types. So you don't have to stick with xmas if you want permanent snow.

**Comment by xenfee** [comment]
Было бы здорово!

**Comment by C0kkie** [comment]
Added in v15
