### ISSUE TITLE
Having a server name with less than 2 characters (or emojis) results in an Discord error

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1737]
### Description of the problem

Having a server name with less than 2 characters (or emojis) results in an Discord error clientside because the name should be at least 2 characters.

### Reproduction steps

1. Rename the server name to 'A' or '☕' for example and start it
2. Join the server and open the console
3. You will see the following warning message:
![GTA5_JdjIwT3O9y](https://user-images.githubusercontent.com/50775241/208454866-00ca1556-0fc6-414a-81ce-0f53168ed38c.png)

### Expected behaviour

The name of the server should be there.

### Additional context

Maybe add some invisible whitespace characters to fill the missing character so a single emoji or character could be there

### Operating system

Windows 10

### Version

Release 13.37

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
In no real world scenario would it make sense for a server name to only be one character long, fixing this would be wasting time.

**Comment by Phill030** [comment]
It would be only two lines of code 🤷‍♂️
