### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by YouLing96** [altmp/altv-issues#1739]
### Description of the problem

after updating version 13.x, the server always crashed. the problem started about half an hour after I updated version 13.0, and it still exists today. the current version is 13.37, and there is no error log every time the server crashes.

### Reproduction steps

Occurs irregularly

### Expected behaviour

Server crash

### Operating system

window server 2012

### Version

13.x

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Without reproduction or crashdump you have to wait for newer updates to 13.x.
