### ISSUE TITLE
Random player model desync

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#1744]
### Description of the problem

Player model random desyncs for other people. The desyned model is then cs_amandatownley. I can't provied further information than this:

- Debian 11
- AltV verion 13.37
- Only serverside char appearance setters used
- No clothes set (except hair)
- No probs set
- Players are spawned, then model set, then appearance set

Local char is normal freemode model:
https://i.imgur.com/7ERZaZF.jpeg

Other player is seeing cs_amandatownley :
https://i.imgur.com/oqY64B7.jpeg

Relog is fixing the problem temporarly.

Already reported in #1352 

### Reproduction steps

none

### Expected behaviour

should not desync

### Additional context

was not tested on dev

### Operating system

Debian 11

### Version

13.37 release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Do you use reconnect before?

**Comment by cmdflow** [comment]
You mean if it ever happend using reconnect before (in the past, other versions, etc)? No it did not. I use reconnect at the moment and it happens.

**Comment by LeonMrBonnie** [comment]
> was not tested on dev
Then we will also not test if this is true either.

**Comment by cmdflow** [comment]
wow

**Comment by LeonMrBonnie** [comment]
(Also a sidenote; Do this again and you will be banned from posting issues again, the checkbox is there for a reason!!!)

**Comment by cmdflow** [comment]
Yes but not everybody is able to switch versions or operating systems as they want to

**Comment by litolax** [comment]
You don't need to switch operation system, checkbox don't required it

**Comment by xYouLL** [comment]
Facing this issue on 15.0-dev268 (dev).
No idea on how to reproduce it. It just happens randomly on first spawn.
