### ISSUE TITLE
WebView - new Audio()

### ISSUE THREAD

**Issue by cuBeUrg** [altmp/altv-issues#1745]
### Description of the problem

There is a strange issue going on with the Web Audio API in the WebViews.

The stream URL I'm trying to play is: `https://live.magicfm.ro/magicfm.mp3`

When entering on the link, the music is playing, so the stream works. 

I have the following code running in a Vue 3 + Vite app:

`
this.audioStream = document.createElement('audio');
this.audioStream.crossOrigin = 'anonymous';
this.audioStream.src = this.soundUrl;
this.audioStream.muted = true;
this.audioStream.volume = 0.05;
this.audioStream.play();
this.audioStream.muted = false;
`

When running the code in the browser using the dev mode ( `localhost:5173` ), it works perfectly, nothing wrong, just like it shoul work. However, when I create a WebView from the link ( `localhost:5173` ) the audio doesn't play anymore.

I tried multiple other streams, some of them work in both the browser and webview, and some only play in the browser, including the stream URL from above.

The other streams had different formats (.mp3, etc.) and all the formats I tried worked, so this is for sure not a format problem.

I tried debugging the problem a bit, and checked the console in both the Browser and the Webview. The results where exactly the same, except for the Chromium version. The browser chromium version is 108, and the webview chromium version is 108, and this makes me think that the problem may be from the Chromium version.

![image](https://user-images.githubusercontent.com/42491195/210170342-846f3ce7-5050-422c-bf25-83fb4dd4d29e.png)
![image](https://user-images.githubusercontent.com/42491195/210170348-b249ee36-ac24-4174-8617-df101308a6d7.png)

### Reproduction steps

`
let audioStream = document.createElement('audio');
audioStream.crossOrigin = 'anonymous';
audioStream.src = "https://live.magicfm.ro/magicfm.mp3";
audioStream.muted = true;
audioStream.volume = 0.05;
audioStream.play();
.audioStream.muted = false;
`

### Expected behaviour

The audio should play, just as it plays in the browser.

### Operating system

Windows 10

### Version

up to 14.0-dev4 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
You have to use a none licensed audio/video format (ogg).

**Comment by MyHwu9508** [comment]
Try using https://howlerjs.com/

**Comment by cuBeUrg** [comment]
> Try using https://howlerjs.com/

It doesn't work with audio streams.

**Comment by cuBeUrg** [comment]
> You have to use a none licensed audio/video format (ogg).

Then why do some mp3 streams work then in CEF?

**Comment by deluvas1911** [comment]
It depends on the encoding the mp3 uses. As the shipped CEF doesn’t include proprietary codecs the amount of compatible encodings is limited

**Comment by cuBeUrg** [comment]
> It depends on the encoding the mp3 uses. As the shipped CEF doesn’t include proprietary codecs the amount of compatible encodings is limited

As far as I know CEF can be built using `proprietary_codecs=true` to allow them.

**Comment by yannbcf** [comment]
Because alt:V doesn't have licenses to do so

**Comment by MyHwu9508** [comment]
> > Try using https://howlerjs.com/
> 
> It doesn't work with audio streams. (panning, spatial audio, effects, etc.)

It's working using howler.js
Ive ran my own custom radio script with mp3 streams without any issue xD

Write me on Discord and I'll send you the resource
Kaniggel#6969
