### ISSUE TITLE
Weapon dlc addon crashes the game on connect to the server

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1747]
### Description of the problem

Weapon dlc addon is broken after latest gta update

### Reproduction steps

https://github.com/altmp/altv-example-resources/tree/master/weapon-addon

### Expected behaviour

/

### Operating system

Windows 11

### Version

14.0-dev4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Was confirmed by zziger and other people

**Comment by PlumeDreams** [comment]
confirmed,It is suspected that there is a problem with the loading of the weapon_info file.

**Comment by cRiZZlyy-CR** [comment]
can confirm it too.

**Comment by brainfire-rp** [comment]
Even on gta weapon info files aiminginfos is empty. eg weapon_candycane.meta of mpchristmas3 dlc.
Even on adding an amining info and replacing the UNARMED_TARGETING_RESTRAINTS the game still crashes for me

**Comment by xxshady** [comment]
I have checked and yes, it is the same 

`weapon_candycane.meta`
<img src="https://user-images.githubusercontent.com/54737754/221354667-52d3b3aa-80fe-4510-a700-6e5e430458a2.png" width="250px">

`weaponinfinityblade.meta` (custom addon)
<img src="https://user-images.githubusercontent.com/54737754/221354679-6171ad24-5cc3-40f2-b7b6-b96c8320dc00.png" width="250px">

**Comment by vanlueckn** [comment]
Can confirm this

**Comment by C0kkie** [comment]
Fixed in upcoming dev
