### ISSUE TITLE
Entity models are not freed from memory

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1749]
### Description of the problem

Loading too many entity models, spawning entities and destroying (so the models are not in use) breaks the game. I tried a similar code on ragemp, and the situation is much better there:

ragemp (max 8.2gb):

<img src="https://user-images.githubusercontent.com/54737754/212174005-e4a3f853-0f48-47b1-ab22-35235ed81fb0.png" width=350 />

altv (max is more than 9gb):

<img src="https://user-images.githubusercontent.com/54737754/212174223-b5308748-5fd9-4c9c-8d82-f8d88d5be24c.png" width=350 />

And also thats how the game looks like after destroying entities (in my repro code its peds):

<img src="https://user-images.githubusercontent.com/54737754/212173815-95232136-1e72-4c5e-b473-e547e3ae3bba.png" width=400 />

### Reproduction steps

Load models and ped spawn one at a time (450 models in total)
https://pastebin.com/P259CSR6

### Expected behaviour

/

### Operating system

Windows 11

### Version

13.0-dev4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
I want to add that it's not a new problem, we noticed it on our server more than a year ago but we thought that the problem was in modded vehicles.

**Comment by xxshady** [comment]
As temp solution you can use [`alt.loadModelAsync`](https://xxshady.github.io/custom-altv-types/modules/_alt_client_.html#loadmodelasync) function to load models, as it frees memory correctly
```js
if (!native.isModelValid(modelHash)) throw new Error('invalid model')
alt.loadModelAsync(modelHash)
await alt.Utils.waitFor(() => native.hasModelLoaded(modelHash), 5000) // waiting until model is loaded
```

<img src="https://user-images.githubusercontent.com/54737754/212323671-9e61d781-328d-4c84-9827-5c50836bb2db.png" width=300 />

**Comment by toyerovsky** [comment]
We have just tested `alt.loadModelAsync` workaround and it causes periodic crashes to our players.

**Comment by b2soft** [comment]
Hello,
Any updates on this?

**Comment by FabianTerhorst** [comment]
loadModelAsync is behaving same as the internal used model loading in dev branch.
Also in dev you dont need model loading anymore because you can spawn vehicles and peds with altv apis clientside.

**Comment by xxshady** [comment]
Tested ped & vehicle models via new API in 15.0 (LocalPed & LocalVehicle classes) and it seems that model loading in them is performed correctly

**Comment by xxshady** [comment]
Tested objects, model un(loading) is also perfomed correctly for them as well
