### ISSUE TITLE
DLC dependency problems

### ISSUE THREAD

**Issue by 5pHiNxX** [altmp/altv-issues#1750]
### Description of the problem

let's say you have a dlc called dlc-a and a dlc called dlc-b that depends on dlc-a.

There are 3 Szenarios:

1. If you add dlc-a as a dependency to dlc-b (via resource.toml) and have the dlc-a in the resource list of the server.toml **AFTER** dlc-b, the following output occurres:
```
[14:47:20] Loading resource dlc-b
[14:47:20] Loading resource dlc-a
[14:47:21] Loaded resource dlc-a
[14:47:21] Loaded resource dlc-b
[14:47:21][Warning] Resource dlcs/dlc-a is already started
```
So as you can see, the dependant dlc-a is loaded when the server tries to load dlc-b and afterwards, the server tries to load dlc-a again because of it's entry in the server.toml.
So far so good, but when you stop the server it stops the dependant dlc-a right after dlc-b and then tries to stop dlc-a again because of its entry in the server.toml. At this point the shutdown is aborted and the server is not shut down correctly (the remaining resources stay loaded).

2. If you add dlc-a as a dependency to dlc-b (via resource.toml) and have the dlc-a in the resource list of the server.toml **BEFORE** dlc-b, there is no warning as dlc-a was started before dlc-b and therefore its dependencies are fulfilled.
So far so good, but when you stop the server it stops the dependant dlc-a right after dlc-b and then tries to stop dlc-a again because of its entry in the server.toml. At this point the shutdown is aborted and the server is not shut down correctly (the remaining resources stay loaded).

3. If you don't add dlc-a as a dependency to dlc-b and have the dlc-a in the resource list of the server.toml **BEFORE** dlc-b, everything works as expeted. Starting and stopping the server works without any errors.

### Reproduction steps

- Create a dlc
- create a second dlc
- put the first dlc as dependency in the second dlc
- add the second dlc **before** the first dlc in the server.toml
- start the server
- stop the server
- if the server stops the second dlc before the first dlc the shutdown will hang

### Expected behaviour

The server should load the dependencies before the dlc that has the dependencies and should recognize them as already loaded. On shutdown the server should unload the dependencies after the dlcs that have the dependencies and recognize them as already unloaded instead of trying to unload them again.

### Operating system

Windows 10

### Version

13.37 release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
We decided to not change load order when dependencies are changed to prevent cache invalidation and other breaking changes. Load order should be fully controlled from server.toml.

**Comment by LeonMrBonnie** [comment]
Heron read the issue wrong, but I fixed it anyway
