### ISSUE TITLE
`voiceInputVolume` sets volume in reverse

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1754]
### Description of the problem

Client console `voiceInputVolume [0-200]` command sets volume in reverse, same thing applies to input volume setting in alt:V main menu

![изображение](https://user-images.githubusercontent.com/54737754/214966240-3e2f51d5-a598-4135-8216-ac5d91a8c5d4.png)

### Reproduction steps

Use `voiceInputVolume 199` - silence
Use `voiceInputVolume 1` - ear rape

### Expected behaviour

/

### Operating system

Windows 11

### Version

14.0-dev8

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Ok nvm i'm dumb as fuck

**Comment by xxshady** [comment]
or not?

**Comment by C0kkie** [comment]
Fixed in v15
