### ISSUE TITLE
Drawmarker native

### ISSUE THREAD

**Issue by dzngusta** [altmp/altv-issues#1756]
### Description of the problem

The native drawmarker, in textureDict and textureName accepts only the string type, when using an undefined type, it gives a error, but it works within the game

### Reproduction steps

Create an alt.drawMarker with textureDict and textureName params undefined using Typescript

### Expected behaviour

Don't throw error when setting textureDict and textureName parameters to undefined

### Additional context

Error image: https://media.discordapp.net/attachments/1070157364298256415/1070157364914823209/image.png?width=720&height=114

### Operating system

Windows 11

### Version

Release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
have you tried 'null'?

**Comment by xxshady** [comment]
@FabianTerhorst it works with null or undefined, he means mistake in altv types

**Comment by TuK4z** [comment]
Same in C# clientside. It shows string type, but works only with null

**Comment by C0kkie** [comment]
Fixed in v14
