### ISSUE TITLE
alt.on not working as it should

### ISSUE THREAD

**Issue by Iamproplayer7** [altmp/altv-issues#1760]
### Description of the problem

We have listener usage at documentation: 
alt-server: on(listener: (eventName: string, ...args: any[]) => void): void

It's not working, no response.

### Reproduction steps

```js
alt.on((name, ...args) => {
    console.log(name, args)
    // this never will be called
})
```

### Expected behaviour

call that listener for iServerEvents

### Operating system

Windows 11

### Version

release/13.46

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
what do you mean by "iServerEvents"? playerConnect, playerDisconnect, etc?

**Comment by LeonMrBonnie** [comment]
Wrong repo, open issues related to JS module API in JS module next time.
Also, this is not an issue but intended behaviour, generic event handler does not catch built-in events.
