### ISSUE TITLE
RSS-Discord Messages are clickable by "Closing Game" view

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#1764]
### Description of the problem

If you press the "Exit" button at the bottom left or ALT+F4 and press "Yes" in the the UI, the browser will open with the Discord link of the message hidden behind the "Yes" key.

### Reproduction steps

Start the alt:V Client 
When the UI appears, then click the "Exit" button at the bottom left and then click "Yes".
The browser should now be open with the Discord message.

### Expected behaviour

That the browser does not open and the RSS feed is not clickable in the background

### Operating system

Windows 11

### Version

dev/14.0-dev34

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Its not just the rss, its the whole ui, which is a bug since a long time #702
