### ISSUE TITLE
player.GiveWeapon (Addon-Weapon) gives 2x the same Weapon

### ISSUE THREAD

**Issue by cRiZZlyy-CR** [altmp/altv-issues#1766]
### Description of the problem

Hello,

If you want to spawn a addon-weapon, you will get the same Weapon 2x in your Wheel.

### Reproduction steps

Drag & Drop a Addon-Weapon. Load the File.

Spawn a Weapon with:

player.giveWeapon + the Weapon Name

### Expected behaviour

You should get only 1 Weapon.

### Additional context

In a ColShape its Buggy too.

### Operating system

Windows 11, 64-Bit

### Version

Release Version / + Dev

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
This issue doesn't make any sense until #1747 is fixed

**Comment by cRiZZlyy-CR** [comment]
They are 2 different Issues, Your Issue is: For some People's Game is crashing while Loading one. This Issue: Is telling you, when you spawn one of the Addon Weapons, You getting 2x of them.

**Comment by C0kkie** [comment]
@cRiZZlyy-CR  check in newest dev please

**Comment by C0kkie** [comment]
Other servers & qa couldnt reproduce it, something is with your configs then fucked up
