### ISSUE TITLE
Link to website in lowercase

### ISSUE THREAD

**Issue by Pixel220** [altmp/altv-issues#1771]
### Description of the problem

If you specify a link to a website in server.toml and the link will have characters of different case, then in the launcher the link will always be displayed in lower case

### Reproduction steps

1) Specify the website link in a different register
2) View the website link in the launcher

### Expected behaviour

Wait fix))

### Operating system

Windows 11 22H2

### Version

release/13.48

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Pleased test it on dev branch.

**Comment by FabianTerhorst** [comment]
Should be fixed now.
