### ISSUE TITLE
Add player.Kill(); Function Server-Side

### ISSUE THREAD

**Issue by cRiZZlyy-CR** [altmp/altv-issues#1774]
### Description of the problem

Hello,

I want to request a new Function Names: player.Kill(); Because we dont have one currently and its important like: player.Spawn.

Example:

You can easily kill a Player with one Call on a Interaction where you want & you can Easily Spawn him again.

It would be useful. Thanks

### Desired solution for the problem

Add: player.Kill();

### Alternatives you considered

player..Health = 0

### Additional context

-

### Version

All

**Comment by C0kkie** [comment]
Where is the diffrence in using health = 0 and .kill ?
I dont see any reason tbh

**Comment by LeonMrBonnie** [comment]
You can make a PR in e.g. JS module to add it as a shorthand in the JS bindings, but this won't be added to core
