### ISSUE TITLE
light alt:v

### ISSUE THREAD

**Issue by simas727** [altmp/altv-issues#1780]
### Description of the problem

as a devaloper i would like to have louncher or version of alt:v to not load not necesary files want to speed up scripting because if error it takes much time to restart to see if error gone +

### Desired solution for the problem

light alt v

**Comment by Stuyk** [comment]
Navigate to your alt:V program folder. Open `altv.cfg`.

**Append the following line to the file:**
`debug = true`

**Like this:**
![](https://i.imgur.com/UZxCfiF.png)

**Then in your server.toml file for your server**
You can add `debug = true` there as well.

**Like this:**
![](https://user-images.githubusercontent.com/21284100/225484714-88eed165-0565-4ff6-9606-36730630d8ce.png)

Then after, you can press `F8` in-game type `reconnect` to rejoin your own server.
