### ISSUE TITLE
Cancel button crashes the client on reconnection

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1785]
### Description of the problem

crashdump: https://discord.com/channels/371265202378899476/1010953750174777385/1087464051396853790

### Reproduction steps

Try to connect to a non-existent server adress, wait for the reconnect button, press it, press cancel during reconnection.

### Expected behaviour

/

### Operating system

Windows 11

### Version

14.0-rc3

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should work in dev/15.0-dev154
