### ISSUE TITLE
Client crash with some Interiors

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1786]
### Description of the problem

If you try to use some maps, the game freezes when joining and becomes unusable. Even after a restart or clearing the cache, the problem persists.

### Reproduction steps

For example, add https://de.gta5-mods.com/maps/meetingpoint-remastered-christmas-normal-styled as resource and try to join.
(There are more maps, not just that one)

For me and friends, the client just freeze and wont respond again.

### Expected behaviour

The game shouldn't freeze

### Additional context

In dev59, for example, this map still worked. I have also tried others and there the problem is also present.

### Operating system

Win 11

### Version

14 rc & dev

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by deluvas1911** [comment]
Please zip your resource and attach it to the issue, the one I created works fine

**Comment by elrobtossohn** [comment]
> Please zip your resource and attach it to the issue, the one I created works fine
[mapping_legion_square.zip](https://github.com/altmp/altv-issues/files/11044934/mapping_legion_square.zip)

**Comment by elrobtossohn** [comment]
> > > Please zip your resource and attach it to the issue, the one I created works fine
> > > [mapping_legion_square.zip](https://github.com/altmp/altv-issues/files/11044934/mapping_legion_square.zip)
> 
> I can't reproduce it with this resource. The loading time is a bit long (9 seconds), but you spawn. The same behavior is with release for me
> 
> Tested with 14.0-rc4

Since the 14.0-rc4 also works for me again. I do not know what the problem was, but it now runs again, wherever the problem was.
