### ISSUE TITLE
Interior Proxies

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1787]
### Description of the problem

Now and then there is the case that the interior proxies do not work and thus players are not in the same interior from the ID and thus "flicker" again and again.

### Reproduction steps

Just add a interior proxy with a map that required one

### Expected behaviour

No flicker

### Operating system

Win 11

### Version

14 rc & dev

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
@elrobtossohn  Check if this issue got also solved for you

**Comment by C0kkie** [comment]
Since there is no response and nobody else complained i will close it
