### ISSUE TITLE
setMinimapComponentPosition doesn't work properly

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1793]
### Description of the problem

If you want to modify the `minimap` position with `alt.setMinimapComponentPosition`, you have to open the GTA V menu with `Esc` and close the menu to see the results.

### Reproduction steps

1. Modify `minimap` position via `alt.setMinimapComponentPosition`.
```js
alt.setMinimapComponentPosition('minimap', 'L', 'B', 0.811, -0.768, 0.150, 0.188888);
alt.setMinimapComponentPosition('minimap_mask', 'L', 'B', 0.8355, -0.738, 0.111, 0.159);
alt.setMinimapComponentPosition('minimap_blur', 'L', 'B', 0.7855, -0.748, 0.266, 0.237);
```
2. I have to open the GTA V menu with `Esc` in order to see the results.

### Expected behaviour

After using `alt.setMinimapComponentPosition`, changes should be applied without opening the GTA V main menu.

### Additional context

- https://github.com/altmp/altv-issues/issues/804
- https://github.com/citizenfx/fivem/blob/34069da52f788a6e21c7ae2e9fc6d84dda932abe/code/components/extra-natives-five/src/InterfaceExtraNatives.cpp#L187

### Operating system

Windows 10

### Version

dev/15.0-dev3

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
Normal GTA behaviour
(Same happens in FiveM too)

**Comment by mrgharabaghi** [comment]
Solution:
```js
import { setMinimapComponentPosition } from 'alt-client';
import { setBigmapActive } from 'natives';

setMinimapComponentPosition('minimap', 'L', 'B', 0.811, -0.768, 0.150, 0.188888);
setMinimapComponentPosition('minimap_mask', 'L', 'B', 0.8355, -0.738, 0.111, 0.159);
setMinimapComponentPosition('minimap_blur', 'L', 'B', 0.7855, -0.748, 0.266, 0.237);

setBigmapActive(true, false);
setBigmapActive(false, false);
```
