### ISSUE TITLE
Reconnect doesnt work post timeout

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#1799]
### Description of the problem

the reconnect button does not work if the server is offline when you connect for the first time. you have to go back to the menu with cancel. then everything works as intended.

### Reproduction steps

start altv. Connect to a recently connected server that is stopped. Wait for the timeout message. Start the server. Click "Reconnect".

### Expected behaviour

Should connect.

### Operating system

Debian 10 / Win 11

### Version

14.4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Can't reproduce
