### ISSUE TITLE
INVALID_CDN_URL

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1808]
### Description of the problem

When connecting to a server on the dev branch, you are disconnected with "INVALID_CDN_URL".

### Reproduction steps

Just set up a server with dev branch files

### Expected behaviour

You should be able to connect without the error

### Operating system

Ubuntu 22

### Version

15.0-dev50

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
@elrobtossohn can you check that you haven't enabled cdn in your server.toml

**Comment by litolax** [comment]
If you will have same error feel free to reopen this issue and provide us your server.toml file

**Comment by elrobtossohn** [comment]
> @elrobtossohn can you check that you haven't enabled cdn in your server.toml

Sorry for the late reply, i haven't enabled it. But it seems like that the issue was resolved with a update, i guess with 51 or 52 lol
