### ISSUE TITLE
Fresh client start make the first vehicle streamed float in the air

### ISSUE THREAD

**Issue by yannbcf** [altmp/altv-issues#1810]
### Description of the problem

.

### Reproduction steps

https://user-images.githubusercontent.com/54820465/233120143-ba7c48e2-d0ec-4212-8a03-0f7a8d243fc0.mp4

### Expected behaviour

.

### Operating system

Windows 11

### Version

15.0-dev52

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Fixed since a few dev updates
