### ISSUE TITLE
Server-side markers are not removed after reconnect

### ISSUE THREAD

**Issue by fengkee** [altmp/altv-issues#1813]
### Description of the problem

Server-side markers are not removed after using reconnect.

### Reproduction steps

Use reconnect after creating server-side marker.

### Expected behaviour

Markers should be removed after using reconnect.

### Operating system

Windows 10

### Version

15.0-dev56

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by fengkee** [comment]
@Doxoh no, for all players using Marker class on server-side.

**Comment by C0kkie** [comment]
Will be fixed in  dev/15.0-dev179
