### ISSUE TITLE
playerWeaponShoot event bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1814]
### Description of the problem

If you shoot one shot with the double barrel shotgun, the playerWeaponShoot event runs many times and freezes the client.
Log: https://pastebin.com/bK7HWaKT

### Reproduction steps

1. Add the client-side code: alt.on('playerWeaponShoot', function(weaponHash, totalAmmo, ammoInClip) {
    alt.log("playerWeaponShoot: totalAmmo: " + totalAmmo + " ammoInClip: " + ammoInClip)
});
2. player.giveWeapon(alt.hash('weapon_dbshotgun'), 10, true)
3. Let's fire the gun. -> RIP

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #14.17, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can not reproduced with the latest release 14.17 and the latest 15.0-dev56

**Comment by xxshady** [comment]
Cannot reproduce on latest dev
