### ISSUE TITLE
Event finish (end) event

### ISSUE THREAD

**Issue by bruhozaurus** [altmp/altv-issues#1816]
### Description of the problem

At the moment we have OnPlayerEvent, which is triggered when a player calls an event.

I think that an event like OnEventFinish / OnEventEnd(string eventName) on server-side will be really useful to protect events from executors, and make our code more safe overall.

### Desired solution for the problem

- Add OnEventFinish(string eventName) / OnEventEnd(string eventName).

### Alternatives you considered

At the moment one solution will be to create a dictionary that stores the name of the event when the player calls it, and then at the end of the called event, to remove it from the dictionary. However this would require to add extra lines of code to every event, and I don't know how good of an idea that is.

**Comment by FabianTerhorst** [comment]
This is already possible.
E.g. 
```csharp
Alt.OnPlayerEvent += (player, name, args) => {
};
```
