### ISSUE TITLE
Download speed bad report

### ISSUE THREAD

**Issue by csskroubledev** [altmp/altv-issues#1817]
### Description of the problem

The speed of resources downloading is showing wrong, it can say resources download at rate of 4**GB/s** which I think anyone knows is **not** possible for now.

### Reproduction steps

Join a server with resources that will download for longer than 10 seconds

### Expected behaviour

Download speed should be showing great (should be around 100MB/s for me)

### Additional context

![GTA5_LXwxRp8o2V](https://user-images.githubusercontent.com/61517520/233803397-f7129fc8-a4df-4d6d-9cce-2a1f42021357.png)

### Operating system

Windows 10.0.19045 Pro

### Version

release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by JustCup** [comment]
I do not think this is a bug, maybe the server you are accessing has a limited channel

**Comment by JustCup** [comment]
> What does limited channel have to do with download speed of 4GB/s, which is clearly wrong as my internet is around 110MB/s at max

How can you download faster if they give it to you slower?

**Comment by martonp96** [comment]
fixed in dev
