### ISSUE TITLE
Possibility to expand Game Texture budget / VRam 

### ISSUE THREAD

**Issue by einsmoka** [altmp/altv-issues#1823]
### Description of the problem

Stock GTA V has quite restrictive value of texture/asset VRAM budget limits as well as the amount of memory. This Limit is just over 1.5GiB.
The Problem is, when a server has a lot of players and has some modded vehicles, some MLOs, modded clothes and more. At a certain point the Graphics start to get blurry/muddy, only LODs of some spots load or the are and players around get invisible. This issue can also occur whit very optimized mods. 

When a player plays with Texture Quality set to "Very High" this Problem happens even faster. On few altV servers (atleast all on i've played so far) it is common that the players should set their Texture Quality to "Normal" or lower. 

Also some Graphic mods (exp. NVE) for SP use this so improve performance, maploading and more.
There are already some other mods that make it possible to edit the physical game budget to improve performance especially with mods.

It noticeable improves performance and Map loading especially for more modified servers and players with bigger graphic mods.

As an example:
With an 3090ti, 1080p, on max settings with NVE or QuantV it is not possible to play flawless without Textureloss on many parts of the map.

### Desired solution for the problem

It would be great to have the option to allow the game to use more resources.
Would be nice to have thios option, like FiveM, in the Graphics setting menu.

In addition it would be great for extended users to edit this value. (Like in the SP mod "Resource Adjuster" from zombieguy )
Where the user can edit the GPU Memory available with their systems spec/usage. 

1: For the easy method_
Gta menu -> Settings -> Graphics Setting -> [Extend Budget = Value]

2: For "extended" method:
Possibility to add a line in the altv.toml of `additionalGPUMemory = VALUE`

### Alternatives you considered

Some people already tried to make such modification compatible for altv.

The Server im working with, have already heavy optimized a lot of stuff. The issue is reduced, but unfortunately still occurring.

### Additional context

FiveM has this great feature since about 2021/22 and players profit from this a lot.
NVE also implemented this feature for its SingePlayer package.
The Mod im referring to is: https://www.gta5-mods.com/tools/resource-adjuster

I think with the upcoming feature of Ped-Sync could benefit of this Feature.

**Comment by C0kkie** [comment]
Its already implemented in dev and gets set automatically
