### ISSUE TITLE
Discord OAuth get more data

### ISSUE THREAD

**Issue by Ffrankys** [altmp/altv-issues#1824]
### Description of the problem

I use Discord OAuth because it provides a quick and easy way for a user to authenticate. However, i think it lacks some information that Discord could provide, such as the user's email address. It could also be great to get the servers the user is in or may automatically join a discord server (that is related to the altv server your authenticating for).

### Desired solution for the problem

Uhm, add the things i just mentioned lol
The user's email would be easy for you to implement, just change the scope to email. Maybe give the developer the ability to change the auth scope by themself, like add an parameter to `requestOAuth2Token`

### Alternatives you considered

- Getting the email from a form using CEF, but that isn't as fast and cool as Discord OAuth
- Using Stuyk's Discord Auth where you can choose the scope by yourself, but is not as easy and fast to implement as `requestOAuth2Token`

**Comment by FabianTerhorst** [comment]
Discord doesn't allow us to do that in the game sdk.
