### ISSUE TITLE
Clientside alt.Object.pos setter crashes the client

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1825]
### Description of the problem

Using prop.pos = new alt.Vector3(x,y,z) crashes the client.

This happens with clientside made alt.Object and serverside made alt.NetworkObject.
Changing model or rotation doesn't crash the client.

### Reproduction steps

Create a Serverside alt.NetworkObject or Clientside alt.Object and set the position clientside with the .pos setter

### Expected behaviour

Client shouldn't crash and the object should update the position, you know?

### Operating system

Windows

### Version

dev77

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed on the latest 15.0-dev77

**Comment by FabianTerhorst** [comment]
Fixed in 15.0-dev79
