### ISSUE TITLE
Add ability to force stream entities outside streaming range

### ISSUE THREAD

**Issue by b2soft** [altmp/altv-issues#1829]
### Description of the problem

Using the newest dev I'm trying to create an NPC car acting like a Taxi. Car is spawned at some distance from player and NPC ped drives it to player. When car is spawned inside streaming range task can be done easily, but when car and ped are spawned outside streaming range, driving task is not possible.
The other possible problem, if we have 2 distant (distance > 2* streamingRange) and not moving  players (A and B) and I want to spawn ped+vehicle to go from A to B, car and ped are spawned and NetOwner is player A. But when it goes outside, NetOwner is null, so npc car will never reach player B.

### Desired solution for the problem

A setter and/or flag to force Entity (e.g. vehicle, ped, object) to be streamed using the last NetOwner it was held by, until new NetOwner comes to a scene. Something like `vehicle.SetForceStream(true, PlayerA)`, or `vehicle.SetForceStreamLastOwner(true)`, or `SetStreamingDistanceIgnored(true)`, or other signature.

NetOwner transfer can be done automatically or manually:
- automatic will switch NetOwner as soon as there is new NetOwner in range;
- manual approach - fire event and implement transfer on server script side

### Alternatives you considered

For now there is a workaround:
1. Once object is out of streaming range spawn local ped/vehicle/etc on last NetOwner's machine
2. Synchronize positions until new NetOwner is in range
3. Once new NetOwner is here, change NetOwner server-side, destroy local ped/vehicle/etc

Other alternative is to increase Streaming range - overwhelming with small amount of players
Another alternative - do the full navigation simulation using serverside navmesh, implies recreating whole traffic and navigation stuff from scratch at server

### Additional context

Latest dev. ped sync, increased sync capability limit

### Version

dev/15.0-dev87

**Comment by martonp96** [comment]
What if the map collisions are not loaded outside the player's streaming range?

**Comment by yannbcf** [comment]
In that case you will still have to manually load the corresponding navmesh, that's not something that should be done within the alt:V core as it's a very specific behavior fitting your needs.

You can indeed read the navmeshes, get the node points and estimate where the taxi will be at a given time and update its position accordingly serverside

**Comment by b2soft** [comment]
Not really, @yannbcf 
I'm not about server-side navmesh to be loaded. I just want to keep the object streamed ignoring the streaming distance. And set this explicitly unless new NetOwner is in range.

**Comment by deluvas1911** [comment]
@yannbcf when I did tests with native spawned vehicles + peds it worked good, just had to take care the entity is frozen until it loaded
@martonp96 depending on how difficult it is to implement it we could maybe provide it as a "use at own risk" feature xd

**Comment by FabianTerhorst** [comment]
stuff like SetForceStream doesn't works with current architecture. only solution i can imagine is that you use a very high streaming distance for that specific vehicle which will be possible.

**Comment by yannbcf** [comment]
It would slow down the streamer tick processing for a feature that almost nobody will ever use, so I highly doubt it would be adopted

**Comment by b2soft** [comment]
@yannbcf I can't argue with that because it hasn't been measured yet, but I think in c++ boolean check is negligible. It can be further optimized, thus I don't know the internals of streaming code in altv, I can't be sure.

**Comment by FabianTerhorst** [comment]
but forcing that stream in for a specific player won't be added, not just because of performance but also because of useless complexity.
