### ISSUE TITLE
networkAddEntityToSynchronisedScene broken

### ISSUE THREAD

**Issue by Phill030** [altmp/altv-issues#1830]
### Description of the problem

(I know that `networkAddEntityToSynchronisedScene` is not synced but it is still fun to work in general with those natives. Sadly it doesn't work when adding entities to the scenes. Maybe it is possible for you to fix it somehow) 

So the scene should have a player putting a usb stick into the scanner and then grab the phone from the pocket. But instead of grabbing the phone when needed, it falls through when the scene starts. 

### Reproduction steps

[SynchronizedScene.txt](https://github.com/altmp/altv-issues/files/11376480/SynchronizedScene.txt) is a helper class to simplify working with Synchronized scenes.

```ts
const scannerModel = alt.hash("ch_prop_fingerprint_scanner_01d");
await alt.Utils.requestModel(scannerModel);

const phoneModel = alt.hash("ch_prop_ch_phone_ing_01a");
await alt.Utils.requestModel(phoneModel);

const dict = "anim_heist@hs3f@ig1_hack_keypad@male@";
await alt.Utils.requestAnimDict(dict);

const { x, y, z } = alt.Player.local.pos;

const spawnPos = native.getOffsetFromEntityInWorldCoords(alt.Player.local, 0.0, 1.0, 1.0);
const scanner = native.createObject(scannerModel, spawnPos.x, spawnPos.y, spawnPos.z, true, false, false);
// const phone = native.createObject(phoneModel, x,y,z, true, false, false);

native.setEntityHeading(scanner, native.getEntityHeading(alt.Player.local));

const scene = new SynchronizedScene(native.getEntityCoords(scanner, true), native.getEntityRotation(scanner, 2).z);
console.log(scene);
scene.addPed(alt.Player.local, dict, "action_var_01", 8, 8, 0, 0, 1000);
// scene.addEntity(phone, dict, "action_var_01_prop_phone_ing", 8, 8, 0);
scene.start();
```
If you run the code like this, it will work and play the animation infront of the terminal. If you uncomment the lines tho, it will spawn the phone but drops it instead of kinda freezing in the air until the player pulls it out in the animation. 

### Expected behaviour

The entity (phone) should be attached to the player since it is part of the SynchronizedScene (animation)

### Operating system

Windows 10

### Version

dev/15.0-dev102

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-issues/issues/1311#issuecomment-1666509185
Should solve it

**Comment by Phill030** [comment]
@C0kkie apparently the game crashes new when starting the scene
![image](https://github.com/altmp/altv-issues/assets/50775241/4f3c2b66-0d59-4eba-bbe9-d626e851a912)

**Comment by Phill030** [comment]
[client_08-08-2023_02-05-47.log](https://github.com/altmp/altv-issues/files/12285939/client_08-08-2023_02-05-47.log)

**Comment by Phill030** [comment]
It indeed works but only using alt.LocalObject instead of native.createObject (no problem ^^)

**Comment by FabianTerhorst** [comment]
you can't add none synchronized entities to a synced scene.

**Comment by Phill030** [comment]
How should I do it then? 🤔 The phone instantly drops to the ground
