### ISSUE TITLE
Marker "rotate"

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1834]
### Description of the problem

In the native "drawMarker" is the parameter "rotate", it would let the marker rotate itself

### Desired solution for the problem

Add "rotate" field to alt.Marker

### Version

dev/15.0-dev117

**Comment by FabianTerhorst** [comment]
isnt .rot what you want to use?

**Comment by C0kkie** [comment]
No @FabianTerhorst 
What he means is already implemented with the `faceCamera` method

**Comment by elrobtossohn** [comment]
> No @FabianTerhorst What he means is already implemented with the `faceCamera` method

No @C0kkie, i mean the `rotate` parameter at `drawMarker` which makes it rotate.
https://natives.altv.mp/#/0x28477EC23D892089

`faceCamera` is not the same like `rotate`

> isnt .rot what you want to use?

No @FabianTerhorst, `rot` is a Vector not a boolean, the `rotate` would let rotate it completely self

**Comment by elrobtossohn** [comment]
nah @C0kkie `rotate` rotates the marker without the camera moving, for example.
I'm not at home right now or I would show you this, in case who else from the team or so doesn't even look at it.

I opened the issue because I am very sure about it, because it has another effect on the marker.

**Comment by Revyn112** [comment]
There should also be "bobUpDown" implemented.

**Comment by C0kkie** [comment]
bobupanddown & rotate added in dev/15.0-dev182
