### ISSUE TITLE
Custom MLO doesn't load

### ISSUE THREAD

**Issue by Sv1ne** [altmp/altv-issues#1836]
### Description of the problem

Custom MLO doesn't load

### Reproduction steps

-

### Expected behaviour

Custom MLO to be work

### Operating system

Client: Windows 10, Server Ubuntu 20.04

### Version

alt:V build #15.0-dev124, branch dev

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Please provide more informations and maybe a example. Cuz mlos just works fine

**Comment by C0kkie** [comment]
Fixed in upcoming dev
