### ISSUE TITLE
[DEV] C# Client not working anymore

### ISSUE THREAD

**Issue by Eager31** [altmp/altv-issues#1837]
### Description of the problem

The C# client version is not working anymore in dev version:

Client console gives :
![image](https://github.com/altmp/altv-issues/assets/32385860/5216f082-f663-459b-a704-fd9537d47b20)

### Reproduction steps

 alt:V Server 15.0-dev124 (dev)
 C# : 
<Project Sdk="AltV.Net.Sdk.Client/15.0.45-dev">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AltV.Net.CApi" Version="15.0.45-dev " />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VicePoint.Shared\VicePoint.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="AltV.Net.Client.Async" Version="15.0.45-dev " />
    </ItemGroup>

</Project>

### Expected behaviour

Clientside C# to work

### Operating system

Windows server

### Version

alt:V Server 15.0-dev124 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
Dev is currently being worked on a lot and is pretty unstable, so this is something that is expected.
