### ISSUE TITLE
Weird IVehicle.ManualEngineControl & IVehicle.EngineOn behaviour

### ISSUE THREAD

**Issue by grtiernan** [altmp/altv-issues#184]
## Expected Behavior
When setting ManualEngineControl to true, I expect that when entering the vehicle that the engine should not turn on by default. As well as this I would expect that whilst driving and shutting off the engine it would not auto-start back up.

## Current Behavior
Currently when setting ManualEngineControl to true, it functions about half as expected. Right now, I can only seem to get it to work from when I first enter a vehicle and start the engine. Then if I drive somewhere and stop, and then stop the engine, it works as intended.

However, it seems that while the vehicle is moving and you stop the engine, you can bug it out and the player will auto-start the engine. At this point, the whole ManualEngineControl becomes obsolete, and will no longer function correctly at all. Getting out and back into the vehicle then, it will not work as it did the first time around and will auto-start the engine. At this point it also starts to mess with EngineOn, and sometimes in my script, pressing the toggle when the engine is already on, will say it's turning it on again, and same with the off bit. So the EngineOn getter seems to bug out and return me a false value.

In my script, I use the 'J' key to send to a function server-side which toggles the vehicles engine. I have no reason to believe that there is anything of fault on my end.

## Possible Solution
From my testing of the issue, it seems that the root cause is stopping the engine whilst the vehicle is already moving and instead of it slowing down and coming to a complete stop, it decides to auto-turn back on and ignore the ManualEngineControl setting.

## Steps to Reproduce
1. Create a vehicle and set ManualEngineControl to true, and EngineOn to false for that vehicle.
2. Get into the vehicle, and start the engine, using a key or command or whatever you can set it up to. You will see that is works as intended, come to a stop and toggle it again, works.
3. Start it back up, get moving and stop it while the vehicle is somewhat moving, try using keys like W as well which in default GTA makes the player try turn the engine on. Pretty sure it's automatic anyways.
4. At this point you 'should' have noticed that the player begins to start the engine, despite what ManualEngineControl is set to.

## Context (Environment)
I'm trying to achieve a system where the player has to manually turn on/off their vehicle engine. This would heavily tie into other aspects of vehicles on my server, such as fuel and other players not being able to just hop in and auto-start without having keys to the vehicle.

Figured I would post a report about it, to see if anyone has experienced it or if anyone has any workarounds to the issue. I will continue to experiment with vehicle engines and update when I have more information.

**Comment by FabianTerhorst** [comment]
Tuxick recommends to use setPedConfigFlag with flag 429 instead of manual engine control.

**Comment by tastydev** [comment]
on #1239 rc manualEngineControl behaves like it should without the ped flag but it is still not preventing the gameengine from turning off the vehicle on pedVehicleLeave so engineOn and gamestate is again out of sync

**Comment by FabianTerhorst** [comment]
Does the Serverside engineon getter returns the wrong value then? @tastydev

**Comment by tastydev** [comment]
checked again the getter returns the right value, so literally the engine gets turned off by the game on every veh leave while engineon was not set to false

**Comment by tastydev** [comment]
Investigated this more:

1. turn vehicle engine on
2. speed up to 50mph
3. turn vehicle engine off while not holding key "w" down anymore and let the vehicle roll
4. press key "w" mutiple times while rolling on the street
5. engine will automatically restart and will bug in true state (engine can´t be turned off anymore)

**Comment by C0kkie** [comment]
Will  behandled here: https://github.com/altmp/altv-issues/issues/737
