### ISSUE TITLE
[C#] Crash on "large" collection emit

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1845]
### Description of the problem

If I emit a list with objects, where the objects have many values, then the server crashes directly with "1240678 Segmentation fault (core dumped) ./altv-server". But this is only since some version so. With the "15.0-dev17" for example everything still went without problems, so something must have been changed.

When i emit the list as a json the server wont crash.

### Reproduction steps

I would say just emit larger objects.
For me it really only happens with larger objects and only in collections.

### Expected behaviour

The server shouldn't crash.

### Additional context

my object as json: https://gist.github.com/elrobtossohn/eb550dd548e88773710cf056950834a9

### Operating system

Ubuntu 22

### Version

15.0-dev135

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Can you try to reproduce it on latest dev version? I tried on wsl but didnt get crash.

**Comment by elrobtossohn** [comment]
as soon as the c# module is updated, i could try yea

**Comment by elrobtossohn** [comment]
> > as soon as the c# module is updated, i could try yea
> 
> Update is there. pls test again

still getting a crash and i dont really understand why, it's happen only when i emit the collection with my data

**Comment by elrobtossohn** [comment]
yea, https://gist.github.com/elrobtossohn/a07fc1268607639ee8a49e0f257f3431

**Comment by elrobtossohn** [comment]
Have you been able to see if you could reproduce it? I still have crashes even with the latest version and can't explain why. @Doxoh

**Comment by elrobtossohn** [comment]
seems like it's fixed
