### ISSUE TITLE
Ladder sync is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1847]
### Description of the problem

Synchronisation of the ladder climbing animation is broken

### Reproduction steps

Climb a ladder

### Expected behaviour

Animation must be synced correctly

### Operating system

Windows 11

### Version

dev/15.0-dev143 & release 14.20

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Fixed in dev/15.0-dev177

**Comment by yannbcf** [comment]
Climbing down while sliding cause sync issue

**Comment by xxshady** [comment]
Fixed, climb up, climb down, fast slide down
