### ISSUE TITLE
Mainmenu & Pop outs are laggy

### ISSUE THREAD

**Issue by cRiZZlyy-CR** [altmp/altv-issues#1848]
### Description of the problem

Dev Launcher is capped on 20 FPS. Menu is lagging, not smooth, Pop Outs are laggy

Dev Launcher with 20 FPS:
![image](https://github.com/altmp/altv-issues/assets/91555896/8d694aab-d7e0-4319-8030-c5dc5849944e)

Release Launcher with uncapped FPS & No Laggs:
![Screenshot 2023-05-18 173037](https://github.com/altmp/altv-issues/assets/91555896/09314d38-6af7-4cf3-b668-17ae55bf4d6b)

### Reproduction steps

Start alt:V Launcher & Test it

### Expected behaviour

Uncapped FPS, Smooth Interface

### Operating system

Windows 11

### Version

Dev Launcher

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Will be fixed in dev/15.0-dev157
