### ISSUE TITLE
Add support for media autoplay

### ISSUE THREAD

**Issue by rsxdalv** [altmp/altv-issues#185]
**Is your feature request related to a problem? Please describe.**
Chromium disallows automatic media playback; however, since the server admin is already in control, he shouldn't have to jump through hoops to play audio from CEF.

**Describe the solution you'd like**
Bundled CEF compiled with flag --autoplay-policy=no-user-gesture-required

**Describe alternatives you've considered**
No alternatives

**Additional context**
NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

**Comment by Lekenthun** [comment]
++

**Comment by iamfronty** [comment]
afaik videos can be autoplayed when `<video>` tag has the `muted ` attribute

**Comment by FabianTerhorst** [comment]
The flag got added long time ago.
