### ISSUE TITLE
Keyboard layout changes itself when game window is in focus

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1851]
### Description of the problem

![5-20-2023 (19-42-26)](https://github.com/altmp/altv-issues/assets/54737754/d1a46641-11ff-4c19-8801-d817c1e47f0e)

### Reproduction steps

1. Two keyboard layouts, in my case RUS & ENG.
2. Focus game window
3. Press alt+shift 
4. Layout changes back

### Expected behaviour

/

### Additional context

The first time i noticed it was May 5, 2023.
It doesnt happen on release branch.

### Operating system

Windows 11

### Version

15.0-dev162

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can reproduce with the latest dev 15.0-dev175

**Comment by zziger** [comment]
Fixed in 15.0-dev378
