### ISSUE TITLE
Client crash on connect

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1856]
### Description of the problem

Client crashes when connecting to the server.
It started happening recently, ~a week or so ago (it does not happen on release branch).
First time i noticed it on May 25: https://discord.com/channels/371265202378899476/1010953750174777385/1111345075709030493

### Reproduction steps

**Make sure your game is in fullscreen mode before you start alt:V client**
1. Start alt:V
2. After the main menu appears press alt+enter
3. Connect to server
4. Crash

### Expected behaviour

/

### Additional context

/

### Operating system

Windows 11

### Version

15.0-dev231

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Atm looks like amd gpu related.

**Comment by C0kkie** [comment]
Fixed in dev/15.0-dev236
