### ISSUE TITLE
GetEntitiesInRange support for different entity types

### ISSUE THREAD

**Issue by b2soft** [altmp/altv-issues#1858]
### Description of the problem

As being stated by altv team, this method works only with Players and Vehicles now.
Requesting support for other server-side Peds and NetworkObjects..
Changes required in altv core.
```
IBaseObject[] pedEntitiesInRange = Alt.Core.GetEntitiesInRange(trackedPlayer.Position, 400, 0, EntityType.Ped);
// pedEntitiesInRange.Length is 0
```

```[tasklist]
### Tasks
- [ ] Add Ped support
- [ ] Add NetworkObject support
```

### Desired solution for the problem

To implement missing entity types

### Alternatives you considered

Use  Alt.GetAll* methods + distance check, track spawned entities myself and provide some spatial partition to quickly find entities around

### Version

15.0-dev179

**Comment by FabianTerhorst** [comment]
blips wont be supported by this method.
Peds and Objects are planned.

**Comment by b2soft** [comment]
> blips wont be supported by this method. Peds and Objects are planned.

Updated description

**Comment by FabianTerhorst** [comment]
Added in dev/15.0-dev603
