### ISSUE TITLE
reconnect if vehicle in range

### ISSUE THREAD

**Issue by ClutchFred** [altmp/altv-issues#1861]
### Description of the problem

current build of dev branch (208) crashes if vehicles are in range before reconnect. if you leave streaming range before reconnect it works just fine

### Reproduction steps

reconnect in streaming range of any vehicle 

### Expected behaviour

no crash after on reconnect as its annoying for developing (i know its the dev branch but it should be investigated so it doesnt occurs in release versions)

### Operating system

Windows 11

### Version

dev/15.0-dev208

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by vanlueckn** [comment]
I can confirm this behaviour in dev208

**Comment by deluvas1911** [comment]
confirmed on 208

**Comment by JohnnyMarconi** [comment]
I can confirm this behaviour in dev211

**Comment by C0kkie** [comment]
@vanlueckn @ClutchFred Is this still a thing?

**Comment by ClutchFred** [comment]
i will do some testing tomorrow

**Comment by C0kkie** [comment]
alright thanks @ClutchFred

**Comment by C0kkie** [comment]
Alright thanks for your confirmation @ClutchFred
