### ISSUE TITLE
Set AudioFilter to player voice output

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#1866]
### Description of the problem

At the current state, you only can apply AudioFilters to a voice canal. Which makes sense of the usage of radio communication etc.

I'm just missing the method to set filters to a single player in the current active voice channel they are talking.

### Desired solution for the problem

Add

const audioFilter = new alt.AudioFilter("Whatever");
audioFilter.addDistortionEffect(1,0,0,0,0,1);

player.audioFilter =  audioFilter;

functionality.

### Alternatives you considered

-

### Additional context

-

### Version

dev227

**Comment by C0kkie** [comment]
Added in dev/15.0-dev415
