### ISSUE TITLE
`enteredVehicle` wrong seat

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1867]
### Description of the problem

If you use `alt.on('enteredVehicle', (vehicle, seat))` the seat from the driver should be 1 and not 0, at least it was like that before "some" updates but not anymore.

And when you enter a vehicle in the log appears "Seat shit enter 0000000014684BC0 0"

### Reproduction steps

```
alt.on('enteredVehicle', (vehicle: alt.Vehicle, seat: number) => {
      alt.log(`Entered vehicle on seat ${seat}`)
})
```

### Expected behaviour

The driver's seat should be 1 and for the other seats then each higher

### Operating system

Win 11

### Version

dev/15.0-dev227

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should be fixed in dev/15.0-dev230
