### ISSUE TITLE
Move 'ignoreLowPriorityProps' to server config

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv-issues#187]
**Is your feature request related to a problem? Please describe.**
Having the config setting '**ignoreLowPriorityProps**' clientside can cause desyncs and unfair advantages if set to 'true' on one client and 'false' on another.
There are not only small cosmetic props that are affected by this setting but also things like boxes (crates), benches, etc. that will be affected by this, so having one player seeing it and another doesn't will cause problems.

**Describe the solution you'd like**
Move the 'ignoreLowPriorityProps' setting to the serverside config and remove it from clientside.

**Describe alternatives you've considered**
Having a clientside or serverside method (like "**boolean ignoreLowPriorityPropsEnabled()**") to check whether this setting is enabled or disabled (to give server developers the possibility to kick the players that have a wrong setting to avoid such issues).

**Comment by vadzz-dev** [comment]
i think it could be just removed

**Comment by datWeazel** [comment]
Remove and make it default to ignore the low priority props or make it default to not ignore them?

**Comment by FabianTerhorst** [comment]
Remove it and make it default to show all props.

**Comment by martonp96** [comment]
This was removed.
