### ISSUE TITLE
Add .Has() to Alt.LocalStorage

### ISSUE THREAD

**Issue by litolax** [altmp/altv-issues#1870]
### Description of the problem

Now we haven't possibility to check if key exists in localstorage without try to get value

### Desired solution for the problem

```csharp
Alt.LocalStorage.Has(key)
```

### Alternatives you considered

Now we have only
```csharp
var result = Alt.LocalStorage.Get(key, value);
``` 

### Version

15.0-dev227 (dev)

**Comment by FabianTerhorst** [comment]
Added in next build.

**Comment by litolax** [comment]
<3
