### ISSUE TITLE
New GTA vehicles disabled

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1873]
### Description of the problem

In an update to the release branch, all new GTA vehicles have been disabled. These vehicles did not have any problems, only some cars have next-gen console tuning available, so they should just be disabled.

### Reproduction steps

-

### Expected behaviour

I want these vehicles back.

### Operating system

Windows 11

### Version

alt:V build #14.29, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Its not disabed anymore
