### ISSUE TITLE
Streaming Distance per Entity in v15

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#1878]
### Description of the problem

Currently there is a global streaming distance for every entity. So you cant seperate e.g. items on ground and vehicles. But there is no need to stream items, markers etc as far as vehicles or players.

### Desired solution for the problem

A nullable streamingRange property would do the trick. It defaults to null and would then just use the value specified in server.toml

**Comment by C0kkie** [comment]
added in v15
