### ISSUE TITLE
WebView reload() crashes the client

### ISSUE THREAD

**Issue by katsutosh** [altmp/altv-issues#1884]
### Description of the problem

WebView.reload() crashes the client

### Reproduction steps

Create a Webview and call reload()

```js
const mainView = new alt.WebView('https://google.de')
mainView.reload()
```

### Expected behaviour

The WebView reloads and doesn't crash the client

### Operating system

Windows 10

### Version

dev/15.0-dev308

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Confirmed on 15.0-dev360

**Comment by xxshady** [comment]
[crashdump.zip](https://github.com/altmp/altv-issues/files/12061995/crashdump.zip)

**Comment by C0kkie** [comment]
@katsutosh Test on newest dev, if it still crashes, reopen the issue
