### ISSUE TITLE
Clientside Blips broken

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1886]
### Description of the problem

Blip names are not displayed in the map overview and the position is always 0, 0, 0

### Reproduction steps

```javascript
const blip = new alt.PointBlip(alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z)
blip.sprite = 1;
blip.name = 'Test'
```

### Expected behaviour

Blips should have a name when viewing the map and at the correct position

### Operating system

Win11

### Version

15.0-dev316

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
You need to Update your Server to save Version as Client.

**Comment by elrobtossohn** [comment]
What you mean with "save" ?

**Comment by FabianTerhorst** [comment]
I mean "Same"

**Comment by FabianTerhorst** [comment]
Every Dev build needs a Server Update.

**Comment by elrobtossohn** [comment]
Both are on the same version, the thing is that the problem is more on the client side with the blips and not on the server side

**Comment by xxshady** [comment]
Confirmed on 15.0-dev321

**Comment by C0kkie** [comment]
Should work in newest dev

**Comment by C0kkie** [comment]
Note: client works, server not

**Comment by C0kkie** [comment]
Works now
