### ISSUE TITLE
Client crashes when entered a VirtualEntity streaming range

### ISSUE THREAD

**Issue by enisn** [altmp/altv-issues#1887]
### Description of the problem

When player enters in a VirtualEntity streaming range, the client crashes immediately without any logs. It was working well in previous version.

I created virtual entities with C#, maybe it can be working with JS module.

Runtime Version: `232677e`
SDK Version: `f56bb0d`
NuGet Version: `15.0.110-dev`
Server version: `15.0-dev330`

### Reproduction steps

1. Create a C# resource
2. Create VirtualEntityGroup and create a VirtualEntity
3. Run & connect the server
4. Go to the virtual entity position with player.
5. And crashes

### Expected behaviour

It should be working without any crash

### Operating system

Windows

### Version

15.0-dev330

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by TuK4z** [comment]
I have same issue with c#. I create IVirtualEntity serverside or INetworkObject serverside and client instant crash, no errors in my case. Same if it's created already and enter streaming range.

**Comment by enisn** [comment]
> C# client right or c# server

It happens when VirtualEntity is created in server-side

**Comment by enisn** [comment]
> I have same issue with c#. I create IVirtualEntity serverside and client instant crash, no errors in my case. Same if it's created already and enter streaming range.
> 
> You can get crash by just spawning near you:
> 
> ```
> Dictionary<string, object> objData2 = new(){
>     {"GroupId", "2"}
> };
> IVirtualEntity a = Alt.CreateVirtualEntity(Resursas.ObjectGroup, player.Position, 20, objData2);
> ```

Yeah, same here, when I create later at my player position, the client immediately crashes too. No logs

**Comment by enisn** [comment]
It seems solved in `15.0-dev338` ✅
