### ISSUE TITLE
[C#][15.0-dev332] Server | OnConnectionQueueAdd & OnConnectionQueueRemove

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#1888]
### Description of the problem

`OnConnectionQueueAdd` and `OnConnectionQueueRemove ` throws a error in the Server Log.

```
OnConnectionQueueAdd Invalid connectionInfo 2850246277424
OnConnectionQueueRemove Invalid connectionInfo 2850246277424
```

### Reproduction steps

1. Using this code:
```c#
        private async Task OnConnectionQueueAdd(IConnectionInfo connectionInfo)
        {
                Console.WriteLine("Accepted client");
                connectionInfo.Accept();
        }

        private Task OnConnectionQueueRemove(IConnectionInfo _)
        {
            Console.WriteLine("Player removed from the queue, even if I accept the connection now it's handled!");
            return Task.CompletedTask;
        }

        public override void OnStart()
        {
            AltAsync.OnConnectionQueueAdd += OnConnectionQueueAdd;
            AltAsync.OnConnectionQueueRemove += OnConnectionQueueRemove;
        }
```
1. Add ConnectionQueue to server.toml
`connectionQueue = true`
1. Start Server
1. Connect with latest fresh installed dev client to server
1. Getting above logs, functions will not executed.

### Expected behaviour

ConnectionInformation shouldn't be invalid and functions should be executed.

### Operating system

Windows 11

### Version

15.0-dev332

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Open the issue in c# module. not a altv issue.
