### ISSUE TITLE
Launcher resets desktop

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1893]
### Description of the problem

In the "Loading alt:V client" stage, my desktop reset (flickering) just like when you want to change the monitor resolution, and all of my folders close in the "Windows Explorer".

+Night Light settings reset.
+Tray icons disappears.

### Reproduction steps

1. Open the launcher.
2. Desktop will reset in the "Loading alt:V client" stage.

### Expected behaviour

Should not reset the Windows 10 desktop.

### Additional context

This bug not happen when I launch GTA V offline mode.

### Operating system

Windows 10

### Version

dev/15.0-dev344

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Can't confirm this on either Windows 10 nor Windows 11

**Comment by mrgharabaghi** [comment]
Disabling third-party services in Windows 10, and updating the NVIDIA driver didn't solve the problem.

**Comment by litolax** [comment]
Can confirm with the latest dev and will be fixed soon
