### ISSUE TITLE
native.displayOnscreenKeyboard doesnt work after gta update

### ISSUE THREAD

**Issue by PrisonIndustry** [altmp/altv-issues#1894]
### Description of the problem

Hello, 

after the last altv update i can not use native.displayOnscreenKeyboard and native.updateOnScreenKeyboard.  

### Reproduction steps

native.displayOnscreenKeyboard(1, "Test:", "", "", "", "", "", 50);
        const waitkey = alt.everyTick(() => {
       if (native.updateOnscreenKeyboard() == 0) {
          // alt.log("warte")
       } if (native.updateOnscreenKeyboard() == 1) {
        alt.log(native.getOnscreenKeyboardResult())
        nameitem.Text = native.getOnscreenKeyboardResult()
          
          
           alt.log(native.getOnscreenKeyboardResult())
           
          
           alt.clearEveryTick(waitkey)
       }
   })

### Expected behaviour

If open a text field like gtao

### Operating system

Windows qq

### Version

Rel. 14.0

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
https://github.com/altmp/altv-issues/issues/1879
