### ISSUE TITLE
OnScreen Keyboard Native Broken Again

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#1897]
### Description of the problem

Recently the on screen keyboard built in to GTA:V broke again.

Some additional information:
- scaleform loads if you call the scaleform directly
- calling scaleform, and then invoking natives doesn't resolve it

### Reproduction steps

```ts
function showInputBox(title: string = "", text: string = "", maxLength: number = 100): string {
    return new Promise((resolve) => {
        alt.addGxtText("INPUT_BOX_CUSTOM_TITLE", title);
        native.displayOnscreenKeyboard(0, "INPUT_BOX_CUSTOM_TITLE", "", text, "", "", "", maxLength);

        let tick = alt.everyTick(() => {
            let state = native.updateOnscreenKeyboard();
            if(state === 0) return;
            let result = native.getOnscreenKeyboardResult();
            native.forceCloseTextInputBox();
            alt.clearEveryTick(tick);
            resolve(result);
        });
    });
}
```

### Expected behaviour

Works with the above code again.

### Additional context

Bunch of people in Discord have been talking about it but nobody knows how to make a god damn bug ticket.

### Operating system

Windows 10

### Version

latest

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
#1879

**Comment by FabianTerhorst** [comment]
its a feature request, not a bug report.so no duplicate.

**Comment by FabianTerhorst** [comment]
ah nvm that was not the issue with the new suggested feature.
