### ISSUE TITLE
Blip route is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1900]
### Description of the problem

![изображение](https://github.com/altmp/altv-issues/assets/54737754/82162fd7-bb91-4b79-a91d-21bee36cb4fb)

### Reproduction steps

```js
const blip = new alt.PointBlip(0, 0, 0)
blip.route = true
blip.routeColor = alt.RGBA.red
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev349

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by enisn** [comment]
Same here, route isn't drawn to blip

**Comment by xxshady** [comment]
@chaosfreak93 works fine on latest dev, did you check it in vehicle?

**Comment by chaosfreak93** [comment]
Found my problem, routeColor is RGBA but past only an int. Some it is invisible then.

**Comment by HorstA380** [comment]
Where to find what route color is set?
I use the same blip function and think they are invisible too.
