### ISSUE TITLE
Ctrl+v doesn't work in direct connect menu

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1901]
### Description of the problem

See title

### Reproduction steps

Press ctrl+v in direct connect menu 

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev351

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed with the latest dev351

**Comment by xxshady** [comment]
Seems like fixed
