### ISSUE TITLE
attach-Api boneids is only int16 instead of uint16

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#1902]
### Description of the problem

Currently you cant use the max number of possible boneids, cuz its only int16

### Reproduction steps

Use attach api and try bone 65245

### Expected behaviour

boneid 65245 should work

### Operating system

-

### Version

dev/15.0-dev351

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.
