### ISSUE TITLE
Disconnected player instance is not invalidated

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#1903]
### Description of the problem

In our case one player connected with what I assume was a troublesome older client version, when he disconnected his alt.Player instance was not destroyed/invalided properly and when we tried to kick out the player it would kick out a completely different player. As if his player.id was attached to another player. If any of the admins teleported to the bugged player then their client would crash and the admins player instance would still remain in the server glitched. It's really weird.

It could be due to the altv client updates that caused issues on the weekend, my suspicion is that a player connects with one of the troublesome client versions and in turn it causes issues with the newer server version.

If this is due to the troublesome client versions then it would be useful to get the full client version in alt.IConnectionInfo.build (14.58 instead of 14), so that we could prevent users from connecting with an older client version.

Else this could be a 14.58 server issue, because before updating altv server we we're running 14.47 and we had no issues.

Server logs don't show any errors/warnings associated with this. This happened yesterday, today we restarted the server and it happened again. This is also reported by other server owners in DC: https://discord.com/channels/371265202378899476/1128972173688709201

### Reproduction steps

1. Player connects to the server (presumably using an older client version?)
2. Spawns
3. Disconnects
4. Player instance is not invalidated

### Expected behaviour

Player instance should be invalidated on disconnect

### Operating system

Debian 11

### Version

release 14.58

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
In 14.59 disconnect should be called again also for clients that got disconnected because of attempted ddos attack.

**Comment by C0kkie** [comment]
Can you confirm this? @edgarasx

**Comment by edgarasx** [comment]
> Can you confirm this? @edgarasx 

I've just updated our server, we'll be watching if the issue persists, I'll let you know.

**Comment by C0kkie** [comment]
thanks @edgarasx

**Comment by FabianTerhorst** [comment]
Feel free to reopen it when you still notice a issue.
