### ISSUE TITLE
attachTo method teleports player to heaven

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1909]
### Description of the problem

https://youtu.be/uAwALWCACVE

### Reproduction steps

```js
const veh = alt.Vehicle.all[0]
alt.Utils.assert(veh)

player.detach()

await alt.Utils.wait(500)

// player.spawn(0, 0, 72, 0)
player.attachTo(veh, 0, 0, alt.Vector3.zero, alt.Vector3.zero, false, false)
```

### Expected behaviour

Attach to vehicle

### Operating system

Windows 11

### Version

15.0-dev359

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xenicle** [comment]
[bug-attachto.webm](https://github.com/altmp/altv-issues/assets/26338409/17e146a5-3316-40bd-a685-68ec5e6965a4)
Can confirm on my project with latest 15-DEV388 `player.attachTo(entity, ... )` make a flickering and don't attach...

**Comment by C0kkie** [comment]
@xenicle @xxshady  still the case?

**Comment by xxshady** [comment]
Seems like it's fixed
