### ISSUE TITLE
Add IVehicle.getTrailer method

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#191]
**Is your feature request related to a problem? Please describe.**
Getting the trailer that is currently attached to the vehicle.
**Describe the solution you'd like**
A method that returns the IVehicle.

**Comment by datWeazel** [comment]
`vehicle.trailer` as a property would fit better I guess. Should be null if there's no trailer attached.

**Comment by FabianTerhorst** [comment]
cpp api has no properties.

**Comment by je-schindler** [comment]
Maybe using a dynamic getter?

**Comment by FabianTerhorst** [comment]
This is not an issue for reinventing the whole cpp api.

**Comment by Zuiron** [comment]
we need this.

**Comment by je-schindler** [comment]
Any updates here?

**Comment by lameule123** [comment]
UP

**Comment by FabianTerhorst** [comment]
Implemented as .Attached .
