### ISSUE TITLE
Client-side event `leftVehicle` no longer triggers after reconnection

### ISSUE THREAD

**Issue by duydang2311** [altmp/altv-issues#1910]
### Description of the problem

Event `leftVehicle` triggers on first connection, but no longer works after `reconnect`.

### Reproduction steps

1. Add an event handler for event `leftVehicle`.
```js
import alt from 'alt-client';

alt.on('leftVehicle', () => {
	alt.log('leftVehicle');
});
```
2. Connect to the server, enter a vehicle, then leave. See a log says "leftVehicle" in the console.
3. Execute `reconnect` command in the console, re-do step 2, but there's no log.

### Expected behaviour

`leftVehicle` should work normally even after reconnection.

### Operating system

Arch Linux 20230625.0.160368

### Version

15.0-dev351

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Can't reproduce

**Comment by duydang2311** [comment]
I think the reproduction code was wrong, sorry for that.

Can you try this code instead? Reproducible on 15.0-dev360 for me.

```js
import alt from 'alt-client';

alt.once('leftVehicle', () => {
	alt.log('once');
});

alt.on('leftVehicle', () => {
	alt.log('on');
});
```

**Comment by xxshady** [comment]
still can't reproduce

**Comment by duydang2311** [comment]
That's strange, I've reproduced this a bunch of times on my side.

Anyway, I had to replace `once` with `on` in my code as a workaround. Seems like the issue has something to do with the behaviour of `once` removing its event handler after first trigger.
