### ISSUE TITLE
Blip color set not working

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1911]
### Description of the problem

Using c# serverside blips color not working in latest dev.

### Reproduction steps

1. Create blip
2. Set color

### Expected behaviour

Color to be set

### Additional context

![image](https://github.com/altmp/altv-issues/assets/40861802/b9bb572f-06d5-4d9f-9039-51ec2fc4a366)

### Operating system

Win11 and Ubuntu 22.04

### Version

15.0-dev365

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by enisn** [comment]
Same here on Windows server.

The bug first appeared in `15.0-dev362`

**Comment by enisn** [comment]
Seems latest client update solved the problem
