### ISSUE TITLE
Wrong alt.Audio typescript types

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1915]
### Description of the problem

Some methods of "Audio" have wrong argument types.
For `addOutput` the parameters and returns should be `AudioOutput` and not `Entity`
Same goes for `removeOutput` and `addOutput` in `alt.Audio`

### Reproduction steps

Just give a look at `@altv/types-client`

### Expected behaviour

Some arguments should be `AudioOutput`

### Operating system

Win11

### Version

15.0-dev368 (types: 2.7.8)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-types/commit/cabd98f56d594cd3421849a00d17b8df0fd2744c

if something else is missing, feel free to open a pr in the repo
