### ISSUE TITLE
LocalVehicle creation with invalid model crashes game

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1916]
### Description of the problem

/

### Reproduction steps

```js
new alt.LocalVehicle('awdawdawdwd', 0, alt.Player.local.pos.add(3, 0, 0), alt.Vector3.zero, false, 0)
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev373

### Crashdump ID

9e0d5832-c8d1-48dc-b24c-35a1be31fd76

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in next build.
