### ISSUE TITLE
Add IVehicle.attachedTo method

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#192]
**Is your feature request related to a problem? Please describe.**
A method to return the vehicle which the current vehicle (the trailer) is attached to.

**Describe the solution you'd like**
vehicle.attachedTo method to return vehicle the trailer is attached to.

**Comment by lameule123** [comment]
I pray everyday for this feature

**Comment by FabianTerhorst** [comment]
Implemented in dev branch.
