### ISSUE TITLE
Marker rot.z has no effect

### ISSUE THREAD

**Issue by yannbcf** [altmp/altv-issues#1929]
### Description of the problem

The alt implementation marker rotation z axis has no effect

### Reproduction steps

```ts
const marker = new alt.Marker(...);
marker.rot = new alt.Vector3(0, 0, 2);
```

### Expected behaviour

The marker should rotate on the z axis

### Operating system

Windows 11

### Version

dev/15.0-dev435

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
fixed in next dev build
