### ISSUE TITLE
C# - OnStreamSyncedMetaChange target is always null for objects

### ISSUE THREAD

**Issue by enisn** [altmp/altv-issues#1933]
### Description of the problem

When I create an object on server-side with `Alt.CreateObject()` and set a StreamSyncedMetaData, I can't handle in the `OnStreamSyncedMetaChange` event on client-side. Key and Value is correct but **target** object is null.

### Reproduction steps

1. Create object on server-side
    ```csharp
    var obj = Alt.CreateObject(
        "w_sb_smg",
        player.Position,
        Rotation.Zero);
    
    obj.Dimension = droppedItem.Dimension;
    
    obj.Frozen = true;
    obj.Collision = true;
    
    obj.SetData(droppedItem);
    
    obj.SetStreamSyncedMetaData("HintText", "MP5 (weapon)");
    ```

- Register the `OnStreamSyncedMetaChange` event on client-side
    ```csharp
    Alt.OnStreamSyncedMetaChange += Alt_OnStreamSyncedMetaChange;
    ```

- In the event method, key is correct, value is correct but **target** is null always.
    ```csharp
    private void Alt_OnStreamSyncedMetaChange(IBaseObject target, string key, object value, object oldValue)
    {
        if (key == "HintText") // 👈 Hits this if
        {
            // Throws NullReferenceException here because 'target' is null 👇
            Console.WriteLine("Hints object type: " + target.GetType().FullName);
            if (target is IEntity entity)
            {
                hintToRenderInRange.Add(entity, value.ToString());
            }
        }
    }
    ```

### Expected behaviour

`target` parameter should be a valid entity object that I can read the Position, Rotation etc.

### Operating system

Windows

### Version

15.0-dev460 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by enisn** [comment]
Bu the way, it works for rest of the entities such as IPed (players), IVehicle. It is null only for IObject

**Comment by C0kkie** [comment]
@enisn  did you test if its also in js the case?

**Comment by KiwisKiwi** [comment]
It's not a core problem, it's related to a missing object pool in c# client.

**Comment by C0kkie** [comment]
Should be fixed
