### ISSUE TITLE
Add useZ to VirtualEntity

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1934]
### Description of the problem

At this time if you enter the `streamingDistance` of a `VirtualEntity`, `z` coordinate ignored and this isn't good.
If you set meta on a `VirtualEntity`, data will be send when the player on sky.

### Desired solution for the problem

Just like `Ped` class.

### Alternatives you considered

Nothing.

### Additional context

```ts
public VirtualEntity(
    group: VirtualEntityGroup,
    position: Vector3,
    streamingDistance: number,
    useZ: boolean,
    data?: Record<string, any>
);
```

### Version

dev/15.0-dev443

**Comment by yannbcf** [comment]
It is done this way because it is faster to calculate it on 2 axis, I wonder if it really should be handled in core or at the gamemode level

**Comment by BluePeer** [comment]
? every streamed entity is based on 2d ignoring z
teach me other if there was a unknow change on that system

**Comment by mrgharabaghi** [comment]
> It is done this way because it is faster to calculate it on 2 axis, I wonder if it really should be handled in core or at the gamemode level

In the first step, it's only needs to calculate 2 axis, if player is in the `streamingDistance`, now check the `z` coordinate.
This is not a heavy calculation.

**Comment by FabianTerhorst** [comment]
Im not sure if this will ever happen, because its not needed in the gta map, but i will keep it open anyway. But personally i think adding that bool isn't worth the added complexity.

**Comment by mrgharabaghi** [comment]
@FabianTerhorst
Do you think this is complex?
```
StreamingDistance -> 10

Player Position -> { x: 5, y: 10, z: 7 }
VirtualEntity Position -> { x: 2, y: 3, z: 5 }

Result = Calculate 2 axis (x, y) here

if (Result == true) {
    if (useZ == true) {
        VerticalDistance = Player.z - VirtualEntity.z
        
        if (VerticalDistance < 0.0) {
            VerticalDistance = -VerticalDistance;
        }
        
        if (VerticalDistance < StreamingDistance) {
            The player is in the StreamingDistance
        } else {
            The player is NOT in the StreamingDistance
        }
    } else {
        The player is in the StreamingDistance
    }
} else {
    The player is NOT in the StreamingDistance
}
```

**Comment by FabianTerhorst** [comment]
> @FabianTerhorst Do you think this is complex?
> 
> ```
> StreamingDistance -> 10
> 
> Player Position -> { x: 5, y: 10, z: 7 }
> VirtualEntity Position -> { x: 2, y: 3, z: 5 }
> 
> Result = Calculate 2 axis (x, y) here
> 
> if (Result == true) {
>     if (useZ == true) {
>         VerticalDistance = Player.z - VirtualEntity.z
>         
>         if (VerticalDistance < 0.0) {
>             VerticalDistance = -VerticalDistance;
>         }
>         
>         if (VerticalDistance < StreamingDistance) {
>             The player is in the StreamingDistance
>         } else {
>             The player is NOT in the StreamingDistance
>         }
>     } else {
>         The player is in the StreamingDistance
>     }
> } else {
>     The player is NOT in the StreamingDistance
> }
> ```

i think its not relevant for normal entity logic. so it adds more complexity then needed.

**Comment by yannbcf** [comment]
So for a niche usecase you want to add a calculation step in the streamer logic rather than handling your specific usecase in your gamemode ?

**Comment by mrgharabaghi** [comment]
> So for a niche usecase you want to add a calculation step in the streamer logic rather than handling your specific usecase in your gamemode ? @mrgharabaghi

Imagine I'm in the sky `z: 500`, and a `VirtualEntity` on the ground `z: 30`.
Or better example: I'm on the ground `z: 30`, and a `VirtualEntity` in the casino `z: -100`.
Every time I want to update the `streamSynedMeta` related to casino's `VirtualEntity`, extra informations will send to every player on the ground (Casino Entrance).
This is my main problem.

**Comment by xxshady** [comment]
> Every time I want to update the streamSyncedMeta related to casino's VirtualEntity, extra informations will send to every player on the ground (Casino Entrance).

@mrgharabaghi cant you just move casino to its own dimension?

**Comment by FabianTerhorst** [comment]
position is already using all 3 dimension for comparising since v15.

**Comment by mrgharabaghi** [comment]
> position is already using all 3 dimension for comparising since v15.

Only works on client side `VirtualEntity`.
@FabianTerhorst

**Comment by mrgharabaghi** [comment]
Should I wait for it?
Or not supposed to be added on the server side?
@FabianTerhorst
