### ISSUE TITLE
Player.getByScriptID doesnt work for remote players

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1936]
### Description of the problem

/

### Reproduction steps

```js
const player = alt.Player.all[1]
alt.log(player.scriptID)
const p = alt.Player.getByScriptID(player.scriptID)
alt.log(p)
```

![изображение](https://github.com/altmp/altv-issues/assets/54737754/3f442ded-f453-4001-a809-92fcf6a01102)

Local player:

![изображение](https://github.com/altmp/altv-issues/assets/54737754/cbc3f031-88c4-4b1a-8534-0bd65137d8ce)

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev444

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Bugged again on dev597

![изображение](https://github.com/altmp/altv-issues/assets/54737754/4eb4eef4-9e38-4d46-810d-9c60a5aedfb7)

**Comment by martonp96** [comment]
should be fixed in next dev build
