### ISSUE TITLE
Attach sync bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1937]
### Description of the problem

The attaching to a vehicle is not working properly. (even with native or with server-side attachTo). What does it really mean? The syncronization "crashes", the other player sees it as the attached vehicle is teleporting. If the driver changes his dimension and back, and gets back in the vehicle. (The driver sees the vehicle normally attached.)

### Reproduction steps

1. Let's create 2 different vehicles.
2. We attach one to the other.
3. Have at least 2 players nearby.
4. One player should sit in the vehicle to which we have attached the other.
5. The sync is still good here. Let's get out, then change dimensions, then get back in and go with it.
6. In this case, the synchronization with the other player already collapses, and the attached vehicle teleports after the source vehicle.

### Expected behaviour

It was working few months earlier for sure, maybe it was the brancing before it. At the moment it is not working either on the release or dev branch.

### Operating system

Windows 11

### Version

alt:V build #15.0-dev445, branch dev

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Probably same as #1089
