### ISSUE TITLE
Allow commandline.txt to be in game files

### ISSUE THREAD

**Issue by MusaSSH** [altmp/altv-issues#1938]
### Description of the problem

alt:V won't load if commandline.txt present in game files, complaining that it should be removed for being an external modification. However, it's not, it's actually a GTAV (existed in GTA IV as well) native file that game reads command line arguments from, and has some good use cases like forcing a specific window mode as the game sometimes breaks itself and runs in the unwanted window mode.
https://support.rockstargames.com/articles/202518358/Full-list-of-command-line-parameters-for-Grand-Theft-Auto-V-on-PC

### Desired solution for the problem

alt:V shouldn't see commandline.txt as a modification.

### Alternatives you considered

A bypass option in altv.toml

**Comment by yannbcf** [comment]
It is also used by mods that we dont support/want, so very unlikely

**Comment by MusaSSH** [comment]
For what purpose they're used by mods? Do mods pass their own custom arguments to the game that does not exist in the official game? It is a file to pass command line arguments to the game. I posted the link of all arguments that can be passed to the game with commandline.txt, which one of them might have a relation with modifications? If there's any other custom argument used by mods in commandline.txt, they won't work without other files of the mods already.

**Comment by C0kkie** [comment]
Can be used to disable shadow and other things completly
