### ISSUE TITLE
Linux Server crash on Scenarios

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1939]
### Description of the problem

On Linux system server is crashing if player is on scenrario in latest DEV. Tested on Windows, no crash, but on linux same code crash.

No log's just when client is in scenario it makes server crash instantly. Im using C# clientside and serverside, but tried run client code on JS, it has same problem.

### Reproduction steps

Alt.Natives.TaskStartScenarioAtPosition(Alt.LocalPlayer, "WORLD_HUMAN_DRUG_PROCESSORS_WEED", Alt.LocalPlayer.Position.X, Alt.LocalPlayer.Position.Y, Alt.LocalPlayer.Position.Z, 0, 0, false, true);

### Expected behaviour

Not to crash

### Operating system

Ubuntu 22.04

### Version

dev 462

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Try without c# serverside. Sounds like a c# module issue.

**Comment by TuK4z** [comment]
With JS on serverside it's working as should no crash.

**Comment by FabianTerhorst** [comment]
then please open a issue on c# module or wait till the events are implemented there.

**Comment by TuK4z** [comment]
Sorry i was mistaken, it's not exactly because of taskScenario but it makes this issue.

If you run task scenario lets say that one i pasted in description or any other with object it gives player weapon with ID: 966099553 (at leats how it looks like) If player have that weapon and then you try to set ammo it crash server.

So it would be: taskScenario >> give ammo >> server crash. I tried in example freeroam resource like this:

**Server**
```
chat.registerCmd("testcrash1", (player) => {
  alt.log("testcrash1");
  alt.emitClient(player, "crash:test");
});
chat.registerCmd("testcrash2", (player) => {
  alt.log("testcrash2");
  player.setWeaponAmmo(player.currentWeapon, 1);
});
```
**Client**
```
alt.onServer("crash:test", () => {
  game.taskStartScenarioAtPosition(alt.Player.local, "WORLD_HUMAN_DRUG_PROCESSORS_WEED", 0, 0, 71, 0, 0, 0, 1)
});
```

**This crash happens no matter c# or JS, they both crash server.**

**Comment by FabianTerhorst** [comment]
fixed with latest dev build.
btw your weapon can't have ammo, because 966099553 is weapon_object.

**Comment by TuK4z** [comment]
Thank You, yes i know, just it's has to be fixed, so server not to crash on code like this. It was code mistake with weapons ammo on weaponchange event and happened that server random crashed without any logs. It was fck hard to find why server is crashing.
