### ISSUE TITLE
Different object rotations on client and server

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1943]
### Description of the problem

![img](https://github.com/altmp/altv-issues/assets/54737754/239fdc60-8011-4d9f-b3cf-dafb8387de73)

### Reproduction steps

server
```js
new alt.Object(
    'prop_air_cargo_01a',
    alt.Player.all[0].pos,
    new alt.Vector3(1.314, -2.93, 0.92)
)
```

client
```js
new alt.LocalObject(
    'prop_air_cargo_01a',
    alt.Player.local.pos,
    new alt.Vector3(1.314, -2.93, 0.92)
)
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev479

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Can you try different Rotation Order for local object. Maybe its using wrong Rotation Order.

**Comment by xxshady** [comment]
Tried 6 different xyz orders

https://github.com/altmp/altv-issues/assets/54737754/ef6e805c-d327-4780-89c3-b6f21874ce9a

**Comment by martonp96** [comment]
Should be fixed in next dev build
