### ISSUE TITLE
Player thrown from vehicle after teleportation

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1944]
### Description of the problem

Issue not exist in altv14 it started in one of 15 version. When teleporting vehicle sometimes player is no longer in vehicle. Can't tell exactly how it happens, but teleport several times and it will be thrown out. Issue is similar to this: https://github.com/altmp/altv-issues/issues/1295

### Reproduction steps

try teleport several times between positions.

[Command("tp1")]
        public static void tp1(IPlayer player)
        {
            player.Vehicle.Position = new Position(-1604.6f, -865.54f, 9.6f);
        }
        [Command("tp2")]
        public static void tp2(IPlayer player)
        {
            player.Vehicle.Position = new Position(-207.9f, 6219.9f, 31.06f);
        }

### Expected behaviour

Player stay in car

### Operating system

Windows 11

### Version

dev 480

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Try again with latest server build dev/15.0-dev481.

**Comment by TuK4z** [comment]
Looks like it's fixed.
