### ISSUE TITLE
Client crash in Cayo Perico

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#1946]
### Description of the problem

In one of latest dev builds started to crash client in CayoPerico Island. Crash happens around this specific location:

player.pos = new alt.Vector3(4890.61, -5736.18, 25.80);

I tested issue in JS and c#. Crash happens in both. No errors, no logs.

### Reproduction steps

Load Cayo perico in performant mode (unloading los santos): https://docs.altv.mp/gta/articles/snippets/cayo-perico.html#

Teleport to location: player.pos = new alt.Vector3(4890.61, -5736.18, 25.80);

Spin camera around you, looks like it happens when you turn to some direction.

### Expected behaviour

Not to crash

### Operating system

Windows 11 & Ubuntu 22.04

### Version

dev 488

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by zziger** [comment]
Fixed in 15.0-dev493
