### ISSUE TITLE
player.spawn clears blood damage locally but doesn't sync it

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1949]
### Description of the problem

![изображение](https://github.com/altmp/altv-issues/assets/54737754/61000e7a-2e5f-4b32-9b12-d295511fd50b)

### Reproduction steps

Kill player, call spawn:
```js
player.spawn(player.pos)
```

### Expected behaviour

It should be synced or blood damage should not be cleared (it was not clearing before in spawn method)

### Operating system

Windows 11

### Version

15.0-dev522

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should be fixed
