### ISSUE TITLE
Vehicle weapon damage sync is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#1950]
### Description of the problem

https://github.com/altmp/altv-issues/assets/54737754/1bbe3657-1e10-4bd2-a2aa-4b325134ccde

### Reproduction steps

Spawn `trailersmall2` vehicle, shoot

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev522

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
Fixed in dev
