### ISSUE TITLE
giveWeapon not adding ammo anymore

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1952]
### Description of the problem

hey.

giveWeapon does not properly add ammo anymore. It adds the weapon and equips it, but with 0 ammo.

### Reproduction steps

```
let hugo = alt.Player.all.find((p) => p.name === "INSERT_PLAYER_NAME");
hugo.giveWeapon(alt.hash("weapon_pistol"), 500, true)
```
is not adding ammo

### Expected behaviour

it should add 500 ammo

### Additional context

-

### Operating system

Linux Server

### Version

15.0-rc3 (rc)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
![изображение](https://github.com/altmp/altv-issues/assets/54737754/68f8270e-3af6-4912-bfb1-ba7d4544e3b3)

![изображение](https://github.com/altmp/altv-issues/assets/54737754/8c10fd0a-bdc7-48b5-b123-1a83deec461a)

Did you test on dev branch?

**Comment by xxshady** [comment]
Seems like no, because I can't reproduce it on latest dev build

**Comment by eiksch** [comment]
It was probably about weapons.bin
