### ISSUE TITLE
enteredVehicle timing issue

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1953]
### Description of the problem

Hey,

when enteredVehicle is fired, I cannot access alt.Player.local.vehicle.scriptID anymore.

### Reproduction steps

```
alt.on("enteredVehicle", (p) =>{
    alt.log(alt.Player.local.vehicle.scriptID);
});
```

returns 

```
[V8] Exception at editor 
alt.log(alt.Player.local.vehicle.scriptID); 
TypeError: Cannot read properties of null (reading 'scriptID')
    at eval (eval at <anonymous> (client.js:11:2), <anonymous>:2:38) 
```

### Expected behaviour

it should log the right scriptID

### Additional context

-

### Operating system

Linux

### Version

15.0-rc3 (rc)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Please test on latest dev

**Comment by BluePeer** [comment]
the vehicle is part of the event

enteredVehicle: (vehicle: Vehicle, seat: number) => void

so double check if this have the same issue

**Comment by eiksch** [comment]
I tested on latest dev, same issue.

Before it was working, thats why I reported it.

**Comment by xxshady** [comment]
Confirmed on 15.0-dev539

**Comment by DanielSchuech** [comment]
Workarround and hint: The first parameter of that event contains the vehicle. There you can access the `scriptID`.

```js
alt.on("enteredVehicle", (vehicle) =>{
    alt.log(vehicle.scriptID);
});
```

So it seems that only the update on `Player.local.vehicle` is not updated yet.

**Comment by eiksch** [comment]
I don't want the apparent timing change to introduce more unexpected errors. If it's "intended" or won't be fixed, then of course I will implement the workaround.

**Comment by BluePeer** [comment]
is this really a workaround?
or is the access of player information a Workaround?
if a event contains the related information, why not use the provided information?

**Comment by eiksch** [comment]
@BluePeer I have no problem using the provided information. Apparantly, this is a location where alt:V 15 broke my existing project and I just want to know whether the timing change is intended or not. Maybe it was not intended and leads to other bugs? You don't know.

**Comment by martonp96** [comment]
Should be fixed in next dev build

**Comment by eiksch** [comment]
can confirm
