### ISSUE TITLE
attachTo not attaching two vehicles anymore

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1954]
### Description of the problem

as specified in the title, it does not attach both vehicles anymore and does not return a proper error

### Reproduction steps

```
let player = alt.Player.all.find((p) => p.name === "INSERT_PLAYER_NAME");
let playerPos = player.pos;

let veh1 = new alt.Vehicle("zentorno", playerPos.x + 10, playerPos.y, playerPos.z+1, 0, 0, 0);
let veh2 = new alt.Vehicle("zentorno", playerPos.x + 5, playerPos.y, playerPos.z+1, 0, 0, 0);

veh1.attachTo(
			veh2,
			0,
			0,
			new alt.Vector3(0, 0, 0),
			new alt.Vector3(0, 0, 0),
			true,
			false
		);
```

### Expected behaviour

should attach. same snippet is working on release

### Additional context

-

### Operating system

Linux Server

### Version

15.0-rc3 (rc)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Please test on latest dev

**Comment by eiksch** [comment]
one question, on dev my reproduction example is working, but our tow system for flatbeds is not working. What are the replacements for bones in the newest version?

we used 0 and 0 for both vehicles, this does not work anymore.

**Comment by martonp96** [comment]
@eiksch please try dev572

**Comment by martonp96** [comment]
@eiksch try dev580

**Comment by eiksch** [comment]
works perfectly. thanks @martonp96 !
