### ISSUE TITLE
CDN reconnect issue solution proposal

### ISSUE THREAD

**Issue by Buh13246** [altmp/altv-issues#1955]
### Description of the problem

Currently a combination of enabled cdn and debug mode results in reconnect not working which is already reported here: https://github.com/altmp/altv-issues/issues/1559

I found a way to serve the cdn ressource still correctly by creating a nginx reverse proxy which serves the resources on the tcp port of the alt:V server. This results in a CDN_INVALID Disconnect from the Server.

The reason why i use cdn based development servers is to route based on Host addresses instead of ports, I'm currently developing a system to give each dev / team their own server based on subdomain routing which is in a large scale better to administrate.

### Desired solution for the problem

I found 4 possible solutions which could fix this issue:

- the reconnect uses the same connect information it used when it connected to the server in the first place
- the server toml allows for multiple cdn domains
- the server toml has a checkCdnUrl flag to disable this check
- the client supports a 30x redirect http response code when reconnecting and follows it. Currently this results in "'<' is not valid json" error

Reconnecting is an important feature for effective debugging / development and i would be very glad if this would be considered.

### Alternatives you considered

Another Solution that would fix my need for the cdn would be to implement SRV Record Support. This would of course be also work, but it would be a good alternative to running a cdn. Also this could be an improvement that would maybe make Alt:V more interesting for server hoster / for friends to play on their own.

### Version

release/14.64

**Comment by martonp96** [comment]
@Buh13246  Please try rc or dev branch to see if the issue still exists.

**Comment by Buh13246** [comment]
Thank you very very much :) I tested it now on 15.0-rc3 and it seems to work there, im a bit confused why it uses http instead of https when reconnecting to the cdn but its completely working and i can use my system. Thank you and the whole altmp team soo much for your work 👍 

Have a nice day :)
