### ISSUE TITLE
"Extended Voice API" perrmission is ignored by server

### ISSUE THREAD

**Issue by elrobtossohn** [altmp/altv-issues#1959]
### Description of the problem

If you specify "Extended Voice API" as required or optional in the config, the client does not even ask if you want to accept it. Apparently it only happens if you don't use a CDN.

When "packing" for the CDN, the permission is also not added to the "connect.json" file and therefore probably "ignored" by the server. But as soon as you add it in the "connect.json" file, the client asks if you want to accept the permission.

### Reproduction steps

Enter "Extended Voice API" to the "required-permissions" array in the server config

### Expected behaviour

The server shouldn't ignore the permission

### Operating system

Win11

### Version

15.0-dev541

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Server config? 
![изображение](https://github.com/altmp/altv-issues/assets/54737754/9889d2b0-16a6-40d0-a54d-770f3c08cb5c)

**Comment by xxshady** [comment]
![изображение](https://github.com/altmp/altv-issues/assets/54737754/09bf7e44-30d7-495a-a019-dcea88639c79)

https://docs.altv.mp/articles/permissions.html?q=permission

**Comment by elrobtossohn** [comment]
Omg, I found them in my server toml and idk why haha. nvermind XD
