### ISSUE TITLE
Vehicle sync brokes after creating more than four objects at once

### ISSUE THREAD

**Issue by S0P4** [altmp/altv-issues#1961]
### Description of the problem

When you are driving a vehicle and create four (4) or more alt.Objects at once vehicle position sync brokes and the server will keep the vehicle in the position were the objects creation was triggered.

### Reproduction steps

Create a vehicle and add a command for creating the objects (Using the chat example that comes in the resource example download and serverside)

```ts
chat.registerCmd('createobjects', (player, args) => {
  const range = 5;
  for (let i = 0; i < range; i++) {
    new alt.Object(alt.hash("prop_beachflag_le"), player.pos, alt.Vector3.zero);
  }
});
```

Trigger the command, drive a little and left the vehicle, unstream it and re stream it, it will be next to the position were the objects were created.

Or just add this event:

```ts
alt.on('playerLeftVehicle', (player, vehicle, seat) => {
    vehicle.pos = vehicle.pos;
});
```
Create the objects, drive a little and jump of the vehicle.

### Expected behaviour

I was specting for the vehicle sync to continue working properly.

### Operating system

Windows 11

### Version

dev/15.0-dev541

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in dev/15.0-dev545.
