### ISSUE TITLE
SetStreamSyncedMeta or getStreamSyncedMeta does not work 

### ISSUE THREAD

**Issue by Pixel220** [altmp/altv-issues#1962]
### Description of the problem

I create an object on the server side and assign it SetStreamSyncedMeta, through the client getStreamSyncedMeta 
data is not received

### Reproduction steps

Create an object and assign SetStreamSyncedMeta
On the client call GetStreamSyncedMeta

### Expected behaviour

Work

### Operating system

Windows 11 22H2

### Version

dev551

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
When have you checked the stream synced meta data getter in clientside?

**Comment by Pixel220** [comment]
> Когда вы проверили синхронизированный поток метаданных на стороне клиента?

return undefined

**Comment by C0kkie** [comment]
@Pixel220  can you try again on newest dev

**Comment by Pixel220** [comment]
> 

getStreamSyncedMeta also returns undefined.
Also now I can't drive or operate any vehicle)

**Comment by xxshady** [comment]
Fixed on latest dev
