### ISSUE TITLE
playerAnimationChange doesn't work

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#1965]
### Description of the problem

`playerAnimationChange` event doesn't triggered on client side.

### Reproduction steps

```js
alt.on('playerAnimationChange', (
    player,
    oldAnimDict,
    newAnimDict,
    oldAnimName,
    newAnimName
) => {
    alt.log(newAnimName);
});
```

### Expected behaviour

It should be triggered same as the server side.

### Additional context

Nothing.

### Operating system

Windows 10

### Version

dev/15.0-dev566

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Duplicate of #1912?
