### ISSUE TITLE
`stop resource`, `restart resource` doesn't free memory.

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-issues#1968]
### Description of the problem

Whenever I start a resource, altv-server memory usage increases (makes sense), but if I stop same resource, the memory doesn't get freed, so when developing the server, it crashes after some amount of resource reloads because of OOM.

https://github.com/altmp/altv-issues/assets/9081457/ac0d9090-e512-4683-85f7-ba28671eb718

### Reproduction steps

1. Start the resource that uses decent amount of memory.
2. Identify that altv-server memory went up.
3. Stop the resource.
4. Identify that altv-server memory stayed the same and didn't went down.

### Expected behaviour

The memory used by stopped resource should be freed.

### Operating system

Windows 10

### Version

15.0-dev566

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Is it altv core issue?

**Comment by Yiin** [comment]
No idea, don't have c# project to test against, could be js-v1 issue.

**Comment by KiwisKiwi** [comment]
> Is it altv core issue?

Seems to be related with js-v1, in C# everything works fine.

https://github.com/altmp/altv-issues/assets/40145372/57777ae1-b252-4d5c-8a24-e90482a87c46

**Comment by vanlueckn** [comment]
The js-v1 module has tons of memory leaks

**Comment by xLuxy** [comment]
Won't be fixed due to development of v2
