### ISSUE TITLE
Strange behavior of setStreamSyncedMeta and player.health

### ISSUE THREAD

**Issue by Pixel220** [altmp/altv-issues#1971]
### Description of the problem

If I change setStreamSyncedMeta or player.health for a player in the streaming area.
His skin becomes almost a copy of my character.

### Reproduction steps

1)Set the server-side skin on the player
2)Change setStreamSyncedMeta or player.health

### Expected behaviour

Normal behavior of setStreamSyncedMeta and player.health

### Operating system

Windows 11 22H2

### Version

rc/4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Pixel220** [comment]
Video
https://youtu.be/V60KxdiLhOs

**Comment by xxshady** [comment]
could be related to #1958

**Comment by Pixel220** [comment]
Yeah, it has to do with the animations

**Comment by FabianTerhorst** [comment]
Test with dev568 Server again.

**Comment by C0kkie** [comment]
@Pixel220
