### ISSUE TITLE
Bqf  Filter not working

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#1973]
### Description of the problem

I tried to implement different biquad filters with the voice api. (lowpass and highpass). I tried different values but was not able to detect any change in sound. 

After a while i switched to a peak eq filter (which is a biquad filter from a technical perspective). With the peak eq filter i noticed a change in sound.

### Reproduction steps

Create bqf and peak eq filters. 

Example : `addPeakeqEffect (0.1, 2, 4, 100, -50, 1)`

Only the peak eq variant will change the sound output.

### Expected behaviour

Biquad filters should also affect the sound.

### Operating system

Windows 11

### Version

rc 15.4

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
The bqf is used for the walkie talkie example and they work as expected.
Example:
filter.addBqfEffect(0, 1400, 0, 0.86, 0, 0, 1);
filter.addBqfEffect(1, 900, 0, 0.83, 0, 0, 2);
