### ISSUE TITLE
Prevent loading of mod dlls from backup folder

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#1974]
### Description of the problem

If you have reshade files in the backup folder, the game will mostly crash on startup

### Reproduction steps

Switch to v15 branch
Put reshade files into backup folder and in game folder
Start game

### Expected behaviour

alt:V should only load the reshade files from game folder and not from backup folder

### Operating system

Windows 11

### Version

dev/15.0-dev585

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
idk
its reshade or its more the .dll
and if this the dll is this not a "wished" feature? (one the point where the backup folder is "inuse")


i think its more usefull to restrict this to "backup in use" then to gamefolder itself
ne do not support mods, but we don't know if one of the updates will include some of that files.

**Comment by C0kkie** [comment]
launcher delets reshade from backup folder npw
