### ISSUE TITLE
Invalid entity / No event on Alt.CreateObject

### ISSUE THREAD

**Issue by KiwisKiwi** [altmp/altv-issues#1978]
### Description of the problem

If I create an object with Alt.CreateObject on server-side, I got the message `Invalid entity: 0 True` on client-side and no event for the object creation get triggered, however, the object is created successfully.

### Reproduction steps

I tried it with an empty server and an empty resource with this code:

Serverside:
```
private void Alt_OnConsoleCommand(string name, string[] args)
{
    if(name == "spawn")
    {
        Alt.CreateObject("ba_prop_battle_vinyl_case", new Position(0, 0, 72), Rotation.Zero);
        Alt.Log("TEST");
    }
}
```
        
Clientside:
```
private void Alt_OnGameEntityCreate(IEntity entity)
{
    Alt.Log("Alt_OnGameEntityCreate: " + entity.GetType().Name);
}

private void Alt_OnWorldObjectStreamIn(IWorldObject target)
{
    Alt.Log("Alt_OnWorldObjectStreamIn: " + target.GetType().Name);
}
```

### Expected behaviour

I shouldn't get the `Invalid entity: 0 True` message and an event should get triggered for the object creation on client-side.

### Operating system

Windows 10

### Version

dev/15.0-dev588

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
С# issue

**Comment by KiwisKiwi** [comment]
I think I found the bug, I created a pull request, a maintainer can take a look if I am right ^^
https://github.com/altmp/coreclr-module-runtime/pull/146
