### ISSUE TITLE
Some TextLabel bug

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#1980]
### Description of the problem

1. Creating a TextLabel when the last one just deleted, it will causes a game crash. i have to use setTimeout for it (nextTick doesn't work in this case)

2. Sometimes, the color alpha doesn't work, even when I creating a new one use alt.TextLabel, the color  alpha still won't update (tried with nextTick, setTimeout)

### Reproduction steps

    var a = new alt.TextLabel("TEST", "YOUR_FONT", 100, 1, alt.Player.local.pos, new alt.Vector3(0,0,0), new alt.RGBA(0,0,0,255), 1, new alt.RGBA(0, 0, 0, 50), true, 100);

a.destroy();

    a = new alt.TextLabel("TEST", "YOUR_FONT", 100, 1, alt.Player.local.pos, new alt.Vector3(0,0,0), new alt.RGBA(0,0,0,255), 1, new alt.RGBA(0, 0, 0, 50), true, 100);

a.color = new alt.RGBA(0, 0, 0, 100);

### Expected behaviour

Be solved

### Operating system

Win 10

### Version

15.0-dev589 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
@hookmethods  please try on newest dev, we cant repro it

**Comment by C0kkie** [comment]
Probably fixed cuz we cant repro it. if its still a issue for you, reopen it
