### ISSUE TITLE
Textlabel Enhancement

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#1981]
### Description of the problem

There's no text/fontsize/fontstyle setter for a existing label

### Desired solution for the problem

Add the ability to change the text / fontSize / fontFamily immediately. for now, I have to create a new one to update these properties

**Comment by Lukascc** [comment]
up up up

**Comment by zziger** [comment]
Duplicate of #1964

**Comment by zziger** [comment]
Setters are implemented with #1964, and will be merged to dev soon

**Comment by ThomasMarangoni** [comment]
Added in latest dev
