### ISSUE TITLE
Audio API alt.Audio.reset() and alt.Audio.seek(0) don't work

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1983]
### Description of the problem

alt.Audio.reset() doesn't reset the currentTime to 0
neither does alt.Audio.seek(0)

### Reproduction steps

1. initialize a sound with `let sound = new alt.Audio("https://dl.statev.de/test.ogg", 1, "hud", false);`
2. play it  ```sound.play() //it will play the sound as expected``` 
4. try to play it again
```
alt.log(sound.currentTime); //will return sound length as expected, because song finished playing
sound.reset();
alt.log(sound.currentTime); //will not return 0 as expected
sound.seek(0);
alt.log(sound.currentTime); //will not return 0 as expected
sound.play(); //it will not play anymore
```

### Expected behaviour

I want to be able to play sounds more than once.

### Additional context

-

### Operating system

Windows 11

### Version

alt:V build 11.4, branch release

### Scope

client

**Comment by martonp96** [comment]
should be fixed in next dev build
