### ISSUE TITLE
Remove weapon bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#1985]
### Description of the problem

With the server side function, when I delete the created gun, the ammo stays at the player and it can bug into another gun or another type of gun even. The removeAllWeapons function is not working at all.

### Reproduction steps

1. player.giveWeapon(0x1B06D571, 1000, true);
2. player.removeWeapon(0x1B06D571);
3. player.giveWeapon(0x1B06D571, 1000, true);
4. Client-side: alt.Player.local.currentAmmo -> return 2000

### Expected behaviour

It would be good, that when I delete the gun with removeWeapon function, then the ammo would be deleted from it. The removeAllWeapons does nothing in the moment, so it would be nice if you could fix it.

### Operating system

Windows 11

### Version

alt:V build #14.64 release

### Reproduction tested

- [ ] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
If you add a Weapon with Ammo, this ammo is added to the Player
Multiple Weapons use the same Ammo (Shared in GTA)
so then you remove ammo from another weapon with same ammo type

If you add 2 Pistols with the same Ammo type (each 50) you have 100 of them in client and bottom have the same amount of reserve bullets

**Comment by Yiin** [comment]
you can try doing this instead.
```
player.giveWeapon(0x1B06D571, 0 true);
player.setWeaponAmmo(0x1B06D571, 1000);

player.removeWeapon(0x1B06D571);

player.giveWeapon(0x1B06D571, 0 true);
player.setWeaponAmmo(0x1B06D571, 1000);
```

**Comment by BluePeer** [comment]
take a look about the new stuff from dev
https://docs.altv.mp/js/api/alt-server.Player.html?q=ammo
there added to get Control of that.
include the setWeaponAmmo that does not exist in 14.64 (added 3 Month ago)

**Comment by FabianTerhorst** [comment]
I don't see a bug. Ammo in gta is shared between different weapons.
