### ISSUE TITLE
[15.0-dev596] LocalObject .attachToEntity not working and can Freeze client

### ISSUE THREAD

**Issue by xenicle** [altmp/altv-issues#1987]
### Description of the problem

When using attachToEntity on LocalObject to attach object to player, client side on 15.0-dev596, the object isn't attached and calling it twice is Freezing client (using native attachEntityToEntity work as attended)

### Reproduction steps

Here is the code to reproduce :

```js
async function testCan () {
    const player = alt.Player.local

    const canPos = new alt.Vector3(0.072, 0.041, -0.06)
    const canRot = new alt.Vector3(33.0, 38.0, 0.0).toRadians()
    
    const canObj = new alt.LocalObject(alt.hash('ng_proc_spraycan01b'), player.pos, alt.Vector3.zero, true, false, true, 200)
    await canObj.waitForSpawn()
//    natives.attachEntityToEntity(canObj, player, natives.getPedBoneIndex(player, 57005), canPos.x, canPos.y, canPos.z, canRot.x, canRot.y, canRot.z, false, true, false, true, 0, true, 0)
    canObj.attachToEntity(
        player,
        natives.getPedBoneIndex(player, 57005),
        canPos, canRot,
        true, false, true)
}
```

### Expected behaviour

The LocalObject been attached to the player.

### Operating system

Windows 11

### Version

15.0-DEV596

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by vanlueckn** [comment]
I also have a similar issue. AttachToEntity does work clientside with native but serverside with Object my prop does fall down or crashes occur.

**Comment by xxshady** [comment]
Confirmed on 15.0-dev604

**Comment by martonp96** [comment]
Should be fixed in next dev build

**Comment by xxshady** [comment]
Fix confirmed
