### ISSUE TITLE
Kill effect on dead network ped creation

### ISSUE THREAD

**Issue by KiwisKiwi** [altmp/altv-issues#1988]
### Description of the problem

If you have dead network ped's and you enter the streaming area of these, you get a kill effect for every ped.
(In the video, several death peds lie at the end of the airport to test)

https://github.com/altmp/altv-issues/assets/40145372/223c7671-3cd5-4c49-b68a-5031aef42b86

### Reproduction steps

1. Spawn some peds
2. Kill them with a gun or smth
3. Leave the streaming area
4. Enter the streaming area

### Expected behaviour

Not get this effect

### Operating system

Windows 10

### Version

dev/15.0-dev597

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
I don't have this effect, maybe it should be turned on in settings somehow? 

But I have this, ped is triggers on me if he sees dead peds streamed in
https://github.com/altmp/altv-issues/assets/54737754/9d5a6bc6-5b77-40f8-835f-090fe2d4bc71

**Comment by KiwisKiwi** [comment]
Yes, is related to this setting:

![grafik](https://github.com/altmp/altv-issues/assets/40145372/5c8b783b-a4de-4f30-bf57-9862d079d1ac)

**Comment by xxshady** [comment]
Confirmed on 15.0-dev606 for reproduction you also need to equip some weapon

**Comment by ThomasMarangoni** [comment]
fixed in latest dev

**Comment by martonp96** [comment]
fixed in dev
