### ISSUE TITLE
F1 Settings - Voice Problems

### ISSUE THREAD

**Issue by JoshuaGerke** [altmp/altv-issues#1989]
### Description of the problem

When I set settings in the main menu of alt:V regarding voice, they are gone as soon as I enter my server, they are not saved. The ingame settings of Voice don't work, no matter if I set my input level to 0 or 100, I have to shout to get my Voice recognized.

### Reproduction steps

Set some options in the main menu regarding to you'r voice and enter a server, the settings should be cleared when pressing f1

### Expected behaviour

The Settings should be saved and updated so that the user can update his voice setting when he is playing on the server

### Additional context

What else I noticed is that the microphone volume is very very low, whether it is the same error and is due to the input volume or a volume problem in the script I can not say at this time, however, players around me are very very quiet. And that also with others.

### Operating system

Windows 11

### Version

#15.0-RC10

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by szkiddaj** [comment]
isnt just your mic volume low af in windows?

**Comment by vanlueckn** [comment]
Maybe  volume settings with values above 100% would make sense. (e.g 0 to 200)

**Comment by C0kkie** [comment]
try on newest dev maybe @JoshuaGerke

**Comment by martonp96** [comment]
No input from issue reporter, closing
