### ISSUE TITLE
Bug with Ped display

### ISSUE THREAD

**Issue by Pixel220** [altmp/altv-issues#1993]
### Description of the problem

If you spawn more than 300 peds will be on the server, the peds will work and move normally, as soon as you make a reconnect, the peds are no longer displayed, but the server sees them

### Reproduction steps

Go to the server
Spawn more than 300 peds 
Re-login

### Expected behaviour

Displaying pedes when reconnecting

### Operating system

Windows 11 22H2

### Version

dev/607

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
@Pixel220  Could you check newest dev please?

**Comment by Pixel220** [comment]
> @Pixel220 Could you check newest dev please?

Work,nice
