### ISSUE TITLE
social club randomly opens and cant be closed

### ISSUE THREAD

**Issue by ClutchFred** [altmp/altv-issues#1994]
### Description of the problem

sometimes (currently pretty rare) the social club menu opens. you cant interact with it in any ways. 
this was not a problem until the new rc15 versions of altv, as the native exit game dialog got removed. before that, you could trigger the exit menu with alt+f4 which closed the social club menu.

### Reproduction steps

no known way to trigger the event

### Expected behaviour

block social club ui or enable interaction with it

### Operating system

windows 11 22621.2134

### Version

rc14

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by vanlueckn** [comment]
Sometimes i also get this error

**Comment by martonp96** [comment]
try with esc button on dev617 @ClutchFred @vanlueckn
