### ISSUE TITLE
`setWeaponAmmo`  does not work with custom weapons from resources

### ISSUE THREAD

**Issue by S0P4** [altmp/altv-issues#1995]
### Description of the problem

`setWeaponAmmo` when is used for weapons resources will not set any ammo.

### Desired solution for the problem

When a weapon resource is loaded, slould parse the data.

### Version

dev/15.0-dev615

**Comment by xxshady** [comment]
I want to add its even more like a bug, because player.giveWeapon doesnt give addon weapon, but maybe it only happens with throwable weapon addon

**Comment by S0P4** [comment]
@xxshady it can be throwables, i try whit a shotgun and it work, but i cant give ammo.

**Comment by xxshady** [comment]
shotgun is not throwable

**Comment by DeRo1337** [comment]
Have the same problem you can give yourself the weapon but cannot set any ammo

**Comment by S0P4** [comment]
Its releted to how wepons work in v15 if u know the ammo hash for the weapon, u can use the ammo hash for setting up the ammo using `player.setAmmo`

**Comment by xxshady** [comment]
marked as bug because `player.giveWeapon` was working before v15

**Comment by S0P4** [comment]
Any updates on this? I didn't test it in the lastest release.
