### ISSUE TITLE
[15-DEV615] LocalObject.attachToEntity have same and additive Y and Z rotations axis

### ISSUE THREAD

**Issue by xenicle** [altmp/altv-issues#1996]
### Description of the problem

I've at first find that native.attachEntityToEntity with rot doesn't match rotation if object attached with object.attachToEntity with same rot.toRadians(), after more investigation by modifying a little [this resource](https://github.com/Squizzor/SquizzorObjectAttacher) to use LocalObject and attachToEntity I found that Rotation axis Y and Z are the same axis and additive to each other.

### Reproduction steps

Here is the dirty modified resource [squizzorobjectattacher](https://www.dropbox.com/scl/fi/0xbzgfw5sxkhsbyret7d0/squizzorobjectattacher.zip?rlkey=3q7aj6xpv4suffulb8z16sh6z&dl=0)

### Expected behaviour

Rotation axis of attachToEntity being correct.

### Operating system

Windows 11

### Version

15-DEV615

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
@xenicle altv uses rotation order 2 internally because that is the most common usage in native scripts. Try with that order when you use rotation or attachment with natives and if it still does not match the LocalObject, then we can reopen the issue.
