### ISSUE TITLE
voice settings will not be applied while changing them ingame

### ISSUE THREAD

**Issue by eiksch** [altmp/altv-issues#1997]
### Description of the problem

When I change from push-to-talk to voice-activation, it does not apply

### Reproduction steps

change from push-to-talk to voice-activation while ingame (F1)

### Expected behaviour

that it applies

### Operating system

Windows 11 (client)

### Version

15.0-dev615 (dev) latest

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
https://github.com/altmp/altv-issues/issues/1989
?

**Comment by C0kkie** [comment]
^ this
Duplicate
