### ISSUE TITLE
alt.TextLabel re-stream issue 

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#2000]
### Description of the problem

Color doesn't apply after TextLabel re-streams in

### Reproduction steps

1. create a textlabel with useStream: true and set a streaming distance
2. Reach the streaming distance
3. you'll see the color (specially alpha) won't re apply

### Expected behaviour

should be reapply

### Operating system

Win 10

### Version

15.0-dev625 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should be fixed in newest dev
