### ISSUE TITLE
connectionComplete is not called in debug mode on reconnect

### ISSUE THREAD

**Issue by MyHwu9508** [altmp/altv-issues#2002]
### Description of the problem

The clientside hook connectionComplete is not called, when reconnecting to a server in debug mode. However the first join after game start works as expected.

### Reproduction steps

Download and load the resource and try to reconnect multiple times.
https://workupload.com/file/2mW7VrHZ6qL

### Expected behaviour

connectionComplete should be called each reconnect when the client is ready.

### Operating system

Windows 11

### Version

15.0-dev629

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
I had a little chat with Kaniggel on Discord. It appears that the event is called - he just had an script error causing the event to not be registered.

**Comment by MyHwu9508** [comment]
This is not fixed yet. Without any code issues this event is not working as expected.
It works when using a complete blank test resource. However if more js content is in a resource it stops working!
![image](https://github.com/altmp/altv-issues/assets/16681058/4f2bd2b5-07e2-4b8c-9ba2-6ec363adf824)

**Comment by xLuxy** [comment]
In this case please provide a reproduction resource. I tried it multiple times with v1 and never had issues with it not being called. It also works in a larger code base.

**Comment by edgarasx** [comment]
@xLuxy I can confirm this issue still persists in js-v1, 15.0-rc26, Windows. First connection is fine, but after attempting to reconnect none of my 6 "connectionComplete" event handlers are called.

**Comment by edgarasx** [comment]
@xLuxy Found the problem, it's to do with altv-js-bytecode. Changing ```client-type = "jsb"``` to ```client-type = "js"``` in resource.toml solves the reconnect issue.

**Comment by xLuxy** [comment]
When it's only related to the bytecode module we won't fix it. The bytecode module is meant to be used for production servers where debug mode is disabled.

**Comment by MyHwu9508** [comment]
Nice, will this issue then properly documented for other Developers, because many will trigger it and will ask for help?

Also we won't fix it for auch a critical issue, is the worst answer you could give to that. When building the resources for production you need to touch the resource config and if you forget that, your code is 0 protected.
