### ISSUE TITLE
map throttle to "analog input" that can be controlled via script

### ISSUE THREAD

**Issue by ClutchFred** [altmp/altv-issues#2003]
### Description of the problem

if you press the throttle (w) key on your keyboard, the throttle is always at 100%. 

### Desired solution for the problem

ability to set max throttle value via script, like vehicle.maxThrottle = 0.5 so the throttle is always at 50% no matter how hard you press your w key

**Comment by BluePeer** [comment]
https://natives.altv.mp/#/0xE8A25867FBA3B05E
native.setControlValueNextFrame(0, 71, 0.5);

**Comment by ClutchFred** [comment]
thanks @BluePeer
