### ISSUE TITLE
Clientside GetNetTime for API consistency

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2005]
### Description of the problem

Serverside API has [`GetNetTime`](https://github.com/altmp/cpp-sdk/blob/d5ad9b4eaf2a1b31cd2be20ebdfe576bc13b9187/ICore.h#L395), but on clientside we have to use [`native.getNetworkTime()`](https://natives.altv.mp/#/0x7A5487FE9FAA6B48)

### Desired solution for the problem

Add `GetNetTime` to clientside

**Comment by FabianTerhorst** [comment]
Added in dev/15.0-dev645
