### ISSUE TITLE
Define streaming ranges for vehicle classes

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#2007]
### Description of the problem

Currently, you can only define a streaming range for all vehicles. If you have set e.g. 400m, this is sufficient for ground vehicles, but too little for air vehicles.

### Desired solution for the problem

If you could override the streaming range for individual vehicle classes, it would allow for more realistic flight operations.

**Comment by FabianTerhorst** [comment]
Streaming range will be definable per entity not per vehicle class.
