### ISSUE TITLE
Vehicle remoteId is undefined

### ISSUE THREAD

**Issue by vanlueckn** [altmp/altv-issues#2008]
### Description of the problem

If i iterate over streamed in vehicles, the remoteId property is undefined.

### Reproduction steps

Iterate over streamed in vehicles on the clientside and try to log  the remoteId property:

```js
alt.Vehicle.streamedIn.forEach(vehicle => {
    console.log(vehicle, vehicle.remoteId);
});
```

Result: 
`Vehicle { sirens: [], sirenLights: false } undefined`

### Expected behaviour

The server remote id should be logged

### Operating system

Windows 11

### Version

dev/15.0-dev635

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Because its .remoteID now
