### ISSUE TITLE
GetClosestEntities does not return entities

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2009]
### Description of the problem

/

### Reproduction steps

```js

const player = alt.Player.all[0]
alt.Utils.assert(player)

const entities = alt.getClosestEntities(
    player.pos,
    10,
    player.dimension,
    1,
    1 | 2 | 3 | 4 | 5 | 6 | 7,
)

alt.log(entities) // []
```

### Expected behaviour

Should return entities

### Operating system

Windows 11

### Version

15.0-dev638

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed in dev/15.0-dev640
