### ISSUE TITLE
metaChange events not called on server-side

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-issues#2010]
### Description of the problem

Currently, the `streamSyncedMetaChange` event aswell as the `syncedMetaChange` event are not called. Modules don't receive that event inside `OnEvent`. the meta getters do return the correct value.

### Reproduction steps

```js
import * as alt from "alt-server";

alt.on("streamSyncedMetaChange", (entity, key, newValue, oldValue) => {
  alt.log(`Stream synced meta change: ${key} ${newValue} ${oldValue}`);
});

const veh = new alt.Vehicle("buffalo", 0, 0, 72, 0, 0, 0);
veh.setStreamSyncedMeta("anchor", +new Date());
alt.log(veh.getStreamSyncedMeta("anchor"));

alt.onClient("testme", player => {
  const veh = player.vehicle;

  veh.setStreamSyncedMeta("anchor", +new Date());
  alt.log(veh.getStreamSyncedMeta("anchor"));
})
```

### Expected behaviour

All metaChange events should be called.

### Additional context

On Clientside, the events are being called as they should.

### Operating system

Windows 11

### Version

dev/15.0-dev642

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Added back in dev643.

**Comment by S0P4** [comment]
This is happening on the latest release.
