### ISSUE TITLE
Damage events for peds

### ISSUE THREAD

**Issue by KiwisKiwi** [altmp/altv-issues#2011]
We need an event when a ped takes damage.
The weapon damage event could be extended to include peds.
But also we need an event like Alt_OnPlayerDamage so that we can also get fall damage and more non weapon related damage.

~~### Description of the problem~~

~~Currently, it is only possible to get the weapon hash in the EntityHitEntity event. It would also be good to add the damage value that the hit makes.
Because the health value is only changed after the event, you unfortunately cannot track this yourself (except with some sketchy timing stuff).~~

~~### Desired solution for the problem~~

~~Add the damage value that the hit makes to EntityHitEntity event.~~

~~### Alternatives you considered~~

~~If this doesn't work for some reason, it would be also a solution to trigger the event after the health value changed, so we can track it on our own. _**only as an alternative**_~~

**Comment by xLuxy** [comment]
The `entityHitEntity` event is not meant to be used for checking damage, use `playerDamage` event instead.

**Comment by KiwisKiwi** [comment]
> The `entityHitEntity` event is not meant to be used for checking damage, use `playerDamage` event instead.

PlayerDamage event doesn't work for peds, it only gets fired if a ped attacks a player, but not the other way around.
So we need an extra event like PedDamage or a universal event e.g. EntityDamage.

**Comment by KiwisKiwi** [comment]
Have been added in dev ^_^
