### ISSUE TITLE
V15 Building lights dont shut off anymore when calling game.setArtificialLightsState

### ISSUE THREAD

**Issue by TheOutburst** [altmp/altv-issues#2014]
### Description of the problem

On the dev build the building lights don't shut off anymore when using the artificial lights native

Here are 4 pictures to clarify:
release:
pre: https://cdn.discordapp.com/attachments/922919249192833116/1154155395628154921/20230920223409_1.jpg
native called: https://cdn.discordapp.com/attachments/922919249192833116/1154155396081127467/20230920223414_1.jpg

dev:
pre: https://cdn.discordapp.com/attachments/922919249192833116/1154155396383129710/20230920223831_1.jpg
native called: https://cdn.discordapp.com/attachments/922919249192833116/1154155396806758460/20230920223836_1.jpg

### Reproduction steps

Call game.setArtificialLightsState on dev build

### Expected behaviour

The lights on the buildings should shut of just like it is right now in release

### Operating system

Windows 22H2

### Version

ev/15.0-dev669

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
https://docs.altv.mp/js/api/alt-client.ConfigFlag.html
that stuff is controlled by this flags

ForceHideNightProps/ForceShowNightProps
DisableEmissiveLightsRendering
you can control this now more differently

**Comment by martonp96** [comment]
Yes it is as BluePeer said. This needs to be added to the breaking changes. Thanks for reporting.
