### ISSUE TITLE
Parachutes cause server to crash

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-issues#2017]
### Description of the problem

Currently, when you equip a parachute and attempt to land, the server crashes immediately. According to Vektor, this issue is related to the object delete event packet.

### Reproduction steps

1.) Equip yourself with a parachute (`gadget_parachute`).
2.) Deploy the parachute and land at any location to make it disappear.
3.) Observe that the server crashes.

### Expected behaviour

The server shouldn't crash

### Operating system

Windows 11

### Version

15.0-dev669

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should be fixed
