### ISSUE TITLE
native applyPedDamagePack doesn't work

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#2018]
### Description of the problem

it doesn't work for alt.Player and alt.Ped

### Reproduction steps

    natives.applyPedDamagePack(alt.Player.local, "BigHitByVehicle", 1.0, 100);
    natives.applyPedDamagePack(alt.Player.local, "SCR_Dumpster", 1.0, 100);
    natives.applyPedDamagePack(alt.Player.local, "SCR_Torture", 1.0, 100);
    natives.applyPedDamagePack(alt.Player.local, "Explosion_Med", 1.0, 100);
    natives.applyPedDamagePack(alt.Player.local, "Skin_Melee_0", 1.0, 100);
    natives.applyPedDamagePack(alt.Player.local, "Fall", 1.0, 100);

### Expected behaviour

to be fixed

### Operating system

Win 10

### Version

15.0-dev670 (dev)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
Fixed in dev
