### ISSUE TITLE
Client-Side Checkpoints

### ISSUE THREAD

**Issue by adriantandara** [altmp/altv-issues#2020]
### Description of the problem

More precisely, this refers to the .d.ts file for typescript in the Client-Side. On the server, when I create a checkpoint, it asks me for 6 arguments, of which the .d.ts file from altv asks for 11 arguments.

```typescript
Checkpoint(type: CheckpointType, pos: IVector3, nextPos: IVector3, radius: number, height: number, rgbcolor: RGBA, iconColor: RGBA, streamingDistance: number): Checkpoint
```

### Reproduction steps

I used only 6 arguments and it worked, but in typescript I have to use @ts-ignore to ignore the error from typescript with insufficient arguments.

```typescript
Checkpoint(type: CheckpointType, pos: IVector3, nextPos: IVector3, radius: number, height: number, rgbcolor: RGBA): Checkpoint
```

### Expected behaviour

Add in that d.ts file how many types it supports on the client and how many on the server because it is different on the server-side. There it supports 11 arguments, the problem is only on the client-side.

### Operating system

Windows

### Version

dev/15.0-dev676

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
On client either 8 arguments or 12 are working. What do you mean by "it worked with only 6 arguments"? Checkpoint shouldn't be created when passing only 6 args.

**Comment by adriantandara** [comment]
Well, when I put more than 6 arguments, I get an error in the client. If the problem has not been reported/solved recently, I will come back with a picture.

**Comment by adriantandara** [comment]
Apparently it was fixed on dev, possibly the problem was solved. Sorry for the trouble
