### ISSUE TITLE
OnGivePedScriptedTask is only fired when re-entering stream distance

### ISSUE THREAD

**Issue by TheDutchDev** [altmp/altv-issues#2021]
### Description of the problem

When spawning a ped and giving it a scripted task, it will never fire the event until you leave and re-enter stream distance of that ped.

### Reproduction steps

- Spawn a ped
- Give it a scripted task (eg taskWander)
- Leave and re-enter stream dist
- Event now fires

### Expected behaviour

Should always fire the event

### Operating system

Win 10

### Version

dev/15.0-dev677

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by TheDutchDev** [comment]
Actually, when testing again now the event doesn't seem to fire at all

**Comment by martonp96** [comment]
should be fixed in next dev build
note: the event is triggered only when a non-netowner tries to play a task on a ped
