### ISSUE TITLE
Server-side object rotation bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2023]
### Description of the problem

If you only want to change the rotation of an object created on the server side, it will be changed for the netOwner player, but not for the other streamed players.

### Reproduction steps

1. Create server-side object.
2. Change the rotation.

Example:
let test = new alt.Object("prop_ld_ferris_wheel", new alt.Vector3(-1663.97, -1126.7, 30.7), new alt.Vector3(0, 0, 0), 255, 0, 1000);
test.frozen = true;
alt.setTimeout(function() {
	test.rot = new alt.Vector3(0, 0, 1.0);
}, 5000);

### Expected behaviour

Have the object in sync with other players, not just netOwner.

### Operating system

Windows 11

### Version

#15.0-rc17

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Lekenthu** [comment]
> can u test it with latest dev?

Yes, I've tested it on dev branch (#15.0-dev685) and it's just as bad.

**Comment by martonp96** [comment]
fixed in dev
