### ISSUE TITLE
Streaming animations doesn't work on dev

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#2025]
### Description of the problem

 it doesn't work on dev but on release

https://media.discordapp.net/attachments/652672692876607507/1155764278012432425/image.png?width=1221&height=1090

### Reproduction steps

1. download the anim mods from any website, and stream or use mine https://www.dropbox.com/scl/fi/kkwquk0gm7lenrpei68m8/coupeanim.zip?rlkey=ll94rxrx1ibll27cj4ay7p6k5&dl=0

dict: 'tigerle@custom@couple@cuddle1a',
anim: 'tigerle_couple_cuddle1a',

### Expected behaviour

it should be work

### Operating system

Win 10

### Version

15.0-dev685

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by emcifuntik** [comment]
Works fine on 15.0-dev740
<img width="1282" alt="image" src="https://github.com/altmp/altv-issues/assets/4309694/766661a7-3daf-4b06-9eb3-c95bfbf430c9">
