### ISSUE TITLE
Add emitRaw support for WebView

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-issues#2026]
### Description of the problem

Since WebView is also running JS environment, it would make sense for it to support raw events.

### Reproduction steps

Try to use webview.emitRaw, observe that the method does not exist.

### Expected behaviour

It should exist and serialize/deserialize objects (such as Map, Set, Date, etc) correctly.

### Additional context

We could try to deserialize `MValueByteArray` values in webview event handlers that include magic bytes and let modules to implement those in serialization process similarly how it is done for server <-> client events. It kinda couples the implementation details between core and JS module, but I think it's okay for this case.

### Operating system

N/A

### Version

N/A

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by LeonMrBonnie** [comment]
WebView doesn't use same JS version as client and server so it's not possible

**Comment by FabianTerhorst** [comment]
Small node: In V15 you can send a byte array to the webview.
