### ISSUE TITLE
Towtruck desync and crash to all near clients

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#203]
https://i.imgur.com/EBlEFOP.png

> Towtruck, stopping to tow is generally unsync somehow. The towed and the towing person are somehow in sync, AKA the towing rope is not attached and car ist standing still, but the towed car can't drive anymore. For third parties the car is still completely towed. Sometimes it randomly works, I feel like that is related to third persons in streaming range or similar, but we couldn't find a pattern there.
> 
> This crash happened after the towed car got untowed but was still attached for third parties and the car couldn't drive. We then tried to attach another car to the truck which didn't work at first, after some trying it worked and for a short duration both cars were towed for third parties, the first towed client was untowed from that point on. Then it crashed on the third party.

https://cdn.discordapp.com/attachments/557307592129511444/599664801739964476/altv_635_Social_Club_0x7ff7b94f0000_c-13-07-2019_20-03-25.rar
https://youtu.be/zNApMOcaEkw
## Context (Environment)
647

**Comment by BlackyGER** [comment]
Any news on this end?

**Comment by Lhoerion** [comment]
@BlackyGER You can test on latest dev branch build

**Comment by C0kkie** [comment]
Its fixed since dev/1.2-dev57
