### ISSUE TITLE
Some dlcs are not (yet) loaded, when streaming rpf

### ISSUE THREAD

**Issue by 5pHiNxX** [altmp/altv-issues#2033]
### Description of the problem

When I load my vehicle `testcara` using the dlc approach, it spawns fine and I also can enter it and everything works fine.

When I use the exact same files but pack them as a (correct) dlc.rpf and stream them using the rpf approach, the car spawns but as soon as I try to enter it, it crashes the client.

After investigating I found out, that the vehiclelayouts.meta from the dlc `mpvinewood` seems not (yet) loaded when my dlc.rpf is loaded in the client. When I alter the vehicles.meta from my dlc.rpf and change it to `LAYOUT_RANGER` which is located in the base game (no dlc), the car works fine.

So it seems like at least some dlcs are not (yet) loaded, when the streamed dlc.rpfs are loaded in the client.

The files:
Testcara as DLC resource: https://workupload.com/file/JvCmnmMBwzm
Testcara as RPF resource (exactly the same files as in the DLC resource): https://workupload.com/file/WNE7xy52ukd
Testcara as RPF resource (fixed by using the vehicle layout `LAYOUT_RANGER` from base file): https://workupload.com/file/tF7zmFR54AJ

### Reproduction steps

Use https://workupload.com/file/JvCmnmMBwzm and stream it using the dlc approach -> vehicle works fine
Create a rpf resource from the files above or use https://workupload.com/file/WNE7xy52ukd with the rpf approach -> client crashes on entering the vehicle
Fix the rpf resource by altering `vehicles.meta` and change the layout to `LAYOUT_RANGER` or use https://workupload.com/file/tF7zmFR54AJ and stream it using the rpf approach -> vehicle works fine

### Expected behaviour

The vehicle should also work if the layout in `vehicles.meta` is `LAYOUT_RANGER_CARACARA2` which is present in the `mpvinewood` DLC when streaming it using the rpf approach, becaus it works fine when streaming it using the dlc approach.

### Operating system

Windows 10 (Server and Client)

### Version

dev/15.0-dev691

### Crashdump ID

c9a49935-2ec7-4f7e-b59a-317f43d31c82

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by martonp96** [comment]
If you have a dependency to a dlc, you have to set a higher order than that in your dlc.
Crash:
testcara setup2.xml order: 9
dlc_mpVinewood setup2.xml order: 33

Works:
testcara setup2.xml order: 34
dlc_mpVinewood setup2.xml order: 33
