### ISSUE TITLE
Unable to send more than 1KB form client to server

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#2035]
### Description of the problem

Since security update 14.72 it is not possible to send more than 1KB of data between the client and server on Linux systems.  It is working fine on Windows but not on Linux.
When sending more than 1KB the client is crashing silently and anything from the alt.Emit() is not executed.

### Reproduction steps

alt.Emit('Test', '<string with more than 1KB of data>');
alt.log('Test message');

### Expected behaviour

Should normally send data to server and display 'Test message' on client console.

### Additional context

Affecting only Linux systems

### Operating system

Debian 11

### Version

Prod/14.72

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Wait for v15 Release. There you will have the ability to adjust the size limit yourself. For more infos see scripting-info channel on discord.
