### ISSUE TITLE
Support async function for RPC

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2037]
### Description of the problem

At this time async functions doesn't work with `RPC`.
```js
// Server side
alt.onRpc('giveMeData', async () => {
    await alt.Utils.wait(5000);
    return 123;
});
```

### Desired solution for the problem

I don't know.

### Version

dev/15.0-dev709

**Comment by xLuxy** [comment]
This is already added - wait for next build :)
