### ISSUE TITLE
Alt+Enter turns the game into a black screen

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2038]
### Description of the problem

Only happens on resource downloading 

https://github.com/altmp/altv-issues/assets/54737754/702a4e50-1a3d-4c7c-a87b-3d41d7574755

### Reproduction steps

See video

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev716

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Confirmed

**Comment by martonp96** [comment]
Fixed in dev734. The black screen fixes are still not available for amd gpus.
