### ISSUE TITLE
Cannot open GTAV menu on start

### ISSUE THREAD

**Issue by 7Hazard** [altmp/altv-issues#204]
The GTA V menu cannot be opened on start, before connecting to any server.
Escape or P button doesn't open the GTA V menu.

**Comment by vadzz-dev** [comment]
It is disabled

**Comment by 7Hazard** [comment]
I still consider it a bug, as it's unexpected
Wanted to change my display and graphic settings, an example

**Comment by martonp96** [comment]
You are out of order hazard
