### ISSUE TITLE
Weird in-out streaming behavior during the 3rd stresstest

### ISSUE THREAD

**Issue by szkiddaj** [altmp/altv-issues#2040]
### Description of the problem

demonstration vid: https://youtu.be/Uz3Q8sFsu80

### Reproduction steps

\-

### Expected behaviour

\-

### Additional context

\-

### Operating system

Windows 10 (revios)

### Version

dev/15.0-dev717

### Crashdump ID

-

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
streaming is 3d now, but with larger packet drop streaming isn't ordered.
