### ISSUE TITLE
voice activation Sens above 0 does not work

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#2041]
### Description of the problem

If you set voice activation and set the sens to above 0, you can no longer speak

### Reproduction steps

activate from push to talk to voice activation and set it higher than 0

### Expected behaviour

it works

### Operating system

Windows 11

### Version

alt:V build #15.0-dev717

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by BluePeer** [comment]
Confirmed on stresstest, same issue on my side at stresstest

**Comment by litolax** [comment]
Confirmed with the latest dev (722)

**Comment by C0kkie** [comment]
Should be fixed
