### ISSUE TITLE
Player Detach not working

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#2044]
### Description of the problem

Tested in latest dev719 player.Detach(); not working.

### Reproduction steps

Use player.AttachToEntity
In my case im using: player.AttachToEntity(target, 0, 0, new Position(0f, 0f, 0f), new Rotation(0, 0, 0), false, false);

Then try to detach with player.Detach();

### Expected behaviour

Player to be detached

### Operating system

Ubuntu 22.04 & Win11

### Version

dev 719

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by C0kkie** [comment]
Should work again

**Comment by TuK4z** [comment]
Can someone else test it? I tried with my c# and with another js project. Issue still happens to my on latest version.
