### ISSUE TITLE
Write log message to clientside console when client can't send payload to server due its size

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#2045]
### Description of the problem

Sometimes it's unclear why client can't send payload to server

### Desired solution for the problem

Write log message to console that payload has exceeded size limit

### Version

dev

**Comment by FabianTerhorst** [comment]
Post code to reproduce.

**Comment by FabianTerhorst** [comment]
limit is 4kb. also dev branch should normally trigger a log when its larger then 4kb.
