### ISSUE TITLE
Version mismatch feedback

### ISSUE THREAD

**Issue by NathanX-S** [altmp/altv-issues#2046]
### Description of the problem

There's no clear feedback when connecting to a server with a mismatched version. The server simply declines your connection with "Server not responding".

### Desired solution for the problem

Some kind of feedback like: (This server requires #hash! to play. Your client version is mismatched.)

**Comment by litolax** [comment]
Many protocol changes make that impossible

**Comment by NathanX-S** [comment]
Don't see any reason why it can't be implemented from X onwards.

**Comment by FabianTerhorst** [comment]
not planned
