### ISSUE TITLE
Connection URL altv://connect dont working

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#2052]
### Description of the problem

alt:V Connect String no longer works. alt:V Starts but does not go to the server.

### Reproduction steps

I have created a shortcut under Windows 11.
once with: `altv://connect/https://cdn.playv.mp`
and once with `altv://connect/cdn.playv.mp:443`
and both do not work

### Expected behaviour

Connect to the server

### Additional context

is a similar issue #1459
I can't test it with dev because when release is uninstalled it can't find alt:V version anymore

### Operating system

Windows 11

### Version

alt:V build #14.73, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Works fine for me, can not reproduce

**Comment by zziger** [comment]
You cannot just check the checkbox without testing. Should work on dev.
