### ISSUE TITLE
Uninstaller does not delete all files from the folder

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#2053]
### Description of the problem

After I uninstalled alt:V, the `altv-launcher-patcher.dll` remained in the folder

### Reproduction steps

Go to controls, apps, installed apps, and uninstall alt:V

### Expected behaviour

Deletes the folder correctly

### Operating system

Windowes 11

### Version

alt:V build #14.73, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Letsion** [comment]
Confirmed under alt:V build #15.0-dev743
in Dev it does not delete the backup folder either

**Comment by deluvas1911** [comment]
Fixed with launcher version dev/15.0-dev66
