### ISSUE TITLE
The XMAS weather doesn't render snow on the roads

### ISSUE THREAD

**Issue by Sv1ne** [altmp/altv-issues#2055]
### Description of the problem

The XMAS weather doesn't render snow on the roads

### Reproduction steps

alt.setConfigFlag("FORCE_RENDER_SNOW", true);
native.setWeatherTypeNowPersist("XMAS")

### Expected behaviour

XMAS weather should render snow on the roads

### Operating system

Client: Windows 10, Server: Ubuntu 20.04

### Version

15.0-dev745

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by deluvas1911** [comment]
You need to call the native `useSnowWheelVfxWhenUnsheltered` and set it to true to leave snow trails.
Same for peds - `useSnowFootVfxWhenUnsheltered`

**Comment by emcifuntik** [comment]
This issue really exist and fixed in next build
