### ISSUE TITLE
The validation between DEV and RC does not work

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#2056]
### Description of the problem

The check between alt:V Dev version and alt:V RC version or an older alt:V RC version does not work.

### Reproduction steps

Try to connect to an alt:V RC version server with the alt:V Dev version (maybe with an older RC 15 version).
my server test.letsion.de:7788 could be tried as a test.

### Expected behaviour

Error message that you are on a different branch or that the server version is outdated.

### Operating system

Windows 11

### Version

dev/15.0-dev745

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
I think it doesn't work because dev branch receives a lot of protocols changes. Try to check it immidiatly after dev->rc merge.
