### ISSUE TITLE
Fire on player body is not synced

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2059]
### Description of the problem

from remote player view
<img width="200px" src="https://github.com/altmp/altv-issues/assets/54737754/b36086b3-f614-473d-b7d3-26bcf4e7384f"/>

from local player view
<img width="200px" src="https://github.com/altmp/altv-issues/assets/54737754/8707eb1e-360b-4739-bc75-3be9514da92c"/>

### Reproduction steps

/

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev755

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Reproduced on the latest dev

**Comment by C0kkie** [comment]
fixed in newest dev
