### ISSUE TITLE
Vehicle wheelsCount server side getter is modified after a player seats in the driver seat

### ISSUE THREAD

**Issue by Darco2903** [altmp/altv-issues#2062]
### Description of the problem

`vehicle.wheelsCount` server-side getter value change when a player seats in the driver seat.
After spawning a Adder for example, the getter value is 4 (which is the correct value) and a few moment after a player enter (driver seat), it returns 10.

### Reproduction steps

```js
import * as alt from "alt-server";

alt.on("playerConnect", (player) => {
    alt.log(`~m~${player.name} joined`);
    player.pos = new alt.Vector3(180, -1030, 29);
    player.model = "mp_m_freemode_01";

    setTimeout(() => {
        const vehicle = new alt.Vehicle("adder", player.pos.add(1, 1, 0), alt.Vector3.zero);
        alt.log("Vehicle spawned", vehicle.wheelsCount); // 4
        player.setIntoVehicle(vehicle, 1); // or just enter the vehicle
    }, 1000);
});

alt.on("playerEnteredVehicle", (player, vehicle, seat) => {
    alt.log("Player Entered Vehicle", vehicle.wheelsCount); // 4
    setTimeout(() => {
        alt.log("1s Timeout", vehicle.wheelsCount); // 10
    }, 1000);
});
```

I made a simple resource [**test-wheelscount.zip**](https://github.com/altmp/altv-issues/files/12851038/test-wheelscount.zip) that contains the above code to reproduce it.

### Expected behaviour

Return the correct number of wheels.

### Additional context

It was working perfectly fine on release version and I recently switched to RC version and I was getting errors on some scripts that was using this value.
I also tried to reproduce it in dev version and same thing happened.

### Operating system

Windows 10

### Version

15.0-dev764

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Could reproduce with latest dev.

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.
