### ISSUE TITLE
LocalPlayer GetWeaponAmmo crashes game

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2063]
### Description of the problem

Without crashdump

### Reproduction steps

Give yourself any weapon
```js
alt.setTimeout(() => {
    alt.log({ ammo: alt.Player.local.getWeaponAmmo(alt.hash('weapon_unarmed')) })
}, 1000)
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

15.0-dev764

### Crashdump ID

Crash without crashdump

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Confirmed, only happens when giving yourself a weapon. When no weapon was given, the client doesn't crash.

**Comment by C0kkie** [comment]
Fixed in newest dev
