### ISSUE TITLE
LocalPlayer CurrentAmmo returns value with delay

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2064]
### Description of the problem

in JS API `alt.Player.local.currentAmmo` returns ammo of current weapon with some delay, meanwhile `getAmmoInPedWeapon` native returns it immediately

### Reproduction steps

![изображение](https://github.com/altmp/altv-issues/assets/54737754/00db50e0-ff44-4344-a26e-204cf646daf6)

```js
import alt from 'alt-client'
alt.on('playerWeaponChange', (_, newWeapon) => {
  const localPlayer = alt.Player.local
  alt.log(
    {
      currentAmmo: localPlayer.currentAmmo,
      native: native.getAmmoInPedWeapon(localPlayer, newWeapon),
    },
  )

  alt.nextTick(() => {
    alt.log(
      {
        currentAmmo: localPlayer.currentAmmo,
        native: native.getAmmoInPedWeapon(localPlayer, newWeapon),
      },
    )
  })

  alt.setTimeout(() => {
    alt.log(
      {
        currentAmmo: localPlayer.currentAmmo,
        native: native.getAmmoInPedWeapon(localPlayer, newWeapon),
      },
    )    
  }, 1000)
})
```

### Expected behaviour

It should return ammo immediately

### Operating system

Windows 11

### Version

15.0-dev765

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Yiin** [comment]
```ts
await alt.Utils.waitFor(() =>!game.isPedSwitchingWeapon(player));
```

**Comment by martonp96** [comment]
if you want the same functionality as getAmmoInPedWeapon, use localPlayer.getWeaponAmmo(newWeapon)
