### ISSUE TITLE
client event size limits

### ISSUE THREAD

**Issue by notmatical** [altmp/altv-issues#2065]
### Description of the problem

Multiple issues here, first one is I have the server config to change event sizes. I have them set to 512kb

```
# Event Limits
maxClientScriptEventSize = 524288
maxServerScriptEventSize = 524288
```

Second issue is the client events are not obeying the server-defined limits.
And i'm pretty sure an empty string isn't greater than 4kb's of data.

### Reproduction steps

emit to server an empty string, the server will never receive it, nor will you get any error in console.
`alt.emitServer('TEST', '');`

Go check your client log and you'll see: 
`[20:37:30][Error] Event was larger than 4kb: 'TEST'`

### Expected behaviour

obey server config event limits, show error in console, and allow a 0.4kb size event through the net.

### Operating system

Windows 11

### Version

15.0-dev773

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Max is (2^16)-1 for client. log will be adjusted next build and server config won't accept larger values.
