### ISSUE TITLE
Add backup feature of GTAV files

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-issues#207]
**Is your feature request related to a problem? Please describe.**
If a GTA Update arrives, it would be nice to have a backup of the needed files to downgrade.

**Describe the solution you'd like**
A flag which can be set in the config. The launcher checks on start if the backup exists and the flag is set, if not the needed files are copied to the altv folder.

**Comment by martonp96** [comment]
We don't support piracy.
