### ISSUE TITLE
(Feature request): function for server timestamp getter

### ISSUE THREAD

**Issue by CENSOR1337** [altmp/altv-issues#2070]
### Description of the problem

When I want to sync the data between server and client like item or vehicle expiration date, we would want to make sure that client time is synced with server time, using client timestamp to find how many hh:mm:ss left sending a event or even using meta there still a little to do.

### Desired solution for the problem

it would be great if I have function like `alt.getServerTime()` or something to make life pretty much easier.

### Additional context

for now I'm set start time and add with nettime to get server timestamp.

serverTime = `server start sync meta` + `alt.getNetTime()`

**Comment by szkiddaj** [comment]
Just use `Date.now()`?

**Comment by CENSOR1337** [comment]
> Just use `Date.now()`?

That is a client side timestamp not server side

**Comment by szkiddaj** [comment]
> That is a client side timestamp not server side

???
Date.now() is everywhere the same because it’s epoch, and available both on Node and V8 runtimes. And because of this, it’s not affected by timezones and etc..

**Comment by martonp96** [comment]
alt.getNetTime() is already synchronized between all clients and the server

**Comment by CENSOR1337** [comment]
> > That is a client side timestamp not server side
> 
> ??? Date.now() is everywhere the same because it’s epoch, and available both on Node and V8 runtimes. And because of this, it’s not affected by timezones and etc..

No, It returns the number of milliseconds elapsed since the Unix epoch (January 1, 1970, at UTC) according to the system clock.
As you can see here i simply change my clock system and then timestamp just changed depend on system clock and it's not a reliable.
![image](https://github.com/altmp/altv-issues/assets/16758153/4b4f4ed1-5364-46e0-8466-5e45921dd778)

**Comment by CENSOR1337** [comment]
> alt.getNetTime() is already synchronized between all clients and the server

Yes this can be use but it will get reset when start restarted, and yes it's right and nothing to do with that.
Let's say I have a vehicle with expiration date since `getNetTime` not return a timestamp so I cannot use that to find when does the vehicle going to be expired, And yes we can do that by just set server start time in syncMeta and add `getNetTime`, it would be same result, But it would be great if that function included with Alt:V it self so I don't have to make one when I make new resource.

**Comment by szkiddaj** [comment]
almost everybody uses ntp, who caresxdd also, if a player does something based on time, just check the time on server side.

**Comment by CENSOR1337** [comment]
> almost everybody uses ntp, who caresxdd also, if a player does something based on time, just check the time on server side.

You trust a client information?, I think it's a good thing that we have more reliable time getter to sync the information and yes it's not the only vehicle expiration date, What if I have a gamemode that shrink circle down every x second and it has 8 hour and it stay even the server is restarted? using `getNetTime` it would get reset everytime server is restarted but server timestamp doesn't, You said who care that mean you don't really have a use case of this function at this time.

**Comment by CENSOR1337** [comment]
> alt.getNetTime() is already synchronized between all clients and the server

Hey, 
I was wondering if we could reopen this? I'm really curious to hear any comments or information about it. 
Thanks

**Comment by szkiddaj** [comment]
> You trust a client information?, 

?????????? 
Why would you use the time the client give you??? what

> You said who care that mean you don't really have a use case of this function at this time.

Nah, I do use time-related calculations. But it's pointless to add anything other than `alt.getNetTime`. There's Date.now() to get epoch time.

> I was wondering if we could reopen this? I'm really curious to hear any comments or information about it.

Nah, he'll probably not. No offense but it's stupid.

**Comment by CENSOR1337** [comment]
> There's Date.now() to get epoch time.

Was my earlier statement was not clear enough or you can't understand that?

> almost everybody uses ntp

You just prove my point, because it's almost everyone not everyone

> Nah, he'll probably not. No offense but it's stupid.

wow did you just put your word on others mouth?

As I said we have a way to achieve this already and it not even hard at all, but it **would be great** to have this in AltV api , at least to consider it, or you can give any other comment that actually useful why not to include that function than "carexddd" or trying to say "no offense" and than continue to do that.

**Comment by ThomasMarangoni** [comment]
This conversation was getting too heated, discussion is now locked.
