### ISSUE TITLE
Connection failure does not allow to re-enter address

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2073]
### Description of the problem

![изображение](https://github.com/altmp/altv-issues/assets/54737754/be0da4a0-be13-4637-96d9-68277bf905f5)

### Reproduction steps

Enter invalid adress, press connect, side buttons for re-entering adress are blocked

### Expected behaviour

Side buttons should be available for re-entering adress

### Operating system

Windows 11

### Version

15.0-dev787

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by zziger** [comment]
Fixed in `dev/15.0-dev799`
