### ISSUE TITLE
maxClientScriptEventSize bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2074]
### Description of the problem

With the maxClientScriptEventSize configuration, I changed the limit to 131072, but the client still said it was 8192.

Error log:
[Error] Event was larger than8192 Bytes: 'exitInteriorEditor'

### Reproduction steps

1. Adjust the limit.
2. Try to send data that is greater than the previous limit.

### Expected behaviour

-

### Operating system

Windows 11

### Version

15.0-rc26 and latest dev branch version

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xLuxy** [comment]
Don't exceed the limit of `65534`
