### ISSUE TITLE
getHeadOverlay index return bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2075]
### Description of the problem

If I set one of the values to 255 (the default) for headOverlay, the getHeadOverlay return at index will be 0. This is incorrect, as it should be 255.

### Reproduction steps

1. player.setHeadOverlay(8, 255, 1.0);
2. player.getHeadOverlay(8).index; -> return value: 0

### Expected behaviour

-

### Operating system

Windows 11

### Version

15.0-rc26

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed next build.
