### ISSUE TITLE
ScriptEvent data overflow

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-issues#2076]
### Description of the problem

When I create a ped and want to send it to the client via event I get the error: 'ScriptEvent data overflow <eventname>'.

### Reproduction steps

serverside:
let testPed = new alt.Ped('mp_f_freemode_01', new alt.Vector3(833, -279, 66), new alt.Vector3(0, 0, 0));
player.emit('ped_task', testPed)

clientside:
alt.onServer('ped_task', (ped: alt.Ped) => {
	console.log(ped.scriptID)
})

### Expected behaviour

-

### Operating system

Windows 11

### Version

15.0-rc26

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by WhishN** [comment]
Same goes for vehicle
```
//data = float[8];
player.Emit("ev", true, data); // working
player.Emit("ev", ivehicle, data); // [16:12:37][Error] ScriptEvent data overflow ev
```

**Comment by FabianTerhorst** [comment]
Try again on latest dev.

**Comment by devpanda0** [comment]
Thank you, the error no longer comes and it works for peds
