### ISSUE TITLE
Closing F1 menu with ESC triggers game menu

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2077]
### Description of the problem

Sometimes closing in-game F1 menu with ESC key will trigger the GTA game menu to open. The game seems to somtimes catch the keydown/keyup event of ESC key and triggers the game menu.

### Reproduction steps

1) Go to server
2) Click F1
3) Click ESC
4) Repeat until GTA menu appears

### Expected behaviour

GTA menu should not open when closing F1 menu

### Operating system

Windows

### Version

15.0-rc26

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Iamproplayer7** [comment]
Also happens in 15.0-dev69, happens more often if you are holding ESC and releasing after F1 menu closes.

**Comment by zziger** [comment]
Fixed in `dev/15.0-dev799`
