### ISSUE TITLE
Setting Ped.currentWeapon server-side does not work

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2078]
### Description of the problem

Setting Ped.currentWeapon server-side does not give ped a weapon. 

### Reproduction steps

The following code does not give ped a weapon.
```ts
const ped = new alt.Ped('G_M_Y_MexGoon_03', new alt.Vector3(-204.1846160888672, 6111.36279296875, 30.4534912109375), new alt.Vector3(0, 0, 0.09894780069589615));

ped.currentWeapon = alt.hash('WEAPON_PISTOL');
```

Client-side you can check if ped received a weapon:
```ts
alt.on('consoleCommand', (command: string, ...args: string[]) => {
    if(command !== 'testped') return;

    alt.Ped.all.forEach(ped => {
        alt.log(
            ped.remoteID, 
            'PED WEAPON', 
            ped.currentWeapon, 
            native.hasPedGotWeapon(ped.scriptID, alt.hash('WEAPON_PISTOL'), false),
        );
    });
});
```

Will print:
```
[16:26:03] 1 PED WEAPON 2725352035 false
```

CurrentWeapon property value is correct on client-side, but the ped does not receive or equip the weapon. Even if you set it to attack you it will not take out a weapon. But if you give it a weapon client-side, then it works.

### Expected behaviour

Since Ped.currentWeapon is writable I assume the ped should receive a weapon and equip it

### Operating system

Windows

### Version

15.0-rc26

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
the ped setters in v15 will all have the limitation that they need a net owner. when you do it to early it won't work. rework is planned for v16.
