### ISSUE TITLE
Error when putting from ped clothes

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-issues#2079]
### Description of the problem

I try to put clothes on a ped with setPedDlcClothes & setPedDlcProp Clientside, but this throws an error 'SetDlcProps is not supported for players. Use the serverside api for that' even if I omit setPedDlcProp the error comes up.

### Reproduction steps

alt.setPedDlcClothes(ped.scriptID, hash, 2, 0, 0); // Hair
alt.setPedDlcClothes(ped.scriptID, hash, 4, 0, 9); // Legs
alt.setPedDlcClothes(ped.scriptID, hash, 6, 0, 2); // Shoes
alt.setPedDlcClothes(ped.scriptID, hash,8, 0, 0); // Shirt
alt.setPedDlcClothes(ped.scriptID, hash, 11, 26, 7); // Top
alt.setPedDlcProp(ped.scriptID, hash, 1, 0, 0); // Hat

This is the code I use on the client side to put the clothes on the ped

### Expected behaviour

-

### Operating system

Windows 11

### Version

15.0-dev792

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
This works as intended, we disabled it for players. the error message tells you what to do.

**Comment by FabianTerhorst** [comment]
For peds its disabled intentional as well. v16 will support same clothes api as for players.
