### ISSUE TITLE
Colshapes not sending callback

### ISSUE THREAD

**Issue by csskroubledev** [altmp/altv-issues#2080]
### Description of the problem

**Using C# module**

After creating ColShape, it doesn't send any events to callback - worked in current release (v14), now doesn't.

### Reproduction steps

- Add an callback using AltAsync.OnColShape
- Create an colshape using Alt.CreateColShapeSphere
- Walk into the colshape

### Expected behaviour

Callback should be sent

### Operating system

Windows 10

### Version

rc

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
C# issue? it works for me on latest dev

**Comment by litolax** [comment]
I can check in c# in ~50 mins

**Comment by litolax** [comment]
Works fine for me, show your code please

**Comment by edgarasx** [comment]
@litolax Can confirm, sometimes colshape events are not being called, no idea why, it seems random. Was working perfectly before. Noticed in rc26, using js.

```ts
const colshape = new alt.ColshapeSphere(pos.x, pos.y, pos.z, radius);
colshape.setSafeZone();

alt.on("entityEnterColshape", (colshape: alt.Colshape, entity: alt.Entity) => {
    
    if(entity === null || colshape === null) return;
    if(!entity.valid) return;
    if(!colshape.isSafeZone()) return;

    if(entity instanceof alt.Player) {
        SafeZone.onPlayerEnter(entity);
        return;
    }
});
```

**Comment by litolax** [comment]
> @litolax Can confirm, sometimes colshape events are not being called, no idea why, it seems random. Was working perfectly before. Noticed in rc26, using js.
> 
> ```ts
> const colshape = new alt.ColshapeSphere(pos.x, pos.y, pos.z, radius);
> colshape.setSafeZone();
> 
> alt.on("entityEnterColshape", (colshape: alt.Colshape, entity: alt.Entity) => {
>     
>     if(entity === null || colshape === null) return;
>     if(!entity.valid) return;
>     if(!colshape.isSafeZone()) return;
> 
>     if(entity instanceof alt.Player) {
>         SafeZone.onPlayerEnter(entity);
>         return;
>     }
> });
> ```

Did you try to reproduce it without your custom server logic? Only event + console.log?

**Comment by edgarasx** [comment]
@litolax I couldn't reproduce the issue by myself, but players on our server keep experiencing it. The only thing I noticed is that it's only the `entityLeaveColshape` event that is causing issues and inside SafeZone.onPlayerLeave function we check if the player is inside the safe zone before removing him by doing:

```ts
static isEntityInSafeZone(entity: alt.Entity) {
        for (let index = 0; index < SafeZone.registrar.length; index++) {
            const colshape = SafeZone.registrar[index];

            if(colshape.isEntityIn(entity)) {
                return true;
            }
        }

        return false;
    }
```
So my guess it that it could be `colshape.isEntityIn(entity)` causing the issue, maybe sometimes the entity is removed from colShape before the leave event is fired? It used to work fine, but with v15 multithreading rework something might have changed.

**Comment by csskroubledev** [comment]
On release branch this seems to be fixed, as everything works as intended.

**Comment by FabianTerhorst** [comment]
there was no change related to colshapes between dev and release merge in alt:V Core.

**Comment by Arochka** [comment]
I encounter the same issue in release using C# module since v15.
Randomly colshape events are not triggered
