### ISSUE TITLE
Blush visible bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2083]
### Description of the problem

The overlay (blush) display of setHeadOverlay 5 on the character is incorrect. It looks completely different when set to the same value native than it does with the server-side function.

### Reproduction steps

1. Set server-side: player.setHeadOverlay(3, 5, 0.99); -> https://i.imgur.com/jstFotc.png
2. Set client-side: game.setPedHeadOverlay(localPlayer.scriptID, 3, 5, 0.99); -> https://i.imgur.com/Dg4w5vV.png

### Expected behaviour

-

### Operating system

Windows 11

### Version

#15.0-dev801

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
try again on latest dev server

**Comment by FabianTerhorst** [comment]
Fixed in dev 828.
