### ISSUE TITLE
Players can't hear one another inside a garage or appartment

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2085]
### Description of the problem

Players can't hear one another inside a garage, no volume settings seem to help. Tried various different garage interiors and appartment interiors, same thing.

### Reproduction steps

1) Go to position: new alt.Vector3(-1067.010986328125, -85.83296203613281, -90.2021484375)
2) Both players need to be in a non-global dimension, but same dimension for both players, for example: 1
3) Try to speak to another player

https://streamable.com/763665

### Expected behaviour

Voice should be heard inside a garage

### Operating system

Debian 11

### Version

15.1

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Yiin** [comment]
is it only in the garage, or everywhere in non default dimension?

**Comment by edgarasx** [comment]
> is it only in the garage, or everywhere in non default dimension?

Good point, checked it and it seems the issue is with changing the dimension, doesn't matter where you are.

**Comment by FabianTerhorst** [comment]
Try again on latest release build with updated server and voice server.

**Comment by edgarasx** [comment]
> Try again on latest release build with updated server and voice server.

All good on latest release build
