### ISSUE TITLE
Early Auth - Refused by Server with a Nickname length of 30+

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#2090]
### Description of the problem

When we use an altv nickname with a total length of 30+, we cant connect to a server with early auth.
If the server has early auth deactivated, theres no problem. But if you use early auth, the client get the message: "Refused by Server"

### Reproduction steps

Change you AltV Nickname to a 30+ sign. And then connect to a server with early auth activated.

### Expected behaviour

Dont crash

### Additional context

We also tried with deactivated early auth, and there we havnt this problem.

### Operating system

Ubuntu 20.04

### Version

Since v15

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by litolax** [comment]
Can not reproduce

**Comment by KyuubiDDragon** [comment]
Added a video: https://www.youtube.com/watch?v=Bbfeoa5RhcM

**Comment by FabianTerhorst** [comment]
Fixed in dev 825.
