### ISSUE TITLE
streamSyncedMetaChange new value problem

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2096]
### Description of the problem

The streamSyncedMetaChange will return the wrong value as the new value if you delete the given meta.

### Reproduction steps

Code:
```
player.setStreamSyncedMeta("test", true);
alt.setTimeout(function() {
alt.log("delete")
player.deleteStreamSyncedMeta("test");
}, 1000);

alt.on("streamSyncedMetaChange", function(entity, key, value) {
	if(key == "test") {
		alt.log("new value: " + value)
	}
})
```

Console log:
[04:27:45] new value: true
[04:27:46] delete
[04:27:46] new value: true

### Expected behaviour

-

### Operating system

Windows 11

### Version

#15.33, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
Fixed next dev build.
