### ISSUE TITLE
player.getDlcClothes() didn't return correct data

### ISSUE THREAD

**Issue by PlumeDreams** [altmp/altv-issues#2097]
### Description of the problem

use ` player.setClothes(id, drawable, texture, palette);` set any native clothes with drawable higher than 172
and use `player.getDlcClothes(id);` to get dlc data it will return incorrect

### Reproduction steps

like description

### Expected behaviour

`player.getDlcClothes(id);` return correct data

### Operating system

Windows 10

### Version

release/15.34

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by FabianTerhorst** [comment]
you have to use get clothes. the dlc getter now only works with dlc setter.

**Comment by FabianTerhorst** [comment]
next build dlc setter will return empty cloth when it got set with none dlc setter. also normal getter will return empty clothes when clothes got set with dlc setter.

**Comment by PlumeDreams** [comment]
how can i get cloth dlc with normal setter?

**Comment by FabianTerhorst** [comment]
you can't.
