### ISSUE TITLE
fuelLevel low value bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2098]
### Description of the problem

On the client side, if you set the fuelLevel to a low value, the vehicle will be hit by a collision, so you can't move it.

### Reproduction steps

alt.Player.local.vehicle.fuelLevel = 6 (It works well above a value of 6.)

### Expected behaviour

-

### Operating system

Windows 11

### Version

#15.36, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by xxshady** [comment]
Not sure if its bug, it could be intended behavior

**Comment by xxshady** [comment]
not a bug, see: https://youtu.be/tIDIWrV8_9A?t=228

**Comment by xxshady** [comment]
its gta behavior: https://youtu.be/o9MQX-0OOzo?t=158
