### ISSUE TITLE
Can't connect to the server after receiving timeout once

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#210]
## Steps to Reproduce
1. At server startup, operations that will burden it should be performed. In my case, it's aggregation of data from the database.
2. Run server.
3. Try to connect.
4. If you get a _[Error] Connection failed: Timed out_ message it's fine, other way go to step 2.
5. Try connect again.

## Context (Environment)
Because of this problem I have to restart the alt: V client every time I get a server timeout message.

## Detailed Description
![image](https://user-images.githubusercontent.com/32741786/62008056-286bca00-b155-11e9-9514-f5ef1ef5e3cc.png)

**Comment by MacieGx** [comment]
Fixed. Now its showing [17:41:40][Error] HTTP Request failed, curl code: 7
[17:41:40][Error] Connection failed: Error connecting to HTTP server

**Comment by MacieGx** [comment]
![image](https://user-images.githubusercontent.com/32741786/91917719-067e3880-ecc1-11ea-8a39-8300c394b40b.png)
However, the problem is still there.

**Comment by Lhoerion** [comment]
😛

**Comment by MacieGx** [comment]
The problem does not occur in our natural environment, it only happens when we screw up something and things take too much time to start. We screwed up yesterday, so we also managed to reproduce the bug. 😛

**Comment by FabianTerhorst** [comment]
Fixed with next update
