### ISSUE TITLE
LocalPed scriptID is set asynchronously

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-issues#2100]
### Description of the problem

After creating a client LocalPed instance, scriptID returns 0. The scriptID seems to be set asynchronously after instantiation.

### Reproduction steps

Create a resource with this client code :
```js
let ped;

ped = new alt.LocalPed('MP_M_Freemode_01', 0, new alt.Vector3(447.032, 5645.732, 750), alt.Vector3.zero);

alt.log('ScriptID before :', ped.scriptID); // 0

alt.setInterval(() => {
    alt.log('ScriptID after :', ped.scriptID); // OK
}, 1000)
```

### Expected behaviour

ScriptID be getted after instantiation

### Operating system

Windows and probably also Linux

### Version

dev/15.0-dev833

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by ThomasMarangoni** [comment]
As long as the ped isn't created by RAGE (GTA Engine), the scriptID is 0. This applies to all entities, because there can't be an scriptID, if the entity doesn't exist yet.

You need to await the creation of the entity.

**Comment by yannbcf** [comment]
To give more context, in order to create an entity you need to request the model in the engine which make their creation asynchronous

**Comment by FlorianV85** [comment]
> To give more context, in order to create an entity you need to request the model in the engine which make their creation asynchronous

Oh, ok! I thought it was only necessary to load the model when using createPed and not the alt:V functions. I thought LocalPed did this itself, as the ped appeared anyway.
