### ISSUE TITLE
alt:V voice - not supported input devices

### ISSUE THREAD

**Issue by JumpSpinn** [altmp/altv-issues#2103]
### Description of the problem

We have a few user they dont have the option to choose the right input device for the alt:v voice (voicemeeter and some other devices with a eq setup)

### Reproduction steps

Go to the settings and click on the input device if u have a not supported device, its not showing up

### Expected behaviour

That alt:v voice supports more input devices (voicemeeter etc.)

### Additional context

Screenshot from a user, he has no option to choose his voicemeeter or other devices
[https://cloud.breezident.dev/s/fdHsbt7WgTqtwSG/preview](url)

### Operating system

Windows

### Version

15.38 (release)

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by Tsumiki-Chan** [comment]
This is also true for GoXLR.

As I see it there's currently no Workaround (i.E. Setting the application Input/Output Device through windows).

**Comment by fiftyy** [comment]
Can confirm. GoXlr not supported.

**Comment by martonp96** [comment]
Should be fixed in dev already
