### ISSUE TITLE
getVehicleMod native bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2108]
### Description of the problem

I put the turbo (modType 18) in the vehicle. I can hear and experience that it is included, on the server side the getMod returns a good value, but on the client side the native does not return the same value at all. I tested it with several vehicles. (sultan2, futo and modded veh)

### Reproduction steps

Log:
[oneAdmin] SRUN command: player.vehicle.getMod(18) 
[oneAdmin] SRUN result: 1 
[oneAdmin] CRUN command: game.getVehicleMod(localPlayer.vehicle.scriptID, 18) 
[oneAdmin] CRUN result: -1 

### Expected behaviour

-

### Operating system

Windows 11

### Version

#15.46, branch release

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by lackos888** [comment]
This is not a bug of alt:V, this is intended GTA5 behavior.

Use https://natives.altv.mp/0x84B233A8C8FC8AE7 for some modtypes.
