### ISSUE TITLE
Display CloudID in the main menu

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#2116]
### Description of the problem

In order to be able to use the CloudID e.g. for the whitelist or to identify yourself, it would be good if it were displayed in the main menu next to the alt:V user name as ReadOnly

### Desired solution for the problem

Display the CloudID next to the alt:V user name in the main menu as readonly

**Comment by litolax** [comment]
A lot of people will photoshop it

**Comment by ThomasMarangoni** [comment]
Not possible from a technical perspective.

**Comment by zziger** [comment]
CloudID is only available after game has started (and therefore after connection has started).
As an alternative servers can show users their ID in the disconnect message.
