### ISSUE TITLE
alt:V Voice Action Cam

### ISSUE THREAD

**Issue by BenGamingGER** [altmp/altv-issues#2123]
### Description of the problem

[DE]
Wenn man im Auto, als Beifahrer mitfährt und die Action Cam (R) aktiviert kann es passieren das man die anderen Insassen nicht mehr hört. Passiert immer wenn die Action Cam aus dem Sprachradius geht.

[EN]
If you are a passenger in the car and the Action Cam (R) is activated, it may happen that you no longer hear the other passengers. Always happens when the action cam goes out of voice range.

### Reproduction steps

[DE]
Als Beifahrer R drücken

[EN]
As a passenger, press R

### Expected behaviour

[DE]
Dass man den Fahrer und die anderen Mitfahrer durchgehen hört.

[EN]
That you can hear the driver and the other passengers walking through.

### Operating system

Windows

### Version

15.57 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by zziger** [comment]
Point that tracks ingame sounds is located at the camera position. In cinematic mode on the outside camera all sounds will behave as if you're outside the vehicle, including voice.
