### ISSUE TITLE
[OpenVZ] posix_spawn: Permission denied (13)

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [altmp/altv-issues#2124]
### Description of the problem

On an `OpenVZ server` with `Debian 11.3` I get the following error message.

![image](https://github.com/altmp/altv-issues/assets/139617589/67707815-e7e9-4f3a-903c-5503c4a758fc)

### Reproduction steps

...

### Expected behaviour

...

### Operating system

Debian 11.3

### Version

rel/15.57

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
You need to give altv crash handler execution rights.
