### ISSUE TITLE
Audio panning in altv-voice

### ISSUE THREAD

**Issue by prdatur** [altmp/altv-issues#2125]
### Description of the problem

Currently it is not possible to change if a voice channel can be heared more to the left ear or right.
If there would be such a feature, we could better decide "i currently speak through the phone, because it is on the left side of my ears"

### Desired solution for the problem

Because this is a client side setting, it would be good, to add a new filter function
```
// 50% on left side
filter.setStereoVolume(0, 0.5);

// 100% on right side
filter.setStereoVolume(1, 1.0);
```

or

```
// left ---X---center-------right
filter.setPanning(0.25);
// left ----------X----------right
filter.setPanning(0.5);

// left -------center-------X
filter.setPanning(1.0);
```

**Comment by vadzz-dev** [comment]
Should be available on latest dev an optional argument to addVolumeEffect

Possible values:
-1: all channels (default)
1: left channel
2: right channel

`{
  // 75% on the left ear
  filter.addVolumeEffect(0.75, 0, 1);

  // 25% on the right ear
  filter.addVolumeEffect(0.25, 0, 2);
}`
