### ISSUE TITLE
Wrong model data type

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [altmp/altv-issues#2128]
### Description of the problem

Vehicles like a police car are negative and the `uint` data type only allows positive. A change here would make sense

![image](https://github.com/altmp/altv-issues/assets/139617589/1414a57e-eb65-4106-956d-43adc80d3424)

### Reproduction steps

/

### Expected behaviour

/

### Additional context

I'm not sure if this repository is correct, if not I'm sorry.

### Operating system

Windows 11 (64)

### Version

rel/15.57

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
All hashes are positive. You can just cast them to a unsigned data type when you look into older docs.
