### ISSUE TITLE
`Alt.LogInfo()` is not thread-safe

### ISSUE THREAD

**Issue by ghost** [altmp/altv-issues#2129]
### Description of the problem

As soon as I create a new thread in C# and use `Alt.LogInfo()`, it doesn't appear on a new line like `Alt.Log()`.

![image](https://github.com/altmp/altv-issues/assets/139617589/91a50ab9-58bc-4a6f-8b7c-2ee1b513d875)

### Reproduction steps

```C#
public override void OnStart()
{
    Thread test = new Thread(() => {
        Alt.LogInfo("AltV");
    });
    test.Start();
}
```

### Expected behaviour

![image](https://github.com/altmp/altv-issues/assets/139617589/aa44329c-49ec-43c9-9f6c-f96c8d3facb4)

### Operating system

Windows 11 (64)

### Version

rel/15.57

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment]
most likely related: https://github.com/altmp/altv-issues/issues/2109

**Comment by Doxoh** [comment]
please retest on latest version (16.2.39)
