### ISSUE TITLE
Spawning vehicle while/after jumping desyncs the vehicle/player

### ISSUE THREAD

**Issue by TheDutchDev** [altmp/altv-issues#2131]
### Description of the problem

https://medal.tv/games/gta-v/clips/1Fgrikz3qSyTsz/13uB6GgasnTD?invite=cr-MSxQbUosMzM3OTQ2NjEs

It doesn't happen 100% of the time, but it is fairly easy to reproduce.
We're not using any entity factories, custom classes etc etc. Just the base altV AltAsync.CreateVehicle and SetIntoVehicle methods.

### Reproduction steps

- run around
- jump once or twice or so
- spawn a vehicle via hotkey or command etc
- watch it bug out

### Expected behaviour

Should not bug out

### Additional context

Can't 100% confirm, but it seems to happen more often with bikes compared to cars.

Appears to have been reported before. So this may be marked as duplicate. https://github.com/altmp/altv-issues/issues/1174

### Operating system

Windows 10 x64

### Version

release v15

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-issues/issues/1174
