### ISSUE TITLE
New ``LocalPed`` doesn't trigger ``gameEntityCreate`` event

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-issues#2132]
### Description of the problem

The creation of a ``LocalPed`` is not listened to by ``gameEntityCreate`` event (client).

### Reproduction steps

1. Create a new LocalPed
2. Listen ``gameEntityCreate``
```js
alt.on('gameEntityCreate', (entity) => {
    alt.log('Entity created', entity.type); 
});
```

### Expected behaviour

When a new ``LocalPed`` is created, it should be listened to by ``gameEntityCreate`` event

### Operating system

Windows 10

### Version

15.0-dev895

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Use workd object stream in / stream out event.
