### ISSUE TITLE
`IObject.PlaceOnGroundProperly()` doesn't work

### ISSUE THREAD

**Issue by ThisAccountHasBeenSuspended** [altmp/altv-issues#2134]
### Description of the problem

If you call the function via C# (server side) and then call `IObject.Frozen = true`, the object will not be put on the ground.

### Reproduction steps

```C#
...
IObject obj = Alt.CreateObject(model, pos, rot);
obj.PlaceOnGroundProperly();
obj.Frozen = true;
...
```

### Expected behaviour

The object is placed on the ground and then frozen

### Operating system

Windows 11 (64)

### Version

release/15.60

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
PlaceOnGroundProperly In General Currently does not work ob Objects
doublicate of https://github.com/altmp/altv-issues/issues/1783
