### ISSUE TITLE
Everything doubles in latest version

### ISSUE THREAD

**Issue by Lukascc** [altmp/altv-issues#2142]
### Description of the problem

I don't know what happened but after chop shop update's compatibility update, everytime I spawn a vehicle or a ped (serverside, don't know nothing about client) i get them +1 (instead of 1 i get 2) same with other things too

### Reproduction steps

const model = "ig_lamardavis"; 
const position = new alt.Vector3(-1612.4176025390625 ,-951.94287109375, 13.0029296875); 
const rotation = new alt.Vector3(0, 0, 0); 

const newPed = new alt.Ped(model, position, rotation);
![Q54PrCR](https://github.com/altmp/altv-issues/assets/28227747/11a87d16-c563-4802-bd8f-c2d95a382321)
![xQIU5Xc](https://github.com/altmp/altv-issues/assets/28227747/1d391bb7-e184-4d3e-b353-6dca7f3ea202)

### Expected behaviour

So that nothing doubles..

### Operating system

Windows

### Version

dev/15.0-dev968

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Please test on empty gamemode and provide sample code when you get it reproduced there.

**Comment by MarcoTheGreatXD** [comment]
Similar sh**  after v15 release happened to me with some of my scripts, they started double executing everything i did, so i had to add filter, to filter the same two executions and send only one of them 
💀

**Comment by chaosfreak93** [comment]
Can't reproduce

**Comment by xxshady** [comment]
Can't reproduce
