### ISSUE TITLE
ClearTasks Not working after last GTA update

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#2143]
### Description of the problem

Using player.ClearTasks(); not working after Update

### Reproduction steps

Use: player.ClearTasks();

### Expected behaviour

To clear player Tasks

### Operating system

Win 11 & Ubuntu 22.04

### Version

release 15.66

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by ThomasMarangoni** [comment]
fixed in latest dev
