### ISSUE TITLE
altV Voice ignoring Audio Occlusions

### ISSUE THREAD

**Issue by TheNytech** [altmp/altv-issues#2147]
### Description of the problem

At some point if the user doesn't move and stands still for some time, the voice of this user ignores the audio occlusion of the portal and can be heard normally as if they were standing next to you. If you, for example, open and close the door the person is muffled again, only to be louder again later. 
The person who talks almost continuously remains muffled because he is always moving.

To rule out errors in the audio occlusion on my part, the test was carried out in Michael's house. A vanilla MLO

tl;dr:
Users who are constantly moving are muffled through portal audio occlusions. Users who stand still won't be muffled after some time.

### Reproduction steps

Go to an MLO that has Audio Occlusions (So basically any vanilla MLO) and have a person on each side of the door. one as the listener, one as the speaker. The speaker should walk in circles and talk a bit (Either with PPT or Voice activation.) He should stay muffled the whole time.
If the speaker stands still while talking, his voice will eventually ignore the audio occlusion of the door/portal after some time and can be heard without any muffle effect.

### Expected behaviour

The voice of people should always stay muffled if there is a door with audio occlusion properties between them and others.

### Additional context

Here is a [video](
https://www.youtube.com/watch?v=-w_6znr0yvQ) capturing the issue.
You can hear that the guy talking is muffled all the time because he is walking. 
The girl talking can be heard normaly, eventhough she is in the same room as the guy and should be muffled like him.

### Operating system

Windows 10

### Version

release 15.66 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by martonp96** [comment]
Should be fixed in dev972.
