### ISSUE TITLE
LocalStorage not shared between resources

### ISSUE THREAD

**Issue by RickTran** [altmp/altv-issues#2148]
### Description of the problem

LocalStorage not shared between resources

### Reproduction steps

resource A: 
```
alt.on('resourceStart', () => {
      alt.LocalStorage.set('player_hotkey', {
          mainmenu: altEnums.KeyCode.F2,
          inventory: altEnums.KeyCode.F3,
          char_info: altEnums.KeyCode.F4,
          setting: altEnums.KeyCode.F5,
      });
      alt.LocalStorage.save();
      alt.log(alt.LocalStorage.get('player_hotkey'));
})
```

resource B: 
```
alt.on('resourceStart', () => {
    alt.setTimeout(() =>{
        alt.log(alt.LocalStorage.get('player_hotkey'));
    }, 2000);
})
```

server.toml:
`
resources = [ 'resourceA', 'resourceB' ]
`

resource A print correct value
resource B print undefined

![image](https://github.com/altmp/altv-issues/assets/27629415/03f81260-0171-47fd-b863-89034cb4d749)

### Expected behaviour

resource B must same value as resource A

### Operating system

Windows

### Version

release/15.66

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by ThomasMarangoni** [comment]
Every resource has it isolated context, so this is intended behavior.
