### ISSUE TITLE
Vehicles don't spawn

### ISSUE THREAD

**Issue by h2e8c6g4x2** [altmp/altv-issues#2151]
### Description of the problem

Vehicles don't appear as for today.
No errors shown.
No crashes.

### Reproduction steps

let vehicle = new alt.Vehicle(['police', 'police2', 'police3', 'police4'][randomNumber(0, 3)], x, y, z, rx, ry, rz);
vehicle.rot = {
    x: rx,
    y: ry,
    z: rz
};

### Expected behaviour

Vehicles appear

### Operating system

Windows

### Version

15.0-dev974 (dev)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by h2e8c6g4x2** [comment]
Video: https://youtu.be/sZ1Ku_mN1OA

**Comment by FabianTerhorst** [comment]
You have to upgrade server to 976. Each dev version is not compatible with older server version.
