### ISSUE TITLE
[alt:V Voice] Seperate voice and ingame sounds

### ISSUE THREAD

**Issue by TheNytech** [altmp/altv-issues#2154]
### Description of the problem

Currently, altV Voice uses the same line as the GTA sound effects, meaning that increasing/decreasing the sound effect volume of GTA also de-/increases the voices of users in altV. 

Yes, the output volume slider in altV (F1) does lower/raise the voice of others, but they are still linked to the GTA sound volume which decreases the voice volume even more. And having the ingame sounds on the minimum setting plus the voice output on its highest is still too quiet. 
Sadly, this is very unfavorable because a lot of GTA's sounds can interrupt or somewhat annoy you. This is the case for engine sounds, sirens, weather sounds (mostly rain and thunder), the sounds of horns etc.

It is almost challenging to understand/hear other players when a police siren is close to your current position.

### Desired solution for the problem

A seperation of altV Voice and the ingame sounds would be a welcome change that will improve the altV Voice experience and its useability. So that changing the ingame sound level in GTA's options doesn't affect altV Voice at all.

### Additional context
https://www.youtube.com/watch?v=kNKmkmW0OPA

**Comment by ThomasMarangoni** [comment]
The 3d sounds from alt:Voice are calculated by RAGE (GTA V Game Engine). This makes it impossible to completely separate them from GTA V sounds.

A separation would mean, no occlusion audio in MLOs, no reverb effects etc.

**Comment by TheNytech** [comment]
Though I wish there was a direct way to solve this issue,I can see the how it'll negatively affect altV Voice! I will forward this task to our gremlins (devs) and hope they find a workaround!
Thanks for the answer!
