### ISSUE TITLE
Add VirtualEntity3D

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2157]
### Description of the problem

Related to https://github.com/altmp/altv-issues/issues/1934
Instead of adding a new argument (Extra calculation step) to `VirtualEntity`, it's a good idea to create a seperate class called `VirtualEntity3D`.
If alt:V developers prefer this issue to https://github.com/altmp/altv-issues/issues/1934, we can close that.

### Desired solution for the problem

Just like `VirtualEntity` class.

**Comment by FabianTerhorst** [comment]
position is already using all 3 dimension for comparising since v15.
