### ISSUE TITLE
Native function taskHandsUp sometimes crashes the game

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#216]
## Steps to Reproduce
It's not so easy to reproduce bcs as i said it's just happend sometimes.
That's my code:
```js
alt.on("keydown", (key: number) => {
    if(key !== 107) return;
    game.taskHandsUp(localPlayer.scriptID, 3000, 0, 0, false);
})

alt.on("keyup", (key: number) => {
    if(key !== 107) return;
    game.updateTaskHandsUpDuration(localPlayer.scriptID, 0);
    game.clearPedTasks(localPlayer.scriptID);
}) 
```

## Detailed Description
[altv_720_Steam_0x7ff618bc0000_c-31-07-2019 01-10-31.zip](https://github.com/altmp/altv/files/3451627/altv_720_Steam_0x7ff618bc0000_c-31-07-2019.01-10-31.zip)

It happened to two other people.
Always after clicking the + button or spamming.
Sometimes it worked for a long time.

**Comment by martonp96** [comment]
I couldn't reproduce the problem.
