### ISSUE TITLE
VirtualEntity's Z dimension works only on client

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2160]
### Description of the problem

Even though Fabian said [here](https://github.com/altmp/altv-issues/issues/1934#issuecomment-1868111014), `VirtualEntity` server side instances still ignore `Z` dimension.

Should I wait for it?
Or not supposed to be added on the server side?

### Reproduction steps

1. Spawn a `buzzard`.
2. Create a server side `VirtualEntity`.
3. Fly to the sky vertically (Press `W`).
4. After 10 meters, `worldObjectStreamOut` event will never invoked.
- Server side:
```js
import alt from 'alt-server';

const virtualEntityGroup = new alt.VirtualEntityGroup(128);
const player = alt.Player.getByID(1);

const virtualEntity = new alt.VirtualEntity(
    virtualEntityGroup,
    new alt.Vector3(
        player.pos.x,
        player.pos.y,
        player.pos.z
    ),
    10
);
```
- Client side:
```js
import alt from 'alt-client';

alt.on('worldObjectStreamOut', (object) => {
    console.log('~m~worldObjectStreamOut');
});
```

### Expected behaviour

Should work on server side too.

### Operating system

Windows 10

### Version

dev/16.0-dev9

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Fixed in next build.
