### ISSUE TITLE
[Serverside] The server crashes when a player dies by exploding car

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-issues#2165]
### Description of the problem

The server crashes when a player dies by exploding car

Error Message: Process finished with exit code -1073741819 (0xC0000005)

I use the newest jsv2 module dev/0.0-dev68

### Reproduction steps

alt.Events.onPlayerConnect(({ player }) => {
    player.model = 'mp_m_freemode_01';
    player.spawn({ x: 0, y: 0, z: 71 });
    player.giveWeapon('weapon_smg', 999, true);
});

alt.Vehicle.create({ model: 'vigero2', pos: { x: 0, y: 0, z: 71 } });

Then go onto the engine cover and shoot at the engine block until the car explodes

### Expected behaviour

no crash

### Operating system

Windows 10

### Version

16.0.0-dev.30

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xLuxy** [comment]
We had a little chat on Discord and he was unable to re-produce it on latest `dev` version.

**Comment by xLuxy** [comment]
Still happens on latest dev - it's module indepedant. There's also no crashdump id in server log after restarting the server.

**Comment by FabianTerhorst** [comment]
I need reproduction steps so that i can reproduce it locally.

**Comment by devpanda0** [comment]
It is actually the way I mentioned above, but it also happens sometimes when joining. What I still had last night is. I have to restart the client after the crash otherwise the server crash comes back immediately

**Comment by FabianTerhorst** [comment]
Please try again on latest dev build.

**Comment by devpanda0** [comment]
Error has been fixed. Thank you very much for the quick fix.

A quick question, since an update the player sometimes doesn't spawn where it should. Primarily only when reconnecting (by restarting the server), but rarely like this. According to the AltV it is at the place, but I am somewhere else
