### ISSUE TITLE
Game Close/Crash on LocalObject get on alpha/lodDistance values

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2166]
### Description of the problem

Accessing the alpha value of a LocalObject allworld
closes the client (no crash/crashreport)

found more
same for 
lodDistance

on latest dev and on release

### Reproduction steps

alt.LocalObject.allWorld.forEach((o) => {
alt.log("Object modelhash: " + o.model + " alpha: " + o.alpha);
});

### Expected behaviour

not close the game, get a value

### Operating system

Windows

### Version

dev/16.0.0-dev.38

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
![image](https://github.com/altmp/altv-issues/assets/1764570/e82501e2-e2a6-4bf1-88ea-98d6fbb83630)
this i happen on c#
Alt.OnClient("testobject", async () =>
{
    try
    {
        //var hhhh = await Alt.TakeScreenshotGameOnly();
        Alt.Log("Local Object count " + Alt.GetAllWorldObjects().Count);
        foreach (var o in Alt.GetAllWorldObjects())
        {
            Alt.Log("Object Model: " + o.Model + " alpha: " + o.Alpha);
        }
    }
    catch (Exception e)
    {


        Alt.Log("LocalObject Exception: " + e.ToString());
    }
});

**Comment by deluvas1911** [comment]
Confirmed on dev.73

**Comment by FabianTerhorst** [comment]
Try again in .75

**Comment by BluePeer** [comment]
tested with dev77
js and csharp bottom returns value , no crashes
