### ISSUE TITLE
Semi-trailers don't hook to the tractor

### ISSUE THREAD

**Issue by SCVNG3R** [altmp/altv-issues#2169]
### Description of the problem

Semi-trailers don't hook if they're spawned with **manualEngineControl()** enabled

![trailers-min](https://github.com/altmp/altv-issues/assets/45922722/bf2e14a2-221a-499b-8c0d-e855197153f6)

### Reproduction steps
```js
vehicle.manualEngineControl = true;
```
Spawn a truck and semi-trailer and attempt to hook up

### Expected behaviour

After backing up the tractor to the point where the 5th wheel aligns to the kingpin, the trailer should snap and attach to the tractor

### Additional context

SC version

### Operating system

Windows 10

### Version

dev/16.0.0-dev.57

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by C0kkie** [comment]
Should work in release

**Comment by Lekenthu** [comment]
> Should work in release

In the latest release branch (16.0.14) the trailer attach doesn't work anymore. manualEngineControl is not set on the trailer, I simply create the trailer and it cannot be hooked up.
