### ISSUE TITLE
Enable xenon mod automatically when setting headlight colour

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#217]
**Is your feature request related to a problem? Please describe.**
Vehicle HeadlightColor isn't working when vehicle xenon mod isn't enabled.

**Describe the solution you'd like**
Enable it automatically when HeadlightColor is used.

**Comment by LeonMrBonnie** [comment]
Available in next update

**Comment by zziger** [comment]
Will there be available some value like -1 to return lights to a default variant (xenon disabled, stock lights)?

**Comment by xxshady** [comment]
Doesn't work for me on dev-10.0/dev3

**Comment by C0kkie** [comment]
not working. Does not set the xenon mod and therefore no headlightColor

**Comment by FabianTerhorst** [comment]
Should now automatically enable the mod in next version.
