### ISSUE TITLE
entityHitEntity event stop working after few shots on objects

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#2170]
### Description of the problem

The entityHitEntity stop working after X hits(5 to 20 hits from my tests) on objects.

Only the object that received the shots are impacted, and if I go out the streaming range and come back it work again for X shots. 

I tried the event on different entities(peds, vehicles, object, localobject) but it seem to only happen on object or localobject.

### Reproduction steps

//Spawn an object:
const prop = new alt.LocalObject('bkr_prop_prtmachine_dryer', alt.Player.local.pos, alt.Vector3.zero)

//Add the listener:
alt.on('entityHitEntity', (damager, target, weapon) => {
    alt.log('entityHitEntity', damager.id, target.id, weapon)
})

//Give yourself a weapon:
native.giveWeaponToPed(alt.Player.local, alt.hash('weapon_assaultrifle'), 0, false, true)
native.setPedInfiniteAmmo(alt.Player.local, true, alt.hash('weapon_assaultrifle'))

Hit the object multiple times, after X shots the event is not triggered anymore

### Expected behaviour

The event should trigger each time

### Operating system

Windows 11

### Version

release/15.68

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
that is related to entity healt 0 at this point
so no issue, simply GTA Engine

**Comment by Arochka** [comment]
You are right it work thank you :)
