### ISSUE TITLE
Add more context to "Failed to load server.toml" error

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2172]
### Description of the problem

Right now altv-server prints this message when it fails to read server config because of wrong syntax

![image](https://github.com/altmp/altv-issues/assets/54737754/996c1ddb-9636-4bae-904d-d5f36d2cffc2)

### Desired solution for the problem

Add more context to error, for example wrong syntax at line, column (altcfg had it)

**Comment by vadzz-dev** [comment]
Should be done in 16.0.0-dev.110

**Comment by xxshady** [comment]
thanks
