### ISSUE TITLE
Player ped first person sync glitches

### ISSUE THREAD

**Issue by AWGshka** [altmp/altv-issues#2175]
### Description of the problem

When in first mode any sync of ped model is incorrect for other players.
Stop crounching (ctrl by default) in first person will result a t-pose.
Walking backwards is not visible for other players.

_**p.s. this occurs when setting "dlcWhitelist" in server.toml is set to [ "*" ]**_

### Reproduction steps

Turn first person mode by double tapping V (by default).

### Expected behaviour

Ped model to be synced when player is in first person mode.

### Additional context

https://youtu.be/a0hkWzaE6C4

### Operating system

Windows 11

### Version

release/15.68
dev/16.0.0-111

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by ThomasMarangoni** [comment]
Wildcards aren't supported, we plan to add a warning. You can fix it by removing the entry dlcWhitelist from server.toml
