### ISSUE TITLE
alt.WebView.destroy method doesn't clear events

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#218]
alt.WebView() events arent correctly removed/cleaned up when calling WebView.destory(). This results into multiple WebView.on() calls.

## Expected Behavior
When calling WebView.destory() creating the same WebView with same events should only trigger them one time.

## Current Behavior
WebView.on-Events are triggered multiple times. You need to do it multiple times to get this behavior.

## Possible Solution
No clue.

## Steps to Reproduce
Sample-Code
[webview-test.zip](https://github.com/altmp/altv/files/3456843/webview-test.zip)

## Context (Environment)
Workingbranch is BETA.

**Comment by kineese** [comment]
You need to adjust the URL in the samplecode!

**Comment by sab0h** [comment]
i can confirm this bug, actually was working around to figure out the problem

**Comment by 7Hazard** [comment]
Related: https://github.com/altmp/altv/issues/170

**Comment by 7Hazard** [comment]
Should be fixed in RC and dev
