### ISSUE TITLE
startLeavingVehicle event broken

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2182]
### Description of the problem

Client-side `startEnteringVehicle` and `startLeavingVehicle` events are broken if you try to enter or leave a vehicle.

### Reproduction steps

```js
alt.on('startLeavingVehicle', (vehicle, seat, player) => {
    alt.log('Leaving -------------');
});

alt.on('startEnteringVehicle', (vehicle, seat, player) => {
    alt.log('Entering -------------');
});

```

### Expected behaviour

Should trigger the event when you press the `F` button.

### Operating system

Windows 10

### Version

dev/16.0.0-dev.124

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by martonp96** [comment]
should be fixed in next dev build
