### ISSUE TITLE
Sync clearPedBloodDamage native function

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#219]
## Expected Behavior
game.clearPedBloodDamage will be synced

## Current Behavior
game.clearPedBloodDamage is not synced

## Steps to Reproduce
1. Spawn Hydra
2. Kill other player
3. execute game.clearPedBloodDamage(killedPlayerScriptID)
4. you will see clean player, the other player with was killed will still see a blood

## Detailed Description
![image](https://user-images.githubusercontent.com/32741786/62325787-becd2200-b4ac-11e9-8dd9-26194051d636.png)
![image](https://user-images.githubusercontent.com/32741786/62325794-c42a6c80-b4ac-11e9-9f6d-0bfb477f20e7.png)

Screenshot from two other players (its same player, he just change undershirt)

**Comment by FabianTerhorst** [comment]
What is when the killed player executes it on himself? Maybe the other player can't change it for him.

**Comment by MacieGx** [comment]
@FabianTerhorst Then he will see himself without blood, but the other player will still see blood.

**Comment by MacieGx** [comment]
And even when new player will come to server, he will see a blood.

**Comment by FabianTerhorst** [comment]
@MacieGx have you tested it? Or only from a other player

**Comment by MacieGx** [comment]
First, the player who had the blood on him execute function - for him was fine. I saw blood.

Then I execute the function and both of us didnt' see blood.

Then the third player joined the server and saw the blood.

We did it live time because we are using in game editor.

**Comment by TheSmilez** [comment]
I can second this as well.

**Comment by ithr0n** [comment]
Still not fixed in current beta (server #818)

**Comment by tastydev** [comment]
If u call this native on the bloody character the blood is cleared for all players in streaming range, everytime the cleared player/entity gets recreated on gameEntityCreate for others his body is bloody again. #build beta 1003

**Comment by tastydev** [comment]
any news here?

**Comment by martonp96** [comment]
fixed on latest dev
