### ISSUE TITLE
Magnitude issue

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#2192]
### Description of the problem

Vehicle.Velocity.GetMagnitude();
Returning odd high values

### Reproduction steps

Use for example: float Magnitude = player.Vehicle.Velocity.GetMagnitude();

### Expected behaviour

To return correct value

### Additional context

Issue started in alt:v 16

### Operating system

Linux 22.04

### Version

Release 16.0

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Serverside?

**Comment by TuK4z** [comment]
Yes sorry forgot to mention

**Comment by FabianTerhorst** [comment]
Test again on latest release.

**Comment by TuK4z** [comment]
Tested in 16.0.7 issue still exist

**Comment by FabianTerhorst** [comment]
This was fixed in 16.0.8. Feel free to reopen when it still happens. Make sure all clients updated to latest version otherwise it will happen again.

**Comment by TuK4z** [comment]
It's still exist in 16.0.12
I have created radars and using magnitude for them in serverside.
Magnitude is returned still to high. Could it be c# module issue?

This is log of action in image. I convert Magnitude *3.6 to KM / H, so in image text chat show different value.
Magnitude 720,61847

![image](https://github.com/altmp/altv-issues/assets/40861802/bcdd3d87-f3a8-47a8-af5d-6ee4a562f768)

**Comment by xxshady** [comment]
It's not C# issue

**Comment by FabianTerhorst** [comment]
Fixed in latest dev build.
