### ISSUE TITLE
Server-side clearTasks sync bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2193]
### Description of the problem

If you play an animation on the server side, and then stop it with clearTasks, you will stop the animation for yourself, but not for someone else who is near you.

### Reproduction steps

1. Play animation. (player.playAnimation)
2. Use player.clearTasks() in server-side.

### Expected behaviour

Work properly.

### Operating system

Windows 11

### Version

#16.0.0, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by martonp96** [comment]
should be fixed in dev163
