### ISSUE TITLE
OnPlayerWeaponChange event not working

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#2194]
### Description of the problem

Simply Alt.OnPlayerWeaponChange serverside doesn't working in latest version. Im using c#

### Reproduction steps

Alt.OnPlayerWeaponChange += (IPlayer player, uint oldWeapon, uint newWeapon) =>
{
    ConsoleWriter.Log($"Olwaa: {oldWeapon} New: {newWeapon}");
};

### Expected behaviour

Event to work

### Operating system

Linux 22.04 & Win11

### Version

Release 16

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by lLukDreams** [comment]
do you have in server toml this:

[antiCheat]
weaponSwitch = false

**Comment by FabianTerhorst** [comment]
Also it won't trigger anymore for weapons you set by serverside.

**Comment by TuK4z** [comment]
No im not using:
[antiCheat]
weaponSwitch = false

Sorry didint understood: "Also it won't trigger anymore for weapons you set by serverside."
Im setting weapons serverside.

**Comment by lLukDreams** [comment]
That's why it isn't triggering, if u use what I said it will. It won't trigger because u set weapons server side and in the new version it won't check since they are allowed to have the weapon

**Comment by TuK4z** [comment]
Tested with this param. Still event not working. Must be something else

**Comment by TuK4z** [comment]
Just to be clear it's server event that not working

**Comment by FabianTerhorst** [comment]
do you swap the weapon in your local client in the weapon wheel?

**Comment by TuK4z** [comment]
Nope, im suing serverside setter.

player.CurrentWeapon = ItemHash;
and
player.GiveWeapon(ItemHash, 0, true);

**Comment by FabianTerhorst** [comment]
it only triggers when you change weapon on clientside in weapon wheel.

**Comment by TuK4z** [comment]
Whaaat no way... Im using custom made inventory system with weapons are picked by number buttons.
But i guess no problem, i can make some handler to call method myself

**Comment by FabianTerhorst** [comment]
As explained earlier this isn't a bug but expected behavior.
