### ISSUE TITLE
Script Event Weapon Change - Show change to Fist if player enter streamrange

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#2195]
### Description of the problem

If a player enter the streaming range of another player, the script event weaponchange triggers and put out that the player switched to "fist" but it doesnt

### Reproduction steps

Log in with 2 Chars.

1. Char -> Get a Weapon
2. Char -> Go out of range, drive into the range

Now the weapon change event triggers and put out, that the player weapon switched to fist

### Expected behaviour

doesnt trigger or put out the right wepaon

### Operating system

ubuntu

### Version

16.0.7

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by KyuubiDDragon** [comment]
client side is fixed since 16.0.10. serverside c# is missing <3

**Comment by ThomasMarangoni** [comment]
@KyuubiDDragon another fix is in release, please test it again.
