### ISSUE TITLE
Animation getter not working on Linux

### ISSUE THREAD

**Issue by TuK4z** [altmp/altv-issues#2196]
### Description of the problem

Serverside Animation getter returning 0 on Linux

### Reproduction steps

Use: player.CurrentAnimationName or player.CurrentAnimationDict
Getter on Linux. Windows Working just fine.

### Expected behaviour

Getter to work

### Operating system

Ubuntu 22.04

### Version

Release 16.0.10

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Are we sure this isn't a module issue? Please test in js module as well.

**Comment by xxshady** [comment]
Works fine on js

**Comment by BluePeer** [comment]
works fine on 16.0.10 Debian 11 and Windows 10

**Comment by TuK4z** [comment]
In latest version it works on ubuntu 22.04 too, i don't know what issue was. Sorry for bothering.
