### ISSUE TITLE
alt.getPoolSize(pool) logs in F8 console

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#2197]
### Description of the problem

Calling alt.getPoolSize(pool) logs "pool <HASH>" in the F8 console.

### Reproduction steps

Call alt.getPoolSize(pool)

### Expected behaviour

Remove the log

### Operating system

Windows

### Version

16.0.10-release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.
