### ISSUE TITLE
hashResourceName and Resource.getByName

### ISSUE THREAD

**Issue by AWGshka** [altmp/altv-issues#2199]
### Description of the problem

Enabling hashResourceName in server.toml makes alt.Resource.getByName unable to find resource by it's name on client-side (since now name is hashed)

### Reproduction steps

Enable hashResourceName in server.toml
Create a resource1 with code alt.Resource.getByName("resouce2")
Create a resource2 with/out any code

### Expected behaviour

Resource should be found by name even if setting is true

### Operating system

Windows 11

### Version

release/16.0.10 & dev/16.0.0-149

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by AWGshka** [comment]
> @AWGshka can u please add if its clientside or serverside

Hashing changes the name of resources on the client. But just in case, added it for clarification.

**Comment by martonp96** [comment]
should be fixed in dev164
