### ISSUE TITLE
Client logs are deleted before creating new one

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2200]
### Description of the problem

/

### Reproduction steps

1. start client
2. client log is created
3. close client
4. start client again
5. old log is removed

### Expected behaviour

/

### Operating system

Windows 11

### Version

16.0.0-dev.149

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
Fixed with core 16.0.13 & launcher 16.0.6
