### ISSUE TITLE
Vehicle jumps/drives when spawned

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2202]
### Description of the problem

Sometimes when a new vehicle is spawned it automatically drives away. Also, sometimes when vehicles position is changed it jumps up into the air. 

https://streamable.com/dsocy6

### Reproduction steps

Spawn a vehicle server side

### Expected behaviour

Vehicle should be stationary

### Operating system

Debian 11

### Version

16.0.3

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by TuK4z** [comment]
We are using c# and on vehicle spawn there is no issue. Always spawns stationary, but on position change yes, there is issue since long time ago, we work around it with natives to place on ground properly.

**Comment by ThomasMarangoni** [comment]
Should be fixed, if it happens again please create a new issue.
