### ISSUE TITLE
Trailer hook bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2203]
### Description of the problem

Theoretically, in the latest release patch, the trailer attachment has been fixed (https://github.com/altmp/altv-issues/issues/2169). Well, it doesn't work for me with the latest release, even though the server has been updated (16.0.14). manualEngineControl is not set on the trailer, I simply create the trailer and it cannot be hooked up.

### Reproduction steps

-

### Expected behaviour

-

### Operating system

Windows 11

### Version

#16.0.14, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment]
Fixed in 16.0.0-dev.157
