### ISSUE TITLE
BaseObjectCreate event is not being called for RmlElement objects

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-issues#2209]
### Description of the problem

What the title says

### Reproduction steps

```ts
import * as alt from 'alt-client';

alt.on('baseObjectCreate', (object) => {
    alt.log("Base Object Created", object.constructor.name);
});

const document = new alt.RmlDocument("/client/index.rml");

const node = document.createElement("div");

alt.log("Node", node.constructor.name);
```

```
[V8] Starting script client/index.js 
Base Object Created RmlDocument 
Node RmlElement 
```

### Expected behaviour

BaseObjectCreate event should also be called for RmlElement objects, as they do extend BaseObject class.

cpp-sdk:
```cpp
class IRmlElement : public virtual IBaseObject
```

### Operating system

Win11

### Version

16.0.0-dev.173

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.

**Comment by xLuxy** [comment]
On latest dev Version, OnCreateBaseObject method receives nullptr when creating an RmlDocument. (Basically logging the type inside the methods):
Crashdump Id: 631f276d-858b-4d88-a4e2-3cf88a2a2087

**Comment by FabianTerhorst** [comment]
try again when 269 build is done.
