### ISSUE TITLE
player.AttachToEntity rotation

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#2217]
### Description of the problem

While trying to use C#
```
player.AttachToEntity(vehicle, "chassis", "SKEL_ROOT", position, rotation, true, false);
```
Even if we will pass the rotation, it will set randomly.

### Reproduction steps

Try to attach player to vehicle with desired rotation

### Expected behaviour

Player rotation to set properly

### Operating system

Windows 11

### Version

release/16.0.57

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
can't confirm
i get everytime the correct offset roation related to the vehicle entity
the rotation value is sure a offset static offset and not a current entity rotation?

**Comment by Avepy** [comment]
Will check this out and let you know, prob didn't realised that it's an offset, thought it is current rotation

**Comment by Avepy** [comment]
My bad, it works fine, big thanks to @BluePeer
