### ISSUE TITLE
Vehicle model sync bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2222]
### Description of the problem

A randomly occurring problem on my server is that a vehicle does not appear when you arrive at the streaming distance.
On the client-side, the model returns a null value.
I have just spoken to Heron about the problem in more detail and have sent him further information.

Debug log: https://i.imgur.com/CitYULn.png
(Top is the client side, bottom is the server side.)

### Reproduction steps

-

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #16.0.66, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Missing vehicle model was fixed some versions ago. It got added back into the broadcast as a fix.
