### ISSUE TITLE
Custom alt:V wrapper/function for taskScriptedAnimation

### ISSUE THREAD

**Issue by BuddiesTV** [altmp/altv-issues#2226]
### Description of the problem

[taskScriptedAnimation](https://natives.altv.mp/0x126EF75F1E17ABE5) is a native, that allows you to combine animations or even just play animations on "filtered" bones, so just on your left arm for example. But sadly it cannot be used from a alt:V resource, as it requires structs as arguments(priorityLowData, priorityMidData, priorityHighData)

### Desired solution for the problem

A wrapper in the core of alt:V to use this functions from our resources

**Comment by vadzz-dev** [comment]
You can use alt.MemoryBuffer to pass structs to natives
