### ISSUE TITLE
server: onStreamSyncedMetaChange event is not called for VirtualEntity

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-issues#2231]
### Description of the problem

onStreamSyncedMetaChange event is called for other entities (such as Vehicle), but not for VirtualEntity.

### Reproduction steps

```ts
import * as alt from '@altv/server';

alt.Events.onStreamSyncedMetaChange(props => {
    alt.log('Stream Synced Meta Change', props);
});

const veh = alt.Vehicle.create({
    model: 'adder',
    pos: alt.Vector3.zero,
});

veh.streamSyncedMeta.foo = 'bar';

const vg = alt.VirtualEntityGroup.create({
    maxEntitiesInStream: 10,
});

const ve = alt.VirtualEntity.create({
    group: vg,
    streamingDistance: 100,
    pos: alt.Vector3.zero,
});

// @ts-expect-error
ve.streamSyncedMeta.foo = 'bar';
```

![image](https://github.com/altmp/altv-issues/assets/9081457/7a261707-ef18-4a58-aa75-e9cf19e1796e)

### Expected behaviour

For the event to be called for VirtualEntity objects as well.

### Operating system

any

### Version

16.0.0-dev.226

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Fixed in next dev build
