### ISSUE TITLE
Can't connec to server after lost connee

### ISSUE THREAD

**Issue by DmitryChekh** [altmp/altv-issues#2235]
### Description of the problem

I can't connect to server after lost connection.
Buttons: home, connect, servers - doesnt work and not clickable

![image](https://github.com/altmp/altv-issues/assets/48753762/2aed8dc7-5d70-4d89-9533-faac4aae6f3c)

### Reproduction steps

Run local server, join and stop server. 

### Expected behaviour

I can connect to server after lost connection

### Operating system

Windows 10

### Version

16.0.80

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
this is not a bug , that is default.
you need server and client .toml debug=true
to use reconnect

after connect to a server you can only open settings or Quit
with debug=true (on bottom sides) you can use reconnect  button/console command

**Comment by xxshady** [comment]
Works as it is supposed to (at least for now)
