### ISSUE TITLE
gameEntityDestroy is not triggered for local objects

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#2236]
### Description of the problem

gameEntityDestroy is not triggered when local object is destreamed by alt:V

### Reproduction steps

Use this code to reproduce it, 'destroyed [id]' will be logged when object scriptID becomes 0

![image](https://github.com/altmp/altv-issues/assets/54737754/50529d99-fb46-4c6f-ad42-f1a6e21c7c62)

```js
import alt from 'alt-client'

alt.on('gameEntityCreate', (e) => {
    alt.log('gameEntityCreate', e, e.id)
    e.tick = alt.Utils.drawText3d(`${e.id}`, e.pos.add(0, 0, 0.3), 4, 0.5)

    const tick = new alt.Utils.EveryTick(() => {
        if (e.scriptID === 0) {
            alt.log('destroyed', e.id)
            tick.destroy()
            return
        }
    })
})

alt.on('gameEntityDestroy', (e) => {
    alt.log('gameEntityDestroy', e)
    e.tick?.destroy()
    e.tick = null
})

const obj = new alt.LocalObject('stt_prop_stunt_soccer_ball', new alt.Vector3(0, 1, 72), alt.Vector3.zero, true, false, true, 2)
obj.positionFrozen = true
```

### Expected behaviour

/

### Operating system

Windows 11

### Version

16.0.0-dev.235

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by FabianTerhorst** [comment]
Fixed in next dev build.
