### ISSUE TITLE
Serverside Blip issue

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2239]
### Description of the problem

in C# and JS
we have a issue with server side created Blip

There exist server side but only synced to client where connected at creation
after creation connected ppl don't get them

if you have serverside 10 Blips and connect , clientside 0
if you create serverside another then there are 11 and on client 1

repo code

### Reproduction steps

create blip , reconnect/rejoin (with debug or without)

[blip-repo.zip](https://github.com/altmp/altv-issues/files/14309259/blip-repo.zip)

### Expected behaviour

sync blip on connect

### Operating system

Linux/Windows

### Version

release 16.0.111 dev 16.0.0-dev.247

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
additional testing,

This issue looks related to the additonal c# resource
if i test the js only without active c# server module the code works (if you add player spawn)
but the reported issue is back on load a serverside c# resouirce

**Comment by BluePeer** [comment]
test case 1 player/person
if js and c# resource running
you get a working blip sync after connect 2 (multiple reconnects after that works)

c# resource only
after multiple reconnects sometimes the sync work (1 of 3~50)

**Comment by FabianTerhorst** [comment]
Doesn't seems to be a issue in latest dev.
