### ISSUE TITLE
Invisible driver issue

### ISSUE THREAD

**Issue by edgarasx** [altmp/altv-issues#2247]
### Description of the problem

Sometimes player drops out of a newly created vehicle which he is sat into. Yet he becomes the driver of the vehicle and appears as if the vehicle is driven by itself.

Video below shows our admin teleporting to a player who found this bug, when he teleports to him he appears at the position where the vehicle was spawned even though the player is driving the vehicle outside of the barn and the position should be different. Then you can see the vehicle being driven, even though the driver is not visible.

https://streamable.com/nq0mm2

### Reproduction steps

1) Create a large vehicle at position A.
2) Create another smaller vehicle at the exact same location and use `player.setIntoVehicle(smallerVehicle, 1)`
3) Result = sometimes (I'm guessing something to do with netOwner?) the driver disappears yet he can control the vehicle

Video below shows the steps taken by players in our production server. After spawning the vehicle the driver seems to fall out of the map (because the streamed players around him are being streamed out and the map is unloaded), yet he is still the driver of the vehicle. At that time player.vehicle returns null and player.pos returns a very different position from the vehicles position. You can even see that the players position stays the same on the mini-map (where the vehicle was spawned) even though he is driving away.

https://streamable.com/nq0mm2

Our temporary fix was simply not using player.setIntoVehicle function it seems to cause the issue.

### Expected behaviour

Player should not fall out of the vehicle

### Operating system

Debian 11 server, Windows client

### Version

16.0.125 release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
Sounds like the same issues as #1174
Can you confirm it's the same behaviour @edgarasx ? If so we could close this as a duplicate issue

**Comment by edgarasx** [comment]
> Sounds like the same issues as #1174 Can you confirm it's the same behaviour @edgarasx ? If so we could close this as a duplicate issue

Yeah, it seems to be the same issue

**Comment by deluvas1911** [comment]
Closed due duplicate then
