### ISSUE TITLE
Vehicle passengers count server side is not correctly sometimes

### ISSUE THREAD

**Issue by JumpSpinn** [altmp/altv-issues#2259]
### Description of the problem

I check the vehicle.passengers serverside and return true if passengers.Count is higher then 0. Sometimes the count is wrong and says that are passengers in inside although there are none inside

### Reproduction steps

> public async Task<bool> HasVehiclePassengers(UndefinedVehicle vehicle) {
>     try {
>         if (!Helper.IsVehicleValid(vehicle)) return false;
>         if (vehicle.Passengers is null) return false;
>         if(vehicle.Passengers.Count > 0) return true;
>     }
>     catch (Exception e) {
>         _ = Logger.Exception(e);
>     }
>     return false;
> }

### Expected behaviour

That the count is zero if no players inside the vehicle

### Operating system

Windows

### Version

16.0.143-release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by litolax** [comment]
Need more clean reproduction steps. I tried with js and c# and can not reproduce it. Feel free to reopen this issue if you will have video or more info about reproducion steps.
