### ISSUE TITLE
Event for unhandledExceptions / errors on client-side

### ISSUE THREAD

**Issue by dGxxxx** [altmp/altv-issues#2265]
### Description of the problem

I think it will be a good idea to have a event which catches all the errors generated on the client-side code. We can use this to catch all errors from server-players, without them having to report anything.

The current AnyResourceError (C#) doesn't do nothing regarding this kind of errors, so we cant use it for this purpose.

### Desired solution for the problem

Add ResourceException / ResourceError as client event.

### Alternatives you considered

Use Try - Catch all over the code.

**Comment by xxshady** [comment]
if its c# related you can open issue inc# module repo

**Comment by dGxxxx** [comment]
> if its c# related you can open issue in c# module repo

I will test on JS, and if its only c# related, I will open repository there.

**Comment by xxshady** [comment]
js module has resourceError & anyResourceError events

**Comment by dGxxxx** [comment]
> js module has resourceError & anyResourceError events

thank you. will open on C# module.
