### ISSUE TITLE
getTattooShopDlcItemData native not working latest release

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2268]
### Description of the problem

Since the last release the getTattooShopDlcItemData native does not work.

### Reproduction steps

Example code: https://discord.com/channels/371265202378899476/1061638230107238470/1061638230107238470

Error message:
[one_appearance:client.js:1681] Native argument at index 2 (object) could not be parsed to type struct (getTattooShopDlcItemData) 
Check the documentation for the needed arguments of this native. 
Native call failed: getTattooShopDlcItemData 
Exception offset: 0xA80C1C 
Exception code: C0000005 
Error code: 0 
[V8] Exception at one_appearance:client.js:1681 
game.getTattooShopDlcItemData(characterType, i, buffer) || {}; 
Error: Native call failed
    at client.js:1681:12 
Error: Native call failed 

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #16.0.149, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by nortages** [comment]
Same, but with the getEventData native.

**Comment by Lekenthu** [comment]
Fixed.
