### ISSUE TITLE
Troubleshooting Server Launch Issues.

### ISSUE THREAD

**Issue by saintedlittle** [altmp/altv-issues#2271]
### Description of the problem

`
[3233:3233:20240407,202525.657024:FATAL spawn_subprocess.cc:221] posix_spawn: Permission denied (13)
[3231:3231:20240407,202525.724917:WARNING spawn_subprocess.cc:245] intermediate process terminated by signal 5 (Trace/breakpoint trap) (core dumped)
[3245:3245:20240407,202525.768212:FATAL spawn_subprocess.cc:221] posix_spawn: Permission denied (13)
[3231:3231:20240407,202525.838615:WARNING spawn_subprocess.cc:245] intermediate process terminated by signal 5 (Trace/breakpoint trap) (core dumped)
`
The first launch of the server was downloaded using your configurator. Immediately throws a mistake.

### Reproduction steps

Attempt to launch the alt:V server.
Observe the logs for any errors or warnings reported during the launch process.
Note the occurrence of errors such as posix_spawn: Permission denied (13) and warnings indicating process termination with signal 5 (Trace/breakpoint trap).

### Expected behaviour

No errors or warnings.

### Additional context

The provided logs highlight critical errors and warnings during the server launch process. Notably, errors like posix_spawn: Permission denied (13) and warnings about intermediate process termination with signal 5 (Trace/breakpoint trap) indicate potential permissions and debugging issues. It's essential to address these to ensure server stability and performance.

### Operating system

Fedora Linux 39 (Server Edition) x86_64

### Version

alt:V Server 16.0.151 (release)

### Crashdump ID

N/A (No specific crashdump ID provided)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by devpanda0** [comment]
give `altv-crash-handler` execute perms

**Comment by xLuxy** [comment]
Run `chmod +x altv-crash-handler`
