### ISSUE TITLE
Add client-based authorization system for additional features

### ISSUE THREAD

**Issue by indilo53** [altmp/altv-issues#230]
**Is your feature request related to a problem? Please describe.**
Actually, screenshots are enabled only in sandbox

**Describe the solution you'd like**
A promise-based modal window explaining the treadeoffs of enabling the feature to let user decide what he want

**Describe alternatives you've considered**
Checkboxes in main menu

**Additional context**
None

**Comment by 7Hazard** [comment]
I think that we discussed in the future that message notifications will pop up from the side when the server attempts to use a certain feature that requires permission.

**Comment by martonp96** [comment]
This was implemented in dev branch some weeks ago.
