### ISSUE TITLE
SetWheels not work

### ISSUE THREAD

**Issue by kernkode** [altmp/altv-issues#2309]
### Description of the problem

I try to put a wheel on my vehicle but it does not change, does not give errors and does not throw exceptions.

### Reproduction steps

```ts
let vehicle = new alt.Vehicle("comet6", player.pos.x, player.pos.y, player.pos.z, 0, 0, 0);
vehicle.setWheels(0, 4);
```

### Expected behaviour

I was hoping that the wheel would be put on or at least pull exception

### Additional context

none

### Operating system

windows 10

### Version

16.1.1 (release)

### Crashdump ID

none

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by devpanda0** [comment]
try to set the modkit first then change the weels
