### ISSUE TITLE
types-natives drawMarker parameter needs to be nullable

### ISSUE THREAD

**Issue by nordpoldieb** [altmp/altv-issues#2312]
### Description of the problem

The textureDict and textureName parameter in the drawMarker types need to also accept null. If you just put in empty strings the native call fails.

### Reproduction steps

```
// This native call fails because of the two empty strings
const everyTick = alt.everyTick(() => {
    const pos = alt.Player.local.pos;
    native.drawMarker(1, pos.x, pos.y, pos.z - 1, 0, 0, 0, 0, 0, 0, 5, 5, 1, 57, 192, 216, 100, false, true, 2, true, "", "", false);
});

alt.setTimeout(() => {
    alt.clearEveryTick(everyTick);
}, 10 * 1000);
```
```
// This native call works because the two parameter are null, but the types need to be ignored
 const everyTick = alt.everyTick(() => {
    const pos = alt.Player.local.pos;
    // @ts-ignore
    native.drawMarker(1, pos.x, pos.y, pos.z - 1, 0, 0, 0, 0, 0, 0, 5, 5, 1, 57, 192, 216, 100, false, true, 2, true, null, null, false);
});

alt.setTimeout(() => {
    alt.clearEveryTick(everyTick);
}, 10 * 1000);
```

### Expected behaviour

The drawMarker native should also accept null for those two parameters
```
 const everyTick = alt.everyTick(() => {
    const pos = alt.Player.local.pos;
    native.drawMarker(1, pos.x, pos.y, pos.z - 1, 0, 0, 0, 0, 0, 0, 5, 5, 1, 57, 192, 216, 100, false, true, 2, true, null, null, false);
});

alt.setTimeout(() => {
    alt.clearEveryTick(everyTick);
}, 10 * 1000);
```

### Operating system

Windows

### Version

alt:V v16.1.2 - @altv/types-natives 16.2.0

### Confirmation of issue's presence

- [ ] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by S0P4** [comment]
Types are opensource, https://github.com/altmp/altv-types you can change it an make a pull request whit the change.

**Comment by nordpoldieb** [comment]
Thanks for your quick response. PR is open: https://github.com/altmp/altv-types/pull/321

**Comment by xxshady** [comment]
natives typings are generated, you shouldn't change them manually

**Comment by xxshady** [comment]
https://github.com/altmp/altv-native-gen

**Comment by C0kkie** [comment]
Adjust it here: https://github.com/alloc8or/gta5-nativedb-data

**Comment by xxshady** [comment]
i think its oversight in alt:V natives generator

**Comment by xxshady** [comment]
https://github.com/altmp/altv-issues/issues/1756#issuecomment-1493039888

but it should be fixed already xd

**Comment by xxshady** [comment]
https://github.com/altmp/altv-native-gen/commit/b440d8bf1b78d7f240ebbcc0ce9f8bf198e54c82

**Comment by xxshady** [comment]
fixed in latest typings
