### ISSUE TITLE
Visible Setter not Working

### ISSUE THREAD

**Issue by Alessandro18K** [altmp/altv-issues#2316]
### Description of the problem

When you use player.Visible = false; on ServerSide (C#) or game.setEntityVisible(alt.Player.local.scriptID, false, false) on Javascript side both only work for that player but all other players can see the player

### Reproduction steps

Use player.Visible = false on C# or game.setEntityVisible(alt.Player.local.scriptID, false, false) on Javascript

### Expected behaviour

That the player is Visible for all players not only for himself

### Operating system

Debian

### Version

release/16.1.6

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
https://github.com/altmp/altv-issues/issues/2211
