### ISSUE TITLE
 reloadVehiclePhysics broken

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2324]
### Description of the problem

By calling `alt.HandlingData.reloadVehiclePhysics(alt.hash('adder'))`, client will crash.

### Reproduction steps

1. Spawn `adder`.
2. Enter to the `adder`.
3. Call `alt.HandlingData.reloadVehiclePhysics(alt.hash('adder'))`.
4. Client crash.

### Expected behaviour

Should not crash.

### Operating system

Windows 10

### Version

release/16.2.1

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment]
fixed on latest rc
