### ISSUE TITLE
Disable strict type check for setPedUsingActionMode

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2325]
### Description of the problem

I need to call `setPedUsingActionMode` with `0` instead of `'DEFAULT_ACTION'`.
1. [Disable combat mode after shooting](https://forum.cfx.re/t/disable-combat-mode-after-shooting/5016128/6)
2. [action is either 0 or "DEFAULT_ACTION"](https://natives.altv.mp/0xD75ACCF5E0FB5367)

>You might consider using using SetPedUsingActionMode(playerPed, false, -1, 'DEFAULT_ACTION') instead, however, this will not block this stance after melee combat.

### Reproduction steps

```js
import alt from 'alt-client';

alt.on('taskChange', () => {
    alt.setTimeout(() => {
        native.setPedUsingActionMode(alt.Player.local, false, -1, 0);
    }, 500);
});
```
```toml
Native argument at index 3 (number) could not be parsed to type string
```

### Expected behaviour

Allow us to pass `int` as the last argument.

### Operating system

Windows 10

### Version

release/16.2.1

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by xxshady** [comment]
did you try to pass null?

**Comment by mrgharabaghi** [comment]
Yes. `null` value works for shooting with weapons, but doesn't work for melee combat.

**Comment by xxshady** [comment]
![it-is-what-it-is-it-is](https://github.com/user-attachments/assets/2932e1e6-4965-4b40-945e-9ec4fd3c7133)

**Comment by mrgharabaghi** [comment]
I test the `SET_PED_USING_ACTION_MODE` with `Script Hook SDK` in GTA V Story Mode.
Works fine for shooting, but it doesn't work for attacking with fist.
```cpp
void update()
{
    PED::SET_PED_USING_ACTION_MODE(PLAYER::GET_PLAYER_PED(-1), false, -1, 0);
}
```
