### ISSUE TITLE
handlingFlags setter is broken

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#2336]
### Description of the problem

The value of `vehicle.handling.handlingFlags` changed but doesn't affect on vehicle.
I use `200` as `NO_REVERSE`. [GTA5VehicleFlagTool](https://adam10603.github.io/GTA5VehicleFlagTool/)

### Reproduction steps

```js
import alt from 'alt-client';

alt.on('enteredVehicle', (vehicle) => {
    vehicle.handling.handlingFlags = 200;
    alt.log('FLAG >', vehicle.handling.handlingFlags); // FLAG > 200

    // Remove NO_REVERSE flag
    alt.setTimeout(() => {
        vehicle.handling.handlingFlags = 0;
        alt.log('FLAG >', vehicle.handling.handlingFlags); // FLAG > 0
    }, 5000);
});
```

### Expected behaviour

I need to disable and enable the reverse gear via `handlingFlags`.

### Additional context

No

### Operating system

Windows 10

### Version

release/16.2.5

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest developer version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
https://forge.plebmasters.de/vehicleflags?category=HandlingFlags&value=200
never tested that stuff but wrong value?

**Comment by mrgharabaghi** [comment]
That's true, thank you so much.
I used [that](https://adam10603.github.io/GTA5VehicleFlagTool/) page long time ago.
`512` is the correct value of `NO_REVERSE` for the real-time modification.

**Comment by x90nik** [comment]
@BluePeer
> 200 looks wrong for a single value

`200` is a hexadecimal value. I should've had to set the `handlingFlags` like this: `vehicle.handling.handlingFlags = 0x200;`
