### ISSUE TITLE
Vehicles doesn't get destroyed when removed with player inside

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#234]
The https://github.com/altmp/cpp-sdk/blob/master/IResource.h#L57 isn't called when calling https://github.com/altmp/cpp-sdk/blob/master/IServer.h#L70 on a vehicle with a player inside.

## Expected Behavior
https://github.com/altmp/cpp-sdk/blob/master/IResource.h#L57 should trigger to make it possible for the method to cleanup the vehicle.

## Current Behavior
The method isn't triggered and the vehicle can't be removed from pool.

## Possible Solution
Destroy the vehicle correctly with players inside.

## Steps to Reproduce
1. Create a vehicle.
2. Set a player inside.
3. Destroy the vehicle.

## Context (Environment)
#735 beta

**Comment by ZackaryH8** [comment]
Seems to be fixed on `release/2.8`

**Comment by FabianTerhorst** [comment]
yes its already fixed.
