### ISSUE TITLE
RPF resource are no longer loaded with wildcard

### ISSUE THREAD

**Issue by shloooo** [altmp/altv-issues#2341]
### Description of the problem

When using `vehicles/*` all `rpf` resources are ignored

### Reproduction steps

Add a rpf resource and load them using `path/to/*`

### Expected behaviour

`rpf` resources should be loaded

### Additional context

This issue only happens when using `.../*` (... is the path), when using, for example, `vehicles/test` it works

### Operating system

Ubuntu 24.04

### Version

16.2.7-rc.7

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
can you specific with toml examples
it sounds like
issue on enter in server.toml or on the resource side with client-files, can you specific the issue location with content of .toml files ?

**Comment by shloooo** [comment]
It is definitely not a problem in any config as it worked a few days ago. There was also a recent update -> `Wildcard support for resources parameter in the toml`. ^^

**Comment by shloooo** [comment]
Fixed with 16.2.7-rc.8
