### ISSUE TITLE
New logs not stacking

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#2344]
### Description of the problem

New logs are not longer stacking, so now we can see some logs like:
```
xxx
xxx
xxx
```
instead of:
```
xxx [3]
````

I assume that it is not intended, so marked it as bug

### Reproduction steps

Log something `N` times on client

### Expected behaviour

Proper stacking of logs as it was before the 'more detailed' logs, it was kind of essential.
Now it is just really hard to catch some things between repeated logs

### Operating system

Windows 11

### Version

release/16.2.8

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by MellKam** [comment]
@Avepy Hey! I can't seem to reproduce your issue. Can you provide a screenshot/video of the console where you didn't get the stacking behavior and the message that doesn't stack? That would really help

**Comment by Avepy** [comment]
@MellKam It seems to be fixed right now. Thank you for reaction
