### ISSUE TITLE
Reduced download speed

### ISSUE THREAD

**Issue by cryptocoder-cloud** [altmp/altv-issues#2348]
### Description of the problem

I'm in Russia. My ISP has deliberately reduced the speed of your servers. The download speed became 200 kb/s. The Internet allows you to reach speeds of up to 500 mbps

### Reproduction steps

I'm in Russia. My ISP has deliberately reduced the speed of your servers. The download speed became 200 kb/s. The Internet allows you to reach speeds of up to 500 mbps

### Expected behaviour

Start downloading the Launcher

### Additional context

Internet provider - MGTS

### Operating system

Windows 10

### Version

16.2

### Crashdump ID

-

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by chaosfreak93** [comment]
Hello,

The download speed depends on the server you are playing on. alt:V has nothing to do with the download speed of the servers, as it is not responsible for their infrastructure.

**Comment by GVMP** [comment]
Modern Warfare, limit access to alt:V servers

**Comment by on1kson** [comment]
тебе удалось решить проблему? у меня тоже самое

![Image](https://github.com/user-attachments/assets/c8c917a3-4cf5-4aa8-8a0d-ff3040fcd2a6)

![Image](https://github.com/user-attachments/assets/d3e7de6f-a750-4577-ab92-0648a535973c)
