### ISSUE TITLE
ENB Crash AltV

### ISSUE THREAD

**Issue by Everik55** [altmp/altv-issues#2349]
### Description of the problem

When logging in to the server, the game simply freezes if ENB and Nvidia app overlay are installed. If you disable the overlay or use GeForce Experience, this problem will not occur.

### Reproduction steps

1. Install ENB
2. Enable the Nvidia App overlay
3. Join the server via AltV or Majestic Launcher

### Expected behaviour

There are no problems logging into the server from the enb

### Additional context

The problem is that a large number of players use ENB to improve the game, by the end of the year Nvidia will transfer all users to the Nvidia app

### Operating system

Windows 11

### Version

16.2.13 release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by devpanda0** [comment]
alt:V doesn´t support client mods

https://docs.altv.mp/articles/troubleshooting/client-mods.html
