### ISSUE TITLE
Entities aren't deleted on any subsequent reconnect

### ISSUE THREAD

**Issue by aviadmini** [altmp/altv-issues#235]
Something weird happening with reconnects:

- on script start I create a ped
- on 'disconnect' I use `deleteEntity` on ped handle

This works fine on first use of `reconnect`, but on subsequent uses the entities don't get deleted

## Expected Behavior
Peds should be deleted every time

## Current Behavior
Peds are deleted on first reconnect, and not deleted on any subsequent reconnects.

## Steps to Reproduce

use script
```js
import * as alt from "alt";
import * as game from "natives";

let handle = game.createPed(4, 0x705E61F2, -1379.665039, 51.105522, 53.053589, false, true);
alt.log(`created ped with handle: ${handle}`);

alt.on('disconnect', () => {
  alt.log(`Deleting ped with handle: ${handle}`);
  game.clearPedTasksImmediately(handle);
  game.deleteEntity(handle)
});
```

1. reconnect once, ped is deleted
2. reconnect second time, ped is not deleted

Same issue happens to `deleteObject` and probable some other natives

**Comment by MacieGx** [comment]
I confirm, sometimes I get a similar issue with deleting objects.

**Comment by martonp96** [comment]
same for removeModelHide

**Comment by martonp96** [comment]
Issue will be tracked in #193.
