### ISSUE TITLE
Wrong .NET Version Docker Image 16.2.14-rc.1

### ISSUE THREAD

**Issue by CodesHeaven** [altmp/altv-issues#2350]
### Description of the problem

The latest docker image for rc-branch 16.2.14-rc.1 comes with .net 6 installed, instead of .net 8
![image](https://github.com/user-attachments/assets/4f889d39-b168-40ae-9b3c-59abf160f8bd)
![image](https://github.com/user-attachments/assets/2ff9d070-2418-47f9-885c-4f849e17f3a7)

### Reproduction steps

![image](https://github.com/user-attachments/assets/1d3442cf-67ee-4d8b-9977-e681d8a9ae35)

### Expected behaviour

Docker Container should not throw message: "missing ,net sdk 8.0"

### Operating system

Docker Image

### Version

16.2.14-rc.1

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
https://hub.docker.com/layers/altmp/altv-server/16.2.14-rc.1/images/sha256-739159080ec413336f20c23cb32b632ee89bb78f9661bf963a57ad4bec808174?context=explore

is updated to dotnet 8 and node 22.8

please test again

**Comment by CodesHeaven** [comment]
Fixed
![image](https://github.com/user-attachments/assets/13f9ae80-c2c7-4b30-a952-d362ab9a86a9)
