### ISSUE TITLE
server start issue without predefined server.toml

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2351]
### Description of the problem

on windows/linux
the server process does not launch without a predefined server.toml
and gives no reasons why

on windows it only echo a timestamp with blank space and exit
on linux it outputs 

[1100185:1100185:20241003,181955.960019:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1100185:1100185:20241003,181955.960056:ERROR file_io_posix.cc:144] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)

same like missing rights

current release and RC make this

### Reproduction steps

start server exe on windows/linux without server.toml

### Expected behaviour

like in old days
generate a default server.toml file and start, 
or output a message "missing server.toml" and exit

### Operating system

Win/Linux

### Version

16.2.14-rc.1

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
fixed with 16.2.15
