### ISSUE TITLE
.NET 8 Not found on RC Branch Client Side

### ISSUE THREAD

**Issue by CodesHeaven** [altmp/altv-issues#2352]
### Description of the problem

the latest release of rc branch does not provide .net8 client support
![image](https://github.com/user-attachments/assets/e6ce263c-bedc-492d-91c7-3f7aeccdb2e4)

### Reproduction steps

1. Create C# Client Resource  (.NET 8)
![image](https://github.com/user-attachments/assets/572ac05d-d8da-4a68-b1f9-acf588a90894)
2. Start Alt:V on RC Branch
3. Connect to server

### Expected behaviour

Console output: "Hello from APEX.Client!"

### Operating system

Windows

### Version

RC

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
should be fixed

**Comment by CodesHeaven** [comment]
@Doxoh its broken again. 9 hours ago it worked. Changed nothing
 
![image](https://github.com/user-attachments/assets/59731dae-5f90-4c50-bf17-a3e2f0bdead9)

**Comment by Doxoh** [comment]
yeah, @CodesHeaven I saw, someone messed up the latest rc update
The team working on it
