### ISSUE TITLE
cdn alt.loadYtyp problem

### ISSUE THREAD

**Issue by MosIbOad** [altmp/altv-issues#2355]
### Description of the problem

when i load the dlc.rpf file as source, if it has the .ytyp file in it, when i load it with cdn i cannot access the .ytyp files. i tried this in modded objects. alt.loadYtyp cannot access the .ytyp files in cdn. when i try this on my local server and on a server without cdn, alt.loadYtyp works fine, but when i try it on a server with cdn it cannot load the .ytyp files. In short, I think that the .ytyp files in dlc.rpf are not loaded when I load them with alt.loadYtyp on the cdn server.

### Reproduction steps

https://www.mediafire.com/file/nahatke859322za/SoupObjectMappingKit.rar/file If you download the object package in this link and add the folders as resource rpf in an example way, the .ytyp files inside are not loaded with cdn.

### Expected behaviour

you can see the problem when you install cdn with a dlc containing any .ytyp

### Operating system

ubuntu 22.04

### Version

16.2.14 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
16.2.14 release on debian server
0 issues with load this 2 dlc.rpf files as cdn
resources 2 testdlc and testdlcb
testdlc/dlc.rpf (38MB)
testdlcb/dlc.rpf (294MB)
(identical if i use the forldernames)
bottom generated (without refered visual issues)
correct size, part of the connect.json
client can download and load the files
the dlc related autoload of the ytyp files works too

sound like you have a special not posted setup related issue?

and btw there is no usecase for alt.loadYtyp in this case the dlc contains a automatic load of the ytyp files

**Comment by MosIbOad** [comment]
server-files > resources > bareinteriors > dlc.rpf
server-files > resources > interiordesigner > dlc.rpf

This is how I specify the resources above and load the ytyp's contained in them. loadYtyp code (client-side-js):
```js
alt.on('connectionComplete', async () => {
    await alt.Utils.wait(3000);
    await loadYtyps(['soupbareinteriors', 'soup_objects']);
    alt.loadDefaultIpls();
});

async function loadYtyps(ytypList, delay = 3000) {
    for(let i = 0; i < ytypList.length; i++) {
    const ytypName = ytypList[i];
    const isLoaded = alt.loadYtyp(ytypName);
    alt.log(`${ytypName} ytyp loaded: ${isLoaded}`);
    await alt.Utils.wait(delay);
    }
}
```

server without cdn (no problem): https://i.imgur.com/Xsynfuz.png
server with cdn (texture issues, ytyp in my opinion): https://i.imgur.com/iyXhm8U.png https://i.imgur.com/CVclCvF.png https://streamable.com/sgrzvb

**Comment by MosIbOad** [comment]
a mistake on my part. no problem for now
