### ISSUE TITLE
Removed .NET 8 Support on Release Docker Image

### ISSUE THREAD

**Issue by CodesHeaven** [altmp/altv-issues#2359]
### Description of the problem

![image](https://github.com/user-attachments/assets/ca32be18-390d-43bf-b85b-5e22a75db188)

### Reproduction steps

altmp/altv-server:release

### Expected behaviour

No error message

### Operating system

Linux Docker image

### Version

altv-server:release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
https://github.com/altmp/altv-docker/issues <--

**Comment by Doxoh** [comment]
@CodesHeaven still?
