### ISSUE TITLE
Server CLI Argument --logfolder does not work

### ISSUE THREAD

**Issue by leoms1408** [altmp/altv-issues#2361]
### Description of the problem

According to https://docs.altv.mp/articles/commandlineargs.html#server-launch-options there is a Command-line Argument named --logfolder where the Server Log file should be located. This Argument does not work. 

Is it in general possible to keep the Server Logs even after a Server Restart using `Alt.StopServer();`?

### Reproduction steps

Setup an altv-server and start the Server using the CLI Argument `--logfolder /path/to/folder`

### Expected behaviour

Inside this folder, the server.log or a similar file should be created. 

### Operating system

Ubuntu 22.04.5 LTS

### Version

16.2.16 (release)

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by leoms1408** [comment]
Also according to this. When I start my server with the argument --logfile /var/log/altv a file called server.log_2024-11-02 will be created but when I restart the server 5 min later the new log will not be posted in this file and no new file will be created

**Comment by shloooo** [comment]
The option doesn't really exist. See https://discord.com/channels/371265202378899476/557307592129511444/946415242047533130

It's a flag but not really more

**Comment by BluePeer** [comment]
https://docs.altv.mp/articles/configs/server.html
```
# How many log files to keep in the "logs" directory (created automatically by alt:V)
# Set to 0 to disable "logs" directory (default behavior)
# For example, logsToKeep = 3 will set limit to 3 files in default server mode + 3 files for --justpack
logsToKeep = 0
```

**Comment by leoms1408** [comment]
Thank you guys!
