### ISSUE TITLE
resourceContainerizerMode bytecode module issue

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2367]
### Description of the problem

If you enable
resourceContainerizerMode = true

the bytecode module (jsb client resource)
the resource get generated without resourceContainerizerMode 
so no meta file and no splits

the verification on client then fails (404 download of meta ...)

### Reproduction steps

enable resourceContainerizerMode 
try connect, and see the verification issue on connect

### Expected behaviour

work

### Operating system

linux

### Version

16.2.24

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
[2311.zip](https://github.com/user-attachments/files/17825833/2311.zip)

**Comment by Doxoh** [comment]
fixed with  16.2.25-rc.3
