### ISSUE TITLE
resourceContainerizerMode issues

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2369]
### Description of the problem

For DLC type resources, the client will crash after downloading the server files. This is the case for dlcpack resources and for plain dlc resources.

### Reproduction steps

Enable the resourceContainerizerMode, then test it with any dlc type resources.

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #16.2.24, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
cannot repo it with `16.2.25` anymore

can u pls try it again, or provide a ressource in this issue?

**Comment by Lekenthu** [comment]
> cannot repo it with `16.2.25` anymore
> 
> can u pls try it again, or provide a ressource in this issue?

[17:00:18][Error] Error on asset reading. Collection [RawStreamer], readedBytes = 4294967295, lastFileReadBytes = 0[Error] Error on asset reading. Collection [RawStreamer], readedBytes = 4294967295, lastFileReadBytes = 0
[17:[00:18]17:[00:18]17:00:18][Error] Invalid asset Apartman_03_Stone_Wood.ymap Shutting down


Now a .ymap file in another resource could not be loaded.  (16.2.25.)

**Comment by Lekenthu** [comment]
@Doxoh With the latest alt:V release, loading all resources now works properly. Thought I'd report back. Thanks! :D
