### ISSUE TITLE
Download Progress bug

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2371]
### Description of the problem

Since the containerisation
the size of downloading resources shows alltime the Full size of all resources and not the "to downloaded" size
X/10GB instead of X/20MB if there only download one resource of 20MB and not all resources
if you enable containerisatzion it shows the old correct X/20MB not X/10GB

### Reproduction steps

disable the new container download in server toml and chance a single resource
connect to server and see the full resource count size instead the single size of the resource that is in download queue

### Expected behaviour

show the requested download queue size and not the full size of all resources

### Operating system

windows/linux

### Version

16.2.24

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
pls retest, should be fixed
