### ISSUE TITLE
new UI in RC client F8 Console

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2372]
### Description of the problem

```
[13:59:53][Error] [WEB, View 000001FC2054AA80] http://ui/index.html#/connection:0:ResizeObserver loop limit exceeded
[13:59:56][Error] [WEB, View 000001FC2054AA80] http://ui/index.html#/connection:0:ResizeObserver loop limit exceeded
[14:00:25][Error] [WEB, View 000001FC2054AA80] http://ui/index.html#/connection:0:ResizeObserver loop limit exceeded
```
if you resize the window to the left you get this messages (resize works? visual)

the new UI don't remember the resize (before it remember)

the new UI is not resize able in top/down and not full left right
it goes max to from left ~20% and canr resize from right to left site

many dev's have stuff on the right side , and transsparent mode or not the location "sucks" it is on the position where i have all my relevant stuff so i can't use the transparent mode anymore with this.

### Reproduction steps

open console F8 and try resize

### Expected behaviour

remember resize
make resize to 100% avaible (not only 80% left/right
make the right and down resize able tooo

### Operating system

Windows

### Version

16.2.25-rc.3

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
![image](https://github.com/user-attachments/assets/4d4db240-eb59-463e-a0c2-6e77d5d42633)

and there is a black box on the right side if you click on the 3 Points

**Comment by MellKam** [comment]
> 
> 
> ![image](https://github.com/user-attachments/assets/4d4db240-eb59-463e-a0c2-6e77d5d42633)
> 
> 
> 
> and there is a black box on the right side if you click on the 3 Points

Black box is fixed

**Comment by MellKam** [comment]
Vertical resize will be added in the next release, already implemented

**Comment by MellKam** [comment]
The issue should be resolved in the RC branch, let me know if you still encounter it.
