### ISSUE TITLE
Installer ignores custom location.

### ISSUE THREAD

**Issue by Allerek** [altmp/altv-issues#2373]
### Description of the problem

alt:v installer currently only stores cache in a directory selected while installing. It should install all of the alt:v files into selected directory.

### Reproduction steps

Download alt:v installer.
Run it, select custom location for install(f.e. F:/ALTV)
Proceed.

Your alt:v files will be in 
%localappdata%/altv
Your cache will be in
F:/ALTV

### Expected behaviour

Install all of alt:v files into selected custom directory.

### Operating system

Windows 11 23H2

### Version

Installer, 22.11.2024 20:19 UTC Time

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by BluePeer** [comment]
read text
the location is the cache location
you can't select the install location
![image](https://github.com/user-attachments/assets/5f1d4751-009c-442f-9d2a-93506e1e1144)

**Comment by Allerek** [comment]
> read text the location is the cache location you can't select the install location ![image](https://private-user-images.githubusercontent.com/1764570/388681229-5f1d4751-009c-442f-9d2a-93506e1e1144.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDgzMDUsIm5iZiI6MTczMzg0ODAwNSwicGF0aCI6Ii8xNzY0NTcwLzM4ODY4MTIyOS01ZjFkNDc1MS0wMDljLTQ0MmYtOWQyYS05MzUwNmUxZTExNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMTYyNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJjYzFmMDdmMzQ4NGNhYjc4MzRmYmQ5ODE1M2Y4NTc1YzA3MDRmNzk2M2Y4Y2IyOTdhYWExZTdlZjAxNTc5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qvcFlueGCUlvDh33vv_qlOulSZxMLUVv3XQo2SJ1gNc)

Locales suggest it should be alt:v install location. Either way - we should add option to select instal location, mainly for 'backup' files that can be pretty big.
![image](https://github.com/user-attachments/assets/47120217-42bb-4be5-ad66-599dbd460ac8)
