### ISSUE TITLE
New console vertical resize

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2375]
### Description of the problem

My request is that the new console UI can be resized vertically. This feature was useful in the previous one. It bothers me when the console takes up half the screen.

### Desired solution for the problem

-

**Comment by MellKam** [comment]
Added in https://github.com/altmp/altv-ui/commit/625b1b53b50d6f86ec3ff09a5e0aba76e7432ed1

**Comment by BluePeer** [comment]
> Added in [altmp/altv-ui@625b1b5](https://github.com/altmp/altv-ui/commit/625b1b53b50d6f86ec3ff09a5e0aba76e7432ed1)

im not shure about the source of this issue.
before the current rc
you added the multicounter fix and the resize
bottom are present there (resize worked if i remember but shown regular cursor not the arrows <-> / updown )
but in the latest rc the resize is gone (the cursor display is corrected shows <-> on resize)
and the multicounter fix is present too
the but the vertical resize is gone
alt:V build 16.2.25-rc.13

**Comment by MellKam** [comment]
Vertical resize was added in the RC branch

**Comment by Doxoh** [comment]
should be fixed on latest release
