### ISSUE TITLE
Rocstar Editor problem - can't save project or export it

### ISSUE THREAD

**Issue by domo978** [altmp/altv-issues#2377]
### Description of the problem

The problem is the inability to use the "save project as" button or the "export" button at the final export screen in Rocstar Editor using altV.

### Reproduction steps

Try to export project or click save project as and give it name

### Expected behaviour

Possible naming of projects and exporting them

### Operating system

Win 10

### Version

16.2.25

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
https://github.com/altmp/altv-issues/issues/1880
