### ISSUE TITLE
client crash on enter voiceVolume 100 in client console

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2379]
### Description of the problem

client crash on enter 
voiceVolume 100
inside client console (alt:V Start window/MainPage)

### Reproduction steps

launch alt:V
wait for the "Start page" (Last connected and Discord announces)
press F8
enter
"voiceVolume 100"
client crash

### Expected behaviour

no client crash

### Operating system

Windows 10

### Version

alt:V build #16.2.25-rc.5, branch rc

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
Should be fixed in the next release or the one after

**Comment by BluePeer** [comment]
crash is gone

but, if you use it connected or before connected to a server
the value does not update inside the UI (F1 settings) , value inside toml is changed
and you get no confirm set log entry, only a issue entry if you enter nothing or a value outside range
