### ISSUE TITLE
Vehicle engine health not synced with server

### ISSUE THREAD

**Issue by Zuiron** [altmp/altv-issues#238]
## Current Behavior

clientside returns 1000. (wrong)
serverside returns 500. (correct)

## Steps to Reproduce

1. create new vehicle on server startup.
2. set engineHealth to 500.
3. connect to server, enter vehicle.
4. check engine health from serverside: returns 500 (correct).
5. check engine health clientside `getVehicleEngineHealth(alt.Player.local.vehicle.scriptID)`
6. it returns 1000 (wrong)

**Comment by martonp96** [comment]
fixed in dev/2.1-dev6

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[2.1-dev6](https://discord.com/channels/371265202378899476/528297438348574741/772455522934325249)
