### ISSUE TITLE
quit game result in Freeze

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2381]
### Description of the problem

required sync value in altv.toml is true (cefFrameSync)
![image](https://github.com/user-attachments/assets/51f4a1a1-d083-41c9-a629-baa68ce87b96)
Like the screen shows the game get stuck on shutdown longest wait 10 Minutes then killed over taskmanager
connect to a server
using F6 (open zigger dev tools) (stay open or close)
used F8 console command quit 
freeze
no crash handler/log entries

quit with the exit button on Start page = no issue instant exit

quit with F1 Exit button on connected
only connected and press F1 = small freeze 5-20s then exit

using F8 console command after connect (without any script/webview/ofterstuff) = instant quit

CPU: AMD 2800X
GPU: Nvidia 1660S with driver 560.94
Windows 10

altv.toml
```
audioFrameLimit = false
autoBackup = true
autoFindMic = false
branch = 'rc'
build = 14.18
cachePath = ''
cefFrameSync = true
consoleHeight = 0.42037037014961243
consoleWidth = 0.4536764919757843
crashOnFatalError = false
crashReporterEnabled = true
debug = false
disableForcedRawInput = false
disableRestrictedSandbox = false
disableRtl = false
discordRichPresence = true
displaySystemUpdateMessagesInLog = false
earlyAuthTestURL = ''
earlyLoad = true
enableDiscordOverlay = false
enableGuildedOverlay = false
enableModDirectory = false
enableNvidiaShadowPlayOverlay = false
enableOverwolfOverlay = false
expandedConsole = true
externalConsoleX = 156
externalConsoleY = 156
gtaPlatform = 'steam'
gtapath = 'C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V'
heapSize = 1024
lang = 'en'
lastip = '127.0.0.1:7788'
launcherSkin = ''
launcherSkinsDisabled = [ 'CzYPuxr' ]
linuxCompatibility = false
logTimeFormat = '%H:%M:%S'
maxDownloadSpeed = 0
name = 'BluePeer'
netgraph = true
permissionsSet = true
promotedOnTop = false
region = 'global'
runAsAdmin = true
streamerMode = false
textureBudgetPatch = true
uiVolume = 50
useExternalConsole = true
useSharedTextures = true
voiceActivationEnabled = false
voiceActivationKey = 18
voiceAutoInputVolume = false
voiceEnabled = true
voiceInputDevice = 'default'
voiceInputNormalization = true
voiceInputSensitivity = 20
voiceInputVolume = 100
voiceNoiseSuppression = false
voiceNormalization = false
voiceVolume = 100
```

### Reproduction steps
[qa-tools.zip](https://github.com/user-attachments/files/17952710/qa-tools.zip)

connect to a server
using F6 (open zigger dev tools) (stay open or close)
used F8 console command quit 
freeze

### Expected behaviour

quit and not freeze

### Operating system

Windows

### Version

alt:V build #16.2.25-rc.13

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
should be fixed
