### ISSUE TITLE
[JS] Problem destroying WebView elements with CEF 127

### ISSUE THREAD

**Issue by RysonTV** [altmp/altv-issues#2384]
### Description of the problem

When i try to destroy a created WebView the CEF seems to crash completly with the .destroy() function. Even the client console is not available anymore. Game just closes by task manager. Login is builded in Vue 3 / Vuetify 3

https://prnt.sc/akPabWFCJxyb

### Reproduction steps

https://prnt.sc/akPabWFCJxyb -> create a webview and destroy it after some time.

### Expected behaviour

The login window should close normally and all other subsequent WebViews should still work or be able to load.

### Additional context

no Errors in Client log.

### Operating system

Windows 10 Home

### Version

16.2.25-rc.13

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by RysonTV** [comment]
I temporarily could fix the problem by adding an alt.setTimeout with 1000 between unfocus and destroy of the webview. Furthermore, the command "quit" in the client console causes the client to hang and does not close it.

**Comment by Doxoh** [comment]
pls test with latest release or current rc `16.2.39-rc.1`
