### ISSUE TITLE
resourceContainerizerMode add-on vehicle tuning bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2385]
### Description of the problem

With resourceContainerizerMode enabled, random tunings of add-on vehicles are not loaded by the server.

### Reproduction steps

Add a larger vehicle pack to the server and enable resourceContainerizerMode.

### Expected behaviour

-

### Operating system

Windows 11

### Version

alt:V build #16.2.26, branch release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
should be fixed in `16.2.28-rc.1`
