### ISSUE TITLE
issue with start/stop/restart resources

### ISSUE THREAD

**Issue by BluePeer** [altmp/altv-issues#2387]
### Description of the problem

there are multiple issues with resources start/stop/restart
if subfolder are used
type dlc/asset resources for example can be stopped with name but not started/restarted config not found error
script resourced cant be stop or restarted (not found)

### Reproduction steps

use resource entry in server toml

'folderinsideresources/resourcename',

type dlc/asset resources
can be
```
start/stop/restart resourcename
```
there stop but not start/restart 
reply config not found (path issue)
But 
```
start/stop/restart folderinsideresources/resourcename
```
this works for asset/typedlc resources
this also works for c# serverside, but not for js clientside resources

### Expected behaviour

let resources only stop with the correct name (name include subfolderpath)
sync the start/stop/restart over all resources to the identical correct way

### Operating system

Windows/Linux

### Version

16.2.28-rc.1 + current release

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by Doxoh** [comment]
fixed in `16.2.39-rc.1`
