### ISSUE TITLE
C# WeaponDamageResponse param name

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#2390]
### Description of the problem

First param of server C# `WeaponDamageResponse` is `NotCancel` which is not very descriptive.

### Desired solution for the problem

Change `NotCancel` to better name like `Cancel` or `AllowAction` if we really do not want to change current logic

**Comment by ghost** [comment]
You should probably open this in the [c# module](https://github.com/altmp/coreclr-module/issues), not an core issue

**Comment by Avepy** [comment]
sure, thanks
