### ISSUE TITLE
Installer always install altV to appdata

### ISSUE THREAD

**Issue by TheDutchDev** [altmp/altv-issues#2397]
### Description of the problem

I recently reinstalled altV. It asked me where I wanted to put the cache folder and whatnot. All fine.

However, in the final step it then proceeded to tell me it was gonna install altV inside appdata folder (AppData/Local/altv).

- Why is this enforced? 
- Why can't we specify where we want altV installed?
- Why can we select cache location but not altV install dir?

Normally it wouldn't bother me that much, but now whenever I want to check client log files, I have to navigate thru appdata to find them... 

### Reproduction steps

Just install altV client

### Expected behaviour

I expected to be able to specify where I want altV installed.

### Operating system

Win 10

### Version

RC 16.2.x

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
AppData is the directory which is least prone to issues with Anti Virus solutions and permissions, therefor the installation behaviour won't be changed.
Experienced users have the options to just move the directory after installation to whereever they want it to be, as alt:V will adjust all registry entries on start to the new path.

**Comment by TheDutchDev** [comment]
While I agree with you there, "idiot" users should stick to the default installation path. Experienced users should still have the option to install it elsewhere. Just show a red popup if the default installation path is changed "This could potentially break altV installation due to antivirus blablabla yada yada, are you sure you want to do this?".

Or hide it under an "advanced" tab or something. (Recommended Installation, Advanced Installation/Custom Installation). You see that quite often with installers. "Idiot" users will just spam-press the next button until it installs while experienced users will look through each page and read it properly.

Moving the folder later on works, but it breaks existing shortcuts (desktop, start menu, etc) which then have to be fixed manually as well.

You could even have it install the bing toolbar and mcafee antivirus, which can only be skipped by unchecking a checkbox in the custom installation 🤣

**Comment by BluePeer** [comment]
a "Experienced users" is able to create shortcuts and move folders
or simply place a altv.toml next to the downloaded exe to skip the hole "installer"" process
