### ISSUE TITLE
Grafana Virtual Entities Wrong Number

### ISSUE THREAD

**Issue by ghost** [altmp/altv-issues#2401]
### Description of the problem

![image](https://github.com/user-attachments/assets/e68ea37c-2be5-4f66-8125-94cb12c0ac78)

Grafana shows wrong number for VE.

### Reproduction steps

I start with 0 VE, Grafana shows 0 VE. I create 1 VE, Grafana shows 1VE. I destroy the single VE, Grafana still shows 1 VE in the dashboard. If I create 2 VE, in Grafana it shows 2 VE, and if I destroy both, it will still show 1VE. 

### Expected behaviour

Should be the correct number.

### Operating system

Windows 11

### Version

16.2.38

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by GVMP** [comment]
Might be related to the general virtual entity streaming issue. Something in the backend probably is broken.
https://github.com/altmp/altv-issues/issues/2230

**Comment by Doxoh** [comment]
fixed
