### ISSUE TITLE
Delayed Firing of OnPlayerDisconnect Event

### ISSUE THREAD

**Issue by Avepy** [altmp/altv-issues#2402]
### Description of the problem

The `Alt.OnPlayerDisconnect` and `AltAsync.OnPlayerDisconnect` events in C# exhibit delayed firing when a player exits the game via the `ALT+F4` shortcut or potentially game crashes. This results in a noticeable delay compared to the expected behavior when disconnecting through the in-game menu or console commands. 

### Reproduction steps

1. Set up a listener for the `OnPlayerDisconnect` event.
2. Start the game and connect a player to the server.
3. Exit the game using the `ALT+F4` shortcut.
4. Observe the delay before the `OnPlayerDisconnect` event is triggered.

### Expected behaviour

The `OnPlayerDisconnect` event should fire promptly and consistently, regardless of whether the player disconnects via the in-game menu, console command or `ALT+F4` shortcut. The response time should match that of other disconnection methods

### Additional context

This issue impacts real-time processing for disconnected players, such as saving player data or releasing resources

### Operating system

Windows 11

### Version

release/16.2.38

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by GVMP** [comment]
Player connections rely on UDP.

If the connection to the server gets interrupted by the player without letting the server know, it might be that the server waits a threshold before the connection gets dropped.
Same vice-versa, when the server unexpectedly crashes without dropping the connections, the players still can move in the game, before they see the "Disconnect" screen.

**Comment by Doxoh** [comment]
right - normal behaviour. It is then a timeout that is waited for before the connection is disconnected
