### ISSUE TITLE
game chrash

### ISSUE THREAD

**Issue by nitedave** [altmp/altv-issues#2404]
### Description of the problem

.

### Reproduction steps

.

### Expected behaviour

.

### Additional context

.

### Operating system

.

### Version

.

### Crashdump ID

12504428

### Confirmation of issue's presence

- [X] *By submitting this ticket, I affirm that I have verified the presence of this issue on the latest RC (Release Candidate) version available at the time of writing this ticket.*

**Comment by deluvas1911** [comment]
You successfully ignored every mandatory field, ticked a field which you haven't even tested and provided a wrong crashdump id...
