### ISSUE TITLE
Ped component id 10 not loading properly

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#261]
## Expected Behavior
Setting Slot 10 (Decal) should show an decal as separate clothing part.

## Current Behavior
Setting Slot 10 (Decal) load the Texture not properly (area is blocked out).

## Steps to Reproduce
1. Load MP Default Ped.
2. Set Clothes via game.setPedComponentVariation(entity.scriptID, 10, 58, 0, 0);

## Detailed Description

![image](https://user-images.githubusercontent.com/7781906/64496068-74a44100-d2a1-11e9-9fec-50961ab74b33.png)

**Comment by Revyn112** [comment]
Update on here: 
This seems only to be a problem, if once an decal with an emblem (from online crews) was loaded.
Before the specific decal works like it used to be. Afterwards the decal loads with black textures.

**Comment by Arochka** [comment]
Seem to work with latest dev
![image](https://user-images.githubusercontent.com/34453212/124745154-ca8ab400-df1f-11eb-97fd-7efc47ce412f.png)

**Comment by LeonMrBonnie** [comment]
Confirmed to be fixed on newest dev by QA

**Comment by Revyn112** [comment]
Can not confirm, this is not fixed.
https://img.revyn112.dev/data/HeLaX9frVY.webm

**Comment by emcifuntik** [comment]
> Can not confirm, this is not fixed.
> https://img.revyn112.dev/data/HeLaX9frVY.webm

Does it work in singleplayer or another multiplayers as should? Just want to know that your ymt file is not wrong.

**Comment by Arochka** [comment]
Oh yeah I just tried your reproduction step, didn’t see your following comment

**Comment by FabianTerhorst** [comment]
Feel free to comment when this is still happening.

**Comment by Revyn112** [comment]
> Feel free to comment when this is still happening.

Still happening.
"This seems only to be a problem, if once an decal with an emblem (from gta online crews) was loaded.".

**Comment by ThomasMarangoni** [comment]
Did you test on dev?
