### ISSUE TITLE
Ped custom components aren't working

### ISSUE THREAD

**Issue by Nicoo34** [altmp/altv-issues#268]
-backpack add-on not working.
-hair and beard add-on no longer working now.
-armor add-on not working.
-accessories add-on not working.

edit: 
-Hat and other things are not working too

Try to add all this things with the Alt Clothes Tool by tuxick. 

For the hair, a guy on the stuyk discord told me his team got the same problem.

**Comment by lameule123** [comment]
Same problem for us.

**Comment by lameule123** [comment]
Any news?

**Comment by Nicoo34** [comment]
up

**Comment by martonp96** [comment]
Custom ped components are working perfectly, it's possible that you are trying to load them wrong.
