### ISSUE TITLE
alt.WebView rendered in 3D responds to keyboard input

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv-issues#270]
When I create CEF in 3D it responds to all keyboard buttons. 
Even if I use the unfocus function.

Build: #778

**Comment by Lhoerion** [comment]
Is this reproducable all the times?
Is this still present in newest build? (beta #793)

**Comment by Lekenthun** [comment]
Yes, reproducible all the times. And I haven't tryed using the newest yet, but I hadn't seen listed the fix in the changelog.

**Comment by Arochka** [comment]
Confirmed, this is a problem when you want to sync a video, for example a youtube video players can rewind or advance

**Comment by LeonMrBonnie** [comment]
Confirmed as fixed by QA
