### ISSUE TITLE
Helicopters falls through ground and explodes

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#272]
Helicopters mostly aren’t there where we left them. When going to the location a explosion is hearable. I think it is because I currently working on a really bad pc and the collisions aren’t fully loaded. But it is synced mostly.(exploded or disapeared on other clients)

## Possible Solution
Planes and Cars doesn’t seems to have this issue. Maybe the native “HasCollisionLoadedAroundEntity“ would help.

## Steps to Reproduce
Spawn a vehicle drive a bit away and back towards helicopter.

**Comment by 7Hazard** [comment]
Does this only happen with helicopters?

It could be that when the player gets sync ownership again that the world collision hasn't loaded yet and the vehicle reacts to the physics of the player at that moment.  It could be solved by decreasing the streaming range for entities but that might be undesirable.

**Comment by AixMC** [comment]
We first recognized that on two polmavs at top of the pd. At fort zancudo all 6 helicopters are gone now but the planes and cars are in the right place. Maybe freezing the helicopters position if no pilot is in there would help too. But then every helicopter where the pilot jumped out would hover midair.

**Comment by YannBcf** [comment]
It has been fixed in the 10.0 update
