### ISSUE TITLE
LocalSyncedMeta

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#273]
**Is your feature request related to a problem? Please describe.**
We currently have setSyncedMeta; this applies to all players and gets synced to all users. I think we should add one more type of meta that only applies to the specific player. Allowing for better server performance; and a direct alternative to the alt.emitClient pattern.

**Describe the solution you'd like**
This meta only applies to the server and only emits changes to the local user. This won't work for vehicles; as vehicles are special and this type of meta should not apply.

This would work great for systems that use:
- Cash
- Bank
- Faces
- Clothing
- etc.

Clientside & Serverside Event:
```
alt.on('localSyncedMetaChange', (key, value) => {

});
```

Functions:
```
player.setLocalSyncedMeta('isLoggedIn', true);
const isLoggedIn = player.getLocalSyncedMeta('isLoggedIn');
```

**Describe alternatives you've considered**
I've written my own handler for something similar to this; and have found it very useful.

**Comment by FabianTerhorst** [comment]
Where is the difference between emit? Isnt it possible to build.thos feature via already existing components.

**Comment by DurtyFree** [comment]
This would be really neat and save some extra work

**Comment by LeonMrBonnie** [comment]
Available in next version
