### ISSUE TITLE
Sync dirt level on vehicles

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv-issues#28]
Hello,
Dirt level on vehicles are not properly synced, if your out of range it is resetted.
Please properly sync this in order to improve important roleplay feeling.

![grafik](https://user-images.githubusercontent.com/20757266/54479254-3a3e7780-481b-11e9-9bf5-17d4a6d917ba.png)

Best regards
Durty

**Comment by emcifuntik** [comment]
Clientside dirt will be disabled soon. You should set dirt level on serverside. You can get xml with zones from GTA files and find there dirt value for each zone, to control dirt level on server.

**Comment by 7Hazard** [comment]
It is possible to set dirt level since... idk since when
