### ISSUE TITLE
Weapon components are not synced

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv-issues#280]
When I set explosive rounds for weapons it doesn't get synched for others. It doesn't matter if I set it on client or on server side.

**For example:**
player.giveWeapon(0xA914799, 30, true);
player.addWeaponComponent(0xA914799, 0x89EBDAA7);

**Comment by Lekenthun** [comment]
The problem here is that if I make the player immortal on client-side using setPlayerInvincible then the explosions created by this player (f.e.: component or grenade) are not synced.

**Comment by C0kkie** [comment]
Should be fixed, we cant reproduce it anymore
