### ISSUE TITLE
Weather progression in cycles aren't synced and can't be overwritten

### ISSUE THREAD

**Issue by kreuzundquer** [altmp/altv-issues#281]
## Expected Behavior
Weather progression should be synced for all players.

## Current Behavior
Weather progression isn't synced for different players.

## Possible Solution
Make the progression overwritable or sync it.

## Steps to Reproduce
1. Login with 2 different clients.
2. Print out the weather progression with
`
let [_, _currentWeather, _nextWeather, _transitionProgress] = native.getWeatherTypeTransition();
alt.log(_transitionProgress);`
3. See that the progress isnt synced.

## Context (Environment)
I'm trying to build a Real Weather Sync with smooth Weather transitions that is also controllable via chat commands.

**Comment by martonp96** [comment]
Use alt.setWeatherCycle instead of the native.
