### ISSUE TITLE
Add alt.Blip.display property

### ISSUE THREAD

**Issue by DooDesch** [altmp/altv-issues#282]
**Is your feature request related to a problem? Please describe.**

The native "game.setBlipDisplay" isn't yet usable with the current blip api.
Therefor we're not able to decide to show the blip on either the radar or fullmap.

**Describe the solution you'd like**

Adding "display" to the blip api setters

**Describe alternatives you've considered**

Getting the blip's scriptID and use it with the native itself, but there isn't any way to get it

**Additional context**

/

**Comment by Stuyk** [comment]
Would like to see this implemented. It would be useful for clearing up overly saturated blips on the map, and hard-locking them to specific displays.

**Comment by tastydev** [comment]
Is it still not possible to get the blip scriptId?

**Comment by Stolzenberg** [comment]
What is the current way to display a blip over the whole map. I still want to show it to the player on the minimap. No matter on which distance he is.

Any workarounds?

**Comment by Stolzenberg** [comment]
Is there currently a workarond to display a blip everywhere, on radar and on fullmap?
Regardless of the distance to the blip.

**Comment by martonp96** [comment]
This feature is available in dev and rc.
