### ISSUE TITLE
Vehicle body modifications not visible until vehicle is restreamed

### ISSUE THREAD

**Issue by PourrezJ** [altmp/altv-issues#285]
## Expected Behavior
Body modifications (window, wheels, body) apply after the use of the methods in question.

## Current Behavior
The changes are executed well, but for what is visible, the player must reconnected or recreate the vehicle to see them.

## Steps to Reproduce
Use this code server side:

let veh = player.vehicle;
if (veh != null)
{
    for(let i = 0; i < 5; i++){
        veh.setWindowDamaged(i, true);
    }
}

**Comment by FabianTerhorst** [comment]
Is the bug still happening?

**Comment by Lekenthu** [comment]
Yes

**Comment by C0kkie** [comment]
Any update on this maybe? :(

**Comment by martonp96** [comment]
This is now tracked in #737 .
