### ISSUE TITLE
Texture file vehshare cannot be replaced via resource

### ISSUE THREAD

**Issue by rethon82** [altmp/altv-issues#286]
## Expected Behavior
A modified vehshare.ytd (which contains license-plates etc.) should replace the one provided by the game.

## Current Behavior
Putting a modified vehshare.ytd in a resource does excactly nothing.

## Possible Solution
Fix the streaming of the resource I guess.

## Steps to Reproduce
Modify any texture in the vehshare.ytd (I did modify the police-new2 as it is easy to check in game) and put it in a resource.

**Comment by emcifuntik** [comment]
Need example resource to reproduct

**Comment by rethon82** [comment]
Here you go

[vehshare.zip](https://github.com/altmp/altv/files/3745036/vehshare.zip)

**Comment by C0kkie** [comment]
Works in dev/15.0-dev11

**Comment by LoudBlowinChungus** [comment]
I am having the same issue streaming a custom vehshare.ytd does not work and I would like to add custom license plates to the server via vehshare.ytd

**Comment by LoudBlowinChungus** [comment]
[custom_vehshare.zip](https://github.com/user-attachments/files/17265167/custom_vehshare.zip)
here is the resource I am attempting to stream if this helps
