### ISSUE TITLE
Native function createMissionTrain created entities are buggy

### ISSUE THREAD

**Issue by FavouRYT** [altmp/altv-issues#291]
## Expected Behavior
Sometimes you spawn an Missiontrain the Model is bugged and the Entity can't deleted.

## Current Behavior
Entity are buggy.

## Possible Solution
n/a

## Steps to Reproduce
1. Loading Models by the following code:
```
models = [
    "freight",
    "freightcar",
    "freightgrain",
    "freightcont1",
    "freightcont2",
    "freighttrailer",
    "tankercar",
    "metrotrain",
    "s_m_m_lsmetro_01"
];

function requestTrainModels() {
    for (var i in models) {
        let temp = game.getHashKey(models[i]);
        game.requestModel(temp);
    }
}```

2. Create Train by following Code as example (sometimes it works):
```
let Train = null;
function spawnTrain() {
Train = game.createMissionTrain(24, 1578.4533, -932.9816, 71.4226, true);
game.setEntityAsMissionEntity(Train, true, true);
alt.log(`Train Number: ${Train}`);
}
```

## Context (Environment)
n/a

## Detailed Description
fix it

## Possible Implementation

**Comment by FavouRYT** [comment]
seems to be the entity is bugged when it not spawns properly.
if i set my player into train on any seat and leave the train = gamecrash = thats only happens on "bugged" trains

**Comment by FabianTerhorst** [comment]
Trains aren't synced so strange stuff will happen when you use them.

**Comment by FavouRYT** [comment]
yeah but this bugs appears too for clientside?

**Comment by martonp96** [comment]
We do not give support for vehicles created by native. Use the alt:V api.
