### ISSUE TITLE
Native function loadScene gives event handler warning

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#297]
## Current Behavior
```
[22:42:42][Warning] Resource client event handler 7 was too long 1379 ms
[22:42:42][Warning] Resource client event handler 6 was too long 1379 ms
```

## Steps to Reproduce
1. use game.loadScene(position);

## Context (Environment)
Using to render position for camera, when player isn't near this position.

**Comment by martonp96** [comment]
This is normal behavior as the game starts to load multiple models, collisions, entities on that position.
