### ISSUE TITLE
Add possibility to get local ping

### ISSUE THREAD

**Issue by Lhoerion** [altmp/altv-issues#306]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
`alt.Player.local.ping` or `alt.getPing()`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Lekenthun** [comment]
We should be able to get everybody's ping on client-side. This would help creating a scoreboard.

**Comment by FabianTerhorst** [comment]
Ping from everyone would be waste of traffic. The local pig is already available and just needs a getter.

**Comment by 7Hazard** [comment]
Getting packet loss would also be very useful

**Comment by FabianTerhorst** [comment]
We will add
 uint16_t fps, uint16_t ping, uint32_t tx, uint32_t rx in 7.0

**Comment by FabianTerhorst** [comment]
Fixed in next release.
