### ISSUE TITLE
Add getter for getting ammo of all equipped weapons.

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#309]
**Is your feature request related to a problem? Please describe.**
Its currently not possible to get the ammo of none active weapons. So its not possible to determinate from serverside the current ammo of a none active weapon.

**Describe the solution you'd like**
A getter that returns a dictionary of <uint32_t, uint16_t> where uint32_t is the weapon hash and uint16_t the ammo.

**Describe alternatives you've considered**
A event that calls when player started and stopped shooting.

**Comment by FabianTerhorst** [comment]
Another alternative would be a event that triggers when player switches weapon.

**Comment by emcifuntik** [comment]
This info simply doesn't send by client. Sending this info from client will just increase average trafic

**Comment by tastydev** [comment]
Is there still a chance to get a serverside ammo getter/setter for the activeWeapon on the player object?

**Comment by Lhoerion** [comment]
@tastydev There's always, but the time when it arrives is unknown

**Comment by FabianTerhorst** [comment]
Available in 15.0 dev branch.
