### ISSUE TITLE
Antivirus programs may block the launcher

### ISSUE THREAD

**Issue by IdoX1** [altmp/altv-issues#312]
## Expected Behavior

The alt:v installation file should install the alt:v client.

## Current Behavior

The Avast anti virus blocks it ( maybe more anti viruses )

## Possible Solution

Some kind of windows installer might solve the problem.

## Steps to Reproduce

1. Download client - https://altv.mp/#/downloads
2. Unzip the downloaded zip file.
3.  Run the installation file in the folder.
4. Avast Antivirus blocks the installation and makes

**Comment by FabianTerhorst** [comment]
You have to disable the anti virus checking. A installer won't prevent the anti virus to detecting memory reads of different processes.

**Comment by 7Hazard** [comment]
What could be a solution is to sign altv.exe with a certificate. Eventually we'll get one.

**Comment by C0kkie** [comment]
Should work in v15
