### ISSUE TITLE
CEF not playing live youtube videos and other online streams

### ISSUE THREAD

**Issue by sirbenson** [altmp/altv-issues#313]
## Expected Behavior
Chromium (Cef) not playing live videos

## Current Behavior
Stream isnt loading

## Possible Solution
https://unix.stackexchange.com/questions/438045/chromium-not-playing-live-youtube-videos-and-other-online-streams

## Steps to Reproduce
Embedding youtube video (Working)
Embedding youtube live stream (Not working)

## Context (Environment)
Embedding custom livestreams (hls, mpeg, h.264)

**Comment by 7Hazard** [comment]
Could also be related to https://github.com/altmp/altv/issues/298
We're in the works on a new web engine for our Webviews, multiple encodings might be fixed at that point.

**Comment by vadzz-dev** [comment]
Live streams are protected by widevine cdn and we do not have a license to redistribute it, so it does bot work and won't work in the near future

**Comment by sirbenson** [comment]
we useing an own streaming service (own hls / rtmp) streaming server based on node.js so its not protected

**Comment by FabianTerhorst** [comment]
Duplicate of #298
