### ISSUE TITLE
IPlayer.IsInVehicle property returns wrong value on Linux

### ISSUE THREAD

**Issue by FavouRYT** [altmp/altv-issues#314]
## Expected Behavior
if Player is in Vehicle it should to be return true,
if player is not in vehicle it should be return false.

## Current Behavior
player.isInVehicle returns everytime true.

## Possible Solution
n/A

## Steps to Reproduce
1. Alt.Log($"InVehicle: " + player.IsInVehicle);

## Context (Environment)
n/A

## Detailed Description
On Windows it works fine, only on Linux it doesnt work properly.

**Comment by vadzz-dev** [comment]
Is it still actual?

**Comment by FavouRYT** [comment]
yes

**Comment by FavouRYT** [comment]
same with colshapes IsEntityIn is always true in every case on linux

**Comment by vadzz-dev** [comment]
Can you provide more info abput the environment? (Distro, kernel version, glibc version)

**Comment by FavouRYT** [comment]
I tested it out on Debian 10, how to check kernel & glibc?

**Comment by Lhoerion** [comment]
Issue needs to be reported on appropriate issue tracker [https://github.com/altmp/altv-js-module/issues]()

**Comment by FabianTerhorst** [comment]
I think this is already fixed since a few months in altv core.
