### ISSUE TITLE
Native deletePed crashes the game when scriptID is valid

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#316]
## Expected Behavior
do not crash

## Current Behavior
it crashes

## Steps to Reproduce
try to create and delete peds very often in short period of time

**Comment by 7Hazard** [comment]
Are you deleting subverting that isn't created by a native? A player?

**Comment by nrzull** [comment]
@7Hazard nope, I just create a ped via `createPed` native and then delete him with `deletePed`

**Comment by martonp96** [comment]
Run a doesEntityExist native on the ped before you call deletePed.
