### ISSUE TITLE
Add point dist and for each in range

### ISSUE THREAD

**Issue by danartzz** [altmp/altv-issues#32]
SERVER SIDE
a function to get all entities in range
**entity.forEachInRange(position, int range, int world/dimension, callback);** // returns all entities within the specified range

a function to get distance between player and a map coordinate
**GetPlayerDistanceFromPoint(player, position):** would return distance between player and a map coordinate

//optional (useful for local chat)
**players.broadcastInRange(pos, 15, `Message from ${player.name}: ${message}`);**

**Comment by gamelaster** [comment]
I expect this is for server-side. Well, this can be implemented also by dev, it's nothing complicated, but I will probably make those kind of util functions

**Comment by vadzz-dev** [comment]
Is the last option for text chat? If so this should be a part of chat resource so please post it in chat repo

**Comment by vadzz-dev** [comment]
And for second it will look smth like worldObject.distanceTo(coords/worldObject)

**Comment by danartzz** [comment]
> Is the last option for text chat? If so this should be a part of chat resource so please post it in chat repo

yes OK I will do that, thanks.

**Comment by martonp96** [comment]
All of this mentioned is scriptable so it's pointless to add.
