### ISSUE TITLE
Prevent ALL Clock Natives from Going Above 24 Hours, 60 Minutes, 60 Seconds, etc.

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#323]
## Expected Behavior
Advance to any hour, minute, or second without crashing.

## Steps to Reproduce
Set time to 23 Hours
Set time to 24 Hours
Crash

**Comment by FabianTerhorst** [comment]
Best solution would be to disable the time native, because serverside supports that already.

**Comment by FabianTerhorst** [comment]
Its now disabled serverside for 
```
if (day > 30 || month > 30 || hour > 23 || minute > 60 || second > 60) return;
```
Will be available in next release.
