### ISSUE TITLE
Ped appearance getters

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv-issues#324]
Those getter functions (clientside) would be useful to have:

| Function  | Parameters | Returns |
| ---------- | ------------ | --------- |
| **GetPedFaceFeature** | **ped**: Ped, **index**: int | **scale**: int |
| **GetPedEyeColor** | **ped**: Ped | **index**: int |
| **GetPedHairColor** | **ped**: Ped | [**colorID**: int, **highlightColorID**: number] |
| **GetPedHeadOverlay** | **ped:** Ped, **overlayID**: int | [**index**: int, **opacity**: float] |
| **GetPedHeadOverlayColor** | **ped**: Ped, **overlayID**: int | [**colorType**: int, **colorID**: int, **secondColorID**: int] |

**Comment by FabianTerhorst** [comment]
We will add it serverside for 7.0

**Comment by Revyn112** [comment]
> 
> 
> We will add it serverside for 7.0

also are setters planned?

**Comment by C0kkie** [comment]
All working in dev/7.0-dev17
