### ISSUE TITLE
Add boolean parameter in altv.cfg to ask which branch to run at startup

### ISSUE THREAD

**Issue by EtzBetz** [altmp/altv-issues#329]
**Is your feature request related to a problem? Please describe.**
Many of us Devs have several clients side-by-side installed just for different configurations, as in for each different branch and eventually also for debug options. It's bloating the taskbar and editing the config is not really a viable option as it takes too long when switching frequently.

**Describe the solution you'd like**
I'd like an `boolean` parameter e.g. `configAtStartup` to be added in the `altv.cfg`.
If it's `false`, alt:V would just startup like it's currently doing.
If it's `true`, when started, alt:V will ask the user which `branch` to run and eventually other things like the `debug`, `netgraph` or `streamerMode`-parameter.

**Describe alternatives you've considered**
An idea of other people was to generally ask the user which branch to start, but the alt:MP Team was against this, as people/players are generally supposed to stay active on one branch. This problem is more of a problem for developers and testers.

**Additional context**
Nothing I guess.

**Comment by Lhoerion** [comment]
I think it'd be better to actually make this settable via program arguments.

**Comment by derRAV3N** [comment]
Good idea, would be fine with this as well

**Comment by C0kkie** [comment]
You can set debug & branch in upcoming version via cli arg
