### ISSUE TITLE
Server Resources finally loaded event

### ISSUE THREAD

**Issue by abstractFlo** [altmp/altv-issues#33]
I communicate from server resource to server resource with the alt:v eventhandler `on` & `emit`

Sometimes i emit and event directly on server start to another resource. This is only working, if all involved resources are loaded.

It would be nice, if there is an event like
```
alt.resReady(() => {
  // do all stuff you need after resources successfully loaded
})
```

I hope you understand what i mean :)

**Comment by gamelaster** [comment]
alt.on('resourceReady', ...)

**Comment by Lhoerion** [comment]
https://altmp.github.io/altv-typings/modules/_alt_server_.html#on

**Comment by vadzz-dev** [comment]
It was about event that will get fired after all resources were started, not just one

**Comment by Lhoerion** [comment]
Then I suggest new parameter in `anyResourceStart` like `isLast`

**Comment by LeonMrBonnie** [comment]
Clientside has `connectionComplete` event, so serverside should get something similiar.

**Comment by LeonMrBonnie** [comment]
Serverside has the `serverStarted` event now, which is dispatched when the server is fully started
