### ISSUE TITLE
Client crashes when imported client resource doesn't exists as dependency or doesn't exists at all

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#330]
## Expected Behavior
Client shouldn't crash and only print the error in console.

## Current Behavior
Client crashes

## Steps to Reproduce
1. Add two client resources
2. Import one client resource from the other one
3. Make sure the imported client resource isn't loaded first
4. Client crash

## Context (Environment)
#879
(linux server)

**Comment by Lekenthun** [comment]
Server-side also have the same error.
