### ISSUE TITLE
Add ability to disable console warnings about time execution of resources/ticks/updates

### ISSUE THREAD

**Issue by nrzull** [altmp/altv-issues#332]
**Is your feature request related to a problem? Please describe.**
Console freezes on warning spam. Also it interferes to catch app errors by myself during debug

**Describe the solution you'd like**
Add ability to disable console warnings

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by FabianTerhorst** [comment]
i would suggest only showing them in debug mode.

**Comment by nrzull** [comment]
From one point it's a good suggestion, but in other point, developers are almost always use debug mode on development and then they will not be able to catch its own warnings/errors in console because of a spam if they have it.

**Comment by Lhoerion** [comment]
Suggestion to add console command working similiar to net graph command etc.

**Comment by LeonMrBonnie** [comment]
> 
> 
> Suggestion to add console command working similiar to net graph command etc.

This will be the used approach once https://github.com/altmp/altv-issues/issues/730 is fixed.

**Comment by ThomasMarangoni** [comment]
Won't get added
