### ISSUE TITLE
WebView.isVisible setter problem

### ISSUE THREAD

**Issue by PepoDance** [altmp/altv-issues#335]
## Expected Behavior
To toggle the display of the web view.

## Current Behavior
Doesn't toggle the display of the web view after you create a new web view.

## Possible Solution
Make the web views into a single page application, hide the content in the background and display it when you need it. But you shouldn't have to do this in order to use this function.

## Steps to Reproduce
1. Create a new web view.
2. Attempt to do `view.isVisible = false;`

## Context (Environment)
You cannot hide the user interfaces after creating it and you should be able to toggle it. 

## Detailed Description
```js
const testView= new alt.WebView("http://resource/Client/html/store/index.html");
testView.isVisible = false;
```

**Comment by iRequire** [comment]
Noticed this aswell. Really annoying.

**Comment by vadzz-dev** [comment]
is it still actual?

**Comment by PepoDance** [comment]
> is it still actual?

Yes

**Comment by Lhoerion** [comment]
@PepoDance Check it on latest build in dev branch, I couldn't reproduce it anymore.

**Comment by PepoDance** [comment]
Still doesn't work, some views are still showing after setting it to false.

**Comment by Lhoerion** [comment]
@PepoDance Can't reproduce it on `build #1088, branch dev`. Could you provide me in some way WebView, which always reproduces said issue?

**Comment by kineese** [comment]
I still got the same problem. Using SaltyChat in it's own resource. Sometimes I'm lucky and my UI-WebView is in front sometimes it isnt.

**Comment by c0nnex** [comment]
I can hide a webView using webView.isVisible=false, however i cannot make it show up again using webView.isVisible=true . It will remain hidden,
Build #1098, release

**Comment by R0ckzo0r** [comment]
same here

**Comment by SandDanGlokta** [comment]
yeah, same problem here.

**Comment by DatMayo** [comment]
Same here too.
Just writing to get informed :>

**Comment by architectlog** [comment]
**To get around:**

The problem does not occur when setting the value in the webview's load event.

`_webview.on('load', () => _webview.isVisible = false)`

This code makes the webview visible for a micro moment on the screen if you have visible html elements. To prevent this, hide your html by default, and make it visible after it has been loaded (and set isVisible to false).

Tested on my server.

**Comment by StormShadow5880** [comment]
build #1181, branch release
dont work's for me either. the window still appears (isVisible  is set to false...)

**Comment by LeonMrBonnie** [comment]
Confirmed on 2.1-dev32.

**Comment by LeonMrBonnie** [comment]
Fixed.

**Comment by TheMysteriousVincent** [comment]
And what does isVisible exactly - technically speaking?
Does it just disable rendering of a page?

**Comment by LeonMrBonnie** [comment]
Probably yes, as the CEF process is still running and the page behaves normally, you just can't see and interact with it anymore.
