### ISSUE TITLE
Sync setVehicleSearchlight native function

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#337]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i see a native not sync

**Describe the solution you'd like**
Pls synchronize native.setVehicleSearchlight

**Describe alternatives you've considered**
I currently use syncedmeta and to synchronize this thing.

**Additional context**
Long Life to Heron Master and alt:V

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
