### ISSUE TITLE
Sync setVehicleHasMutedSirens native function

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#339]
**Is your feature request related to a problem? Please describe.**
Would be fun to have a native synchronisation of Siren Audio from vehicles since almost all of the other native are functionnal and sync already.

**Describe the solution you'd like**
Like other native, pls synchronize it and create Getter/Setter serverside :) !

**Describe alternatives you've considered**
SyncedMeta..:'(

**Additional context**
Long life to Heron Master and alt:V team

**Comment by FabianTerhorst** [comment]
native is called now setVehicleHasMutedSirens but issue is still valid https://natives.altv.mp/#/0xD8050E0EB60CF274

**Comment by C0kkie** [comment]
Will be handedld here: https://github.com/altmp/altv-issues/issues/737
