### ISSUE TITLE
Get vehicle category(Boat, Helicopter etc.)

### ISSUE THREAD

**Issue by Tolan87** [altmp/altv-issues#34]
**Is your feature request related to a problem? Please describe.**
We need a function to get the category of a vehicle, to control what should happen based on the category.

**Describe the solution you'd like**
A serverside Vehicle_getCategory(alt::IVehicle* vehicle) function that return the category of given vehicle.

**Describe alternatives you've considered**
Use the natives clientside:
```
IsThisModelAHeli(model: NativeHash)
IsThisModelACar(model: NativeHash)
OR
GetVehicleClass(vehicle: NativeVehicle)
```

**Comment by FabianTerhorst** [comment]
added in next release.
