### ISSUE TITLE
Add object pool for all objects in rendering range

### ISSUE THREAD

**Issue by Unnvaldr** [altmp/altv-issues#340]
**Is your feature request related to a problem? Please describe.**
Being unable to get objects in rendering range

**Describe the solution you'd like**
`alt.WorldObject.all` for uniformity

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tastydev** [comment]
Object sync is on the alt:V roadmap. So this feature will be available if the devs will bring the object sync feature in.

**Comment by Lhoerion** [comment]
Enhancement doesn't concern about object sync, just about getting objects in rendering range.
(I can't mark this as client-side, so I understand the confusion)

**Comment by Stuyk** [comment]
Existing objects or objects you create?

**Comment by Lhoerion** [comment]
Existing objects, but with ability to push to the pool

**Comment by derRAV3N** [comment]
I don't exactly know what you're planning, but we used https://natives.altv.mp/#/0xE143FA2249364369 to index important objects. Eventually this helps until a final solution is released.

**Comment by Lhoerion** [comment]
Still only closest one, I'd need to change my player pos to get all entities, also I'd need to know modelHash.

The purpose of this enhancement is pretty straight, maybe just lack of ability to understand makes it harder to notice

**Comment by derRAV3N** [comment]
Well, I definitely see the use-cases for this, but there are points on the list which just have a higher priority.
Just as a heads-up, I'm not in the dev team or anything, but if you want this feature anytime soon, you should/could build your own database with the native and use that.

**Comment by Lhoerion** [comment]
I didn't wrote this enhancement to get advices, you're free to give your opinions, the rest leave to the devs regarding priority and their list.

**Comment by derRAV3N** [comment]
Sorry for trying to help you.

**Comment by Lhoerion** [comment]
No thanks, didn't ask for your help.
