### ISSUE TITLE
Event weaponDamage cancellation doesn't work properly

### ISSUE THREAD

**Issue by FavouRYT** [altmp/altv-issues#346]
## Expected Behavior
Target dont get Damage & stay alive.

## Current Behavior
Target dont get Damage but falls down by the player where shoot at him. But by Target Player he's still alive & can walk but for the player where shoot at him he lay on the ground.

## Steps to Reproduce
1. return false on the weaponDamage Event and shoot at a Player.

**Comment by Lhoerion** [comment]
Does it happen on latest build #1004?

**Comment by derRAV3N** [comment]
I can confirm this issue. Generally I would like to have this working better, e.g. cancelling damage that is happening to vehicles, or damage that is coming from explosions, falling or when driving against walls with a car.

**Comment by martonp96** [comment]
Lethal damage cannot be cancelled "visually". You have to stream weapon configs and change the a mount of lethal damage to non-lethal.
