### ISSUE TITLE
Add getResourceName Server- and Clientside

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-issues#348]
**Is your feature request related to a problem? Please describe.**
You are not able to get the resource name of the current running resource.

**Describe the solution you'd like**
An API you can get the resource name from on server and clientside

**Describe alternatives you've considered**
No alternatives I can think of.

**Additional context**
With this method you could generate static prefixes, add the resource name to custom logs, even if someone changes the name of the resource folder.

**Comment by Lekenthun** [comment]
Server-side: alt.resourceName
