### ISSUE TITLE
Headlight RGB colors

### ISSUE THREAD

**Issue by Enerv** [altmp/altv-issues#349]
I think an interesting idea would be to add the RGB variant for headlights colors. Currently there are only 12 colors of lights from 0 to 12.

**The could look like this**:
```js
vehicle.customHeadlightColor = { r: 255, g: 0, b: 0 };
alt.log(JSON.stringify(vehicle.customHeadlightColor));
```
I will definitely use it well in my race project.

**Comment by Enerv** [comment]
Get and locally changing the client-side would also be useful. 🤩

**Comment by FabianTerhorst** [comment]
Not possible in gta. Feel free to reopen when you know a way how to do it in gta.
