### ISSUE TITLE
Vehicle.EngineOn getter/setter sync issue

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#356]
## Expected Behavior
If EngineOn is set to true serverside, vehicle have engine activated clientside.

## Current Behavior
Getter not fiable, same for Setter he doesn't work at all.
( Tested on c#. Problem come from cpp sdk maybe? )
## Possible Solution
SyncedMetaChange and alot of emit to maintain an updated boolean serverside my friend.

## Steps to Reproduce
- Spawn a vehicle
- Use flag to prevent automatic start
- Set EngineOn serverside
- Nothing Happen

**May the force be with you, long life to alt: V**

**Comment by PourrezJ** [comment]
Same problem for me after having updated my gamemode which had not been updated since November.

**Comment by tastydev** [comment]
Can confirm this bevahiour with 10/10 reproducable trys:

1. Use flag to prevent automatic start
2. Set EngineOn serverside
3. Leave the Vehicle
4. Enter the Vehicle
5. EngineOn is true while the engine is false
6.  Now u have to toggle EngineOn twice to get the "sync" back

**Comment by lameule123** [comment]
Problem is still here with latest release.
Use tastydev step to reproduce the bug

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
