### ISSUE TITLE
discordInfo function returns null after Discord restart

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv-issues#358]
## Expected Behavior
`alt.discordInfo()` should return null only when its not running / shutdown. After started again it should again return discordInfo

## Current Behavior
`alt.discordInfo()` works perfectly fine as long as discord is not restarted while the game runs. **After a restart** this it seems like **its always returning null**, even tho discord is running.

## Possible Solution
`alt.discordInfo()` should only return null as long as discord is not running. It should send the info again if its back up & running.

## Steps to Reproduce
1. Call alt.discordInfo() -> returns correct object
2. Restart discord
3. Call alt.discordInfo() -> returns null

## Context (Environment)
I want discord info

## Detailed Description
I noticed `Discord: Shutdown` in the console log, after this message it seems like discordInfo() is always null. I think it internally never receives an "Discord: Started" or something...

**Comment by DatMayo** [comment]
alt.discordInfo() is deprecated, use alt.Discord.x
See: https://altmp.github.io/altv-typings/classes/_alt_client_.discord.html

**Comment by Lhoerion** [comment]
@vadzz-dev Is it still a thing on newer builds and/or is it going to be worked on?

**Comment by C0kkie** [comment]
Currently its not null if you restart discord if it was open while altv was open.
It will be null if you close discord -> start game -> start discord -> alt.log(alt.Discord.currentUser) -> will be null

**Comment by martonp96** [comment]
done in 9.0-dev1
