### ISSUE TITLE
Sync taskScenarioInPlace native function problem

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#360]
## Expected Behavior
Same Scenario for all.

## Current Behavior
taskScenarioInPlace have some sync bug, if u use emote like "WORLD_HUMAN_SMOKING" u can see urself smoking locally but other player see you doing fitness.
The problem seem's to be here randomly for some emote.

## Steps to Reproduce

1. native.taskStartScenarioInPlace(alt.Player.local.scriptID, "WORLD_HUMAN_SMOKING", 0, true);
1. U see u'rself smoking but other player see u doing other scenario.

**Comment by lameule123** [comment]
Weird.

**Result after some experiment:**
The problem is the same for scenario "WORLD_HUMAN_MUSICIAN" but if u call it twice in very short delay he is sometimes correctly sync.

**Comment by tastydev** [comment]
did u reconnect?

**Comment by lameule123** [comment]
I use reconnect for developpement sure but problem is present without i can confirm that.

**Comment by Stuyk** [comment]
Set last parameter to false maybe.

**Comment by lameule123** [comment]
The problem is still here...i've try to set last param to false

**Comment by tastydev** [comment]
@martonp96 this is happening on rc2.1-rc1 again. In example scenario `PROP_HUMAN_MUSCLE_CHIN_UPS` will play a different scenario for other players. Very gamebraking.

**Comment by tastydev** [comment]
We found out that it´s an NVE bug. If u have NVE installed u will stream wrong scenarios to non-NVE players. Reproducable 10/10. It seems like NVE is negatively affecting the synctree?!

**Comment by tastydev** [comment]
We reached out to the creator of NVE and he confirmed the bug and will fix it in a new NVE package 
![nve-issue-confirmation](https://cdn.discordapp.com/attachments/258004810605789194/777268214844489758/unknown.png)

**Comment by ThomasMarangoni** [comment]
Because it's related to NVE and not alt:V it will be closed.
