### ISSUE TITLE
Game lag when the in-game date equals the real life date

### ISSUE THREAD

**Issue by iRequire** [altmp/altv-issues#364]
So I recently investigated the FPS issues I had on my server.
I tested through all the Weather IDs and Time of day on the Ingame date 0, 0, 0 and got good FPS on all of them. Then I set the date to 29 12 2019 and my game lagged out on all of them.

## Expected Behavior
No lags

## Current Behavior
Lags (from 150-180 FPS to ~50)

## Possible Solution
Remove 1 from the Month (12 -> 11) and it will work.
Maybe block values above 11.

## Steps to Reproduce
1. Set Ingame month to 12
2. Get bad FPS

**Comment by emcifuntik** [comment]
game months goes from 0 to 11, as I know

**Comment by DurtyFree** [comment]
Shouldnt alt:V prevent servers from breaking your client with such things?

**Comment by emcifuntik** [comment]
> Shouldnt alt:V prevent servers from breaking your client with such things?

alt:V doesn't do anything with native stuff and will never do. We can't protect players from 6k of natives

**Comment by iRequire** [comment]
Maybe it should atleast be noted on the wiki for setDateTime that ingame months start at 0 :)

**Comment by derRAV3N** [comment]
You're free to add a comment :)

**Comment by vadzz-dev** [comment]
Are you using server-side funcs or natives for this?

**Comment by iRequire** [comment]
> 
> 
> Are you using server-side funcs or natives for this?

I use `player.setDateTime` on Server side

**Comment by 7Hazard** [comment]
We could add an extra param for TimeFormat, whether it's Zero11 or One24, where One24 would be default

**Comment by tastydev** [comment]
Could be a solution but isn´t it possible to just hook the arguments in v8? And correct them by minus 1 if the month arg is 12 for example? So its noob friendly for newcomers

**Comment by Lhoerion** [comment]
Added `DateTime` type for parameters of `player.setDateTime` method in altv-typings

**Comment by LeonMrBonnie** [comment]
This has been fixed.
