### ISSUE TITLE
Explosion event not fired for certain vehicles

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#366]
Explosion event isn't called when the vehicle explodes.

**Comment by XMGamingMaster** [comment]
It does get called but you can't cancel it.

**Comment by Lekenthu** [comment]
Helicopter doesn't work, sure.

**Comment by Lhoerion** [comment]
Does it happen on latest beta build #993?

**Comment by Lekenthu** [comment]
Yes. After the helicopter explosion, the event is still not called.

**Comment by martonp96** [comment]
See #675 for the explanation.
