### ISSUE TITLE
Add getFocusCoords function for retrieving current game focus coords

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv-issues#367]
**Is your feature request related to a problem? Please describe.**
I use to set focus area a lot, but there is currently no way to find out what my current focus coord is.
This is related to the native: `setFocusPosAndVel()` http://natives.altv.mp/#/0xBB7454BAFF08FE25`

**Describe the solution you'd like**
Have an method that reads current focus coords from game. Like `alt.GetFocusCoords()` returning Vector3 or something

**Describe alternatives you've considered**
Theres no other way to get this.

**Additional context**
I have some rather old reversing snippet, I am not sure if it still works with the current version
```c
class CFocusData;

Vector4*(__thiscall* CFocusData__GetCoords)(CFocusData* This, Vector4* coords);

class CFocusData
{
public:
    inline Vector4 GetCoords()
    {
        Vector4 coords;
        CFocusData__GetCoords(this, &coords);
        return coords;
    }

private:
    int m_focusType; // 0x00
    char _0x04[0xC]; // 0x04
    Vector4 m_coords; // 0x10
    Vector4 m_offset; // 0x20
    char _0x30[0x20]; // 0x30
    CEntity* m_entity; // 0x50
    CEntity* m_entity2; // 0x58
    bool m_0x60; // 0x60
};

CFocusData* g_focusData;
```
```C
// init
auto addr = Pattern::Scan("48 8D 0D ? ? ? ? E8 ? ? ? ? 44 38 3D ? ? ? ? F3 0F 10 30");

if (addr)
{
    g_focusData = (CFocusData*)(addr + *(int*)(addr + 3) + 7);
    CFocusData__GetCoords = (decltype(CFocusData__GetCoords))(addr + *(int*)(addr + 8) + 12);
}
```

**Comment by C0kkie** [comment]
Added in dev/11.0-dev15
