### ISSUE TITLE
Sync Vehicle.SetPartBulletHoles method

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#371]
## Current Behavior

The setter does not work when it is executed at serveur launch to load all vehicles from SQL. 
The code is well executed and the values ​​are good but nothing seems to be applied in the game.

Do the same operation with the same value once connected works but you have to exit the stream range and re-enter to see the damage.

## Possible Solution
**No One since Base64 Method are depreciated.**

## Steps to Reproduce
**Server Launch Context:**
1. Store value from 0-5 Parts.
2. Apply value on serveur launch for future connection.
3. BulletHoles not visible in game.

**In-Game Connected Context**
1. Apply Value
2. Not working
3. Go out of range on re-enter again
4. BulletHoles is applied and visible

## Code exemple
https://i.gyazo.com/136de0f0d75fe6d826d7153d5d6e3010.png
https://i.gyazo.com/8d6905460b9fcac4c2ae0a92ada9d305.png

**Comment by lameule123** [comment]
Same problem for SetPartDamageLevel, SetBumperDamageLevel3

**Comment by martonp96** [comment]
fixed
