### ISSUE TITLE
Vehicle.dirtLevel property always return 0 or 41 and setter problem

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#372]
## Expected Behavior
Progressive Float and working Getter Serverside.

## Current Behavior
The Dirt Level seems to have only two value: 0 for clean car and 41 for dirty car.

I take this value from Vehicle.DirtLevel serverside.

## Steps to Reproduce

1. Print value of DirtLevel before vehicle utilisation: 0
1. After some run on dirt terrain
1. DirtLevel retun 41

There is no progression.

**Comment by lameule123** [comment]
When value is 41.
Set the DirtLevel to 0 serverside doens't have any effect in game.

**Comment by lameule123** [comment]
Update:
Forgot what i wrote before.
DirtLevel 0 is applied but we need to go out of streaming range and enter again to see the change.

**Comment by C0kkie** [comment]
Will be handled here https://github.com/altmp/altv-issues/issues/737

**Comment by LameuleFR** [comment]
The problem is still present in latest version of altV.
Same behaviour as before

**Comment by FabianTerhorst** [comment]
Yes ofc thats why its in the list of the other issue.
