### ISSUE TITLE
Previously exploded vehicles are exploding again on stream in

### ISSUE THREAD

**Issue by tastydev** [altmp/altv-issues#376]
If a vehicle is destroyed through a explosion it will always do the explosion sound again on entity streamIn.

## Expected Behavior
No Explosion on entity streamin

## Current Behavior
Explosion of already exploded vehicles on entity streamin

## Possible Solution
This feature already exists in the old streamer maybe it was forgotten
## Steps to Reproduce
1. Spawn vehicle and destroy/explode it
2. Go out of the streaming range
3. Go back in the streaming range
4. You should hear the explosion again

## Context (Environment)
Beta Build

**Comment by lameule123** [comment]
That's bug is really tasty i can confirm he is still present.

**Comment by Lhoerion** [comment]
Is it still present on build #1003?

**Comment by tastydev** [comment]
yes, but its random. hard to reproduce maybe it depends on the vehicle class

**Comment by FabianTerhorst** [comment]
not reproducable with current version. Feel free to open again when you got video etc.
