### ISSUE TITLE
Add Player.visible

### ISSUE THREAD

**Issue by GregologyDEV** [altmp/altv-issues#381]
**Is your feature request related to a problem? Please describe.**
It will be much easier if we get getter and setter player ped alpha

**Describe the solution you'd like**
getter example: player.visible

setter example: player.visible(true, false)
This will set player ped invisible to every player on server, but keep visible for himself

**Describe alternatives you've considered**
Now we need to set loops with exceptions and emit setter to client

**Additional context**
I hope for add this method.

**Comment by faizmain** [comment]
use native setEntityVisible

**Comment by faizmain** [comment]
if u want use local, use setEntityAlpha is not sync

**Comment by C0kkie** [comment]
Got added in 2.1-dev65.
