### ISSUE TITLE
Improve error message when wrong interface is set to server cfg

### ISSUE THREAD

**Issue by IcarusSG** [altmp/altv-issues#384]
## Expected Behavior
It should warn you rather than crash or give a seg fault.

## Current Behavior
Segmentation fault occurs when starting server with wrong IP bound.

## Steps to Reproduce
1. Bind the wrong IP in server.cfg
2. Start server
3. Segmentation fault occurs and core is dumped.

## Context (Environment)
Fresh install:
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

libatomic1 package installed.

I came across this rather by accident, it wasn't until I got to the point of handing over the core dump that I realised that the IP that I was trying to bind to was incorrect.

Reporting it as I assume you would rather it warn server owners rather than create a seg fault.

**Comment by LeonMrBonnie** [comment]
Fixed in next version.
It will now display this error: `Failed to create host, make sure the host field in the server config is properly configured`
