### ISSUE TITLE
Additional vehicle wheel functions

### ISSUE THREAD

**Issue by Shrimpey** [altmp/altv-issues#385]
**Is your feature request related to a problem? Please describe.**
Having a variety of wheel natives is crucial for vehicle-based servers (racing/drifting/car RP servers).

**Describe the solution you'd like**
Implementing following natives/functions:
`alt.Vehicle.GetWheelXOffset(wheelId)` aka trackWidth
`alt.Vehicle.SetWheelXOffset(wheelId, value)`
`alt.Vehicle.GetWheelYRotation(wheelId)` aka camber
`alt.Vehicle.SetWheelYRotation(wheelId, value)`

Above ones are crucial for creating basic stancer resource, in addition, the following ones would improve it even more:

`alt.Vehicle.GetTireRadius(wheelId)`
`alt.Vehicle.SetTireRadius(wheelId, value)`
`alt.Vehicle.GetRimRadius(wheelId)`
`alt.Vehicle.SetRimRadius(wheelId, value)`
`alt.Vehicle.GetTireWidth(wheelId)`
`alt.Vehicle.SetTireWidth(wheelId, value)`

The first set of natives (marked as crucial, ones that would allow to change *TrackWidth* and *Camber* parameters) is implemented in FiveM and allowed for creation of vStancer which is a necessity for a lot of servers. The further ones are not yet implemented there, however their addition would improve stancer a lot (but they are not the top priority).

**Describe alternatives you've considered**
No alternatives

**Additional context**
I am coming from FiveM community. I am fed up with that platform and so is a lot of people. All the major drift servers from FiveM are thinking about switching to alt:v, we're currently doing a lot of research about this platform, however it is necessary to have functions mentioned above available in order to create basic stancer resource.

If it comes to research, there is FiveM's source code (especially [this file](https://github.com/citizenfx/fivem/blob/master/code/components/extra-natives-five/src/VehicleExtraNatives.cpp)) for identifying corresponding natives, as well as original GTAVStancer single player resource that has all the necessary vehicle's memory locations marked, [especially in this file](https://github.com/E66666666/GTAVStancer/blob/master/SlamIt/Offsets.h).

**Comment by Shrimpey** [comment]
Currently experimenting on those additional ones on FiveM, seems as though they do not work as described in SP stancer. That would leave only the trackWidth and camber ones to implement as they are bound to work (unless I stumble upon mem address of proper tire width and radius properties, I'll keep on experimenting). There's also option to set wheel toe (at offset 0x04), but it's not as important.

**Comment by Lhoerion** [comment]
Isn't ``GetWheelYRotation`` possible to get (it's still a bone)?
What's ``GetWheelXOffset`` result, offset relative to vehicle position or something else?

**Comment by Shrimpey** [comment]
As for `GetWheelXOffset` it returns the offset of the specified wheel relative to the wheel's axle center (and not the vehicle's center) so adjusting it moves the wheel along the axle axis.
As for `GetWheelYRotation` do you mean getting it with a native that would return wheel's bone and then get rotation from it? Haven't thought of that, maybe it is the case, not sure if the stancer/fivem implementation of that native is exactly the same it would result from getting bone rotation. Nevertheless, setting the bone is not possible, is it? 

All of those wheel-specific parameters are described in [stancer](https://github.com/E66666666/GTAVStancer/blob/master/SlamIt/Offsets.h) as placed in a block of vehicle's memory dedicated to specific wheel (vehAdd + wheelOffset + camber/trackWidth offset), if modifying bones also modifies those same offsets then it may be the case, however I think that bones are vehicle specific/not wheel specific so would need to experiment to tell whether there's any difference with getter.

**Comment by Lhoerion** [comment]
You can get wheel offset by dividing distance between front/back wheels by 2, but I'm not sure if it's reliable for every case

**Comment by Shrimpey** [comment]
But then, if we had only a dedicated setter for Xoffset that would modify said memory address directly and get the value from calculating 2-wheel midpoint, we would have to assume that there is no height offset between those two (2-wheel midpoint and actual axle center), because that would make results different. So if we were to add Setter I think for the sake of consistency there should be a Getter implemented in the same way.

If there is a function to Set specific bones' rotation then it would probably be sufficient to replace all those functions, however I don't know about a function like this either. Neither fivem nor stancer had any option like this afaik.

**Comment by DurtyFree** [comment]
This contains all offsets & patterns for the requested APIs
https://github.com/E66666666/GTAVStancer/tree/master/SlamIt

**Comment by Shrimpey** [comment]
> This contains all offsets & patterns for the requested APIs
> https://github.com/E66666666/GTAVStancer/tree/master/SlamIt

Yeah, already linked it in an earlier comment. I previously said that I couldn't get those size/width ones to work, but I've added those to FiveM since then based on IKT's stancer offset values (https://github.com/citizenfx/fivem/pull/361). So in Alt:V should be possible as well.

**Comment by alberto2345** [comment]
Would love this feature. It's a really awesome feature for vehicles.

**Comment by MARIO228** [comment]
We would like to see Stancer or such functions to be on Alt:V, since we are interested in that on our server! :)

**Comment by C0kkie** [comment]
Added in upcoming update
