### ISSUE TITLE
Add IResource:GetDeps()

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#387]
**Is your feature request related to a problem? Please describe.**
Get the dependencies of a given resource.

```cpp
virtual alt::Array<alt::StringView> IResource:GetDeps();
```

**Describe the solution you'd like**
Add a method to cpp sdk for IResource that returns a array of IResource pointers or array of strings.

**Describe alternatives you've considered**
Parsing resource.cfg manually.

**Comment by Lhoerion** [comment]
Related to https://github.com/altmp/cpp-sdk/pull/11

**Comment by Lhoerion** [comment]
Related to https://github.com/altmp/altv/issues/387

**Comment by Lhoerion** [comment]
https://github.com/altmp/cpp-sdk/pull/11

**Comment by Lhoerion** [comment]
Related to https://github.com/altmp/cpp-sdk/pull/11

**Comment by FabianTerhorst** [comment]
Already implemented.
