### ISSUE TITLE
Select html element dropdown menu will close after scrolling once

### ISSUE THREAD

**Issue by EtzBetz** [altmp/altv-issues#388]
Dropdown menus created with `<select>` and `<option>` elements will close, when the menu is open and you scroll, after the scroll-animation is finished.

## Expected Behavior
You should be able to scroll through a dropdown-list without it closing.

## Current Behavior
https://youtu.be/nyA6y2kZPK8
The dropdown menu will just close without an option selected.

## Steps to Reproduce
1. Create a webview
1. Add a `<select>` element
1. Add `<option>` elements to it so that the dropdown is scrollable
1. Scroll through the list once

## Context (Environment)
I wanted to create a dropdown, nothing more.

**Comment by AteshM** [comment]
That's not actually an issue, you can disable the scroll control when you open webviews, thats a quick solve, now you just have to find the scroll control id.

**Comment by derRAV3N** [comment]
I have this issue on another codebase that I didn't record the video with, there the weapon-selection/scroll is disabled and the issue still persists.

**Comment by mehrangta** [comment]
It is fixed on cef.
Related commit : https://bitbucket.org/chromiumembedded/cef/commits/95daea76fc2e

**Comment by C0kkie** [comment]
I can't repro it on rc/6.0-rc1, so it should be fixed. If you still have the issue, feel free to reopen it
