### ISSUE TITLE
New export method

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv-issues#391]
Hi. Here is my idea:
Make a global variable called by 'exports' (clientside + serverside) and make a new function called by 'addExport'.

How it works?
You define a function in resource1 and you call 'alt.addExport(testFunction)'  or for example string 'alt.addExport("teststring")' and then call in other script like 
'alt.exports["resource1"].testFunction()'
'alt.log(alt.exports["resource1"].teststring)'

If resource has exports and it stops delete 'alt.exports["resource1"]'

Currently if you have imported from other resource and you restart that server will crash or you need to restart every resource.

**Comment by LeonMrBonnie** [comment]
You can now use `getResourceExports` on both sides (https://github.com/altmp/altv-js-module/commit/650d321ade5ec1207a1f1b51a684975173fc701f)
Making this redundant
