### ISSUE TITLE
Entity is not marked as deleted

### ISSUE THREAD

**Issue by tmcyrix** [altmp/altv-issues#393]
## Expected Behavior
The entity (vehicle) should be marked as deleted and if you try to call something on the deleted entity, you should get a print that the entity does not exist and not that the server crashed immediately.

## Current Behavior
Currently the server crashes when a vehicle is deleted with vehicle.destroy() and then vehicle.getSyncedMeta(""); is called.

## Steps to Reproduce

1. Create an interval, while you call getSyncedMeta on a vehicle entity
2. Remove the vehicle with vehicle.destroy(); in a for loop
3. Server is now crashing

## Context (Environment)
Server instantly crashes, while trying to getSyncedMeta of an entity, that was deleted in a for loop!

**Comment by ItsMos** [comment]
I believe this is the default nodejs behaves when you have an error in a timer, it just crashes if the errored is not caught
A workaround I use is
```js
let _setInterval = setInterval
setInterval =  (fun, time) => {
  let _fun = fun
  fun = ()=> {
    try {
      _fun()
    } catch (error) {
      console.log('Just saved your ass from a stack hook error')
      console.error(error)
    }
  }
  return _setInterval(fun, time)
}

let _setTimeout = setTimeout
setTimeout =  (fun, time) => {
  let _fun = fun
  fun = ()=> {
    try {
      _fun()
    } catch (error) {
      console.log('Just saved your ass from a stack hook error')
      console.error(error)
    }
  }
  return _setTimeout(fun, time)
}
```
you can stick that in your resource index. if you have multiple resources, then you have to try catch every timer manually

**Comment by LeonMrBonnie** [comment]
This doesn't crash the server anymore and throws an error instead.
You should still use the .valid property to check if the entity has been destroyed.
