### ISSUE TITLE
Vehicle.roofOpened property returns opposite value

### ISSUE THREAD

**Issue by echoWanderer** [altmp/altv-issues#395]
vehicle.roofOpened returns opposite value.

## Expected Behavior
false when closed
true when opened

## Current Behavior
true when closed
false when opened

**Comment by Lhoerion** [comment]
I've checked this and it persists on build #997

**Comment by martonp96** [comment]
is the behavior same for SetRoofOpened?

**Comment by martonp96** [comment]
no answer

**Comment by Lhoerion** [comment]
~~Added~~/~~Fixed~~/Changed in build #[1.0-dev18](https://discord.com/channels/371265202378899476/528297438348574741/758928246795665419)
