### ISSUE TITLE
Native function clearPedLastWeaponDamage doesn't work

### ISSUE THREAD

**Issue by sab0h** [altmp/altv-issues#396]
## Expected Behavior

this native clearPedLastWeaponDamage should reset this value hasPedBeenDamagedByWeapon
## Current Behavior

clearPedLastWeaponDamage dont reset hasPedBeenDamagedByWeapon so once its true, its all the time true
## Steps to Reproduce

1. hasPedBeenDamagedByWeapon in a interval
2. if its true, try to set it with clearPedLastWeaponDamage false again

**Comment by ThomasMarangoni** [comment]
I teseted it on release #1301, code to reproduce:

Get Damage by Weapon and then run this:
`
alt.log(game.hasPedBeenDamagedByWeapon(alt.Player.local.scriptID, 0, 2));
game.clearPedLastWeaponDamage(alt.Player.local.scriptID);
alt.log(game.hasPedBeenDamagedByWeapon(alt.Player.local.scriptID, 0, 2));
`

**Comment by LeonMrBonnie** [comment]
Use hasEntityBeenDamagedByWeapon instead to work around this problem.

**Comment by FabianTerhorst** [comment]
This is a gta bug no real priority to fix.
