### ISSUE TITLE
Allow loading of custom RESIDENT.rpf file through client's `mods` folder

### ISSUE THREAD

**Issue by jcfoxtrot54** [altmp/altv-issues#397]
**Is your feature request related to a problem? Please describe.**
On other multiplayer platforms, we can load custom `RESIDENT.rpf` files. This file contains vehicle, weapon and as far as I know ped sounds. A lot of communities rely on this to change police sirens, weapon sounds, and vehicle engine sounds. It's quite a big part of roleplay communities, and any others revolving around realism - including the drift community where I - and others - are looking to migrate to Alt:V. It's taken for granted on the other platforms, hence why we're trying to get it integrated here too.

**Describe the solution you'd like**
We would like the ability to add our own modified `RESIDENT.rpf` files to the `mods` folder in the client's root directory, wherein the default `RESIDENT.rpf` file will be replaced by our custom file, allowing us to have custom vehicle and weapon sounds.

**Describe alternatives you've considered**
As far as I'm aware, there are no other alternatives. Any changes to GTA:V itself results in an `update` in which the modified files are redownloaded for the defaults by the launcher.

**Additional context**
None

**Comment by martonp96** [comment]
Only verified mods are allowed to be loaded "manually" through mods folder. Another option would be to load it through the alt:V streaming methods. For further info check #508 .
