### ISSUE TITLE
Ability to create your own custom streamer

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#400]
**Is your feature request related to a problem? Please describe.**
The basic thing that is found on most types of gamemode is the custom streamer.
It allows you to sync things that are not synced by default, and add other things like custom 3D sounds. I think a good solution would be to implement this inside alt:V. To implement the possibility of creating your own streamer pools.

**Describe the solution you'd like**
Everything could look like this:
```ts
const STR_PACKET_NAME = "ObjectStreamer-Packet";
const streamRange = 50;
const maxEntities = 123;
const calcZ = true;

const objectStreamer = new alt.Streamer(STR_PACKET_NAME, streamRange, maxEntities, calcZ);
objectStreamer.addItem(pos, customData);
```

and then we can handle it however we want clientside, like:
```ts
enum StreamerPacketType {
  ENTITY_STREAM_IN,
  ENTITY_STREAM_OUT,
  ENTITY_DESTROY
}

alt.onServer("ObjectStreamer-Packet", (packetType: StreamerPacketType, pos: Vector3, customData: any) => {
  // check packetType, create your object or do whatever you want.
});
```
_This is just an example and it can probably be done better._

**Describe alternatives you've considered**
Currently in my gamemode all data is calculated on the clientside by R-Tree. I think this should be on the serverside and I'm ready to rewrite it.

The problem with calculating this on the clientside is that when a new player enters the server, you need to send him the entire data package, which will eventually be larger than 512KB.

Just now, when I came to the conclusion that the calculation should be entrusted to the server I thought that it would be great if alt:V had built-in methods for this.

**Additional context**
In my opinion, such a solution would be pleasant for many developers, because a custom streamer is one of the things that should be on most servers - regardless of their type.

**Comment by FabianTerhorst** [comment]
Virtual entities exists on both client and server side on v15.
