### ISSUE TITLE
alt.loadYtyp & alt.unloadYtyp

### ISSUE THREAD

**Issue by DurtyFree** [altmp/altv-issues#402]
**Is your feature request related to a problem? Please describe.**
Ytyps specially created for props that are used in interiors, are only loaded by the game when you are in such an interior. The reason for this is probably performance. But because of this we are not able to create models from those ytyps during runtime (createObject native).

**Describe the solution you'd like**
It would be amazing if we can control the loading & unloading of those on our own by having APIs for that: `alt.loadYtyp(ytypName)` & `alt.unloadYtyp(ytypName)`.

**Describe alternatives you've considered**
It is possible to teleport to the interior that loads your wanted ytyp, create Object with wanted model & teleport back to the created object. It seems like the ytyp will stay loaded this way.

**Comment by indilo53** [comment]
I think it will be good to also be able to register a single archetype or even an array of thoses directly so we don't have to generate ytyp first.

we could have **alt.loadYtyp(ytypName)** / **alt.loadArchetype(archetypeDef)** / **alt.loadArchetypes(archetypeDefs)**

and of course inverse functions

**Comment by DurtyFree** [comment]
Some extra informations from FiveM regarding loading archetypes during runtime:

This is how they handle the REGISTER_ARCHETYPES custom fivem native
https://github.com/citizenfx/fivem/blob/871e449a8eecc3a9b4d5fc48d2cfc2e1823552fb/code/components/extra-natives-five/src/RuntimeAssetNatives.cpp#L919

This contains some code related to getting archetype information
https://github.com/citizenfx/fivem/blob/5f3e25f4bf84cf2e832fff2a04435c25a84f0447/code/components/devtools-five/src/WorldEditor.cpp

This also contains code related to registering & loading archetypes during runtime
https://github.com/citizenfx/fivem/blob/d9c6086cd7778f3f08ee51496e3014b3948e73b9/code/components/gta-streaming-five/src/PlacementHacks.cpp

**Comment by LeonMrBonnie** [comment]
This has been implemented.
https://github.com/altmp/altv-client-js/commit/db45b2361b6ce5d9e90da7e0dd77a3071ce337ac
