### ISSUE TITLE
Add-on vehicle handling not found

### ISSUE THREAD

**Issue by dexslab** [altmp/altv-issues#403]
When you request handling data for an addon model it always errors saying model not found
## Expected Behavior
Should pull handling lines based on vehicles.meta
## Current Behavior
An error occurs stopping the thread when attempting to retrieve handling data

## Steps to Reproduce
1. Add an addon vehicle
2. Spawn addon vehicle
3. Request handling data client side

## Context (Environment)
Just trying to modify handling on custom vehicles

## Detailed Description
Be able to pull custom model handling data and modify it even if its stock handling

**Comment by dexslab** [comment]
What is the status of this bug fix?

**Comment by lameule123** [comment]
Streaming of Handling.meta is one of the most needed feature btw.

**Comment by dexslab** [comment]
Streaming of Handling meta is already supported this issue pertains to using the handling which may actually be an issue that may require more thought after what i have been witnessing

**Comment by martonp96** [comment]
If you upload a test resource that triggers this problem, i can try to fix.

**Comment by tastydev** [comment]
The vehicles just need the handlingName as a class instance property to fix it. Some vehicles like "taxi" just have a different handlingName. In this case "taxi2" (taxi is no addon vehicle). So alt.HandlingData.getForModel should be renamed to alt.HandlingData.getForHandlingName and the veh object should be extended with handlingName @martonp96  see #405

**Comment by martonp96** [comment]
renamed getForModel to getForHandlingName
handling name is not stored anywhere in the game as string, only as hash
alternatively you can use vehicle.handling in dev/1.0-dev15

**Comment by tastydev** [comment]
@martonp96 expieriencing a lot of native calls failing on dev branch and getForHandlingName is undefined 
````[17:52:46][Error] [V8] Exception at statev-rp:client/index.js:3275
[17:52:46][Error]               let handling = HandlingData.getForHandlingName(hash(vehicleHandlingN...
[17:52:46][Error]   TypeError: HandlingData.getForHandlingName is not a function
    at LoginModule.loadVehicleHandlingChange (client/index.js:3275:41)
    at client/index.js:3207:18```

**Comment by martonp96** [comment]
yeah, hazard broke the dev branch and the latest commits are not built yet
everything will be fine as soon as hazard comes online

**Comment by tastydev** [comment]
okay just wanted to inform u cause vadZz told us to test possible dlc fixes on dev branch
