### ISSUE TITLE
Vehicle class handling name property

### ISSUE THREAD

**Issue by Lhoerion** [altmp/altv-issues#405]
**Is your feature request related to a problem? Please describe.**
This would allow to edit handling data for every vehicle model, no matter shared handling data or not

**Describe the solution you'd like**
```
interface Vehicle {
    /** Vehicle handling name */
    public readonly handlingName: string;
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by martonp96** [comment]
handling name is not stored as string anywhere in game's memory
