### ISSUE TITLE
Instant crash in sandbox mode

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv-issues#407]
## Expected Behavior
No crash, or enable screenshots in normal mode

## Current Behavior
After GTAV loading screen game just crashes.

## Steps to Reproduce
Enable sandbox mode

## Version
#972 Beta

## Crashdumps
[altv_972_Social Club_0x7ff6951b0000_c-27-01-2020 09-06-32.zip](https://github.com/altmp/altv/files/4116052/altv_972_Social.Club_0x7ff6951b0000_c-27-01-2020.09-06-32.zip)
[altv_972_Social Club_0x7ff6951b0000_c-27-01-2020 09-08-31.zip](https://github.com/altmp/altv/files/4116053/altv_972_Social.Club_0x7ff6951b0000_c-27-01-2020.09-08-31.zip)

**Comment by Lhoerion** [comment]
Confirmed on build #993
[altv_993_Social Club_0x7ff74dfc0000_c-06-02-2020 17-24-23.zip](https://github.com/altmp/altv/files/4166314/altv_993_Social.Club_0x7ff74dfc0000_c-06-02-2020.17-24-23.zip)

**Comment by martonp96** [comment]
I think sandbox is not supported anymore.
