### ISSUE TITLE
Add onPlayer(Start)VehicleEnter && onPlayer(Start)VehicleExit

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv-issues#408]
**Describe the solution you'd like**
This feature is useful in scripting.

onPlayerStartVehicleEnter triggers when player start entering into vehicle
onPlayerStartVehicleExit triggers when player start exiting vehicle
onPlayerVehicleEnter triggers when player entered into vehicle
onPlayerVehicleExit triggers when player has exited vehicle

**Examples**
```
/* Both clientside + serverside */
/*
Arguments:
- player (entity)
- vehicle (entity)
- seat (number)
*/
alt.on('onPlayerStartVehicleEnter', (player, vehicle, seat)=>{
	alt.log(`${player.name} started entering into vehicle ${vehicle.id}, seat: ${seat}`);
});

/*
Arguments:
- player (entity)
- vehicle (entity)
- seat (number)
*/
alt.on('onPlayerStartVehicleExit', (player, vehicle, seat)=>{
	alt.log(`${player.name} started exiting vehicle ${vehicle.id}, seat: ${seat}`);
});

/*
Arguments:
- player (entity)
- vehicle (entity)
- seat (number)
*/
alt.on('onPlayerVehicleEnter', (player, vehicle, seat)=>{
	alt.log(`${player.name} entered into vehicle ${vehicle.id}, seat: ${seat}`);
});

/*
Arguments:
- player (entity)
- vehicle (entity)
- seat (number)
- stealedBy (entity)
*/
alt.on('onPlayerVehicleExit', (player, vehicle, seat, stealedBy)=>{
	if (stealedBy)
		alt.log(`${stealedBy.name} stealed vehicle from ${player.name}. (${vehicle.id}, seat: ${seat})`);
	else
		alt.log(`${player.name} has left vehicle ${vehicle.id}, seat: ${seat}`);
});
```

**Comment by derRAV3N** [comment]
Just to add from #11, 'onPlayerVehicleChangeSeat' would be neat as well.

**Comment by Lhoerion** [comment]
@derRAV3N
onPlayerVehicleChangeSeat - triggered on player seat change attempt
onPlayerVehicleChangedSeat - triggered when player already changed seat

**Comment by martonp96** [comment]
Events are added except for onPlayerStartVehicleExit. If you want to prevent player from exiting the vehicle, disable the corresponding control.
