### ISSUE TITLE
Change player slots amount and server password at runtime

### ISSUE THREAD

**Issue by Matix8981** [altmp/altv-issues#410]
**Is your feature request related to a problem? Please describe.**
Add allowing from API manage server config, the most important is possibility change password and player slots, other is not that important. 

**Describe alternatives you've considered**
Now exist only one way to change password or slots is restart server

**Comment by FabianTerhorst** [comment]
Modifying player slots at runtime isn't possible afaik.

**Comment by ThomasMarangoni** [comment]
Partly duplicate with #81

**Comment by vadzz-dev** [comment]
Should it save password if changed?

**Comment by Matix8981** [comment]
Without saving

**Comment by C0kkie** [comment]
Change password getting handled here: https://github.com/altmp/altv-issues/issues/81
And changing slots wont be added
