### ISSUE TITLE
Add auto reconnect behaviour

### ISSUE THREAD

**Issue by Michael-xT** [altmp/altv-issues#416]
Hey guys, again with some request, if it is possible it would be nice if the client would have some Auto-Reconnect option in the Server-Menu, like if I want to auto reconnect to server it would be automatically, if not you would need to type reconnect in console. Thanks.

**Comment by FabianTerhorst** [comment]
You can restart the server resources instead of using reconnect. The client also redownloads the client resources that are restarted.

**Comment by DurtyFree** [comment]
As explained, we will not implement such feature. Additionally "auto-reconnect" is also a development only feature right now.
