### ISSUE TITLE
In-game resource download progress bar

### ISSUE THREAD

**Issue by vorty123** [altmp/altv-issues#423]
**Is your feature request related to a problem? Please describe.**
A progressbar that shows resource download while playing (for example, when I restart a resource, I can't see the download progress right now)

**Describe the solution you'd like**
Like in MTA: https://i.imgur.com/xRXVCXm.png

**Comment by FabianTerhorst** [comment]
Will be done for new ui.

**Comment by C0kkie** [comment]
#1212
