### ISSUE TITLE
CEF remote debugging is broken

### ISSUE THREAD

**Issue by vorty123** [altmp/altv-issues#424]
## Current Behavior
CEF remote debug is not working. Just shows a blank white page.
Chrome console errors: https://media.discordapp.net/attachments/557307592129511444/675049453278986290/unknown.png

**Comment by Xenius97** [comment]
I'm using latest beta (#1004), and it works perfectly. https://puu.sh/F9UAa/f3b7f212e3.png

**Comment by FabianTerhorst** [comment]
The bug only happens with chrome 80+

**Comment by Xenius97** [comment]
Also happens with latest Firefox & Edge, but it works with older browsers (Chrome 79.0)

**Comment by FabianTerhorst** [comment]
Fixed in next release.

**Comment by nils-kt** [comment]
Same problem again...

**Comment by midmika** [comment]
> Same problem again...

There is another way: go to ``chrome://inspect/#devices``, wait for it to load and click “inspect” and the debugger will appear in a new window.

![Image](https://github.com/user-attachments/assets/e46416b3-a678-47d7-b954-36188b49b8cc)
