### ISSUE TITLE
Vue.js click events are broken

### ISSUE THREAD

**Issue by vadzz-dev** [altmp/altv-issues#430]
That's connected to weird behavior of event.timeStamp in CEF

https://bitbucket.org/chromiumembedded/cef/issues/2749/osr-results-in-weird-eventtimestamp-values

https://github.com/vuejs/vue/issues/10366

## Expected Behavior

Click event shoud work & event.timeStamp should return normal value

## Current Behavior

event.timeStamp behaves weirdly resulting in vue.js click events behave weirdly too

## Possible Solution

1) downgrade vue to <=2.5.17
2) Use this PR https://github.com/vuejs/vue/pull/11031

## Steps to Reproduce

Check out the link above

**Comment by ericdrobinson** [comment]
The Vue maintainers appear to be 100% focused on Vue3 and have not been merging PRs. This was fixed back during the 2.6.10 cycle with [this approved PR](https://github.com/vuejs/vue/pull/10459). As of today, the PR remains open.

In the meanwhile, an updated version of Vue 2.6.11 with the CEP fix applied is available at [this branch](https://github.com/ericdrobinson/vue/tree/v2.6.11-with-cep-fix).

**Comment by vadzz-dev** [comment]
@ericdrobinson thanks for your reply, but this pr seems to fix the issue only for Adobe's CEP but alt:V uses CEF

**Comment by ericdrobinson** [comment]
@vadzz-dev Then perhaps [this PR](https://github.com/vuejs/vue/pull/11031) would apply? Probably worth a test.

**Comment by vadzz-dev** [comment]
> @vadzz-dev Then perhaps [this PR](https://github.com/vuejs/vue/pull/11031) would apply? Probably worth a test.

Put it as a workaround option

**Comment by Mindsaver** [comment]
> @vadzz-dev Then perhaps [this PR](https://github.com/vuejs/vue/pull/11031) would apply? Probably worth a test.

Has someone tested this PR? for me its not working.

**Comment by toyerovsky** [comment]
Hey. For me disabling windows fast boot option fixed the issue. As mentioned here https://github.com/vuejs/vue/issues/10366#issuecomment-574723737

**Comment by DatMayo** [comment]
You can find the version mentioned above here:
```
https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js //Developement
https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js //Production
```

**Comment by Revyn112** [comment]
Updated today to Vue.js 3 and it is still be a problem with CEF.

**Comment by FabianTerhorst** [comment]
Fixed in next release.
