### ISSUE TITLE
Add current played animation getter

### ISSUE THREAD

**Issue by PoroDev** [altmp/altv-issues#441]
**Is your feature request related to a problem? Please describe.**
I want to detect when a ped client-side is playing an anim with the ai so i can't right now

**Describe the solution you'd like**
I don't know if it's possible to add a property to Ped class so it can handle the anims.

**Describe alternatives you've considered**
Detect some variations on others properties to "know" the anim should be playing

**Comment by martonp96** [comment]
We are not adding features for entities created by natives.
