### ISSUE TITLE
Voice chat - isTalking bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#446]
If you press the voice button (n) many times, you can get a bug where the isTalking property is true on client side while you aren't using that key already, and the voice is not even active.

**Comment by DatMayo** [comment]
@Lekenthu why you closed this issue? Its still a thing.

**Comment by Lekenthu** [comment]
It works fine for me already.

**Comment by Heryshaf** [comment]
It's broken on build #1286, branch release.
isTalking always returns false, micLevel also returns 0
