### ISSUE TITLE
On screen keyboard native is broken

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv-issues#448]
**Current behavior**
On screen keyboard never shows up in altV. Native returns always 'undefined'.
Maybe displayOnscreenKeyboardWithLongerInitialString is broken too, didn't test it.

**Steps to reproduce**
```
var keyboard = game.displayOnscreenKeyboard(0, "FMMC_KEY_TIP8", "", "", "", "", "", 32);
alt.log(keyboard);
```

**Comment by martonp96** [comment]
The native works, see the code by Leon below.
```javascript
function showInputBox(title: string = "", text: string = "", maxLength: number = 100): string {
    return new Promise((resolve) => {
        alt.addGxtText("INPUT_BOX_CUSTOM_TITLE", title);
        native.displayOnscreenKeyboard(0, "INPUT_BOX_CUSTOM_TITLE", "", text, "", "", "", maxLength);

        let tick = alt.everyTick(() => {
            let state = native.updateOnscreenKeyboard();
            if(state === 0) return;
            let result = native.getOnscreenKeyboardResult();
            native.forceCloseTextInputBox();
            alt.clearEveryTick(tick);
            resolve(result);
        });
    });
}
```

**Comment by alphasylvain** [comment]
> The native works, see the code by Leon below.
> 
> ```js
> function showInputBox(title: string = "", text: string = "", maxLength: number = 100): string {
>     return new Promise((resolve) => {
>         alt.addGxtText("INPUT_BOX_CUSTOM_TITLE", title);
>         native.displayOnscreenKeyboard(0, "INPUT_BOX_CUSTOM_TITLE", "", text, "", "", "", maxLength);
> 
>         let tick = alt.everyTick(() => {
>             let state = native.updateOnscreenKeyboard();
>             if(state === 0) return;
>             let result = native.getOnscreenKeyboardResult();
>             native.forceCloseTextInputBox();
>             alt.clearEveryTick(tick);
>             resolve(result);
>         });
>     });
> }
> ```

this code no longer works altv 14.37 :(

**Comment by alphasylvain** [comment]
hi bug :(

**Comment by gurkansahinn** [comment]
up
