### ISSUE TITLE
IsEntityIn, IsPlayerIn, maybe IsVehicleIn -> Broken

### ISSUE THREAD

**Issue by Zynischer** [altmp/altv-issues#449]
Hello, Colshape.IsEntityIn/IsPlayerIn will always return true

**Expected behavior**

It should return true if we are in, else false

**Current behavior**

**Possible solution**

**Steps to reproduce**

`        [Command("t1")]
        public void T1(IPlayer player)
        {
            IColShape col = Alt.CreateColShapeSphere(new Position(0, 0, 0), 3.0f); // We Declare & Create our ColSphere.
            Alt.Log($"col.IsEntityIn(player): {col.IsEntityIn(player)}");
        }

        [Command("t2")]
        public void T2(IPlayer player)
        {
            IColShape col = Alt.CreateColShapeSphere(player.Position, 3.0f); // We Declare & Create our ColSphere.
            Alt.Log($"col.IsEntityIn(player): {col.IsEntityIn(player)}");
        }`
**Context (environment)**

**Detailed description**

**Possible implementation**

**Comment by Zynischer** [comment]
Commands to reproduce:

        IColShape col1 = Alt.CreateColShapeSphere(new Position(0, 0, 0), 3.0f); // We Declare & Create our ColSphere.
        [Command("t1")]
        public void T1(IPlayer player)
        {
            Alt.Log($"col1.IsEntityIn(player): {col1.IsEntityIn(player)}");
        }

        IColShape col2;
        [Command("t3")]
        public void T3(IPlayer player)
        {
            col2 = Alt.CreateColShapeSphere(player.Position, 3.0f); // We Declare & Create our ColSphere.
        }
        [Command("t2")]
        public void T2(IPlayer player)
        {
            Alt.Log($"col2.IsEntityIn(player): {col2.IsEntityIn(player)}");
        }
getting always true

**Comment by H4mm3rb0y** [comment]
yup, under Buster i get the same issue.... Did you figure out a fix/workaround for Linux?

**Comment by Zynischer** [comment]
Hey, the issue is not fixed, dont have any fix/workaround for this.. we could wait for an fix for this :)

**Comment by Lhoerion** [comment]
Issue needs to be reported on appropriate issue tracker [https://github.com/FabianTerhorst/coreclr-module/issues]()

**Comment by FabianTerhorst** [comment]
unrelated to c# module afaik.

**Comment by zziger** [comment]
This is still an issue actually
