### ISSUE TITLE
Add Vehicle Damage event

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#45]
**Is your feature request related to a problem? Please describe.**
A way to react to damage being applied to a vehicle

**Describe the solution you'd like**
A event for it.
```
OnVehicleDamage(IVehicle vehicle, IEntity attacker, uint16_t damage, uint32_t weapon)
OnVehiclePartDamage(IVehicle vehicle, IEntity attacker, uint8_t partId, uint8_t damage)
```

**Comment by robertnisipeanu** [comment]
This really needs to take more priority, I need the damage event for my GM type, doesn't really feel like checking every tick if the vehicle health is different is the best way to do it

**Comment by tastydev** [comment]
I think this request needs a reminder :D

**Comment by c0nnex** [comment]
+1

**Comment by VnX-SolidSnake** [comment]
+1 10000000000%

**Comment by Revyn112** [comment]
+1

**Comment by araynimax** [comment]
+10000

**Comment by BigEll89** [comment]
+1

**Comment by FabianTerhorst** [comment]
Added in next dev release.
