### ISSUE TITLE
macOS Server

### ISSUE THREAD

**Issue by StiviiK** [altmp/altv-issues#451]
**Describe the solution you'd like**
A build of the server which can be run under macOS

**Describe alternatives you've considered**
Running the Server in a docker container

**Comment by FabianTerhorst** [comment]
Afaik the server would be buildable without problems. But you only would have the c# module right now that supports macos.

**Comment by vadzz-dev** [comment]
Yes, the server should be buildable but we do not have any server that has macos rn

**Comment by FabianTerhorst** [comment]
When a server with diamand patreon requests it we will add it to the build pipeline.
