### ISSUE TITLE
Network owner change event

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv-issues#452]
Just a simple event that triggers when the _NetworkOwner_ for an entity changes.

**Is your feature request related to a problem? Please describe.**

Currently you'd need to check every entity in an interval and compare the last network owner to the current one to see if the network owner changed which is highly unperformant.

**Describe the solution you'd like**

OnEntityNetworkOwnerChange(IEntity _entity_, IEntity _oldOwner_, IEntity _newOwner_)

**Describe alternatives you've considered**

**Additional context**

**Comment by c0nnex** [comment]
Bump. Since vechicle properties seem not to be synced unless a vehicle has a NetworkOnwner, it's imported to know when it changes/is set. Currently when you set properties before the vehicle has a networkowner, the information is lost once it get's a networkowner and been overwritten by defaults from the client.

**Comment by FabianTerhorst** [comment]
thats why vehicle properties should only be changed serverside.

**Comment by c0nnex** [comment]
This would make sense if this would be actually be working.
Fact#1: If a vehicle has no syncer and you make changes to the vehicle (e.g. after restart) changes get lost as soon as the vehicle gets a syncer and the values from unsynced client will be used. Workaround as soon as a vehicle is streamedin, check if it ever has been streamed in before, if not move it out of streaming range and back in again after a second so the client accepts the data. 
Fact#2: Some properties are not synced/ignored by the client. (e.g. if a door is missing)
Fact#3: Setting a tyre to flat serverside will lead to the position/rotatrion sync going haywire for spectators
Fact#4: Setting a tyre to missing serverside is completely ignored clientside
Also see #459 and #371

**Comment by WhishN** [comment]
just to bump this once..
Ive had a idea of NPC traffic, in which the server controls all vehicles and on stream in the network owner gives a ped the task to drive around. If a NetworkOwner Change event would be implemented this could be used to give the new owner the right to control the ped as he is the NetOwner anyway.

**Comment by FabianTerhorst** [comment]
Implemented in dev branch.
