### ISSUE TITLE
Slow eventhandlers serverside

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#453]
On serverside eventhandlers of alt.onClient take much more time than same functions/tasks on other threads. (Especially database queries.)

For example, normal code, takes multiple seconds:
alt.onClient("event", function(player) {
//code
})

My method (takes 0.01 seconds with SQL query):
alt.onClient("event", function(player) {
setTimeout(function(player) {
//code
}, 1, player)
})

I made several tests with different codes to measure the code execution time. This is a real problem, please make tests and resolve it, as this affects all servers using events and databases.

**Comment by vadzz-dev** [comment]
What is server & node-module versions? According to tests it should not be a thing in latest node-module

**Comment by Lekenthu** [comment]
RC branch, 1025 build.

**Comment by vadzz-dev** [comment]
Node-module is latest from rc too?

**Comment by Lekenthu** [comment]
Yes, it is also 1025 build.

**Comment by LeonMrBonnie** [comment]
No one else ever reported this problem and I could not reproduce it after a lot of testing.
