### ISSUE TITLE
Entity returned from exported function is not the same with those from events

### ISSUE THREAD

**Issue by AteshM** [altmp/altv-issues#458]
Entity returned from exported function is not the same with those from events

So in short terms, if I do this:

Same RESOURCE! 
file1.js :
`import * as alt from 'alt';
alt.on('playerConnect', player => {
  player.somedata = 1;
  alt.log(player.somedata);
});```
//Here it prints 1.

file2.js:
`import * as alt from 'alt';
import * as chat from 'chat';

chat.registerCmd('test', (player, arg) => {
  alt.log(player.somedata);
}`
//Here it prints undefined.

**Comment by Xenius97** [comment]
That's because you can't set custom value in that way.
Use setMeta && getMeta, or setSyncedMeta && getSyncedMeta

**Comment by AteshM** [comment]
This should not work that way! Its not a different resource, its a bug!

**Comment by KifKick** [comment]
I think this is because of that callback is running in the other resource.

**Comment by FabianTerhorst** [comment]
@KifKick each resource has its own memory and is isolated from each other, so thats not possible.

**Comment by KifKick** [comment]
@FabianTerhorst yeah, but file1.js & file2.js are in the same resource. I suppose that chat is a another one resource. So there I think callback is running in chat resource, and it doesn't have saved .somedata to player object because of resource isolation.

**Comment by FabianTerhorst** [comment]
No the callback is running in the resource where its defined. Unlike normal js behavior.

**Comment by Lhoerion** [comment]
Issue needs to be reported on appropriate issue tracker [https://github.com/altmp/altv-js-module/issues]()
