### ISSUE TITLE
Add Networking entity

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#46]
**Is your feature request related to a problem? Please describe.**
Is needed to add static objects, peds ect. to the client

**Describe the solution you'd like**
A entity that has a position and a synced meta data. The client can use it to read the meta data and create and destroy the ped, object ect. depending on the meta data in entityStreamIn / entityStreamOut.

**Comment by Kudze** [comment]
Bump.

**Comment by Kudze** [comment]
Temporary solution for JS api will be available here: https://github.com/Kudze/altmp-js-network-streamer

**Comment by danartzz** [comment]
bump really useful to have this

**Comment by FabianTerhorst** [comment]
Will soon publish docs how to do it with c# module.

**Comment by FabianTerhorst** [comment]
Added in dev/15.0-dev11
