### ISSUE TITLE
Allow edit and stream of frontend.xml

### ISSUE THREAD

**Issue by Kmz-rash** [altmp/altv-issues#460]
Allowing editing of this file could unlock ne way to design hud with map and such movable easely

For now it's impossible to move some of the basic HUD elements, we can do some stuff in cef/webview but it will be easier to resize/move thoses elements that are native hud from GTA.

For exemple, we could:
- change minimap position easely allowing new hud design.
- resizing minimap.
- adding new minimap for custom interior.
- move streetname position
-editing bigmap and bigminimap size and pos
- Weapon wheel (and it could opent the way to custom weapons "wheel")
**Is your feature request related to a problem? Please describe.**

Well, i want to move the minimap healthbar and stuff without doing cef.
**Describe the solution you'd like**

Just allow stream from this file could be a solution, but don't know if there are undiscovered native that can do that.

**Additional context**

[![Screenshot from Gyazo](https://gyazo.com/6d2b75cddd6fa81ce4e0aac54d3f0ac6/raw)](https://gyazo.com/6d2b75cddd6fa81ce4e0aac54d3f0ac6)

**Comment by C0kkie** [comment]
Works in dev/15.0-dev68:
