### ISSUE TITLE
IVehicle.BodyHealth & IVehicle.BodyAdditionalHealth setter not working

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#463]
**Expected behavior**
Setting the BodyAdditionalHealth to a specific value should keep the new value.

**Current behavior**
BodyHealth/BodyAdditionalHealth stays at value 1000.

If BodyHealth is lower then 1000 (do to damage from driving) and setting it to another value, the setter working partly, it sets the BodyHealth to new damage, but if you take another damage it calculates the health based on the old body health.

**Steps to reproduce**
```
public Task SetBodyAdditionalHealth(uint value)
        {
            return AltAsync.Do(() => BodyAdditionalHealth = value);
        }
```
1. SetBodyAdditionalHealth(800);
2. Check BodyAdditionalHealth.
Same For BodyHealth.

PetrolTankHealth / EngineHealth seems to good and working correctly.
**Context (environment)**
Saving right values to database for vehicle health system.

**Comment by martonp96** [comment]
Fixed in dev/2.1-dev5 or newer.
