### ISSUE TITLE
IVehicle.SetWheelDetached & IVehicle.SetWheelHasTire working partly

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#467]
**Expected behavior**

For Detaching Wheel: `SetWheelDetached(0, true)`
For (Re-)Attaching Wheel: `SetWheelDetached(0, false)`
For burst tire: `SetWheelHasTire(0. false)`
For fixing broken Tire: `SetWheelHasTire(0. true)`

**Current behavior**
Detach Wheel working like expected. (Re-)Attaching the wheel doesn't work visually. 
Burst Wheel working like expected. Fixing broken tire doesn't work visually. 

**Steps to reproduce**
1. `SetWheelDetached(0, true)` - Tire falls off.
2. `SetWheelDetached(0, false)` - Nothing happens (IsWheelDetached changes to false).
3. Going Somewhere else and coming back to Vehicle shows the (Re-)Attached Wheel. (Stream-In)

1. `SetWheelHasTire(0, false)` - Tire bursting.
2. `SetWheelHasTire(0, false)` - Nothing happens (DoesWheelHasTire changes to false).
3. Going Somewhere else and coming back to Vehicle shows the fixed Tire. (Stream-In)

**Context (environment)**
Complex Vehicle Repair System.

**Comment by martonp96** [comment]
The issue is now tracked in #737.
