### ISSUE TITLE
 Tattoos become invisible after a few minutes

### ISSUE THREAD

**Issue by Unrelated-V** [altmp/altv-issues#468]
The Tattoos become invisible after a few minutes and this for 3-4 Minutes and then the Tattoos are Visible. The Project Royal-RP.pink and Dirty-Gaming.com have this problems https://clips.twitch.tv/SleepyIntelligentParrotBabyRage

**Comment by FabianTerhorst** [comment]
Please post Code to reproduce.

**Comment by ehrenlostv** [comment]
game.addPedDecorationFromHashes(alt.Player.local.scriptID,parseInt(tattoos.collection), parseInt(tattoos.overlay));

**Comment by DirtyNenzar** [comment]
Is there any news yet?

**Comment by lameule123** [comment]
I can confirm this bug is present on my server.

**Comment by martonp96** [comment]
Is this bug present both on local player and remote players?

**Comment by DirtyNenzar** [comment]
Currently on our server, it is so that the tattoos do not disappear in one self but in other players already

**Comment by Benni9323** [comment]
I can confirm this Bug. Please fix, issue exists since ma

**Comment by FacesHC** [comment]
Just got this bug while creating the tattooshop stuff I can confirm.

**Comment by martonp96** [comment]
The latest dev build (dev/2.1-dev7) should fix this issue, please try it and provide feedback if you can.

**Comment by FacesHC** [comment]
Wasn't able to reproduce the bug since, so **probably** working

**Comment by martonp96** [comment]
Thank you for your feedback.

**Comment by FabianTerhorst** [comment]
Some more infos. Make sure you don't have more then 128 decals active at the same time. One way to do this is to limit decals per player by one.

**Comment by Niitsuj** [comment]
As soon as someone enters the streamingrange without any decals or tattoos all the other tattoos disappear. 
If the Player applys a tattoo to himself all the other tattoos are visible again

**Comment by SandDanGlokta** [comment]
Any news about this bug?

**Comment by FabianTerhorst** [comment]
Please test again if its fixed with last release build.

**Comment by SandDanGlokta** [comment]
> Please test again if its fixed with last release build.

No. Its still bugging. Overlays (Tattoos) disapear and appear randomly.

**Comment by C0kkie** [comment]
Should be fixed in v15, if not reopen after release
