### ISSUE TITLE
IVehicle.Rotation.Yaw and IPlayer.Rotation.Yaw are visually opposite to each other

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#473]
Spawning a Vehicle based on the Player Rotation leads to opposite behavior.

![image](https://user-images.githubusercontent.com/7781906/76317863-236f1b80-62dd-11ea-88a1-d756d539c578.png)

**Expected behavior**
Spawning Vehicle based on Player Rotation should heading in the same direction.

**Current behavior**
Vehicle Spawns in the Opposite direction.

**Steps to reproduce**
1. Heading with the Player into Rotation 90° or -90°.
2. `CreateVehicle(vehicleHash, player.Position, player.Rotation)`

Both have the same Rotation.Yaw but the Vehicle face in the opposite direction.

**Comment by Revyn112** [comment]
![image](https://user-images.githubusercontent.com/7781906/76319125-08051000-62df-11ea-9ce9-6f935b5a58b3.png)

Invert the Player Rotation for Vehicle Create face the Vehicle in right direction (but player and vehicle have then different Rotation.Yaw values).
`Rotation.Yaw *= -1;`

**Comment by Lhoerion** [comment]
Same as #585, also it's more up-to-date

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.

**Comment by Lhoerion** [comment]
Duplicate of #585, also it's more up-to-date

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
