### ISSUE TITLE
Ability to run server server.cfg as json file format.

### ISSUE THREAD

**Issue by R3DIANCE** [altmp/altv-issues#476]
In my opinion making server configuration json will be much easier to manage and in making panels that you can manage your config server via web/other frameworks, and it might be possible to altv-server load one of them server.cfg/server.json?

**Comment by FabianTerhorst** [comment]
The config file parser is open source. https://github.com/altmp/alt-config

**Comment by R3DIANCE** [comment]
well i need it for web i don't think i can remake it as json tho, but imo json format will be just fine..

**Comment by GVMP** [comment]
`function getConfig() {
    fs.readFile('server.cfg', function read(err, data) {
        if (err) return console.log(err);

        data.toString().replace(new RegExp(/^([a-zA-Z_]\w*)\s*:\s*([^#]+?)$/gm), function(match, g1, g2) {
            if(g2 !== '[' && g2 !== null) {
                let para = parameters.find((p) => { return p.name == g1; });

                if(para) {
                    if(para.type === "number") {
                        server.config[g1] = parseInt(g2);
                    } else if(para.type === "boolean") {
                        server.config[g1] = (g2 == "'true'") ? true : false;
                    } else if(para.type === "string") {
                        server.config[g1] = g2.substring(1, g2.length - 1);
                    } else server.config[g1] = g2;
                }
            }
        });

        console.log(JSON.stringify(server.config));
    });
}`

`{"branch":"release","players":552,"streamingDistance":175,"debug":true}`

Greetings from Dirty-Gaming

**Comment by FabianTerhorst** [comment]
We don't want fragmentation by allowing multiple different formats.
