### ISSUE TITLE
Some Texture Dictionaries cannot be replaced

### ISSUE THREAD

**Issue by DeeJayBro** [altmp/altv-issues#484]
Texture Dictionaries around the airport cannot be replaced (prefix: ap1) with the use of dlc resources

**Expected behavior**

The .ytd File should be replaced correctly

**Current behavior**

A chunk of the world clips out and isn't rendered correctly anymore:
![40e7ba6feab88e11162854bd831a8c2e](https://user-images.githubusercontent.com/11636732/77050048-6d38bf80-69c9-11ea-8f8c-9af0a5a562a4.jpg)

**Steps to reproduce**

I tested it by copying the unchanged `ap1_03.ytd` from the game into my dlc resource with the config:
```
  
files: [
  stream/*
]

meta: {
}
```

**Comment by C0kkie** [comment]
ap1_03.ytd works in dev/15.0-dev11
