### ISSUE TITLE
Native getNewSelectedMissionCreatorBlip always returns 0

### ISSUE THREAD

**Issue by jovanivanovic** [altmp/altv-issues#485]
**Expected behavior**
`getNewSelectedMissionCreatorBlip` native should return blip handle of the mission creator blip that is currently selected on the map.

**Current behavior**
It always returns 0.

**Steps to reproduce**
```
let blipHandle = game.addBlipForCoord(0, 0, 0);
game.setBlipAsMissionCreatorBlip(blipHandle, true);
alt.log(game.isMissionCreatorBlip(blipHandle));
alt.setInterval(() => {
    alt.log(game.getNewSelectedMissionCreatorBlip());
    alt.log("----");
}, 5000);
```

**Context (environment)**
Tried creating an info panel when you select a blip.

**Comment by Lhoerion** [comment]
Confirmed on `build #1092, branch dev`

**Comment by FabianTerhorst** [comment]
The altv blip api got improved and also has the mission creator blip bool now.

**Comment by zziger** [comment]
> The altv blip api got improved and also has the mission creator blip bool now.

I think you misunderstood what native does. That native should return scriptID of currently hovered mission creator blip in fullscreen map, not the missionCreator state of the specified blip

**Comment by zziger** [comment]
It's interesting that the native does work for me on my gamemode, but doesn't on an empty gamemode. I guess that something I do affects it, but still idk what exactly

**Comment by WhishN** [comment]
Its still returning 0 always for me tested on latest dev today
