### ISSUE TITLE
Native function taskEnterVehicle call failed

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#489]
There was a bug when we can't get into vehicles. This solved bythe base F button but for taskEnterVehicle it still happens. We even have error message. It happens randomly. Here is the log and code:
https://pastebin.com/ttLg6kvW
https://pastebin.com/SwdV0VRH

**Comment by FabianTerhorst** [comment]
Not reproducable, will be reopened when reproduction steps are given.

**Comment by Lhoerion** [comment]
I've found out that calling native function `GET_ENTITY_PROOFS` makes above task unusable, because of native call fails

**Comment by Lhoerion** [comment]
@Lekenthu Do you use that native too?

**Comment by Lhoerion** [comment]
No response from the author.

Issue closed because of the specified reason(s).
Feel free to respond back here, if you think that issue should be reopened.

**Comment by FDiskas** [comment]
Get near the car and press B:
Works on `release` branch - does not work on `rc`
Reproducible code:
```ts
alt.on('keyup', async (key) => {
    if (key == 'B'.charCodeAt(0)) {
        const closest = native.getClosestVehicle(
            alt.Player.local.pos.x,
            alt.Player.local.pos.y,
            alt.Player.local.pos.z,
            50,
            0,
            70
        );
        native.taskEnterVehicle(alt.Player.local.scriptID, closest, 5000, 2, 1.0, 2, 0);
    }
});
```
![image](https://user-images.githubusercontent.com/468006/102818187-ceb71000-43d9-11eb-982c-55a25425ae80.png)

**Comment by Hutstaender** [comment]
can confirm, unfortunately not reproduceable yet.

https://i.imgur.com/WECkJob.png
