### ISSUE TITLE
Vehicle rotation inconsitent

### ISSUE THREAD

**Issue by c0nnex** [altmp/altv-issues#494]
Vehcile Rotation is in Degrees until the first Player connects. It then switches to Radians

**Expected behavior**
vehicle.Rotation should be always in radians

**Steps to reproduce**
1. Create vehicle
2. Query Rotation before any player connects. It will be in degrees
3. Connect to server and spawn in streaming range of vehicle
4. Query Rotation again. It will be in radians

**Context (environment)**
Release #1071

**Comment by derRAV3N** [comment]
When I wanted to work with rotation on vehicles yesterday, it didn't even update after a car first being spawned.

**Comment by Lhoerion** [comment]
Confirmed on `build #1088, branch dev`

**Comment by Lhoerion** [comment]
@c0nnex Can you confirm if this issue is still present? I've checked it on latest dev build #1248 and all seems to be working
