### ISSUE TITLE
Add OnVehicleDestroy event

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#5]

**Comment by vadzz-dev** [comment]
What do you mean
Call of veh.destroy() or vehicle becoming undriveable?

**Comment by FabianTerhorst** [comment]
Vehicle that got damaged and then exploded.

**Comment by Zuiron** [comment]
> 
> 
> What do you mean
> Call of veh.destroy() or vehicle becoming undriveable?

think he means, event triggered on vehicle destroy aka explodes.

example:

```
alt.on('onVehicleDestroy', (vehicle) => {
    alt.log(`vehicle with id ${vehicle.id} was destroyed`);
});
```

**Comment by uwe1337** [comment]
that would be really nice :)
