### ISSUE TITLE
Streaming priority of vehicles with players on board

### ISSUE THREAD

**Issue by uwe1337** [altmp/altv-issues#500]
**Expected behavior**

Vehicle with players on board should've streaming precedence before empty vehicles

**Current behavior**

https://youtu.be/KWJA8GOv9ZU

**Possible solution**

N/A

**Steps to reproduce**

https://youtu.be/KWJA8GOv9ZU

**Context (environment)**

N/A

**Detailed description**

N/A

**Possible implementation**

N/A

**Comment by FabianTerhorst** [comment]
Would consider this as a feature not as a bug.
