### ISSUE TITLE
Event playerDisconnect returns wrong player count

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv-issues#504]
When you have i.E. 10 Player on your server and 1 player disconnects, playercount is still the old one  (in the event)

**Expected behavior**
Return the correct player count

**Current behavior**
Returns the playercount including the disconnected person

**Possible solution**
playerCount - 1

**Steps to reproduce**
```
// i.E. 10 player
alt.on("playerDisconnect", (player: alt.Player) => {
  alt.log(alt.Player.all.length); // 10
})
```

**Comment by derRAV3N** [comment]
Do you have 

`alt.on('playerConnect', () => {...})`

somewhere in that resource?
I'm not sure if the bug was fixed, but about a month ago you had to have that even handled or player count was broken^^

**Comment by DatMayo** [comment]
@derRAV3N yes I have. But I'm building a complete new gamemode (with no old code)

**Comment by martonp96** [comment]
It is the correct behavior, since the player is still valid and connected inside the event.
