### ISSUE TITLE
Vehicle class handling manipulation for each vehicle individually

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#505]
Make it possible, to change the handling for each vehicle individually.
It doesn't need to be sync for now.

**Comment by gamelaster** [comment]
Does this even RAGE engine supports?

**Comment by Lhoerion** [comment]
@gamelaster From what I saw I think it supports that

**Comment by martonp96** [comment]
added in dev/1.0-dev15

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[1.0-dev15](https://discord.com/channels/371265202378899476/528297438348574741/756859402094641173)
