### ISSUE TITLE
Event weaponDamage will not be called for helicopter caused damage

### ISSUE THREAD

**Issue by VnX-SolidSnake** [altmp/altv-issues#506]
if you hit someone with the Machine-gun from the Helicopter .... 
the weapon damage event will not be called.
Helicopter : https://wiki.altv.mp/File:Annihilator.png

**Comment by Lhoerion** [comment]
@VnX-SolidSnake Edit the issue content to match template

**Comment by VnX-SolidSnake** [comment]
soooo.... we test it with a ,, Buzzard "...
The Machine guns still not working on the Weapon Damage event... but the rockets work !

so the event is getting called if you hit someone with the rockets ^-^
but with other stuff not.

here a little image : https://imgur.com/a/gYq7yNl

**Comment by 7Hazard** [comment]
Tested in dev, works fine
