### ISSUE TITLE
Entity.getByScriptID method doesn't work properly

### ISSUE THREAD

**Issue by Lhoerion** [altmp/altv-issues#507]
**Expected behavior**

Should return proper entity instance

**Current behavior**

Returns null along with message below*
`GetEntityByScriptID 0000000000000000 0000000000000000`

**Possible solution**

N/A

**Steps to reproduce**

```
const vehicleEntity = native.getVehiclePedIsIn(alt.Player.local.scriptID, false);
alt.log(alt.Vehicle.getByScriptID(vehicleEntity));
```

**Context (environment)**

N/A

**Detailed description**

N/A

**Possible implementation**

N/A

**Comment by c0nnex** [comment]
workaround:
alt.Vehicle.all.find( (v,i,a) => v.scriptID == vehicleEntity))
(same for getByID btw)

**Comment by Lhoerion** [comment]
> (same for getByID btw)
@c0nnex What do you mean?

**Comment by c0nnex** [comment]
alt.Vehicle.getByID and alt.Player.getByID are bugged as well and work unreliable. (50% chance that it works, 50% that it does not)

**Comment by Lhoerion** [comment]
I'll try to confirm that `alt.Entity.getByID` doesn't work sometimes, so far it always worked for me

**Comment by c0nnex** [comment]
Faced that issue some days ago while debugging something with Hazard. He mentioned it's kinda bugged and proposed that find-workaround

**Comment by Lhoerion** [comment]
Yeah, that was used even before said methods above were introduced, but fixing them is important because of their low-level optimization

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[1237](https://discord.com/channels/371265202378899476/528297438348574741/718877443884056596)
