### ISSUE TITLE
Allow streaming of custom resident.rpf file

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#508]
That's a feature, which FiveM couldn't solve yet.
The resident.rpf is the main sound file in GTA, where a lot of sounds are saved.
I've tried to stream it, but it doesn't work at all.
All I know so far is, you can replace them with client mods.

**Comment by martonp96** [comment]
Some files can't be replaced in runtime, because they are loaded when the game starts up. I think it's true for resident.rpf too.

**Comment by GVMP** [comment]
It would already work, if we could replace the resident.rpf on GTA 5 startup, save it as backup and restore it as AltV closes

**Comment by martonp96** [comment]
what if i disconnect from your server and connect to a different one? that server will have the modded sounds too?

**Comment by ZackaryH8** [comment]
Duplicate #397

**Comment by Lhoerion** [comment]
No, it's not a duplicate

**Comment by martonp96** [comment]
Duplicate of #397.

**Comment by Lhoerion** [comment]
Client mods ≠ resource stream

**Comment by C0kkie** [comment]
works in v15
