### ISSUE TITLE
Add IPlayer.Despawn method

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#510]
**Expected behavior**
Player will be despawned and not visible anymore for other players.

**Current behavior**
Nothing happens.

**Steps to reproduce**
`player.Despawn()`

**Context (environment)**
Internal logout function.

**Comment by FabianTerhorst** [comment]
Yes thats because i already implemented that method from cpp sdk, but that method is just a placeholder in the sdk and not yet functional.

**Comment by C0kkie** [comment]
Implemented since 9.0
