### ISSUE TITLE
Client log enhancements

### ISSUE THREAD

**Issue by vorty123** [altmp/altv-issues#513]
**Describe the solution you'd like**
The client should create a new log file every execution, like so:
client_yyyy_mm_dd_c.log, where c is a counter.

For example:
client_2020_04_13_1.log
client_2020_04_13_2.log
client_2020_04_13_3.log
client_2020_04_14_1.log

The other small feature is to log the errors&warnings into a different file, to make normal logs more readable. For example: client_error_yyyy_mm_dd_c.log

**Comment by Lekenthu** [comment]
+1

**Comment by Lhoerion** [comment]
Related to #369

**Comment by martonp96** [comment]
I added it now and the merge is pending.

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[1237](https://discord.com/channels/371265202378899476/528297438348574741/718877443884056596)
