### ISSUE TITLE
Server-side checkpoint not destroying

### ISSUE THREAD

**Issue by typeWanderer** [altmp/altv-issues#514]
You can create server-side checkpoints, but you can't delete (destroy) them.
When you use `Checkpoint.destroy()` it's still valid.

**Expected behavior**
Checkpoint deletes.

**Current behavior**
None.
(Trying to delete a blip it says Removing of Blips is not implemented, is situation the same for checkpoints?)

**Possible solution**
Inform if it's not implemented.

**Comment by Lhoerion** [comment]
Related to #129

It seems that it's problem of module API, so I'm gonna leave this issue and close the old one

**Comment by C0kkie** [comment]
not working. Does not destroy the checkpoint when calling checkpoint.destroy();
