### ISSUE TITLE
Force Feedback feature of controller emulated by x360ce

### ISSUE THREAD

**Issue by SzaBo-BakTeR** [altmp/altv-issues#518]
**Expected behavior**
"alt:v" need update for "x360ce" (https://www.x360ce.com/) plugin support for the "Force Feedback" effect of the emulator.

**Current behavior**
So I have this "Logitech G29 Steering Wheel" (https://www.logitechg.com/de-de/products/driving/driving-force-racing-wheel.html) and the only way to get it work ingame without
hard moding, is to use this Plugin to emulate an xbox controller. There is also full "Forece Feedback" support and if you don't "alt-tab" to desktop, the plugin works just fine in singleplayer and online. But if I start "alt:v", the plugin only load the controllermapping and there is no "Forece Feedback" at all. It would be real nice to have full support for this plugin, because it can handle allmost every gamecontroller on the market and support for "alt:v" could be very usefull to many people who use "Rockstar Games Luncher", because there is only support for xbox controller. Not like in "Steam".

**Steps to reproduce**
"Setting controller in "x360ce" and start "alt:v". There will be no "Forece Feedback" ingame at all, only the controller buttonmapping. 

**Context (environment)**
This problem won't let me have full range of functions with the "Logitech G29 Steering Wheel" if I use "x360ce" Plugin for emulation.

**Comment by Lhoerion** [comment]
This issue is not related to alt:V, but let me figure it out if we can help you in any way.
What version do you use of this x360ce?

**Comment by SzaBo-BakTeR** [comment]
I'm using the one you can download from thier site what I have linked. It is 3.2.10.82.

**Comment by Lhoerion** [comment]
Check the latest alpha version they provide on
https://github.com/x360ce/x360ce/releases

**Comment by FabianTerhorst** [comment]
Unlreated to altv
