### ISSUE TITLE
Change API design of broadcast to all clients

### ISSUE THREAD

**Issue by tastydev** [altmp/altv-issues#519]
I have come to an point where i think i discovered a _bad_ api design (in my opinion) for the **emitClient** function. 

**Is your feature request related to a problem? Please describe.**
 I discovered some bad bugs emitting events to a client cause it ended up with sending to all clients. For unknown reasons the given player object was null (not invalid). (Of course i added some checks now to prevent those miss fired events)

**Describe the solution you'd like**
Maybe it would be better to encapsulate those functions to help and prevent unexpected behaviour.

**Describe alternatives you've considered**
currently: `alt.emitClient(null, 'eventString', ...args)` // this will broadcast
possible solution (make a new function to prevent unwanted null insertion) : `alt.emitAllClients('eventString', ...args)` // this will broadcast

So u clearly have two different functions for broadcasting and single emits and avoid issues with inserting invalid/null player objects.

**Additional context**
The current design is working fine but i think this "enhancement" would avoid headache for future projects to resolve unwanted event emits.

I do not have issues anymore cause i am aware now but i think it would be really good to change this api behaviour.

**Comment by 7Hazard** [comment]
The desired API design could be implemented in an API utilizing the C++ SDK rather than change the SDK's behaviour. Eg the C# API can have that desired API at will.
The C++ SDK does need such a change.

**Comment by vadzz-dev** [comment]
it has scope: node-module, not sdk

**Comment by Lhoerion** [comment]
Issue needs to be reported on appropriate issue tracker [https://github.com/altmp/altv-js-module/issues]()
