### ISSUE TITLE
No speed info by some DLC cars

### ISSUE THREAD

**Issue by schneidermr** [altmp/altv-issues#521]
By some DLC cars the client-side alt:V API's vehicle.speed property always return 0.

**Steps to reproduce**
Some affected DLC car model packs find you below.
https://www.gta5-mods.com/vehicles/ford-mustang-gt-nfs-gt500-2013-add-on
https://www.gta5-mods.com/paintjobs/hun-police-audi-a8

**Comment by martonp96** [comment]
vehicle.speed refers to the value on the speedometer inside the vehicle, alternatively you can use the length of vehicle.speedVector
