### ISSUE TITLE
Allow drawing more than 32 decals at once

### ISSUE THREAD

**Issue by Artiik373** [altmp/altv-issues#525]
I want to be able to draw more than 32 decals (as seen with addDecal native)

**Describe the solution you'd like**
Being able to draw more than 32 decals

**Comment by Lhoerion** [comment]
I assume more than 32 decals at once?

**Comment by Artiik373** [comment]
> I assume more than 32 decals at once?

If i use addDecal beyond 32 times the decals aren't shown/drawn

**Comment by C0kkie** [comment]
We use issue #781
