### ISSUE TITLE
Using special chars (e.g. umlaute) in eventnames

### ISSUE THREAD

**Issue by c0nnex** [altmp/altv-issues#527]
When using special chars in eventnames (e.g. german umlaute) those will be received as utf meta by the client.
Using them in content is fine.

**Expected behavior**
Charset should be converted back correctly

**Current behavior**
charset not converted back

**Steps to reproduce**
alt.emitServer("CLIENT!ähnlich");

server receives the event
"CLIENT!Ã¤hnlich"

**Context (environment)**
Current release #1098

**Comment by martonp96** [comment]
excuse me sir, but there are not enough characters to choose from?

**Comment by DatMayo** [comment]
Special characters should not ne used. You can't even use them in function named, so stick with english words.

**Comment by Lhoerion** [comment]
I wouldn't consider this a bug, more of enhancement, but I'm not sure if it will be implemented at all. I leave the decision whether close it or not to the devs.

**Comment by 7Hazard** [comment]
This would probably increase the packet size of events which is undesirable. Don't think it's necessary to step outside of ASCII's boundries for event names. However, this raises a different kind of bug where it would make sense to also have the server register events the same way the client parses them. Then it would at least be possible to use eventnames with special characters albeit they would be unreadable.

**Comment by 7Hazard** [comment]
This is a point of unhandled bugs, characters outside of the ASCII table are to throw an error

**Comment by LeonMrBonnie** [comment]
Works in 2.2-rc10.

**Comment by 7Hazard** [comment]
Appears to be more of a problem for coreclr-module.
