### ISSUE TITLE
Entity heading is not synced between dimensions

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv-issues#529]
Preparation:

1. Place player in another dimension (i.E. 1).
2. Spawn a car
3. Set entity heading via native (with 250ms delay)
4. Set entity dimension to player dimension

**Expected behavior**
Heading should be set correct

**Current behavior**
Heading is way of (depending of your current heading)

**Possible solution**
Don't do that

**Steps to reproduce**
See above

**Comment by WhishN** [comment]
As the Native needs a scriptID from the vehicle and the vehicle is not visible because it is in another dimension and therefore not created for client it should be 0. So the native cant set anything.

**Comment by DatMayo** [comment]
Yeah but it should be, if the vehicle is streamed in. I think its also related to #494, which is basicly the same streaming issue.

**Comment by martonp96** [comment]
Vehicle rotation bugs are fixed in dev.
