### ISSUE TITLE
Provide ability to turn on vehicle lights when vehicle's engine is turned off

### ISSUE THREAD

**Issue by EtzBetz** [altmp/altv-issues#530]
It would be good to be able to turn on and off the different lights of a vehicle, even if the vehicle's engine is turned off. The default behavior of GTA is to not being able to turn on any light, except the emergency lights of police, ambulance vehicles etc.

This is needed for e.g. (un)locking lights when (un)locking a vehicle.

**Is your feature request related to a problem? Please describe.**
Currently I can't use the normal lights of a vehicle when I want to indicate that it's being locked or unlocked.

**Describe the solution you'd like**
I would like to have a setter and getter on client and/or server to set and get if the various vehicle's lights are turned on/off, this currently only works with natives and when the vehicle's engine is turned on. Also a removal of that requirement, that the engine has to be on, so that I just have to use the native, would be fine for me.

**Describe alternatives you've considered**
We are curently doing this with spotlights, it works, but it's not really fancy, since it looks fake.

**Comment by je-schindler** [comment]
+1

**Comment by EtzBetz** [comment]
Just to note, some months ago when Vektor refactored some internal alt:V code, we found a flag for the vehicle which enabled the turning light to be on (I don't know if permanently or ticking) without the engine being on. If I remember correctly, it was with the group of lights and interior lights. If this could be setable, it would already be enough.

**Comment by FabianTerhorst** [comment]
Added in next update vehicle.lightState = 2;
