### ISSUE TITLE
Buildinfo

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv-issues#533]
Hi guys,

My suggestion is a website, like https://buildinfo.mtasa.com/ where you can find latest changes. This is better than Discord changelog. Or when an update comes to 'release' branch make a wiki page (or a discord message) where you can find all changes (in a list) between current and prevorius versions.

**Comment by ThomasMarangoni** [comment]
A detailed log like this can be accesed by altruists via discord.

**Comment by LeonMrBonnie** [comment]
A list of commits can be found in the #update-log channel in the discord on every update. And a handmade list is made for big updates, so there is not much need for a website like that.
