### ISSUE TITLE
No preloader is shown on resource download

### ISSUE THREAD

**Issue by danilaplee** [altmp/altv-issues#534]
No preloader is shown on resource download when I connect to the server using -connecturl option
this produces a blank space where my character is just hanging mid-air for some time (10 mins for 1.5gb).

**Expected behavior**
default altv loader appearing 

**Current behavior**

**Possible solution**

**Steps to reproduce**

try using -connecturl with any public server
**Context (environment)**

**Detailed description**

**Possible implementation**

**Comment by vadzz-dev** [comment]
Fixed
