### ISSUE TITLE
IPlayer.EntityAimingAt returns a vehicle instead of a player

### ISSUE THREAD

**Issue by xuri02** [altmp/altv-issues#539]
I use IPlayer.EntityAimingAt to find the player another is looking at

**Expected behavior**
A car will be returned if you look at a car, a player if you look at a player

**Current behavior**
two possible behaviors was experienced
1. a player is returned but not the one who is looked at but the player on which the method was called
2. a car will be returned when looking at a player

**Possible solution**
using some other AimingAt methode (not tested)

**Steps to reproduce**
![80847247-3af8bf80-8c0f-11ea-8be1-48450bf89fe6](https://user-images.githubusercontent.com/33527599/89196024-ecf6ad80-d5a9-11ea-953f-589de618ce20.png)

*CODE*
![grafik](https://user-images.githubusercontent.com/33527599/80847242-3207ee00-8c0f-11ea-80f7-045ee84fd9f4.png)

**Context (environment)**
trying to find the player another is looking at
called every 500ms

**Detailed description**

**Possible implementation**
raycast

**Comment by Heady20006** [comment]
another/same issue is clientside with native_getEntityPlayerIsFreeAimingAt().
Result is a vehicle if no one is inside the vehicle, if someone is in vehicle the result is the player not the vehicle.

**Comment by martonp96** [comment]
fixed in rc
