### ISSUE TITLE
Client crashing on vehicle exit

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#540]
### Sometime client crashing on vehicle exit

>  v8::Function::Call: Function to be called is a null pointer

https://cdn.discordapp.com/attachments/557307592129511444/706959373884194816/altv_1174_Steam_0x7ff787610000_c-04-05-2020_22-01-09.zip

**Comment by lameule123** [comment]
The same error suddently appear on my side after enabling tuning script on my server.

**Comment by MacieGx** [comment]
fixed long time ago by VadZzz
