### ISSUE TITLE
Setting currentTime of audio stored in assets does nothing.

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#541]
### Setting currentTime of audio stored in assets does nothing.
Setting media.currentTime does nothing, same `#t=00:01:00` from the example below.
It's working fine for files e.g. from cdn.

**Steps to reproduce**
```js
// Audio should start from 1min
const media = document.createElement("audio");
media.src = "http://assets/your_resource/file.mp3#t=00:01:00";
media.play();
```

**Comment by FabianTerhorst** [comment]
This is a cef bug that needs to be fixed by cef.
