### ISSUE TITLE
Add getter/setter for vehicle paint type

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#545]
**Describe the solution you'd like**
Both native under this message is synced clientside, can u pls add a getter/setter serverside to make it more easy?

native.setVehicleModColor1
native.setVehicleModColor2

**Comment by FabianTerhorst** [comment]
Its only synced when you are the net owner of the vehicle, otherwise the clientside native isn't synced. You should always use the serverside setter.

**Comment by lameule123** [comment]
That's why i open this issue, i want ServerSide setter for this :) !

**Comment by lameule123** [comment]
**Already suggested:** 

> https://github.com/altmp/altv-issues/issues/486
