### ISSUE TITLE
Increase the blip limit

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#546]
**Describe the solution you'd like**
Increase the blip pool to display more than 1800 blips.

**Additional context**
Current Limit is set to 1800.
When u reach it player waypoint become unusable and new alt.PointBlip result in 
Error: Blip creation failed

I hope it is possible, at the time of GTMP we had already largely exceeded this limit without problem.
Maybe u can discuss it with Durty.
Good luck to the altV team

**Comment by Lhoerion** [comment]
We decided to not push the limits, 1 800 concurrent blips is enough.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that issue should be reopened.
