### ISSUE TITLE
WebView freezes on FileDialog

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#547]
**Expected behavior**
WebView should act normal (like it normally does).

**Current behavior**
WebView freeze when using an FileDialog.
https://streamable.com/1u6a5w

**Steps to reproduce**
1. Create WebView with some Live Content (e.g. Time)
2. Open an File Dialog to upload something.

**Context (environment)**
Using Websockets in a seperate WebView for external Voice Solution. Uploading Images to Ingame freeze these WebSocket and Player will be kicked from external Voice Solution.

**Comment by Benni9323** [comment]
::push::

**Comment by Revyn112** [comment]
For reproduce this error use this in webview: https://jsfiddle.net/cz2a597g/1/
Example: https://img.revyn112.dev/data/Zq129gndEu.webm

**Comment by C0kkie** [comment]
Fixed in newest dev
