### ISSUE TITLE
Add ability to stream handling.meta replacements

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#549]
**Simple description**
I think it is vital to be able to stream a complete handling.meta for vanilla vehicles. It's much simpler and the whole modding community has been waiting for this for a while.

**Describe alternatives you've considered**
Converting .meta to JSON and use Handling API.
That require alot of work.

**Comment by lameule123** [comment]
Any Update? Still one of the most needed feature by server owner !

**Comment by lameule123** [comment]
Up

**Comment by tobiplomi** [comment]
Cmon, we need this

**Comment by martonp96** [comment]
Can be done with few lines of code using handling api.
