### ISSUE TITLE
Add ability to stream mp_creaturemetadata.ymt

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#550]
With the creaturemetadata.rpf you can set behavior of component with addon props and clothes.
Like adding a new addon cap and the behavior of the current hairstyle.

**Current behavior**
The expected behavior didn't happend at the moment.

**Steps to reproduce**
Use this example Resource.
[addon-clothing.zip](https://github.com/altmp/altv-issues/files/4665146/addon-clothing.zip)

**Context (environment)**
https://forum.cfx.re/t/how-to-fix-addon-hats/957208/1

**Comment by matzep94** [comment]
mp_creaturemetadata.ymt seems already be streamed. 
The example Resource hast got an Error in the mp_m_freemode_01_mp_m_bugstar.ymt. 
With that fixed it works. (Tested on release [branch)

Updated Resource:
[addonhat.zip](https://github.com/altmp/altv-issues/files/5721058/addonhat.zip)
