### ISSUE TITLE
setPlayerHealthRechargeMultiplier native not working

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#552]
I have try to manipulate this value to define Heal Regen rate clientside.
Sadly native doesn't seem to work :( !

**Current behavior**
Doesn't work. I have test from range 0 to 2f.

**Possible solution**
No one

**Steps to reproduce**
Set Player Heal to 10 and try to use native to activate HealRechargeMultiplier
native.setPlayerHealthRechargeMultiplier(alt.Player.local.scriptID, 1.5)

No effect on health.

**Comment by LeonMrBonnie** [comment]
Setting the multiplier to 0.0 works for me. I haven't tested other values. But also only on RC branch, idk if it is a problem with dev branch

**Comment by lameule123** [comment]
The problem was about not using it OnTick.
Solved
