### ISSUE TITLE
Command line argument for mod resourcefile path

### ISSUE THREAD

**Issue by danilaplee** [altmp/altv-issues#553]
Hi! Me and my team would like to sign and verify the resourcefile for our server before allowing connections. This is needed for security purposes so no injection is done on the clientside. 
I perceive this feature to be a command line argument like this:
```
altv.exe -connecturl http://test.com -resourcefile ./gamemode.resource
```

**Comment by FabianTerhorst** [comment]
Hi, there won't be a exclusive feature that requires a custom launcher. I don't see a reason why you would need this.
