### ISSUE TITLE
Ability to modify the voice volume on clientside

### ISSUE THREAD

**Issue by TheMysteriousVincent** [altmp/altv-issues#554]
The volume of a player in a voice channel is not editable on clientside nor on serverside.
Adding a property which allow the modification of the player voice volume in post would introduce a very powerful option to voice server users.

**This feature request consists of two new features:**

1. A way to modify the volume of others players on clientside by using a property representing a factor
2. A way to modify the output volume of the local player (not the volume factor).

There is a need for a volume factor property, such that one is able to modify the volume of a player manually on clientside, as this is some fundamental feature for, not only, three dimensional voice communication.
Introducing this kind of feature would imply a many more possibilities to the developers using the voice server.

For example:
Introducing only the property to modify the volume in post, could solve the issue of the currently missing fade-out in voice-channels. You guys then also do not have to modify the voice server and the serverside implementation as everything would be further modified by the client.

Besides the need of a factor for volume modification of other players, there is a need for a way to modify the output volume of the local players voice (e.g. an overwrite to the alt:V settings for the microphone volume).

### Is your feature request related to a problem? Please describe.

Currently, there is no way to modify the voice volume of other players manually on clientside and there exists no way to be able to overwrite the microphone output volume of the local player.

#### 1.

I suggest a new property called `micLevelFactor` on the `Player` object:

```ts
export class Player extends Entity {
// ...
    public micLevelFactor: number;
// ...
}
```

where the property is **not** `readonly` and represents a factor that behaves like the following:
- 0 equals no volume (muted locally)
- 1 equals the default volume
- everything above 1 would make the volume louder
- everything below 1 would make the volume quiter

Of course, there should be an upper limit for the factor. For example, `4`. The lower limit is, of course, 0.

Modifying this value on `alt.Player.local` wouldn't change anything, as it is not possible to hear oneself.

#### 2.

The second point is related to overwriting of the local player output volume. Currently, there exists a setting `Output volume` for voice communication in the alt:V settings.

The overwritten volume would be actually the same as the value of the `Output volume` setting.

I imagine three new methods in the global namespace of the clientside module that would be used to get/set the overwritten volume of the local player:

```ts
declare module "alt-client" {
    // ...
    public getOutputVolume(): number; // to get the current output volume.
    public setOutputVolume(volume: number): void // to set the current output volume.
    public getDefaultOutputVolume(): number // to get the setting made in the alt:V menu.
    // ...
}
```

**Describe alternatives you've considered**

There are none yet.

**Additional context**

Note that everything that I request here is solvable by only modifying the clientside of alt:V, because both the modification of other players and the pre-modification of the local player volume (before it is sent to the voice server) is done on clientside.

Both features will introduce new possibilities for the alt:V voice server (very good, though), by only modifing the client for no more effort. Keep this in mind.

I hope this will be added soon.

Thanks in advance.

**Comment by TheMysteriousVincent** [comment]
After having a chat with @7Hazard about the clientside voice, the idea came up to instead use a modification of byte packages for point 1.

An example event for the modification of byte packages I thought of could be:

```ts
alt.on('voiceData', (player: Player, data: Uint8Array) => Uint8Array);
```

An API interface like would not only cover the feature of point 1, it also would make it possible to add some kind of sound effects to the voice a player is hearing from another player.

**Comment by C0kkie** [comment]
Got added in release/2.13

**Comment by TheMysteriousVincent** [comment]
@C0kkie What was added exactly?

**Comment by vadzz-dev** [comment]
@TheMysteriousVincent 
player.spatialVolume // gets/sets volume for 3d voice
player.nonSpatialVolume // gets/sets volume for 2d voice

types will be updated soon
