### ISSUE TITLE
Ability to Set/Get Meta from both Client and Server

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#555]
**Is your feature request related to a problem? Please describe.**

When I am using set and get Meta, if I **setMeta("x", 1)** on clientside, I am unable to **getMeta("x")** on serverside

**Describe the solution you'd like**

The ability to Set a meta and get a meta regardless of whether it is clientside or serverside

**Describe alternatives you've considered**

For now I have used setSyncedMeta and getSyncedMeta as an alternative, however it would be nice to be able to use normal meta

**Additional context**

N/A

**Comment by FabianTerhorst** [comment]
You have synced meta and stream synced meta for this. Modifying that on clientside won't be possible.
