### ISSUE TITLE
Add player current weapon list getter

### ISSUE THREAD

**Issue by SokratesMir** [altmp/altv-issues#556]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add some more weapon API, e.x
**GetAllWeapons** of a player
**GetWeaponTint** of a specific weapon a player has
**GetWeaponAmmo** of a specific weapon a player has
**GetWeaponComponents** of a specific weapon a player has

**Describe alternatives you've considered**
Doing a workaround by tracking the GiveWeapon etc. functions and doing my own getter

**Additional context**
-

**Comment by FabianTerhorst** [comment]
GetCurrentWeaponComponents already exists.
GetCurrentWeaponTintIndex already exists.
Weapon ammo #309 
So you request GetAllWeapons in this issue.

**Comment by SokratesMir** [comment]
As discussed in general chat in discord.
GetWeaponTint(uint weaponHash);
GetWeaponAmmo(uint weaponHash);
GetWeaponComponents(uint weaponHash);

since these functions should be for a specific weapon in the weapon wheel and not only the current weapon.

**Comment by TheMysteriousVincent** [comment]
@Lhoerion This issue is not only referred to the server. On clientside, you can't get all player weapons too.
You would have to check for all available weapon if the player has the weapon.
Thus, I mean, if the server should be able to get all weapons, the client should be able to do so too.

**Comment by Lhoerion** [comment]
By default I assume it's related to server, unless specified otherwise in the issue.

**Comment by FabianTerhorst** [comment]
Added in next release.
