### ISSUE TITLE
DestroyVehicleEvent triggered before PlayerLeaveEvent

### ISSUE THREAD

**Issue by 7Hazard** [altmp/altv-issues#557]
Destroying a vehicle triggers VehicleDestroyed event before PlayerLeaveVehicle
All players inside the to-be-destroyed vehicle needs to be ejected and trigger an EjectedEvent before actually destroying the vehicle

Requires implementing serverside Vehicle Eject function

For devs:
https://gitlab.com/fivenet/fivenet/fivenet-server/blob/master/src/core/CServerAPICore.cpp#L366

**Comment by FabianTerhorst** [comment]
Fixed since some time ago.
