### ISSUE TITLE
SetWheelHasTire have diffrent result when server was on Linux and on Windows

### ISSUE THREAD

**Issue by cherro0125** [altmp/altv-issues#561]
When I used SetWheelHasTire method it's work diffrent on altV server started on Linux machine and on Windows machine.

**Expected behavior**

SetWheelHasTire method should have the same result on all supported OS.

**Current behavior**

SetWheelHasTire(0,false)
 - Result on Linux: first wheel was destroyed. 
- Result on Windows: first wheel is ok.

**Steps to reproduce**

- Spawn Vehicle
- Use SetWheelHasTire method to change wheel state
- Check result when server was on Linux and on Windows.

**Context (environment)**

I used Windows 10 for development with local altV server and Linux Debian for develop/production servers. I used 'dev' branch and C# module for altV server.

**Comment by toyerovsky** [comment]
Any progress on this?

**Comment by martonp96** [comment]
The issue is now tracked in #737.
