### ISSUE TITLE
Crash since last dev build

### ISSUE THREAD

**Issue by chaosfreak93** [altmp/altv-issues#562]
Hey,

the Client crash all the time i want to connect to my server(dev branch).

Server and Client up-to-date.

`[09:45:43][Error] [V8] Module 'alt' is attempting to load non-existant class 'Voice'`

**Comment by chaosfreak93** [comment]
`Crash time: 06.06.2020 09:50:49
Base address: 0x00007FF61FD10000
alt:V Branch: dev
alt:V Build: 1235
Game DRM: Social Club

=========== Exception info ===========
Exception address: 00007FFD14AE2B3E
Exception code: 0xc0000005
Exception flags: 0
======== Exception parameters ========
0. 0x00000097EACFE350
1. 0x00000097EACFE350
======================================

=========== Registers data ===========
Rax: 0
Rbx: 1c823c3edc0
Rcx: 1c823bc0000
Rdx: 1c823bc0000
Rdi: 1c8d88ffa40
Rip: 7ffd14ae2b3e
Rsi: 1c823c3ee40
Rsp: 97eacfe400
R8: 1c823da3140
R9: 1
R10: 8000
R11: 97eacfe360
R12: e
R13: 1c823c3edd0
R14: 1c8d88ffa58
R15: 7ffd14d1b3b0
SegCs: 33
SegDs: 2b
SegEs: 2b
SegFs: 53
SegGs: 2b
SegSs: 2b
======================================`

**Comment by Revyn112** [comment]
can confirm this, same behavior

**Comment by Lhoerion** [comment]
Confirmed on `build #1235, branch dev`

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[1236](https://discord.com/channels/371265202378899476/528297438348574741/718842951857602665)
