### ISSUE TITLE
Colors in disconnected modal

### ISSUE THREAD

**Issue by davis-thereal** [altmp/altv-issues#563]
colors for disconnected modals help user categorize the message directly as an error (ban, kick, blabla)

**Describe the solution you'd like**
maybe use the same type of color formatting as gta / your logger (~ r ~this is some damn red text)

**Describe alternatives you've considered**
HTML Colors maybe?

**Comment by 7Hazard** [comment]
Custom coloring in disconnect reasons will not be supported right now.
