### ISSUE TITLE
Stop server programmatically 

### ISSUE THREAD

**Issue by chaosfreak93** [altmp/altv-issues#564]
Is it possible to add a function on Serverside to stop/restart the complete Server?

**Comment by FabianTerhorst** [comment]
For restart you can just restart the resource via script already.

**Comment by 7Hazard** [comment]
You have the `exit` command. If you want to restart you can use a watchdog script or something.

**Comment by 7Hazard** [comment]
My fault. A function to stop a server via c++ sdk can be added.

**Comment by chaosfreak93** [comment]
What about JavaScript?

**Comment by Lhoerion** [comment]
@chaosfreak93 Module developers will probably implement it, when it'll become available

**Comment by ZackaryH8** [comment]
You can use `process.exit();` along side this .bat for auto-restart

```
@ECHO OFF
SET RestartTimer=5

:Loop
%CD%\altv-server.exe
TIMEOUT /T %RestartTimer%
GOTO:Loop
```

**Comment by LeonMrBonnie** [comment]
Added in next dev
