### ISSUE TITLE
Voice server config does not apply ports

### ISSUE THREAD

**Issue by pixlcrashr** [altmp/altv-issues#565]
The config file for the voice server does not apply the values given in the config file regarding the ports.

Well, the problem is that if the `voice.cfg` was changed to, e.g.:

```
host: '0.0.0.0'
playerHost: '0.0.0.0'
playerPort: '8899'
port: '8898'
secret: '1234'
```

The default ports would be `7798` and `7799` instead of `8898` and `8899`. But the ports in the config are not applied. The default values are used by the voice server.

**Expected behavior**

It should be possible to configure custom ports for the voice server.

**Current behavior**

It seems like the voice server does ignore port settings provided in `voice.cfg`.

**Possible solution**

Just make sure that ports are configurable ;) .

**Steps to reproduce**

1. Download the voice server.
2. Provide a file `voice.cfg` with the contents from above in the same directory as the voice server.
3. Start the voice server.
4. First, check what ip/port combination is shown in the console.<br>Second, check if the wanted UDP ports (in this case 8898 and 8899) are opened (I used portqry on Windows: `PortQry.exe -n 127.0.0.1 -p both -e 8898`).
5. The result should be `UDP port 8898 (unknown service): LISTENING or FILTERED`.<br>But currently, the UDP port is not opened, so the result is: `UDP port 8898 (unknown service): NOT LISTENING`

**Context (environment)**

Currently Windows. Also appears on Linux, but I have only tested it within a container.

**Comment by TheMysteriousVincent** [comment]
Any news on the investigation?

**Comment by danilaplee** [comment]
would love to see a fix for this

**Comment by martonp96** [comment]
fixed in dev444
