### ISSUE TITLE
Add server-side vehicleDamage Event

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#568]
**Is your feature request related to a problem? Please describe.**
Yeah, can't handle vehicle damage at serverside for now.

**Describe the solution you'd like**
Add a vehicleDamage Event like the playerDamage Event.

**Additional context**
Want to trigger some vehicle specific events, when certain damage was taken.

**Comment by FabianTerhorst** [comment]
Duplicate of #45

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[1228](https://discord.com/channels/371265202378899476/528297438348574741/716366843425587280)
