### ISSUE TITLE
Pass player.kick reason to playerDisconnect event reason.

### ISSUE THREAD

**Issue by R3DIANCE** [altmp/altv-issues#569]
**Is your feature request related to a problem? Please describe.**
i guess not.

**Describe the solution you'd like**
pass kick reason type to reason playerDisconnect event.

**Current behavior**
[20:11:04] [chat:cmd] R3DIANCE: /kick r3diance hacking
[20:11:04] R3DIANCE has disconnected from the server. **timed out**

**Comment by Lhoerion** [comment]
Please refactor this issue title and content, it's not as straightforward as it should be

**Comment by C0kkie** [comment]
Should be added with the latest release or? @Lhoerion

**Comment by Lhoerion** [comment]
Indeed @C0kkie 
Added/~~Fixed~~/~~Changed~~ in build #[1234](https://discord.com/channels/371265202378899476/528297438348574741/717942218165583883)
