### ISSUE TITLE
Rename Handlingdata breakForce to brakeForce

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#570]
**Expected behavior**
breakForce should be renamed to brakeForce to keep it constant.

**Current behavior**
It's named breakForce.

**Context (environment)**
brakeForce is the correct name, like in the handling.meta (FBRAKEFORCE)

**Comment by Lhoerion** [comment]
Confirmed on build #[1241](https://discord.com/channels/371265202378899476/528297438348574741/721090791103266816)

**Comment by martonp96** [comment]
fixed in dev
