### ISSUE TITLE
Add additional infos to clientside key presses

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv-issues#572]
At the moment you'll get the key code when you press a key. It would be nice if would be converted to an object like:
```
key: {
  key: 'Control',
  location: 1,
  code: "controlLeft",
  number: 17
}
```
See [http://keycode.info](keycode.info) as an example

**Comment by Lhoerion** [comment]
Why would you want that?

**Comment by DatMayo** [comment]
To check if i.E. left or right ctrl key is pressed

**Comment by Lhoerion** [comment]
You've keyCode already for that

**Comment by Lhoerion** [comment]
Closing on author's request.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.

**Comment by vanlueckn** [comment]
It would be nice to reopen this issue. KeyCodes are deprecated and there are multiple keys with the same KeyCode.

**Comment by xxshady** [comment]
Not sure, but it seems like #1190 is similar to this one
