### ISSUE TITLE
Ability to change vehicle rpm

### ISSUE THREAD

**Issue by R3DIANCE** [altmp/altv-issues#574]
Currently i can't find a way to reset or set vehicle rpm value.

**Is your feature request related to a problem? Please describe.**
In my case, turning off engine and preventing it to turn on again rpm stuck on last value when you  turn engine off and vehicle is shaking. 
you can see it in the video => 
https://streamable.com/0tnjxz

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
