### ISSUE TITLE
stt_ track parts are not usable in ymap

### ISSUE THREAD

**Issue by WhishN** [altmp/altv-issues#575]
If you use objects with a very high lodDist they do not appear until you are very close to them
testet this with several objects having a lodDist and HDtextdist with 5000

Those two Pictures should explain the issue, its not happening in singleplayer
tried making a track with CW and DurtyEditor both ending up in the same result.
https://cdn.discordapp.com/attachments/652672692876607507/723073842670469120/unknown.png
https://cdn.discordapp.com/attachments/652672692876607507/723073917261971517/unknown.png

**Expected behavior**
it should appear at the set distance from codewalker like any other prop

**Current behavior**
its just showing up at like 50m dist... 

**Possible solution**

i dont know exactly what is the problem but i guess its related to the very high lodDist of the object

**Steps to reproduce**

Make a ymap using any editor you want and use any element that has a lodDist of 5000
(many stt_* objects have this lodDist)

**Context (environment)**

tried on release/1181/windows

**Comment by FabianTerhorst** [comment]
Please provide a resource to reproduce.

**Comment by WhishN** [comment]
https://cdn.discordapp.com/attachments/664765088338542598/723468018847580160/testmap.rar

its location is x="160" y="-855" z="30"
West of Park Mission Row PD on the street

**Comment by WhishN** [comment]
as it turns out even CW people dont know how to use this parts in ymaps or they are indeed only usable with native createObject, got informed that this issue is related to the props itself! updated title,
and closing this.
