### ISSUE TITLE
Native game.startRecording not working in rc branch

### ISSUE THREAD

**Issue by r3sist3nt** [altmp/altv-issues#577]
When calling the native `game.startRecording(1)`, the Rockstar Editor doesn't start recording. `game.startRecording(0)` is also not working for action replay.

**Expected behavior**

Editor Starts recording / Action replay

**Current behavior**
Nothing at all Happens

**Possible solution**
-

**Steps to reproduce**
Execute native `game.startRecording(0)`

**Context (environment)**
Recording Clips

**Detailed description**

The Rockstar Editor used to work, by calling the native `game.startRecording(1)`. In the current RC Branch, this call isnt working properly anymore. Nothing happens when calling it. This is, however, working fine in the Release branch.

**Possible implementation**

Edit: Fixed parameter

**Comment by ThomasMarangoni** [comment]
Have you tried `game.startRecording(1)`? Because doc of this native is saying:

> Starts recording a replay.
> If mode is 0, turns on action replay.
> If mode is 1, starts recording.
> If already recording a replay, does nothing.

https://natives.altv.mp/#/0xC3AC2FFF9612AC81

**Comment by tastydev** [comment]
action replay works on release but native call is broken on rc

**Comment by r3sist3nt** [comment]
@ThomasMarangoni action replay and recording is broken. It used to work - and it is working in the Release Branch, but not in the current stable.

**Comment by martonp96** [comment]
fixed in build 1249
