### ISSUE TITLE
DeleteSyncedMetaData - double Trigger to clientside

### ISSUE THREAD

**Issue by R0ckzo0r** [altmp/altv-issues#578]
**Expected behavior**
entity.DeleteSyncedMetaData should trigger 1 time to alt.on("syncedMetaChange", instead it does 2 times 

**Current behavior**
entity.DeleteSyncedMetaData triggers 2 times to alt.on("syncedMetaChange"

**Possible solution**
idk

**Steps to reproduce**
use DeleteSyncedMetaData and log it on clientside.

**Comment by MacieGx** [comment]
i can confirm the issue

**Comment by C0kkie** [comment]
Confirmed on o rc/2.2-rc10

**Comment by martonp96** [comment]
fixed in rc
