### ISSUE TITLE
petrolTankHealth setter truncating most-significant bits

### ISSUE THREAD

**Issue by micaww** [altmp/altv-issues#579]
When using the `petrolTankHealth` setter on the server, only the lowest 18 bits of the number is sent to the client, even though the SDK type is a signed 32-bit number.

**Expected behavior**
Full signed 32-bit number should be sent to client.

**Current behavior**
Setting a number over `262143` using the `petrolTankHealth` setter results in overflow. If you read the value on the client using natives, you will see the wrapped number. If you read the value after setting on the server, it will be what you set it.

I imagine this same behavior happens with other setters too.

**Possible solution**
I would imagine there's some type mismatching / casting that is happening on the way to the client or engine when setting the petrol tank health on the client.

**Steps to reproduce**
- Spawn any vehicle

```js
// server

vehicle.petrolTankHealth = 500000;
console.log(vehicle.petrolTankHealth); // 500000

// client
alt.log(natives.getVehiclePetrolTankHealth(vehicle.scriptID)); // 237856
```

**Context (environment)**
Setting the petrolTankHealth super high makes it basically impossible to blow up a car by shooting the gas tank. Otherwise at the default 1,000 it only takes a couple shots. Other client-side natives don't seem to work to prevent damage to this, so setting the health server-side is how I discovered this issue.

**Detailed description**
The health actually gets set to 237,856, which is the lowest significant bits of 500000. Any damage done to the tank will update the server's health representation correctly.

```js
500000 == 0b00000000000001111010000100100000
// becomes
237856 == 0b00000000000000111010000100100000

// max i32
2147483647 == 0b01111111111111111111111111111111
// becomes
262143     == 0b00000000000000111111111111111111

```

**Comment by C0kkie** [comment]
Will be handeldhere: https://github.com/altmp/altv-issues/issues/737

**Comment by FabianTerhorst** [comment]
I added a check to print a warning when petrol tank health is setted larger then 262143. thats the maximum supported values. there are no 18bit types.
