### ISSUE TITLE
Change server configs in runtime

### ISSUE THREAD

**Issue by R0ckzo0r** [altmp/altv-issues#580]
Possibility to change Server configs like password and name temporary in runtime

Just a simple way to lock the server down with a password in runtime or change the name for it without the need of restart

**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
On c# Module Alt.Server.Settings. ...Name , ...Password etc

**Comment by 7Hazard** [comment]
Changing settings are done on a case-to-case basis. If we wish to modify specific settings like password and player count programmatically, please open up specific issues about them.

**Comment by Lhoerion** [comment]
Duplicate of #81
