### ISSUE TITLE
Native getInteriorAtCoords not working properly

### ISSUE THREAD

**Issue by Izakun** [altmp/altv-issues#583]
When we are in front of an interior (on the road), we get the interior ID. We just need to get the interior ID when we are inside the interior.
The getInteriorFromEntity function work properly thought.

**Comment by FabianTerhorst** [comment]
Please provide sample code to reproduce including coordinates.

**Comment by Lhoerion** [comment]
Tested on `x: 131.1692352294922, y: -197.15603637695312, z: 54.4703369140625`
`alt.log(game.getInteriorAtCoords(alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z));`
Doesn't return 0 even when outside said interior

**Comment by martonp96** [comment]
The issue will be tracked in #522.
