### ISSUE TITLE
Weird portal bug while changing ped model inside an interior

### ISSUE THREAD

**Issue by Kmz-rash** [altmp/altv-issues#584]
Portal seems to be not working properly after you change the model of the player

Juste change the model, tested in MRPD and the Foundry
**Expected behavior**

Portal seems to stop working, collision are still there and when you left the interior trough a portal or noclip it's working again
**Current behavior**

It should display properly the interior.
**Possible solution**

IDK
**Steps to reproduce**

https://www.youtube.com/watch?v=fiqQLjDK8lg&feature=youtu.be

**Comment by ZackaryH8** [comment]
This is a well known issue and is to do with base GTA to mitigate this issue you should use player.spawn after setting the model inside an interior

**Comment by Lhoerion** [comment]
I'll keep it as a reference for devs and for other people that may encounter it

**Comment by Erk71** [comment]
You need to refresh the interior.

You can use this js clientside code as reference.

```
alt.onServer("INTERIOR_RELOAD", () => {
	var pos = alt.Player.local.pos;
	var int = game.getInteriorAtCoords(pos.x, pos.y, pos.z);
	
	game.refreshInterior(int);
});
```

Worked for me, hope it helps.

**Comment by martonp96** [comment]
There are many solutions, like setting player pos, respawning player or refreshInterior as you can see above

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[1248](https://discord.com/channels/371265202378899476/528297438348574741/730935744121536643)

**Comment by Lhoerion** [comment]
Confirmed on build #1248

**Comment by martonp96** [comment]
The issue will be tracked in #522.
