### ISSUE TITLE
Entity rotation issues

### ISSUE THREAD

**Issue by tastydev** [altmp/altv-issues#585]
As latest rc/dev branch should fix serverside getter and setter issues i will summarize rotation bugs which are still present.
**Build: #1249**
Doing a new Issue cause some fixes has been applied so behaviour changed.

**Expected behavior**
Getter and setters for entitys should be the same system

**Current behavior**
Probably the rotation for a vehicle is right if u get it but only gets applied right when the value is set to the constructor of a new vehicle.
If u set the same value for an existing vehicle the heading will be still inverted.

The player heading getter is right and setter sets to the right direction but the old heading gets reapplied to the player.
So still not reliable. 

**Possible solution**
fix invert bugs

**Steps to reproduce**
**vehicle:**
1. alt.log(player.vehicle.rot.z)  result: 1.4688
2. player.vehicle.rot = new alt.Vector3(0, 0, 1.4688) result: veh will be inverted (180° invert) to wrong heading
3. new alt.Vehicle('adder', player.pos.x, player.pos.y, player.pos.z, 0, 0, 1.4688); result: right heading on new veh
**player:**
1. alt.log(player.rot.z)  result: 1.4688
2. player.rot = new alt.Vector3(0, 0, 1.4688) result: will be set right but old heading gets applied ~100ms later

**Comment by martonp96** [comment]
Fixed

**Comment by tastydev** [comment]
still not fixed reproduce on step 4

**Comment by tastydev** [comment]
Someone on discord reported the rotation setter teleport bug, too.
https://discord.com/channels/371265202378899476/547079158300147725/776450765043925002

**Comment by martonp96** [comment]
Fixed in dev56
