### ISSUE TITLE
Client crash when in different dimension with voice server

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#586]
Player 1 crash if player 2 ist talking in spatial voice channel in another dim but at the same position

**Steps to reproduce**
player 1 and player 2 should talk to each other in one dimension and one of them change dimension

**Comment by MalteCr** [comment]
it does not occur if player1 (talking) is in dim 0 and player2 is in a private dimension. Maybe there is no dim check at the voice server?

**Comment by FabianTerhorst** [comment]
We are not able to reproduce the crash in latest dev branch, feel free to comment when you still can reproduce it on dev.
