### ISSUE TITLE
Frame rate issues

### ISSUE THREAD

**Issue by VnX-SolidSnake** [altmp/altv-issues#588]
Dear alt:V Team...
I don't know why some people not realized this bug or reported it either..
My Friends & me have this bug for months....

If you Restart alt:V a little but much or Reconnect the whole Time... you will have CEF Lags.
And no it doesn't depend on our code... you have the lags even in the Masterlist & Home Window of alt:V...
Alot of People from Roleplay Server i know, have this damn issue... 

Please ... Please just fix it... it isn't cool if you have animations or other stuff in your CEF window with 10 FPS.
The Game isn't lagging... just the CEF stuff....

Thank you.

~ Solid

**Comment by gamelaster** [comment]
@VnX-SolidSnake Any more information about it? What OS and GPU?

**Comment by so-lar** [comment]
Sometimes I reconnect/restart like 50-100 times a day. But I never had this issue.

**Comment by Lhoerion** [comment]
We need more detailed information about the issue you've encountered, reproduction steps, hardware and OS information (best dump by dxdiag). Also we need to be sure that the issue isn't caused by your code, so the best way would be to reproduce it with minimal resources. Without these informations, the issue will be closed

**Comment by VnX-SolidSnake** [comment]
@Lhoerion ,,Also we need to be sure that the issue isn't caused by your code, "

I started alt:V for the first time today and i have CEF lags in my alt:V Homescreen.... WTF...

Hardware Specs : 
~ AMD Ryzen 5 2600
~ AMD RX 580
~ 16 GB RAM
~ Windows 10 Pro

i don't know why i have these bugs... some days i can restart my Client like 1000 times ... and nothing happens...
but some days ( like rn -.- ) i can't even connect to a server because my alt:V Masterlist are lagging...

this isse is on NVidia Graphic cards & intel CPU's too...

**Comment by FabianTerhorst** [comment]
does it only happen when you connect to your own server before?

**Comment by VnX-SolidSnake** [comment]
@FabianTerhorst I just connected in my whole alt:V time on 3 servers... on all the 3 servers it was like that.

~ V2 Gangwars
~ Extended Gangwars
~ German Classic Roleplay

and the last one is my server... yes.

its only CEF Lags... like if you animate stuff or something ... you will see the animation with 2 FPS xD

but the ingame-background is still working you know ? 

and it lags in the alt:V masterlist homescreen etc.

~ Solid

**Comment by VnX-SolidSnake** [comment]
Soo....

After like 7 Restarts or something... 
Please take a look at the Button-Hover in the alt:V Homescreen/Server select.

In the Browser all the Animations works perfectly fine.
If i restart my PC ( not everytime but most of the cases after 1-2 restarts ), the Lags are gone.
Most of the lags are in Animations...

Here is a little preview how fucked up it looks like on my PC -.- :(

https://www.youtube.com/watch?v=08hOsN2G6ho

**Comment by folienkleber** [comment]
https://youtu.be/WJVNInhWHio
fix pls

**Comment by FabianTerhorst** [comment]
Try to check if it also happens when you only connect to a empty server and reconnect.

**Comment by VnX-SolidSnake** [comment]
> Try to check if it also happens when you only connect to a empty server and reconnect. Even when the lag also happens in altv ui doesnt mean its not caused by the gamemode.

it doesn't matter because you have lags in the homescreen too.

**Comment by FabianTerhorst** [comment]
read the message again that i send.

**Comment by Stuyk** [comment]
Framerate issues could be caused by incorrect loading SVGs and constantly loading those SVGs over and over again.
Vue based frameworks can use a component like this to help with `prefetch`.

```
function createIconComponent(iconName) {
    Vue.component(`icon-${iconName}`, {
        props: ['title'],
        data: () => {
            return {
                url: `../icons/${iconName}.svg`
            };
        },
        methods: {},
        template: `<img rel="prefetch" :src="url"/>`
    });
}
```

**Comment by VnX-SolidSnake** [comment]
> Framerate issues could be caused by incorrect loading SVGs and constantly loading those SVGs over and over again.
> Vue based frameworks can use a component like this to help with `prefetch`.
> 
> ```
> function createIconComponent(iconName) {
>     Vue.component(`icon-${iconName}`, {
>         props: ['title'],
>         data: () => {
>             return {
>                 url: `../icons/${iconName}.svg`
>             };
>         },
>         methods: {},
>         template: `<img rel="prefetch" :src="url"/>`
>     });
> }
> ```
> 
> Side note: Some graphics cards at `MSAA 8x+` cause frame rate drops. Try lowering it.
> Other issues can include resources not unloading their events, icons, etc.
> These things can stack up lower FPS of a single CEF instance.

Hello Stuyk :),

First of all thanks for your help, but we use plain JS + JQuery for our HTML Code.
Our Animations are most of the case CSS Animations ... 
The MSAA 8x+ error... have i to change it via my Graphic Card Settings ( AMD Graphic settings ? ) or inside my GTA 5 Settings ? 
or both? 

Thanks for your help

~ Solid

**Comment by gamelaster** [comment]
> The MSAA 8x+ error... have i to change it via my Graphic Card Settings ( AMD Graphic settings ? ) or inside my GTA 5 Settings? or both?

@VnX-SolidSnake 
Changing in GTA 5 Settings should be sufficient.

**Comment by VnX-SolidSnake** [comment]
i've to say.... i'm on RC Branch...

After i changed ,,MSAA" to ,,off" .... it seems after some restarts, cache deletes & more to work...

i will test it for 3-7 Days....
But it looks very good right now :)

**Comment by vorty123** [comment]
It has to do something with resource restarts too, because after a few resource restarts the CEF CSS3 animations start to visibly lag.

**Comment by Stuyk** [comment]
> 
> 
> It has to do something with resource restarts too, because after a few resource restarts the CEF CSS3 animations start to visibly lag.

Generally speaking, you should be turning off and destroy WebViews on resource restarts as a just in case.

@VnX-SolidSnake Any updates?
