### ISSUE TITLE
MLO doesn't get loaded

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#589]
**Expected behavior**
MLO should be loaded.

**Current behavior**
MLO won't be loaded in alt:V, but without problems in Codewalker and in FiveM.

**Steps to reproduce**
Take the MLO-resource, i've sent to Tuxick.

**Context (environment)**
This is the first time, i didn't managed to get a MLO to work. The big difference here (to other MLO) is, that his much bigger and has a polycount around 300.000. Im not 100 percent sure, if this is the issue but yeah, could be worth a look into it.

**Comment by martonp96** [comment]
The MLO streaming works perfectly in alt:V, if your MLO is not working, then you are doing something wrong.

**Comment by 7Hazard** [comment]
alt:V is less forgiving than FiveM when it comes to MLO loading. FiveM for example always displays warnings about poorly made MLOs.
