### ISSUE TITLE
Streaming hollywood.ytd doesn't work

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#590]
When trying to stream hollywood.ytd, it only seems to stream one specific file out of the entire dictionary. The .ytd is <16Mb and there is no warning client side about it exceeding this limit. I have attached the file with the modified textures and an image to show the 1 texture it does stream.

**Expected behavior**
It should stream all textures in the .ytd file

**Current behavior**
It only streams one of the textures out of the entire dictionary

**Possible solution**

**Steps to reproduce**
- Download the resource (linked below)
- Go to Vinewood Bank
- See the 1 texture has been changed out of the 27 in the dictionary

**Context (environment)**
I am trying to replace the road textures and this issue is not allowing me to do this

[Download](https://drive.google.com/file/d/1osV4Hag0Py4s-PQ8TlIHXJB2zHnip2gO/view?usp=sharing)
![image](https://user-images.githubusercontent.com/40175773/88458403-bfad4f80-ce85-11ea-89e9-ee4f789bb236.png)

**Comment by C0kkie** [comment]
@ZackaryH8  what exactly should be changed too? Also can you check on newest dev?

**Comment by C0kkie** [comment]
Since there is no response and it looks fine to me in v15, i will close it
