### ISSUE TITLE
Browser drag-and-drop functionality doesn't work

### ISSUE THREAD

**Issue by DeathNeroTV** [altmp/altv-issues#591]
this issu is driven by used actual cef system, many events or functionallity not working right.

if i used cursor: pointer; in css file it's not working in the html file, cursor not ruren into a hand pointer like css announces.
the whole html dnd system not working, in my browser on pc it handels this events, but not ingame browser.
hovering working without shwoing pointer cursor. seams their are missing some expected functionallity to cursor:pointer; (css)
and the whole dnd system for moving elements from one place to another.

**Comment by FabianTerhorst** [comment]
Cef html5 drag and drop is not implemented because its also for moving stuff from windows to cef not just to use inside apps. I would recommend to use custom drag and drop written in js. The Cursor is currently the Cursor gta uses. Maybe there is something possible to modify it with custom apis.

**Comment by LeonMrBonnie** [comment]
Please use the Bug report template.
Also drag and drop not working CEF is known already.

**Comment by DeathNeroTV** [comment]
Which dnd in jus would you recommed to me, cause found variouse versions, but don't know which i should use.
Can you recommend from own knowledge in using seams perfect actually?

**Comment by 7Hazard** [comment]
The different cursor types was recently fixed. It will reach dev at some point.

**Comment by DeathNeroTV** [comment]
okay :) thanks for the fast help for cursor fix 👍

**Comment by LeonMrBonnie** [comment]
https://github.com/kutlugsahin/smooth-dnd
This is a DND library that should work.

**Comment by kineese** [comment]
Nice drag and drop for ReactJS
https://github.com/atlassian/react-beautiful-dnd

**Comment by Lhoerion** [comment]
As explained above, drag & drop needs own implementation.
In the future stick to the issue template, it makes things much easier for us.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
