### ISSUE TITLE
Native setPedFaceFeature id 19 is not synced

### ISSUE THREAD

**Issue by AlienDwarf** [altmp/altv-issues#593]
`native.setPedFaceFeature(ped: Ped, index: int, scale: float)` is not sync with index 19 (neck width). You can see the changes on your own character but other players can not see any changes.

**Expected behavior**
The neck width should be sync like the other face features. 

**Current behavior**
Only the player can see the changes on his own character.

**Steps to reproduce**
Let **someone else** adjust neck width and try to see any changes. The other indexes are working.

**Context (environment)**
Branch: rc
Language: JS

**Comment by FabianTerhorst** [comment]
Fixed in next update.

**Comment by martonp96** [comment]
We tested it and it works, don't forget to set head blend data first.

**Comment by martonp96** [comment]
Still, we tested it and it works, if it doesn't work for you then please provide steps how to reproduce on an empty server, until then, case closed.
fyi @C0kkie
