### ISSUE TITLE
CEF - Windows will not receive any Events.

### ISSUE THREAD

**Issue by VnX-SolidSnake** [altmp/altv-issues#594]
Hey alt:V Team,

i found a new issue...
if you require this script inside your Body Code via HTML, your WebView will not receive any events...
It won't show any errors/-warnings ( only some cookie warning inside chrome ).

https://hastebin.com/iqenipidiz.js
`<script src="music.js"></script>`

~Solid

**Comment by tastydev** [comment]
it works fine u probably doing something wrong in u are implementations then

**Comment by VnX-SolidSnake** [comment]
just add this single file inside your HTML Code...
it won't receive any alt:V Events O.o

**Comment by vorty123** [comment]
There is a bug that you need to wait 1 second after creating webview

**Comment by VnX-SolidSnake** [comment]
dude... it won't receive any events even after 2 hours...

**Comment by VnX-SolidSnake** [comment]
i don't get it... how hard it is to understand ?.... 

if you put this file into your HTML code.... you won't be able to receive any events... don't matter how long you wait... 
it won't call any alt:V browser event...

**Comment by FabianTerhorst** [comment]
Please create code to reproduce your issue with minimal setup as possible, e.g. a git repo.

**Comment by vorty123** [comment]
> i don't get it... how hard it is to understand ?....
> 
> if you put this file into your HTML code.... you won't be able to receive any events... don't matter how long you wait...
> it won't call any alt:V browser event...

I just wanted to help you, why are you so f*kin rude?

**Comment by VnX-SolidSnake** [comment]
I did not want to offend you... sorry

**Comment by martonp96** [comment]
can you please find which line causes the problem in your script?

**Comment by martonp96** [comment]
no answer
