### ISSUE TITLE
Taking self inflicted damage and then setting health to 0 makes the player the killer

### ISSUE THREAD

**Issue by zacbarnaby** [altmp/altv-issues#597]
If I take damage, say for example; I drive my vehicle in to a wall which reduces my health and then I set my health to 0, the `playerDeath` event is trigger and the `killer` parameter is set to myself.

**Expected behavior**
The killer parameter should be unset/undefined/null.

**Current behavior**
The killer parameter is set to myself/current player.

**Steps to reproduce**
Drive in to a wall and take damage. Set `player.health = 0`. Check the `killer` parameter.

**Context (environment)**
I was handling the player death depending on suicide or whether they was killed by another player.

**Comment by EtzBetz** [comment]
What happens when another person damages you and then you set health to zero? Are you still the killer, oder the other player?

**Comment by zacbarnaby** [comment]
I can check this and get back to you.

**Comment by C0kkie** [comment]
Will be fixed in an upcoming dev version
