### ISSUE TITLE
Incorrect password message shows after downloading resources

### ISSUE THREAD

**Issue by jovanivanovic** [altmp/altv-issues#598]
I tried to connect to a server earlier. Went through early auth that was checking my browser through CloudFlare I think and then I was on the "downloading resources" popup. After it downloaded the resources, it told me that I entered a wrong password.

**Expected behavior**
"Incorrect password" popup should be shown before all the other stuff so you don't download resources before you are sure that you will connect.

**Current behavior**
"Incorrect password" popup shows after the resource download.

**Possible solution**
See expected behavior above.

Note: this happened on RC branch.

**Comment by FabianTerhorst** [comment]
Not possible to fix.
