### ISSUE TITLE
Make slipstream settable per vehicle, fix visuals, make boost customizable

### ISSUE THREAD

**Issue by EtzBetz** [altmp/altv-issues#599]
https://natives.altv.mp/#/0x36492C2F0D134C56 and https://natives.altv.mp/#/0xE6C0C80B8C867537 can be used to enable and get values of slipstream boosts.
_0xE6C0C80B8C867537 enables it on a client as a whole, for the player who drives behind another player. The player in front doesn't have to have it enabled, but he won't see the visual effects in that case.
(Just FYI: Interestingly, I'd have suspected that when having it enabled as the front player and disabled as the back player, that the front player sees visuals, but this isn't the case.)

I'd like a to be able to have slipstream settable per vehicle, makes more sense to me.

Also it would be nice to have the visuals displayed for everyone, no matter if that person has slipstream enabled/sits in a slipstream enabled vehicle.

A nice final step would be to be able to customize the "ramp-up-time" for the boost, as well as customizing the total boost value.

**Is your feature request related to a problem? Please describe.**

Not really. The only problem is that players which don't have it enabled, don't see the visual effects.

**Describe the solution you'd like**

A getter and setter like <Vehicle>.slipstream [ true | false ] would be nice.
For the ramp-up time and total boost value, there should be some globally settable value in my opinion, I'm not sure about this, tho, open to discussion.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
