### ISSUE TITLE
Add vehicle bulletproof tyres property

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#600]
Title pretty much explains it all. Would like a server-side getter/setter for bulletproof tyres on vehicles.

More vehicle modifications = better yes? :)

**Is your feature request related to a problem? Please describe.**

No it aint related to a problem, aside from the fact that we can't set tyres bulletproof server-side yet.

**Describe the solution you'd like**

A setter/getter, something like "vehicle.BulletproofTyres = true/false".

**Describe alternatives you've considered**

Could do it manually w/ some native probably, and sync it manually. but would be much better if it were a part of the ALTV vehicle system itself

**Additional context**

**Comment by AlteredCarbonate** [comment]
I don't really get the point.
"Bullet proof tyres" usually is set with a .meta

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
