### ISSUE TITLE
Vehicle getStreamSyncedMeta and Vehicle getSyncedMeta are not identical or undefined on all clients

### ISSUE THREAD

**Issue by inpex** [altmp/altv-issues#601]
Vehicle getStreamSyncedMeta and Vehicle getSyncedMeta are not identical or undefined on all clients

Branch is rc

           let pos = GetEntityFrontPosition(alt.Player.local.scriptID)
            alt.Vehicle.all.forEach((el) => {
                    var id = el.getSyncedMeta("dbId");
                    alt.log("Id " + id);
            });

here times 2 logs of the code. 2 different players
https://cdn.discordapp.com/attachments/547079158300147725/742346198085533806/unknown.png

**Expected behavior**

Two players made the same log

**Current behavior**

Some vehicles have no synced data for one player

**Possible solution**

**Steps to reproduce**

i can repeat mistakes with an affected player. 
Player has also already reinstalled alt:V

**Context (environment)**

**Detailed description**

**Possible implementation**

**Comment by inpex** [comment]
Only on my Linux server

**Comment by tastydev** [comment]
The vehicle has to be in streaming range for streamSyncedMeta mate!
Show full code.

**Comment by inpex** [comment]
@tastydev 
problem also exists with vehicles with a distance of 2 meters

**Comment by FabianTerhorst** [comment]
Feel free to reopen when bug still happens in latest dev.
