### ISSUE TITLE
2060 native bugs

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#602]
Hi.

3 natives (Maybe all the vehicle natives are bugged) are bugged in the 2060 branch version. (alt:V build: 1275)
These are:
setVehicleTyresCanBurst
setVehicleCustomPrimaryColour
_0x5B91B229243351A8

**Comment by lameule123** [comment]
Use ServerSide setter for:
setVehicleCustomPrimaryColour

**Comment by Lekenthu** [comment]
> Use ServerSide setter for:
> setVehicleCustomPrimaryColour

 For vehicles which are created client side I can't use server side functions.. :))

**Comment by lameule123** [comment]
Why are u creating vehicle clientside ?

**Comment by Lhoerion** [comment]
Stick to the issue template, also what `_0x5B91B229243351A8` function does?

**Comment by Lekenthu** [comment]
> Stick to the issue template, also what `_0x5B91B229243351A8` function does?

It is about vehicle damage



> Why are u creating vehicle clientside ?
> It's possible that this native will be disabled in the future

I creat vehicles client side because using other way would mean unnecessary syncronization.

**Comment by tastydev** [comment]
Can confirm much vehicle natives are broken right now i.e setVehicleNeonLightsColour and setVehicleNitroEnabled, too

**Comment by Lekenthu** [comment]
It's working. Thanks.
