### ISSUE TITLE
Native setVehicleNitroEnabled not working as it used to

### ISSUE THREAD

**Issue by DasNiels** [altmp/altv-issues#604]
**Client/server version**

`Build #1278, branch RC`

**Current behavior**

Before this update, when I'd call the setVehicleNitroEnabled native, it would enable it on the vehicle and show that little yellow progress bar below the map(next to health and armor). and nothing else. Which was fine. But now it adds that yellow bar and automatically shows the effect that it triggers on the exhausts(flames particle).

Also, when activated, the yellow bar should deplete over time, which it used to do but doesn't any more. The nitro does end after a couple of seconds but the UI doesn't update it accordingly.

**Expected behavior**

When called, it should add the yellow progress bar and add nitro to the vehicle, but not yet activate the particle until the appropriate button is pressed to activate it(X by default on gta 5)

**Steps to reproduce**

1. Call this in a client script that initializes on connect: natives.requestNamedPtfxAsset( "veh_xs_vehicle_mods" );
2. When spawning a vehicle, call the nitro native and set the 2nd parameter to true.
3. the yellow bar at the bottom left should appear, but it's completely static and doesn't update at all. The effect is also permanently shown(it should only show when the nitro is activated by pressing X)
4. Pressing X still activates nitro, but the yellow progress bar does not deplete or anything.

**Context (environment)**

Got a nitro feature in my server, which worked fine until this update.

**Possible solution**

No clue really, I'm guessing something internally changed? I've noticed there being other vehicle natives that were bugged and patched earlier today.

**Comment by DasNiels** [comment]
Did some more testing around. it seems that in the latest gta 5 update they reduced the duration for nitro on arena wars vehicles. I'm assuming this could have something to do with the native now being broken-ish?

Also, when spawning an arena wars vehicle in-game, it automatically has nitro enabled on it and it works fine on those vehicles. But when I spawn a non-arena wars vehicle the nitro doesn't work anymore.

It can be tested by spawning for example the "impaler4" which is an arena wars vehicle. then press X while driving it to activate the nitro.

Then spawn a regular non-arena wars vehicle, like "dukes" or smtn, call the setVehicleNitroEnabled native and set it to true, then try to press X. it might work once(it does randomly for me when adding it the first time), but the yellow bar at the bottom left does not deplete and after the first time, it can't be activated again.

Aside from that, I've been looking into the natives abit and it would seem that the setVehicleNitroEnabled native has gotten 4 extra parameters in the latest update:

`"0xC8E9B6B71B8E660D": {
			"name": "_SET_VEHICLE_NITRO_ENABLED",
			"jhash": "",
			"comment": "",
			"params": [
				{
					"type": "Vehicle",
					"name": "vehicle"
				},
				{
					"type": "BOOL",
					"name": "toggle"
				},
				{
					"type": "float",
					"name": "p2"
				},
				{
					"type": "float",
					"name": "p3"
				},
				{
					"type": "float",
					"name": "p4"
				},
				{
					"type": "BOOL",
					"name": "p5"
				}
			],
			"return_type": "void",
			"build": "1604"
		},`

I've messed around with those parameters abit, setting them to 0, 1 etc but it doesn't seem to have any effect(not sure if calling the native with extra parameters does anything via the ALTV methods though, idk if you guys filter it or whatsoever).

**Comment by FabianTerhorst** [comment]
The latest updates from the natives repo would need to be used to make the params usable. But that breaks existing code and will happen after merge.

**Comment by DasNiels** [comment]
Ah oke, I'll wait for that then.

`The latest updates from the natives repo would need to be used to make the params usable.`
Does that mean that even if I call the native with those extra parameters now, it won't have any effect?

**Comment by FabianTerhorst** [comment]
Yes i think it wont have a effect.

**Comment by DasNiels** [comment]
Oki, I'll leave it as is then and wait till the natives have been updated. thanks! :)

**Comment by DasNiels** [comment]
So, it's been a while and I've seen alot of interesting updates pass by on the discord which is truly amazing and I appreciate the hard work and effort :). Just kinda hoping this one doesn't end up being forgotten heheh, is there any ETA on this issue?

**Comment by C0kkie** [comment]
Will be handled here: https://github.com/altmp/altv-issues/issues/737
