### ISSUE TITLE
alt.Player.local.vehicle.speed is not work

### ISSUE THREAD

**Issue by inpex** [altmp/altv-issues#605]
**Client/server version**

`Build #1278, branch rc`

**Current behavior**

Vehicle speed is displayed as 0

**Expected behavior**

Vehicle speed should output the value of the speed

if (alt.Player.local.vehicle != null) {     
    alt.log("alt.Player.local.vehicle.speed: " + alt.Player.local.vehicle.speed)
}

**Comment by DasNiels** [comment]
Use the "getEntitySpeed" native. https://natives.altv.mp/#/0xD5037BA82E12416F

**Comment by Lhoerion** [comment]
Confirmed on build #1277

**Comment by DerKieler91** [comment]
> Use the "getEntitySpeed" native. https://natives.altv.mp/#/0xD5037BA82E12416F

Also minimap.showVehicleSpeed = `${(vehicle.speed * (isMetric ? 3.6 : 2.236936)).toFixed(0)}`;
Zu: minimap.getEntitySpeed = `${(vehicle.speed * (isMetric ? 3.6 : 2.236936)).toFixed(0)}`; 

???

**Comment by DasNiels** [comment]
> Confirmed on build #1277

Also on build 1278 RC branch

**Comment by martonp96** [comment]
Fixed in dev/1.0-dev13

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[1.0-dev13](https://discord.com/channels/371265202378899476/528297438348574741/756180743759200288)
