### ISSUE TITLE
Wrong entries in modules property of example server.cfg

### ISSUE THREAD

**Issue by riffy** [altmp/altv-issues#607]
**Client/server version**
`Build #1278, branch rc`

**Current behavior**

When downloading the following package:
| Data | Toggle |
| ------ | ------- |
| Type  | Linux  |
| Data Files  | X |
| JS Module  | X |
| C# Module  | X |
| Sample Config File  | X |
| Example Resource Pack  | X |

the server will not start, due to the server.cfg containing the following line:
`modules: [js-module csharp-module]`

**Expected behavior**
The server should start as sample config file is ticked.

**Steps to reproduce**
see _Current Behaviour_

**Context (environment)**
Provided example should work.
`./start.sh
[12:40:04] alt:V Server, build #1278, branch rc
[12:40:04] Starting alt:V Server on 0.0.0.0:7788
[12:40:04][Error] Failed to load module "js-module csharp-module", could not find (lib)js-module csharp-module.so
[12:40:04] Starting HTTP server on 0.0.0.0:7788
[12:40:04] Server started
`

**Possible solution**
As the array does not contain any limiters, it tries to load module "js-module csharp-module".
Implement limiter in server.cfg by replacing `modules: [js-module csharp-module]` with either:

`modules: [js-module, csharp-module]` or
`modules: [
    js-module
    csharp-module
]`

**Comment by Lhoerion** [comment]
It was fixed approx. week ago, so make sure you refresh the page correctly.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
