### ISSUE TITLE
alt.Player.local.rot.[x,y or z] returns 0

### ISSUE THREAD

**Issue by Erijl** [altmp/altv-issues#609]
**Client/server version**
`Build #1279, branch rc`

**Current behavior**
alt.Player.local.rot.[x,y or z] no matter what coord i choose it returns 0.

**Expected behavior**
alt.Player.local.rot.[x,y or z] should return the player rotation coord.

**Comment by C0kkie** [comment]
can confirm it

**Comment by LeonMrBonnie** [comment]
Confirmed on 2.1-dev32

**Comment by martonp96** [comment]
fixed
