### ISSUE TITLE
Sending uints/long to client results in "unsupported" datatype

### ISSUE THREAD

**Issue by Hardy535** [altmp/altv-issues#61]
When sending an uint or long _(maybe also other datatypes)_ from server _(tested only C# server but that shouldn't matter I guess)_ to the client, the client interprets it as "bigint", this leads to crashes with functions like "alt.loadModel" and basically all natives.

## Possible Solution
Convert uint/long to "number" on clientside if possible or support "bigint" for all alt:V functions and all natives.

## Steps to Reproduce
**When testing on clientside only**
```
var modelHash = 2912874939; // Ped model: s_m_o_busker_01
alt.log("Hash: " + modelHash + " | " + typeof (modelHash)); // Output: "Hash: 2912874939 | number"
alt.loadModel(modelHash); // Works as intended
```

**Sending uint/long model to clientside**
```
// SERVER
uint modelHash = 2912874939; // Using 'long' here results in the same behaviour
await player.EmitAsync("createped", modelHash);

// CLIENT
alt.onServer('createped', (modelHash) =>
{
	alt.log("Hash: " + modelHash + " | " + typeof (modelHash)); // Output: "2912874939 | bigint"
	alt.loadModel(modelHash); // Crashes the game
});
```

**Comment by 7Hazard** [comment]
Well you should either try it out with cpp-sdk on the server, or await confirmation from the maintainers of the C# API.

**Comment by FabianTerhorst** [comment]
I have written vadzz already that the signed integer mvalue gets converted to a bigint which is incompatible with the natives.

**Comment by Hardy535** [comment]
@vadzz-dev Any updates on this? Seems to still be a problem.

**Comment by FabianTerhorst** [comment]
can also be workaround by providing support for #55 to use msgpack, protobuf ect.

**Comment by DurtyFree** [comment]
Please fix, this had cost me hours of debugging

**Comment by Lhoerion** [comment]
I think it was fixed recently in C# module, so I'll mark it as fixed.
If it still doesn't work, please post an issue on appropriate issue tracker https://github.com/FabianTerhorst/coreclr-module/issues

**Comment by FabianTerhorst** [comment]
When bigint in general continue to lead to a client crash when calling a native with them feel free to a create a client related issue for that.
