### ISSUE TITLE
Peds/NPCs are not Working

### ISSUE THREAD

**Issue by DerKieler91** [altmp/altv-issues#611]
**Client/server version**

`Build #1280, branch release`

**Current behavior**

I updated the server to the new version, and the client too, and now I can no longer see the NPCs in the shops and garages. Thus they are unusable

**Expected behavior**

How can you fix it now? Is it the client or the server? Or were natives removed again? Then like new natives

**Steps to reproduce**

Unfortunately there is no error code or display in logs

**Possible solution**

The new update seems to be to blame, with the previous version everything still worked with: Build # 1278 rc branch

**Comment by Revyn112** [comment]
Can't confirm, Peds working here like before.

**Comment by LeonMrBonnie** [comment]
I also cannot confirm this. Peds are working for me just like before.

**Comment by DerKieler91** [comment]
> I also cannot confirm this. Peds are working for me just like before.



> Can't confirm, Peds working here like before.

Strange for me they all went with version build # 1279 and before the client update. Since yesterday 00 o'clock when I started AltV, the NPC no longer work.

**Comment by LeonMrBonnie** [comment]
Have you tried doing some debugging? E.g. log the events when the ped is getting created, and log the created ped script id (the createPed native returns the script id) and check that positions etc. are also correct. 
Make sure this is a problem with alt:V and not a problem with your script.

**Comment by DerKieler91** [comment]
> Have you tried doing some debugging? E.g. log the events when the ped is getting created, and log the created ped script id (the createPed native returns the script id) and check that positions etc. are also correct.
> Make sure this is a problem with alt:V and not a problem with your script.

So I have now looked, there are no messages for errors ect, it is only confirmed that these have been loaded ...

In the script I have the following for the NPC:

entSync.setGameEntityData(entId, entityTypes.PED, 'model', worldData.farming[i].pedModel);

**Comment by LeonMrBonnie** [comment]
> 
> 
> > Have you tried doing some debugging? E.g. log the events when the ped is getting created, and log the created ped script id (the createPed native returns the script id) and check that positions etc. are also correct.
> > Make sure this is a problem with alt:V and not a problem with your script.
> 
> So I have now looked, there are no messages for errors ect, it is only confirmed that these have been loaded ...
> 
> In the script I have the following for the NPC:
> 
> entSync.setGameEntityData(entId, entityTypes.PED, 'model', worldData.farming[i].pedModel);

That is not clientside. Look at your clientside code where the ped gets created using natives. Entity Sync itself doesn't create the entities.

**Comment by DerKieler91** [comment]
> > > Have you tried doing some debugging? E.g. log the events when the ped is getting created, and log the created ped script id (the createPed native returns the script id) and check that positions etc. are also correct.
> > > Make sure this is a problem with alt:V and not a problem with your script.
> > 
> > 
> > So I have now looked, there are no messages for errors ect, it is only confirmed that these have been loaded ...
> > In the script I have the following for the NPC:
> > entSync.setGameEntityData(entId, entityTypes.PED, 'model', worldData.farming[i].pedModel);
> 
> That is not clientside. Look at your clientside code where the ped gets created using natives. Entity Sync itself doesn't create the entities.

Okay this is in the clientside (client.mjs)

class PedStreamer {
    constructor() {
        this.peds = [];
    }

    addPed(entityId, model, entityType, pos, heading, collision = true) {
        this.removePed(entityId, entityType);
        this.clearPed(entityId, entityType);
        const hash$1 = hash(model);
        if (!hasModelLoaded(model)) {
            loadModel(hash$1);
        }
        let handle = createPed(
            1,
            hash$1,
            pos.x,
            pos.y,
            pos.z - 0.5,
            heading,
            false,
            false
        );
        let ped = {
            handle: handle,
            entityId: entityId,
            model: model,
            entityType: entityType,
            position: pos,
            heading: heading
        };
        this.peds.push(ped);
        taskSetBlockingOfNonTemporaryEvents(handle, 1);
        setBlockingOfNonTemporaryEvents(handle, 1);
        setPedFleeAttributes(handle, 0, 0);
        setPedCombatAttributes(handle, 17, 1);
        setEntityInvincible(handle, true);
        setPedCanBeTargetted(handle, false);
        freezeEntityPosition(handle, true);
        setEntityCollision(handle, collision, false);
        //game.setEntityCoords(handle, pos.x, pos.y, pos.z - 1, false, false, false, false);
    }

    getPed(entityId, entityType) {
        let ped = this.peds.find(p => p.entityId === entityId && p.entityType === entityType);

        if (!ped)
            return null;

        return ped;
    }

    restorePed(entityId, entityType) {
        let ped = this.getPed(entityId, entityType);
        if (ped === null)
            return;

        const hash$1 = hash(ped.model);
        if (!hasModelLoaded(ped.model)) {
            loadModel(hash$1);
        }
        ped.handle = createPed(1, hash$1, ped.position.x, ped.position.y, ped.position.z - 0.5, ped.heading, false, false);

        taskSetBlockingOfNonTemporaryEvents(ped.handle, 1);
        setBlockingOfNonTemporaryEvents(ped.handle, 1);
        setPedFleeAttributes(ped.handle, 0, 0);
        setPedCombatAttributes(ped.handle, 17, 1);
        setEntityInvincible(ped.handle, true);
        setPedCanBeTargetted(ped.handle, false);
        freezeEntityPosition(ped.handle, true);
        //game.setEntityCoords(ped.handle, ped.position.x, ped.position.y, ped.position.z - 1, false, false, false, false);
    }

    removePed(entityId, entityType) {
        let ped = this.getPed(entityId, entityType);
        if (ped === null)
            return;

        deletePed(ped.handle);

        ped.handle = null;
    }

    clearPed(entityId, entityType) {
        let idx = this.peds.findIndex(p => p.entityId === entityId && p.entityType === entityType);

        if (idx === -1)
            return;

        this.peds.splice(idx, 1);
    }
}

const pedStreamer = new PedStreamer();

on("resourceStop", () => {
    pedStreamer.peds.forEach((ped) => {
        pedStreamer.removePed(ped.entityId, ped.entityType);
        pedStreamer.clearPed(ped.entityId, ped.entityType);
    });
});

**Comment by LeonMrBonnie** [comment]
This is no scripting support. Please as I said try to debug your ped system and add logs to make sure that the problem is not caused by your script. If you need scripting support, please refer to the alt:V discord and ask there.

**Comment by DerKieler91** [comment]
> This is no scripting support. Please as I said try to debug your ped system and add logs to make sure that the problem is not caused by your script. If you need scripting support, please refer to the alt:V discord and ask there.

It can only be due to AltV, because I haven't changed anything and could still do everything yesterday evening and where I restarted the AltV Client, the update made and since then the NPCs are no longer visible.

**Comment by Lhoerion** [comment]
Unconfirmed on `build #1280, branch release`
Even if it worked somehow, it doesn't mean it was indeed valid usage of natives. Your code is incomplete thus we are unable to deduce what could be an source of the issue

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
