### ISSUE TITLE
2060: health is regenerating

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#613]
**Client/server version**
`Build #1280, branch release`

**Current behavior**
The health is regenerating to 50%

**Expected behavior**
Health shouldnt regenerate automatically, like it was befor the update

**Comment by lameule123** [comment]
I can confirm this new behaviour.

**Comment by tastydev** [comment]
can confirm, too

**Comment by Lhoerion** [comment]
Does it happen on `build #1285, branch rc`?

**Comment by C0kkie** [comment]
Looks fine for me

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[1285](https://discord.com/channels/371265202378899476/528297438348574741/744173325252821034)
