### ISSUE TITLE
Server crashes when the client is driving in a petrol station

### ISSUE THREAD

**Issue by Mr-Zero88** [altmp/altv-issues#616]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
When someone drives in a petrol station so that it explodes and then after a few seconds the server crashes.

**Expected behavior**
The server has to stat up and doesn't crash.

**Steps to reproduce**
Take a car.
Drive in a petrol station so that it explodes.
Wait a few seconds.
And then the server crashes.

**Comment by FabianTerhorst** [comment]
Make sure to update your nuget package to latest release build.
