### ISSUE TITLE
Ammo stacking after removing and giving weapon

### ISSUE THREAD

**Issue by VictorFerraresi** [altmp/altv-issues#617]
**Client/server version**
`Build #1279, branch rc`

**Current behavior**
Removing a weapon from a player with X ammoand giving it back with Y ammo causes ammo amount to be X + Y instead of only Y.

**Expected behavior**
The weapon should be given with the indicated ammo count, without adding up with the old amount from the previous one.

**Steps to reproduce**
C# Server
player.GiveWeapon(xpto, 100, true/false);
player.RemoveWeapon(xpto);
player.GiveWeapon(xpto, 100, true/false);
The ammo amount will be 200.

**Context (environment)**
I'm trying to have a command to equip and un-equip weapons on demand.

**Possible solution**
Call native to reset weapon ammo and remove old memory data that might be left.

**Comment by 7Hazard** [comment]
This is expected behavior. You give a player a weapon with the amount of ammo for that caliber (where the same ammo type goes for other weapons as well). The ammo that you gave previously will stay with the player unless you remove his ammo as well.
