### ISSUE TITLE
Native setVehicleFixed() not in sync with server side vehicle property isWheelBurst()

### ISSUE THREAD

**Issue by mexyn** [altmp/altv-issues#619]
**Client/server version**

`Build #1290, branch rc`

**Current behavior**

We have a car with burst wheels. When we call the native setVehicleFixed() (client side) and afterwards call isWheelBurst() (server side, with any wheel index) then isWheelBurst() returns still true for the damaged wheels.

**Expected behavior**

isWheelBurst() should return the proper burst status. In this case false, after the vehicle got fixed. 

**Steps to reproduce**

See here: https://streamable.com/j25mjb

**Context (environment)**

We use the isWheelBurst() function to save the tire status of a vehicle in our database. After a server restart we can set the burst status again, when this vehicle gets spawned again.

**Comment by C0kkie** [comment]
In my eyes such things shouldnt be synced if you set it clientside, cuz never trust the client, cuz it can be easy manipulated

**Comment by tastydev** [comment]
@C0kkie This native is the only way to repair deformation for vehicles when it got executed by netOwner and if this native breaks the serverside wheel getters (maybe more) its definetly a bug that happens serverside which needs to be fixed. Trying to catch or avoiding cheaters by disallowing the only way to restore vehicle deformation does not stand in any relation, Sorry.

**Comment by gamelaster** [comment]
> Trying to catch or avoiding cheaters by disallowing the only way to restore vehicle deformation does not stand in any relation, Sorry

This is true. I think that server-side itself should be able to restore the vehicle deformation, and this should be only way.

**Comment by LeonMrBonnie** [comment]
Fixed in dev/1.2-dev61.
