### ISSUE TITLE
Custom Request Headers in CEF

### ISSUE THREAD

**Issue by davis-thereal** [altmp/altv-issues#620]
**Suggestion**
possibility to add custom headers for a request / each request in a webview

**Use cases**
authentication for multiple external webpages

**Describe the solution you'd like**
something like `webView.addHeader("header", "value")`
or a event like 
```
webView.onWebRequest((request) => { 
    request.headers["key"] = "value";
});
```

**Additional context**
in cef you can use OnBeforeResourceLoad and add custom headers to the request.

**Comment by FabianTerhorst** [comment]
webView.setExtraHeader("key", "value") is available in next release.
