### ISSUE TITLE
WebView gets hidden if Steam/Rockstar overlay is open

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#622]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
If you open the steamoverlay or rockstaroverlay all altv cef windows gets hidden.
https://streamable.com/xstx0a
https://prnt.sc/u1x2m0

**Expected behavior**
That the cef windows dont get hidden.

**Steps to reproduce**
Just open steamoverlay/rockstar overlay, and you will see that every cef gets hidden. Also the altv text at the bottom

**Comment by 7Hazard** [comment]
Im saying CEF windows are hidden intentionally when you open Social Club's ingame "Home" meny for example

**Comment by C0kkie** [comment]
Possible to disable that and hide them? @7Hazard

**Comment by FabianTerhorst** [comment]
@C0kkie you tried setting your webviews as overlay?

**Comment by FabianTerhorst** [comment]
Not hiding them would be bad ux since they can't use the socialclub anymore.

**Comment by C0kkie** [comment]
Not yet, will do today

**Comment by C0kkie** [comment]
Nop not working as overlay

**Comment by FabianTerhorst** [comment]
When you need to hide players do a black screen and a camera move to a different location.

**Comment by martonp96** [comment]
I don't see any problems with it. The game handles the rendering of the layers and prioritizes steam/r* overlay.
