### ISSUE TITLE
setEntityVisible  & setPlayerModel synced

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#623]
**Client/server version**

`Build #1286, branch release`

**Current behavior**
Both natives are synced if they are set.

**Expected behavior**
That it is only synced, if it got set serverside

**Comment by bozoweed** [comment]
personaly , i'm gona build my own anticheat , but thanks you to work on some feature for secured our server you are anwsome <3

**Comment by martonp96** [comment]
added in dev56
