### ISSUE TITLE
OnPlayerDead and OnPlayerDamage not triggered by DamageByWorld

### ISSUE THREAD

**Issue by Heady20006** [altmp/altv-issues#624]
**Client/server version**
`Build #1293, branch rc`

**Current behavior**
If i´m jumping of a roof i am dieing but the OnPlayerDamage neither the OnPlayerDead event is triggered.

**Expected behavior**
OnPlayerDamage and/or OnPlayerDead should be triggered if you are dieing by WorldDamage.

**Steps to reproduce**
Just jump of a roof, high enough to die.

**Context (environment)**
I want to trigger death-event if the player is dead.

**Possible solution**
no solution

**Comment by LeonMrBonnie** [comment]
This seems to be fixed now on 4.0-dev3, so I am closing this issue.

**Comment by VnX-SolidSnake** [comment]
What the... of course its get triggered... 
Did you putted your Event ( if you are a C# user ) into a : IScript Class ? .. 
Otherwise.. if you are JS user.. did you even imported/required your JS file ? 

These event's worked all the time by world damage...
