### ISSUE TITLE
Automatically generate server config if none

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#625]
**Suggestion**
Automatically generate `server.cfg` if it does not exist.

**Use cases**
Just prevents people from missing this step.

**Describe the solution you'd like**
Generate a .cfg for the server automatically.

**Comment by LeonMrBonnie** [comment]
Shouldn't the `Sample config file` on the official download page be enough?

**Comment by Stuyk** [comment]
> 
> 
> Shouldn't the `Sample config file` on the official download page be enough?

Let's say you have never scripted before. 
You download partial bits of the server framework. 
You don't download the server.cfg. 
Your server doesn't run because you missed this one file that could be generated automatically.

**Comment by LeonMrBonnie** [comment]
IMO downloading a `Sample config file` when it is offered, is common sense.
But it really depends on how much work it would be to implement this, maybe it does make sense.

**Comment by gamelaster** [comment]
It's very easy to implement this.

**Comment by Lhoerion** [comment]
I'm in favour of this, the more straightforward server configuration the better
Not to mention that many similar gameserver binaries takes care after that already

**Comment by LeonMrBonnie** [comment]
If it's easy to implement, then I am also in favor of this.

**Comment by LeonMrBonnie** [comment]
Added in next dev
