### ISSUE TITLE
Change "modules" in default server.cfg

### ISSUE THREAD

**Issue by DatMayo** [altmp/altv-issues#626]
** Where to find **
https://cdn.altv.mp/others/server.cfg

** Whats the issue **
There was a breaking change, `node-module` was renamed to `js-module`. So when you download the sample config, you'll get an error right away.

** How to fix **
Remove node-mode in default server.cfg

**Comment by Lhoerion** [comment]
@DatMayo When downloading server binaries from page, `server.cfg` is modified already to include added modules.
Do you download it by external scripts?

**Comment by FabianTerhorst** [comment]
Module array in cfg from cdn should be empty by default @vadzz-dev

**Comment by DatMayo** [comment]
@Lhoerion When downloading i.E. for a docker image, you'll need to stick to cdn versions. Thats why I opend this issue

**Comment by Software-Noob** [comment]
Any news related to this? Seems like an extremely easy fix to update the file on the CDN to reflect the latest changes regarding not using node-module.

**Comment by FabianTerhorst** [comment]
i think server.cfg could just be removed from cdn. The websites builds it dynamically anyway.

**Comment by Software-Noob** [comment]
> i think server.cfg could just be removed from cdn. The websites builds it dynamically anyway.

This is not for downloading and building from the website, CDN is used for docker image builds. The CDN file has not been updated since last year, so it's out of date.

**Comment by C0kkie** [comment]
Got fixed and updated to js-module
