### ISSUE TITLE
Add console.log method

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#629]
**Suggestion**
Replace `console.log` so it has the same functionality of `alt.log` to stop confusing developers on client-side.

**Use cases**
Clearing up confusion between `console.log` and `alt.log`.

**Describe the solution you'd like**
Literally just override `console.log` and make it behave similar to `alt.log` for client-side.

**Comment by 7Hazard** [comment]
Are they similar in the sense of having the same args and behavior when using?

**Comment by Lhoerion** [comment]
Hmm, good point, afaik our method don't serialize objects by default

**Comment by tastydev** [comment]
Would also like to see alt.log printing to stdout (on serverside) because currently it doesn´t. Which makes it hard to log information without using console.log while managing the server process with tools like pm2 (process forks are only listening to standard streams)

**Comment by Lhoerion** [comment]
@tastydev https://github.com/altmp/altv-issues/issues/544

**Comment by Lhoerion** [comment]
I'm for adding this function alias, but before that would happen we'd need to rework alt:V function in conform of
https://console.spec.whatwg.org/#logger

**Comment by Lhoerion** [comment]
Issue needs to be reported on appropriate issue tracker [https://github.com/altmp/altv-js-module/issues]()

**Comment by FabianTerhorst** [comment]
altv-js-module is not the correct repository. Open a issue or pull request on https://github.com/altmp/altv-client-js

**Comment by Lhoerion** [comment]
It was correct, that one you added is still W.I.P.
Nevertheless changed it in my previous message too
