### ISSUE TITLE
Resource OnStop not called on SIGTERM

### ISSUE THREAD

**Issue by StiviiK** [altmp/altv-issues#630]
**Client/server version**
`build #1286, branch release`

**Current behavior**
SIGTERM does not trigger the resource OnStop handler.

**Expected behavior**
SIGTERM should also trigger the resource OnStop handler.

**Comment by 7Hazard** [comment]
Theres a deadlock bug that occurs, will be resolved.

**Comment by StiviiK** [comment]
It happens both on Windows and Linux.

**Comment by FabianTerhorst** [comment]
This isnt a altv bug, it works great with c++ module. Its related to c# and js module. Open the issues there.
