### ISSUE TITLE
Don't create a scrthread for none coding clientside resources

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-issues#632]
**Client/server version**
`Build #1293, branch rc`

**Current behavior**
A scrthread is created for each resource. This will fill the script thread pool and crash the client when having many none coding related resources.

**Expected behavior**
Only create a script thread for resources that actually can execute code.
**Steps to reproduce**
Create a dlc resource and a script thread is created.

**Comment by 7Hazard** [comment]
Fixed in dev
