### ISSUE TITLE
Add some ped customization getters

### ISSUE THREAD

**Issue by jayr33n** [altmp/altv-issues#633]
**Suggestion**

Add missing ped customization natives
https://runtime.fivem.net/doc/natives/?_0xC46EE605
https://runtime.fivem.net/doc/natives/?_0xA47B860F
https://runtime.fivem.net/doc/natives/?_0xA3EA2893
https://runtime.fivem.net/doc/natives/?_0xBA352ADD
https://runtime.fivem.net/doc/natives/?_0x4B087305

**Comment by FabianTerhorst** [comment]
I don't see a reason for the need of the getters, but they probably can be added some day.

**Comment by bozoweed** [comment]
personnaly i have never used them , but why not

**Comment by r3sist3nt** [comment]
You dont need to use the getter.
Just build your own data structure with the desired appearance. When you change a bit, just reset and reapply everything. This is also way more flexible then relying on the natives.
