### ISSUE TITLE
Invalid component variation cause sync anomalies

### ISSUE THREAD

**Issue by bozoweed** [altmp/altv-issues#634]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
when we set some invalide component variation on player ped that remove the variation from my player, but other player steal seen the old variation

**Expected behavior**
should remove the variation for ohter player too not only in my screen

**Steps to reproduce**
put a component variation in a player (like shirt , undershirt ,etc ) then removed it by using componentId -1 , so other player steal seen older Variation one

**Context (environment)**
that totaly bug my player and it's not funny in my rp server 

**Possible solution**
put back the code before 2060 update , is working great befor this update 

(not asked but thanks you for your work and for the support <3)

**Comment by martonp96** [comment]
This issue was tested and i think the game just does not sync the invalid id, instead it uses some default one. I don't see any problems with it, don't use invalid IDs.
