### ISSUE TITLE
Add action buttons to disconnection modal

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#637]
![](https://i.imgur.com/qbYKvDO.png)

**Suggestion**
Currently the above message appears when a player is disconnected from their server. They have no idea what they need to do to close it and the information from a UX standpoint is not helpful. I suggest we add a button that shuts down the game as well as a `reconnect` button if the client has `debug` on.

**Use cases**
Understanding the client better.

**Describe the solution you'd like**
Either quit the game or reconnect to the server if debug is on. However, a `restart game` option would be even better.

![](https://i.imgur.com/WNgATTz.png)

**Comment by ZackaryH8** [comment]
Saves me pressing F8, would be a nice feature

**Comment by holyschytt** [comment]
I agree.

**Comment by Serrulien** [comment]
Would be even better if user can go back to the server list without restarting the game

**Comment by Stuyk** [comment]
> Would be even better if user can go back to the server list without restarting the game

Currently there is no proper way across any GTA:V client that allows the proper cleaning of GTA:V's memory and state. Thus resulting in more crashes when hopping between servers if we allow this.

**Comment by FDiskas** [comment]
I cant believe that there is no solution for this one. So if server is restarting all player should restart the GTA also?

**Comment by BaixoGamer** [comment]
> > Would be even better if user can go back to the server list without restarting the game
> 
> Currently there is no proper way across any GTA:V client that allows the proper cleaning of GTA:V's memory and state. Thus resulting in more crashes when hopping between servers if we allow this.

So the team has to start finding a way to do that, because the other platforms allow it.
It would be nice to set this option in alt:v, as it is kind of annoying, whenever I want to do a small test of changes on my server, I have to restart gta.

**Comment by Stuyk** [comment]
> > > Would be even better if user can go back to the server list without restarting the game
> > 
> > 
> > Currently there is no proper way across any GTA:V client that allows the proper cleaning of GTA:V's memory and state. Thus resulting in more crashes when hopping between servers if we allow this.
> 
> So the team has to start finding a way to do that, because the other platforms allow it.
> It would be nice to set this option in alt:v, as it is kind of annoying, whenever I want to do a small test of changes on my server, I have to restart gta.

Use debug mode and use reconnect.

**Comment by ZackaryH8** [comment]
> should we enable debug mode and teach our players how to reconnect in production server also?

If you want a server which is desynced, with traffic lights falling over everywhere? Go for it. If not then then that's probably not the best idea

**Comment by FDiskas** [comment]
As solution - After launching a client - display server browser first and only after user clicks on a server and only after handshaking start download assets and launch a game. This way it will be mo user friendly

**Comment by C0kkie** [comment]
#1259 #1258
