### ISSUE TITLE
Rolling & shooting are not synced

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#638]
**Client/server version**
Build #1286

**Current behavior**
Shooter:
https://drive.google.com/file/d/1_1-xnoTEcm4FQnP2Ou7ym6sWnenO1PQi/view

Other Pedestrian:
https://drive.google.com/file/d/1y2L4RJlRp254O0U1AC0GiYTwWEtLCzQt/view

**Expected behavior**
Shooting is synchronized completely. Rolling is synchronized completely.

**Steps to reproduce**
Shoot. Roll around.

**Comment by tastydev** [comment]
Does it happen in rc, too? Cause i tux pushed an shooting/hiding sync update there

**Comment by FabianTerhorst** [comment]
Maybe test on dev the rolling yes. For shooting there might be a possibility to add a server.cfg setting if it should be fully synced or not.

**Comment by Benni9323** [comment]
Can confirm this. Have a look to this Video: https://youtu.be/t3605IV9_MI

**Comment by 7Hazard** [comment]
Could not reproduce. Either this happens in a very specific case or it's fixed.

**Comment by Shino58** [comment]
The native setPlayerVisibleLocally can block that sync .

**Comment by C0kkie** [comment]
There should be already a issue that it will be only possible serverside for security
