### ISSUE TITLE
OnColShapeHit event won't get called everytime for some colshapes.

### ISSUE THREAD

**Issue by VnX-SolidSnake** [altmp/altv-issues#640]
**Client/server version**

`Build #1286, branch Release`

**Current behavior**
- Player A is walking to the ,,Police Duty ColShape"
- Player A's Window isn't showing...
- Player A is walking to a other ColShape ... then he go back and it works 👍 .

Preview of the Code : 
https://cdn.discordapp.com/attachments/672801216505315356/749254025957867541/unknown.png
Preview of the Marker : 
https://cdn.discordapp.com/attachments/672801216505315356/749256479185305680/Replay_2020.08.29-15.17.mp4
How it works if you go into a other ColShape : 
https://cdn.discordapp.com/attachments/672801216505315356/749256608449691801/Replay_2020.08.29-15.18.mp4

it doesn't matter which colshape you enter... if you enter some random colshape.. you will be able to see the PD Duty Point..
the thing is.. for other players ( who spawn like the other side of the map ) .. they have this issue with gas stations and other colshapes.. 
( Event will not be called ... event only got called when i was going to a other colshape in and then back ( like in the video ) )
https://cdn.discordapp.com/attachments/672801216505315356/749256713802088488/unknown.png

**Expected behavior**
All ColShapes should work... doesn't matter if you go inside one or not 😄 

**Steps to reproduce**
Step 1 : Write a Gamemode
Step 2 : After like 40 ColShapes you will see that.

**Context (environment)**
This issue is for some Players and is not produced by our Code for 100%.
The Event ,,OnColShapeHit" Like in my Code Preview... will not be called for some how for some ColShapes.
I talked with heron and we tried already to put the ColShapes into ,, Dimension.GlobalDimension ".
Still same issue.

**Possible solution**
Idk.. maybe let the player enter a colshape and leave it after connect idk ( would be a unperformant fix maybe )

**Comment by lameule123** [comment]
I can confirm this annoying bug.

**Comment by martonp96** [comment]
Fixed in 2.2-dev7
