### ISSUE TITLE
Add subfolder feature for scripts

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#641]
**Suggestion**
Add subfolder feature for scripts.

**Use cases**
To further organize, developers can categorize their scripts with help of subfolders.

**Additional context**
To use subfolder property, developer can use the **[ ]** symbol for the main folder and specify how many scripts are in this folder.

**Example**
```js
resources/
└── [group-a]/
    └── script-a/
        ├── client.mjs
        ├── index.mjs
        └── resource.cfg
    └── script-b/
        ├── client.mjs
        ├── index.mjs
        └── resource.cfg
└── [group-b]/
    └── script-c/
        ├── client.mjs
        ├── index.mjs
        └── resource.cfg
    └── script-d/
        ├── client.mjs
        ├── index.mjs
        └── resource.cfg
```

**Comment by Lhoerion** [comment]
There's already other feature that works similarly, but it requires using launch argument
Check https://wiki.altv.mp/Command-line_Args#Server_launch_options table `--extra-res-folder`

**Comment by mrgharabaghi** [comment]
This `--extra-res-folder` is good, but I think the suggestion I made is cleaner and does not require additional **Key** for developers like this: `./altv-server --extra-res-folder firstDir --extra-res-folder secondDir`

**Comment by FabianTerhorst** [comment]
I would prefer something like this
server.cfg
```yaml
resources: 
[
myresource
myfolder1/myresource2
myfolder1/myresource3
myfolder2/myreosurce4
myfolder3/myfolder4/myfolder5/myresource5
]
```

**Comment by mrgharabaghi** [comment]
I used your suggestion but it doesn't work in alt:V Linux version.
Error: `terminate called after throwing an instance of 'std::runtime_error'
  what():  File cannot be created`
```js
resources: [
	folder-test/my-resource
]
```
@FabianTerhorst

**Comment by FabianTerhorst** [comment]
Thats why i wrote it here as a Feature request.

**Comment by Lhoerion** [comment]
Wouldn't it be nice that category/container needs to have some distinguishable elements in folder name?

**Comment by OvileAmriam** [comment]
**━━━━━━━━━━━━━━━━━━━━━**
**Multi Resource/Categorization Support for alt:V**
**Author: OvileAmriam**
**━━━━━━━━━━━━━━━━━━━━━**
***Are you coming from platform where resources are often grouped/categorized?***
***Are you having trouble to cope up with altV's resource structure?***
***Want to tidy up the resource directory with neat categorization? instead of using `./altv-server --extra-res-folder firstDir --extra-res-folder secondDir`***
:point_down: :point_down: :point_down: 
***Setup your server using this quick multi resource boilerplate and get things automated!***
https://github.com/OvileAmriam/ALTV-Multi_Resource

**Comment by OvileAmriam** [comment]
@mrgharabaghi @FabianTerhorst Created quick resource to stimulate multi resource system; should be helpful :point_up_2: :point_up_2: :point_up_2:

**Comment by mrgharabaghi** [comment]
It's a good idea, but what about Linux (Shell)?
@OvileAmriam 
```bat
set launcherCommand=altv-server.exe
for /F "delims=" %%a in ('dir "./resources" /b /a:d ^| findstr "[^[$]]"') do (
    set "launcherCommand=!launcherCommand! --extra-res-folder resources/%%a"
)
%launcherCommand%
```

**Comment by OvileAmriam** [comment]
@mrgharabaghi  _i'll add categorize the resource into windows/linux version ASAP_ 🗡️

**Comment by OvileAmriam** [comment]
@mrgharabaghi Updated now it'll support for windows/linux both.

**Comment by OvileAmriam** [comment]
If you want pure .sh script i'll try to convert it tomorrow!

**Comment by OvileAmriam** [comment]
@mrgharabaghi Uploaded the linux script too 🚀

**Comment by mrgharabaghi** [comment]
It works well for me, perfect.
@OvileAmriam 
```sh
export launcherCommand=./altv-server
for a in resources/\[*\]
do
    export "launcherCommand=$launcherCommand --extra-res-folder $a"
done
$launcherCommand
```

**Comment by OvileAmriam** [comment]
@mrgharabaghi Cheers :)

**Comment by OvileAmriam** [comment]
@mrgharabaghi https://github.com/OvileAmriam/altV-Manager Updated package with more automization and improvement better than last time. Should be final version 👍 Feel free to open PR if you face any issue.

**Comment by mrgharabaghi** [comment]
Special thanks to @OvileAmriam

Linux - `start.sh`
```sh
export launcherCommand=./altv-server
for a in resources/\[*\]
do
    export "launcherCommand=$launcherCommand --extra-res-folder $a"
done
$launcherCommand
```
Windows - `start.bat`
```bat
setlocal EnableDelayedExpansion
set launcherCommand=altv-server.exe
for /F "delims=" %%a in ('dir "./resources" /b /a:d ^| findstr "[^[$]]"') do (
    set "launcherCommand=!launcherCommand! --extra-res-folder resources/%%a"
)
%launcherCommand%
```

**Comment by LeonMrBonnie** [comment]
This is available in the next version, in the way that Heron suggested.

**Comment by C0kkie** [comment]
Currently it crashes the server, crashdump: https://discord.com/channels/371265202378899476/744981304222679191/961751653764198420
