### ISSUE TITLE
Native loadCloudHat not working properly

### ISSUE THREAD

**Issue by jayr33n** [altmp/altv-issues#642]
**Client/server version**

`Build #1286, branch release`

**Current behavior**

https://natives.altv.mp/#/0xFC4842A34657BFCB
Invoking this native with the correct parameters (found [here](https://runtime.fivem.net/doc/natives/?_0xFC4842A34657BFCB)) always throws `native call failed exception`

**Expected behavior**

the native correctly sets the cloudhat

**Comment by zziger** [comment]
Clouds blink a bit while using loadCloudHat, but both this native and unloadCloudHat always throw `Native call failed`, and the clouds don't get applied

**Comment by martonp96** [comment]
fixed in dev602
