### ISSUE TITLE
Can't open parachute

### ISSUE THREAD

**Issue by KadirFiratFTW** [altmp/altv-issues#643]
**Client/server version**
`Build #1286, branch release`

**Current behavior**

When i give a parachute to player with "player.giveWeapon(...)" player can not open parachute with mouse left click.

**Expected behavior**

Parachut needs to be deployed.

**Context (environment)**

I'm trying to create a battleroyale gamemode for alt:V community. Players are needs to be deployed from air with parachutes. This gamemode will be unsuccesfully if players can not open their parachutes.

**Comment by FabianTerhorst** [comment]
Parachute isn't synced. Thats a known issue. But will keep this open since no one did a issue for that before.

**Comment by lameule123** [comment]
After a little bit of research and discussion within the discord it appears that the native itself does not work. Nothing happens when it is executed

https://natives.altv.mp/#/0xD2F1C53C97EE81AB

**Comment by zziger** [comment]
Parachute actually opens right now (use giveWeapon from server, jump from e.g. building and then right click), but it is not synced, so other players just see you falling :c

**Comment by xtance** [comment]
IDK, I still can't open a parachute
That was given via `player.giveWeapon(0xFBAB5776, 1, true);`

**Comment by C0kkie** [comment]
Parachute opens and is synced in v15
