### ISSUE TITLE
Fix UI flickering by default

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#644]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
In Default the UI is flickering, Without native.drawRect(0, 0, 0, 0, 0, 0, 0, 0);

**Expected behavior**
That it doesnt flickering as default and not that everybody needs to fix it.
I mean its not hard to fix it, but if you just search in the altv discord, many users asked that in the past. And i guess/hope it shouldnt be much work for you

**Comment by Lhoerion** [comment]
Well why not

**Comment by C0kkie** [comment]
Fixed in dev/0.4-dev6

**Comment by xxshady** [comment]
@C0kkie can it be reopened?

**Comment by C0kkie** [comment]
We cant repro it anymore, should work without it in rc/11.0-rc21

**Comment by C0kkie** [comment]
Will be fixed in dev/15.0-dev50
