### ISSUE TITLE
Server resource loading abort button

### ISSUE THREAD

**Issue by localcc** [altmp/altv-issues#645]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
When aborting resource loading when connecting to server nothing happens and resources continue to load

**Expected behavior**
When aborting resource loading when connecting to server resource loading should stop and close the modal

**Steps to reproduce**
1. Start connecting to a server
2. Wait for it to start downloading resources
3. Press abort button, nothing happens

**Context (environment)**
Cannot abort connecting to server

**Possible solution**
Abort button click is not handled correctly or at all

**Extras**
When pressing esc instead of abort it stops resource loading and closes modal

**Comment by FabianTerhorst** [comment]
Fixed in next release.
