### ISSUE TITLE
Disconnection modal displayed twice after reconnect

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#648]
**Client/server version**
`Build #1286, branch release`

**Current behavior**
If you use the reconnect function multiple times you will see the disconnect reason overlay twice.

https://i.imgur.com/0fWW6Pu.jpg

**Expected behavior**
Only 1 disconnect overlay is visible

**Steps to reproduce**
Start Server -> connect.
Stop Server -> you get the first disconnect overlay
Start Server -> connect
Stop Server -> you get the second disconnect overlay

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[2.1-dev26](https://discord.com/channels/371265202378899476/528297438348574741/778610565509283841)

**Comment by C0kkie** [comment]
Will be fixed in dev/14.0-dev13
