### ISSUE TITLE
Vehicle sentinel2 seats not synchronized

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#649]
**Client/server version**

`Build #1286, branch release`

**Current behavior**
If you get the Seat count with getVehicleMaxNumberOfPassengers it returns 3. And if you port the player into the 3th seat, something like that will happen: https://cdn.discordapp.com/attachments/695045870231617589/695051416926027816/video0.mov

**Expected behavior**
Sync it correctly or return correct seat amount

**Steps to reproduce**
Spawn sentinel2, go into the vehicle and execute this

let vehicle = alt.Player.local.vehicle;
                let vehicleSeats = native.getVehicleMaxNumberOfPassengers(vehicle.scriptID) + 1;
                alt.log("vehicleSeats: " + vehicleSeats)
                alt.log("PassengerSeats: " + native.getVehicleMaxNumberOfPassengers(vehicle.scriptID));
`

you will see it will return 3 passanger seats and you you put the player then into the 3th passanger seat, yea you see it in the video

**Comment by martonp96** [comment]
passenger seats are starting from 0, the driver seat is -1... so if you want to put the player in the third seat, use the number 2

**Comment by C0kkie** [comment]
Yea i know, and if you use 2 he is on the correct seat. But while driving it looks like the in the video for others.

**Comment by C0kkie** [comment]
maybe i explained it wrong first

**Comment by martonp96** [comment]
you said you use the third seat

**Comment by martonp96** [comment]
post the code you use please

**Comment by C0kkie** [comment]
const localPlayer = alt.Player.local;
function getnearestVehicle(distance = 4, pos = localPlayer.pos) {
    let inRange = [];

    alt.Vehicle.forEachStreamed((v, i, a) => {
        v.cDistance = v.distance(pos);

        if (v.cDistance < distance) inRange.push(v);

        if (i == a.length - 1) {
            if (inRange.length > 0) inRange.sort((a, b) => a.cDistance - b.cDistance);
        }
    });

    if (inRange.length > 0) {
        return inRange[0];
    } else return null;

let nearestVehicle = getnearestVehicle();
native.taskEnterVehicle(alt.scriptID, nearestVehicle.scriptID, 5000, 2, 2, 1, 0);

For yourself its fine, for others it looks buggy

**Comment by C0kkie** [comment]
And we noticed this only for this 1 vehicle. Every other is fine

**Comment by Lhoerion** [comment]
The target seats would be 1 & 2, it's not possible to enter them without teleporting, they don't have scripted entrances.
So they could be just leftovers or are indeed bugged.

**Comment by Lhoerion** [comment]
For reference, as you can see below there's no entry points defined for rear seats, so they're not meant to be used (but honestly I think it's just a leftover)
```xml
<Item type="CVehicleLayoutInfo">
  <Name>LAYOUT_LOW_SENTINEL2</Name>
  <Seats>
    <Item>
      <SeatInfo ref="SEAT_LOW_FRONT_LEFT" />
      <SeatAnimInfo ref="SEAT_ANIM_LOW_FRONT_LEFT" />
    </Item>
    <Item>
      <SeatInfo ref="SEAT_LOW_FRONT_RIGHT" />
      <SeatAnimInfo ref="SEAT_ANIM_LOW_FRONT_RIGHT" />
    </Item>
    <Item>
      <SeatInfo ref="SEAT_LOW_REAR_LEFT" />
      <SeatAnimInfo ref="SEAT_ANIM_STANDARD_REAR_LEFT" />
    </Item>
    <Item>
      <SeatInfo ref="SEAT_LOW_REAR_RIGHT" />
      <SeatAnimInfo ref="SEAT_ANIM_STANDARD_REAR_RIGHT" />
    </Item>
  </Seats>
  <EntryPoints>
    <Item>
      <EntryPointInfo ref="ENTRY_POINT_LOW_FRONT_LEFT" />
      <EntryPointAnimInfo ref="ENTRY_POINT_ANIM_LOW_FRONT_LEFT" />
    </Item>
    <Item>
      <EntryPointInfo ref="ENTRY_POINT_LOW_FRONT_RIGHT" />
      <EntryPointAnimInfo ref="ENTRY_POINT_ANIM_LOW_FRONT_RIGHT" />
    </Item>
  </EntryPoints>
  <LayoutFlags>StreamAnims UseDoorOscillation UseLeanSteerAnims UseSteeringWheelIk</LayoutFlags>
  <BicycleInfo ref="NULL" />
  <AnimRateSet ref="STD_LOW_ANIM_RATE_SET" />
  <HandsUpClipSetId>busted_vehicle_low</HandsUpClipSetId>
  <SteeringWheelOffset x="0.000000" y="0.350000" z="0.320000" />
  <MaxXAcceleration value="15.00000" />
  <BodyLeanXApproachSpeed value="10.00000" />
  <BodyLeanXSmallDelta value="0.40000" />
  <LookBackApproachSpeedScale value="0.5" />
  <FirstPersonAdditiveIdleClipSets>
    <Item>clipset@veh@low@ds@idle_a</Item>
    <Item>clipset@veh@low@ds@idle_b</Item>
    <Item>clipset@veh@low@ds@idle_c</Item>
    <Item>clipset@veh@low@ds@idle_d</Item>
    <Item>clipset@veh@low@ds@idle_e</Item>
  </FirstPersonAdditiveIdleClipSets>
  <FirstPersonRoadRageClipSets>
    <Item>clipset@veh@low@ds@hit_wheel@idle_a</Item>
    <Item>clipset@veh@low@ds@hit_wheel@idle_b</Item>
    <Item>clipset@veh@low@ds@hit_wheel@idle_c</Item>
  </FirstPersonRoadRageClipSets>
</Item>
```

**Comment by Lhoerion** [comment]
I researched further and indeed in GTA5 scripts I found final confirmation for the fact that last seats shouldn't be used
