### ISSUE TITLE
Outdated js-module on CDN for almost a week.

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#650]
**Client/server version**
1.0-dev16

**Current behavior**
It's v40

**Expected behavior**
It's v41

**Steps to reproduce**
https://cdn.altv.mp/js-module/dev/x64_linux/modules/js-module/

**Context (environment)**
Can't use dev branch since last update.
```
[01:46:27][Error] Failed to load module "/mnt/d/Projekty/oesis-altv/build/linux/modules/js-module/libjs-module.so"
         Module uses incompatible SDK version(v40) while v41 is required
```

**Possible solution**
Upload files to CDN

**Comment by 7Hazard** [comment]
This is an issue of the JS module, please make an issue on their repo: https://github.com/altmp/altv-js-module/issues
