### ISSUE TITLE
Increase modding features / make gameconfig streamable / raise pool size limit

### ISSUE THREAD

**Issue by anthonyisthere** [altmp/altv-issues#651]
**Suggestion**
Increase the modding features for server owners on Alt V as right now, it is very limited on this platform. I own a ~400 players community myself that relies on a huge map dlcpack and our move to Alt V is not possible due to these limitations. 

**Use cases**
Import a ~6.5GB map into the game and eventually car packs, custom interiors etc. I'm sure other server owners would love to see this happen as well and would bring a lot of new players to alt:V.

**Describe the solution you'd like**
Increase pool size limit, allow custom gameconfig.

**Describe alternatives you've considered**
N/A

**Additional context**
If any alt:V representative would like to contact me, I'm available on discord at oRe#4300. My DMs are open and I'd love to talk to someone from the team directly.

**Comment by KovacsBotond** [comment]
It would be very good to solve this.

**Comment by Mempler** [comment]
Couldn't you just simply put that huge Map DLC Pack into multiple DLCs? E.G `MapPack_0` `MapPack_1`. That is the simplest way, i guess...

**Comment by AlteredCarbonate** [comment]
> Couldn't you just simply put that huge Map DLC Pack into multiple DLCs? E.G `MapPack_0` `MapPack_1`. That is the simplest way, i guess...

I agree.
Limits are there for a reason.
To either prevent issues or similar.

Enhancements e.g streaming of config files are a big yes from me

**Comment by lameule123** [comment]
@anthonyisthere are not talking about file size limit in DLC_Ressources. He is talking about general gameconfig.xml wich is modifiable in rageMP.

U actually can't load big map like Liberty City or Vice City without any issues

**Comment by xForcer** [comment]
I am currently using a slightly modified gameconfig.xml on the other platform and I have no problems nor anybody else who tested it. I agree the limits are there for a reason, but please give us the option. It's up to us how we use it

**Comment by 7Hazard** [comment]
It requires that the gameconfig pools are setup in the start of GTAV, so therefore it is not straight forward to be able to stream completely custom pool sizes.

**Comment by xForcer** [comment]
> It requires that the gameconfig pools are setup in the start of GTAV, so therefore it is not straight forward to be able to stream completely custom pool sizes.

How is RageMP handling it in this case?

**Comment by FabianTerhorst** [comment]
it restarts the game.

**Comment by xForcer** [comment]
> it restarts the game.

Ahh sorry, I now understand what's the issue here. RageMp gives you the server list and ability to download client files before you even start the game. Here on Alt:V you first enter the game and then choose a server...

**Comment by KubasGC** [comment]
How's the situation with this issue? I know that rebuilding this may be very difficult to do at this moment, but external launcher for downloading assets and loading custom gameconfig with game starting is in my opinion much more usable scenario. And giving server owners much more flexibility with game modding.

**Comment by C0kkie** [comment]
Should be possible in upcoming dev with a empty ressource and as resource.toml for example

```
type = "rpf"

[pools]
"DrawableStore" = 240420
```
