### ISSUE TITLE
Player health and armour getter

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#654]
**Suggestion**
I'd like the ability to access player health and armour on client side to avoid using emits or natives

**Use cases**
You could use this for getting the players current health or armour then run natives based on it's value

**Describe the solution you'd like**
Client side Read Only getter
`
alt.Player.local.health
`
`
alt.Player.local.armour
`

**Describe alternatives you've considered**
Using natives
`
native.getEntityHealth(alt.Player.local.scriptID)
`

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[2.1-dev30](https://discord.com/channels/371265202378899476/528297438348574741/778656411239710750)
