### ISSUE TITLE
[VOICE] isTalking returns false and micLevel returns 0 all the time.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#655]
**Client/server version**

`build #1286, branch release`

**Current behavior**

using isTalking returns false, micLevel returns 0. All the time even if you are talking or pressing the vc chat key

**Expected behavior**

It should returns the right values.

**Steps to reproduce**

alt.everyTick(() => {
            alt.log(`alt.Player.local.isTalking`);
});

**Comment by VnX-SolidSnake** [comment]
I think you're not pressing the key ... I wouldn't log it in a tick event ... try this out : 

alt.everyTick(() => {
if(alt.Player.local.isTalking)
   alt.log("he is talking now");
});

This getter works for us in our gamemode... 
please check your altV settings .. maybe the wrong key pressed?


~ 🐍

**Comment by Heryshaf** [comment]
it's an issue with windows 10 special mic access.
