### ISSUE TITLE
Native setVehicleLights is not synced

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#657]
**Client/server version**

`Build #1286, branch release`

**Current behavior**
Its not synced automatically

**Expected behavior**
That we dont need to sync it self

**Steps to reproduce**
Just call the functions and you will see that it isnt synced

**Comment by FabianTerhorst** [comment]
setVehicleIndicatorLights = #76

**Comment by C0kkie** [comment]
Will be tracked here https://github.com/altmp/altv-issues/issues/737
