### ISSUE TITLE
Add dimension getter

### ISSUE THREAD

**Issue by cmdflow** [altmp/altv-issues#658]
**Suggestion**
Please integrate client side getter for dimension

**Use cases**
You'll need the dimension getter e.g. if you build yourself an object streamer or other checks when player are in different dimensions (e.g. they are in their homes which is seperated by dimension so you can use the same interieur).

**Describe the solution you'd like**
Implementation of: alt.Player.local.dimension

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Lhoerion** [comment]
Related to #654

**Comment by FabianTerhorst** [comment]
Client doesn't know its own dimension. You can send it via a own event when you need it.

**Comment by ZackaryH8** [comment]
[#654 ](url) Already an issue for one part of this

**Comment by cmdflow** [comment]
That's why i posted a feature request. We need dimension getter on the client :)

**Comment by FabianTerhorst** [comment]
You can send it via event, otherwise it costs more traffic for people that dont use it.

**Comment by cmdflow** [comment]
Okay then. Just tought it would be an improvement for all but if it would cause to much traffic, i will do that event on my own :)

**Comment by FabianTerhorst** [comment]
is added in dev/15.0-dev49
