### ISSUE TITLE
Health issues

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#659]
**Client/server version**

`build #1286, branch release`

**Current behavior**

1. player.spawn() ignores the maxHealth set and makes health goes out of sync for other clients if the maxHealth is > 200
2. Setting Health//maxHealth after player.model set is usually ignored a timeout is required
3. player.maxHealth would only allow the player.health to be set to maxHealth -1, unlike maxArmour, armour.

**Expected behavior**

Everything goes in order in an expected way, you know.

**Steps to reproduce**

1-.
```
player.maxHealth = 600;
player.spawn(50, 60, 70);
player.health = 600;
(use the player.health gett => 200)

```
2- 
```
player.model = 'whatever_model';
player.maxHealth = 600;
```

3-  
```
player.maxHealth = 600;
player.health = 600;
```

(try to use the player.health getter => returns 200)

**Possible solution**

player.spawn respects the maxHealth set or gets an extra argument to pass the new maxHealth
player.model setter becomes a function with maxHealth?

**Comment by Heryshaf** [comment]
I want to add it also bugs out on stream in for other players if you have hp > 200

**Comment by LeonMrBonnie** [comment]
This is only partly fixed.
The correct max health value gets sent to the client, but it seems to get reset on the server. (But the value after the reset is not synced to the client)

With this code:
`js
    alt.log(player.maxHealth);
    player.maxHealth = 500;
    alt.log(player.maxHealth);
    alt.setTimeout(() => {
        alt.emitClient(player, "maxHealth");
        alt.log(player.maxHealth);
    }, 2000);
`
It will log the following:
`
200
500
200
`
But clientside the getEntityMaxHealth native correctly shows 500 max health.

**Comment by Heryshaf** [comment]
Server side as Leon said will store the wrong player.health if maxHealth is used in many cases

**Comment by martonp96** [comment]
Fixed in latest dev

**Comment by Heryshaf** [comment]
Health, armour are still bugged if you teleport to a player out of your stream range and that player has maxHealth > 200, it falls back to 200
Armour on hud is not correctly correlated with maxArmour

**Comment by martonp96** [comment]
fixed in dev55
