### ISSUE TITLE
Roll and pitch are inverted for vehicles

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#661]
**Client/server version**
`Build #1299, branch RC`

**Current behavior**
Rool and Pitch are inverted server-sive for vehicles

**Expected behavior**
![image](https://user-images.githubusercontent.com/7643284/96190535-af67b680-0f42-11eb-8744-acda8884f2bc.png)

**Steps to reproduce**
```
IVehicle vehicle = player.Vehicle;
vehicle.Rotation = new Rotation(vehicle.Rotation.Roll, vehicle.Rotation.Pitch + 1, vehicle.Rotation.Yaw);
```
With vehicle aligned north
![image](https://user-images.githubusercontent.com/7643284/96190218-2781ac80-0f42-11eb-9107-48532b50f43b.png)

Applying pitch results in:
![image](https://user-images.githubusercontent.com/7643284/96190282-42ecb780-0f42-11eb-8af1-c51ededd9910.png)

**Context (environment)**
I saw that several natives have roll and pitch inverted in parameters so I wanted to be sure this apply also to server-managed entities.

**Possible solution**
Invert Roll and Pitch where needed

**Comment by LeShred** [comment]
Setting vehicle aligned East makes applying Roll and Pitch correctly.
It seems like Roll and Pitch are not based on vehicle rotation but based on Y axis as origin point

**Comment by martonp96** [comment]
Fixed in dev branch.
