### ISSUE TITLE
native setEntityVisible is synced across clients

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#664]
**Client/server version**

`build #1286, branch release, also on 2.1-dev2`

**Current behavior**

native setEntityVisible is synced across clients
**Expected behavior**

It shouldn't be synced, else, we might end up with ghost hackers we can't see?

**Steps to reproduce**

`game.setEntityVisible(player.scriptID, true);`

**Comment by C0kkie** [comment]
Thats a duplicate of https://github.com/altmp/altv-issues/issues/623

**Comment by Heryshaf** [comment]
@C0kkie Ah, cheers!

**Comment by Lhoerion** [comment]
Duplicate of #623
