### ISSUE TITLE
Improve long string emits

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-issues#666]
Improving long string emits with a better method. Original idea from hazard.

**Suggestion**
Improving long string emits with a better method.

**Additional context**
Original idea from hazard.

**Comment by 7Hazard** [comment]
Both client and server can now send long strings in dev

**Comment by Lhoerion** [comment]
Added/~~Fixed~~/~~Changed~~ in build #[2.1-dev4](https://discord.com/channels/371265202378899476/528297438348574741/769043993035014164)

**Comment by Lhoerion** [comment]
~~Added~~/~~Fixed~~/Changed in build #[2.1-dev4](https://discord.com/channels/371265202378899476/528297438348574741/769043993035014164)
