### ISSUE TITLE
Function to block unequip empty weapons 

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#667]
**Suggestion**
It would be nice if there will be a function to block the automatically unequipment of a empty weapon in the future,

**Use cases**
I have no special use case to describe it, but i think its always a good function to block it. Its mostly just annoying

**Describe the solution you'd like**
Something like

alt.Player.local.unequipEmptyWeapons = boolean;

**Describe alternatives you've considered**
At the moment it is possible to do at with a workround via the clearPedTasks native

**Comment by tastydev** [comment]
would like to see this, too

**Comment by DurtyFree** [comment]
Some technical input to this issue: https://github.com/citizenfx/fivem/blob/57621774bdad97a4acf4a94b21ee32f14e3c7c6e/code/components/extra-natives-five/src/WeaponExtraNatives.cpp#L140
https://github.com/CamxxCore/RealisticReload/blob/master/ManualReload/main.cpp

**Comment by C0kkie** [comment]
Added dev/4.0-dev17

alt.setConfigFlag("DISABLE_AUTO_WEAPON_SWAP", true)
