### ISSUE TITLE
Event weapondamage doesnt trigger if you get punched

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#668]
**Client/server version**

`Build #1286, branch release`

**Current behavior**
Currently this event doesnt get triggered if you punch someone

**Expected behavior**
That it also triggers if you get punched or add a seperate event

**Comment by martonp96** [comment]
Currently we handle only weapon shots came from players. (basically this event is bulletDamage instead of weaponDamage)

**Comment by C0kkie** [comment]
Is it possible to add such type of damage also or any other event or something?

**Comment by yoranjj** [comment]
Just tested on 2.1-dev33 (dev branch), it does trigger when you get hit/punched with fists.
