### ISSUE TITLE
WebView scalling not the same as in normal Chrome Browser

### ISSUE THREAD

**Issue by Jooonaas** [altmp/altv-issues#669]
**Client/server version**

`Build 1286, branch release`

**Steps to reproduce**

Using VueJS and fill the data with values emited by alt:v client WebView Object

**Context (environment)**

I am using VueJS on my WebViews but the scalling and the position of some elements is not the same as if I open the file with my Chrome Browser

**Comment by Lhoerion** [comment]
Provide "real" steps to reproduce and show what's the difference

**Comment by FabianTerhorst** [comment]
Cef is not fully identical to chrome. It wont always give the same result. Thats not a bug of the implementation, but feel free to open a issue in cef's repository.
