### ISSUE TITLE
Event playerDamage has inverted damage and weaponHash + the weaponHash and the attacker doesn't valid

### ISSUE THREAD

**Issue by John-Deamers** [altmp/altv-issues#670]
**Client/server version**
Build #1286, branch release

**Current behavior**
Currently this event has damage and weaponHash inverted
[https://i.imgur.com/3s2wbjZ.png](url)
When you get punch by a player(toto for this example) then jump off a building for example, the attacker still toto and the weapon still her fist and not the correct weapon (weapon_fall)

**Expected behavior**
That the values damage and weaponHash is not inverted in the wiki or in game
and when a player jump off a building or other (like do player.health -= 10) it return the good weaponHAsh and the good attacker

**Comment by John-Deamers** [comment]
This is a démo in **Build #1301, branch release**:

**Demo** : [https://i.imgur.com/BbEodga.png](url)
Step 1: Player 2 punch Player 1, you can see all data is good
Step 2: Player 1 jump of à little building, but this write that Player 2 punch again Player 1
Step 3: Same as step 2
Step 2: Same as step 3
Step 4: Player 1 died and all data is correct

**My function** : [https://i.imgur.com/hrZt9CY.png](url)
**In the Wiki** : [https://i.imgur.com/0j0xf50.png](url)
You can see that the order of the parameters are not the same but the values ​​are good, weaponHash and damage are inverted

**Comment by Lhoerion** [comment]
I've already fixed that, thanks for report
