### ISSUE TITLE
Implement a querying mechanism

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#671]
**Suggestion**

Implement a querying mechanism to expose some or all information about current online count, total slots and online names / pings
a limit can be added to be used by server owners or give the ability to server owners on what to expose upon querying though events api
Maybe add the option to turn it off/on through the script?
**Use cases**

Showing players, online count on a custom website or for a discord bot or for server monitoring and regular statistics or banners and other stuff, beside giving more publicity to alt:v on game monitoring sites without relaying on a single point like a master list or whatever.

**Comment by FabianTerhorst** [comment]
This is unrelated to the server core functionality. You can create a e.g. express server in it yourself to report the new count in connect disconnect.

**Comment by Heryshaf** [comment]
@FabianTerhorst It can be implemented into the core itself like hundreds of other game mp mods or multiplayer games, since the server core already comes equipped with a fine http server (and game querying usually is carried on the same port) or on udp too.
An alternative would be make a resource with a separate web server that runs on a different port and do what you want, implementing it into the server might come handy for some people that relay on querying. I know it's not a priority or whatsoever but it's a suggestion for the future. Thanks.

**Comment by ZackaryH8** [comment]
If you want your server stats, you can use the Masterlist API [here](https://wiki.altv.mp/Masterlist_API). It is rate-limited so be aware how much data you pull from it

**Comment by martonp96** [comment]
Important information about a server can be reached trough the masterlist as @ZackaryH8 mentioned. If you need unique API for your server, you have all the tools to do it through modules.
