### ISSUE TITLE
takeScreenshotGameOnly throwing debug error even with permission required

### ISSUE THREAD

**Issue by MacieGx** [altmp/altv-issues#676]
**Client/server version**
2.1-dev4

**Current behavior**
takeScreenshotGameOnly throwing error ``Must be in debug mode`` even when Screen Capture permission is required.

**Expected behavior**
takeScreenshotGameOnly work with Screen Capture permission.

**Steps to reproduce**
``alt.takeScreenshotGameOnly()``

**Comment by C0kkie** [comment]
Cant reproduce it on dev/2.1-dev65
