### ISSUE TITLE
takeScreenshotGameOnly throws error v8::Context::Exit():

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#677]
**Client/server version**
`Build 2.1-dev4`

**Current behavior**
Using `takeScreenshotGameOnly` like `takeScreenshot` throws error: `[Error] [V8] v8::Context::Exit(): Cannot exit non-entered context`.

**Expected behavior**
No error.

**Steps to reproduce**
Using the function with this method:
`
export const CreateScreenshotOnlyGame = async (name: string): Promise<string> => {
    const screen = await alt.takeScreenshotGameOnly(name);
    return screen;
};
`

**Comment by 7Hazard** [comment]
Where do you call CreateScreenshotOnlyGame from

**Comment by Revyn112** [comment]
@7Hazard Calling it Webview Event "On"

`
mainView.on('CEF:DO_SCREENSHOT_ONLY_GAME', () => {
    CreateScreenshotOnlyGame('ID_CARD_SCREENSHOT').then((screen) => {
        mainView.emit('CEF:UI:InterfaceController', 'ActionView', callback, screen);
    });
});
`

**Comment by LeonMrBonnie** [comment]
https://github.com/altmp/altv-client-js/blob/master/src/bindings/Main.cpp#L657
This might be the cause of the problem.
