### ISSUE TITLE
playerWeaponChange gets triggered on modelchange and scenarios

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#680]
**Client/server version**

`Build #1301, branch release`

**Current behavior**
Currently if you change the playermodel serverside for example to a a_c_husky the playerWeaponChange event gets triggered and the event param "newWeapon" will result 3854032506

Also if you play a sceneario the following hash will be triggered as new weapon (966099553)

native.taskStartScenarioInPlace(alt.Player.local.scriptID, "WORLD_HUMAN_CONST_DRILL", 0, true);

**Expected behavior**
That it doesnt trigger if you change the model or playing a scenario

**Comment by zziger** [comment]
Some models (mostly animal) like pigeon or husky have built-in weapon, that executes some action of this model. As far as i remember for husky it's bite. This is likely related to issue.

**Comment by C0kkie** [comment]
4194021054, 2725352035,
  3799318422,   94548753,
  1161062353, 3854032506,
  3146768957, 2793925639,
   955837630, 4106648222,
   861723357,  148160082,
  1205296881, 4198358245,
   743550225, 3030980043

That are btw all ids which get triggered by animals
