### ISSUE TITLE
Vehicle handling (initialDriveForce) bug!

### ISSUE THREAD

**Issue by Mikhalin** [altmp/altv-issues#681]
**Client/server version**

`2.1-dev7 (dev)`

**Current behavior**
vehicle.handling.initialDriveForce - does not work

**Expected behavior**

vehicle.handling.initialDriveForce - apply to the vehicle

**Steps to reproduce**

```
alt.on("gameEntityCreate', (entity) => {
    if(entity.constructor.name === "Vehicle") {
        entity.handling.reset();
        entity.handling["initialDriveForce"] = 1;
        try {
            entity.setMeta('defaultHandling', JSON.stringify(handlingToObject(entity.handling)))
            let newHandling = entity.getSyncedMeta('newHandling')
            if(!newHandling) return
            newHandling = JSON.parse(newHandling)
            for(let property of Object.keys(newHandling)) {
                const value = newHandling[property]
                if(property == 'initialDriveForce') {
                    alt.log(entity.handling["initialDriveForce"]);
                } else if(property === 'centreOfMassOffset' || property === 'inertiaMultiplier') {
                    entity.handling[property] = new alt.Vector3(value.x, value.y, value.z)
                } else if(property == 'maxSpeed') {
                    var currentSpeed = parseFloat(value / 3.6);
                    alt.setTimeout(() => {
                        native.setEntityMaxSpeed(entity.scriptID, currentSpeed)
                    }, 1500);
                }
                else entity.handling[property] = value
            }
        } catch(err) { console.log(err) }
    }
});
```

**Context (environment)**

I'm just trying to apply handling to the created car via a request from the server to the client using
gameEntityCreate

**Possible solution**

Without concept

**Comment by ThomasMarangoni** [comment]
Please provide properly formatted code, branch name and version you tested it on.

**Comment by Mikhalin** [comment]
> Please provide properly formatted code, branch name and version you tested it on.
alt:V Server and Client version: 2.1-dev7 (dev)

**Comment by Lhoerion** [comment]
Edit the issue to match the template, otherwise it'll get closed

**Comment by Mikhalin** [comment]
> Edit the issue to match the template, otherwise it'll get closed

Is everything right now?

**Comment by Lhoerion** [comment]
By "doesn't work", you mean that it has no effect on the vehicle handling?
And did you test it thoroughly?

**Comment by Mikhalin** [comment]
> By "doesn't work", you mean that it has no effect on the vehicle handling?
> And did you test it thoroughly?

> Yes.
> Very carefully.

**Comment by Mikhalin** [comment]
And more: Another function getForHandlingName doesn't work with custom cars, even if I specify the handling Name from handling.meta

**Comment by martonp96** [comment]
@Mikhalin show me your vehicle resource with handling.meta in it

**Comment by martonp96** [comment]
and the code with getForHandlingName

**Comment by Mikhalin** [comment]
> and the code with getForHandlingName

> alt.log(alt.HandlingData.getForHandlingName(alt.hash('G63AMG6x6')));
> https://imgur.com/a/PQ3wkIm

**Comment by martonp96** [comment]
Did you try to set initialDriveForce to any high values to see if there is any change?
What do you see when you print initialDriveForce's value before and after setting it?
@Mikhalin

**Comment by Mikhalin** [comment]
This value is applicable, but does not affect the car's handling. I tried multiple values.
Similarly with drag Coef
@martonp96

**Comment by aydek** [comment]
it seems that none of the setters work expect acceleration.

**Comment by martonp96** [comment]
Things are working in latest dev, i tested them myself.

**Comment by aydek** [comment]
> Things are working in latest dev, i tested them myself.

Could you drop me your code, unless I'm doing something wrong it still doesn't work for me. Tried currend dev and release

**Comment by LeonMrBonnie** [comment]
Will be tracked in #684
