### ISSUE TITLE
Event onPlayerDamage not fired when player is drowning

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#682]
**Client/server version**
`Build #1300, branch RC`

**Current behavior**
The onPlayerDamage-Event only gets triggered when the player.Health changes; except when the player is drowning.

**Expected behavior**
onPlayerDamage-Event should trigger when player is drowning.

**Steps to reproduce**
Take a good swim and dive.

**Context (environment)**

**Possible solution**

**Comment by martonp96** [comment]
It works perfectly for me. Can you please point out where is the issue? And post the code you are testing with please. @kineese

**Comment by Arochka** [comment]
Same issue with fall damages

**Comment by martonp96** [comment]
Both fall damage and drowning damage triggers playerDamage event for me. 
Can you please provide reproduction steps that work on empty servers? @Arochka @kineese

**Comment by Heady20006** [comment]
The health is going down but the server side event OnPlayerDamage isn't triggered.

**Comment by Arochka** [comment]
The problem is only with C# module, JS module trigger event fine

**Comment by FabianTerhorst** [comment]
Fixed with latest release module update.
