### ISSUE TITLE
Adding onArmourChange event

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#683]
**Suggestion**
Currently the only way to track the players armour is only by checking it inside an intervall or when the onPlayerDamage-Events fires in case that the player health changes.

_Getting damage by bullet_
When the player gets shot part of the incoming damage is absorbed by the armor ==> onPlayerDamage gets triggerd.

_When driving/falling_
Driving against a wall or falling down reduced the armour. The onPlayerDamage event only gets triggered when the incoming damage is bigger than the players current armour ==> onPlayerDamage when (armour-incomingDamange<0).

_Elemental damage fire/smoke_
Those sources of damage afflict direct damage ==> onPlayerDamage triggerd. When the player drowns the onPlayerDamage-Event will not be triggered (see #682 ).

It would be great to have a buildin solution for change-tracking the players armour.

**Use cases**
_Roleplay_
Implementing item-based armour management. A armour-vest can be equiped. The armour has a duration (0-100) and changes if the players armour changes. E.g a player equips a vest with 45 duration the player should only get 45 armour.
 
**Describe the solution you'd like**
Adding an server-side event for tracking changes of the players armour.

**Describe alternatives you've considered**
Current workaround would be to track the current armour on client-side and check on everytick/in an interval if the armour has been changed. In case of a change emit an update to the server.

**Comment by FabianTerhorst** [comment]
In my opinion player damage should trigger always on armor change when hitted.

**Comment by b2soft** [comment]
any news on this?

**Comment by Pads-El** [comment]
any news?

**Comment by FabianTerhorst** [comment]
Fixed in next dev version.
