### ISSUE TITLE
IVehicleHandling setters with initial at front does not work

### ISSUE THREAD

**Issue by aydek** [altmp/altv-issues#684]
**Client/server version**
`Build #2.1-dev7, branch dev`

**Current behavior**
IVehicleHandling setters that starts with initial doesn't work

**Expected behavior**
Should work

**Steps to reproduce**
```
alt.on('gameEntityCreate', (entity: alt.Entity) => {
    if (entity instanceof alt.Vehicle) {
        //Does not work
        entity.handling.initialDragCoeff = 5;
        entity.handling.initialDriveForce = 5;
        entity.handling.initialDriveGears = 3;
        //Works fine
        entity.handling.tractionCurveMax = 5;
        entity.handling.tractionCurveMin = 5;
    }
});
```

**Context (environment)**
Trying to change vehicle handling.

**Comment by martonp96** [comment]
```
    veh.handling.initialDragCoeff = 500;
    veh.handling.initialDriveForce = 500;
    veh.handling.initialDriveGears = 30;
```
this works for me

**Comment by aydek** [comment]
Don't know how it works for you but on current version I'm getting 0 effect with same code.

**Comment by yoranjj** [comment]
Related to https://github.com/altmp/altv-issues/issues/681

The snippet marton provided doesn't work on latest dev.

**Comment by b2soft** [comment]
any news on this?

**Comment by mrgharabaghi** [comment]
`Build #2.24, branch release`

Some properties of `IVehicleHandling` interface not working at all.
It is better to check all the properties of `IVehicleHandling` again.

The number of gears must be reduced to 2 and the weight of the vehicle must be changed to 100kg.
```js
// Determines how many forward speeds/gears a vehicle's transmission contains.
alt.Player.local.vehicle.handling.initialDriveGears = 2;

// The weight of the vehicle.
alt.Player.local.vehicle.handling.mass = 100.0;
```

**Comment by gotgameru** [comment]
branch 5.3 release, without respawn of vehicle inital* setters don't work.

**Comment by Revyn112** [comment]
still not working

**Comment by amazur31** [comment]
Bump.
This is a really big issue for us. We can't develop any custom handlings for default cars due to this and related issues. Any streaming or Handling API calls don't work on AltV.
@DurtyFree recommended us to push this issue.

**Comment by TrashaPanda** [comment]
> Bump. This is a really big issue for us. We can't develop any custom handlings for default cars due to this and related issues. Any streaming or Handling API calls don't work correctly on AltV. @DurtyFree recommended us to push this issue.

            Alt.Natives.ModifyVehicleTopSpeed(vehicle, 1); <--- add this after all your handling adjustments. profit. have a nice day.

**Comment by mrgharabaghi** [comment]
@aydek @xxshady

Take a look at [this](https://github.com/altmp/altv-issues/issues/2274#issuecomment-2327826948) and [this](https://github.com/altmp/altv-issues/issues/1606#issuecomment-2327823397). Time to close the issue.
