### ISSUE TITLE
Server closes shortly after loading a resource

### ISSUE THREAD

**Issue by hookmethods** [altmp/altv-issues#685]
**Client/server version**
`Build #1301, branch Release`

**Current behavior**
Server closes shortly after loading a resource

**Expected behavior**
Server should be able to intercept that and print information that loading resource failed with adequate reason

**Steps to reproduce**
N/A

**Context (environment)**
N/A

**Possible solution**
I have a img folder in my CEF resource and I have a bunch of images that named in Chinese letters and the server doesn't support UTF8 letters yet so the compilation leads to a crash issue i don't know if it was an ALTV bug I prefer it to be an language support

I hope AltV could support Chinese letters and the ime editor in the future

**Comment by Lhoerion** [comment]
Closing it by request of the author.

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.
