### ISSUE TITLE
The native setVehicleFixed fix the doors but sometimes they fall on the ground

### ISSUE THREAD

**Issue by John-Deamers** [altmp/altv-issues#686]
**Client/server version**

`Build #1301, branch release`

**Current behavior**

When the native "setVehicleFixed" is called the vehicle doors that where broken, come back but fall to the ground sometimes, not every times

**Expected behavior**

When the native is called, the vehicle doors that where broken should be fixed and not fall on the ground

**Steps to reproduce**

You just need to open a vehicle door and broke it then call the native, sometimes you will see the door spawn and fall on the ground

**Context (environment)**

I just try to create a system for repair my vehicle without respawn a new car and i try this native and i saw the doors fall. I set the doors state etc.. in the server-side before i call the native in client, the server is on local so there's no sync problem i think

**Possible solution**

I don't know, i'm sorry

**Comment by Heryshaf** [comment]
I have some sort of the same function but doors don't fall i use the following:

on server:
```
	vehicle.engineHealth = 1000;
	vehicle.bodyHealth = 1000;
	alt.emitClient(null, `RepairVehicle`, vehicle);
```

on client:
```

alt.onServer('RepairVehicle', (vehicle) => 
{
		if(!vehicle.scriptID) return;
		game.stopEntityFire(vehicle.scriptID);
	        game.setVehicleFixed(vehicle.scriptID); 
});
```
