### ISSUE TITLE
Weird & unexplained client errors/warnings in log.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#689]
**Client/server version**

`alt:V build #2.1-dev14`

**Current behavior**

Spams the following error on connection only:

`[00:36:52][Error] Temp data already defined`

and also spams many!!! of these
`[Warning] No vehicle 1096`

if many vehicles are added to the server (>1000?) it only shows upon init connection.

**Steps to reproduce**

I don't have any ideas about Temp data error, the no vehicle error is achieved by adding many vehicles to the server (i currently have 2000)

**Comment by martonp96** [comment]
Temp data already defined might happen when the game can't create the networked entity on the first try.
No vehicle warning happens when the vehicle is in the pool but the game didn't create the vehicle yet. (by any reasons)
