### ISSUE TITLE
Add the ability to retrieve a single server information through API.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#690]
**Suggestion**

Add the ability to retrieve a single server information through API using the unique identifier of the server, as it currently supports retrieving the whole list through the GET request.

**Use cases**

Discord bots, websites and etc, wouldn't need to actually scrape the whole list.

**Describe the solution you'd like**

Add an API route to get a single server information using the unique ID, a proper example might be: 

http://api.altv.mp/servers/server_info/{unique_id}
--

**Describe alternatives you've considered**

Scraping the whole list, parsing and obtaining my own server's info.

**Comment by drakeee** [comment]
I think thats what https://api.altv.mp/server/uniqueidhere is used for.

**Comment by FabianTerhorst** [comment]
Api already exists.
