### ISSUE TITLE
getCursorPos is removed on client side.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#691]
**Client/server version**

`alt:V build #2.1-dev15`

**Current behavior**

getCursorPos no longer works/exists on client side => "SyntaxError: The requested module 'alt-client' does not provide an export named 'getCursorPos'"

this breaks many functions and libs including the nativeUI port.

**Expected behavior**

It should exist, it's an important function that many scripts depend on.

**Comment by FabianTerhorst** [comment]
Dev currently has some broken js runtime so when you find more functions that don't work its not because they are removed but because there is a bug in dev build.

**Comment by Heryshaf** [comment]
> Dev currently has some broken js runtime so when you find more functions that don't work its not because they are removed but because there is a bug in dev build.

Ah well, wanted to not some stuff are broken in latest dev, i also mentioned the version. Cheers

**Comment by 7Hazard** [comment]
Fixed in latest dev
