### ISSUE TITLE
Server termination after loading resource.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#692]
**Client/server version**

`2.1-dev16 (dev)`

**Current behavior**

Server crashes (terminates) instantly after trying to load a resource. (On a linux box with Ubuntu as a distro, other altv server versions work and worked just fine)
```
[10:56:18] alt:V Server 2.1-dev16 (dev)
[10:56:18] Starting Test Server on 0.0.0.0:7788
[10:56:18] Loading resource GreenfieldV
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

**Comment by Lhoerion** [comment]
Try to run server with debugger, so we got more useful informations.

**Comment by Lhoerion** [comment]
Try to run server with debugger, so we got more useful informations

**Comment by Heryshaf** [comment]
@Lhoerion Already did and send the dump to Heron on discord in a pastebin.

**Comment by Heryshaf** [comment]
It looks fixed within dev20.
Thank you
