### ISSUE TITLE
Native call failed

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#693]
**Client/server version**

`alt:V build #2.1-dev16, branch dev`

**Current behavior**

Calling some natives on clientside (not sure which or how many) sometimes fail.
example:

```
[13:04:07][Error] Native call failed: setAudioFlag
[13:04:07][Error]   native.setAudioFlag("LoadMPData", true);
[13:04:07][Error]   Error: Native call failed
[13:07:01][Error] Failed to load resource GreenfieldV
```

**Comment by Hardy535** [comment]
Some other natives that are not working since some dev-branch update:

- requestStreamedTextureDict
- taskFollowToOffsetOfEntity
- playSound

**Comment by Heryshaf** [comment]
The natives i reported have been fixed in latest devs, no idea if anyone has other issues with any other natives

**Comment by Hardy535** [comment]
Can confirm, the natives I listed are also fixed.

**Comment by LeonMrBonnie** [comment]
Natives seem to be completely fixed now, if there are still any natives that do not work, please report them here and the issue will be reopened.
