### ISSUE TITLE
setPartDamageLevel is reseted after some seconds

### ISSUE THREAD

**Issue by Heady20006** [altmp/altv-issues#695]
Please fill in the *entire* template below. -->

**Client/server version**
Server-Version
`Build # 2.1-rc1 (rc)`

**Current behavior**
I tried to set damage to vehicleparts with setPartDamageLevel().
Straight after the setting i can read out the setted damageLevel
but after some seconds the damageLevel is reseted to "NotDamaged"

**Expected behavior**
It should not be reseted.

**Steps to reproduce**
Try to set damage with this codesnipped:

` await AltAsync.Do(() =>
  {
     serverVehicle.SetPartDamageLevel(VehiclePart.FrontLeft, (byte)3);
     serverVehicle.SetPartDamageLevel(VehiclePart.FrontRight, (byte)3);
     serverVehicle.SetPartDamageLevel(VehiclePart.MiddleLeft, (byte)3);
     serverVehicle.SetPartDamageLevel(VehiclePart.MiddleRight, (byte)3);
     serverVehicle.SetPartDamageLevel(VehiclePart.RearLeft, (byte)3);
     serverVehicle.SetPartDamageLevel(VehiclePart.RearRight, (byte)3);
     Logger.Info($"Setting PartDMG-Level FrontLeft: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.FrontLeft)}");
     Logger.Info($"Setting PartDMG-Level FrontRight: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.FrontRight)}");
     Logger.Info($"Setting PartDMG-Level MiddleLeft: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.MiddleLeft)}");
     Logger.Info($"Setting PartDMG-Level MiddleRight: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.MiddleRight)}");
     Logger.Info($"Setting PartDMG-Level RearLeft: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.RearLeft)}");
     Logger.Info($"Setting PartDMG-Level RearRight: 
     {serverVehicle.GetPartDamageLevel(VehiclePart.RearRight)}");
  });
`
DamageLevel of each part will be 3

after some seconds try to read the damageLevel of these parts with:

`
await AltAsync.Do(() =>
  {
     Logger.Info($"Checking PartDMG-Level FrontLeft: {serverVehicle.GetPartDamageLevel(VehiclePart.FrontLeft)}");
     Logger.Info($"Checking PartDMG-Level FrontRight: {serverVehicle.GetPartDamageLevel(VehiclePart.FrontRight)}");
     Logger.Info($"Checking PartDMG-Level MiddleLeft: {serverVehicle.GetPartDamageLevel(VehiclePart.MiddleLeft)}");
     Logger.Info($"Checking PartDMG-Level MiddleRight: {serverVehicle.GetPartDamageLevel(VehiclePart.MiddleRight)}");
     Logger.Info($"Checking PartDMG-Level RearLeft: {serverVehicle.GetPartDamageLevel(VehiclePart.RearLeft)}");
     Logger.Info($"Checking PartDMG-Level RearRight: {serverVehicle.GetPartDamageLevel(VehiclePart.RearRight)}");
  });
`

it will show you "NotDamaged"

Screenshot:
https://prnt.sc/vhu7h9

And there is no visually damage on the vehicleParts.
Its a nice and clean vehicle.

**Context (environment)**

**Possible solution**

**Comment by C0kkie** [comment]
Will be tracked here in the future https://github.com/altmp/altv-issues/issues/737

**Comment by martonp96** [comment]
The issue is now tracked in #737.
