### ISSUE TITLE
 Asking for a new installation if you use connecturl

### ISSUE THREAD

**Issue by Lennnart1337** [altmp/altv-issues#696]
**Client/server version**

`Build #1301, branch release`

**Current behavior**

The launcher is currently asking for a new installation if
you use connecturl.

**Expected behavior**

Usually the launcher shouldn't ask questions and the game should open as normal.

**Steps to reproduce**

1. Open CMD
2. use start [path to your altv folder] + /altv.exe -connecturl [url] (Exemple: start C:\altv\altv.exe

Informations:
Alt:V must already be installed. The command must also be executed from an Other Folder. For example C:\. 

**Context (environment)**

It affects the way connecturl should work and severely limits the
possibilities which would be possible with connecturl. (It sucks to have a second alt: V Launcher)

**Possible solution**

I think it asks whether there is an altv.exe in the folder where you use connecturl. To fix this you would have to transfer this query to the exe location.

**Comment by C0kkie** [comment]
Confirmed on rc/2.2-rc11

**Comment by 7Hazard** [comment]
This is more of an issue of not starting altv.exe in the install dir as the current working directory

**Comment by 7Hazard** [comment]
Im afraid restricting launching of altv.exe with current working directory to anything other than the installation dir would cause undesired side effects, so no fix at this time.

You should just not launch altv.exe from anywhere other than the installation dir as the current working directory.
