### ISSUE TITLE
Changing a player's dimension that inside a vehicle doesn't remove him from his vehicle

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#697]
**Client/server version**

`alt:V Server 2.1-rc1 (rc)`

**Current behavior**

Changing a player's dimension that inside a vehicle doesn't remove him from his vehicle and shows him up in the vehicle just fine. Whilst the dimension of the vehicle is still in the old one.

**Comment by FabianTerhorst** [comment]
fixed in next dev release.
