### ISSUE TITLE
Add player.barePing getter, server tick getter.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#698]
**Suggestion**

Add a player.barePing getter that only measures the time in ms for the client<>server connection, unlike player.ping getter which involves the game server as a middle layer.
Add a server tick getter for other measures.
**Use cases**

Have network (connectivity) performance measures for the clients, this can be used to have mean values of only the connection ping (server<>client) to be able to have better data about the server network stuff, like which location is better to host at, which isp, etc.
 
**Describe alternatives you've considered**

having just a server tick getter and subtracting from the current player.ping

**Comment by FabianTerhorst** [comment]
We will document more clearly what the getter is doing. But we won't do 2 getters.
