### ISSUE TITLE
Client stuck on launching GTA V if connection to Rockstar servers fail.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#701]
**Client/server version**

`alt:V build #2.1-rc1`

**Current behavior**

Client stuck on launching GTA V if connection to Rockstar servers fail.
https://i.ibb.co/P5WH4Sg/image.png
This also happens on dev, release.
**Expected behavior**

The alt:V client to just quit / terminate.

**Comment by EtzBetz** [comment]
I'd expect the client to show a message about why it's being shut down, but otherwise yes, it shouldn't be stuck.

But I don't know if it's feasible to detect this, just my opinion.

**Comment by zziger** [comment]
Fixed (by adding a timeout and a descriptive error message) with launcher rework
