### ISSUE TITLE
alt.setTimeout not triggering

### ISSUE THREAD

**Issue by Zynischer** [altmp/altv-issues#703]
**Client/server version**

`2.1-dev24 (dev)`

**Current behavior**
alt.setTimeout is not getting triggered.
Output ist only "a"

**Expected behavior**
Output should be 
"a"
"b"
"c"

**Steps to reproduce**
`alt.on("connectionComplete", () => {
    loginCef = new alt.WebView("http://resource/client/webviews/login/anmelden.html", false);

    loginCef.focus();

    setCamera();

	alt.log("a");

	alt.setTimeout(()=>{

		alt.log("b");

		hide();

		alt.log("c");

	}, 1000)

});`

**Context (environment)**

Only 2 resources are running, this script and chat resource

**Possible solution**

**Comment by FabianTerhorst** [comment]
Is the timer outside the webview event not working as well?

**Comment by LeonMrBonnie** [comment]
This is a known and already fixed, but there wasn't a new dev build yet.

**Comment by Heryshaf** [comment]
Fixed in latest devs (dev 29 - dev30)
