### ISSUE TITLE
Methods showCursor, toggleGameControls are not working

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#706]
**Client/server version**

`dev/2.1-dev30`

**Current behavior**

Broken cursor show, ToggleGameControls (they don't work)

**Expected behavior**

They should work

Steps to reproduce: 

```
		  alt.showCursor(true);
		  alt.toggleGameControls(true);
```

**Comment by 7Hazard** [comment]
Please provide reproduction steps.

**Comment by Heryshaf** [comment]
Fixed.
