### ISSUE TITLE
Adding ARM support for Raspberry Pis

### ISSUE THREAD

**Issue by shockdevv** [altmp/altv-issues#708]
**Suggestion**
ARM support for Raspberry Pis.

**Use cases**
I think a lot of people would benefit from having ARM support, especially the ones who have home servers. Nowadays, indeed, Raspberry Pis are very popular.

**Comment by alextwothousand** [comment]
> **Suggestion**
> ARM support for Raspberry Pis.
> 
> **Use cases**
> I think a lot of people would benefit from having ARM support, especially the ones who have home servers. Nowadays, indeed, Raspberry Pis are very popular.

This would also be good to be able to target the future Mac's, which now consist of the Apple M1 chip - based on the ARM architecture.

**Comment by FabianTerhorst** [comment]
Just because it might support Raspberry PI's it doesnt mean it supports the m1 macs.

**Comment by alextwothousand** [comment]
But what's the likelihood of it not?

**Comment by FabianTerhorst** [comment]
Im 100% sure it won't work on the m1 without a extra adjustment for it.

**Comment by FabianTerhorst** [comment]
When a diamand server asks for this we can add it to the build pipeline since it increases ci minutes and a arm runtime isn't supported by the ci.
