### ISSUE TITLE
DestroyBaseObject on webview

### ISSUE THREAD

**Issue by inpex** [altmp/altv-issues#709]
**Client/server version**

`build #2.1-dev31, branch dev`

**Current behavior**

I create a webview via F8 Console and destroy them

**Expected behavior**

A webview is provided but not done. Console returns errors -> https://pastebin.com/Ycxj3Qqx

**Steps to reproduce**

https://pastebin.com/V6yz8GGD

**Context (environment)**

destroy the webview

**Possible solution**

**Comment by martonp96** [comment]
fixed
