### ISSUE TITLE
Missing newline in resource main tick too long message

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#710]
**Client/server version**

`Build #2.1-dev32, branch dev`

**Current behavior**
A newline is missing after the message, causing the next log to be on the same line. Also the message is missing a few spaces.
`[00:20:39][Warning] Resourcemaintick was too long27Event handler at main:client.js:106 was too long 35ms`

**Expected behavior**
A newline should be added after the message.

**Steps to reproduce**
Do heavy work on the resource main and wait for the next console log.

**Context (environment)**
-

**Possible solution**
-

**Comment by 7Hazard** [comment]
Fixed in upcoming dev

**Comment by Lhoerion** [comment]
~~Added~~/Fixed/~~Changed~~ in build #[2.1-dev33](https://discord.com/channels/371265202378899476/528297438348574741/780061122991620127)
