### ISSUE TITLE
Unimplemented getters

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#712]
**Client/server version**

`Build #2.1-dev32, branch dev`

**Current behavior**
Using the new clientside getters returns a placeholder value and shows a warning about them not being implemented in the CPP SDK.
List of unimplemented getters:
```c++
// Weapon getters
V8::SetAccessor(isolate, tpl, "currentWeaponTintIndex", &CurrentWeaponTintIndexGetter);
V8Helpers::SetAccessor<IPlayer, bool, &IPlayer::IsJumping>(isolate, tpl, "isJumping");
V8Helpers::SetAccessor<IPlayer, bool, &IPlayer::IsShooting>(isolate, tpl, "isShooting");
```

**Expected behavior**
They should be implemented.

**Steps to reproduce**
Use one of the new getters and look in the console.

**Context (environment)**

**Possible solution**

**Comment by C0kkie** [comment]
Everything got added except

currentWeaponTintIndex
isJumping
isShooting
isReloading

**Comment by C0kkie** [comment]
Currentstate on 9.0

isShooting is true when aiming for some reason | isShooting is true until ped gets his gun to bottom
isJumping doesnt seem to be working at all

**Comment by Marvisak** [comment]
alt::IPlayer::GetWeaponTintIndex and alt::IPlayer::HasWeaponComponent also don't work on the server.

**Comment by LeonMrBonnie** [comment]
> alt::IPlayer::GetWeaponTintIndex and alt::IPlayer::HasWeaponComponent also don't work on the server.

Currently the server does not know about all the weapon data of the player, only the currently equipped weapon, so this will have to wait until that data is available

**Comment by martonp96** [comment]
fixed in dev590
