### ISSUE TITLE
some clothing part are not synced

### ISSUE THREAD

**Issue by MikeAngel-dev** [altmp/altv-issues#713]
**Client/server version**

`Build #1301, branch release`

**Current behavior**

If you change clothing parts to -1 (in my case it's the torso but there could be more clothing parts affected), other players can't see that and see that you are wearing a shirt.
**Expected behavior**

This clothing part should be synced, so that the player can see the clothes of other players.
**Steps to reproduce**

first of all => I saw a fixed bug report about sync problems with female characters and the other player was a FEMALE character, so this could be necessary!

use a command or something else on server side:
server:
`chat.registerCmd("settorso", (player) => {
    alt.emitClient(player, "changeTorso", -1);
})`

client:
`alt.onServer("changeTorso", (index) => {
  game.setPedComponentVariation(game.playerPedId(), 11, index, 0, 0);
})`

**Context (environment)**

It shows a wrong torso. Everything is explained in the following images:

My point of view:
https://prnt.sc/vnll8t
view of other players (may be only existent for female characters):
https://i.imgur.com/9LIfF0j.png

**Possible solution**

**Comment by C0kkie** [comment]
Did you try alt.Player.local.scriptID instead of playerPedId

**Comment by MikeAngel-dev** [comment]
> Did you try alt.Player.local.scriptID instead of playerPedId

that does not fix it.

**Comment by Sushi1337** [comment]
Pretty sure -1 is just not a valid drawable for component 11, that's why the other player sees the default top instead of 'nothing'. If you want no top, use drawable 15 instead of -1.

**Comment by FabianTerhorst** [comment]
Unlike other mods invalid values arent synced. Feel free to report back when its not synced with correct values.
