### ISSUE TITLE
playerDisconnect refuses to be called

### ISSUE THREAD

**Issue by alextwothousand** [altmp/altv-issues#714]
**Client/server version**

`Build #2.1-rc5, branch rc`

**Current behavior**

When a player disconnects from my server, `playerDisconnect` is not called in any resource - whether its my main resource, or an empty resource.

**Expected behavior**

That callback should be called, so that I can save player's data in the database on disconnect.

**Steps to reproduce**

Create a resource. Handle the `playerDisconnect` callback and it won't work.

```js
/// <reference types="@altv/types-server"/>
import * as alt from "alt-server";

alt.on("playerConnect", (player) => {
    console.log("player connected");
    // this works fine.
});

alt.on("playerDisconnect", (player) => {
    console.log("player disconnected");
    // this does not work fine.
});
```

**Context (environment)**

As a result of this, I have to save player data after every operation that involves the database. This isn't efficient as database ops are costly, whereas, if this was working, I could simply cache the updates and then perform those costly database ops once whenever that player disconnects.

**Possible solution**

Did Not Answer.

**Comment by LeonMrBonnie** [comment]
Can't confirm on 2.1-dev32. The event works fine for me.

**Comment by alextwothousand** [comment]
> Can't confirm on 2.1-dev32. The event works fine for me.

Possibly an issue with the rc/release branch? I will try dev today and see whether the event is called or not.

**Comment by LeonMrBonnie** [comment]
If this is only on rc/release this issue can be closed, because dev is the newest version and if it's fixed in dev, it will be fixed in the other branches.

**Comment by alextwothousand** [comment]
> If this is only on rc/release this issue can be closed, because dev is the newest version and if it's fixed in dev, it will be fixed in the other branches.

IF it is, then I will close this issue.

**Comment by alextwothousand** [comment]
> If this is only on rc/release this issue can be closed, because dev is the newest version and if it's fixed in dev, it will be fixed in the other branches.

Here is my playerDisconnect event.

```js
alt.on("playerDisconnect", (player) => {
	console.log("you are a nerd");
	(async () => {
		console.log("player is disconnected");

		alt.emitClient(player, "menu:pause"); // Stop the menu music, if it is playing.
		alt.emitClient(player, "account:destroy"); // Destroy the account webview.
	
		let db;
	
		try {
			db = await getConnection();
	
			let p = cache.player.getAccount(player);
	
			db.query("UPDATE accounts SET username = ?, admin = ?, helper = ?, score = ?, money = ?, tester = ?, language = ? WHERE id = ?", 
				[player.name,  p.admin, p.helper, p.score, p.money, p.tester, p.language, p.dbid]
			);
	
			console.log(chalk.bold.green("Account save successful!"));
		} catch(_) {
			console.log(chalk.bold.red("Failed to save account for " + player.name));
		} finally {
			if (db) db.release();
		}
	
		pool.setFreeId(player.getSyncedMeta("pID")); // Free up the ID.
		player.kick(); // Kick the player.
	});
});
```

What I've realised is it absolutely does not like asynchronous functions. They are not called at all. However, my code outside of the async function is called fine.

I'm going to try a workaround I have in mind. I'll let you know how it goes

**Comment by LeonMrBonnie** [comment]
Uh. Your code will not work anywhere, as you are only defining a anonymous function but do not call it lol.
You can define the handler function as async directly, you don't need to do what you are doing there.

**Comment by alextwothousand** [comment]
> Uh. Your code will not work anywhere, as you are only defining a anonymous function but do not call it lol.
> You can define the handler function as async directly, you don't need to do what you are doing there.

I did that, and it refuses to be called. But alt.emit as a workaround appears to work.

**Comment by alextwothousand** [comment]
```js
alt.on("playerDisconnect", async (player) => {
	console.log("you are a nerd");
	console.log("player is disconnected");
	console.log(player);

	let db;

	try {
		console.log("creating database handle");
		db = await getConnection();

		console.log(player);
		let p = cache.player.getAccount(player);

		await db.query("UPDATE accounts SET username = ?, admin = ?, helper = ?, score = ?, money = ?, tester = ?, language = ? WHERE id = ?", 
			[player.name,  p.admin, p.helper, p.score, p.money, p.tester, p.language, p.dbid]
		);

		alt.emitClient(player, "menu:pause"); // Stop the menu music, if it is playing.
		alt.emitClient(player, "account:destroy"); // Destroy the account webview.

		pool.setFreeId(player.getSyncedMeta("pID")); // Free up the ID.
		player.kick(); // Kick the player.

		console.log(chalk.bold.green("Account save successful!"));
	} catch(_) {
		console.log(chalk.bold.red("Failed to save account for " + player.name));
	} finally {
		if (db) db.release();
	}
});
```

```
(node:1660) UnhandledPromiseRejectionWarning: Error: entity is invalid
    at file:///C:/Users/alex/game/resources/pilotslife/server/events/playerDisconnect.js:36:69
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at emitWarning (internal/process/promises.js:120:15)
    at processPromiseRejections (internal/process/promises.js:168:7)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
(node:1660) Error: entity is invalid
    at file:///C:/Users/alex/game/resources/pilotslife/server/events/playerDisconnect.js:36:69
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1660) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:134:13)
    at emitWarning (internal/process/promises.js:127:3)
    at processPromiseRejections (internal/process/promises.js:168:7)
    at processTicksAndRejections (internal/process/task_queues.js:90:32)
```

**Comment by alextwothousand** [comment]
All is well.
It appears to work on the dev branch.
