### ISSUE TITLE
alt.Player.local.scriptID different values

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#715]
**Client/server version**
`Build 2.1-dev32`

**Current behavior**
Alt.Player.scriptID is differs when storing it on resource-start compared to receiving it later.
Using the scriptID, which has been stored on resource-start doesnt work with natives.
Using the scriptID, which has been loaded in e.g. events works fine.

**Expected behavior**
Alt.Player.scriptID should be the same.

**Steps to reproduce**
```
import * as alt from "alt";
var playerPed = alt.Player.local.scriptID;

alt.on("keyup", (key) => {
  alt.log("PlayerPed is set to ", playerPed); // <--- this scriptID doesn't work with natives
  const playerScriptId = alt.Player.local.scriptID; // <--- this scriptID is valid, native calls works
  alt.log("ScriptId is ", playerScriptId);
});
```

**Context (environment)**
Implementing/Using setPedComponentVariation

**Possible solution**

**Comment by LeonMrBonnie** [comment]
This is normal, because your script id changes every time you get assigned a new model.
Just access the scriptID property directly instead of storing it once.
