### ISSUE TITLE
Player Data not available from other files in same resource

### ISSUE THREAD

**Issue by Michael-xT** [altmp/altv-issues#716]
**Server version**
`Build #1301, branch release`

**Current behavior**
So, basically when a player connects he follows this steps:
Login -> Character Selection -> Spawn
When Spawning I save some of the character's data on player, all good!
When disconnecting I am calling two functions ( as a test, before I had just one ) and the following thing happens:
In one file ( playerConnect file ) I am logging player's data as `JSON.stringify` and this pops up:
```
[20:56:03] Disconnect PConnect {"Admin":10,"characterID":"5fb62dcc6a59871184971270","accountID":"5fb6294baa2cff42108f63b6","inProgress":false,"IsConnected":true,"hoursInterval":0}
```
and in the other file ( default player disconnect event file ) I am logging again player's data.
this time in the console I get this:
```
[20:56:03] Disconnect
[20:56:03] {}
```

**Expected behavior**
Well, basically in both my files I have the same event, called at the same time, both events should print player's data.

**Steps to reproduce**
In Player Disconnect event file:
```
alt.on('playerDisconnect', (player)=>{
    alt.log('Disconnect');
    alt.log(JSON.stringify(player));
});
```
In playerConnect ( the same file where all the data is being saved on player ):
```
alt.on('playerDisconnect', (player) => {
    alt.log('Disconnect PConnect ' + JSON.stringify(player));
});
```

**Context (environment)**
This strange bug happens randomly, as sometimes everything works as intended.

**Possible solution**
I cannot tell what is the issue, the certain thing is that: both files are in the same Resource, even the same folder (if this info helps) and both of them are being imported when my db driver is ready, as : 
```
Mongo.onReady(() => {
    import('./events/playerConnect.mjs');
    import('./events/playerDisconnect.mjs');
});
```
P.S. I am going to test this on dev branch asap.

**Comment by LeonMrBonnie** [comment]
I can not reproduce this on 2.1-dev35.

**Comment by AteshM** [comment]
Tested it again right now on
2.1-dev35 (dev), same results.

**Comment by AteshM** [comment]
After some additional digging, i found out that, setting Meta will resist, even if player.data wont, 4 example, by adding this 
```
            player.setMeta('dataz', JSON.stringify(player));
```
and then printing the `player.getmeta` of dataz, I get the data, even if I dont get any data with normal `JSON.stringify(player)`

**Comment by deluvas1911** [comment]
can't confirm this, neither on current release nor current rc
