### ISSUE TITLE
getGxtText returns undefined.

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#717]
**Client/server version**

`2.1-dev35 `

**Current behavior**

getGxtText returns undefined breaking some libs like nativeUI (create menu > close > open again (annnnd... hud is bugged))
**Expected behavior**

It should work normally and return correct values.

**Steps to reproduce**

```
let test = alt.getGxtText("HUD_INPUT2");
alt.log(test);
```

**Comment by martonp96** [comment]
fixed
