### ISSUE TITLE
Blinkers are not visible to other players (sync)

### ISSUE THREAD

**Issue by Firjens** [altmp/altv-issues#718]
**Client/server version**

`Build #1301, branch rel`

**Current behavior**

When activating your blinkers using the native `setVehicleIndicatorLights`, it's only visible to the person who activated it, other players who are around you do not see the blinker.

**Expected behavior**

The blinkers should be visible to anyone in streaming range.

**Steps to reproduce**

Enable a vehicles blinker using the native `setVehicleIndicatorLights`. Other players cannot see it.

**Comment by C0kkie** [comment]
There is already a issue for that https://github.com/altmp/altv-issues/issues/76

**Comment by Firjens** [comment]
Ah, my bad, I used the search function but no results came up.

**Comment by Lhoerion** [comment]
Duplicate of #76
