### ISSUE TITLE
StreamSyncedMetaData can't be altered when vehicle is spawned

### ISSUE THREAD

**Issue by Firjens** [altmp/altv-issues#719]
**Client/server version**

`Build #1301, branch release`

**Current behavior**

You can set a vehicles `StreamSyncedMetaData` when it spawns, but you are unable to edit it afterwards, when trying to edit it after it has spawned it'll return the initial value.

**Expected behavior**

You should be able to edit a vehicle's synced meta even when it has already spawned.

**Steps to reproduce**

1. Set a vehicle's meta on spawn.
2. Change the meta after some time a vehicle has spawned.
3. Get the meta via GetStreamSyncedMetaData, the meta data will be the same to the initial meta data.

**Context (environment)**

**Possible solution**

**Comment by Firjens** [comment]
I'll be providing some super simplified code to help explain this problem..

```C#
/// Run on initial spawn of vehicle
vehicle.SetStreamSyncedMetaData("value", 0);

// This can be run after the vehicle has spawned.
vehicle.SetStreamSyncedMetaData("value", 1);
vehicle.GetStreamSyncedMetaData("value"); // This will still return 0
```

**Comment by FabianTerhorst** [comment]
Stream synced meta data is saving int's as long.

**Comment by Firjens** [comment]
I'm going to close this issue. Storing values in `int` will not work, use `long` instead
