### ISSUE TITLE
Add Player.tabbedOut property

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#725]
**Suggestion**

Add player.tabbedOut getter to know if a player's game is minimized
**Use cases**

Marking minimized players with something overhead or making them invincible or etc so players can interact peacefully, also can be useful for chatting and pms so the other players know the player x is not ignoring them or etc and just has his game minimized. 

**Describe the solution you'd like**

Add player.tabbedOut (server+cllient?) getter that returns true/false

**Describe alternatives you've considered**

Ringing the players on their home telephones and sending faxes.

**Comment by 7Hazard** [comment]
Added in dev
