### ISSUE TITLE
Add a server variable to be able to set timeout threshold

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#726]
**Suggestion**

Add a server variable to be able to set timeout threshold
**Use cases**

Adjust the timeout according to owner's preferences and for other testing purposes 
**Describe the solution you'd like**

Add a server variable in server.cfg ie:` timeout: 15000 `(may also be edited thro a property like alt.timeoutLimit)

**Comment by martonp96** [comment]
this already exists in server cfg as `timeout`
