### ISSUE TITLE
MapZoomData is unimplemented

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#727]
**Client/server version**
`Build #2.1-dev58, branch dev`

**Current behavior**
```
[14:33:50][Error] [V8] Exception at client:.client.bundle.esm.js:19947
[14:33:50][Error]       const ZOOM_LEVEL_0 = alt.MapZoomData.get('ZOOM_LEVEL_0');
[14:33:50][Error]   TypeError: Cannot read property 'get' of undefined
```

**Expected behavior**
Should be working like before.

**Steps to reproduce**
```
const ZOOM_LEVEL_0 = alt.MapZoomData.get('ZOOM_LEVEL_0');
ZOOM_LEVEL_0.fZoomScale = 0;
ZOOM_LEVEL_0.fZoomSpeed = 0;
ZOOM_LEVEL_0.fScrollSpeed = 0;
ZOOM_LEVEL_0.vTilesX = 0.0;
ZOOM_LEVEL_0.vTilesY = 0.0;
```

**Context (environment)**
Using MapZoomData to replace default map.

**Comment by LeonMrBonnie** [comment]
https://github.com/altmp/altv-client-js/blob/master/src/bindings/Main.cpp#L711
It seems this was commented out for some reason.

**Comment by martonp96** [comment]
fixed
