### ISSUE TITLE
Add vehicle.dead and vehicle.repair()

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#728]
**Suggestion**

Add vehicle.dead property and vehicle.repair() method

- [ ] `dead` property
- [X] `repair` method

**Use cases**

Repair vehicles or revive dead vehicles

**Describe the solution you'd like**

Add vehicle.dead property and vehicle.repair() method

**Comment by LeonMrBonnie** [comment]
Fixed in 1.2-dev61.

**Comment by martonp96** [comment]
you don't need vehicle.dead property, you can just reset the netowner and it will be undrivable
