### ISSUE TITLE
C# Alt.CreateVehicle no return value

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#729]
**Client/server version**
`Build #2.1dev-59, branch dev`

**Current behavior**
When using `Alt.CreateVehicle` on start up of the server, when there is no player connected, there is no return value.
If you using the method as a player on the server there is no problem and the right return value.
This worked up to version 2.1dev-56.

**Expected behavior**
Should be return the vehicle value like before upto version 2.1dev-56,

**Steps to reproduce**
Using the method on Server Startup with no connected player:

```
var gameVehicle = Alt.CreateVehicle(vehicle.Hash, vehicle.Position, vehicle.Rotation);
return gameVehicle;
```

Variable `gameVehicle` is `null`.

**Context (environment)**
Using the return value for other tasks and methods.

**Comment by Hardy535** [comment]
This also seems to happen with ColShapes, also returns NULL since some of the last versions.

**Comment by FabianTerhorst** [comment]
fixed in latest dev package
