### ISSUE TITLE
[Bug] NPC's spawning

### ISSUE THREAD

**Issue by GangstaSunny** [altmp/altv-issues#73]
## Expected Behavior
Not spawning NPC's.

## Current Behavior
NPC's will spawn as soon as a player will come to the stream radius of a police car.

## Possible Solution
i.d.k

## Steps to Reproduce
1. Spawn a police car on the LSPD at server start
1. Goto the LSPD (flying or teleport)
1. See the bot

## Context (Environment)
-

## Detailed Description
https://www.youtube.com/watch?v=aDM3s2NDzsE&feature=youtu.be

## Possible Implementation
-

**Comment by yoranjj** [comment]
I've had this happen to me as well, it sometimes happens when you use /reconnect/.

**Comment by FabianTerhorst** [comment]
Can you check if its still happening with latest version?
