### ISSUE TITLE
Setting Vehicle.EngineOn results into exception 

### ISSUE THREAD

**Issue by kineese** [altmp/altv-issues#731]
**Client/server version**
`c# based server 2.1-dev63 (dev)`

**Current behavior**
Setting the Vehicle.EngineOn serverside results into a AccessViolationException.
**Expected behavior**
Should set the engine w/o exception (worked on prior versions).

**Steps to reproduce**
```
var vehicle =  new AltV.Net.Elements.Entities.Vehicle((uint)VehicleModel.Adder, Position.Zero, Rotation.Zero);
lock(vehicle){
  vehicle.EngineOn=true;
}
```
**Context (environment)**
I try to start my already runnable server ;) Using Async Ressource

**Possible solution**
Dont call that method

**Comment by Revyn112** [comment]
Could be linked with issue #729

**Comment by FabianTerhorst** [comment]
Please check again on e.g. rc with the correct incremented sdk version.

**Comment by C0kkie** [comment]
Do you still have the problem? @kineese

**Comment by kineese** [comment]
Nope! Seems to be fixed. Thx
