### ISSUE TITLE
Add a vehicle.passengers getter

### ISSUE THREAD

**Issue by SokratesMir** [altmp/altv-issues#733]
**Suggestion**
Since you can already get the driver of a vehicle, it would be great to also get the a list/array of passengers inside the vehicle.

**Use cases**
Do special things with the passengers of a vehicle, like dimension change or remove a weapon etc.

**Describe the solution you'd like**
A simple getter of the players inside a vehicle.

**Describe alternatives you've considered**
Just having an extension for the vehicle, that adds/removes players when entering and/or leaving the game.
But a support from altv side would be much greater

**Additional context**
Nothing additional

**Comment by FabianTerhorst** [comment]
In my opinion i would recommend people to do it inside enter exit event themself. In some runtimes it would at least be faster then calling the getter from the sdk.

**Comment by martonp96** [comment]
You can get passengers easily with the modules.
