### ISSUE TITLE
model getter returns 0

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#735]
**Client/server version**

`Build #dev/2.1-dev65, branch dev`

**Current behavior**
alt.Player.local.model returns 0

**Expected behavior**
That it tells the current modelhash

**Steps to reproduce**
Just use alt.log(alt.Player.local.model)

**Comment by tastydev** [comment]
*also returns 0 on remote players

**Comment by C0kkie** [comment]
Fixed in dev/2.2-dev1
