### ISSUE TITLE
Blip size/scale setter does not work

### ISSUE THREAD

**Issue by localcc** [altmp/altv-issues#736]
**Client/server version**
`Build 2.1-rc1, branch rc`

**Current behavior**
Blip doesn't change size

**Expected behavior**
Blip should change size

**Steps to reproduce**
1. Create alt.PointBlip
2. Try to change it's scale/size
Code that doesn't work:
```
const p = alt.Player.local.pos;
var blip = new alt.PointBlip(p.x, p.y, p.z);
blip.scale = 0.1;
blip.size = 0.1;
```
Code that does work:
```
const p = alt.Player.local.pos;
var blip = native.addBlipForCoord(p.x, p.y, p.z);
native.setBlipScale(blip, 0.1);
```
3. Nothing happens

**Context (environment)**
Trying to change blip size

**Comment by martonp96** [comment]
blip.scale was removed and size takes an object with an x, y property where x and y is the width and height respectively. 
So: blip.size = { x: 0.1, y: 0.1 };
