### ISSUE TITLE
Server doesn't exit probably on linux (exit or ctrl+c)

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#739]
**Client/server version**

` alt:V Server 2.1-dev65 (dev)`

**Current behavior**

Server doesn't exit probably on linux (exit or ctrl+c)

**Expected behavior**

For it to exit probably
**Steps to reproduce**

Try to exit the server using 'exit' or press ctrl c

**Possible solution**

killall -9 altv-server

**Comment by C0kkie** [comment]
Will be fixed in dev/2.2-dev3
