### ISSUE TITLE
Add clientside interior api

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#740]
**Suggestion**

Add a clientside interior API

**Use cases**

Detect what interior the player is in. Ex: shops, tunnels, interiors, banks and etc.
Can be used to detect interior changes, current interior to start missions or do different functions only if you are inside interior id xx

**Describe the solution you'd like**

`player.interior` getter
`playerChangedInterior` event

**Comment by martonp96** [comment]
The issue will be tracked in #522.
