### ISSUE TITLE
alt.hash("model") returns the wrong value

### ISSUE THREAD

**Issue by katsutosh** [altmp/altv-issues#741]
**Client/server version**
`Build #2.2-rc2, branch rc` on linux

**Current behavior**
alt.hash('Ratloader') returns the wrong modelhash (on client- & server-side)

**Expected behavior**
returns the correct modelhash

**Steps to reproduce**
alt.log(alt.hash('Ratloader'));
returns -667151410 but it should return 3627815886

**Context (environment)**
just hash the vehiclemodel

**Possible solution**
-

**Comment by LeonMrBonnie** [comment]
`alt.hash` is working fine, some hashes in the wiki are just outdated.

**Comment by katsutosh** [comment]
in release-branch is the return value from alt.hash, native getHashKey('ratloader'), player.vehicle.model the same (Unsigned-hash)
now in RC is the return value different from alt.hash and native.getHashKey / .model

alt.hash return the signed-hash instead of the unsigned-hash
hash checked with: https://emcifuntik.github.io/joaat/jooat/

**Comment by martonp96** [comment]
fixed
