### ISSUE TITLE
playerWeaponChange getts called while switching weapon in vehicle

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#743]
**Client/server version**
`Build #2.2-dev1, branch dev`

**Current behavior**
If you sit in a vehicle and justing switching through the weaponwheel (not equip it) it calls the event everytime while switching.

**Expected behavior**
It should only get triggered if the weapon got equipped like if you are not in a vehicle

**Steps to reproduce**
Create logs serverside for the playerWeaponChange event
go into a vehicle
switch through the weaponsheel
check logs

**Comment by LeonMrBonnie** [comment]
Pretty sure this is intentional, because you ARE switching to that weapon.
I also don't see a reason why this should be removed.
It could be abused by cheaters knowing the anticheat is using that event for verifying weapons, and then the cheater could switch the weapon in the car and use it.

**Comment by C0kkie** [comment]
if you are outside of a vehicle, it only gets called when the weapon gets equipped. Only in veh is it different

**Comment by LeonMrBonnie** [comment]
That is still probably intented behaviour because you can't use the weapon wheel in the vehicle like when you are on foot.

**Comment by C0kkie** [comment]
As it is a GTA behavior its not fixable
