### ISSUE TITLE
Add a client side getter to return only streamed vehicles 

### ISSUE THREAD

**Issue by Hershef** [altmp/altv-issues#745]
**Suggestion**

Add a client side getter to return an array/object of only streamed vehicles 
**Use cases**

Quickly loop thro nearest vehicles without actually bothering with global loops which may contain thousands
**Describe the solution you'd like**

Add something like alt.Vehicle.streamedIn to return an array/object 
**Describe alternatives you've considered**

**Additional context**

**Comment by LeonMrBonnie** [comment]
See https://github.com/altmp/altv-issues/issues/747
