### ISSUE TITLE
The requested module 'alt-server' does not provide an export named 'VehicleLockState' | Enum not useable

### ISSUE THREAD

**Issue by its4l3x** [altmp/altv-issues#746]
**Client/server version**
`Build #rc/2.2-rc3, branch rc`

**Current behavior**
When i'm trying to build the Server with the altV Typescript-Types and Using for example alt.VehicleLockState Enum, the Server will throw an Error: https://pic.its4l3x.de/share/chrome_g61xNyPlYA.png

**Expected behavior**
The Server should build normally and not throw any error

**Steps to reproduce**
User alt.VehicleLockState Types for setting the vehicle Lock State

**Context (environment)**
Throws an Error when Using this type, so Server isnt able to start.

**Possible solution**
Make own Typescript Enums of this, but anyway - typescript (vscode) marked this as an error because it is not assignable to this type. Because of that, we want to use the official altV Types.

**Comment by LeonMrBonnie** [comment]
Enums are not supported by JavaScript. 
If you want to use enums you have to use TypeScript and transpile your code.

**Comment by tastydev** [comment]
thats what hes trying tom do @LeonMrBonnie

**Comment by its4l3x** [comment]
We are using Typescript... @LeonMrBonnie

**Comment by LeonMrBonnie** [comment]
Then there is something wrong with your TypeScript config.
Anyway problems with the typings do not belong in this repository, you should report this here: https://github.com/altmp/altv-types

**Comment by its4l3x** [comment]
... I should try to report in a Repo where i can't report an issue? Nice...

And here's our tsconfig. I didnt see any problems there.

https://pic.its4l3x.de/share/Code_obMbZMdn0l.png

**Comment by LeonMrBonnie** [comment]
Set `preserveConstEnums` to false.

**Comment by Lhoerion** [comment]
When you add tsconfig entries without deeper understanding, then yes there's a problem 🤔

**Comment by its4l3x** [comment]
@LeonMrBonnie Didn't helped. Same issue as mentioned

**Comment by its4l3x** [comment]
Found a solution:

Didnt changed anything in the TSConfig

I've changed the imports in the specific module: 
import * as alt from 'alt-server';
const { VehicleLockState } = alt;


vehicle.lockState = VehicleLockState.Locked;

This is working, without throwing an Error at startup

**Comment by Lhoerion** [comment]
@its4l3x `VehicleLockState` is a const enum, default TypeScript behaviour is to remove them at the compile time, as they're replaced with the values from the fields.
Your "solution" even if works, it's an abberation.
