### ISSUE TITLE
Add possibility to get streamed in entities for player

### ISSUE THREAD

**Issue by Chris0x** [altmp/altv-issues#747]
**Suggestion**

Add a function/property to get all current streamed in players for a player
**Use cases**

When you want to emit an event but dont want to iterate through all players, this should be the way to go
**Describe the solution you'd like**

I think alt:V already caches somehow these players, so make them available
**Describe alternatives you've considered**

client.EmitInRange(event, args...)
**Additional context**

/

**Comment by C0kkie** [comment]
Also on clientside it would be usefull to only get players in range

**Comment by LeonMrBonnie** [comment]
This should just be added to the C++ SDK as a shared method. Because this would be useful on both client- and serverside.

**Comment by zziger** [comment]
It would be actually nice to have something like alt.Player.streamedIn or alt.Vehicle.streamedIn. It would allow to e.g. render nametags / find nearest player more efficiently

**Comment by LeonMrBonnie** [comment]
You can use the `gameEntityCreate` and `gameEntityDestroy` event to keep track of streamed entities already.

**Comment by zziger** [comment]
I actually do this rn to render nicknames, but i think this is something that would be nice to have in altv itself

**Comment by LeonMrBonnie** [comment]
This was discussed for a long time but ultimately decided against, like I mentioned you can keep track of this yourself using the aforementioned events.

**Comment by LeonMrBonnie** [comment]
Available as `alt.Player.streamedIn` etc. on clientside in newest dev
