### ISSUE TITLE
Lodlight ymap/ymap problem.

### ISSUE THREAD

**Issue by Kmz-rash** [altmp/altv-issues#749]
**Client/server version**

`Build #1301, branch release`

**Current behavior**

When you try to steam lodlight ymap it doesn't work 
small gyazo to show you current lodlight that should be removed https://gyazo.com/ef1e37e917a52d9f83ff3a810f7b70b2
Name is the same as gta one, it's just a replacement so idk why it isn't working

**Expected behavior**

being able to stream edited lodlight files. result should be like this (fivem version) https://gyazo.com/b974c5ee2c1271619d984094e9a5af93

**Steps to reproduce**

Make a friend request to Gabz (Gabz#0710) to get files version, he will give them to admin of alt:v for testing purpose.

**Context (environment)**

It's a problem that is only related to Alt:v idk why it doesn't stream correctly.
The same thing happen sometimes with custom ymaps that work on FiveM but doesn't on Alt:V (exemple would be Gabz christmas ymap).

**Comment by martonp96** [comment]
Are you using `<flags value="0"/>` in the ymap?

**Comment by Kmz-rash** [comment]
Gabz told me that lodlight are <flags value="2"/>

**Comment by martonp96** [comment]
Okay thank you for the reply.

**Comment by Kmz-rash** [comment]
with flag 0 btw: https://gyazo.com/5aa702f76a7d308c377968183b51037d

**Comment by Kmz-rash** [comment]
Gabz is on something i'll close the issue if his finding solves the problem (basicly since alt:V is on the last DLC, lods that he made where the one from FiveM and there are not from the same DLC as alt:V)

**Comment by Kmz-rash** [comment]
Problem solved he was using lod from previous DLC, it's working with current DLC LOD
