### ISSUE TITLE
Change Server-Permission "Screen Capture" Text

### ISSUE THREAD

**Issue by fiftyy** [altmp/altv-issues#750]
**Suggestion**
With the new server permission "Screen Capture", some users think that the server will capture their whole pc.
Because it really sounds like that.
![unknown](https://user-images.githubusercontent.com/20678496/102079889-c9702900-3e0d-11eb-8df8-00252e5a2776.png)

**Use cases**
Simple explanation so that no user is afraid

**Describe the solution you'd like**
Change the Text to something like "Game Window Capture".
And maybe add a tooltip on it to display an extra-text with a small explanation

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 7Hazard** [comment]
Perhaps game capture would be more fitting

**Comment by FabianTerhorst** [comment]
I could add a I and when you click on it it opens a dialog that explains the permission.

**Comment by FabianTerhorst** [comment]
Or i create a tooltip component, since thats the first place where we actually need it.

**Comment by fiftyy** [comment]
> Or i create a tooltip component, since thats the first place where we actually need it.
Tooltip Component would be okay i think.

**Comment by C0kkie** [comment]
Should be better in dev/14.0-dev13
