### ISSUE TITLE
After using HandlingData.getForHandlingName game crashed

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#751]
**Client/server version**

`Build #2.2-rc8, branch rc`

**Current behavior**
Game Crashed after connect by using HandlingData.getForHandlingName.

**Expected behavior**
Want to get in JavaScript the HandlingData for vehicle model

**Steps to reproduce**
Run the following in the `[AsyncClientEvent("player:ready")]` event
```
let modelHash = native.getHashKey("SOME_HANDLING_ID")
let result = alt.HandlingData.getForHandlingName(modelHash);
```

**Comment by FabianTerhorst** [comment]
Please provide exact clientside code to reproduce with same data used.

**Comment by Doxoh** [comment]
On C#:
```
        [AsyncClientEvent("player:ready")]
        public async Task OnPlayerReadyAsync(IGamePlayer player)
        {
        this.EmitLocked("doSomeThing", someparameter);
}
```

On Javascript:
```
import * as alt from 'alt-client'

function doSomeThing(someparamter: string){
        let modelHash = native.getHashKey(someparamter)
        let result = alt.HandlingData.getForModel(modelHash);
        //Do something with result
}

alt.onServer('doSomeThing', this.doSomeThing);
```

**Comment by tastydev** [comment]
is there a possibility that u use a bad wrong string etc? I can´t reproduce it´s working on rc with ~100 handling names

**Comment by tastydev** [comment]
also u are using the wrong function snippet

**Comment by Doxoh** [comment]
oh yes, so sorry. I have updated the snippet.
No, with the Old function getForModel I didnt get these exception

**Comment by Doxoh** [comment]
@tastydev I tried again.
With `getForModel` I got "Error: Model does not exist". With `getForHandlingName` it crashed immediately

**Comment by tastydev** [comment]
That´s why the function got renamed it is the handlingName and not the model. So the function works but it still shouldn´t crash on wrong handlingNames

**Comment by Doxoh** [comment]
@tastydev yes, I use the hash of handlingName as paramter. Can you check why its crashed by wrong handlingName?

**Comment by tastydev** [comment]
what name and vehicle do u use?

**Comment by Doxoh** [comment]
@tastydev Custom vehicle with custom handlingname

**Comment by martonp96** [comment]
fixed in rc
