### ISSUE TITLE
player.setDateTime() seems to override alt.setMsPerGameMinute()

### ISSUE THREAD

**Issue by Moondarker** [altmp/altv-issues#753]
**Client/server version**
`Build #2.2-RC8, branch rc` (both client and server)

**Current behavior**
When time is set from server-side using `player.setDateTime()`, game time speed modifier set by client-side method `alt.setMsPerGameMinute()` gets reset to default value

**Expected behavior**
`player.setDateTime()` shouldn't affect whatever value was set using `alt.setMsPerGameMinute()` (it was working this way before RC8)

**Steps to reproduce**
Code to repro, client:
```
alt.on('connectionComplete', () => {
	alt.setMsPerGameMinute(5);
});
```

Code to repro, server:
```
import chat from 'chat';

chat.registerCmd("setTime", (player, args) => {
    let startTime = new Date();

    alt.Player.all.forEach((player) => {
        if (!player || !player.valid) return;

        player.setDateTime(startTime.getDate(), startTime.getMonth(), startTime.getFullYear(),
                parseInt(args[0] || 0), parseInt(args[1] || 0), parseInt(args[2] || 0));
    });
});
```

Then use `/setTime 8` command in chat

**Context (environment)**
A lot of gamemodes work this way, first setting the multiplier, then sending game time (as it was always working up until RC8)

**Possible problem**
Seems like setDateTime handler now also calls the multiplier native for some reason or calls it with wrong value?

**Comment by tastydev** [comment]
can confirm

**Comment by Arochka** [comment]
Got the same issue on release

**Comment by Doxoh** [comment]
can confirm too

**Comment by C0kkie** [comment]
Its already fixed in dev, wait for the next update
