### ISSUE TITLE
[2.2-rc9] CDN Error: HTTP Request failed, curl code: 52

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#754]
**Client/server version**
`Build #2.2rc-9`

**Current behavior**
Using CDN with RC didn't worked.
Console Error:
```
HTTP Request failed, curl code: 52
```

Using Curl under windows terminal worked without any issue:
```
PS C:\Users\Revyn112> curl http://test.cdn.net:80/connect.json

StatusCode        : 200
StatusDescription : OK
Content: 
{"files":[{"hash":"484c0005fb76278d","name":"ascas"},{"hash":"e4461449569ca313","name":"asc-fasc-asc"},"hash":"586312f2406099f0","name":"asc-asc-asc"},{"hash":"846ee56fa2d39527",...
```

**Expected behavior**
Connect to CDN, download resources and everything like intended.

**Steps to reproduce**

server.cfg
```
useCdn: true
cdnUrl: "http://test.cdn.net:80/"
```

**Comment by FabianTerhorst** [comment]
What did you enter in direct connect window?

**Comment by Revyn112** [comment]
Yeah used the server ip and port, not the cdn url - little bit confused about the terms.
