### ISSUE TITLE
Ability to save files

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#755]
**Suggestion**
Add a way to save files (or only images) locally on player's pc.

**Use cases**
I think main usage of this feature is saving screenshots, so maybe it can be restricted to saving only pictures.
Its very helpful feature, and with new screenshot api it gives ability to create a screenshot editor ingame.

**Describe the solution you'd like**
Maybe some kind of "File Save" permission?

**Describe alternatives you've considered**
Now user needs to screenshot his game window manually.

**Comment by ZackaryH8** [comment]
This could be subject  to abuse right? Like spam saving images to someone's local machine

**Comment by 7Hazard** [comment]
No programatic API will be provided to save files directly to a user's file system. If you want to do advanced processing and storage, do so through your servers.
