### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by PepoDance** [altmp/altv-issues#757]
**Client/server version**
`Build #2.2-rc10 (rc), release candidate`

**Current behavior**
The timers console command outputs nothing now.
```
================ Timers benchmark info ===============
======================================================
```

**Expected behavior**
Should display the timers a specific resource has.

**Steps to reproduce**
1. Type in console `timers`.

**Comment by LeonMrBonnie** [comment]
Fixed on newest dev
