### ISSUE TITLE
Problem streaming custom assets/ymap

### ISSUE THREAD

**Issue by Kmz-rash** [altmp/altv-issues#759]
**Client/server version**

build #1302, branch release

**Current behavior**
Cannot stream the content of this resource, it's only a simple ymap/ytyp and customs assets. It's working in FiveM and rage but not here on alt:V.
I tried to rename ymap name to see if this was the problem but only one was working.

**Expected behavior**
it should work and display this https://www.gabzv.com/products/christmas-update

**Steps to reproduce**
[gabzxmas.zip](https://github.com/altmp/altv-issues/files/5720867/gabzxmas.zip)
here is the resource to test.

**Context (environment)**
Well this is a big issue for modders if simple ymap doesn't work.

**Possible solution**
i'v try to rename the ymap with a different name it was only working for one of the ymap but it's weird.

**Comment by C0kkie** [comment]
Did you try to rename the _manifest.ymf to manifest.ymf?

**Comment by C0kkie** [comment]
Also if you try to open the ytyp file on codewalker it throws error, so maybe thats why altv cant also read it cuz the file is broken

**Comment by Kmz-rash** [comment]
Gabz told me it's normal that codewalker can't read the ytyp

**Comment by Revyn112** [comment]
> 
> 
> Did you try to rename the _manifest.ymf to manifest.ymf?

what is the logic behind this? never had problems with _manifest.ymf before.
Also have this problem with this package in latest release 2.3

**Comment by deluvas1911** [comment]
@C0kkie Confirmed

**Comment by C0kkie** [comment]
Its the same issue like #722
