### ISSUE TITLE
Sync setVehicleIndicatorLights native function

### ISSUE THREAD

**Issue by Prakkkmak** [altmp/altv-issues#76]
**Is your feature request related to a problem? Please describe.**
Turn light ( indicators ) are not synced.

**Describe the solution you'd like**
I want make native turn light (indicator) synced between clients

**Describe alternatives you've considered**
Make possible to emit to all client in client side script

**Comment by FabianTerhorst** [comment]
Post the native calls you used here is as well.

**Comment by Prakkkmak** [comment]
game.setVehicleIndicatorLights

**Comment by jesst3r** [comment]
the same, visible only locally
`let veh = alt.Player.local.vehicle;
if(veh) {
    const vehId = veh.scriptID;
    game.setVehicleIndicatorLights(vehId, 0, true);
    game.setVehicleIndicatorLights(vehId, 1, true);
    
}
`

**Comment by C0kkie** [comment]
Is there any update maybe?

**Comment by C0kkie** [comment]
Will  be tracked here: https://github.com/altmp/altv-issues/issues/737
