### ISSUE TITLE
[Core / Client] Missing 2 Natives in release branch or an invoke function

### ISSUE THREAD

**Issue by DerEnderman** [altmp/altv-issues#760]
**Client/server version**

`Build #1302, branch release`

**Current behavior**

They are missing natives + a invoke method
 Requested Natives : 0x9A9D1BA639675CF / 0x5E1460624D194A38
**Expected behavior**

There should a native for it to be able to load new map in gta v

**Steps to reproduce**

```js
let pCoords = game.getEntityCoords(alt.Player.local.pos, -1);
let distance1 = game.getDistanceBetweenCoords(pCoords.x, pCoords.y, pCoords.z, 4840.571, -5174.425, 2.0, false);

function checkIslandPosition() {
    if(distance1 < 2000) {
        game.InvokeNative("0x9A9D1BA639675CF1", "HeistIsland", true); # load the map and removes the city
        game.InvokeNative("0x5E1460624D194A38", true); # load the minimap/pause map and removes the city minimap/pause map
    } else {
        game.InvokeNative("0x9A9D1BA639675CF1", "HeistIsland", false);
        game.InvokeNative("0x5E1460624D194A38", false);
    }
}
```

**Context (environment)**

This missing natives is stopping from entering the new island because you will not able to switch it
**Possible solution**

None

**Comment by martonp96** [comment]
The problem will be solved when rc will be merged into release.

**Comment by DerEnderman** [comment]
ah means the natives are already in rc? can you tell me the names of it that i can play around with?

**Comment by Lhoerion** [comment]
They should be accessible through their assigned guessed name
```
0x9A9D1BA639675CF1 ->_SET_ISLAND_HOPPER_ENABLED
0x5E1460624D194A38 ->_SET_TOGGLE_MINIMAP_HEIST_ISLAND
```
