### ISSUE TITLE
Native getFinalRenderedCamRot emitted to webview returns NULL

### ISSUE THREAD

**Issue by GVMP** [altmp/altv-issues#762]
**Client/server version**
RC

**Current behavior**
Emitting the data type of getFinalRenderedCamRot to a webview returns null.

**Expected behavior**
The data type should be serialize into an object.

**Steps to reproduce**
let rot = native.getFinalRenderedCamRot(0);

webview.emit('bla', rot); // Rot is defined and looks like valid xyz object

alt.on('bla', (rot) => {
console.log('Rotation: ' + rot); // NULL
});

**Context (environment)**

**Possible solution**
Convert the data type to an object.

**Comment by LeonMrBonnie** [comment]
This is because that native returns a Vector3 instance, and WebView does not have the Vector3 class.
Convert it to an object containing x, y, z yourself or send it seperately.

**Comment by FabianTerhorst** [comment]
This will be fixed.

**Comment by LeonMrBonnie** [comment]
MValueVector3 seems to be unhandled by webview internally.

**Comment by LeonMrBonnie** [comment]
This is fixed in the next RC build.
