### ISSUE TITLE
CEF Pointer Cursor State

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#763]
**Current behavior**
Cursor regardless of the `cursor: pointer` option in css does not change the cursor state.

https://gfycat.com/SlimyImpressiveGoldenmantledgroundsquirrel

**Expected behavior**
Cursor state changes based on the `cursor: pointer` css.

**Steps to reproduce**
Just add `cursor: pointer;` to your WebView CSS.

**Comment by FabianTerhorst** [comment]
which branch?

**Comment by 7Hazard** [comment]
I believe this has been fixed in rc

**Comment by Stuyk** [comment]
> which branch?

release
