### ISSUE TITLE
Rockstar launcher detecting unexpected Files

### ISSUE THREAD

**Issue by WhishN** [altmp/altv-issues#764]
**Client/server version**
Latest Release

**Current behavior**
Sometimes Rockstar launcher detects unexpected Files due to CEF placing them in GTA Folder

**Expected behavior**
Nothing should be created in GTA Folder

**Steps to reproduce**
It seems it only happens sometimes.

**Possible solution**
i think its possible either to disable CPUCache completely for all users or change path to alt:V folder.
something i found was something like this:
var settings = new CefSettings
{
	CefCommandLineArgs = {["disable-gpu-shader-disk-cache"] = "1"}
};

**Comment by LeonMrBonnie** [comment]
Fixed in the next update
