### ISSUE TITLE
isAiming getter doesn't work in vehicles

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#766]
**Client/server version**
`Build #rc/2.2-rc12, branch rc`

**Current behavior**
If you use the getter and you are aiming while sitting in a vehicle, it returns false

**Expected behavior**
It should also return true if aiming in vehicles

**Steps to reproduce**
Just use alt.log(alt.Player.local.isAiming)  while you are aiming in a veh

**Comment by martonp96** [comment]
fixed in rc
