### ISSUE TITLE
everyTick function is stopped for some unknown reason

### ISSUE THREAD

**Issue by FDiskas** [altmp/altv-issues#767]
[core.zip](https://github.com/altmp/altv-issues/files/5730673/core.zip)

**Client/server version**

`Build #2.2-rc12, branch rc`

**Current behavior**
Player joins the server. Under his head the tag is displayed using everyTick function. He enters the bus using B key as a passenger and nametag is stops working. If I add a log in to the tick it also stops firing the logs

**Expected behavior**
The ticks should not stop in any case.

**Steps to reproduce**
I attached minimal reproducible code to the issue. Load `core` resource to the server

**Context (environment)**
I restart server, cleaned resources, restarted client couple times and yes reproducible, but problem unknown :(
Release it works because there is no event enterVehicle Only on latest RC issue persists

**Possible solution**
If I wrap `clearTimeout(timerToGarage);` within if statment it works
```js
if (timerToGarage) {
    clearTimeout(timerToGarage);
}
```

**Comment by martonp96** [comment]
Your script is broken, you are clearing a timer which is not even running when you are entering the vehicle thus stopping the timer with id 0. The timers are working perfectly so please stop blaming alt:V for your script issues.

**Comment by FDiskas** [comment]
It shouldn't be related to tick :)
