### ISSUE TITLE
Cursor type bug (CEF)

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#769]
**Client/server version**
rc/2.2-rc14

**Current behavior**
The cursor type changes when i hover a button in CEF. it's not a problem, but when i delete the CEF, the cursor type remains the same. (https://i.imgur.com/OT99tMr.png)

**Expected behavior**
The cursor type should be set back to the default after deleting the CEF.

**Steps to reproduce**
Hover a button in CEF, then click it. the button should delete the CEF.
Example script:
https://pastebin.com/fieb0KdF

**Context (environment)**

**Possible solution**

**Comment by 7Hazard** [comment]
We could do so if the focused view is getting destroyed, reset the pointer type to the default

**Comment by C0kkie** [comment]
Fixed in upcoming dev
