### ISSUE TITLE
Models looking strange?

### ISSUE THREAD

**Issue by cuBeUrg** [altmp/altv-issues#770]
**Client/server version**

Build 2.2, RC 14

**Current behavior**
The skins look weird. Here is an example: 
![image](https://user-images.githubusercontent.com/42491195/103011579-d8a85280-4542-11eb-8175-348d4d3305e4.png)

**Expected behavior**
They should look normal.

**Steps to reproduce**

Client script: 
`
import * as alt from 'alt';
import * as native from 'natives';

const fModel = alt.hash('mp_f_freemode_01');
const mModel = alt.hash(`mp_m_freemode_01`);

native.requestModel(fModel);
native.requestModel(mModel);

alt.emitServer(`character:AwaitModel`, fModel);`

Server script: 
`import alt from 'alt-server';

alt.onClient(`character:AwaitModel`, handleAwaitModel);

function handleAwaitModel(player, characterSex) {
    player.model = 'mp_m_freemode_01';
    
}`

**Context (environment)**

All I am trying is to get the model correct, and create a character.

**Possible solution**

No idea.

**Comment by 7Hazard** [comment]
This happens if you set his model but don't spawn him. You will see that he slowly but surely deteriorates and compresses into himself and becomes some kind of psuedo-midget.

Spawn the player before or after setting his model.
