### ISSUE TITLE
Dynamic resource reimport is not working

### ISSUE THREAD

**Issue by FilkodonAwang** [altmp/altv-issues#771]
**Client/server version**
`Build #2.2-rc14, branch rc`

**Current behavior**
I import dynamicly an other resource everytime, when the resource is restarted.
After, I change something in the imported resource (like change a constant text in a log).
The resource, which is imported the other, logged about the reload, due to the restart.
When I try to run an exported function from the dynamicly imported resource I always
got the first time loaded version of the run.
( It's like the dynamic reload not changed anything.)

**Expected behavior**
I got the new log text after the script change and the automatic dynamic reload.

**Steps to reproduce**

[test_resources.zip](https://github.com/altmp/altv-issues/files/5736974/test_resources.zip)

- Load the two resources from the attachment. (dev,chat)
- Press num4 button.
- Change the log text (chat/client.js:4)
- Restart the chat resource.
- Press num4 button again.

**Context (environment)**
I running the server on Windows, using the 2.2-rc14  version.

**Possible solution**
I guess there is something wrong in the new dynamic import implementation.

**Comment by LeonMrBonnie** [comment]
This has been fixed in dev/4.0-dev5
