### ISSUE TITLE
Clothprint bug

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#773]
**Client/server version**

`Build 2.3, branch release`

**Current behavior**
https://prnt.sc/w9f0im
On the cloth their printing other stuff now

**Expected behavior**
No printed stuff on the clothed

**Steps to reproduce**
Not sure

**Context (environment)**

**Possible solution**

**Comment by LeonMrBonnie** [comment]
Please fill out the whole issue template.

**Comment by Doxoh** [comment]
@LeonMrBonnie added. More then these infos and screenshot I cannot provide.

**Comment by LeonMrBonnie** [comment]
Please research this problem a little bit yourself to find out if it is caused by a specific circumstance, a specific other decal etc.

**Comment by Doxoh** [comment]
Its the same problem like the "prevent communist rise up" bug. We had this before the release today but we hoped that its fixed with these version

**Comment by yuAwi** [comment]
Its happening randomly only for some players. It seems that only the male model is affected by this.
In the screenshot above there is no decal set, but we call
`native.setPedComponentVariation(alt.Player.local.scriptID, 10, 0, 0, 0);`
to remove the old decal.

**Comment by Doxoh** [comment]
I thing its fixed
