### ISSUE TITLE
Data files vehmodels.bin and vehmods.bin not updated

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#774]
**Client/server version**
`Build #2.3, release`

**Current behavior**
New vehicles of cayo perico update are not supported yet in data files.

**Expected behavior**
Should be supported in release update.

**Steps to reproduce**
1. Spawn vehicle of cayo perico update like: `italirsx`
2. Console Output: `[Error] Failed to create vehicle: 3145241962 is not a proper model hash`

**Comment by DurtyFree** [comment]
Meanwhile you can use my updated versions from this post: https://discord.com/channels/371265202378899476/583109900024938527/788504176946446357

vehmods.bin has some issues tho, thats why it haven't got updated in release yet.

**Comment by DurtyFree** [comment]
vehmods.bin & vehmodels.bin got updated for latest GTA update and should be available on CDN :)
