### ISSUE TITLE
Mouse events are sent to the webview even if cursor is hidden

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#775]
**Client/server version**

`rc/2.2-rc15`

**Current behavior**

Mouse events (click, mousemove, etc) are sent to the webview even if cursor is hidden and webview is unfocused.
Even CSS's :hover reacts to the hidden cursor.

**Expected behavior**

Hidden cursor shouldn't cause webview to fire mouse events.

**Steps to reproduce**

1. Create a webview, that tracks mouse clicks for example.
2. Call `alt.showCursor(false)` and `webview.unfocus()`.
3. Clicks, mouse movements etc are captured by the webview anyways.

**Context (environment)**

I have some interfaces that allow hiding of the cursor (to control the game) without hiding UI.
Players are still able to move/cilck some things, even when they try to interact with the game.

**Comment by FDiskas** [comment]
![unknown.png](https://user-images.githubusercontent.com/468006/103143062-07c3ed00-4718-11eb-837b-2970b0410afc.png)

**Comment by zziger** [comment]
Now keyboard and mouse events are disabled until focus() is called
