### ISSUE TITLE
Mic Key bind Getter

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#777]
**Suggestion**
If possible I'd like to see a getter like `getMicKeybind` which would return the current key the client has binded in the alt:v launcher

**Use cases**
To allow players to rebind all the other keys on the server without binding something like a menu key to the same key that is binded to their mic

**Describe the solution you'd like**
Add a getter to the client API

**Describe alternatives you've considered**
N/A

**Comment by LeonMrBonnie** [comment]
Available as `alt.Voice.activationKey` in newest dev.
