### ISSUE TITLE
Masterlist API returns wrong build number

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#778]
**Client/server version**

`Build #xxxx, branch release`

**Current behavior**
The masterlist API currently returns `-1` for the build number regardless of what it actually is

**Expected behavior**
Should return the correct build number

**Steps to reproduce**
Go to [here](http://api.altv.mp/servers/list)

**Context (environment)**
I'm using the API for a web panel

**Possible solution**
N/A

**Comment by LeonMrBonnie** [comment]
This may be intended/obsolete because the new versioning doesn't use build numbers anymore.

**Comment by FabianTerhorst** [comment]
Yes build number will be removed.

**Comment by vadzz-dev** [comment]
There's no buildNumber anymore so it's set to -1 for backward compatibility
