### ISSUE TITLE
Cef processes aren't killed on client quit

### ISSUE THREAD

**Issue by cuBeUrg** [altmp/altv-issues#780]
**Client/server version**
alt:V Server 2.4 (release)

**Current behavior**
I have a hosted server, and a localhost server. They have the same gamemode / files. The problem is that when I join the localhost server, and then leave the game (using quit in console), and join my hosted server, things start getting strange. The console (F8) starts to get laggy (there is a delay between when I press the button, and when It shows up), and the same is for other WebViews. I thought this is a server (host) issue, but then I rejoined the localhost, and again, some of the WebViews and Console were laggy. 

I asked about this on the Discord and someone told me to destroy the WebViews after the players leave, and I did that, but the problem is still there. 

I even tried reinstalling altV, but no changed were visible.

**Expected behavior**
I expect the console and the webviews to not be so laggy.

**Steps to reproduce**
`alt.on('disconnect', () => {
  if (view) {
    view.destroy();
  }
})`

And try to get from one server to another for like 3-4 times, and the problem should happen.

**Context (environment)**
The only fix I found for it is to restart the PC, which fixes the issue, but then again, joining / leaving the server, will cause that problem.

**Possible solution**

No idea, I thought maybe `view.destroy();` dosen't work as it should? No idea.

**Comment by LeonMrBonnie** [comment]
Can you check in the task manager how many tasks of CEF there are open after reconnecting and getting the lags?

**Comment by cuBeUrg** [comment]
> Can you check in the task manager how many tasks of CEF there are open after reconnecting and getting the lags?

Gonna check.

**Comment by cuBeUrg** [comment]
![image](https://user-images.githubusercontent.com/42491195/103217024-42987180-4920-11eb-92a6-9c5bb3788e06.png)

**Comment by cuBeUrg** [comment]
Also, so I tested this for a while, and if I keep joining the same server (localhost), for many times, this problem does not happen. So it only happens if you change servers.

**Comment by LeonMrBonnie** [comment]
alt:V doesn't allow you to change servers without restarting, what do you mean?

**Comment by cuBeUrg** [comment]
> alt:V doesn't allow you to change servers without restarting, what do you mean?

Well, I change the servers by quiting the game, launching it again, and joining another server from the masterlist.

**Comment by ZackaryH8** [comment]
Might be a long shot, but if you have MSAA enabled in your GTA settings, this can cause severe FPS drops particularly in first person.

**Comment by LeonMrBonnie** [comment]
This issue will be tracked in #1285
