### ISSUE TITLE
Permissions not working while using CDN

### ISSUE THREAD

**Issue by DanielSchuech** [altmp/altv-issues#783]
**Client/server version**

`Version 2.2, branch release`

**Current behavior**
The permission dialog is displayed to the user when we are not using a CDN. After enabling `useCdn` in the `server.cfg` the dialog will not be shown. Instead the Client directly connects to the server and has not the required permissions.

**Expected behavior**
Permission dialog is displayed weather a CDN is used or not.

**Steps to reproduce**
1) add Screen Capture permission to `resource.cfg`
2) enable cdn in `server.cfg`
3) connect to server

**Context (environment)**
Screenshot API

**Possible solution**
Maybe the required permissions has to be included into the `connect.json` to have this information without connecting with the game server.

**Comment by C0kkie** [comment]
Can confirm on release/2.8

**Comment by Hanashi** [comment]
Can confirm on release version 2.23

**Comment by vanessa** [comment]
This is badly affecting the experience of one of our features (which takes a headshot of the player, thus needs screenshot permission). Do we have an estimate of when this bug will be resolved? I'd be happy to pull out a PR if this code was open source or contribute on https://issuehunt.io/ or something else.

**Comment by C0kkie** [comment]
Fixed in upcoming dev build. Only thing what still needs to be fixed then:

After early auth the loading screen is missing and you think you are back to main menu
