### ISSUE TITLE
-connecturl not working

### ISSUE THREAD

**Issue by danilaplee** [altmp/altv-issues#784]
**Client version**
Build 2.8, branch release

**Current behavior**
-connecturl option is always producing Malformed connection url error
**Expected behavior**
-connecturl options working as before working with ip:port or domain:port

**Steps to reproduce**
see screenshot

![Desktop Screenshot 2020 12 29 - 22 47 48 31](https://user-images.githubusercontent.com/6561396/103310305-4c0d0100-4a28-11eb-93f4-f899aca8a3dd.png)
![Desktop Screenshot 2020 12 29 - 22 55 04 69](https://user-images.githubusercontent.com/6561396/103310572-fc7b0500-4a28-11eb-9001-77542459202d.png)

**Comment by 7Hazard** [comment]
If you write `altv://connect/127.0.0.1:7788` it would understand it

**Comment by danilaplee** [comment]
I cannot seem to get altv://connect working where is the docs for this?

**Comment by 7Hazard** [comment]
I meant `altv://connect/127.0.0.1:7788` as the arg to -connecturl, so `./altv.exe -connecturl altv://connect/127.0.0.1:7788` would connect you to your local gameserver at port 7788.

**Comment by danilaplee** [comment]
@7Hazard thanks this seems to be working, and I don't have to do "register the new windows protocol" dance :)

**Comment by danilaplee** [comment]
btw is it possible to switch server in runtime?

**Comment by danilaplee** [comment]
@7Hazard please update the docs and close the issue after this then

**Comment by LeonMrBonnie** [comment]
A proper explanation of how to use the connecturl argument will be provided in the wiki.
