### ISSUE TITLE
IVehicle.WheelsCount changes after repairing vehicle

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#789]
**Client/server version**
`Build 2.8, branch release`

**Current behavior**
When calling IVehicle.Repair() the number the property IVehicle.WheelsCount is set to 10 instead of the right number of wheels

**Expected behavior**
Wheels count should not change

**Steps to reproduce**
Simply spawn a vehicle, run Repair() on it.
Before IVehicle.Repair():
![image](https://user-images.githubusercontent.com/7643284/103469290-39196a00-4d63-11eb-9f53-44cf0588bd5d.png)

After :
![image](https://user-images.githubusercontent.com/7643284/103469299-49314980-4d63-11eb-9801-8ddc2416f2a2.png)

**Context (environment)**
Using last release .NET module

**Comment by YannBCF** [comment]
Issue confirmed on the JS module on the 4.0-dev3

**Comment by FabianTerhorst** [comment]
Fixed in next release.
