### ISSUE TITLE
Custom blip icons

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#793]
**Suggestion**

Add an ability to stream custom blip icons (additional or by replacing)

**Use cases**

To have my own blips on the map, and to possibly fix the gta's problem with the areablips and shortRange property.
( Areablips with shortRange enabled are moving strangely on the minimap, setting sprite to the empty image instead of using shortRange would probably fix the problem ) 

**Describe the solution you'd like**

Maybe adding ability to replace minimap.ytd file (to replace icons)

**Comment by C0kkie** [comment]
Works in dev/15.0-dev11
