### ISSUE TITLE
Continuously resource reloading on import error

### ISSUE THREAD

**Issue by FilkodonAwang** [altmp/altv-issues#795]
**Client/server version**
`Build #3.0-rc2, branch rc`

**Current behavior**
I made an import mistake in a resource and after the resource continuously reloading itself.

**Expected behavior**
I got an error of the import mistake and the resource stopping.

**Steps to reproduce**
[resources.zip](https://github.com/altmp/altv-issues/files/5773365/resources.zip)

- Load the attached resource 'vf_utils'
- Load the attached resource 'vf_tester' 
- In some case you need to reconnect to reproduce the bug.

**Context (environment)**
Running server in Windows.
I can't stop manually the resource even in the server console because of the continuously logging.

**Comment by FabianTerhorst** [comment]
Please report again when its not yet fixed.
