### ISSUE TITLE
Local player tasks are not cleared after player.spawn

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#797]
**Client/server version**

`alt:V Server 2.8 (release)`

**Current behavior**

Local player tasks are not cleared after player.spawn
ie: you are having cuff task applied to you, everyone sees you cuffed. If you are spawned. You only show cuffed to yourself only, not to everyone else. 
The local tasks should be cleared for the player on spawn too.

**Comment by C0kkie** [comment]
Fixed in current rc
