### ISSUE TITLE
Max health and max armor client getters return 0

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#799]
**Client/server version**

`3.0-rc2`

**Current behavior**

Client player.maxHealth and player.maxArmor getters return incorrect values (0) on another players, but on local player values are correct.

**Expected behavior**

Values should be correct

**Steps to reproduce**

Check result of `alt.Player.getByID(id of another player).maxHealth` on client

**Comment by Arochka** [comment]
Confirmed on dev

**Comment by C0kkie** [comment]
We will track it here, because there are more informations https://github.com/altmp/altv-issues/issues/1318
