### ISSUE TITLE
Apply textures to objects/surfaces

### ISSUE THREAD

**Issue by 7Hazard** [altmp/altv-issues#8]
Like how a game engine would handle textures

Make a texture that can be modified with custom bitmaps and can be applied to objects and surfaces.
Make the object/surface perpenicular to one's screen to simulate a 2D3D rendition.

**Comment by martonp96** [comment]
no

**Comment by zziger** [comment]
Why btw, we can replace textures with a webview, why can't we replace a texture with some other texture?

**Comment by FabianTerhorst** [comment]
The memory of that Texture is only present one time no matter how many objects are using it.
