### ISSUE TITLE
alt.Player.local.IsInRagdoll return false when the player is called to ragdoll with native.

### ISSUE THREAD

**Issue by lameule123** [altmp/altv-issues#802]
**Client/server version**
2.8 Release branch

**Current behavior**
alt.Player.local.IsInRagdoll return false clientside when the player is called to Ragdoll with native SetPedToRagdoll
(native.isPedRagdoll also return false)

**Expected behavior**
This should return true.

**Steps to reproduce**
- Define a StreamSyncedMetaData
- Check for meta OnUpdate clientside and if set to true call game.setPedToRagdoll(localPlayer.scriptID, 1000, 1000, 0, false, false, false);
- IsInRagdoll/Native IsPedRagdoll still return false.

**Possible solution**
Check the StreamSyncedMetaData instead of alt property or natives.

**Comment by C0kkie** [comment]
Call game.resetPedRagdollTimer(alt.Player.local.scriptID);
In everytick and check again
That should work

**Comment by lameule123** [comment]
I already call game.setPedToRagdoll(localPlayer.scriptID, 1000, 1000, 0, false, false, false); OnTick if the player is meta is set to true. Do u think that will work?

**Comment by C0kkie** [comment]
Just use setPedToRagdoll and then resetPedRagdollTimer in everytick until you dont need it anymore

**Comment by LeonMrBonnie** [comment]
If the native also returns false, then this is either a GTA bug or the developers fault. We cannot fix this then.
