### ISSUE TITLE
Add setMinimapComponentPosition function

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#804]
**Suggestion**
```js
/**
 * @param {string} name
 * @param {string} alignX
 * @param {string} alignY
 * @param {number} posX
 * @param {number} posY
 * @param {number} sizeX
 * @param {number} sizeY
 * @returns {void}
 */
setMinimapComponentPosition(name, alignX, alignY, posX, posY, sizeX, sizeY)

// "L" Left - "B" Bottom
alt.setMinimapComponentPosition('minimap', 'L', 'B', -0.0045, -0.022, 0.210, 0.258888);
alt.setMinimapComponentPosition('minimap_mask', 'L', 'B', 0.0, 0.032, 0.101, 0.259);
alt.setMinimapComponentPosition('minimap_blur', 'L', 'B', 0.012, 0.022, 0.256, 0.337);
```

**Use cases**
A method for changing the position of Minimap.

**Describe the solution you'd like**
Overrides the minimap component data (from `common:/data/ui/frontend.xml`) for a specified component.

**Additional context**
https://runtime.fivem.net/doc/natives/?_0x3E882B23

**Comment by mrgharabaghi** [comment]
Overrides the minimap component data (from common:/data/ui/frontend.xml) for a specified component.

**Comment by Lhoerion** [comment]
You can only request such function to add it to API, not to GTAV natives.
Change your issue to reflect that feedback.

**Comment by DurtyFree** [comment]
Note: This is a FiveM "extra native" / custom API, the implementation for that is available here: https://github.com/citizenfx/fivem/blob/34069da52f788a6e21c7ae2e9fc6d84dda932abe/code/components/extra-natives-five/src/InterfaceExtraNatives.cpp#L187

**Comment by LeonMrBonnie** [comment]
Available in next update
