### ISSUE TITLE
Add HTML Tags for Custom Launcher -> RSS Feed

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#806]
Good Morning,
It would be nice if you can add some html tags to the rss feeds and use them at the startpage.
Like <p> tags or <br> Tags.

Same, if its possible, for the image tag. XML, Rss Feeds can have an image tag. But the images doesnt work.

Thank you 👍

**Comment by ThomasMarangoni** [comment]
Please provide an example for visual goal and rss feed itself.

**Comment by KyuubiDDragon** [comment]
You can use in typical rss feed the following style of description:_
<description><![CDATA[ 
<p>Welcome<br/>
	Line1<br>
	Line2<br>
	Line3<br>
</p>
]]></description>
In this case he should use the breaks and go in a new row.
For the moment, everything you write into the description he write in 1 row.
Like:
WelcomeLine1Line2Line3

But it should looks like
Welcome
Line1
Line2
Line3.

**Comment by ThomasMarangoni** [comment]
I formated your code to a codeblock thanks for your feedback

**Comment by vadzz-dev** [comment]
can we form a list of tags we should allow?

**Comment by FabianTerhorst** [comment]
With the next release img tag is allowed in rss feed as well.
