### ISSUE TITLE
setPauseMenuActive() does not working

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#809]
**Client/server version**
`Build #2.8, branch release`

**Current behavior**
`native.setPauseMenuActive()` does not working.

**Expected behavior**
Change the "Pause Menu" status. Open and close the "Pause Menu".

**Comment by mrgharabaghi** [comment]
This native cannot open the `Pause Menu`. All it does is prevent the `Pause Menu` from opening.
```js
alt.everyTick(() => {
    native.setPauseMenuActive(false);  // Prevent the "Pause Menu" from opening.
});
```

**Comment by DurtyFree** [comment]
Can you please try some frontend native like ACTIVATE_FRONTEND_MENU ?

**Comment by mrgharabaghi** [comment]
Customized control on open and close "Pause Menu".
```js
// Client Side - JavaScript
import alt from 'alt-client';
import native from 'natives';

alt.on('keyup', (key) => {
    if (key === 69) { // E = 69
        if (native.getPauseMenuState() === 0) {
            native.activateFrontendMenu(native.getHashKey('FE_MENU_VERSION_MP_PAUSE'), true, -1);
        } else {
            native.activateFrontendMenu(native.getHashKey('FE_MENU_VERSION_MP_PAUSE'), false, -1);
        }
    }
});
```
