### ISSUE TITLE
Change server password during runtime

### ISSUE THREAD

**Issue by MrNeta** [altmp/altv-issues#81]
**Is your feature request related to a problem? Please describe.**
No, but it would be great to have the possibility to change the server password during runtime

**Describe the solution you'd like**
Add an function to the sdk to change the server password

**Comment by gamelaster** [comment]
This reminds me a Terraria. The password could be dynamically set by server, so you will be capable to login with your password even before connecting to server.

**Comment by 7Hazard** [comment]
I approve of thy

**Comment by vadzz-dev** [comment]
@Lhoerion why client?

**Comment by nick-strohm** [comment]
Backed. Are there some news regarding this issue?

**Comment by FabianTerhorst** [comment]
Is added in dev/3.0-dev4

**Comment by ThomasMarangoni** [comment]
Not working as expected

**Comment by LeonMrBonnie** [comment]
Fixed in next dev build

**Comment by ThomasMarangoni** [comment]
fixed with dev/4.0-dev8
