### ISSUE TITLE
Vehicle handling crashes when out of streaming distance

### ISSUE THREAD

**Issue by Iubotch** [altmp/altv-issues#810]
**Client/server version**

`Build #3.0, branch rc2`

**Current behavior**
If you attempt to access or modify a value of IVehicleHandling of a streamed-out vehicle, the game will unexpectedly crash.

**Expected behavior**
It should not crash. Even more so when vehicle.handling.isModified() has a valid return even when the vehicle is not streamed in.

**Steps to reproduce**
Spawn a vehicle server-side, send the vehicle object to the client and attempt to modify or read any handling value. The vehicle takes a few ticks to stream in and so the event is triggered faster, causing the crash.

**Context (environment)**
Simply reading the handling values to send them to a UI for real-time handling modification.

**Possible solution**
Nothing too fancy but either return an error if the client tries to modify the handling when the vehicle is out of stream or simply apply the values once it gets streamed in.

**Comment by zziger** [comment]
That actually crashes the game even for vehicles that were removed at all (those aren't removed from the client alt.Vehicle.all array, and even have the valid param set to true)

**Comment by LeonMrBonnie** [comment]
> That actually crashes the game even for vehicles that were removed at all (those aren't removed from the client alt.Vehicle.all array, and even have the valid param set to true)

Even if the vehicle doesn't exist in your game world the valid property will still be true, because the valid property only checks if the vehicle exists at all. 
If you want to check if the vehicle exists in the game world check for scriptID == 0

**Comment by zziger** [comment]
That's what i actually do atm, but seems weird that vehicle that was removed from the server still stays in the client. If there will be many cars spawning and destroying (e.g. for npc traffic implementation) then it will cause clients to use more ram (even for vehicles that don't exist anymore).

**Comment by LeonMrBonnie** [comment]
> That's what i actually do atm, but seems weird that vehicle that was removed from the server still stays in the client.
That shouldn't be happening, and I am pretty sure it doesn't.

**Comment by zziger** [comment]
> > That's what i actually do atm, but seems weird that vehicle that was removed from the server still stays in the client.
> 
> That shouldn't be happening, and I am pretty sure it doesn't.

I'll check it later and will give a repro code if that's happening

**Comment by C0kkie** [comment]
Fixed in next rc version
