### ISSUE TITLE
Client HTTP/HTTPS request api

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#811]
**Suggestion**

It would be nice to have ability to make http/https requests from the client

**Use cases**

Requesting some data from external source

**Describe the solution you'd like**

E.g. browser fetch api

**Describe alternatives you've considered**

Creating a webview to send requests

**Comment by LeonMrBonnie** [comment]
The C++ SDK should just provide a HTTP client to module developers, so it can be added to every client module.
We are already using IXWebSocket for the websocket client implementation, and it also has a HTTP client available, so there wouldn't be any additional dependencies necessary.

**Comment by ThomasMarangoni** [comment]
**Note:** Better would be a implementation with curl, because it is already used in client.

**Comment by LeonMrBonnie** [comment]
Available in dev
