### ISSUE TITLE
Event Alt.OnNetworkOwnerChange doesn't give old entity network owner

### ISSUE THREAD

**Issue by LeShred** [altmp/altv-issues#813]
**Client/server version**
`Build #2.8, branch release`

**Current behavior**
When network entity had a network owner and loose its network owner, the parameter oldNetOwner of NetOwnerChangeDelegate(IEntity target, IPlayer oldNetOwner, IPlayer newNetOwner) is null.

**Expected behavior**
Getting the old network owner of the entity

**Steps to reproduce**
Alt.OnNetworkOwnerChange += (IEntity target, IPlayer oldNetOwner, IPlayer newNetOwner) =>
{
      Alt.Log($"Old network owner: {oldNetOwner}");
};

**Comment by FabianTerhorst** [comment]
Did the old net owner disconnected or moved out of range?

**Comment by JulianMa** [comment]
I used it very extensive, while building logs for the vehicle teleportation bug. There was no time, the old netOwner was null, when there actually was an old netOwner, so i can't really confirm this for the JS-Module atleast.

**Comment by LeShred** [comment]
I finally managed to find the problem.
In fact it happens when the vehicle network owner disconnects/crash/reconnects. When this happens oldNetOwner is null.

**Comment by FabianTerhorst** [comment]
And thats not a Bug.

**Comment by LeShred** [comment]
But the vehicle had a network owner before client disconnected, why passing null instead of the old network owner?

**Comment by FabianTerhorst** [comment]
Because the entity is deleted.

**Comment by LeShred** [comment]
I would have kept the entity in memory and flagged it has invalid but I understand your position.
Issue can be close then.
