### ISSUE TITLE
Make dimension '-1' able to see all, not just 0

### ISSUE THREAD

**Issue by Heryshaf** [altmp/altv-issues#816]
**Suggestion**
Make dimension '-1' or any other exception like  int32 max able to see all, not just 0 while they can't see the the other way around
Since already -1 can see 0, why not positives too?
**Use cases**

For better spec systems and etc. 
**Describe the solution you'd like**

player.dimension -1 should be able to see 0, 1, 2, 3 etc

**Comment by tastydev** [comment]
The behaviour of -1 shouldn´t be change it would be better to introduce an own dimension for that behavior. Like max int32. min int32 is already used for a different behavior for colshapes

**Comment by FabianTerhorst** [comment]
Spectate is now possible with .isStreamed setter/getter.
