### ISSUE TITLE
getNearestPlayerToEntity returns -1

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#817]
**Client/server version**

`Build #2.7, branch release`

**Current behavior**
The native getNearestPlayerToEntity returns everytime -1
Tried snippets:
```
alt.log(native.getNearestPlayerToEntity(alt.Player.local.scriptID)) OR
const chair = game.getClosestObjectOfType(alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z, 10.0, alt.hash("prop_bench_01a"), false, false, false)
alt.log(native.getNearestPlayerToEntity(chair ))
```

**Expected behavior**
Give back the nearst Player. Not -1

**Steps to reproduce**
Maybe replace the object:
`alt.log(native.getNearestPlayerToEntity(alt.Player.local.scriptID)) OR
const chair = game.getClosestObjectOfType(alt.Player.local.pos.x, alt.Player.local.pos.y, alt.Player.local.pos.z, 10.0, alt.hash("prop_bench_01a"), false, false, false)
alt.log(native.getNearestPlayerToEntity(chair ))`

**Context (environment)**
I tried todo it with a second player. Tried with a differend entitys and more.
Also checked the entity with the native doesEntityExist. This was true.

**Possible solution**

**Comment by LeonMrBonnie** [comment]
Probably because `players` in the sense of GTA V are different than normal peds.

**Comment by mrgharabaghi** [comment]
Hello @KyuubiDDragon
You can use this example. All you have to do is use `Player` instead of `Vehicle`.
https://discord.com/channels/371265202378899476/583109900024938527/750432452975132762
(alt:V Official Discord)

**Comment by DurtyFree** [comment]
Please write your own method for such use cases, as Leon pointed out this native will not work because of the way alt:V handles players
