### ISSUE TITLE
Add getCamMatrix function

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#818]
**Suggestion**
```js
/**
 * @typedef {Object} Matrix
 * @property {Vector3} rightVector
 * @property {Vector3} forwardVector
 * @property {Vector3} upVector
 * @property {Vector3} position
 */

/**
 * @param {} camera
 * @returns {Matrix}
 */
getCamMatrix(camera)
```
**Use cases**
Returns the world matrix of the specified camera.

**Additional context**
To turn this into a view matrix, calculate the inverse.
https://runtime.fivem.net/doc/natives/?_0x8F57A89D
https://github.com/crosire/scripthookvdotnet/blob/main/source/scripting_v3/GTA/Camera.cs

**Comment by DurtyFree** [comment]
Note: This is a FiveM "extra native" / custom API. See https://github.com/citizenfx/fivem/blob/34069da52f788a6e21c7ae2e9fc6d84dda932abe/code/components/extra-natives-five/src/CameraNatives.cpp#L142

**Comment by FabianTerhorst** [comment]
Just because its not a native doesn't mean it won't be added.
