### ISSUE TITLE
Crash when calling a group of hud natives

### ISSUE THREAD

**Issue by Avililla** [altmp/altv-issues#819]
**Client version**
`Build #2.2-dev12, branch development`

**Current behavior**
Crash client when creating floating help text. Function i used to make it:
```lua

  function showfloatinghelptext(msg,coords)
      native.setFloatingHelpTextWorldPosition(1, coords.x,coords.y,coords.z)
      native.setFloatingHelpTextStyle(1, 1, 2, -1, 3, 0)
      native.beginTextCommandDisplayHelp('STRING')
      native.addTextComponentSubstringPlayerName(msg)
      native.endTextCommandDisplayHelp(2, false, false, -1)
  end
```
the function provided is a copy/paste from a working resource i have on my fivem server

**Expected behavior**
![image](https://user-images.githubusercontent.com/54501703/105751242-07508900-5f46-11eb-9084-c2f37ed7201a.png)

**Steps to reproduce**
The function must be every tick but it cash also when calling it once.

**Context (environment)**
Function for displaying help text to players

**Possible solution**

**Comment by yoranjj** [comment]
Just tried this on the most recent dev build (#3.0-dev4) by copy & pasting your example code and it works perfectly fine, no crashes whatsoever.

**Comment by Lhoerion** [comment]
If it'll be confirmed that the issue is related to the client itself, then issue will get reopened.
Otherwise this it belongs to lua module issue tracker.
