### ISSUE TITLE
Voice chat position sync doesn't properly work in clientside loaded interiors

### ISSUE THREAD

**Issue by Kaev** [altmp/altv-issues#825]
**Client/server version**

3.0-dev 5

**Current behavior**
The position of the player voice sometimes stops following the player in clientside loaded IPLs (non modded, GTA V original IPLs so not related to interior proxies). Usually happens when you switch rooms.

**Expected behavior**
The voice of the player should always be at the players position.

**Steps to reproduce**
- Add GTA V original IPLs on clientside (we used these for testing: https://github.com/jovanivanovic/altv-os-missing-interiors/blob/master/client/interiors.js )
- Drive to the Live Invader building
- Keep talking while you move through the building
- Often happens when you let yourself fall from the upper floor to the lower floor (keep talking during all of that, might be an important hint)
- You'll notice that the voice position of the other players will stuck at some positions (e.g. on the upper floor if you let yourself fall down)

**Context (environment)**
We try to use the AltV voice chat and talk in clientside loaded interiors.

**Possible solution**
@vadzz-dev  said in discord that the problem might be related to the room portals. The voice position probably stucks at the portals instead of following the player.

**Comment by Lawliz** [comment]
I've done something like this to solve temporary this issue but sometimes it doesn't work:

```js
everyTick(async () => {
    if (voiceLoaded === true) {
        const interior = getInteriorFromEntity(Player.local.scriptID)
        if (interior !== lastInterior) {
            lastInterior = interior
            emitServer('voice:muteSelf')
            await wait(500)
            emitServer('voice:unmuteSelf')
        }
    }
})
```

You've to wait ~500ms to unmute the player otherwise the voice is still stucked at the door.
And I face the same issue when going under tunnel or parkings on 2.23 (release).

**Comment by C0kkie** [comment]
Can you try the latest dev build? It should be fixed there

**Comment by Lawliz** [comment]
Can't test it right now, if you want to test it you'll need to be with another person.

One need a soundpad with a sound playing with his input and both need to enter in the interior, if the sound stay at the door of the interior then it's not fixed.

**Comment by C0kkie** [comment]
Will be fixed in next rc build, but the rever, muffling will be broken for now

**Comment by C0kkie** [comment]
Should be fixed
