### ISSUE TITLE
Integrate Clientside Modding

### ISSUE THREAD

**Issue by noellietlive** [altmp/altv-issues#826]
**Suggestion**
This request suggests the implementation of an easier method to add client side mods - specifically retextures which will not create too much of a 'sync' issue. Preferably, clothing models etc. would also be available. Not to compare the two, but RageMP has a system wherein you can add files via a server's cache which then appear ingame. You can use this to add custom clothes, graffiti to the world, custom weapons and so on.

This is currently already possible through use of OpenIV but makes sharing mods very difficult due to large .rpf sizes - where they cannot be defragmented. In addition to this, OpenIV server mods would overwrite your clientside mods if for example the server sided files replaced a default GTA tattoo. 

**Use cases**
Being able to add client only mods is one of the core aspects which makes up a typical RP community's modding habits. For example, on GTA World or LSRP (for SAMP) players have means in which they can create and integrate mods of their own making to allow greater individual customization. 

A working example of this might be creating custom tattoo mods for a faction - you cannot feasibly expect a server owner to add a pack full of tattoos for every new faction that is created on the server. In order to find a middle ground, users should be able to (at very least) add their own textures to their client in an easier manner.

**Describe the solution you'd like**
The most obvious solution I could see would be to allow a user to create their own clientside resource packs, or to add to a server's cache with their own mod folders. This way you could keep the filesizes small and make mods shareable as well as save the headache of installing through openIV.

**Describe alternatives you've considered**
The current alternative is to either beg a server owner to add mods to the server (explained above as to why that is obviously unfeasible for a large community) or to add them through modifying your gamefiles as I also touched on earlier. There are limitations to modifying your game files, since you have to edit large .rpf files which within themselves contain the .rpf files and .ydd's that you are potentially modifying. There is no way to defragment these smaller, since if you remove core files you would break the default clothing models etc.

**Additional context**

**Comment by DurtyFree** [comment]
@noellietlive Please edit your feature request to follow our template as provided:
```
<!-- 🚨 STOP 🚨 STOP 🚨 STOP 🚨

Before you post an issue, make sure you've read quick introduction to our bug tracker:
  * https://github.com/altmp/altv-issues/blob/master/README.MD

Please fill in the *entire* template below. -->

**Suggestion**
<!-- A summary of what you'd like to see added or changed -->

**Use cases**
<!-- What do you want to use this for? -->

**Describe the solution you'd like**
<!-- A clear and concise description of how do you imagine the implementation -->

**Describe alternatives you've considered**
<!-- A clear and concise description of any alternative solutions or features you've considered -->

**Additional context**
<!-- Add any other context or screenshots about the feature request here -->
```

**Comment by FabianTerhorst** [comment]
There won't be client side mods that create sync issues like dlcs for tatoos ect. Only something like visual mods like nve, nvr, ect. For tatoos use serverside dlc resources.

**Comment by jovanivanovic** [comment]
@noellietlive It is expected that the server dictates how the user's gameplay experience would be hence why we don't want to allow client mods. Although we are aware that some players and some servers would require such feature, our decision is that the server is the main authority when it comes to what mods you get when playing.
