### ISSUE TITLE
Add a armourDamage IServerEvent

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#829]
**Suggestion**
Add an IServerEvent for when armour is damaged 

**Use cases**
To update custom health bars

**Describe the solution you'd like**
armourDamage ServerEvent

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by C0kkie** [comment]
There is already a issue open https://github.com/altmp/altv-issues/issues/683
Please use the searchfunction in the future
