### ISSUE TITLE
.spawn() delay argument to be removed, or the function should return a promise.

### ISSUE THREAD

**Issue by Tricky-Ricky** [altmp/altv-issues#831]
**Suggestion**
The function `spawn(x: number, y: number, z: number, delay: number): void` should return a promise, currently it returns void.

**Use cases**
The reason I am suggesting this, Is you would normally delay something to be able to do something after, for example:
`
function respawnPlayer (target) {
const spawnPoint = teleportLocations.find((location) => location.name === 'pillboxH');
 target.spawn(spawnPoint.x, spawnPoint.y, spawnPoint.z, 10000);
 alt.emitClient(target, 'player:clearBlood');
}
`
You would expect, due to the delay parameter, that you would clear the pedBloodDamage after spawning, but that is not the case. To do this you would need to set a delay to 0 and wrap it in a setTimeout() like so:

`
function respawnPlayer(target) {
    const spawnPoint = teleportLocations.find((location) => location.name === 'pillboxH');
    setTimeout(() => {        
        target.spawn(spawnPoint.x, spawnPoint.y, spawnPoint.z, 0);
        alt.emitClient(target, 'player:clearBlood');
    }, 10000);
}
`
**Describe the solution you'd like**
As you would need to set a delay to 0 and wrap it in a setTimeout(), I would recommend removing the delay parameter.

Alternatively, get the .spawn() function to return a promise and make this asynchronous, I myself do not see many use cases for not having subsequent code after spawning, when handling client side code, In regards to multiple setTimeouts() being needed, which could affect overall performance.

**Describe alternatives you've considered**
Currently, to clearPedBloodDamage, clearPedTasks and anything else you would normally expect to run after respawning you would need to wrap it in a `setTimeout()`. I have found no other alternatives here if you need to run code, after respawning.

**Comment by martonp96** [comment]
This is js module related feature, please move it to that repository.
