### ISSUE TITLE
Sound streaming problem

### ISSUE THREAD

**Issue by Nicoo34** [altmp/altv-issues#833]
**Client/server version**

`Build #2.10 branch Release`

**Current behavior**
two problems with sound streaming : 
- we are not able to stream resident.rpf sound

- Weapon sounds are not synced,  when someone shoot near from you, you will heard the original sound, but if you shoot, you will heard the custom sounds.

**Expected behavior**
- Be able to stream resident.rpf custom sounds
- Fix the shoot problem?

**Steps to reproduce**
use this resources (contain custom police sounds(LA real sirens)

[https://mega.nz/file/4wEEBZJb#4CB2naXezpcQWo5fxJa3Wn0eU5Uku1lWi9HUUeadbqQ](url)

**Comment by Lhoerion** [comment]
Duplicate of #508
