### ISSUE TITLE
[C#] enteredVehicle | changedVehicleSeat - wrong seatIndex

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#836]
**Client/server version**

`Build #2.8, branch release`

**Current behavior**
When player is entered vehicle or changedVehicleSeat the param seat return the wrong seatIndex of the vehicle.
The actual return value is +2.
Example: The seatIndex for the driverSeat should be -1, event returns 1. Passenger should be 0, return is 2.

**Expected behavior**
Should be the right seatIndex like used in the client natives.

**Steps to reproduce**
1. Listen to enteredVehicle and changedVehicleSeat
2. Log param seatIndex of both events.

**Context (environment)**
1. Saving the seatIndex in the native natural way like its handled by GTAV itself.

**Possible solution**
You could make an own implementation to calculate the right seatIndex, but in my opionen the events should trigger in the natural native way.

**Comment by Revyn112** [comment]
![grafik](https://user-images.githubusercontent.com/7781906/107875604-3b71f680-6ec1-11eb-8915-f76f234b26f4.png)

**Comment by LeonMrBonnie** [comment]
That is not a bug but expected behaviour.
alt:V uses the values the actual game engine uses, and for the game engine the driver seat is, not -1 like in the natives.
