### ISSUE TITLE
Exceptions in input method CPU usage

### ISSUE THREAD

**Issue by Cyuancai** [altmp/altv-issues#837]
**Client/server version**

`Build #xxxx, branch x`
Build release 2.11
**Current behavior**

When the Chinese input method is enabled, press any English button to display the input content.
![image](https://user-images.githubusercontent.com/32071418/107915026-93caf600-6f9e-11eb-829d-8716f641c250.png)
Then CEF starts using CPU like crazy
![image](https://user-images.githubusercontent.com/32071418/107915066-aba27a00-6f9e-11eb-8de4-0e489762f27c.png)
**Expected behavior**

It should not take up too much CPU
**Steps to reproduce**

The following is a Chinese input method as an example. The display interface all displays Chinese by default
First, if you have to use Win10 system to prove the rigor of the experiment, And add Chinese input method in the language input, other input method can also be.
Methods the following 
![image](https://user-images.githubusercontent.com/32071418/107915332-44d19080-6f9f-11eb-8f18-292d06cc1c25.png)
![image](https://user-images.githubusercontent.com/32071418/107915359-4d29cb80-6f9f-11eb-8d01-124eb342ea72.png)
![image](https://user-images.githubusercontent.com/32071418/107915413-67fc4000-6f9f-11eb-894c-5ec968c30947.png)
Then switch the input method to Chinese
Start the ALTV client and enter a server randomly.
With the Chinese input method in the state, press any English character, cut out the game, check the CEF CPU utilization status.
**Context (environment)**

It severely affects the experience of the game and can be confusing to unsuspecting players, especially those with poor configuration
**Possible solution**

To end the CPU high usage method, call up any input box in CEF

**Comment by Th1s1sYukia** [comment]
****有解决方案吗？ ？

**Comment by Cyuancai** [comment]
有啊,但是我不想说

**Comment by Letsion** [comment]
pls. write in English pls. 😀

**Comment by ZackaryH8** [comment]
> write in English pls. 😀

```
Th1s1sYukia: ****Is there a solution? ?
Cyuancai: Yes, but I don’t want to say
```

Last 2 replies using Google translate

**Comment by C0kkie** [comment]
Can you try it on newest rc/dev build?

**Comment by FabianTerhorst** [comment]
Most likely fixed in next release. Feel free to reopen when its not fixed after next update.

**Comment by Th1s1sYukia** [comment]
Its work on me!

**Comment by Th1s1sYukia** [comment]
Good job!  Thank you for fixing it. Salute the developers.
