### ISSUE TITLE
toLocaleString / toLocaleTimeString

### ISSUE THREAD

**Issue by PepoDance** [altmp/altv-issues#839]
**Client/server version**
`Build #3.0-rc3, release candidate`

**Current behavior**
When you use the function that I provided below it returns something like; `Sat Dec 26 2020 17:22:56 GMT-0800 (Pacific Standard Time)`. 

**Expected behavior**
The function below with the options should only return the `hh:mm` so for an example; `17:22`. Before a previous update, it worked fine without any issues but I'm not sure what update this came in.

**Steps to reproduce**
1. Create a file on clientside with the following code;
```js
function getTimestamp() {
  const date = new Date();
  const results = date.toLocaleString("en-US", {
    timeZone: "America/Los_Angeles",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
  return `[${results}]`;
}
```
2. Then do `alt.log(getTimestamp());`

**Context (environment)**
N/A.

**Possible solution**
N/A.

**Comment by ZackaryH8** [comment]
Try use `toLocaleTimeString` like this 

```js
date.toLocaleTimeString("en-US", { hour: '2-digit', minute: '2-digit', hour12: false})
```

**Comment by PepoDance** [comment]
> Try use `toLocaleTimeString` like this
> 
> ```js
> date.toLocaleTimeString("en-US", { hour: '2-digit', minute: '2-digit', hour12: false})
> ```

Tried with; 
```js
function getTimestamp() {
  const date = new Date();
  const results = date.toLocaleTimeString("en-US", {
    timeZone: "America/Los_Angeles",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });

  return `[${results}]`;
}```

Returns: `[15:50:01 GMT-0800 (Pacific Standard Time)]` when it should return only `[15:50]`.

**Comment by ZackaryH8** [comment]
The code above is working fine on `alt:V Server 3.0-dev6 (dev)`

![image](https://user-images.githubusercontent.com/40175773/108438821-f1ce3680-7247-11eb-9fb4-0d52c4d41f46.png)

**Comment by ZackaryH8** [comment]
Can confirm this bug on `alt:V Server 3.0-dev6 (dev)`
The bug only seems to be present on client, server is unaffected

**Comment by losdevpath** [comment]
Confirmed bug on `alt:V Server 6.0-rc16`

**Comment by LeonMrBonnie** [comment]
Seems to be fixed since we enabled ICU
