### ISSUE TITLE
Streaming custom graphics.ytd isn't working

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#841]
**Client/server version**

`Build #2.14 branch release`

**Current behavior**
Streaming an custom graphics.ytd isn't working at the moment.

**Expected behavior**
The custom graphics.ytd should be streamed.

**Steps to reproduce**
1. Create a stream resource
|- stream
|-- assets
|--- graphics
|---- graphics.ytd (with changed textures)
|- steam.cfg
|- resource.cfg

2. Load resource with server start
3. Check if textures are changed.

**Context (environment)**
Want to change textures of radarmasksm and radarmaskxl for rounded radar.

**Possible solution**
1. Add possibility to stream graphics.ytd (update/update.rpf/x64/textures/graphics.ytd)
2. Own function to change texture on runtime #820

**Comment by C0kkie** [comment]
@Revyn112  can you upload sample ressource?

**Comment by C0kkie** [comment]
we will use this issue here #1083
