### ISSUE TITLE
Ability to get blip's scriptID

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#842]
**Suggestion**
Would be very nice to have ability to get blip's scriptID

**Use cases**
E.g. using blips as missionCreator (to identify blip from getNewSelectedMissionCreatorBlip native)
Or to use blip with natives such as setBlipAsFriendly etc.

**Describe the solution you'd like**
scriptID param

**Describe alternatives you've considered**
I create those blips with natives now, but in that way i can't e.g. shrink blip (scale only by one axis) fade them nicely.

**Comment by martonp96** [comment]
added in rc
