### ISSUE TITLE
Shoes getting changed if any undershirt is set.

### ISSUE THREAD

**Issue by mastermonk700** [altmp/altv-issues#843]
**Client/server version**

`Build #dev/3.0-dev13, branch dev`

**Current behavior**
If i change any undershirt, the shoes change.

**Expected behavior**
The Shoes should not get changed

**Steps to reproduce**
Just set an Undershirt.

**Context (environment)**
Setting an Undershirt on my Ped.

**Comment by C0kkie** [comment]
How do you set it? Any code snipped?

**Comment by mastermonk700** [comment]
player.SetClothes(8, 58, 0, 0); Serverside.

Forgot to mention, the local player shoes are right. But for other players, the shoes are replaced.

**Comment by mastermonk700** [comment]
This Bug just appears if my shoes are set to 97.

**Comment by C0kkie** [comment]
Did you download the clothes bin?

**Comment by mastermonk700** [comment]
Yes. But it just appears with Shoe Ids 96 and 97.

**Comment by YannBCF** [comment]
Could not reproduce it on the 4.0-dev3. Could you try to reproduce it on the latest dev version ?

**Comment by FabianTerhorst** [comment]
Most likey that shoe id isnt in the clothes Data yet. The next Version will Support setting clothes with setClothesDlc without the need of the clothes in the clothes.bin.

**Comment by FabianTerhorst** [comment]
Can't reproduce. Feel free to comment when the bug is still present.
