### ISSUE TITLE
Server Crashes when using explosion ammo on vehicles

### ISSUE THREAD

**Issue by Jooonaas** [altmp/altv-issues#844]
**Client/server version**

`Build #214, branch release`

**Current behavior**
If you use explosion ammo on a vehicle like a hydra the server will crash instantly.

**Expected behavior**
The server will not crash

**Steps to reproduce**
Spawn for example a hydra

**Comment by FabianTerhorst** [comment]
Pleased Show your code. It seems related to your Gamemode.

**Comment by Jooonaas** [comment]
Yes It was my error.
I am so sorry
