### ISSUE TITLE
Force Render Webview for Frontend Menus

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#848]
**Client/server version**
release

**Current behavior**
Currently a webview is toggled off when a user enters a GTA:V native frontend menu. Such as the pause menu, social club exit, etc. There is now a need for this disabled functionality to be re-enabled.

**Expected behavior**
WebViews should left alone when navigating to different GTA:V native menus. The server developers should account for these issues. 

**Steps to reproduce**
Create a WebView. Open your escape menu, options menu, or any other menu. Including ALT + F4.

**Context (environment)**
This prevents developers from overlaying webviews over existing frontend menus which is necessary to achieve a handful of new features and scripts.

**Possible solution**
Remove the statement that turns off webviews when navigating inside of a frontend menu.

**Comment by zziger** [comment]
Maybe it can be configurable via e.g. some parameter in the WebView object.

**Comment by Stuyk** [comment]
"u can render the cef on game gui stage by passing false to the constructor for isOverlay" - Tastey

Was confirmed to work. Thanks.
