### ISSUE TITLE
startResource not working on dev version

### ISSUE THREAD

**Issue by FilkodonAwang** [altmp/altv-issues#850]
`Build 3.0-dev16, branch dev`

**Current behavior**
I wanted to start a resource from an other script. 
On the version 3.0-dev16 I see in the console that the resource starting loading, but never finish with it.

<img width="169" alt="dev_version" src="https://user-images.githubusercontent.com/48822215/111647996-417e2e80-8803-11eb-8223-1160ca08fe0d.png">

**Expected behavior**
The starter scripts starting the other script.
<img width="232" alt="rc_version" src="https://user-images.githubusercontent.com/48822215/111647848-1d225200-8803-11eb-8241-d6066749f1c8.png">

**Steps to reproduce**
[attachments.zip](https://github.com/altmp/altv-issues/files/6165087/attachments.zip)

- Download the attachments
- Start the script called 'vf_starter'.
- Check the console.

**Context (environment)**
I checked the resources in other version (3.0-rc6) and everythings works as expected.

**Comment by LeonMrBonnie** [comment]
I don't see anything wrong in that log. The other resource is started normally

**Comment by FilkodonAwang** [comment]
That was the expected result, I shot from version 3.0-rc6.
The first picture is what the dev version only do.

**Comment by FabianTerhorst** [comment]
Resources got some fixed, please test again with latest dev.
