### ISSUE TITLE
add client or server functions to set the current stamina of players

### ISSUE THREAD

**Issue by ppaglier** [altmp/altv-issues#851]
**Suggestion**

add client or server functions to set the current stamina of players

**Use cases**

Actually, you can only with natives reset to 100% or restore a percent of stamina, so you can only make an unlimited stamina system, but for RolePlay for example, if we can reduce or set the current stamina, we can create some sports/medical script

**Describe the solution you'd like**

I think, a function client or server side in the player class for set or reduce the current stamina

**Describe alternatives you've considered**

i've tried to use `alt.setStat('stamina', 0);` then call the native `resetPlayerStamina`, but this native can only set stamina to 100%
and i've tried to call the native `restorePlayerStamina` with negative float but nothing happened

**Comment by TheMysteriousVincent** [comment]
Why don't you build another layer ontop the GTAV stamina system? Then implementing a serverside stamina is not needed anymore.

**Comment by John-Deamers** [comment]
Because there's actually getter and setter for the default stamina of GTA but setter can only restore stamina, so i just suggest adding 1 function for set the current stamina
If i want to reproduce all of the stamina system of GTA, i need to create synced meta, then send from client to server if my player is swimming, walking, running, etc... and on the GTA minimap, the life bar will not flicker when the player doesn't have enough stamina for run

**Comment by TheMysteriousVincent** [comment]
> If i want to reproduce all of the stamina system of GTA, i need to create synced meta, then send from client to server if my player is swimming, walking, running, etc... and on the GTA minimap, the life bar will not flicker when the player doesn't have enough stamina for run

Well, good point. But isn't just missing a native to set the stamina then?

**Comment by John-Deamers** [comment]
i already tried to find the right native but no one can set the current stamina, they can only restore a percent or full
i tried to use negative percent too, but nothing happend.
There's always unamed natives which could do that, but i didn't find it for the moment

**Comment by C0kkie** [comment]
Its possible since v13 https://docs.altv.mp/js/api/alt-client.LocalPlayer.html#_altmp_altv_types_alt_client_LocalPlayer_stamina
