### ISSUE TITLE
Client-side player.visible always return true

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#852]
**Client/server version**

`Build #2.19, branch release`

**Current behavior**
Client-side player.visible always return true

**Expected behavior**

**Steps to reproduce**
**server**: `player.visible set false`
**client**: `try to get player.visible`

**Comment by C0kkie** [comment]
Confirmed on dev/3.0-dev16

**Comment by Letsion** [comment]
Confirmed on dev/4.0-dev17

**Comment by C0kkie** [comment]
Fixed in next rc
