### ISSUE TITLE
Allow password in connect url

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#853]
**Suggestion**
Allow connect url to have a password in it `altv://connect/109.22.33.43`

**Use cases**
People who want to use connect url but have a server password

**Describe the solution you'd like**
`altv://connect/109.22.33.43` should allow the password passed as a parameter `altv://connect/109.22.33.43/password_here` or `altv://connect/109.22.33.43?password=xyz`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jovanivanovic** [comment]
+1 for the query string parameter

**Comment by LeonMrBonnie** [comment]
The connect url will support the `password` query param in the next version
