### ISSUE TITLE
Uninstaller

### ISSUE THREAD

**Issue by jovanivanovic** [altmp/altv-issues#855]
**Describe the solution you'd like**

Adding the `-uninstall` argument to the launcher to uninstall the current alt:V client installed and remove all of its files and registry data.

Would be also useful to add the uninstaller to the registry as an actual uninstaller package for alt:V 
https://docs.microsoft.com/en-us/windows/win32/msi/uninstall-registry-key?redirectedfrom=MSDN

**Comment by C0kkie** [comment]
Added in next dev
