### ISSUE TITLE
Native 0x639431E895B9AA57 - wrong parameter type

### ISSUE THREAD

**Issue by XChrome80** [altmp/altv-issues#856]
**Client/server version**
Build 2.29, branch release

**Current behavior**
 `function _0x639431E895B9AA57(ped: Ped, vehicle: Vehicle, p2: boolean, p3: boolean, p4: boolean): boolean`
p2 is a seatIndex and this function seems to cast int to boolean. So -1, 1, 2 is always true (1) and produces incorrect results.

**Expected behavior**
This undocumented native is some kind of vehicle entry-check. p2 is a seatIndex (-1,0,1,2) in the original scripts. 

`0x639431E895B9AA57(ped, vehicle, -1, false, false): `
If you park your vehicle near a wall and the ped cannot enter/exit this side, the return value toogles from true (not blocked) to false (blocked).

p3 seems relevant for motorcycles and bikes to check if the the left (false)/right (true) side is blocked (false).
p4 is unknown. Maybe relevant if you are inside or outside of a vehicle. Can be tested better if the function works correctly.

You can give a name like 'isSeatEntryAccessible' or something :-)

**Comment by ZackaryH8** [comment]
All fixes should be submitted [here](https://github.com/alloc8or/gta5-nativedb-data)

**Comment by Lhoerion** [comment]
Yes, all natives changes should be directed to alloc8or repository, as from time to time we update ours based on that file.
