### ISSUE TITLE
IVehicle::GetWheelSpeed has performance issues

### ISSUE THREAD

**Issue by YannBCF** [altmp/altv-issues#857]
**Client/server version**
dev/3.0-dev16

**Current behavior**
```JS
class TicksController {
    lowTick: number | null;
    lowTickContent: any[];

    constructor() {
        this.lowTick = null;
        this.lowTickContent = [];
        alt.setTimeout(() => {
            return;
        }, 1);
    }

    lowTickHandler(): void {
        // this.lowTickContent[i].vehicle = alt:V vehicle entity
    
        //! Doesn't output a warning
        this.lowTickContent.forEach(item => {
            API.Views.front.emit('speedo', speedoState.update, native.getEntitySpeed(item.vehicle.scriptID), 0, 0);
        });

        // Output a warning of 17 ms
        for (let i = 0, l = this.lowTickContent.length; i < l; i++) {
            API.Views.front.emit('speedo', speedoState.update, this.lowTickContent[i].vehicle.speed, 0, 0);
        }
    }

    insertLowTick(items: any[]): void {
        if (this.lowTick === null) {
            this.createLowTick();
        }

        for (let i = 0, l = items.length; i < l; i++) {
            this.lowTickContent.push(items[i]);
        }
    }

    createLowTick(): void {
        this.lowTick = alt.setInterval(this.lowTickHandler.bind(this), ticks.low);
    }
}
```
The warning ONLY appear when you just started your game, if you reconnect via the debug option, it won't appear.
The warning ONLY appear in the FIRST loop of the interval.

**Expected behavior**
It should not output any warning log in the F8 console

**Steps to reproduce**
I posted my code, you can replace ``API.Views.front.emit`` by a simple ``webivew.emit`` as it's a simple wrapper class

**Context (environment)**
I try to make a global interval controller of different layers /delays. Here i insert to the lowTick method the alt:V vehicle object into the ``lowTickContent`` array, that gets processed by the lowTick interval (50 ms) running. If no inveral is running, it gets created, if nothing is actually in the content the interval will be cleared.

**Comment by tastydev** [comment]
seems like the performance issue is in alt-core `vehicle->GetWheelSpeed()`

**Comment by LeonMrBonnie** [comment]
Not related to the JS module accessor, caused by the internal method.
This might actually be a problem with caching inside the engine.

**Comment by martonp96** [comment]
The first call of GetWheelSpeed will do a signature scan on the game's memory and cache its value. I'm not sure if it worth fixing.

**Comment by LeonMrBonnie** [comment]
As the devs have already pointed out, this is expected behaviour.
This happens only for the very first call to the method, so this should not really cause any issues.
