### ISSUE TITLE
IVehicle::GetWheelSpeed always returns 0 for model sanchez and sanchez2

### ISSUE THREAD

**Issue by YannBCF** [altmp/altv-issues#859]
**Client/server version**
dev/3.0-dev16

**Current behavior**
The vehicle speed getter seem to always return 0 on the following vehicle models : ``sanchez`` and ``sanchez2``

**Expected behavior**
It should return the actual speed of the vehicle

**Steps to reproduce**
```JS
alt.on('enteredVehicle', onEnteredVehicle);

let interval: number | null = null;
let lastSpeed = 0;

function onEnteredVehicle(vehicle: alt.Vehicle, seat: number): void {
    if (interval !== null) {
        return;
    }

    interval = alt.setInterval(() => intervalHandler(vehicle), 50);
}

function intervalHandler(vehicle: alt.Vehicle): void {
    // const speed = Math.ceil(native.getEntitySpeed(vehicle.scriptID) * 3.6);
    const speed = Math.ceil(vehicle.speed * 3.6);
    console.log(`Speed: ${speed}`);
    console.log(vehicle.model);

    if (speed === lastSpeed) {
        console.log('I break');
        return;
    }

    console.log('I run');
    API.Views.front.emit('speedo', speedoState.update, speed, vehicle.gear, 0);
    lastSpeed = speed;
}
```
NOTE: The native way ``const speed = Math.ceil(native.getEntitySpeed(vehicle.scriptID) * 3.6);`` returns the actual speed of those models

**Possible solution**
I don't know

**Comment by martonp96** [comment]
vehicle.speed is the value on the gauge on the dashboard, not the "speed" for calculating use the vector one

**Comment by LeonMrBonnie** [comment]
As Vektor said, working as intended.
