### ISSUE TITLE
Intermittent Pattern not Found

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#860]
**Client/server version**
Client: 2.23/Release

**Current behavior**
Client fails to load and throws `Pattern not found`
![image](https://user-images.githubusercontent.com/40175773/113481147-cf0e7f00-948f-11eb-8fca-09fd809a4d8f.png)

**Expected behavior**
alt:V should load without any errors

**Steps to reproduce**
Currently not reproducible 

**Context (environment)**
N/A

**Possible solution**
Restarting the machine seems to be fixing the issue

**Comment by jovanivanovic** [comment]
Reproduction steps would help

**Comment by ZackaryH8** [comment]
> Reproduction steps would help

- Open alt:V Client
- Wait for the Error message (this doesn't always come up)

There is nothing in the logs that would suggest an error

**Comment by C0kkie** [comment]
@ZackaryH8  is that still a issue?
