### ISSUE TITLE
When players explode while spawning, the client crashes

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#861]
**Client/server version**
3.0-dev16 (dev)

**Current behavior**
When a player explodes in succession (probably when spawning the player). the client crashes. 

**Expected behavior**
If he dies and dies again the player should respawn normally without crashing

**Steps to reproduce**
Several cars spawn... Stand next to the one car and explode a car with an Assaultrifle or Drive a vehicle into a gas station. 
Spawn the player again in the playerdeath event: 
Serverside:
```
import * as alt from'alt-server';

alt.on('playerConnect', (player) => {
    player.model = "mp_m_freemode_01"
   player.spawn(0,0,76,0);
   new alt.Vehicle('adder',2,2,76,0,0,0);
});

alt.on('playerDeath', (player, killer, weapon) => {
    player.spawn(player.pos.x, player.pos.y, player.pos.z, 0);
});
```
Crashdrumps:
[altv_3.0-dev16_Social Club_0x2cc9b8_05-04-2021_22-53-59.zip](https://github.com/altmp/altv-issues/files/6260806/altv_3.0-dev16_Social.Club_0x2cc9b8_05-04-2021_22-53-59.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_05-04-2021_22-48-48.zip](https://github.com/altmp/altv-issues/files/6260812/altv_3.0-dev16_Social.Club_0x2cc9b8_05-04-2021_22-48-48.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_05-04-2021_22-28-01.zip](https://github.com/altmp/altv-issues/files/6260814/altv_3.0-dev16_Social.Club_0x2cc9b8_05-04-2021_22-28-01.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_05-04-2021_22-05-31.zip](https://github.com/altmp/altv-issues/files/6260815/altv_3.0-dev16_Social.Club_0x2cc9b8_05-04-2021_22-05-31.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_05-04-2021_21-57-56.zip](https://github.com/altmp/altv-issues/files/6260816/altv_3.0-dev16_Social.Club_0x2cc9b8_05-04-2021_21-57-56.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_24-03-2021_22-35-46.zip](https://github.com/altmp/altv-issues/files/6260817/altv_3.0-dev16_Social.Club_0x2cc9b8_24-03-2021_22-35-46.zip)
[altv_3.0-dev16_Social Club_0x2cc9b8_24-03-2021_21-50-16.zip](https://github.com/altmp/altv-issues/files/6260819/altv_3.0-dev16_Social.Club_0x2cc9b8_24-03-2021_21-50-16.zip)

Videos:
  On My server scripts:
  [2021-04-05 22-27-32.zip](https://github.com/altmp/altv-issues/files/6260529/2021-04-05.22-27-32.zip)
  Server only with the code up there:
  https://user-images.githubusercontent.com/69867073/113626023-eac97f00-9661-11eb-977e-5ca739b50859.mp4

**Comment by LeonMrBonnie** [comment]
Confirmed on 4.0-dev3

**Comment by Andrik-WX** [comment]
confirmed on 2.20 (release)
Crashes just like in the videos above.

**Comment by Letsion** [comment]
confirmed on 4.0-dev13

**Comment by C0kkie** [comment]
@Letsion  Is this still  a thing?

**Comment by Letsion** [comment]
I look at the Issue the week @C0kkie

**Comment by C0kkie** [comment]
Okay thanks @Letsion

**Comment by Letsion** [comment]
I could not reproduce the error.
The player is no longer "revived" when spawn is called during an explosion (probably correct error handling). But remains lying on the ground etc. You can live with that.
Issue is fixed
