### ISSUE TITLE
Add generic event handler to JS module

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#864]
**Suggestion**

Add the ability to catch ALL server events (should maybe exclude alt:V events and only include custom events?) and ALL client events.

**Use cases**

Benchmarking for example and a lot more.

**Describe the solution you'd like**

```js
alt.on((eventName, ...args) => { });
```

**Describe alternatives you've considered**

Writing a wrapper for events.

**Additional context**

Needs some work on the event handling inside JS module.
Should be available on both sides (client & server).

**Comment by FabianTerhorst** [comment]
For clientside e.g. #498

**Comment by LeonMrBonnie** [comment]
Available the next time the JS module is updated on the CDN.
