### ISSUE TITLE
altV Native isPointOnRoad -> return Problem

### ISSUE THREAD

**Issue by uzJT92** [altmp/altv-issues#867]
**Client/server version**
`Build 2.23, branch release`

**Current behavior**
Native isPointOnRoad always returns false.
https://natives.altv.mp/#/0x125BF4ABFC536B09

**Expected behavior**
Should return true, when user stays on road

**Steps to reproduce**
https://pastebin.com/49qrjvZq

**Context (environment)**
I want to detect if a player tries to plant an object on streets.

**Possible solution**
Dunno

**Comment by LeonMrBonnie** [comment]
You should check if this also happens on other GTA MP mods or singleplayer, I assume this is not an alt:V problem, because alt:V does not do modifications to the natives that would cause that.

**Comment by uzJT92** [comment]
Ok thank you for the quick response

**Comment by deluvas1911** [comment]
I'm using this native and always get reliable results from it. Can you show how you call it?

**Comment by uzJT92** [comment]
seems to work now with undefined. Issue can be closed. Thanks and sorry for the entrance
