### ISSUE TITLE
make a good cdn the actual is very shit

### ISSUE THREAD

**Issue by dictateurfou** [altmp/altv-issues#869]
i explain the problem we dev one server for multiple month all work good no problem we add cdn for allow user to download at the same time when we have cdn we crash after the download complete without cdn we d'ont crash the system for download is very poor because he curl all resource at the same time for make a download speed its hard we have use 1.tb of bp for 2h AND THE LAST MAYBE YOU CRASH 9/10 when connect with cdn in front of more than 600 people

**Comment by LeonMrBonnie** [comment]
Next time create an issue where you follow the template and use a normal title.
