### ISSUE TITLE
Store client->webView events emitted before webView loading

### ISSUE THREAD

**Issue by combowomb0** [altmp/altv-issues#870]
**Client/server version**
`Build #2.23, branch release`

**Current behavior**
Events emitted before loading are not handled

**Expected behavior**
Such events should be handled

**Steps to reproduce**
`client.js`
```ts
const view = new alt.WebView(...);
view.emit('someEventName');
```
`view.js`
```ts
window.alt.on('someEventName', () => {
  // it will never happen :(
});
```

**Context (environment)**
n/a

**Possible solution**
You can make your own buffer
Example:
```ts
type TBuffer = {
  eventName: string;
  args: any[];
};

class WebViewWrapper {
  public instance: alt.WebView;

  private isLoaded = false;
  private readonly buffer = new Set<TBuffer>();

  public constructor() {
    this.instance = new alt.WebView('...');
    this.instance.on('load', this.handleLoad);
  }

  private readonly handleLoad = () => {
    this.isLoaded = true;

    if (this.buffer.size > 0) {
      this.buffer.forEach(({ eventName, args }) => {
        this.instance.emit(eventName, ...args);
      });

      this.buffer.clear();
    }
  };

  public emit = (eventName: string, ...args: any[]) => {
    if (this.isLoaded) {
      return this.instance.emit(eventName, ...args);
    }

    this.buffer.add({ eventName, args });
  };
}
```

**Comment by LeonMrBonnie** [comment]
https://github.com/altmp/altv-client-js/pull/37#issuecomment-767815043
Vadzz already said some time ago, that this will be added to alt:V core in the future.

**Comment by combowomb0** [comment]
@LeonMrBonnie Tuxick said to create issue 🤔

**Comment by LeonMrBonnie** [comment]
> 
> 
> @LeonMrBonnie Tuxick said to create issue 🤔

I just wanted to clarify that this was already planned. This issue can stay open so we can track the progress

**Comment by YannBCF** [comment]
Implemented in https://github.com/altmp/altv-js-module/pull/89
