### ISSUE TITLE
Error in the operation of two WebView

### ISSUE THREAD

**Issue by moysha-tsoref** [altmp/altv-issues#871]
**Client/server version**

`server #2.8, branch release`

**Current behavior**

The second WebView does not open if you click on "`<select><select/>`" in the first one"

**Steps to reproduce**

      
Client
```
import alt from 'alt-client';
      
let select = new alt.WebView("http://resource/client/browser/test2/index.html");`
let oneTwo = new alt.WebView("http://resource/client/browser/test1/index.html");

alt.showCursor(true);
alt.toggleGameControls(false);

alt.on("keydown", (key) => {
    if(key == 73) {
        oneTwo.isVisible = !oneTwo.isVisible
    }
});

alt.on("keydown", (key) => {
    if(key == 74) {
        select.unfocus();
        oneTwo.focus();
    }
});

alt.on("keydown", (key) => {
    if(key == 75) {
        oneTwo.unfocus();
        select.focus();
    }
});
```

test2.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<select>
    <option value="1">123</option>
    <option value="2">123</option>
    <option value="3">123</option>
</select>
</body>
</html>
```
test1.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
1321231321313131313131313131
</body>
</html>
```
1) Click on the "I (key == 73)" button to hide "test1.html"
2) Click on "K (key == 75)" to set the focus to "test2.html"
3) Click on the drop-down menu (<>select</>)
4) Press the button "J (key == 74)" or "I (key == 73)" in any sequence to show "test1.html"
Result: "test1.html" won't appear

P.S. If "select" is replaced with "input" - everything will work

**Context (environment)**

I need to switch browsers between each other. They cannot be deleted. I only need to hide it via isVisible

**Comment by LeonMrBonnie** [comment]
Fixed on dev
