### ISSUE TITLE
Player property isTalking is always active

### ISSUE THREAD

**Issue by pixlcrashr** [altmp/altv-issues#874]
**Client/server version**

`v2.23`

**Current behavior**
The player property `isTalking` is always true when voice activation is enabled. The property is not affected when using Push-To-Talk.

**Expected behavior**
The property `isTalking` should only be true when the voice activation threshold is exceeded **OR** when Push-To-Talk is being used - e.g. when data is being **transmitted**.

**Steps to reproduce**
1. Enable voice activation and set a threshold which fits for you the best.
2. Setup an alt:V server aswell as an alt:V voice server and configure it to work.
3. Add the following code to a resource (to have a debug output):
```js
import * as alt from 'alt-client';

alt.everyTick(() => {
    alt.log(`${alt.Player.local.isTalking}`);
});
```
4. Log on to the server and try talking.

**Context (environment)**
Everywhere.

The fact that that this property is not working as expected removes the ability to check whether or not a player is **transmitting** data to the voice server. Therefore, it is only possible to check whether or not the player has **local** voice input gain (**input gain** != **transmitting data**).

**I did not check, whether or not `isTalking` is always active on other players than the local one.**

**Possible solution**
Well, fix the condition on which `isTalking` is set on the local player.

**Comment by TheMysteriousVincent** [comment]
@vadzz-dev Any news on this?

**Comment by FabianTerhorst** [comment]
IsTalking is basically .micLevel > 0.

**Comment by TheMysteriousVincent** [comment]
> IsTalking is basically .micLevel > 0.

Yes, but again, the property `isTalking` IS NOT an indicator whether a player is really talking (e.g. actual sent voice data). Either implement the condition described above and/or rename the property `isTalking` to `isMicActive`.

Thanks in advance.

**Comment by FabianTerhorst** [comment]
Can you check what .micLevel returns for you?

**Comment by FabianTerhorst** [comment]
Maybe the mic level is lower when voice activation isnt hit.

**Comment by TheMysteriousVincent** [comment]
> Can you check what .micLevel returns for you?

> Maybe the mic level is lower when voice activation isnt hit.

This is the result:

The `micLevel` property of a player returns the device's input gain volume when the **microphone is activated**.
Def.: The microphone is activated **if and only if** voice activation is enabled *OR* voice activation is disabled and the Push-To-Talk key is pressed down.

The key point which I also tried to underline in the issue description is that the condition **microphone activated/deactivated** is **NOT** equal to the condition **transmitting voice-data** to the voice server.

Again, there is a need to be able to check if a player is **actually transmitting data to the voice server**.

**Comment by C0kkie** [comment]
fixed in v15
