### ISSUE TITLE
Opening RSS feed through exit screen possible

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#875]
**Client/server version**

`Build #2.23, branch release`

**Current behavior**
After pressing alt+f4 or clicking exit, you can click through the exit screen and open the rss feeds in the browser

**Expected behavior**
Exit screen not passing through the mouse click to the rss feed view

**Steps to reproduce**
Open custom launcher with rss feed
Press alt+f4 or click exit
Click on the location where the rss feed is
=> browser opens

**Context (environment)**
Windows 10
GTA 5 on steam

**Possible solution**
Don't passthrough the clicks on the exit screen

**Comment by C0kkie** [comment]
Its related to this: https://github.com/altmp/altv-issues/issues/702
