### ISSUE TITLE
Player.isDead is always true on debian C#

### ISSUE THREAD

**Issue by AliveShiro** [altmp/altv-issues#876]
**Client/server version**
`Server  Version 2.22, branch release`

**Current behavior**
The player getter `player.isDead`  always returns `true` on my server, Debian10, however on Windows it returns the correct value (true if player is dead, false if player is alive)

**Expected behavior**
The getter should return the correct value.

**Steps to reproduce**
Server: 
```c
using AltV.Net;
using AltV.Net.Data;
using AltV.Net.Elements.Entities;
using AltV.Net.Enums;
using System;

namespace Server.Scripts
{
    internal class Server : IScript
    {
        [ScriptEvent(ScriptEventType.PlayerConnect)]
        public void PlayerConnect(IPlayer player, string reason)
        {
            player.SetDateTime(DateTime.Now);
            player.Model = (uint)PedModel.FreemodeMale01;

            // Spawns the player at coordinates x, y, z, with a delay of 1000 Milliseconds.
            player.Spawn(new Position(813, -279, 66), 1000);

            player.Emit("Client:Spawn");
        }

        [ClientEvent("Server:ClientSpawned")]
        public void PlayerSpawned(IPlayer player)
        {
            Alt.Log($"player.isDead: {player.IsDead}");
        }
    }
}
```

Client:
```js
import * as alt from 'alt-client';

alt.onServer('Client:Spawn', () =>
{
    alt.emitServer('Server:ClientSpawned');
});
```

**Comment by FabianTerhorst** [comment]
Please test the same with the js module to verify its a core bug.

**Comment by AliveShiro** [comment]
If I am not mistaken, there is no isDead getter in js module

**Comment by LeonMrBonnie** [comment]
> 
> 
> If I am not mistaken, there is no isDead getter in js module

Please report such missing things next time, otherwise it will never be noticed.
I will test this today and add the property to JS module.

**Comment by LeonMrBonnie** [comment]
Checked this with JS module, it worked fine. So this seems to be a problem with the C# module.

**Comment by FabianTerhorst** [comment]
with which linux debian version you tested?

**Comment by LeonMrBonnie** [comment]
Debian 9

**Comment by FabianTerhorst** [comment]
@AliveShiro can you tell us your debian version?

**Comment by FabianTerhorst** [comment]
> Debian 9

Afaik you should use debian 10.

**Comment by AliveShiro** [comment]
I am using Debian 10

**Comment by LeonMrBonnie** [comment]
Nvm, I thought I was using Debian but I actually switched my WSL machine to Ubuntu 20.
I don't have any disk space to install Debian to test it, so this will have to wait until it is merged into the JS module and someone else can test it.

**Comment by AliveShiro** [comment]
If you are allowed to give me the compiled js module with the isDead getter I can test it on my machine and tell the outcome.

**Comment by LeonMrBonnie** [comment]
Sure.
[js-module.zip](https://github.com/altmp/altv-issues/files/6376459/js-module.zip)

**Comment by AliveShiro** [comment]
Hmm... can't test this on Debian 10 due to missing `GLIBCXX_3.4.26` in Debian 10.
All needed packages are installed in latest available Version from packagemanager (apt)

**Comment by AliveShiro** [comment]
Just tested on a fresh Debian11 VM, with js-module the getter is working as intended, but with csharp-module the getter always returns `true`.

Tested with Server Version `alt:V Server 4.0-dev5 (dev)`

**Comment by FabianTerhorst** [comment]
Test both modules on the Same Branch. I cant See anything that causes it. Maybe use Clean Server and without async.

**Comment by FabianTerhorst** [comment]
fixed in c# rc update
