### ISSUE TITLE
Sending big amount of data from client to server is broken

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-issues#879]
**Client/server version**

`Build #dev/4.0-dev5, branch dev`

**Current behavior**

When transmitting a big amount of data from client to server (e.g. a screenshot taken with `alt.takeScreenshot`) only a partial amount of the data is received on the serverside. 

**Expected behavior**

The maximum size the client can send to server has been increased to UINT32_MAX bytes in a prior update, this has worked fine for e.g. sending a screenshot from client to server before.

**Steps to reproduce**

Client:
```js
let screen = await alt.takeScreenshot();
alt.log(screen.length);
alt.emitServer("getScreenshot", screen);
```
Server:
```js
alt.onClient("getScreenshot", (player, screenshot) => {
    alt.log(screenshot.length);
});
```

**Context (environment)**

Sending a screenshot from client to server.

**Possible solution**

This has appeared since the packet compression is available in dev branch, so it is probably related.

**Comment by inpex** [comment]
this problem still persists. would it be possible to fix this. before merging in release. For us an actively used function

**Comment by FabianTerhorst** [comment]
We prefered to limit the amount of data. Thats why limit is now added again. Client as a http client for that now.

**Comment by LeonMrBonnie** [comment]
> 
> 
> We prefered to limit the amount of data. Thats why limit is now added again. Client has a http client for that now.

Or WebSocketClient.
