### ISSUE TITLE
Delays in CEF 

### ISSUE THREAD

**Issue by SofiaVantablack** [altmp/altv-issues#943]
**Client/server version**
2.23 | Current, I really don't know where to find it I installed altv once again yesterday. 

**Current behavior**

Hi! For several months I have had a problem with the CEF interface jamming. The problem is that the interface delays when you click the mouse and type on the keyboard. The problem does not always occur, it's pretty random. Sometimes delay are shorter, sometimes longer. The longest delay time I observed was 15 seconds.
In my opinion, I have the right computer to play GTA V (my specs are listed below) without any problems, in singleplayer there is no such problem and I can play with ultra settings without any frame drops.

I have tried many methods of fixing the problem, but none of them has brought the expected result:

- reinstall ALTV, GTA and Windows,
- limit frames by nvidia panel for the "webview" process,
- I tried to play without mods and with NVE (installing NVE doesn't change much),
- setting the priority of webview, gta5 and altv in the task manager,
- turning vsync on and off,
- of course I did all the troubleshooting steps from official altv guide,
- turning off GPU acceleration in windows settings.
- running altv and webview as an administrator

Two videos of my issue: https://imgur.com/a/IrwBkUg

**Expected behavior**

CEF is responsive without delays (it feels like dream for me)

**Steps to reproduce**

- The problem is likely dependent on **GPU usage**, however, it often occurs with 86% usage of GPU as well,
- the problem does not occur for everyone, I have friends with hardware that are much weaker than mine, and where this error does not appear,
- ALTV-Webview's GPU consumption sometimes reaches **50%**, 
![image](https://user-images.githubusercontent.com/83585885/117741209-2972cc00-b202-11eb-805c-97edc01ccb2a.png)
 _last one is gpu usage_
- delays are shorter when altv is not the current window I'm on (while GTA is open in window mode).
- **bug only affects displaying**, for example: when I write something on chat and send it, it's send in real time 

**My specs**

- GTX 980 
- i7-4790k
- 16 GB RAM
- GTA and Altv both installed on M2 drive.

**Possible solution**

- Maybe build in frame limiter or option to turn off the hardware acceleration in atlv settings. 
- Turning off the MSAA and turning on V-SYNC works for some people propably because that two steps are reducing GPU ussage.

**Comment by zziger** [comment]
For me that problem occurs everytime i have GPU usage over 98%

**Comment by SofiaVantablack** [comment]
> For me that problem occurs everytime i have GPU usage over 98%

Sure, but I really know a lot of people with GPU even over 99% without this issue.

**Comment by cuBeUrg** [comment]
#780 , issue created by me a while ago, is the same problem.

**Comment by SofiaVantablack** [comment]
For some reason the delays are shorter or completely doesn't appear when I play on full screen, not the borderless one.

**Comment by EiDay** [comment]
I have same issue on gtx 1080, fullscreen is somehow fixing it a bit.

**Comment by SofiaVantablack** [comment]
Ok I found something interesting, it appears that similar issue was in FiveM before, it was fixed by adding this option:
![image](https://user-images.githubusercontent.com/83585885/123000696-31e92580-d3b0-11eb-9196-5f96203cd73b.png)

**Comment by zziger** [comment]
As i see that option adds `--in-process-gpu` switch to the cef
https://github.com/citizenfx/fivem/blob/e80b826a45087e749bb95fcb175a50ac51e9750a/code/components/nui-core/src/NUIApp.cpp#L192
Maybe it would be possible to implement that via option in the altv.cfg?

**Comment by C0kkie** [comment]
Should be fixed with release 6.0
