### ISSUE TITLE
Play 3D spatial audio

### ISSUE THREAD

**Issue by mrgharabaghi** [altmp/altv-issues#945]
**Suggestion**
Add functions to play 3D spatial audio file with client side alt:V `Voice` Class.
This feature can added from server side alt:V `VoiceChannel` Class (Stream audio file).

**Use cases**
I have several audio files in `mp3` and `wave` format that should be played in 3D spatial by the server or client side in a specific coordinate or from a specific entity such as a vehicle.

**Describe alternatives you've considered**
I have another solution for play from server side.
First, the audio files are stored on the client side and each has a specific name or ID and on the server side, the name or ID of that file is sent to the client and the audio is played (3D spatial) in a specific coordinate or from a specific entity such as a player or vehicle.

**Additional context**
https://docs.altv.mp/js/api/alt-client.Voice.html
https://docs.altv.mp/js/api/alt-server.VoiceChannel.html

**Comment by LeonMrBonnie** [comment]
A `Audio` class to allow that is currently being implemented.

**Comment by mrgharabaghi** [comment]
A new idea came to my mind that is very efficient.
In the function that is supposed to play the sound in a coordinate or a specific entity, an additional parameter called `range` is placed.
In fact, this parameter specifies the radius of sound transmission. For example, if the input parameter is `1000`, it is clear that this sound is a very loud sound like an explosion and has a high playback radius, but if parameter `5` is given, it is clear that for a very quiet sound like a human speaking.

**Comment by C0kkie** [comment]
Possible with sound category in v15
