### ISSUE TITLE
Mounter for water_file

### ISSUE THREAD

**Issue by ThePawlow** [altmp/altv-issues#946]
**_Suggestion_**
Add `water_file` as a new data file mounter

**_Use cases_**
Adding custom water areas for his needs

**_Describe the solution you'd like_**
There're already several data types available, but this one is missing

**_Describe alternatives you've considered_**
Creating it via. 3ds Max, which makes things unneeded complicated

**_Additional context_**
N/A

**Comment by C0kkie** [comment]
Works in newest dev
