### ISSUE TITLE
emitClient to specified player array

### ISSUE THREAD

**Issue by KifKick** [altmp/altv-issues#948]
**Suggestion**

Add option to use alt.emitClient to specified player array

**Use cases**

Emiting event for specified player array, like in distance etc

**Describe the solution you'd like**

```ts
alt.emitClient(player: alt.Player | alt.Player[] | null, eventName: string, ...args: any[])
```

**Describe alternatives you've considered**

Using forEach and emit to every player

**Additional context**

https://docs.altv.mp/js/api/alt-server.html#_altmp_altv_types_alt_server_emitClient

**Comment by tastydev** [comment]
implemented in next build
