### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by 2563411574** [altmp/altv-issues#950]
**Suggestion**
add more client languages to ALTV

**Use cases**
Attract more players

**Describe the solution you'd like**
I will help translate

**Describe alternatives you've considered**
Provide a translation channel

**Additional context**
Chinese

Hello, can I add more client languages to ALTV?
Maybe I can contribute my strength Chinese

**Comment by C0kkie** [comment]
You can contribute here: https://github.com/altmp/altv-locales
