### ISSUE TITLE
Setting tractionLossMult doesn't seem to work

### ISSUE THREAD

**Issue by lackos888** [altmp/altv-issues#952]
**Client/server version**

`Build #2.24, branch release`

**Current behavior**
I'm setting tractionLossMult to non-proper values like 300, and it doesn't affect the traction after reaching like 50 km/h. 
Setting lowSpeedTractionLossMult works and it really affects traction under like 50 km/h.

Getting the current value always work for tractionLossMult and lowSpeedTractionLossMult.

**Expected behavior**
Affecting traction.

**Steps to reproduce**
```
/crun localPlayer.vehicle["handling"]["lowSpeedTractionLossMult"] = 300;
```
=> you can't really move forward with your car | under like 50 km/h

```
/crun localPlayer.vehicle["handling"]["lowSpeedTractionLossMult"] = 1.14;
```
=> you can now move forward, drift at low speed, etc. | under like 50 km/h

=
```
/crun localPlayer.vehicle["handling"]["tractionLossMult"] = 300;
```
=> nothing happens at higher speeds

```
/crun localPlayer.vehicle["handling"]["tractionLossMult"] = 0;
```
 => nothing happens at higher speeds

**Context (environment)**
I'm trying to add unique vehicle settings/builds like in other games.

**Possible solution**
Debugging lmao.

**Comment by WhishN** [comment]
Be aware that this value only affects driving off-road.

```js
alt.on("gameEntityCreate", (entity) => {
    if(entity instanceof alt.Vehicle) HandleVehicleCreate(entity);
})

function HandleVehicleCreate(vehicle) {
    vehicle.handling.tractionLossMult = 10;
}
```

Just tested with this code. Working as intended.

**Comment by lackos888** [comment]
Now thats some weird stuff, lowSpeedTractionLossMult works on asphalt, but tractionLossMult only works on mud/while offroading. Can I somehow use tractionLossMult on asphalt aswell?

**Comment by martonp96** [comment]
The feature works as intended.
