### ISSUE TITLE
alt.Player.prototype not working properly when called from a alt.onClient event (sometimes)

### ISSUE THREAD

**Issue by FrankoFM** [altmp/altv-issues#954]
**Client/server version**

`Build #2.24, branch release`

**Current behavior**

I have an issue with prototypes. The player class from alt.onClient seems not to have the prototype functions and variables sometimes. Giving me the error: 'TypeError: player.[myPrototypeFunc] is not a function'
The weird thing is that it is working 20% of the time (for the event that is giving me the errors)
Yes, I know prototypes only work in the same resource and it is in the same resource.
And the same prototype function is working (sometimes from THE client event, and everytime called from another client event)

**Expected behavior**

The player class from onClient should deliver the prototype function everytime without any errors.

**Steps to reproduce**

Can't really tell. What I noticted is that when I start my server and wait like 60s to connect its more likely to work. But doesn't help everytime. (And yes, everything is loaded. So its not the prototype functions not loading because the same function is callabel with other events and stuff)

**Context (environment)**

I'm trying to execute a function that uses an item.

**Possible solution**

Idk.

Thanks for the help!

**Comment by LeonMrBonnie** [comment]
Please provide reproduction code

**Comment by FabianTerhorst** [comment]
Prototype only works inside the same resource.

**Comment by FrankoFM** [comment]
> Prototype only works inside the same resource.

You didn't even read my text :(

> Please provide reproduction code

It is nearly impossible to recereate.


Is there maybe a way to reinitialize prototypes for the player?

**Comment by LeonMrBonnie** [comment]
> Is there maybe a way to reinitialize prototypes for the player?
I mean you can make a function to register your prototype extensions, but I think the issue lies somewhere in your script, as I never heard about this issue before and very many people are using prototypes on both client- and serverside.
You need to debug it to find the cause for it, and then write some reproduction code, otherwise it's impossible for me to look deeper into it.

**Comment by FrankoFM** [comment]
I totally agree with you. Now its really hard the recreate even on my main server. It is working 95% of the time now.
I tried to do the same things on a test server but dont get it to not work haha.

**Comment by FrankoFM** [comment]
Client:
```
inventoryView.on('use', (item) => {
    alt.emitServer('Inventory:UseItem', item);
})
```

Server:
```
alt.onClient('Inventory:UseItem', (player, item) => {
    player.useItem(item);
})
```

Prototype:
```
alt.Player.prototype.useItem = function(item){
    inventoryFunctions.useItem(this, item);
}
```

The file where the prototypes are created is loaded, and yes before the event is called (even when the bug occurs)
So I guess the problem is that the player object given from the onClient isn't the right player but that is impossible i guess. I think im going crazy or something

**Comment by FrankoFM** [comment]
I outsourced my prototype file in different categories, seems like it is working now.
