### ISSUE TITLE
alt:V doesn't start with epic games

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-issues#957]
**Client/server version**

`alt:V build #2.24, branch release`

**Current behavior**
When running altv.exe and the epic games launcher is not running, you aren't loggedin or GTA:V has an update available alt:V launcher is stuck and loads infinitely.

**Expected behavior**

alt:V should start.

**Possible solution**

- Check if Epic Games Launcher process is running, otherwise start it.
- use [EOS](https://dev.epicgames.com/docs/services/en-US/EpicAccountServices/GettingStarted/index.html) and check if user is authenticated.

**Comment by FabianTerhorst** [comment]
Im using Epic Games myself and never had a Problem with it. Maybe it works better with current Dev branch.

**Comment by xLuxy** [comment]
When starting alt:V (and there's an update available) it will start the Epic Games Launcher and will also update the game. However, once completed the alt:V Launcher has to be restarted.

Not quite sure if it still a bug or just a small "flaw"

**Comment by deluvas1911** [comment]
That bug mostly happens when Rockstar Games Launcher isn't loaded with admin context & enabled UAC

**Comment by juztim** [comment]
Can't repro anymore, seems fixed
