### ISSUE TITLE
Vehicle bumpers are destroyed when creating a vehicle

### ISSUE THREAD

**Issue by xLuxy** [altmp/altv-issues#958]
**Client/server version**

`Build 4.0-dev9, dev`

**Current behavior**
When spawning certain vehicles the bumper will fall off. For example fbi or fbi2.

This didn't happen earlier tomorrow when i switched from release (2.24) branch to dev.

**Expected behavior**
Vehicles should not be loosing their bumpers upon creation

**Steps to reproduce**
Spawn a vehicle on server side:

**CSharp:**
```csharp
[Command("veh")]
public static void VehicleCommand(IPlayer player, string modelName = "adder")
{
    var vehicle = Alt.CreateVehicle(Alt.Hash(modelName), player.Position, player.Rotation);
}
```

**JS:**
```js
import alt from "alt-server";

// i don't have the chat api - change this
alt.onClient("spawnVehTest", (player: alt.Player, modelName: string) => {
  new alt.Vehicle(modelName, player.pos.x, player.pos.y, player.pos.z, 0, 0, 0);
});
```

**Context (environment)**
N/A

**Possible solution**
N/A

**Comment by xLuxy** [comment]
I found the issue: i was still using release data files which are somehow not compatible with dev branch. According to Heroin nothing changed there.

**Comment by htg115** [comment]
I'm also experiencing the same issue. I observed the following two cases repeatedly:

1. Bumper just falls off and that's it.
2. Duplicate bumper lays on the ground, while a bumper correctly sits on the vehicle.

I also tried different Z axis heights, with no noticeable change.

**Comment by zziger** [comment]
This is the issue only if you spawn vehicles via C# module. I guess the module needs to be updated.

**Comment by xLuxy** [comment]
> This is the issue only if you spawn vehicles via C# module, i wasn't able to reproduce that bug on latest JS module. I guess the C# module needs to be updated.

I tested it on both and both are broken for me.

**Comment by FabianTerhorst** [comment]
Solved by updating cpp sdk
