### ISSUE TITLE
Add Entity.invincible property

### ISSUE THREAD

**Issue by R0ckzo0r** [altmp/altv-issues#96]
Serverside API to set a EntityInvincible true/false

**Comment by FabianTerhorst** [comment]
player invincible setter/getter will be available on next release.

**Comment by EtzBetz** [comment]
What about vehicles?

**Comment by FabianTerhorst** [comment]
They dont have a invincible state in gta.

**Comment by tastydev** [comment]
what about enabling entity proofs for vehicles as invincible setter for vehicles? @FabianTerhorst

**Comment by FabianTerhorst** [comment]
didnt saw a invincible serverside for vehicle.

**Comment by FabianTerhorst** [comment]
Proofs are easy to implement
