### ISSUE TITLE
Motorcycles spawn stuck in the air

### ISSUE THREAD

**Issue by Letsion** [altmp/altv-issues#960]
**Client/server version**

4.0-dev9 (dev)

**Current behavior**

Motorcycles spawn in the air and are solid

Error Serverside:
```
[22:19:50][Error] Vehicle [ID: 1] node read: Automobile_PhysicalVelocity, node size = 35, readed = 27
```

Error Clientside:

```
[22:19:50][Error] Veh node read failed 17 35 27
```
![Screenshot_121](https://user-images.githubusercontent.com/69867073/121252137-f4f93b00-c8a7-11eb-8a3c-546745910dc8.png)
![Screenshot_122](https://user-images.githubusercontent.com/69867073/121252142-f62a6800-c8a7-11eb-9fdb-5b80635ddd75.png)
![Screenshot_123](https://user-images.githubusercontent.com/69867073/121252143-f62a6800-c8a7-11eb-957e-2c35e29d78f9.png)

**Expected behavior**
Motorcycle spawns normally on the ground

**Steps to reproduce**
```
const veh = new alt.Vehicle('akuma', player.pos.x + 1, player.pos.y + 1 , player.pos.z, 0,0,0);
  veh.dimension = player.dimension;
 ```

**Comment by ThomasMarangoni** [comment]
Newest version is 4.0-dev12 und you are using 4.0-dev9

**Comment by LeonMrBonnie** [comment]
I just tried to verify this and it is caused by either an updated server or client. Works fine on newest dev.
