### ISSUE TITLE
Vehicle damage do not sync if out of display range

### ISSUE THREAD

**Issue by ifthenelse42** [altmp/altv-issues#964]
**Client/server version**
`Build #2.24, branch release`

**Current behavior**
Vehicle damage are not synchronized when out of display range.

**Expected behavior**
The damage should be synchronized as advertised in documentation.

**Steps to reproduce**
Have a player damage vehicle far from your position damage his vehicle then come to you. Vehicle will not be damaged, but for the player driving the vehicle, it will be damaged. Thus the vehicle damage is out of sync.

**Possible solution**
Allow vehicle damage sync even if out of display range (might be heavy on performances) **or** have server dispatch vehicle damage when it comes into displaying range to other clients.

**Comment by FabianTerhorst** [comment]
Hi, please add e.g. a Video to illustrate the problem.

**Comment by LeonMrBonnie** [comment]
Closed because of missing informations
