### ISSUE TITLE
[UX] External Reconnection REST API for Debug Mode

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#966]
**Suggestion**
Basically you can call a localhost REST service that will automatically reconnect your alt:V client to the last server it was connected to from outside alt:V.

**Use cases**
1. You rebuild your server code.
2. You have to restart your server to change state.
3. You can have the script automatically reconnect you when the server is ready.

**Describe the solution you'd like**
1. REST Service that you can invoke on the localhost.
2. Automatically Reconnect while Debug mode is enabled and connection is lost.

**Describe alternatives you've considered**
None; no good solutions for this at this time.

**Comment by Stuyk** [comment]
I agree; but if a websocket is too hefty for some reason then a REST service will be enough. We could just make an interval to check the status of the client and base the direction around that.

**Comment by jovanivanovic** [comment]
> I agree; but if a websocket is too hefty for some reason then a REST service will be enough. We could just make an interval to check the status of the client and base the direction around that.

WebSockets are better since it's already implemented in client but an HTTP server isn't.

**Comment by martonp96** [comment]
added in 9.0-dev1

**Comment by Stuyk** [comment]
Dummy Code:
```
import alt from 'alt-server';
import fetch from 'node-fetch';

function autoConnect() {
    fetch('http://127.0.0.1:9223/status').then(async res => {
        const body = await res.text();
        if(body == "MAIN_MENU" || body == "IN_GAME") {
            fetch('http://127.0.0.1:9223/reconnect');
        } else {
            alt.setTimeout(autoConnect, 3000);
        }
    }).catch(alt.log);
}

autoConnect();
```

**Comment by pixlcrashr** [comment]
Why adding a whole REST point? I mean, a config option for an auto-reconnect would be enough, though.

**Comment by Stuyk** [comment]
> Why adding a whole REST point? I mean, a config option for an auto-reconnect would be enough, though.

If your server needs time to boot and configure things then no it's not enough.

**Comment by pixlcrashr** [comment]
> > Why adding a whole REST point? I mean, a config option for an auto-reconnect would be enough, though.
> 
> If your server needs time to boot and configure things then no it's not enough.

That's not really an argument - I would expect the auto-reconnect functionality to probe automatically if the server is reachable, though.
A REST endpoint seems a bit overkill for the thing you want to achieve: Connecting to the server (again) after it was restarted. It is irrelevant how long the "restart process" takes, though.

In general, your problem only consists of 3 states:
* You wait until the server is reachable
* You reconnect
* You quit the game

Since a config option covers all 3 states, why would you need a REST endpoint? I don't get it.
