### ISSUE TITLE
beforeConnect - To Prevent Limbo Connections

### ISSUE THREAD

**Issue by Stuyk** [altmp/altv-issues#967]
**Suggestion**
An event like `beforeConnect` that has a list of ip, hwid, etc. of the incoming connection and you can `return false` to prevent the connection and that will allow them to continue browsing servers.

**Use cases**
* Preventing connections from banned players immediately rather than later in the codebase.
* Waiting for a database to initialize various classes, functions, etc.
* Waiting for data to come down from some external apis.
* Setting up classes, colshapes, etc. before a player joins.

**Describe the solution you'd like**
An event like `beforeConnect` that has a list of ip, hwid, etc. of the incoming connection and you can `return false` to prevent the connection and that will allow them to continue browsing servers.

**Describe alternatives you've considered**
Kicking through the playerConnect event if a boolean is true. If the client is not in debug mode they get stuck in the limbo between not being able to reconnect and not being able to rejoin without restarting their client. It's not a good solution and it needs to be something with better control.

**Comment by Stuyk** [comment]
This was discussed in an internal development channel.

**Comment by zziger** [comment]
Would be also nice if there would be any possibility to provide custom "disconnect" message to the user

**Comment by mrgharabaghi** [comment]
`Player.socialID` could be one of the main elements that `beforeConnect` event can returns.

**Comment by FabianTerhorst** [comment]
Added in next release.

**Comment by FabianTerhorst** [comment]
But the user can only go back to main menu when the server isn't using early auth.

**Comment by PavlovTM** [comment]
Wuhuuu
