### ISSUE TITLE
JS | Client | Add "SetDlcClothes" & "SetDlcProps" for Peds

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#968]
**Suggestion**
Add a method to use SetDlcCloth on JS Client to set dlc clothes on peds.

**Use cases**
Show different characters of a player as peds with the complete clothing - (character selection screen after login).

**Describe the solution you'd like**
`Alt.SetDlcClothes(pedId, component, drawable, texture, palette, dlcHash)`
`Alt.SetDlcProps(pedId, component, drawable, texture, dlcHash)`

**Describe alternatives you've considered**
No alternative yet found. Drawable Id are not very reliable for dlc clothes if you add new ones.

**Additional context**
Discussed in Discord #javascript https://discord.com/channels/371265202378899476/547079158300147725
![grafik](https://user-images.githubusercontent.com/7781906/122248570-72d0ce00-cec8-11eb-9e82-7cc9c1016d75.png)

**Comment by C0kkie** [comment]
Added in rc/4.0-rc4 for peds

clearPedProp
setPedDlcClothes
setPedDlcProp
