### ISSUE TITLE
Vehicle maxGear is offset by 256

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#971]
**Client/server version**
`4.0-dev13`

**Current behavior**
If you're using vehicle.maxGear it is offset by 256.
Cyclone & Neon as electric cars with 1 gear return 257, Jugular & Nero with 7 gears return 263

**Expected behavior**
Subtract 256 before returning the value to the client

**Steps to reproduce**
Spawn any vehicle and log alt.Player.local.vehicle.maxGear

**Context (environment)**
Not that big impact, but would be nice to don't have to subtract 256 everytime

**Possible solution**
Same as expected behaviour

**Comment by FabianTerhorst** [comment]
Fixed in next release.
