### ISSUE TITLE
Ability to get resource list from clientside and serverside

### ISSUE THREAD

**Issue by zziger** [altmp/altv-issues#975]
**Suggestion**
It would be nice to have an ability to get all loaded resources from both the clientside and serverside

**Describe the solution you'd like**
alt.getResources or alt.getResourceList

**Describe alternatives you've considered**
Listening to anyResourceStart event, but that returns only resources that are loaded after the current

**Comment by LeonMrBonnie** [comment]
```cpp
alt::Aray<alt::IResource*> alt::ICore::GetAllResources() const = 0;
alt::Aray<alt::IResource*> alt::ICore::GetAllResourcesOfType(alt::StringView type) const = 0;
```

**Comment by LeonMrBonnie** [comment]
Available in next version
