### ISSUE TITLE
CDN does not worked anymore or RC version

### ISSUE THREAD

**Issue by Doxoh** [altmp/altv-issues#976]
**Client/server version**
alt:V Server 4.0-rc1 (rc)

**Current behavior**
When connecting to the server, all resources are downloaded successfully, but then the following error message appears:
![grafik](https://user-images.githubusercontent.com/17340739/122767462-fca2e180-d2a2-11eb-92d4-ee011b335a33.png)
Even after restarting the server and deleting the cache, it did not work.

**Expected behavior**
After successfully downloading the resources, you spawn on the server.

**Steps to reproduce**
server.cfg -> useCdn: 'true' and set the correct CDN-Url

**Comment by FabianTerhorst** [comment]
Is it your own server?

**Comment by Doxoh** [comment]
yes

**Comment by Doxoh** [comment]
I forgot to write that after switching to release the connection with the CDN works without problems

**Comment by C0kkie** [comment]
Did you try to clear your cache? What url did you try to connect and what is in the server cfg?

**Comment by C0kkie** [comment]
Solved via Discord. You need to be sure the direct connect url is exactly the same, which is in the server.cfg
