### ISSUE TITLE
Player Hair style is corrupted after changing Hat

### ISSUE THREAD

**Issue by b2soft** [altmp/altv-issues#978]
**Client/server version**
`alt:V Server 4.0-dev13, branch dev`

**Current behavior**
If you set a hairstyle server-side and then set a Hat, hair style corrupts.

Apply hair style: `player.SetClothes(2, 14, 0, 2);` - works as expected
![image](https://user-images.githubusercontent.com/6034932/122821332-5d530e00-d2e5-11eb-8038-a7ecf6bd3e97.png)

Applying an empty Hat prop ``player.SetProps(0, 57, 0);`` - hair corrupts
![image](https://user-images.githubusercontent.com/6034932/122821401-78be1900-d2e5-11eb-8b37-26a071cba207.png)

**Expected behavior**
Hair style is not being corrupted

**Steps to reproduce**
1. Set Hair style `player.SetClothes(2, 14, 0, 2);`
2. Apply null Hat prop, for femal will be `player.SetProps(0, 57, 0);`

**Context (environment)**
Trying to set clothes and props serverside

**Possible solution**
Use natives instead

**Comment by FabianTerhorst** [comment]
use clear props instead of using the transparent prop.

**Comment by b2soft** [comment]
> use clear props instead of using the transparent prop.
