### ISSUE TITLE
Clientside "spawned" event

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-issues#979]
**Suggestion**
As `gameEntityCreate` doesn't triggers for the local player, some event like `spawned` would be awesome to have.

**Use cases**
Some ped config flags depend on being set again after the player has been respawned (revive or whatever). With the `spawned` event there would be a good way to set up those flags again

**Describe the solution you'd like**
Add an `spawned` event

**Describe alternatives you've considered**
Maybe `gameEntityCreate` could also trigger for the local player, so it could be catched with an `if (entity == alt.Player.local)`

**Additional context**
Saw a lot of workarounds by setting those flags in intervals or do custom emits on respawn, but I think some `alt.on("spawned", (void))` would be way cleaner

**Comment by YannBCF** [comment]
Since you spawn the player yourself you can emit an event to the client to tell him that the has spawn

**Comment by deluvas1911** [comment]
As already written in **additional context** this is in my opinion just an workaround.

Imaging changing the player model before the spawn or whatever. There could be possibilites where the event is coming through before the respawn is completed. Getting an event by alt:V after the player has been spawned is ways cleaner.

**Comment by juztim** [comment]
Agreed, could be useful

**Comment by LeonMrBonnie** [comment]
Available in next version
