### ISSUE TITLE
Client crashes when trying to access the blip variable

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#980]
**Client/server version**
`Build #4.0-rc1, branch rc`

**Current behavior**
The client crashes if you create a blip (PointBlip/RadiusBlip/AreaBlip) and try to access the blip variable _**after starting the resource**_ (try to get `blip.name` for example)

**Expected behavior**
no crash pls

**Steps to reproduce**
```js
alt.log('run blip timeout...')
alt.setTimeout(() => {
  const blip = new alt.PointBlip(0, 0, 0)

  alt.log('get blip pos...')
  alt.nextTick(() => {
    const pos = blip.pos // no crash

    alt.log('get blip name...')
    alt.nextTick(() => {
      const name = blip.name // crash
      // const str = '' + blip <-- crash too
    })
  })
}, 500)
```

**Comment by LeonMrBonnie** [comment]
Any crashdump?

**Comment by xxshady** [comment]
[altv_4.0-rc1_Social Club_0x28c32e6c3_22-06-2021_21-07-29.zip](https://github.com/altmp/altv-issues/files/6696594/altv_4.0-rc1_Social.Club_0x28c32e6c3_22-06-2021_21-07-29.zip)

**Comment by Basarus** [comment]
When you make a mistake in any of the values of the blip, the client crashes (the card breaks, the client breaks, and so on). It's just that you need to be more careful with this and check for what you assign.

**Comment by xxshady** [comment]
confirmed on `dev/6.0-dev5`
![image](https://user-images.githubusercontent.com/54737754/127779507-c6cd06ae-df65-4abd-a6c4-a77dc7dc4251.png)

**Comment by DasNiels** [comment]
Can confirm this aswell. Doing simply this in a client-script will instantly crash the client on connect:

`
import * as alt from 'alt-client';

const blip = new alt.PointBlip( 0, 0, 0 );
blip.name = "test";
alt.log( `blipname: ${ blip.name }` );
`

**Comment by martonp96** [comment]
fixed in rc
