### ISSUE TITLE
Dont force wss for localhost

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-issues#981]
**Suggestion**
Allow localhost connections via ws and not forced wss

**Use cases**
Voiceplugins

**Comment by Arochka** [comment]
I would like to say more, just don't force wss, we can already bypass this by using CEF, just let us use the WebSocketClient the way we want

**Comment by C0kkie** [comment]
Added in rc/4.0-rc4 if you use 127.0.0.1 instead of localhost
