### ISSUE TITLE
setFollowPedCamViewMode native crash the client on rc

### ISSUE THREAD

**Issue by Arochka** [altmp/altv-issues#985]
**Client/server version**

`rc/4.0-rc1`

**Current behavior**
Calling this native with these parameters crash the client:
 `native.setFollowPedCamViewMode(4)`

**Expected behavior**
Not crashing the game, it work on release actually

**Steps to reproduce**
Just call: `native.setFollowPedCamViewMode(4)`

**Context (environment)**
I'm forcing first person when aiming with a weapon

**Comment by LeonMrBonnie** [comment]
Can't reproduce on dev.

**Comment by Arochka** [comment]
[test.zip](https://github.com/altmp/altv-issues/files/6720462/test.zip)
You can use this resource

**Comment by tastydev** [comment]
can´t be reproduced even if i copy paste ur clientside code @Arochka the cause has to be somethign different

**Comment by Arochka** [comment]
Maybe crashdump can help investigate ? Cause same resource on release is working perfectly

**Comment by LeonMrBonnie** [comment]
You can upload the crashdump here and we will take a look

**Comment by Arochka** [comment]
[altv_4.0-rc1_EGS_0x1654401_26-06-2021_19-44-13.zip](https://github.com/altmp/altv-issues/files/6721882/altv_4.0-rc1_EGS_0x1654401_26-06-2021_19-44-13.zip)
Here is it

**Comment by LeonMrBonnie** [comment]
The crash is in GTA and not in alt:V

**Comment by Arochka** [comment]
> The crash is in GTA and not in alt:V

Then how did you explain the same resource is working on release and not in RC ?

Is pretty easy to try, the resource is forcing first person when you aim with a gun, and give you a gun at spawn

**Comment by martonp96** [comment]
@Arochka do you have anything related to traffic lights? map mods or something

**Comment by Arochka** [comment]
I'm only using Reshade + NVE

**Comment by martonp96** [comment]
can you please try without those mods?

**Comment by tastydev** [comment]
> > The crash is in GTA and not in alt:V
> 
> Then how did you explain the same resource is working on release and not in RC ?
> 
> Is pretty easy to try, the resource is forcing first person when you aim with a gun, and give you a gun at spawn
As i posted earlier this native works and the crash is definitely not related to this firstperson/gun script. It has to be something related to ur local environment i. e. mods or other things in ur gamemode.

**Comment by Arochka** [comment]
Seem to be related to NVE or reshade, no crash without them
