### ISSUE TITLE
Show connect fail/disconnect message

### ISSUE THREAD

**Issue by 7Hazard** [altmp/altv-issues#99]
Show a message or popup when attempting to connects fails
For example
https://i.imgur.com/NBYb8pf.png

Same thing for when disconnected/timed out

Currently only shows in console

**Comment by vadzz-dev** [comment]
Done for connection errors

**Comment by Lhoerion** [comment]
Is it already fixed and are the labels properly assigned?

**Comment by Lhoerion** [comment]
~Added~/fixed/~changed~ in build [#1230](https://discord.com/channels/371265202378899476/528297438348574741/716467109391106069)
