### ISSUE TITLE
Start Menu shortcut on client install

### ISSUE THREAD

**Issue by ZackaryH8** [altmp/altv-issues#992]
**Suggestion**
On install alt:V client should ask user if they want to create a start menu shortcut

**Use cases**
I don't have desktop icons enabled

**Describe the solution you'd like**
Create a shortcut on install

**Describe alternatives you've considered**
Making my own shortcut

**Additional context**
![image](https://user-images.githubusercontent.com/40175773/124334572-62d71080-db8f-11eb-9c5e-4c5eef4443dc.png)

**Comment by LeonMrBonnie** [comment]
Available in next version
