### ISSUE TITLE
Possibility for branch selection in altv connect protocol

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#993]
**Suggestion**
It would be a "nice to have" feature if you can choose in altv connect protocol the correct branch for the client to start with.

**Use cases**
We have a custom launcher with altv quick connect links to our dev / rc / stable server. 
When the user choose to join the dev server, he can click the link but in most cases his release client will start and will try to connect to the server.

**Describe the solution you'd like**
Every branch client could use another protocol.
Release: `altv://connect/127.0.0.1:7788/`
Release Candidat: `altv-rc://connect/127.0.0.1:7777/`
Development: `altv-dev://connect/127.0.0.1:7777/`

**Describe alternatives you've considered**
Don't use quick connect protocol.

**Additional context**
I know that the enhancement is just a nice to have feature and this would affect <1% of the users.
Just nice to have.

**Comment by FabianTerhorst** [comment]
We don't want to add features that help custom launchers since we usually don't want people to use them. So i don't think that will be added.
