### ISSUE TITLE
streamEnded event on new Audio api spams after stream actually ended

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#995]
**Client/server version**
`#4.0-dev15, branch dev`

**Current behavior**
`The "streamEnded" events spams after the stream ended`

**Expected behavior**
`it should fire only once`

**Steps to reproduce**
`listen to the event`

**Context (environment)**
`I've tried to loop an audio but it doesnt work properly, so i've tried it with the event as workaround.`
```js
audio.on('streamEnded', () => {
    alt.log('startagain')
    audio.play();
});
```

**Comment by Arochka** [comment]
![image](https://user-images.githubusercontent.com/34453212/124518964-3b2eb500-dde8-11eb-825d-5e70c8d2ac40.png)

I can confirm the issue on dev15

**Comment by C0kkie** [comment]
Fixed in a internal version already
