### ISSUE TITLE
client side gear setter only change the value

### ISSUE THREAD

**Issue by MalteCr** [altmp/altv-issues#996]
**Client**
`#4.0-dev15, branch dev`

**Current behavior**
`the gear setter only changes the value but not the actual gear of the vehicle.`

**Expected behavior**
`it should set the gear and the vehicle should shift down or up to the given value`

**Steps to reproduce**
`set the gear to 1 in an everyTick and go for a ride`

**Comment by Arochka** [comment]
I can confirm, the vehicle gear is unaffected by the setter

**Comment by C0kkie** [comment]
Fixed in next dev
