### ISSUE TITLE
Client player.model getter returns a new value with a delay

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-issues#999]
**Client/server version**
`dev/4.0-dev16` and `rc/4.0-rc2` and `release/2.24`

**Current behavior**
Visually, the player's model has already changed, but `player.model` returns the old model and only after a maximum of ~500 ms (on my machine) returns the correct model, unlike the `native.getEntityModel(player.scriptID)`, which returns the correct model immediately after the visual change

**Expected behavior**
The `player.model` getter should return the new value immediately, at least like the `native.getEntityModel`

**Steps to reproduce**
reproduction js resource (includes client console command "model" for testing): https://github.com/xxshady/player-model-issue

![image](https://user-images.githubusercontent.com/54737754/125165768-1ac47900-e1a1-11eb-9a4d-683a77be8d90.png)

**Comment by FabianTerhorst** [comment]
We currently use a cached model value for performance reasons. We will look into improving the time it takes until it contains the new value in the future.

**Comment by C0kkie** [comment]
Fixed in next dev
